{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighway"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPManeuverType@CPManeuverTypeChangeHighway",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "changeHighway"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPManeuverTypeChangeHighway"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CPManeuverType.changeHighway"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "changeHighway"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType": {
      "abstract": [
        {
          "text": "Values that describe types of navigation maneuvers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arriveAtDestination"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeArriveAtDestination"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.arriveAtDestination",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/arriveatdestination"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arriveAtDestinationLeft"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeArriveAtDestinationLeft"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.arriveAtDestinationLeft",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/arriveatdestinationleft"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arriveAtDestinationRight"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeArriveAtDestinationRight"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.arriveAtDestinationRight",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/arriveatdestinationright"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfDirections": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arriveEndOfDirections"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfDirections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeArriveEndOfDirections"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.arriveEndOfDirections",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/arriveendofdirections"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfNavigation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arriveEndOfNavigation"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeArriveEndOfNavigation"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.arriveEndOfNavigation",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/arriveendofnavigation"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeFerry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeFerry"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeFerry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeChangeFerry"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.changeFerry",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/changeferry"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighway": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHighway"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighway",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeChangeHighway"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.changeHighway",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/changehighway"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHighwayLeft"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeChangeHighwayLeft"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.changeHighwayLeft",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/changehighwayleft"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHighwayRight"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeChangeHighwayRight"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.changeHighwayRight",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/changehighwayright"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enterRoundabout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterRoundabout"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enterRoundabout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeEnterRoundabout"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.enterRoundabout",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/enterroundabout"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enter_Ferry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enter_Ferry"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enter_Ferry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeEnter_Ferry"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.enter_Ferry",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/enter_ferry"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitFerry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exitFerry"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitFerry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeExitFerry"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.exitFerry",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/exitferry"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitRoundabout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exitRoundabout"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitRoundabout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeExitRoundabout"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.exitRoundabout",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/exitroundabout"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/followRoad": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "followRoad"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/followRoad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeFollowRoad"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.followRoad",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/followroad"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highwayOffRampLeft"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeHighwayOffRampLeft"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.highwayOffRampLeft",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/highwayofframpleft"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highwayOffRampRight"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverTypeHighwayOffRampRight"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType.highwayOffRampRight",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype/highwayofframpright"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Maneuver-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestination",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationLeft",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationRight",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfDirections",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfNavigation",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeFerry",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayLeft",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayRight",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enterRoundabout",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enter_Ferry",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitFerry",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitRoundabout",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/followRoad",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampLeft",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampRight"
      ],
      "title": "Maneuver types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPManeuverTypeChangeHighway"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeChangeHighway"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Maneuver-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestination",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationLeft",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveAtDestinationRight",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfDirections",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/arriveEndOfNavigation",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeFerry",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayLeft",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/changeHighwayRight",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enterRoundabout",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/enter_Ferry",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitFerry",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/exitRoundabout",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/followRoad",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampLeft",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType/highwayOffRampRight"
              ],
              "title": "Maneuver types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CPManeuverTypeChangeHighway"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighway/title",
          "value": "CPManeuverTypeChangeHighway"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighway/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeChangeHighway"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveEndOfNavigation/title",
          "value": "CPManeuverTypeArriveEndOfNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveEndOfNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeArriveEndOfNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestinationLeft/title",
          "value": "CPManeuverTypeArriveAtDestinationLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestinationLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeArriveAtDestinationLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1highwayOffRampLeft/title",
          "value": "CPManeuverTypeHighwayOffRampLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1highwayOffRampLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeHighwayOffRampLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeFerry/title",
          "value": "CPManeuverTypeChangeFerry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeFerry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeChangeFerry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1exitFerry/title",
          "value": "CPManeuverTypeExitFerry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1exitFerry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeExitFerry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestination/title",
          "value": "CPManeuverTypeArriveAtDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeArriveAtDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/title",
          "value": "CPManeuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveEndOfDirections/title",
          "value": "CPManeuverTypeArriveEndOfDirections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveEndOfDirections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeArriveEndOfDirections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1followRoad/title",
          "value": "CPManeuverTypeFollowRoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1followRoad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeFollowRoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1enterRoundabout/title",
          "value": "CPManeuverTypeEnterRoundabout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1enterRoundabout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeEnterRoundabout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighwayLeft/title",
          "value": "CPManeuverTypeChangeHighwayLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighwayLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeChangeHighwayLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1highwayOffRampRight/title",
          "value": "CPManeuverTypeHighwayOffRampRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1highwayOffRampRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeHighwayOffRampRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighwayRight/title",
          "value": "CPManeuverTypeChangeHighwayRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1changeHighwayRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeChangeHighwayRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestinationRight/title",
          "value": "CPManeuverTypeArriveAtDestinationRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1arriveAtDestinationRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeArriveAtDestinationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1exitRoundabout/title",
          "value": "CPManeuverTypeExitRoundabout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1exitRoundabout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeExitRoundabout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1enter_Ferry/title",
          "value": "CPManeuverTypeEnter_Ferry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType~1enter_Ferry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverTypeEnter_Ferry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaneuvertype/changehighway"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaneuvertype/changehighway"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
