{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidDisplayPortCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PGResumeErrorCode@PGResumeErrorCodeInvalidDisplayPortCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidDisplayPortCount"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGResumeErrorCodeInvalidDisplayPortCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PGResumeErrorCode.invalidDisplayPortCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidDisplayPortCount"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode": {
      "abstract": [
        {
          "text": "Error codes for suspend-resume actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidDisplayPortCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDisplayPortCount"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidDisplayPortCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeInvalidDisplayPortCount"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.invalidDisplayPortCount",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invaliddisplayportcount"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGResumeErrorCodeInvalidDisplayPortCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidDisplayPortCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PGResumeErrorCodeInvalidDisplayPortCount"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/title",
          "value": "PGResumeErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidDisplayPortCount/title",
          "value": "PGResumeErrorCodeInvalidDisplayPortCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidDisplayPortCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidDisplayPortCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invaliddisplayportcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invaliddisplayportcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
