{
  "abstract": [
    {
      "text": "The content of the suspend state or the guest memory isn’t valid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PGResumeErrorCode@PGResumeErrorCodeInvalidContent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidContent"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGResumeErrorCodeInvalidContent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PGResumeErrorCode.invalidContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidContent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode": {
      "abstract": [
        {
          "text": "Error codes for suspend-resume actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/incompatibleDevice": {
      "abstract": [
        {
          "text": "The resume device is missing capabilities that the suspended device provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleDevice"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/incompatibleDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeIncompatibleDevice"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.incompatibleDevice",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/incompatibledevice"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/internalFault": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFault"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/internalFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeInternalFault"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.internalFault",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/internalfault"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidContent": {
      "abstract": [
        {
          "text": "The content of the suspend state or the guest memory isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidContent"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeInvalidContent"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.invalidContent",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invalidcontent"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidGuestVersion": {
      "abstract": [
        {
          "text": "The guest version is incompatible with this framework version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidGuestVersion"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidGuestVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeInvalidGuestVersion"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.invalidGuestVersion",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invalidguestversion"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidSuspendStateVersion": {
      "abstract": [
        {
          "text": "The suspend state version is incompatible with this framework version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSuspendStateVersion"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidSuspendStateVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCodeInvalidSuspendStateVersion"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode.invalidSuspendStateVersion",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invalidsuspendstateversion"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/incompatibleDevice",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/internalFault",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidGuestVersion",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidSuspendStateVersion"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGResumeErrorCodeInvalidContent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/incompatibleDevice",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/internalFault",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidGuestVersion",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode/invalidSuspendStateVersion"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PGResumeErrorCodeInvalidContent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1incompatibleDevice/title",
          "value": "PGResumeErrorCodeIncompatibleDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1incompatibleDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeIncompatibleDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1internalFault/title",
          "value": "PGResumeErrorCodeInternalFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1internalFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInternalFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidSuspendStateVersion/title",
          "value": "PGResumeErrorCodeInvalidSuspendStateVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidSuspendStateVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidSuspendStateVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidGuestVersion/title",
          "value": "PGResumeErrorCodeInvalidGuestVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidGuestVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidGuestVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidContent/title",
          "value": "PGResumeErrorCodeInvalidContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode~1invalidContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCodeInvalidContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/title",
          "value": "PGResumeErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invalidcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgresumeerrorcode/invalidcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
