{
  "abstract": [
    {
      "text": "Interpolate values along the horizontal axis, which involves the device facing left or right of the user’s viewpoint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect",
        "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongHorizontalAxis"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIInterpolatingMotionEffectType@UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tiltAlongHorizontalAxis"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIInterpolatingMotionEffect.EffectType.tiltAlongHorizontalAxis"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tiltAlongHorizontalAxis"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect": {
      "abstract": [
        {
          "text": "An object that maps the horizontal or vertical tilt of a device to values that you specify so that UIKit can apply those values to your views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffect"
        }
      ],
      "role": "symbol",
      "title": "UIInterpolatingMotionEffect",
      "type": "topic",
      "url": "/documentation/uikit/uiinterpolatingmotioneffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType": {
      "abstract": [
        {
          "text": "The axis to use when interpolating values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EffectType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EffectType"
        }
      ],
      "role": "symbol",
      "title": "UIInterpolatingMotionEffect.EffectType",
      "type": "topic",
      "url": "/documentation/uikit/uiinterpolatingmotioneffect/effecttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongHorizontalAxis": {
      "abstract": [
        {
          "text": "Interpolate values along the horizontal axis, which involves the device facing left or right of the user’s viewpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltAlongHorizontalAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongHorizontalAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
        }
      ],
      "role": "symbol",
      "title": "UIInterpolatingMotionEffect.EffectType.tiltAlongHorizontalAxis",
      "type": "topic",
      "url": "/documentation/uikit/uiinterpolatingmotioneffect/effecttype/tiltalonghorizontalaxis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongVerticalAxis": {
      "abstract": [
        {
          "text": "Interpolate values along the vertical axis, which involves the device facing above or below the user’s viewpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tiltAlongVerticalAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongVerticalAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffectTypeTiltAlongVerticalAxis"
        }
      ],
      "role": "symbol",
      "title": "UIInterpolatingMotionEffect.EffectType.tiltAlongVerticalAxis",
      "type": "topic",
      "url": "/documentation/uikit/uiinterpolatingmotioneffect/effecttype/tiltalongverticalaxis"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongVerticalAxis"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect/EffectType/tiltAlongVerticalAxis"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/title",
          "value": "UIInterpolatingMotionEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType~1tiltAlongHorizontalAxis/title",
          "value": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType~1tiltAlongHorizontalAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffectTypeTiltAlongHorizontalAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType~1tiltAlongVerticalAxis/title",
          "value": "UIInterpolatingMotionEffectTypeTiltAlongVerticalAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType~1tiltAlongVerticalAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffectTypeTiltAlongVerticalAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType/title",
          "value": "UIInterpolatingMotionEffectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect~1EffectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffectType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiinterpolatingmotioneffect/effecttype/tiltalonghorizontalaxis"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiinterpolatingmotioneffect/effecttype/tiltalonghorizontalaxis"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
