{
  "abstract": [
    {
      "text": "Reader session and tag error codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCReaderError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NFCReaderError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors associated with Core NFC APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NFCErrorDomain",
      "type": "topic",
      "url": "/documentation/corenfc/nfcerrordomain"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable": {
      "abstract": [
        {
          "text": "The NDEF tag isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagNotWritable"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagNotWritable"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagNotWritable",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagnotwritable"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall": {
      "abstract": [
        {
          "text": "The NDEF tag memory size is too small to store the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagSizeTooSmall"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagSizeTooSmall",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagsizetoosmall"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure": {
      "abstract": [
        {
          "text": "The reader session failed to update the NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagUpdateFailure"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagUpdateFailure"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagUpdateFailure",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagupdatefailure"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage": {
      "abstract": [
        {
          "text": "The NDEF tag doesn’t contain an NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorZeroLengthMessage"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorZeroLengthMessage"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorZeroLengthMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrorzerolengthmessage"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter": {
      "abstract": [
        {
          "text": "An input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameter"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorInvalidParameter",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorinvalidparameter"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength": {
      "abstract": [
        {
          "text": "The length of an input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameterLength"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorInvalidParameterLength"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorInvalidParameterLength",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorinvalidparameterlength"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound": {
      "abstract": [
        {
          "text": "A parameter value is outside of the acceptable boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorParameterOutOfBound"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorParameterOutOfBound"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorParameterOutOfBound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorparameteroutofbound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled": {
      "abstract": [
        {
          "text": "The NFC wireless radio on the device is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorRadioDisabled"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorRadioDisabled"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorRadioDisabled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorradiodisabled"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation": {
      "abstract": [
        {
          "text": "A security violation associated with the reader session has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorSecurityViolation"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorSecurityViolation"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorSecurityViolation",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorsecurityviolation"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature": {
      "abstract": [
        {
          "text": "The reader session does not support this feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorUnsupportedFeature"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorUnsupportedFeature"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorUnsupportedFeature",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorunsupportedfeature"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead": {
      "abstract": [
        {
          "text": "The first NDEF tag read by this session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorFirstNDEFTagRead"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorFirstNDEFTagRead",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorfirstndeftagread"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly": {
      "abstract": [
        {
          "text": "The reader session terminated unexpectedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTerminatedUnexpectedly"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessionterminatedunexpectedly"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout": {
      "abstract": [
        {
          "text": "The reader session timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTimeout"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSessionTimeout",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessiontimeout"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy": {
      "abstract": [
        {
          "text": "The reader session failed because the system is busy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSystemIsBusy"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSystemIsBusy"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSystemIsBusy",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsystemisbusy"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled": {
      "abstract": [
        {
          "text": "The user canceled the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorUserCanceled"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorUserCanceled"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorUserCanceled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorusercanceled"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong": {
      "abstract": [
        {
          "text": "The packet length exceeds the limit supported by the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorPacketTooLong"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorPacketTooLong"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorPacketTooLong",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorpackettoolong"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded": {
      "abstract": [
        {
          "text": "Too many retries have occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorRetryExceeded"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorRetryExceeded"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorRetryExceeded",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorretryexceeded"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated": {
      "abstract": [
        {
          "text": "The reader session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorSessionInvalidated"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorSessionInvalidated"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorSessionInvalidated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorsessioninvalidated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost": {
      "abstract": [
        {
          "text": "The reader lost the connection to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagConnectionLost"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagConnectionLost"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagConnectionLost",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagconnectionlost"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected": {
      "abstract": [
        {
          "text": "The tag isn’t in the connected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagNotConnected"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagNotConnected"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagNotConnected",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagnotconnected"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError": {
      "abstract": [
        {
          "text": "The tag has responded with an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagResponseError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagResponseError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagResponseError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagresponseerror"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters": {
      "abstract": [
        {
          "text": "The tag has been configured with invalid parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tagCommandConfigurationErrorInvalidParameters"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagCommandConfigurationErrorInvalidParameters"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.tagCommandConfigurationErrorInvalidParameters",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/tagcommandconfigurationerrorinvalidparameters"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey": {
      "abstract": [
        {
          "text": "A user-information dictionary key that indicates an invalid received response packet length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        }
      ],
      "role": "symbol",
      "title": "NFCTagResponseUnexpectedLengthErrorKey",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagresponseunexpectedlengtherrorkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Session-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled"
      ],
      "title": "Session Errors"
    },
    {
      "anchor": "NDEF-Tag-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage"
      ],
      "title": "NDEF Tag Errors"
    },
    {
      "anchor": "Transceive-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong"
      ],
      "title": "Transceive Errors"
    },
    {
      "anchor": "Tag-Command-Configuration-Error",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters"
      ],
      "title": "Tag Command Configuration Error"
    },
    {
      "anchor": "Other-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation"
      ],
      "title": "Other Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Session-Errors",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled"
              ],
              "title": "Session Errors"
            },
            {
              "anchor": "NDEF-Tag-Errors",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage"
              ],
              "title": "NDEF Tag Errors"
            },
            {
              "anchor": "Transceive-Errors",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong"
              ],
              "title": "Transceive Errors"
            },
            {
              "anchor": "Tag-Command-Configuration-Error",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/tagCommandConfigurationErrorInvalidParameters"
              ],
              "title": "Tag Command Configuration Error"
            },
            {
              "anchor": "Other-Errors",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation"
              ],
              "title": "Other Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCReaderError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorParameterOutOfBound/title",
          "value": "NFCReaderErrorParameterOutOfBound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorParameterOutOfBound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorParameterOutOfBound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagSizeTooSmall/title",
          "value": "NFCNdefReaderSessionErrorTagSizeTooSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagSizeTooSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagNotConnected/title",
          "value": "NFCReaderTransceiveErrorTagNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagNotConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameter/title",
          "value": "NFCReaderErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameterLength/title",
          "value": "NFCReaderErrorInvalidParameterLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameterLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorInvalidParameterLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorSessionInvalidated/title",
          "value": "NFCReaderTransceiveErrorSessionInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorSessionInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorSessionInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagResponseError/title",
          "value": "NFCReaderTransceiveErrorTagResponseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagResponseError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagResponseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/title",
          "value": "NFCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorZeroLengthMessage/title",
          "value": "NFCNdefReaderSessionErrorZeroLengthMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorZeroLengthMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorZeroLengthMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorUserCanceled/title",
          "value": "NFCReaderSessionInvalidationErrorUserCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorUserCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorUserCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagNotWritable/title",
          "value": "NFCNdefReaderSessionErrorTagNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorPacketTooLong/title",
          "value": "NFCReaderTransceiveErrorPacketTooLong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorPacketTooLong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorPacketTooLong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTerminatedUnexpectedly/title",
          "value": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTerminatedUnexpectedly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagConnectionLost/title",
          "value": "NFCReaderTransceiveErrorTagConnectionLost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagConnectionLost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagConnectionLost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTimeout/title",
          "value": "NFCReaderSessionInvalidationErrorSessionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagUpdateFailure/title",
          "value": "NFCNdefReaderSessionErrorTagUpdateFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagUpdateFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagUpdateFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorSecurityViolation/title",
          "value": "NFCReaderErrorSecurityViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorSecurityViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorSecurityViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorFirstNDEFTagRead/title",
          "value": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorFirstNDEFTagRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorRetryExceeded/title",
          "value": "NFCReaderTransceiveErrorRetryExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorRetryExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorRetryExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSystemIsBusy/title",
          "value": "NFCReaderSessionInvalidationErrorSystemIsBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSystemIsBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSystemIsBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1tagCommandConfigurationErrorInvalidParameters/title",
          "value": "NFCTagCommandConfigurationErrorInvalidParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1tagCommandConfigurationErrorInvalidParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagCommandConfigurationErrorInvalidParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/title",
          "value": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagResponseUnexpectedLengthErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorUnsupportedFeature/title",
          "value": "NFCReaderErrorUnsupportedFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorUnsupportedFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorUnsupportedFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorRadioDisabled/title",
          "value": "NFCReaderErrorRadioDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorRadioDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorRadioDisabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
