{
  "abstract": [
    {
      "text": "Constants that specify the date and time elements displayed by the picker.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSDatePickerElementFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ElementFlags"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ElementFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSDatePicker.ElementFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ElementFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can combine these constants using the C bitwise ",
              "type": "text"
            },
            {
              "code": "OR",
              "type": "codeVoice"
            },
            {
              "text": " operator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker": {
      "abstract": [
        {
          "text": "A display of a calendar date with controls for editing the date value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDatePicker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePicker"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags": {
      "abstract": [
        {
          "text": "Constants that specify the date and time elements displayed by the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker.ElementFlags",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "era"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagEra"
        }
      ],
      "role": "symbol",
      "title": "era",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/era"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagHourMinute"
        }
      ],
      "role": "symbol",
      "title": "hourMinute",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/hourminute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourMinuteSecond"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagHourMinuteSecond"
        }
      ],
      "role": "symbol",
      "title": "hourMinuteSecond",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/hourminutesecond"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagTimeZone"
        }
      ],
      "role": "symbol",
      "title": "timeZone",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/timezone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearMonth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagYearMonth"
        }
      ],
      "role": "symbol",
      "title": "yearMonth",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/yearmonth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearMonthDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagYearMonthDay"
        }
      ],
      "role": "symbol",
      "title": "yearMonthDay",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/yearmonthday"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style": {
      "abstract": [
        {
          "text": "Constants that define the visual appearance of the date picker cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/style"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/backgroundColor": {
      "abstract": [
        {
          "text": "The date picker’s background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/backgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerElements": {
      "abstract": [
        {
          "text": "A bitmask that indicates which visual elements of the date picker are currently shown, and which won’t be usable because they are hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datePickerElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "datePickerElements"
        }
      ],
      "role": "symbol",
      "title": "datePickerElements",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/datepickerelements"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerStyle": {
      "abstract": [
        {
          "text": "The date picker’s style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datePickerStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerStyle",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "datePickerStyle"
        }
      ],
      "role": "symbol",
      "title": "datePickerStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/datepickerstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/delegate": {
      "abstract": [
        {
          "text": "A delegate for the date picker’s cell",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDatePickerCellDelegate",
          "text": "NSDatePickerCellDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/delegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/drawsBackground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the date picker draws the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawsBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/drawsBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawsBackground"
        }
      ],
      "role": "symbol",
      "title": "drawsBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/drawsbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBezeled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the date picker draws a bezeled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBezeled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBezeled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bezeled"
        }
      ],
      "role": "symbol",
      "title": "isBezeled",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/isbezeled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBordered": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the date picker has a plain border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBordered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBordered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bordered"
        }
      ],
      "role": "symbol",
      "title": "isBordered",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/isbordered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/presentsCalendarOverlay": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to present a graphical calendar overlay when editing a calendar element within a text-field style date picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentsCalendarOverlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/presentsCalendarOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentsCalendarOverlay"
        }
      ],
      "role": "symbol",
      "title": "presentsCalendarOverlay",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/presentscalendaroverlay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/textColor": {
      "abstract": [
        {
          "text": "The date picker’s text color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/textColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textColor"
        }
      ],
      "role": "symbol",
      "title": "textColor",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/textcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the era of the date, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEraDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEraDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nseradatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the hour and minute elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHourMinuteDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHourMinuteDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nshourminutedatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the hour, minute and second elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHourMinuteSecondDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHourMinuteSecondDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nshourminuteseconddatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTimeZoneDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTimeZoneDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nstimezonedatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the year and month elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSYearMonthDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSYearMonthDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsyearmonthdatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the year, month and day elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSYearMonthDayDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSYearMonthDayDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsyearmonthdaydatepickerelementflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Date-Pickers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBezeled",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBordered",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/backgroundColor",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/drawsBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/textColor",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/presentsCalendarOverlay",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/delegate",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerElements",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style"
      ],
      "title": "Configuring Date Pickers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDatePickerElementFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag",
                "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag",
                "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag",
                "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag",
                "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag",
                "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Date-Pickers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBezeled",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/isBordered",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/backgroundColor",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/drawsBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/textColor",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/presentsCalendarOverlay",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/delegate",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/datePickerElements",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style"
              ],
              "title": "Configuring Date Pickers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDatePickerElementFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1textColor/title",
          "value": "textColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1textColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinute/title",
          "value": "NSDatePickerElementFlagHourMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagHourMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1datePickerStyle/title",
          "value": "datePickerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1datePickerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "datePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/title",
          "value": "NSDatePickerElementFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1isBordered/title",
          "value": "bordered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1isBordered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bordered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonth/title",
          "value": "NSDatePickerElementFlagYearMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagYearMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/title",
          "value": "NSDatePicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1presentsCalendarOverlay/title",
          "value": "presentsCalendarOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1presentsCalendarOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentsCalendarOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1isBezeled/title",
          "value": "bezeled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1isBezeled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bezeled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/title",
          "value": "NSDatePickerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1era/title",
          "value": "NSDatePickerElementFlagEra"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1era/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagEra"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonthDay/title",
          "value": "NSDatePickerElementFlagYearMonthDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonthDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagYearMonthDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1timeZone/title",
          "value": "NSDatePickerElementFlagTimeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1timeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagTimeZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1datePickerElements/title",
          "value": "datePickerElements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1datePickerElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "datePickerElements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1drawsBackground/title",
          "value": "drawsBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1drawsBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawsBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinuteSecond/title",
          "value": "NSDatePickerElementFlagHourMinuteSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinuteSecond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagHourMinuteSecond"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdatepicker/elementflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdatepicker/elementflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
