{"abstract":[{"text":"The object does not exist.","type":"text"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataOffsetInvalid","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectCouldNotBeRead","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataEmpty","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code"],"anchor":"Error-Codes","title":"Error Codes"}],"sections":[],"identifier":{"url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDoesNotExist","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/imagecapturecore/icreturnobjecterror/codeobjectdoesnotexist"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"property","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codeObjectDoesNotExist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ICReturnObjectError","preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@ICReturnObjectErrorCode","kind":"typeIdentifier"}],"title":"codeObjectDoesNotExist","roleHeading":"Type Property","externalID":"s:SC23ICReturnObjectErrorCodeLeV04codeB12DoesNotExistSoAAVvpZ","modules":[{"name":"ImageCaptureCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeObjectDoesNotExist"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError","kind":"typeIdentifier","text":"ICReturnObjectError","preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code","kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@ICReturnObjectErrorCode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDoesNotExist":{"kind":"symbol","url":"/documentation/imagecapturecore/icreturnobjecterror/codeobjectdoesnotexist","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDoesNotExist","title":"codeObjectDoesNotExist","abstract":[{"text":"The object does not exist.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeObjectDoesNotExist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ICReturnObjectError","preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@ICReturnObjectErrorCode"}],"role":"symbol","type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataEmpty":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeObjectDataEmpty"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV","kind":"typeIdentifier","text":"ICReturnObjectError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@ICReturnObjectErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataEmpty","url":"/documentation/imagecapturecore/icreturnobjecterror/codeobjectdataempty","abstract":[{"type":"text","text":"The object data is empty."}],"role":"symbol","title":"codeObjectDataEmpty","kind":"symbol","type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code":{"kind":"symbol","url":"/documentation/imagecapturecore/icreturnobjecterror/code","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code","title":"ICReturnObjectError.Code","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ICReturnObjectError"}],"navigatorTitle":[{"kind":"identifier","text":"ICReturnObjectError"}],"abstract":[{"text":"An object error returned from ImageCaptureCore.","type":"text"}],"type":"topic","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError","title":"ICReturnObjectError","url":"/documentation/imagecapturecore/icreturnobjecterror","role":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataOffsetInvalid":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeObjectDataOffsetInvalid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV","kind":"typeIdentifier","text":"ICReturnObjectError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@ICReturnObjectErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectDataOffsetInvalid","url":"/documentation/imagecapturecore/icreturnobjecterror/codeobjectdataoffsetinvalid","abstract":[{"type":"text","text":"The object data offset is invalid."}],"role":"symbol","title":"codeObjectDataOffsetInvalid","kind":"symbol","type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectCouldNotBeRead":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeObjectCouldNotBeRead"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC23ICReturnObjectErrorCodeLeV","kind":"typeIdentifier","text":"ICReturnObjectError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@ICReturnObjectErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/codeObjectCouldNotBeRead","url":"/documentation/imagecapturecore/icreturnobjecterror/codeobjectcouldnotberead","abstract":[{"type":"text","text":"The object could not be read."}],"role":"symbol","title":"codeObjectCouldNotBeRead","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"ICReturnObjectErrorCode","op":"replace","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/title"},{"value":[{"text":"ICReturnObjectErrorCode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ICReturnObjectErrorCode"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}