{
  "abstract": [
    {
      "text": "Creates a new coordinate with an absolute offset in points from the original coordinate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCUICoordinate(im)coordinateWithOffset:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "withOffset"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGVector",
        "text": "CGVector"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUICoordinate",
        "text": "XCUICoordinate"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "coordinateWithOffset:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "withOffset(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withOffset"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "offsetVector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGVector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGVector",
              "text": "CGVector"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUICoordinate",
              "text": "XCUICoordinate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate": {
      "abstract": [
        {
          "text": "A location on screen relative to some UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "role": "symbol",
      "title": "XCUICoordinate",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)": {
      "abstract": [
        {
          "text": "Creates a new coordinate with an absolute offset in points from the original coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGVector",
          "text": "CGVector"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coordinateWithOffset:"
        }
      ],
      "role": "symbol",
      "title": "withOffset(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/withoffset(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGVector": {
      "abstract": [
        {
          "text": "A structure that contains a two-dimensional vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGVector"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGVector",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGVector",
      "type": "topic",
      "url": "/documentation/corefoundation/cgvector"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "coordinateWithOffset:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coordinateWithOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCUICoordinate",
                    "text": "XCUICoordinate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "coordinateWithOffset:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGVector",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGVector",
                    "text": "CGVector"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "offsetVector"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1withOffset(_:)/title",
          "value": "coordinateWithOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1withOffset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coordinateWithOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/title",
          "value": "XCUICoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuicoordinate/withoffset(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuicoordinate/withoffset(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
