{
  "abstract": [
    {
      "text": "A result that indicates the user successfully authorized adding the payment pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/authorized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKIssuerProvisioningExtensionAuthorizationResult@PKIssuerProvisioningExtensionAuthorizationResultAuthorized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorized"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKIssuerProvisioningExtensionAuthorizationResult.authorized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult": {
      "abstract": [
        {
          "text": "A value that indicates the result of authorizing the addition of a payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResult"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationResult",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/authorized": {
      "abstract": [
        {
          "text": "A result that indicates the user successfully authorized adding the payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationResult.authorized",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult/authorized"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/canceled": {
      "abstract": [
        {
          "text": "A result that indicates the user canceled authorization or wasn’t authorized to add the payment card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceled"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/canceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIssuerProvisioningExtensionAuthorizationResultCanceled"
        }
      ],
      "role": "symbol",
      "title": "PKIssuerProvisioningExtensionAuthorizationResult.canceled",
      "type": "topic",
      "url": "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult/canceled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorization-results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/canceled"
      ],
      "title": "Authorization results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authorization-results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIssuerProvisioningExtensionAuthorizationResult/canceled"
              ],
              "title": "Authorization results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult~1authorized/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResultAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult~1canceled/title",
          "value": "PKIssuerProvisioningExtensionAuthorizationResultCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIssuerProvisioningExtensionAuthorizationResult~1canceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIssuerProvisioningExtensionAuthorizationResultCanceled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult/authorized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkissuerprovisioningextensionauthorizationresult/authorized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
