{
  "abstract": [
    {
      "text": "Options indicating which Accessibility features will be turned on or off when an override session is held by your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accessibility",
    "externalID": "c:@E@AXFeatureOverrideSessionOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AXFeatureOverrideSession.Options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Options"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession": {
      "abstract": [
        {
          "text": "A token object that represents an override session held by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSession"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSession"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSession",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options": {
      "abstract": [
        {
          "text": "Options indicating which Accessibility features will be turned on or off when an override session is held by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSession.Options",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/grayscale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grayscale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXFeatureOverrideSession",
          "text": "AXFeatureOverrideSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXFeatureOverrideSessionOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/grayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionOptionsGrayscale"
        }
      ],
      "role": "symbol",
      "title": "grayscale",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/grayscale"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/init(rawvalue:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/invertColors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invertColors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXFeatureOverrideSession",
          "text": "AXFeatureOverrideSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXFeatureOverrideSessionOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/invertColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionOptionsInvertColors"
        }
      ],
      "role": "symbol",
      "title": "invertColors",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/invertcolors"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXFeatureOverrideSession",
          "text": "AXFeatureOverrideSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXFeatureOverrideSessionOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionOptionsVoiceControl"
        }
      ],
      "role": "symbol",
      "title": "voiceControl",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/voicecontrol"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceOver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXFeatureOverrideSession",
          "text": "AXFeatureOverrideSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXFeatureOverrideSessionOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionOptionsVoiceOver"
        }
      ],
      "role": "symbol",
      "title": "voiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/voiceover"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/zoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXFeatureOverrideSession",
          "text": "AXFeatureOverrideSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXFeatureOverrideSessionOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/zoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionOptionsZoom"
        }
      ],
      "role": "symbol",
      "title": "zoom",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options/zoom"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/grayscale",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/invertColors",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceControl",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceOver",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/zoom"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXFeatureOverrideSessionOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Accessibility/documentation/Accessibility"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/grayscale",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/invertColors",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceControl",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/voiceOver",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options/zoom"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AXFeatureOverrideSessionOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/title",
          "value": "AXFeatureOverrideSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/title",
          "value": "AXFeatureOverrideSessionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1zoom/title",
          "value": "AXFeatureOverrideSessionOptionsZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1zoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptionsZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1invertColors/title",
          "value": "AXFeatureOverrideSessionOptionsInvertColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1invertColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptionsInvertColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1voiceOver/title",
          "value": "AXFeatureOverrideSessionOptionsVoiceOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1voiceOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptionsVoiceOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1grayscale/title",
          "value": "AXFeatureOverrideSessionOptionsGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1grayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptionsGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1voiceControl/title",
          "value": "AXFeatureOverrideSessionOptionsVoiceControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options~1voiceControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptionsVoiceControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axfeatureoverridesession/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/axfeatureoverridesession/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
