{"identifier":{"url":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1","interfaceLanguage":"swift"},"abstract":[{"text":"Version 1 of the sound classifier.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/soundanalysis/snclassifieridentifier/version1"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/soundanalysis/snclassifieridentifier/version1"]}],"sections":[],"metadata":{"title":"version1","extendedModule":"SoundAnalysis","navigatorTitle":[{"text":"SNClassifierIdentifierVersion1","kind":"identifier"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"12.0","name":"macOS"},{"name":"tvOS","unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false}],"role":"symbol","externalID":"c:@SNClassifierIdentifierVersion1","modules":[{"name":"Sound Analysis"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SNClassifierIdentifier","preciseIdentifier":"c:@T@SNClassifierIdentifier","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version1"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@SNClassifierIdentifier","kind":"typeIdentifier","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier","text":"SNClassifierIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SNClassifierIdentifier"}],"identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An identifier that represents the versions of the framework’s sound classifier."}],"url":"/documentation/soundanalysis/snclassifieridentifier","title":"SNClassifierIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SNClassifierIdentifier"}]},"doc://com.apple.soundanalysis/documentation/SoundAnalysis":{"role":"collection","abstract":[{"text":"Classify various sounds by analyzing audio files or streams.","type":"text"}],"kind":"symbol","title":"Sound Analysis","url":"/documentation/soundanalysis","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1":{"navigatorTitle":[{"text":"SNClassifierIdentifierVersion1","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SNClassifierIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@SNClassifierIdentifier"}],"type":"topic","url":"/documentation/soundanalysis/snclassifieridentifier/version1","role":"symbol","title":"version1","abstract":[{"text":"Version 1 of the sound classifier.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"12.0","name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"tvOS"},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"op":"replace","path":"/metadata/title","value":"SNClassifierIdentifierVersion1"},{"op":"replace","path":"/metadata/symbolKind","value":"var"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"SNClassifierIdentifierVersion1","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@T@SNClassifierIdentifier","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier","kind":"typeIdentifier","text":"SNClassifierIdentifier"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SNClassifierIdentifierVersion1"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/title","value":"SNClassifierIdentifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/fragments","value":[{"text":"SNClassifierIdentifier","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/navigatorTitle","value":[{"text":"SNClassifierIdentifier","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier~1version1/title","value":"SNClassifierIdentifierVersion1"},{"op":"replace","value":[{"kind":"identifier","text":"SNClassifierIdentifierVersion1"}],"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier~1version1/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}