{
  "abstract": [
    {
      "text": "The NDEF tag memory size is too small to store the data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCReaderError@NFCNdefReaderSessionErrorTagSizeTooSmall",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ndefReaderSessionErrorTagSizeTooSmall"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCReaderError.Code.ndefReaderSessionErrorTagSizeTooSmall"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ndefReaderSessionErrorTagSizeTooSmall"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable": {
      "abstract": [
        {
          "text": "The NDEF tag isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagNotWritable"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagNotWritable"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagNotWritable",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagnotwritable"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall": {
      "abstract": [
        {
          "text": "The NDEF tag memory size is too small to store the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagSizeTooSmall"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagSizeTooSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagSizeTooSmall",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagsizetoosmall"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure": {
      "abstract": [
        {
          "text": "The reader session failed to update the NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagUpdateFailure"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorTagUpdateFailure"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorTagUpdateFailure",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagupdatefailure"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage": {
      "abstract": [
        {
          "text": "The NDEF tag doesn’t contain an NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorZeroLengthMessage"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNdefReaderSessionErrorZeroLengthMessage"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.ndefReaderSessionErrorZeroLengthMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrorzerolengthmessage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "NDEF-Tag-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage"
      ],
      "title": "NDEF Tag Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCNdefReaderSessionErrorTagSizeTooSmall"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "NDEF-Tag-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagNotWritable",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorTagUpdateFailure",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/ndefReaderSessionErrorZeroLengthMessage"
              ],
              "title": "NDEF Tag Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorZeroLengthMessage/title",
          "value": "NFCNdefReaderSessionErrorZeroLengthMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorZeroLengthMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorZeroLengthMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagSizeTooSmall/title",
          "value": "NFCNdefReaderSessionErrorTagSizeTooSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagSizeTooSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagSizeTooSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagUpdateFailure/title",
          "value": "NFCNdefReaderSessionErrorTagUpdateFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagUpdateFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagUpdateFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagNotWritable/title",
          "value": "NFCNdefReaderSessionErrorTagNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1ndefReaderSessionErrorTagNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNdefReaderSessionErrorTagNotWritable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagsizetoosmall"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/ndefreadersessionerrortagsizetoosmall"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
