{
  "abstract": [
    {
      "text": "The reader session timed out.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCReaderError@NFCReaderSessionInvalidationErrorSessionTimeout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "readerSessionInvalidationErrorSessionTimeout"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCReaderError.Code.readerSessionInvalidationErrorSessionTimeout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readerSessionInvalidationErrorSessionTimeout"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead": {
      "abstract": [
        {
          "text": "The first NDEF tag read by this session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorFirstNDEFTagRead"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorFirstNDEFTagRead",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorfirstndeftagread"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly": {
      "abstract": [
        {
          "text": "The reader session terminated unexpectedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTerminatedUnexpectedly"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessionterminatedunexpectedly"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout": {
      "abstract": [
        {
          "text": "The reader session timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTimeout"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSessionTimeout",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessiontimeout"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy": {
      "abstract": [
        {
          "text": "The reader session failed because the system is busy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSystemIsBusy"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorSystemIsBusy"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorSystemIsBusy",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsystemisbusy"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled": {
      "abstract": [
        {
          "text": "The user canceled the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorUserCanceled"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionInvalidationErrorUserCanceled"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerSessionInvalidationErrorUserCanceled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorusercanceled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Session-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled"
      ],
      "title": "Session Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCReaderSessionInvalidationErrorSessionTimeout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Session-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorFirstNDEFTagRead",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorSystemIsBusy",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerSessionInvalidationErrorUserCanceled"
              ],
              "title": "Session Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTimeout/title",
          "value": "NFCReaderSessionInvalidationErrorSessionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSessionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSystemIsBusy/title",
          "value": "NFCReaderSessionInvalidationErrorSystemIsBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSystemIsBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSystemIsBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorUserCanceled/title",
          "value": "NFCReaderSessionInvalidationErrorUserCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorUserCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorUserCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTerminatedUnexpectedly/title",
          "value": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorSessionTerminatedUnexpectedly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorSessionTerminatedUnexpectedly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorFirstNDEFTagRead/title",
          "value": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerSessionInvalidationErrorFirstNDEFTagRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSessionInvalidationErrorFirstNDEFTagRead"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessiontimeout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readersessioninvalidationerrorsessiontimeout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
