{
  "abstract": [
    {
      "text": "A parameter value is outside of the acceptable boundary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCReaderError@NFCReaderErrorParameterOutOfBound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "readerErrorParameterOutOfBound"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderErrorParameterOutOfBound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCReaderError.Code.readerErrorParameterOutOfBound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readerErrorParameterOutOfBound"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter": {
      "abstract": [
        {
          "text": "An input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameter"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorInvalidParameter",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorinvalidparameter"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength": {
      "abstract": [
        {
          "text": "The length of an input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameterLength"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorInvalidParameterLength"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorInvalidParameterLength",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorinvalidparameterlength"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound": {
      "abstract": [
        {
          "text": "A parameter value is outside of the acceptable boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorParameterOutOfBound"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorParameterOutOfBound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorParameterOutOfBound"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorParameterOutOfBound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorparameteroutofbound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled": {
      "abstract": [
        {
          "text": "The NFC wireless radio on the device is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorRadioDisabled"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorRadioDisabled"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorRadioDisabled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorradiodisabled"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation": {
      "abstract": [
        {
          "text": "A security violation associated with the reader session has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorSecurityViolation"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorSecurityViolation"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorSecurityViolation",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorsecurityviolation"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature": {
      "abstract": [
        {
          "text": "The reader session does not support this feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorUnsupportedFeature"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderErrorUnsupportedFeature"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerErrorUnsupportedFeature",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorunsupportedfeature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Other-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation"
      ],
      "title": "Other Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCReaderErrorParameterOutOfBound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorParameterOutOfBound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Other-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorUnsupportedFeature",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameter",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorInvalidParameterLength",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorRadioDisabled",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerErrorSecurityViolation"
              ],
              "title": "Other Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCReaderErrorParameterOutOfBound"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorRadioDisabled/title",
          "value": "NFCReaderErrorRadioDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorRadioDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorRadioDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorSecurityViolation/title",
          "value": "NFCReaderErrorSecurityViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorSecurityViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorSecurityViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorUnsupportedFeature/title",
          "value": "NFCReaderErrorUnsupportedFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorUnsupportedFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorUnsupportedFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameter/title",
          "value": "NFCReaderErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorParameterOutOfBound/title",
          "value": "NFCReaderErrorParameterOutOfBound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorParameterOutOfBound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorParameterOutOfBound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameterLength/title",
          "value": "NFCReaderErrorInvalidParameterLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerErrorInvalidParameterLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderErrorInvalidParameterLength"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorparameteroutofbound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readererrorparameteroutofbound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
