{
  "abstract": [
    {
      "text": "The packet length exceeds the limit supported by the tag.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCReaderError@NFCReaderTransceiveErrorPacketTooLong",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "readerTransceiveErrorPacketTooLong"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderTransceiveErrorPacketTooLong"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCReaderError.Code.readerTransceiveErrorPacketTooLong"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readerTransceiveErrorPacketTooLong"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong": {
      "abstract": [
        {
          "text": "The packet length exceeds the limit supported by the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorPacketTooLong"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorPacketTooLong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorPacketTooLong"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorPacketTooLong",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorpackettoolong"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded": {
      "abstract": [
        {
          "text": "Too many retries have occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorRetryExceeded"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorRetryExceeded"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorRetryExceeded",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorretryexceeded"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated": {
      "abstract": [
        {
          "text": "The reader session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorSessionInvalidated"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorSessionInvalidated"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorSessionInvalidated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorsessioninvalidated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost": {
      "abstract": [
        {
          "text": "The reader lost the connection to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagConnectionLost"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagConnectionLost"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagConnectionLost",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagconnectionlost"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected": {
      "abstract": [
        {
          "text": "The tag isn’t in the connected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagNotConnected"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagNotConnected"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagNotConnected",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagnotconnected"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError": {
      "abstract": [
        {
          "text": "The tag has responded with an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagResponseError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderTransceiveErrorTagResponseError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code.readerTransceiveErrorTagResponseError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrortagresponseerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transceive-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated"
      ],
      "title": "Transceive Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCReaderTransceiveErrorPacketTooLong"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorPacketTooLong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transceive-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorRetryExceeded",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagConnectionLost",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagNotConnected",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorTagResponseError",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code/readerTransceiveErrorSessionInvalidated"
              ],
              "title": "Transceive Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCReaderTransceiveErrorPacketTooLong"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorSessionInvalidated/title",
          "value": "NFCReaderTransceiveErrorSessionInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorSessionInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorSessionInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorRetryExceeded/title",
          "value": "NFCReaderTransceiveErrorRetryExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorRetryExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorRetryExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorPacketTooLong/title",
          "value": "NFCReaderTransceiveErrorPacketTooLong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorPacketTooLong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorPacketTooLong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagConnectionLost/title",
          "value": "NFCReaderTransceiveErrorTagConnectionLost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagConnectionLost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagConnectionLost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagNotConnected/title",
          "value": "NFCReaderTransceiveErrorTagNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagNotConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagResponseError/title",
          "value": "NFCReaderTransceiveErrorTagResponseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code~1readerTransceiveErrorTagResponseError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderTransceiveErrorTagResponseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorpackettoolong"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct/code/readertransceiveerrorpackettoolong"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
