{"sections":[],"identifier":{"url":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a tensor with the sizes, number of feature channels, data, and data type you specify."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mlcompute/documentation/MLCompute","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:dataType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:data:dataType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:fillWithData:dataType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:randomInitializerType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)"],"anchor":"Creating-Tensors-by-Specifying-Shape","title":"Creating Tensors by Specifying Shape"}],"metadata":{"externalID":"c:objc(cs)MLCTensor(cm)tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","title":"init(width:height:featureChannelCount:batchSize:data:dataType:)","roleHeading":"Initializer","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureChannelCount"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCTensorData","preciseIdentifier":"c:objc(cs)MLCTensorData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCDataType","preciseIdentifier":"c:@E@MLCDataType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ML Compute"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","kind":"identifier"}],"platforms":[{"introducedAt":"14.0","deprecatedAt":"17.4","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"14.0","deprecatedAt":"17.4","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"14.0","deprecatedAt":"17.4","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"11.0","deprecatedAt":"14.3","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"introducedAt":"14.0","deprecatedAt":"17.4","beta":false,"deprecated":false,"name":"tvOS","unavailable":false}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureChannelCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"batchSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLCTensorData","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData","preciseIdentifier":"c:objc(cs)MLCTensorData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLCDataType","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType","preciseIdentifier":"c:@E@MLCDataType"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The tensor width.","type":"text"}]}],"name":"width"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tensor height."}]}],"name":"height"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of feature channels."}]}],"name":"featureChannelCount"},{"content":[{"inlineContent":[{"text":"The tensor batch size.","type":"text"}],"type":"paragraph"}],"name":"batchSize"},{"content":[{"inlineContent":[{"type":"text","text":"The tensor data."}],"type":"paragraph"}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The tensor data type.","type":"text"}]}],"name":"dataType"}],"kind":"parameters"}],"variants":[{"paths":["/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:datatype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:datatype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:":{"type":"topic","fragments":[{"kind":"text","text":"+ "},{"text":"tensorWithShape:randomInitializerType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"tensorWithShape:randomInitializerType:"}],"kind":"symbol","url":"/documentation/mlcompute/mlctensor/tensorwithshape:randominitializertype:","abstract":[{"text":"Creates a tensor with the shape and random initializer type you specify.","type":"text"}],"title":"tensorWithShape:randomInitializerType:","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","url":"/documentation/technologies","title":"Technologies","kind":"technologies"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:fillWithData:dataType:)":{"type":"topic","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shape","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"fillWithData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCDataType","preciseIdentifier":"c:@E@MLCDataType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"/documentation/mlcompute/mlctensor/init(shape:fillwithdata:datatype:)","abstract":[{"text":"Creates a tensor with the shape, scalar value, and data type you specify.","type":"text"}],"title":"init(shape:fillWithData:dataType:)","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:fillWithData:dataType:)","deprecated":true,"role":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType","abstract":[{"type":"text","text":"A tensor data type."}],"navigatorTitle":[{"text":"MLCDataType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLCDataType","kind":"identifier"}],"title":"MLCDataType","url":"/documentation/mlcompute/mlcdatatype","type":"topic","deprecated":true},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)":{"kind":"symbol","title":"init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"featureChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"fillWithData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"dataType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCDataType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MLCDataType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)","url":"/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:fillwithdata:datatype:)","deprecated":true,"role":"symbol","abstract":[{"text":"Creates a tensor with the sizes and number of feature channels, and filled with the data and type you specify.","type":"text"}]},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)":{"title":"init(width:height:featureChannelCount:batchSize:)","kind":"symbol","deprecated":true,"identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"featureChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Creates a tensor without data, with the sizes and number of feature channels you specify."}],"navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:","kind":"identifier"}],"url":"/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:)"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)":{"type":"topic","navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","kind":"identifier"}],"role":"symbol","title":"init(width:height:featureChannelCount:batchSize:data:dataType:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"featureChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCTensorData","preciseIdentifier":"c:objc(cs)MLCTensorData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCDataType","preciseIdentifier":"c:@E@MLCDataType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:datatype:)","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)","kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Creates a tensor with the sizes, number of feature channels, data, and data type you specify."}]},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)":{"abstract":[{"text":"Creates a tensor with the sizes, number of feature channels, and random data using the random initializer type you specify.","type":"text"}],"type":"topic","title":"init(width:height:featureChannelCount:batchSize:randomInitializerType:)","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)","navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"featureChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"randomInitializerType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCRandomInitializerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MLCRandomInitializerType"},{"text":")","kind":"text"}],"role":"symbol","url":"/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:randominitializertype:)","kind":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute":{"kind":"symbol","title":"ML Compute","url":"/documentation/mlcompute","type":"topic","role":"collection","identifier":"doc://com.apple.mlcompute/documentation/MLCompute","deprecated":true,"abstract":[{"type":"text","text":"Accelerate training and validation of neural networks across the CPU and one or more GPUs."}]},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:dataType:)":{"abstract":[{"text":"Creates a tensor without data, with the shape and data type you specify.","type":"text"}],"type":"topic","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:dataType:)","role":"symbol","url":"/documentation/mlcompute/mlctensor/init(shape:datatype:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"shape","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"dataType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MLCDataType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MLCDataType"},{"text":")","kind":"text"}],"title":"init(shape:dataType:)","kind":"symbol","deprecated":true},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:":{"type":"topic","title":"tensorWithShape:fillWithData:dataType:","fragments":[{"kind":"text","text":"+ "},{"text":"tensorWithShape:fillWithData:dataType:","kind":"identifier"}],"url":"/documentation/mlcompute/mlctensor/tensorwithshape:fillwithdata:datatype:","navigatorTitle":[{"kind":"identifier","text":"tensorWithShape:fillWithData:dataType:"}],"kind":"symbol","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:","abstract":[{"type":"text","text":"Creates a tensor with the shape, scalar value, and data type you specify."}],"role":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"tensorWithShape:"}],"role":"symbol","title":"tensorWithShape:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tensorWithShape:"}],"url":"/documentation/mlcompute/mlctensor/tensorwithshape:","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:","kind":"symbol","abstract":[{"type":"text","text":"Creates a tensor without data, with the shape you specify."}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"type":"text","text":"Describes an unsigned integer."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","url":"/documentation/objectivec/nsuinteger","title":"NSUInteger"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor":{"abstract":[{"text":"The data object you use throughout the framework.","type":"text"}],"type":"topic","title":"MLCTensor","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor","navigatorTitle":[{"text":"MLCTensor","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MLCTensor"}],"role":"symbol","url":"/documentation/mlcompute/mlctensor","kind":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)":{"type":"topic","title":"init(width:height:featureChannelCount:batchSize:data:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"featureChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"batchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCTensorData","preciseIdentifier":"c:objc(cs)MLCTensorData","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:)","navigatorTitle":[{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)","abstract":[{"text":"Creates a tensor with the sizes, number of feature channels, and data you specify.","type":"text"}],"deprecated":true,"role":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:data:dataType:)":{"kind":"symbol","title":"init(shape:data:dataType:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shape","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"], ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCTensorData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLCTensorData"},{"kind":"text","text":", "},{"text":"dataType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLCDataType","preciseIdentifier":"c:@E@MLCDataType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:data:dataType:)","url":"/documentation/mlcompute/mlctensor/init(shape:data:datatype:)","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Creates a tensor with the shape, data, and data type you specify."}]},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData":{"type":"topic","navigatorTitle":[{"text":"MLCTensorData","kind":"identifier"}],"role":"symbol","title":"MLCTensorData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MLCTensorData","kind":"identifier"}],"url":"/documentation/mlcompute/mlctensordata","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData","kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"An encapsulation of the memory that tensor data uses."}]},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:randomInitializerType:)":{"abstract":[{"type":"text","text":"Creates a tensor with the shape and random initializer type you specify."}],"type":"topic","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:randomInitializerType:)","role":"symbol","url":"/documentation/mlcompute/mlctensor/init(shape:randominitializertype:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shape"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"randomInitializerType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MLCRandomInitializerType","text":"MLCRandomInitializerType"},{"text":")","kind":"text"}],"title":"init(shape:randomInitializerType:)","kind":"symbol","deprecated":true},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:":{"type":"topic","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:","title":"tensorWithShape:data:dataType:","kind":"symbol","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"tensorWithShape:data:dataType:","kind":"identifier"}],"navigatorTitle":[{"text":"tensorWithShape:data:dataType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a tensor with the shape, data, and data type you specify."}],"url":"/documentation/mlcompute/mlctensor/tensorwithshape:data:datatype:"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:)":{"url":"/documentation/mlcompute/mlctensor/init(shape:)","abstract":[{"text":"Creates a tensor without data, with the shape you specify.","type":"text"}],"role":"symbol","title":"init(shape:)","deprecated":true,"identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(shape:)","type":"topic","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shape","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.externally.resolved.symbol/s:Si":{"type":"topic","title":"Int","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"url":"/documentation/Swift/Int","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Si","abstract":[{"text":"A signed integer value type.","type":"text"}],"role":"symbol"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:":{"title":"tensorWithShape:dataType:","kind":"symbol","type":"topic","role":"symbol","url":"/documentation/mlcompute/mlctensor/tensorwithshape:datatype:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tensorWithShape:dataType:"}],"abstract":[{"type":"text","text":"Creates a tensor without data, with the shape and data type you specify."}],"navigatorTitle":[{"text":"tensorWithShape:dataType:","kind":"identifier"}],"identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:"},"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:":{"navigatorTitle":[{"text":"tensorWithShape:randomInitializerType:dataType:","kind":"identifier"}],"kind":"symbol","title":"tensorWithShape:randomInitializerType:dataType:","url":"/documentation/mlcompute/mlctensor/tensorwithshape:randominitializertype:datatype:","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"tensorWithShape:randomInitializerType:dataType:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:","abstract":[{"text":"Creates a tensor with the shape, random initializer, and data type you specify.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecatedAt":"17.4","name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false},{"unavailable":false,"deprecatedAt":"17.4","name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false},{"unavailable":false,"deprecatedAt":"17.4","name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false},{"unavailable":false,"deprecatedAt":"14.3","name":"macOS","introducedAt":"11.0","beta":false,"deprecated":false},{"unavailable":false,"deprecatedAt":"17.4","name":"tvOS","introducedAt":"14.0","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Method","op":"replace"},{"path":"/metadata/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mlcompute/documentation/MLCompute","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Creating Tensors by Specifying Shape","identifiers":["doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)","doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)"],"anchor":"Creating-Tensors-by-Specifying-Shape","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"tensorWithWidth:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureChannelCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"featureChannelCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"batchSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MLCTensorData","identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData","preciseIdentifier":"c:objc(cs)MLCTensorData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"text":"dataType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType","text":"MLCDataType","preciseIdentifier":"c:@E@MLCDataType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"dataType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"width","content":[{"inlineContent":[{"type":"text","text":"The tensor width."}],"type":"paragraph"}]},{"name":"height","content":[{"inlineContent":[{"type":"text","text":"The tensor height."}],"type":"paragraph"}]},{"name":"featureChannelCount","content":[{"inlineContent":[{"text":"The number of feature channels.","type":"text"}],"type":"paragraph"}]},{"name":"batchSize","content":[{"inlineContent":[{"type":"text","text":"The tensor batch size."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tensor data."}]}]},{"name":"dataType","content":[{"type":"paragraph","inlineContent":[{"text":"The tensor data type.","type":"text"}]}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/title","value":"MLCDataType"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/fragments","value":[{"kind":"identifier","text":"MLCDataType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/navigatorTitle","value":[{"text":"MLCDataType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:)/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tensorWithWidth:height:featureChannelCount:batchSize:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:dataType:)/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:dataType:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:randomInitializerType:)/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:randomInitializerType:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title","value":"MLCTensor"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments","value":[{"text":"MLCTensor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle","value":[{"text":"MLCTensor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:)/title","value":"tensorWithWidth:height:featureChannelCount:batchSize:data:"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tensorWithWidth:height:featureChannelCount:batchSize:data:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/title","value":"MLCTensorData"},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/fragments","value":[{"kind":"identifier","text":"MLCTensorData"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/navigatorTitle","value":[{"text":"MLCTensorData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}