{
  "abstract": [
    {
      "text": "Creates a tensor without data, with the shape you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCTensor(cm)tensorWithShape:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "tensorWithShape:"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tensorWithShape:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "name": "tvOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "tensorWithShape:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "tensorWithShape:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "shape"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array that contains the sizes of each dimension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "shape"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A tensor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The tensor data type is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType/float32",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType/float32": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float32"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType/float32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDataTypeFloat32"
        }
      ],
      "role": "symbol",
      "title": "MLCDataType.float32",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdatatype/float32"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor": {
      "abstract": [
        {
          "text": "The data object you use throughout the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)": {
      "abstract": [
        {
          "text": "Creates a tensor without data, with the sizes and number of feature channels you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "featureChannelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithWidth:height:featureChannelCount:batchSize:"
        }
      ],
      "role": "symbol",
      "title": "init(width:height:featureChannelCount:batchSize:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the sizes, number of feature channels, and data you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "featureChannelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithWidth:height:featureChannelCount:batchSize:data:"
        }
      ],
      "role": "symbol",
      "title": "init(width:height:featureChannelCount:batchSize:data:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the sizes, number of feature channels, data, and data type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "featureChannelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCDataType",
          "text": "MLCDataType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:"
        }
      ],
      "role": "symbol",
      "title": "init(width:height:featureChannelCount:batchSize:data:dataType:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:data:datatype:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the sizes and number of feature channels, and filled with the data and type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "featureChannelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillWithData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCDataType",
          "text": "MLCDataType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:"
        }
      ],
      "role": "symbol",
      "title": "init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:fillwithdata:datatype:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the sizes, number of feature channels, and random data using the random initializer type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "featureChannelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "randomInitializerType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCRandomInitializerType",
          "text": "MLCRandomInitializerType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:"
        }
      ],
      "role": "symbol",
      "title": "init(width:height:featureChannelCount:batchSize:randomInitializerType:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(width:height:featurechannelcount:batchsize:randominitializertype:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:": {
      "abstract": [
        {
          "text": "Creates a tensor without data, with the shape you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:": {
      "abstract": [
        {
          "text": "Creates a tensor with the shape, data, and data type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:data:dataType:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:data:dataType:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:data:dataType:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:data:datatype:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:": {
      "abstract": [
        {
          "text": "Creates a tensor without data, with the shape and data type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:dataType:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:dataType:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:dataType:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:datatype:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:": {
      "abstract": [
        {
          "text": "Creates a tensor with the shape, scalar value, and data type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:fillWithData:dataType:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:fillWithData:dataType:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:fillWithData:dataType:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:fillwithdata:datatype:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:": {
      "abstract": [
        {
          "text": "Creates a tensor with the shape and random initializer type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:randomInitializerType:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:randomInitializerType:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:randomInitializerType:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:randominitializertype:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:": {
      "abstract": [
        {
          "text": "Creates a tensor with the shape, random initializer, and data type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tensorWithShape:randomInitializerType:dataType:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithShape:randomInitializerType:dataType:"
        }
      ],
      "role": "symbol",
      "title": "tensorWithShape:randomInitializerType:dataType:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/tensorwithshape:randominitializertype:datatype:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Tensors-by-Specifying-Shape",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:dataType:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:data:dataType:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:fillWithData:dataType:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/tensorWithShape:randomInitializerType:dataType:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:data:dataType:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(width:height:featureChannelCount:batchSize:randomInitializerType:)"
      ],
      "title": "Creating Tensors by Specifying Shape"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:)/title",
          "value": "tensorWithWidth:height:featureChannelCount:batchSize:data:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithWidth:height:featureChannelCount:batchSize:data:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:dataType:)/title",
          "value": "tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:data:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithWidth:height:featureChannelCount:batchSize:data:dataType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:randomInitializerType:)/title",
          "value": "tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:randomInitializerType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithWidth:height:featureChannelCount:batchSize:randomInitializerType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:)/title",
          "value": "tensorWithWidth:height:featureChannelCount:batchSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithWidth:height:featureChannelCount:batchSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)/title",
          "value": "tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(width:height:featureChannelCount:batchSize:fillWithData:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithWidth:height:featureChannelCount:batchSize:fillWithData:dataType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title",
          "value": "MLCTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType~1float32/title",
          "value": "MLCDataTypeFloat32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType~1float32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDataTypeFloat32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlctensor/tensorwithshape:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
