{
  "abstract": [
    {
      "text": "The time span that corresponds to the result’s classifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/timeRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SNClassificationResult(py)timeRange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "timeRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTimeRange",
        "text": "CMTimeRange"
      }
    ],
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "timeRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "timeRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "timeRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTimeRange",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The time range’s ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/coremedia/cmtime-u58",
              "type": "text"
            },
            {
              "text": " values are the number of audio frames at the analyzer’s sample rate. Use these time indices to determine where, in time, the result corresponds to the original audio.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A result’s time range typically refers to audio older than its most recent audio because the request gathers the data into blocks before sending them to the model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassification": {
      "abstract": [
        {
          "text": "A type that pairs a sound classifier’s prediction with its confidence in that prediction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassification"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassification"
        }
      ],
      "role": "symbol",
      "title": "SNClassification",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassification"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult": {
      "abstract": [
        {
          "text": "A result that contains the highest-ranking classifications in a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "role": "symbol",
      "title": "SNClassificationResult",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classification(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the classification for an identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SNClassification",
          "text": "SNClassification"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classification(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classificationForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "classification(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult/classification(foridentifier:)"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classifications": {
      "abstract": [
        {
          "text": "A sorted array of the request’s top classification candidates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classifications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SNClassification",
          "text": "SNClassification"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classifications"
        }
      ],
      "role": "symbol",
      "title": "classifications",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult/classifications"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/timeRange": {
      "abstract": [
        {
          "text": "The time span that corresponds to the result’s classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/timeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeRange"
        }
      ],
      "role": "symbol",
      "title": "timeRange",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult/timerange"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange": {
      "abstract": [
        {
          "text": "A structure that represents a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTimeRange",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeRange"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Result",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classifications",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassification",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classification(forIdentifier:)"
      ],
      "title": "Inspecting the Result"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "timeRange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Result",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classifications",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassification",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult/classification(forIdentifier:)"
              ],
              "title": "Inspecting the Result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMTimeRange",
                    "text": "CMTimeRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "timeRange"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/title",
          "value": "SNClassificationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTimeRange/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1timeRange/title",
          "value": "timeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1timeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1classification(forIdentifier:)/title",
          "value": "classificationForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1classification(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "classificationForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassification/title",
          "value": "SNClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1classifications/title",
          "value": "classifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult~1classifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "classifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis/snclassificationresult/timerange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis/snclassificationresult/timerange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
