{
  "abstract": [
    {
      "text": "Encodes GPU commands to evaluate the custom layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/encode(commandBuffer:inputs:outputs:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MLCustomLayer(im)encodeToCommandBuffer:inputs:outputs:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "encode"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "commandBuffer"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
        "text": "MTLCommandBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inputs"
      },
      {
        "kind": "text",
        "text": ": [any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLTexture",
        "text": "MTLTexture"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "outputs"
      },
      {
        "kind": "text",
        "text": ": [any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLTexture",
        "text": "MTLTexture"
      },
      {
        "kind": "text",
        "text": "]) "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "encodeToCommandBuffer:inputs:outputs:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "encode(commandBuffer:inputs:outputs:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "encode"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "commandBuffer"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inputs"
            },
            {
              "kind": "text",
              "text": ": [any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLTexture",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "outputs"
            },
            {
              "kind": "text",
              "text": ": [any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLTexture",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": "]) "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A command buffer that defines the work the layer performs on the GPU.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "commandBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A texture array that represents the layer’s inputs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A texture array that represents the layer’s outputs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outputs"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to use the GPU to evaluate your layer. Fill ",
              "type": "text"
            },
            {
              "code": "commandBuffer",
              "type": "codeVoice"
            },
            {
              "text": " with the GPU commands that evaluate the layer. Don’t commit the command buffer in this method; Core ML executes the command buffer after this method returns.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Improve your layer’s performance by caching the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLComputePipelineState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances you create and intend to reuse in subsequent calls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Implementing this method doesn’t guarantee that Core ML evaluates this layer on the GPU. For example, Core ML may evaluate the layer on the CPU if the system doesn’t have enough GPU’s resources to run the custom layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The GPU works with 16-bit floats, not 32-bit floats. Verify that lower precision values don’t impact your network’s behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t implement this method, Core ML instead uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/evaluate(inputs:outputs:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about using the GPU for general purpose programming, see ",
              "type": "text"
            },
            {
              "code": "Compute Processing",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer": {
      "abstract": [
        {
          "text": "An interface that defines the behavior of a custom layer in your neural network model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCustomLayer"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCustomLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCustomLayer",
      "type": "topic",
      "url": "/documentation/coreml/mlcustomlayer"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/encode(commandBuffer:inputs:outputs:)": {
      "abstract": [
        {
          "text": "Encodes GPU commands to evaluate the custom layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputs"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "outputs"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/encode(commandBuffer:inputs:outputs:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodeToCommandBuffer:inputs:outputs:error:"
        }
      ],
      "role": "symbol",
      "title": "encode(commandBuffer:inputs:outputs:)",
      "type": "topic",
      "url": "/documentation/coreml/mlcustomlayer/encode(commandbuffer:inputs:outputs:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/evaluate(inputs:outputs:)": {
      "abstract": [
        {
          "text": "Evaluates the custom layer with the given inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inputs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "outputs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/evaluate(inputs:outputs:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluateOnCPUWithInputs:outputs:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "evaluate(inputs:outputs:)",
      "type": "topic",
      "url": "/documentation/coreml/mlcustomlayer/evaluate(inputs:outputs:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers": {
      "abstract": [
        {
          "text": "Add models with custom neural-network layers to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers",
      "kind": "article",
      "role": "article",
      "title": "Creating and Integrating a Model with Custom Layers",
      "type": "topic",
      "url": "/documentation/coreml/creating-and-integrating-a-model-with-custom-layers"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLComputePipelineState": {
      "abstract": [
        {
          "text": "An interface that represents a GPU pipeline configuration for running kernels in a compute pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputePipelineState"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLComputePipelineState",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLComputePipelineState",
      "type": "topic",
      "url": "/documentation/Metal/MTLComputePipelineState"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer": {
      "abstract": [
        {
          "text": "A container that stores a sequence of GPU commands that you encode into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandBuffer",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandBuffer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture": {
      "abstract": [
        {
          "text": "A resource that holds formatted image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLResource",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTexture",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Evaluating-a-Layer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/evaluate(inputs:outputs:)"
      ],
      "title": "Evaluating a Layer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "encodeToCommandBuffer:inputs:outputs:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeToCommandBuffer:inputs:outputs:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Evaluating-a-Layer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer/evaluate(inputs:outputs:)"
              ],
              "title": "Evaluating a Layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "encodeToCommandBuffer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLCommandBuffer",
                    "text": "id<MTLCommandBuffer>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "commandBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "inputs:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<id<MTLTexture>>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inputs"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "outputs:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<id<MTLTexture>>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outputs"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A command buffer that defines the work the layer performs on the GPU.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "commandBuffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A texture array that represents the layer’s inputs.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inputs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A texture array that represents the layer’s outputs.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outputs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return in Objective-C, if an error occurs, a pointer to an error information instance; otherwise ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the method successfully filled ",
                    "type": "text"
                  },
                  {
                    "code": "commandBuffer",
                    "type": "codeVoice"
                  },
                  {
                    "text": "; otherwise ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLCommandBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/title",
          "value": "MLCustomLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer~1encode(commandBuffer:inputs:outputs:)/title",
          "value": "encodeToCommandBuffer:inputs:outputs:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer~1encode(commandBuffer:inputs:outputs:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeToCommandBuffer:inputs:outputs:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLComputePipelineState/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLComputePipelineState"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer~1evaluate(inputs:outputs:)/title",
          "value": "evaluateOnCPUWithInputs:outputs:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer~1evaluate(inputs:outputs:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluateOnCPUWithInputs:outputs:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlcustomlayer/encode(commandbuffer:inputs:outputs:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlcustomlayer/encode(commandbuffer:inputs:outputs:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
