{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar/bnnsDataType"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsscalar/bnnsdatatype"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bnnsDataType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSDataType","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","preciseIdentifier":"c:@EA@BNNSDataType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar"]]},"metadata":{"roleHeading":"Type Property","required":true,"modules":[{"name":"Accelerate"}],"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","introducedAt":"11.0","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","introducedAt":"7.0","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","title":"bnnsDataType","externalID":"s:10Accelerate10BNNSScalarP12bnnsDataTypeSo08BNNSDataE0avpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bnnsDataType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSDataType","text":"BNNSDataType","kind":"typeIdentifier"}],"symbolKind":"property"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType":{"abstract":[{"type":"text","text":"BNNS Data Types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSDataType"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSDataType"}],"type":"topic","url":"/documentation/accelerate/bnnsdatatype","title":"BNNSDataType"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar/bnnsDataType":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bnnsDataType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSDataType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@BNNSDataType"}],"required":true,"title":"bnnsDataType","url":"/documentation/accelerate/bnnsscalar/bnnsdatatype","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar/bnnsDataType","kind":"symbol","type":"topic","abstract":[]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSScalar","navigatorTitle":[{"text":"BNNSScalar","kind":"identifier"}],"kind":"symbol","type":"topic","title":"BNNSScalar","url":"/documentation/accelerate/bnnsscalar","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSScalar"}],"abstract":[],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"BNNSDataType","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments","op":"replace","value":[{"text":"BNNSDataType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"BNNSDataType"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}