{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsuserinterfacelayoutorientation/horizontal"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsuserinterfacelayoutorientation/horizontal"]}],"metadata":{"modules":[{"name":"AppKit"}],"externalID":"c:@E@NSUserInterfaceLayoutOrientation@NSUserInterfaceLayoutOrientationHorizontal","roleHeading":"Case","navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientationHorizontal","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"NSUserInterfaceLayoutOrientation.horizontal","platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.9","unavailable":false,"name":"macOS"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this constant in the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation"},{"type":"text","text":" property to specify a horizontal layout for the stack view. Use it to specify the horizontal user interface axis for clipping resistance and hugging priority."}]},{"type":"paragraph","inlineContent":[{"text":"The leading, center, and trailing gravity areas in a horizontal stack view are arranged left to right or right to left depending on the value of the inherited ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","type":"reference","isActive":true},{"text":" property.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical"],"generated":true,"anchor":"Constants"}],"abstract":[{"type":"text","text":"The horizontal orientation."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection":{"navigatorTitle":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","title":"userInterfaceLayoutDirection","url":"/documentation/appkit/nsview/userinterfacelayoutdirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInterfaceLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSUserInterfaceLayoutDirection","text":"NSUserInterfaceLayoutDirection"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The layout direction for content in the view."}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal":{"abstract":[{"text":"The horizontal orientation.","type":"text"}],"title":"NSUserInterfaceLayoutOrientation.horizontal","type":"topic","url":"/documentation/appkit/nsuserinterfacelayoutorientation/horizontal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical":{"url":"/documentation/appkit/nsuserinterfacelayoutorientation/vertical","title":"NSUserInterfaceLayoutOrientation.vertical","kind":"symbol","abstract":[{"type":"text","text":"The vertical orientation."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"10.9","beta":false,"name":"macOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"NSUserInterfaceLayoutOrientationHorizontal"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"NSUserInterfaceLayoutOrientationHorizontal","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical"],"generated":true,"anchor":"Constants","title":"Constants"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/title","value":"userInterfaceLayoutDirection"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/fragments","value":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title","value":"orientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments","value":[{"text":"orientation","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/title","value":"NSUserInterfaceLayoutOrientationHorizontal"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/title","value":"NSUserInterfaceLayoutOrientationVertical"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationVertical"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title","value":"NSUserInterfaceLayoutOrientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle","value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}