{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsuserinterfacelayoutorientation/vertical"]},{"paths":["/documentation/appkit/nsuserinterfacelayoutorientation/vertical"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"NSUserInterfaceLayoutOrientation.vertical","platforms":[{"beta":false,"name":"macOS","introducedAt":"10.9","unavailable":false,"deprecated":false}],"role":"symbol","modules":[{"name":"AppKit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"externalID":"c:@E@NSUserInterfaceLayoutOrientation@NSUserInterfaceLayoutOrientationVertical"},"sections":[],"kind":"symbol","seeAlsoSections":[{"title":"Constants","generated":true,"anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vertical"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this constant in the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","isActive":true},{"type":"text","text":" property to specify a vertical layout for the stack view. Use it to specify the vertical user interface axis for clipping resistance and hugging priority."}]},{"type":"paragraph","inlineContent":[{"text":"The leading, center, and trailing gravity areas in a vertical stack view are arranged top to bottom.","type":"text"}]}]}],"abstract":[{"type":"text","text":"The vertical orientation."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical":{"url":"/documentation/appkit/nsuserinterfacelayoutorientation/vertical","title":"NSUserInterfaceLayoutOrientation.vertical","kind":"symbol","abstract":[{"type":"text","text":"The vertical orientation."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal":{"abstract":[{"text":"The horizontal orientation.","type":"text"}],"title":"NSUserInterfaceLayoutOrientation.horizontal","type":"topic","url":"/documentation/appkit/nsuserinterfacelayoutorientation/horizontal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.9","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"NSUserInterfaceLayoutOrientationVertical"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal"],"title":"Constants","generated":true,"anchor":"Constants"}],"path":"/seeAlsoSections"},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"NSUserInterfaceLayoutOrientationVertical","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/title"},{"op":"replace","value":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/fragments"},{"op":"replace","value":"orientation","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments"},{"value":"NSUserInterfaceLayoutOrientation","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title"},{"value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle","value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/title","value":"NSUserInterfaceLayoutOrientationHorizontal"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/fragments","value":[{"text":"NSUserInterfaceLayoutOrientationHorizontal","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}