{
  "abstract": [
    {
      "text": "Enable background audio in your app to provide a seamless playback experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/background-execution"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/playing-background-audio"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Playing Background Audio"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While most watchOS apps are optimized for quick interactions, apps that play audio content should continue playing even after the user lowers their wrists or navigates to a new app. Your app needs to play audio in the background in order to provide this seamless playback experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To play background audio:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enable the Audio Background Mode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure and Activate the audio session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start playing.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Enable-the-Audio-Background-Mode",
          "level": 3,
          "text": "Enable the Audio Background Mode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "First, you must enable the Audio Background Mode capability for your WatchKit extension, as shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/watchkit/storyboard_support/playing_background_audio#3008217",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3008217",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This step sets the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-and-Activate-the-Audio-Session",
          "level": 3,
          "text": "Configure and Activate the Audio Session",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you can play audio, you need to set up and activate the audio session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Start by setting the session’s category to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the route policy to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "session.setCategory(AVAudioSession.Category.playback,",
            "                        mode: .default,",
            "                        policy: .longForm,",
            "                        options: [])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, activate the session, by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "session.activate(options: []) { (success, error) in",
            "    // Check for an error and play audio.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This method sets up the audio route asynchronously before activating your session. watchOS requires a Bluetooth audio route for long-form audio. If necessary, the system presents an audio route picker to the user, letting them choose the Bluetooth route (see ",
              "type": "text"
            },
            {
              "identifier": "/documentation/watchkit/storyboard_support/playing_background_audio#3016837",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3016837",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In general, if the user has previously selected a Bluetooth route or if AirPods or other W1-equipped Bluetooth headphones are nearby, the system picks the audio route automatically without displaying a picker view to the user. If no applicable Bluetooth route is selected (either automatically or by the user), the system passes an error to the completion handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-Playing",
          "level": 3,
          "text": "Start Playing",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method calls its completion handler as soon as a Bluetooth route is selected or when an error occurs. Check for errors in the completion handler. If no errors occurred, you can begin playing your audio content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code listing below shows all the steps needed to set up the session, activate it, and begin playing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set up the session.",
            "let session = AVAudioSession.sharedInstance()",
            "",
            "do {",
            "    try session.setCategory(AVAudioSession.Category.playback,",
            "                            mode: .default,",
            "                            policy: .longForm,",
            "                            options: [])",
            "} catch let error {",
            "    fatalError(\"*** Unable to set up the audio session: \\(error.localizedDescription) ***\")",
            "}",
            "",
            "// Set up the player.",
            "let player: AVAudioPlayer",
            "do {",
            "    player = try AVAudioPlayer(data: audioData)",
            "} catch let error {",
            "    print(\"*** Unable to set up the audio player: \\(error.localizedDescription) ***\")",
            "    // Handle the error here.",
            "    return",
            "}",
            "",
            "// Activate and request the route.",
            "session.activate(options: []) { (success, error) in",
            "    guard error == nil else {",
            "        print(\"*** An error occurred: \\(error!.localizedDescription) ***\")",
            "        // Handle the error here.",
            "        return",
            "    }",
            "    ",
            "    // Play the audio file.",
            "    player.play()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/watchkit/storyboard_support/playing_background_audio#3008217": {
      "identifier": "/documentation/watchkit/storyboard_support/playing_background_audio#3008217",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/watchkit/storyboard_support/playing_background_audio#3008217"
    },
    "/documentation/watchkit/storyboard_support/playing_background_audio#3016837": {
      "identifier": "/documentation/watchkit/storyboard_support/playing_background_audio#3016837",
      "title": "Figure 2",
      "titleInlineContent": [
        {
          "text": "Figure 2",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/watchkit/storyboard_support/playing_background_audio#3016837"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback": {
      "abstract": [
        {
          "text": "The category for playing recorded music or other sounds that are central to the successful use of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
      "kind": "symbol",
      "role": "symbol",
      "title": "playback",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm": {
      "abstract": [
        {
          "text": "A policy that routes output to the shared long-form audio output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longForm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionRouteSharingPolicy",
          "text": "RouteSharingPolicy"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm",
      "kind": "symbol",
      "role": "symbol",
      "title": "longForm",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)": {
      "abstract": [
        {
          "text": "Activates an audio session asynchronously on watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionActivationOptions",
          "text": "AVAudioSessionActivationOptions"
        },
        {
          "kind": "text",
          "text": " = [], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "activate(options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIBackgroundModes": {
      "abstract": [
        {
          "text": "Services provided by an app that require it to run in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIBackgroundModes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UIBackgroundModes"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKBackgroundModes": {
      "abstract": [
        {
          "text": "The services a watchOS app provides that require it to continue running in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKBackgroundModes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/WKBackgroundModes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/background-execution": {
      "abstract": [
        {
          "text": "Manage background sessions and tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/background-execution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Background execution",
      "type": "topic",
      "url": "/documentation/watchkit/background-execution"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/enabling-background-sessions": {
      "abstract": [
        {
          "text": "Enable the background mode for audio, location updates, remote notifications, or workouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/enabling-background-sessions",
      "kind": "article",
      "role": "article",
      "title": "Enabling Background Sessions",
      "type": "topic",
      "url": "/documentation/watchkit/enabling-background-sessions"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support": {
      "abstract": [
        {
          "text": "Connect your code to storyboard elements using interface controllers, interface objects, and event handlers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storyboard support",
      "type": "topic",
      "url": "/documentation/watchkit/storyboard-support"
    },
    "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes",
      "title": "UIBackgroundModes",
      "titleInlineContent": [
        {
          "text": "UIBackgroundModes",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes"
    },
    "media-3008217": {
      "alt": "A screenshot showing the Audio Background mode in your WatchKit extension’s Capabilities pane.",
      "identifier": "media-3008217",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7d74be7b7c19230d6b5ac07888532928/media-3008217@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9cb803216826d0882c4937845d078b52/media-3008217~dark@2x.png"
        }
      ]
    },
    "media-3016837": {
      "alt": "A screenshot of the audio rout picker, showing two different Bluetooth headphones.",
      "identifier": "media-3016837",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4624fc8a1f4add47a3a8bb5a395d48a8/media-3016837@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Background-sessions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/enabling-background-sessions",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIBackgroundModes"
      ],
      "title": "Background sessions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Background-sessions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/enabling-background-sessions",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIBackgroundModes"
              ],
              "title": "Background sessions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longForm/title",
          "value": "AVAudioSessionRouteSharingPolicyLongForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyLongForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/title",
          "value": "AVAudioSessionCategoryPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVAudioSessionCategory",
              "text": "AVAudioSessionCategory"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryPlayback"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1activate(options:completionHandler:)/title",
          "value": "activateWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1activate(options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "activateWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioSessionActivationOptions",
              "text": "AVAudioSessionActivationOptions"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "activated"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/playing-background-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/playing-background-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
