{
  "abstract": [
    {
      "text": "An error reported by WatchKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17WatchKitErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WatchKitError"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WatchKitError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WatchKitError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WatchKitError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError": {
      "abstract": [
        {
          "text": "An error reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code": {
      "abstract": [
        {
          "text": "Error codes reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled": {
      "abstract": [
        {
          "text": "An unresponsive delegate error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDelegateWatchKitRequestReplyNotCalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationDelegateWatchKitRequestReplyNotCalled",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/applicationdelegatewatchkitrequestreplynotcalled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed": {
      "abstract": [
        {
          "text": "A download error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "downloadFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/downloadfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/errordomain"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/invalidargument"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed": {
      "abstract": [
        {
          "text": "A media player error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayerFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaPlayerFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/mediaplayerfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed": {
      "abstract": [
        {
          "text": "An audio recording error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordingFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/recordingfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/unknown"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain": {
      "abstract": [
        {
          "text": "The domain for WatchKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "WatchKitErrorDomain",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterrordomain"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Accessing-Error-Codes",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled"
      ],
      "title": "Accessing Error Codes"
    },
    {
      "anchor": "Accessing-the-Error-Domain",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain"
      ],
      "title": "Accessing the Error Domain"
    },
    {
      "anchor": "Accessing-Error-Properties",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code"
      ],
      "title": "Accessing Error Properties"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/title",
          "value": "WatchKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitErrorDomain/title",
          "value": "WatchKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/watchkiterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
