{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WatchKit-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKI_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WKI_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKI_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKI_EXTERN",
      "type": "topic",
      "url": "/documentation/watchkit/wki_extern"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WK_AVAILABLE_WATCHOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WK_AVAILABLE_WATCHOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WK_AVAILABLE_WATCHOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "WK_AVAILABLE_WATCHOS_ONLY",
      "type": "topic",
      "url": "/documentation/watchkit/wk_available_watchos_only"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WATCHOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WK_DEPRECATED_WATCHOS"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WATCHOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "WK_DEPRECATED_WATCHOS",
      "type": "topic",
      "url": "/documentation/watchkit/wk_deprecated_watchos"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WK_DEPRECATED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "WK_DEPRECATED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/watchkit/wk_deprecated_with_replacement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKI_EXTERN",
                "doc://com.apple.watchkit/documentation/WatchKit/WK_AVAILABLE_WATCHOS_ONLY",
                "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WATCHOS",
                "doc://com.apple.watchkit/documentation/WatchKit/WK_DEPRECATED_WITH_REPLACEMENT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/watchkit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/watchkit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
