{
  "abstract": [
    {
      "text": "Tells the interface controller that the reduce motion status has changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityReduceMotionStatusDidChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@WKAccessibilityReduceMotionStatusDidChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "WKAccessibilityReduceMotionStatusDidChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAccessibilityReduceMotionStatusDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "WKAccessibilityReduceMotionStatusDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKAccessibilityReduceMotionStatusDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this notification to customize your application’s user interface for when reduced motion is enabled. You can also use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to determine whether reduced motion is enabled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Observe this notification using the default notification center. This notification doesn’t include a parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether reduced motion is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsReduceMotionEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsReduceMotionEnabled"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityIsReduceMotionEnabled()",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityisreducemotionenabled()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityReduceMotionStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "Tells the interface controller that the reduce motion status has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityReduceMotionStatusDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityReduceMotionStatusDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKAccessibilityReduceMotionStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityreducemotionstatusdidchangenotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged": {
      "abstract": [
        {
          "text": "Tells the interface controller that the VoiceOver status has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityVoiceOverStatusChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityVoiceOverStatusChanged"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityVoiceOverStatusChanged",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityvoiceoverstatuschanged"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged"
      ],
      "title": "Managing Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsReduceMotionEnabled()/title",
          "value": "WKAccessibilityIsReduceMotionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsReduceMotionEnabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityIsReduceMotionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityVoiceOverStatusChanged/title",
          "value": "WKAccessibilityVoiceOverStatusChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityVoiceOverStatusChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityVoiceOverStatusChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaccessibilityreducemotionstatusdidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
