{
  "abstract": [
    {
      "text": "Returns a Boolean value indicating whether VoiceOver is running.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsVoiceOverRunning()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@WKAccessibilityIsVoiceOverRunning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKAccessibilityIsVoiceOverRunning"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAccessibilityIsVoiceOverRunning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "WKAccessibilityIsVoiceOverRunning()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKAccessibilityIsVoiceOverRunning"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if VoiceOver is currently running or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if it is not.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use this function to customize your application’s UI specifically for VoiceOver users. For example, you might want UI elements that usually disappear quickly to persist onscreen for VoiceOver users. Note that you can also listen for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification to find out when VoiceOver starts and stops.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityImageRegion": {
      "abstract": [
        {
          "text": "An object that defines a portion of an image that you want to call out separately to an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityImageRegion"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityImageRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityImageRegion"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityImageRegion",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityimageregion"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether reduced motion is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsReduceMotionEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsReduceMotionEnabled"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityIsReduceMotionEnabled()",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityisreducemotionenabled()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsVoiceOverRunning()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether VoiceOver is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsVoiceOverRunning"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsVoiceOverRunning()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityIsVoiceOverRunning"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityIsVoiceOverRunning()",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityisvoiceoverrunning()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged": {
      "abstract": [
        {
          "text": "Tells the interface controller that the VoiceOver status has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAccessibilityVoiceOverStatusChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityVoiceOverStatusChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAccessibilityVoiceOverStatusChanged"
        }
      ],
      "role": "symbol",
      "title": "WKAccessibilityVoiceOverStatusChanged",
      "type": "topic",
      "url": "/documentation/watchkit/wkaccessibilityvoiceoverstatuschanged"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAlertAction": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a button displayed in an alert or action sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAlertAction"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAlertAction"
        }
      ],
      "role": "symbol",
      "title": "WKAlertAction",
      "type": "topic",
      "url": "/documentation/watchkit/wkalertaction"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController": {
      "abstract": [
        {
          "text": "A class that provides the infrastructure for managing the interface in a watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceController"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceController"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceController",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject": {
      "abstract": [
        {
          "text": "An object that provides information that is common to all interface objects in your watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceObject"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceObject"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceObject",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceobject"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/building-watchos-app-interfaces-using-the-storyboard": {
      "abstract": [
        {
          "text": "Create the user interface for your watchOS app by nesting stacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/building-watchos-app-interfaces-using-the-storyboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Building watchOS app Interfaces Using the Storyboard",
      "type": "topic",
      "url": "/documentation/watchkit/building-watchos-app-interfaces-using-the-storyboard"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface-basics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/building-watchos-app-interfaces-using-the-storyboard",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAlertAction",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityImageRegion",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()"
      ],
      "title": "User interface basics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKAccessibilityIsVoiceOverRunning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityIsVoiceOverRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface-basics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/building-watchos-app-interfaces-using-the-storyboard",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAlertAction",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityImageRegion",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAccessibilityIsReduceMotionEnabled()"
              ],
              "title": "User interface basics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKAccessibilityIsVoiceOverRunning"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if VoiceOver is currently running or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if it is not.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/title",
          "value": "WKInterfaceObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/title",
          "value": "WKInterfaceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityVoiceOverStatusChanged/title",
          "value": "WKAccessibilityVoiceOverStatusChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityVoiceOverStatusChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityVoiceOverStatusChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityImageRegion/title",
          "value": "WKAccessibilityImageRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityImageRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityImageRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityImageRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityImageRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsVoiceOverRunning()/title",
          "value": "WKAccessibilityIsVoiceOverRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsVoiceOverRunning()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityIsVoiceOverRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsReduceMotionEnabled()/title",
          "value": "WKAccessibilityIsReduceMotionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAccessibilityIsReduceMotionEnabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAccessibilityIsReduceMotionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertAction/title",
          "value": "WKAlertAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaccessibilityisvoiceoverrunning()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkaccessibilityisvoiceoverrunning()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
