{
  "abstract": [
    {
      "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WKApplicationDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKApplicationDelegate"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKApplicationDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "WKApplicationDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.watchkit/documentation/WatchKit/using-background-tasks"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement the delegate’s methods to respond to your app’s life-cycle events, such as the activation and deactivation of your app. You can also implement delegate methods to respond to background tasks, Siri intents, workout sessions, or Handoff activity from another devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add an app delegate, define a delegate class that subclasses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import WatchKit",
            "",
            "class MyWatchAppDelegate: NSObject, WKApplicationDelegate {",
            "",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then define an app delegate adaptor in your SwiftUI ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "",
            "@main",
            "struct MyWatchApp_Watch_AppApp: App {",
            "    @WKApplicationDelegateAdaptor var appDelegate: MyWatchAppDelegate",
            "    var body: some Scene {",
            "        WindowGroup {",
            "            NavigationStack {",
            "                ContentView()",
            "            }",
            "        }",
            "    }",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, implement the delegate methods you want to handle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/App": {
      "abstract": [
        {
          "text": "A type that represents the structure and behavior of an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "App"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App",
      "kind": "symbol",
      "role": "symbol",
      "title": "App",
      "type": "topic",
      "url": "/documentation/SwiftUI/App"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps with a single watchOS app target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()": {
      "abstract": [
        {
          "text": "Tells the delegate that the watchOS app is visible and processing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive"
        }
      ],
      "role": "symbol",
      "title": "applicationDidBecomeActive()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidbecomeactive()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has transitioned from the foreground to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground"
        }
      ],
      "role": "symbol",
      "title": "applicationDidEnterBackground()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidenterbackground()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        }
      ],
      "role": "symbol",
      "title": "applicationDidFinishLaunching()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidfinishlaunching()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()": {
      "abstract": [
        {
          "text": "Tells the delegate that the app is about to transition from the background to the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground"
        }
      ],
      "role": "symbol",
      "title": "applicationWillEnterForeground()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationwillenterforeground()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()": {
      "abstract": [
        {
          "text": "Tells the delegate that the system is about to deactivate the watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillResignActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillResignActive"
        }
      ],
      "role": "symbol",
      "title": "applicationWillResignActive()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationwillresignactive()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()": {
      "abstract": [
        {
          "text": "Tells the delegate that the device’s orientation has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOrientationDidChange"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceOrientationDidChange"
        }
      ],
      "role": "symbol",
      "title": "deviceOrientationDidChange()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/deviceorientationdidchange()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Apple Push Notification service (APNs) can’t successfully complete the registration process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFailToRegisterForRemoteNotificationsWithError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didFailToRegisterForRemoteNotificationsWithError:"
        }
      ],
      "role": "symbol",
      "title": "didFailToRegisterForRemoteNotificationsWithError(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/didfailtoregisterforremotenotificationswitherror(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didReceiveRemoteNotification(_:fetchCompletionHandler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a background notification has arrived.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didReceiveRemoteNotification"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "fetchCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKBackgroundFetchResult",
          "text": "WKBackgroundFetchResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didReceiveRemoteNotification(_:fetchCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didReceiveRemoteNotification:fetchCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "didReceiveRemoteNotification(_:fetchCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/didreceiveremotenotification(_:fetchcompletionhandler:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app successfully registered with Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didRegisterForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDeviceToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didRegisterForRemoteNotificationsWithDeviceToken:"
        }
      ],
      "role": "symbol",
      "title": "didRegisterForRemoteNotifications(withDeviceToken:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/didregisterforremotenotifications(withdevicetoken:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-1pfoc": {
      "abstract": [
        {
          "text": "Tells the delegate that the user started a workout session on the paired iPhone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutConfiguration",
          "text": "HKWorkoutConfiguration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-1pfoc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleWorkoutConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "handle(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handle(_:)-1pfoc"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-3kqsk": {
      "abstract": [
        {
          "text": "Responds to Handoff–related activity from Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-3kqsk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleActivity:"
        }
      ],
      "role": "symbol",
      "title": "handle(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handle(_:)-3kqsk"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-4vdjo": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has received one or more background tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKRefreshBackgroundTask",
          "text": "WKRefreshBackgroundTask"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-4vdjo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleBackgroundTasks:"
        }
      ],
      "role": "symbol",
      "title": "handle(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handle(_:)-4vdjo"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-7kiwx": {
      "abstract": [
        {
          "text": "Tells the delegate that the system launched your app to resume an extended runtime session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
          "text": "WKExtendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-7kiwx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleExtendedRuntimeSession:"
        }
      ],
      "role": "symbol",
      "title": "handle(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handle(_:)-7kiwx"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Responds to a Siri intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntentResponse",
          "text": "INIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleIntent:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "handle(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handle(_:completionhandler:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleActiveWorkoutRecovery()": {
      "abstract": [
        {
          "text": "Tells the delegate when the app relaunches after crashing during an active workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleActiveWorkoutRecovery"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleActiveWorkoutRecovery()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleActiveWorkoutRecovery"
        }
      ],
      "role": "symbol",
      "title": "handleActiveWorkoutRecovery()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handleactiveworkoutrecovery()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleRemoteNowPlayingActivity()": {
      "abstract": [
        {
          "text": "Tells the delegate when the user plays audio in the corresponding iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleRemoteNowPlayingActivity"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleRemoteNowPlayingActivity()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleRemoteNowPlayingActivity"
        }
      ],
      "role": "symbol",
      "title": "handleRemoteNowPlayingActivity()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handleremotenowplayingactivity()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleUserActivity(_:)": {
      "abstract": [
        {
          "text": "Responds to Handoff–related activity from complications and notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleUserActivity"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleUserActivity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleUserActivity:"
        }
      ],
      "role": "symbol",
      "title": "handleUserActivity(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/handleuseractivity(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()": {
      "abstract": [
        {
          "text": "Provides the top-level entry point for an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()",
      "kind": "symbol",
      "role": "symbol",
      "title": "main()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/main()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/userDidAcceptCloudKitShare(with:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has access to shared information in CloudKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDidAcceptCloudKitShare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKShareMetadata",
          "text": "CKShareMetadata"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/userDidAcceptCloudKitShare(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userDidAcceptCloudKitShareWithMetadata:"
        }
      ],
      "role": "symbol",
      "title": "userDidAcceptCloudKitShare(with:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/userdidacceptcloudkitshare(with:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates the application object and the application delegate, and sets up the app’s event cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationMain(_:_:_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationmain(_:_:_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKBackgroundFetchResult": {
      "abstract": [
        {
          "text": "The result of an attempt to download the content associated with a remote notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKBackgroundFetchResult"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKBackgroundFetchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKBackgroundFetchResult"
        }
      ],
      "role": "symbol",
      "title": "WKBackgroundFetchResult",
      "type": "topic",
      "url": "/documentation/watchkit/wkbackgroundfetchresult"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for extension-based apps running in watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "role": "symbol",
      "title": "WKExtension",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior of a WatchKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextensiondelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice": {
      "abstract": [
        {
          "text": "An object that provides information about the user’s Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceDevice",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacedevice"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project": {
      "abstract": [
        {
          "text": "Create a new watchOS project or add a watch target to an existing iOS project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a watchOS project",
      "type": "topic",
      "url": "/documentation/watchkit/setting-up-a-watchos-project"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/using-background-tasks": {
      "abstract": [
        {
          "text": "Handle scheduled update tasks in the background, and respond to background system interactions including Siri intents and incoming Bluetooth messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/using-background-tasks",
      "kind": "article",
      "role": "article",
      "title": "Using background tasks",
      "type": "topic",
      "url": "/documentation/watchkit/using-background-tasks"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle": {
      "abstract": [
        {
          "text": "Learn how the watchOS app life cycle operates and responds to life cycle notification methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle",
      "kind": "article",
      "role": "article",
      "title": "Working with the watchOS app life cycle",
      "type": "topic",
      "url": "/documentation/watchkit/working-with-the-watchos-app-life-cycle"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
      ],
      "title": "App structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Monitoring-state-changes",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()"
      ],
      "title": "Monitoring state changes"
    },
    {
      "anchor": "Responding-to-intents",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:completionHandler:)"
      ],
      "title": "Responding to intents"
    },
    {
      "anchor": "Setup-Now-Playing-interface",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleRemoteNowPlayingActivity()"
      ],
      "title": "Setup Now Playing interface"
    },
    {
      "anchor": "Handling-a-workout-session",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-1pfoc",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleActiveWorkoutRecovery()"
      ],
      "title": "Handling a workout session"
    },
    {
      "anchor": "Handling-background-tasks",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-4vdjo"
      ],
      "title": "Handling background tasks"
    },
    {
      "anchor": "Handling-extended-runtime-tasks",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-7kiwx"
      ],
      "title": "Handling extended runtime tasks"
    },
    {
      "anchor": "Managing-remote-notifications",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didReceiveRemoteNotification(_:fetchCompletionHandler:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKBackgroundFetchResult"
      ],
      "title": "Managing remote notifications"
    },
    {
      "anchor": "Coordinating-Handoff-activity",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleUserActivity(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-3kqsk"
      ],
      "title": "Coordinating Handoff activity"
    },
    {
      "anchor": "Accepting-CloudKit-shares",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/userDidAcceptCloudKitShare(with:)"
      ],
      "title": "Accepting CloudKit shares"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Monitoring-state-changes",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()"
              ],
              "title": "Monitoring state changes"
            },
            {
              "anchor": "Responding-to-intents",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:completionHandler:)"
              ],
              "title": "Responding to intents"
            },
            {
              "anchor": "Setup-Now-Playing-interface",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleRemoteNowPlayingActivity()"
              ],
              "title": "Setup Now Playing interface"
            },
            {
              "anchor": "Handling-a-workout-session",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-1pfoc",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleActiveWorkoutRecovery()"
              ],
              "title": "Handling a workout session"
            },
            {
              "anchor": "Handling-background-tasks",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-4vdjo"
              ],
              "title": "Handling background tasks"
            },
            {
              "anchor": "Handling-extended-runtime-tasks",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-7kiwx"
              ],
              "title": "Handling extended runtime tasks"
            },
            {
              "anchor": "Managing-remote-notifications",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didReceiveRemoteNotification(_:fetchCompletionHandler:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKBackgroundFetchResult"
              ],
              "title": "Managing remote notifications"
            },
            {
              "anchor": "Coordinating-Handoff-activity",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handleUserActivity(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/handle(_:)-3kqsk"
              ],
              "title": "Coordinating Handoff activity"
            },
            {
              "anchor": "Accepting-CloudKit-shares",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/userDidAcceptCloudKitShare(with:)"
              ],
              "title": "Accepting CloudKit shares"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
              ],
              "title": "App structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKApplicationDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleActiveWorkoutRecovery()/title",
          "value": "handleActiveWorkoutRecovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleActiveWorkoutRecovery()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleActiveWorkoutRecovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidBecomeActive()/title",
          "value": "applicationDidBecomeActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidBecomeActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidBecomeActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleUserActivity(_:)/title",
          "value": "handleUserActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleUserActivity(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleUserActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-1pfoc/title",
          "value": "handleWorkoutConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-1pfoc/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleWorkoutConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/title",
          "value": "WKExtensionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-7kiwx/title",
          "value": "handleExtendedRuntimeSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-7kiwx/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleExtendedRuntimeSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleRemoteNowPlayingActivity()/title",
          "value": "handleRemoteNowPlayingActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handleRemoteNowPlayingActivity()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleRemoteNowPlayingActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:completionHandler:)/title",
          "value": "handleIntent:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleIntent:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didReceiveRemoteNotification(_:fetchCompletionHandler:)/title",
          "value": "didReceiveRemoteNotification:fetchCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didReceiveRemoteNotification(_:fetchCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didReceiveRemoteNotification:fetchCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didRegisterForRemoteNotifications(withDeviceToken:)/title",
          "value": "didRegisterForRemoteNotificationsWithDeviceToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didRegisterForRemoteNotifications(withDeviceToken:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didRegisterForRemoteNotificationsWithDeviceToken:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillResignActive()/title",
          "value": "applicationWillResignActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillResignActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillResignActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillEnterForeground()/title",
          "value": "applicationWillEnterForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillEnterForeground()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillEnterForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/title",
          "value": "WKInterfaceDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/title",
          "value": "WKApplicationMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKBackgroundFetchResult/title",
          "value": "WKBackgroundFetchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKBackgroundFetchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKBackgroundFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKBackgroundFetchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKBackgroundFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-4vdjo/title",
          "value": "handleBackgroundTasks:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-4vdjo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleBackgroundTasks:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidEnterBackground()/title",
          "value": "applicationDidEnterBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidEnterBackground()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidEnterBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-3kqsk/title",
          "value": "handleActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1handle(_:)-3kqsk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1deviceOrientationDidChange()/title",
          "value": "deviceOrientationDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1deviceOrientationDidChange()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceOrientationDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/title",
          "value": "WKApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/title",
          "value": "applicationDidFinishLaunching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidFinishLaunching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didFailToRegisterForRemoteNotificationsWithError(_:)/title",
          "value": "didFailToRegisterForRemoteNotificationsWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didFailToRegisterForRemoteNotificationsWithError(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didFailToRegisterForRemoteNotificationsWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1userDidAcceptCloudKitShare(with:)/title",
          "value": "userDidAcceptCloudKitShareWithMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1userDidAcceptCloudKitShare(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "userDidAcceptCloudKitShareWithMetadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/title",
          "value": "WKExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkapplicationdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkapplicationdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
