{
  "abstract": [
    {
      "text": "An object that stores a reference to an audio file and provides metadata information about that file.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/AVFoundation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " framework’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVQueuePlayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKAudioFileAsset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKAudioFileAsset"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAudioFileAsset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "message": "Use AVFoundation's AVPlayer and AVQueuePlayer instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKAudioFileAsset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKAudioFileAsset"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create assets when you want to play audio from your watchOS app. Use the audio file asset object to store the location of the file and any Now Playing information you want displayed while the audio is playing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Audio assets must refer to files on the local file system. If you have audio files that are stored on a server, you must download them to the user’s Apple Watch before attempting to play them using an audio file asset object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It is recommended that you encode audio files using 32 kbps stereo AAC. You may use other bit rates, or the LPCM encoding, as preferred for your content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To play an audio file asset, wrap it in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The player item object stores information about the playback status of the asset and works with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to coordinate playback. If you want to queue several audio files for playback, you manage those items using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/AVFoundation"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVQueuePlayer": {
      "abstract": [
        {
          "text": "An object that plays a sequence of player items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVQueuePlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVQueuePlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVQueuePlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVQueuePlayer"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a watchOS app should opt out of automatically launching when its companion iOS app starts playing audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "PUICAutoLaunchAudioOptOut",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset": {
      "abstract": [
        {
          "text": "An object that stores a reference to an audio file and provides metadata information about that file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFileAsset"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFileAsset"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFileAsset",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/albumTitle": {
      "abstract": [
        {
          "text": "The album title information for the audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/albumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "albumTitle"
        }
      ],
      "role": "symbol",
      "title": "albumTitle",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/albumtitle"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/artist": {
      "abstract": [
        {
          "text": "The artist information for the audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/artist"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/duration": {
      "abstract": [
        {
          "text": "The duration (in seconds) of the audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/duration"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:)": {
      "abstract": [
        {
          "text": "Returns an asset for the audio file at the specified URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetWithURL:"
        }
      ],
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/init(url:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:title:albumTitle:artist:)": {
      "abstract": [
        {
          "text": "Returns an audio file asset and sets the metadata for that item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "albumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:title:albumTitle:artist:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetWithURL:title:albumTitle:artist:"
        }
      ],
      "role": "symbol",
      "title": "init(url:title:albumTitle:artist:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/init(url:title:albumtitle:artist:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/title": {
      "abstract": [
        {
          "text": "The title information for the audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/title"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/url": {
      "abstract": [
        {
          "text": "The URL of the audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileasset/url"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer": {
      "abstract": [
        {
          "text": "An object that controls playback of a single audio item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayer"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayer",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem": {
      "abstract": [
        {
          "text": "An object that manages the presentation state of an audio file while it is playing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerItem"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerItem"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerItem",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayeritem"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer": {
      "abstract": [
        {
          "text": "An object that controls playback of one or more audio items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFileQueuePlayer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFileQueuePlayer"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFileQueuePlayer",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofilequeueplayer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceVolumeControl": {
      "abstract": [
        {
          "text": "An interface element that provides control of the audio volume from the watch or a paired iPhone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceVolumeControl"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceVolumeControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceVolumeControl"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceVolumeControl",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacevolumecontrol"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/adding-a-now-playing-view": {
      "abstract": [
        {
          "text": "Provide a view that controls the currently playing audio from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/adding-a-now-playing-view",
      "kind": "article",
      "role": "article",
      "title": "Adding a Now Playing View",
      "type": "topic",
      "url": "/documentation/watchkit/adding-a-now-playing-view"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/playing-background-audio": {
      "abstract": [
        {
          "text": "Enable background audio in your app to provide a seamless playback experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/playing-background-audio",
      "kind": "article",
      "role": "article",
      "title": "Playing Background Audio",
      "type": "topic",
      "url": "/documentation/watchkit/playing-background-audio"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/playing-background-audio",
        "doc://com.apple.watchkit/documentation/WatchKit/adding-a-now-playing-view",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceVolumeControl",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem"
      ],
      "title": "Audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Asset",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:title:albumTitle:artist:)"
      ],
      "title": "Creating an Asset"
    },
    {
      "anchor": "Getting-the-Assets-Properties",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/url",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/duration",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/title",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/albumTitle",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/artist"
      ],
      "title": "Getting the Asset’s Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKAudioFileAsset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Asset",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/init(url:title:albumTitle:artist:)"
              ],
              "title": "Creating an Asset"
            },
            {
              "anchor": "Getting-the-Assets-Properties",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/url",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/duration",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/title",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/albumTitle",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileAsset/artist"
              ],
              "title": "Getting the Asset’s Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/playing-background-audio",
                "doc://com.apple.watchkit/documentation/WatchKit/adding-a-now-playing-view",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceVolumeControl",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFileQueuePlayer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem"
              ],
              "title": "Audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKAudioFileAsset"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFoundation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVQueuePlayer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " classes instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/title",
          "value": "WKAudioFilePlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset/title",
          "value": "WKAudioFileAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1artist/title",
          "value": "artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1init(url:)/title",
          "value": "assetWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1init(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "assetWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/title",
          "value": "WKAudioFileQueuePlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileQueuePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileQueuePlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFileQueuePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/title",
          "value": "WKAudioFilePlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1init(url:title:albumTitle:artist:)/title",
          "value": "assetWithURL:title:albumTitle:artist:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1init(url:title:albumTitle:artist:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "assetWithURL:title:albumTitle:artist:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceVolumeControl/title",
          "value": "WKInterfaceVolumeControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceVolumeControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceVolumeControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceVolumeControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceVolumeControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVQueuePlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVQueuePlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVPlayer",
              "text": "AVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1albumTitle/title",
          "value": "albumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1albumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "albumTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFileAsset~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaudiofileasset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkaudiofileasset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
