{
  "abstract": [
    {
      "text": "The error codes reported by extended runtime sessions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKExtendedRuntimeSessionErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionErrorCode"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKExtendedRuntimeSessionErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The session passes these errors to the sesson delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)": {
      "abstract": [
        {
          "text": "Indicates that the session has encountered an error or stopped running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
          "text": "WKExtendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didInvalidateWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKExtendedRuntimeSessionInvalidationReason",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedRuntimeSession:didInvalidateWithReason:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "extendedRuntimeSession(_:didInvalidateWith:error:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessiondelegate/extendedruntimesession(_:didinvalidatewith:error:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode": {
      "abstract": [
        {
          "text": "The error codes reported by extended runtime sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled": {
      "abstract": [
        {
          "text": "The user has disabled background app refresh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barDisabled"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorBARDisabled"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.barDisabled",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/bardisabled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits": {
      "abstract": [
        {
          "text": "The session exceeded its resource limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceededResourceLimits"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.exceededResourceLimits",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/exceededresourcelimits"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/init(rawvalue:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToPrompt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mustBeActiveToPrompt"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToPrompt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorMustBeActiveToPrompt"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.mustBeActiveToPrompt",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/mustbeactivetoprompt"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule": {
      "abstract": [
        {
          "text": "The watchOS app attempted to start or schedule a session while not in an active state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mustBeActiveToStartOrSchedule"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.mustBeActiveToStartOrSchedule",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/mustbeactivetostartorschedule"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule": {
      "abstract": [
        {
          "text": "The app attempted to schedule a session, but the session type does not support scheduling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApprovedToSchedule"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notApprovedToSchedule",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notapprovedtoschedule"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession": {
      "abstract": [
        {
          "text": "The app attempted to start a session, but doesn’t have a valid session type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApprovedToStartSession"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notApprovedToStartSession",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notapprovedtostartsession"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted": {
      "abstract": [
        {
          "text": "The app invalidated the session before it started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notYetStarted"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorNotYetStarted"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.notYetStarted",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/notyetstarted"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance": {
      "abstract": [
        {
          "text": "The app attempted to schedule a session too far in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledTooFarInAdvance"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.scheduledTooFarInAdvance",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/scheduledtoofarinadvance"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.unknown",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/unknown"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unsupportedSessionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedSessionType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unsupportedSessionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorUnsupportedSessionType"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorCode.unsupportedSessionType",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrorcode/unsupportedsessiontype"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors reported by extended runtime sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionErrorDomain",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessionerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorDomain"
      ],
      "title": "Handling Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToPrompt",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unsupportedSessionType"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKExtendedRuntimeSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unknown",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/scheduledTooFarInAdvance",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToStartOrSchedule",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notYetStarted",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/exceededResourceLimits",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/barDisabled",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToStartSession",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/notApprovedToSchedule"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/mustBeActiveToPrompt",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorCode/unsupportedSessionType"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionErrorDomain"
              ],
              "title": "Handling Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKExtendedRuntimeSessionErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unknown/title",
          "value": "WKExtendedRuntimeSessionErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unsupportedSessionType/title",
          "value": "WKExtendedRuntimeSessionErrorUnsupportedSessionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1unsupportedSessionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorUnsupportedSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSession(_:didInvalidateWith:error:)/title",
          "value": "extendedRuntimeSession:didInvalidateWithReason:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSession(_:didInvalidateWith:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendedRuntimeSession:didInvalidateWithReason:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notYetStarted/title",
          "value": "WKExtendedRuntimeSessionErrorNotYetStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notYetStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotYetStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToStartSession/title",
          "value": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToStartSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotApprovedToStartSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1barDisabled/title",
          "value": "WKExtendedRuntimeSessionErrorBARDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1barDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorBARDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/title",
          "value": "WKExtendedRuntimeSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1scheduledTooFarInAdvance/title",
          "value": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1scheduledTooFarInAdvance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorScheduledTooFarInAdvance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToPrompt/title",
          "value": "WKExtendedRuntimeSessionErrorMustBeActiveToPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToPrompt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorMustBeActiveToPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorDomain/title",
          "value": "WKExtendedRuntimeSessionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToStartOrSchedule/title",
          "value": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1mustBeActiveToStartOrSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorMustBeActiveToStartOrSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToSchedule/title",
          "value": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1notApprovedToSchedule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorNotApprovedToSchedule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1exceededResourceLimits/title",
          "value": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionErrorCode~1exceededResourceLimits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionErrorExceededResourceLimits"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessionerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessionerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
