{
  "abstract": [
    {
      "text": "The reasons why a session can become invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKExtendedRuntimeSessionInvalidationReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionInvalidationReason"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionInvalidationReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKExtendedRuntimeSessionInvalidationReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sessions become invalid when they encounter an error, or when they stop running.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)": {
      "abstract": [
        {
          "text": "Indicates that the session has encountered an error or stopped running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
          "text": "WKExtendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didInvalidateWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKExtendedRuntimeSessionInvalidationReason",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedRuntimeSession:didInvalidateWithReason:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "extendedRuntimeSession(_:didInvalidateWith:error:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessiondelegate/extendedruntimesession(_:didinvalidatewith:error:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionDidStart(_:)": {
      "abstract": [
        {
          "text": "Indicates that the session has started running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedRuntimeSessionDidStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
          "text": "WKExtendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionDidStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedRuntimeSessionDidStart:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "extendedRuntimeSessionDidStart(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessiondelegate/extendedruntimesessiondidstart(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionWillExpire(_:)": {
      "abstract": [
        {
          "text": "Indicates that the session is about to expire.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedRuntimeSessionWillExpire"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
          "text": "WKExtendedRuntimeSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionWillExpire(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedRuntimeSessionWillExpire:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "extendedRuntimeSessionWillExpire(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessiondelegate/extendedruntimesessionwillexpire(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason": {
      "abstract": [
        {
          "text": "The reasons why a session can become invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error": {
      "abstract": [
        {
          "text": "An error prevented the session from running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonError"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.error",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/error"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired": {
      "abstract": [
        {
          "text": "The session used all of its allocated time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expired"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.expired",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/expired"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/init(rawvalue:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none": {
      "abstract": [
        {
          "text": "The session ended normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonNone"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.none",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/none"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost": {
      "abstract": [
        {
          "text": "The app lost its frontmost status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resignedFrontmost"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.resignedFrontmost",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/resignedfrontmost"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress": {
      "abstract": [
        {
          "text": "This app already has a running session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionInProgress"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.sessionInProgress",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/sessioninprogress"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem": {
      "abstract": [
        {
          "text": "The system is in a state that doesn’t allow sessions of this type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suppressedBySystem"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.suppressedBySystem",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/suppressedbysystem"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Monitoring-State-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionDidStart(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionWillExpire(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)"
      ],
      "title": "Monitoring State Changes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Invalidation-Reasons",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem"
      ],
      "title": "Invalidation Reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKExtendedRuntimeSessionInvalidationReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Invalidation-Reasons",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem"
              ],
              "title": "Invalidation Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Monitoring-State-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionDidStart(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSessionWillExpire(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate/extendedRuntimeSession(_:didInvalidateWith:error:)"
              ],
              "title": "Monitoring State Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKExtendedRuntimeSessionInvalidationReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1error/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1expired/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1expired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1suppressedBySystem/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1suppressedBySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1sessionInProgress/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1sessionInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSessionDidStart(_:)/title",
          "value": "extendedRuntimeSessionDidStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSessionDidStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendedRuntimeSessionDidStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1none/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/title",
          "value": "WKExtendedRuntimeSessionInvalidationReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSession(_:didInvalidateWith:error:)/title",
          "value": "extendedRuntimeSession:didInvalidateWithReason:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSession(_:didInvalidateWith:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendedRuntimeSession:didInvalidateWithReason:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1resignedFrontmost/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1resignedFrontmost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSessionWillExpire(_:)/title",
          "value": "extendedRuntimeSessionWillExpire:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate~1extendedRuntimeSessionWillExpire(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendedRuntimeSessionWillExpire:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessioninvalidationreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessioninvalidationreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
