{
  "abstract": [
    {
      "text": "The centralized point of control and coordination for extension-based apps running in watchOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKExtension",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKExtension"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKExtension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKExtension"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode 13 and earlier the system divides a watchOS app into two sections:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An app bundle that contains your app icon. For storyboard-based apps, it also includes your storyboard and any assets used by the storyboard.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "WatchKit app",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An extension that contains your watchOS app’s code.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "WatchKit extension",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode 14 and later, you can produce watchOS apps with a single watchOS app target for code, assets, extensions, and localizations. These single-target watchOS apps can run on watchOS 7 and later",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apps with separate WatchKit app and extensions have a single extension object. While the system creates and manages this object, you can access it to perform app-level tasks such as opening URLs and getting the root interface controller of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As relevant events occur within your WatchKit app, the extension object notifies its delegate of those events. Your delegate object can implement the methods it needs to provide an appropriate response to life cycle events, handle notifications, or handle Handoff–related behaviors. For more information about the methods of the delegate, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps with a single watchOS app target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates the application object and the application delegate, and sets up the app’s event cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationMain(_:_:_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationmain(_:_:_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationState": {
      "abstract": [
        {
          "text": "The running states of the Watch app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationState"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationState"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationState",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for extension-based apps running in watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "role": "symbol",
      "title": "WKExtension",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidBecomeActiveNotification": {
      "abstract": [
        {
          "text": "A message indicating that the watchOS app is visible and processing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActiveNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidBecomeActiveNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDidBecomeActiveNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationDidBecomeActiveNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationdidbecomeactivenotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidEnterBackgroundNotification": {
      "abstract": [
        {
          "text": "A message indicating that the watchOS app transitioned from the foreground to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackgroundNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidEnterBackgroundNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDidEnterBackgroundNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationDidEnterBackgroundNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationdidenterbackgroundnotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidFinishLaunchingNotification": {
      "abstract": [
        {
          "text": "A message indicating that the launch process finished and the extension is ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunchingNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidFinishLaunchingNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDidFinishLaunchingNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationDidFinishLaunchingNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationdidfinishlaunchingnotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationState": {
      "abstract": [
        {
          "text": "The runtime state of the Watch app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKApplicationState",
          "text": "WKApplicationState"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationState"
        }
      ],
      "role": "symbol",
      "title": "applicationState",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillEnterForegroundNotification": {
      "abstract": [
        {
          "text": "A message indicating that the watchOS app is about to transition from the background to the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillEnterForegroundNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillEnterForegroundNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationWillEnterForegroundNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationWillEnterForegroundNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationwillenterforegroundnotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillResignActiveNotification": {
      "abstract": [
        {
          "text": "A message indicating that the system is about to deactivate the watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillResignActiveNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillResignActiveNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationWillResignActiveNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationWillResignActiveNotification",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/applicationwillresignactivenotification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/delegate": {
      "abstract": [
        {
          "text": "The delegate of the WatchKit extension object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKExtensionDelegate",
          "text": "WKExtensionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/delegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/enableWaterLock()": {
      "abstract": [
        {
          "text": "Disables the Apple Watch touch screen to prevent accidental taps while the watch is underwater.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableWaterLock"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/enableWaterLock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableWaterLock"
        }
      ],
      "role": "symbol",
      "title": "enableWaterLock()",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/enablewaterlock()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/globalTintColor": {
      "abstract": [
        {
          "text": "The watchOS app’s global tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "globalTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/globalTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "globalTintColor"
        }
      ],
      "role": "symbol",
      "title": "globalTintColor",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/globaltintcolor"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isApplicationRunningInDock": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app is running in the dock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isApplicationRunningInDock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isApplicationRunningInDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isApplicationRunningInDock"
        }
      ],
      "role": "symbol",
      "title": "isApplicationRunningInDock",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/isapplicationrunningindock"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotated": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system has automatically rotated the user interface so that it is properly oriented for another viewer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutorotated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autorotated"
        }
      ],
      "role": "symbol",
      "title": "isAutorotated",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/isautorotated"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotating": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the interface automatically rotates when the user flips their wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutorotating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autorotating"
        }
      ],
      "role": "symbol",
      "title": "isAutorotating",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/isautorotating"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isFrontmostTimeoutExtended": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the app extends its time as the frontmost app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFrontmostTimeoutExtended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isFrontmostTimeoutExtended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frontmostTimeoutExtended"
        }
      ],
      "role": "symbol",
      "title": "isFrontmostTimeoutExtended",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/isfrontmosttimeoutextended"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isRegisteredForRemoteNotifications": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the app has successfully registered for remote notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRegisteredForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isRegisteredForRemoteNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registeredForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "isRegisteredForRemoteNotifications",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/isregisteredforremotenotifications"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/openSystemURL(_:)": {
      "abstract": [
        {
          "text": "Opens the specified system URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openSystemURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/openSystemURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openSystemURL:"
        }
      ],
      "role": "symbol",
      "title": "openSystemURL(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/opensystemurl(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/registerForRemoteNotifications()": {
      "abstract": [
        {
          "text": "Register to receive remote notifications from the Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/registerForRemoteNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "registerForRemoteNotifications()",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/registerforremotenotifications()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/rootInterfaceController": {
      "abstract": [
        {
          "text": "The app’s root interface controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rootInterfaceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKInterfaceController",
          "text": "WKInterfaceController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/rootInterfaceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rootInterfaceController"
        }
      ],
      "role": "symbol",
      "title": "rootInterfaceController",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/rootinterfacecontroller"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)": {
      "abstract": [
        {
          "text": "Schedules a background task to refresh the app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleBackgroundRefresh"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPreferredDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSecureCoding",
          "text": "NSSecureCoding"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "scheduledCompletion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleBackgroundRefreshWithPreferredDate:userInfo:scheduledCompletion:"
        }
      ],
      "role": "symbol",
      "title": "scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/schedulebackgroundrefresh(withpreferreddate:userinfo:scheduledcompletion:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)": {
      "abstract": [
        {
          "text": "Schedules a background task to refresh your app’s snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleSnapshotRefresh"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPreferredDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSecureCoding",
          "text": "NSSecureCoding"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "scheduledCompletion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleSnapshotRefreshWithPreferredDate:userInfo:scheduledCompletion:"
        }
      ],
      "role": "symbol",
      "title": "scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/schedulesnapshotrefresh(withpreferreddate:userinfo:scheduledcompletion:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/shared()": {
      "abstract": [
        {
          "text": "Returns the shared WatchKit extension object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKExtension",
          "text": "WKExtension"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedExtension"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/shared()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/unregisterForRemoteNotifications()": {
      "abstract": [
        {
          "text": "Unregister for all remote notifications received from Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/unregisterForRemoteNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "unregisterForRemoteNotifications()",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/unregisterforremotenotifications()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/visibleInterfaceController": {
      "abstract": [
        {
          "text": "Returns the last visible interface controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleInterfaceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKInterfaceController",
          "text": "WKInterfaceController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/visibleInterfaceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibleInterfaceController"
        }
      ],
      "role": "symbol",
      "title": "visibleInterfaceController",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension/visibleinterfacecontroller"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior of a WatchKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextensiondelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice": {
      "abstract": [
        {
          "text": "An object that provides information about the user’s Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceDevice",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacedevice"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project": {
      "abstract": [
        {
          "text": "Create a new watchOS project or add a watch target to an existing iOS project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a watchOS project",
      "type": "topic",
      "url": "/documentation/watchkit/setting-up-a-watchos-project"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
      ],
      "title": "App structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-extension-object",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/shared()"
      ],
      "title": "Getting the extension object"
    },
    {
      "anchor": "Accessing-the-extension-delegate",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/delegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate"
      ],
      "title": "Accessing the extension delegate"
    },
    {
      "anchor": "Opening-a-URL-resource",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/openSystemURL(_:)"
      ],
      "title": "Opening a URL resource"
    },
    {
      "anchor": "Getting-the-interface-controllers",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/rootInterfaceController",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/visibleInterfaceController"
      ],
      "title": "Getting the interface controllers"
    },
    {
      "anchor": "Managing-the-execution-state",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isApplicationRunningInDock",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isFrontmostTimeoutExtended"
      ],
      "title": "Managing the execution state"
    },
    {
      "anchor": "Managing-the-user-interface",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotating",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotated",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/globalTintColor",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/enableWaterLock()"
      ],
      "title": "Managing the user interface"
    },
    {
      "anchor": "Managing-the-snapshot",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)"
      ],
      "title": "Managing the snapshot"
    },
    {
      "anchor": "Observing-messages-from-the-notification-center",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidFinishLaunchingNotification",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidBecomeActiveNotification",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillResignActiveNotification",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillEnterForegroundNotification",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidEnterBackgroundNotification"
      ],
      "title": "Observing messages from the notification center"
    },
    {
      "anchor": "Registering-for-remote-notifications",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/registerForRemoteNotifications()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/unregisterForRemoteNotifications()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isRegisteredForRemoteNotifications"
      ],
      "title": "Registering for remote notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKExtension"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-extension-object",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/shared()"
              ],
              "title": "Getting the extension object"
            },
            {
              "anchor": "Accessing-the-extension-delegate",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/delegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate"
              ],
              "title": "Accessing the extension delegate"
            },
            {
              "anchor": "Opening-a-URL-resource",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/openSystemURL(_:)"
              ],
              "title": "Opening a URL resource"
            },
            {
              "anchor": "Getting-the-interface-controllers",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/rootInterfaceController",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/visibleInterfaceController"
              ],
              "title": "Getting the interface controllers"
            },
            {
              "anchor": "Managing-the-execution-state",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isApplicationRunningInDock",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isFrontmostTimeoutExtended"
              ],
              "title": "Managing the execution state"
            },
            {
              "anchor": "Managing-the-user-interface",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotating",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isAutorotated",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/globalTintColor",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/enableWaterLock()"
              ],
              "title": "Managing the user interface"
            },
            {
              "anchor": "Managing-the-snapshot",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)"
              ],
              "title": "Managing the snapshot"
            },
            {
              "anchor": "Observing-messages-from-the-notification-center",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidFinishLaunchingNotification",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidBecomeActiveNotification",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillResignActiveNotification",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationWillEnterForegroundNotification",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/applicationDidEnterBackgroundNotification"
              ],
              "title": "Observing messages from the notification center"
            },
            {
              "anchor": "Registering-for-remote-notifications",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/registerForRemoteNotifications()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/unregisterForRemoteNotifications()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension/isRegisteredForRemoteNotifications"
              ],
              "title": "Registering for remote notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
              ],
              "title": "App structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKExtension"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1enableWaterLock()/title",
          "value": "enableWaterLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1enableWaterLock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableWaterLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1registerForRemoteNotifications()/title",
          "value": "registerForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1registerForRemoteNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isRegisteredForRemoteNotifications/title",
          "value": "registeredForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isRegisteredForRemoteNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "registeredForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isAutorotated/title",
          "value": "autorotated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isAutorotated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autorotated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationState/title",
          "value": "applicationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isAutorotating/title",
          "value": "autorotating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isAutorotating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autorotating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/title",
          "value": "WKApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidBecomeActiveNotification/title",
          "value": "WKApplicationDidBecomeActiveNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidBecomeActiveNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDidBecomeActiveNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isApplicationRunningInDock/title",
          "value": "isApplicationRunningInDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isApplicationRunningInDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isApplicationRunningInDock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/title",
          "value": "WKExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/title",
          "value": "WKApplicationMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)/title",
          "value": "scheduleBackgroundRefreshWithPreferredDate:userInfo:scheduledCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1scheduleBackgroundRefresh(withPreferredDate:userInfo:scheduledCompletion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleBackgroundRefreshWithPreferredDate:userInfo:scheduledCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1unregisterForRemoteNotifications()/title",
          "value": "unregisterForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1unregisterForRemoteNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unregisterForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidFinishLaunchingNotification/title",
          "value": "WKApplicationDidFinishLaunchingNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidFinishLaunchingNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDidFinishLaunchingNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1openSystemURL(_:)/title",
          "value": "openSystemURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1openSystemURL(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openSystemURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isFrontmostTimeoutExtended/title",
          "value": "frontmostTimeoutExtended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1isFrontmostTimeoutExtended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frontmostTimeoutExtended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationWillResignActiveNotification/title",
          "value": "WKApplicationWillResignActiveNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationWillResignActiveNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationWillResignActiveNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1rootInterfaceController/title",
          "value": "rootInterfaceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1rootInterfaceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rootInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1shared()/title",
          "value": "sharedExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationWillEnterForegroundNotification/title",
          "value": "WKApplicationWillEnterForegroundNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationWillEnterForegroundNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationWillEnterForegroundNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationState/title",
          "value": "WKApplicationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/title",
          "value": "WKExtensionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidEnterBackgroundNotification/title",
          "value": "WKApplicationDidEnterBackgroundNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1applicationDidEnterBackgroundNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDidEnterBackgroundNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/title",
          "value": "WKInterfaceDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1visibleInterfaceController/title",
          "value": "visibleInterfaceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1visibleInterfaceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibleInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1globalTintColor/title",
          "value": "globalTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1globalTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "globalTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)/title",
          "value": "scheduleSnapshotRefreshWithPreferredDate:userInfo:scheduledCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension~1scheduleSnapshotRefresh(withPreferredDate:userInfo:scheduledCompletion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleSnapshotRefreshWithPreferredDate:userInfo:scheduledCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
