{
  "abstract": [
    {
      "text": "An interface element that displays a noninteractive map for the location you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKInterfaceMap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKInterfaceMap"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKInterfaceMap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKInterfaceMap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKInterfaceMap"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can configure Maps dynamically from your interface controller. Use the methods of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to specify the visible region of the map and to add any annotations or points of interest. Tapping the map launches the Maps app on the user’s Apple Watch and displays the corresponding location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using a map object, you specify a geographic region to display and you can optionally add annotations to the surface of the map. Maps display annotations as images on top of the map content. You can use custom images or display the built-in pin images. Maps can display no more than five annotations at a time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t subclass or create instances of this class yourself. Instead, define outlets in your interface controller class and connect them to the corresponding objects in your storyboard file. For example, to refer to a map object in your interface, define a property with the following syntax in your interface controller class:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "@IBOutlet weak var myMap: WKInterfaceMap!"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "@property (weak, nonatomic) IBOutlet WKInterfaceMap* myMap;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "During the initialization of your interface controller, WatchKit creates a new instance of this class and assigns it to your outlet. At that point, you can use the object in your outlet to make changes to the onscreen map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Apple Watch must have an active network connection to download map tiles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-Map-in-Interface-Builder",
          "level": 3,
          "text": "Configure the Map in Interface Builder",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode, you can configure information about your map from your storyboard file. The map interface object has an Enabled attribute that appears as a checkbox in the Attributes inspector. When you enable the map interface object in this checkbox, tapping the map launches the Maps app and displays the current selected location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceActivityRing": {
      "abstract": [
        {
          "text": "A view that displays data from a HealthKit activity summary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceActivityRing"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceActivityRing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceActivityRing"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceActivityRing",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceactivityring"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton": {
      "abstract": [
        {
          "text": "A button that you can use to trigger a Sign in with Apple request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceAuthorizationAppleIDButton"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceAuthorizationAppleIDButton"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceAuthorizationAppleIDButton",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceauthorizationappleidbutton"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceButton": {
      "abstract": [
        {
          "text": "A button in the user interface of your watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceButton"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceButton"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceButton",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacebutton"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate": {
      "abstract": [
        {
          "text": "A label that displays the current date or time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceDate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceDate"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceDate",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacedate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceLabel": {
      "abstract": [
        {
          "text": "An interface element that displays static text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceLabel"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceLabel"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceLabel",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacelabel"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap": {
      "abstract": [
        {
          "text": "An interface element that displays a noninteractive map for the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceMap"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceMap"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceMap",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/UserTrackingMode": {
      "abstract": [
        {
          "text": "Modes for tracking the user’s location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserTrackingMode"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/UserTrackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserTrackingMode"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceMap.UserTrackingMode",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/usertrackingmode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)": {
      "abstract": [
        {
          "text": "Adds a pin to the map at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAnnotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKInterfaceMapPinColor",
          "text": "WKInterfaceMapPinColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAnnotation:withPinColor:"
        }
      ],
      "role": "symbol",
      "title": "addAnnotation(_:with:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/addannotation(_:with:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)": {
      "abstract": [
        {
          "text": "Displays the specified image on top of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAnnotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "centerOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAnnotation:withImage:centerOffset:"
        }
      ],
      "role": "symbol",
      "title": "addAnnotation(_:with:centerOffset:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/addannotation(_:with:centeroffset:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)": {
      "abstract": [
        {
          "text": "Displays an image from the WatchKit app’s bundle on top of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAnnotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withImageNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "centerOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAnnotation:withImageNamed:centerOffset:"
        }
      ],
      "role": "symbol",
      "title": "addAnnotation(_:withImageNamed:centerOffset:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/addannotation(_:withimagenamed:centeroffset:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/init()": {
      "abstract": [
        {
          "text": "Creates a map for use in SwiftUI.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/init()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()": {
      "abstract": [
        {
          "text": "Removes all annotations from the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllAnnotations"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllAnnotations"
        }
      ],
      "role": "symbol",
      "title": "removeAllAnnotations()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/removeallannotations()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setRegion(_:)": {
      "abstract": [
        {
          "text": "Changes the map’s visible region to the specified coordinate region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRegion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKCoordinateRegion",
          "text": "MKCoordinateRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setRegion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRegion:"
        }
      ],
      "role": "symbol",
      "title": "setRegion(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/setregion(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserHeading(_:)": {
      "abstract": [
        {
          "text": "Sets whether the map shows the user heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setShowsUserHeading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserHeading(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShowsUserHeading:"
        }
      ],
      "role": "symbol",
      "title": "setShowsUserHeading(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/setshowsuserheading(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserLocation(_:)": {
      "abstract": [
        {
          "text": "Sets whether the map shows the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setShowsUserLocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserLocation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShowsUserLocation:"
        }
      ],
      "role": "symbol",
      "title": "setShowsUserLocation(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/setshowsuserlocation(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setUserTrackingMode(_:animated:)": {
      "abstract": [
        {
          "text": "Sets the map’s tracking mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setUserTrackingMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKInterfaceMap",
          "text": "WKInterfaceMap"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKInterfaceMapUserTrackingMode",
          "text": "UserTrackingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setUserTrackingMode(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setUserTrackingMode:animated:"
        }
      ],
      "role": "symbol",
      "title": "setUserTrackingMode(_:animated:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/setusertrackingmode(_:animated:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setVisibleMapRect(_:)": {
      "abstract": [
        {
          "text": "Changes the map’s visible region to the specified map rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVisibleMapRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapRect",
          "text": "MKMapRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setVisibleMapRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVisibleMapRect:"
        }
      ],
      "role": "symbol",
      "title": "setVisibleMapRect(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemap/setvisiblemaprect(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor": {
      "abstract": [
        {
          "text": "Constants for map pin colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceMapPinColor"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceMapPinColor"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceMapPinColor",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacemappincolor"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject": {
      "abstract": [
        {
          "text": "An object that provides information that is common to all interface objects in your watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceObject"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceObject"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceObject",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceobject"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePaymentButton": {
      "abstract": [
        {
          "text": "A button that you can use to trigger payments through Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfacePaymentButton"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePaymentButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfacePaymentButton"
        }
      ],
      "role": "symbol",
      "title": "WKInterfacePaymentButton",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacepaymentbutton"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSlider": {
      "abstract": [
        {
          "text": "An interface element that lets users select a single floating-point value from a range of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceSlider"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSlider"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSlider",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceslider"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSwitch": {
      "abstract": [
        {
          "text": "An interface element that toggles between an On and Off state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceSwitch"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSwitch"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSwitch",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceswitch"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField": {
      "abstract": [
        {
          "text": "An interface element that displays an editable text area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceTextField"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceTextField"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceTextField",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacetextfield"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTimer": {
      "abstract": [
        {
          "text": "A label that displays a countdown or count-up timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceTimer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceTimer"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceTimer",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacetimer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceLabel",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTimer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceButton",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePaymentButton",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSwitch",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSlider",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceActivityRing"
      ],
      "title": "Controls"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-Map-Region",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setVisibleMapRect(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setRegion(_:)"
      ],
      "title": "Specifying the Map Region"
    },
    {
      "anchor": "Managing-Map-Annotations",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()"
      ],
      "title": "Managing Map Annotations"
    },
    {
      "anchor": "Displaying-the-Users-Location",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserLocation(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserHeading(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setUserTrackingMode(_:animated:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/UserTrackingMode"
      ],
      "title": "Displaying the User’s Location"
    },
    {
      "anchor": "Initializing-for-SwiftUI",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/init()"
      ],
      "title": "Initializing for SwiftUI"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKInterfaceMap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-Map-Region",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setVisibleMapRect(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setRegion(_:)"
              ],
              "title": "Specifying the Map Region"
            },
            {
              "anchor": "Managing-Map-Annotations",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()"
              ],
              "title": "Managing Map Annotations"
            },
            {
              "anchor": "Displaying-the-Users-Location",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserLocation(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setShowsUserHeading(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/setUserTrackingMode(_:animated:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/UserTrackingMode"
              ],
              "title": "Displaying the User’s Location"
            },
            {
              "anchor": "Initializing-for-SwiftUI",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/init()"
              ],
              "title": "Initializing for SwiftUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceLabel",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTimer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceButton",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePaymentButton",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSwitch",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSlider",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceActivityRing"
              ],
              "title": "Controls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKInterfaceMap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKInterfaceObject",
                    "text": "WKInterfaceObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTimer/title",
          "value": "WKInterfaceTimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTimer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceButton/title",
          "value": "WKInterfaceButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:centerOffset:)/title",
          "value": "addAnnotation:withImage:centerOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:centerOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAnnotation:withImage:centerOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setShowsUserLocation(_:)/title",
          "value": "setShowsUserLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setShowsUserLocation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setShowsUserLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/title",
          "value": "WKInterfaceObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:withImageNamed:centerOffset:)/title",
          "value": "addAnnotation:withImageNamed:centerOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:withImageNamed:centerOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAnnotation:withImageNamed:centerOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setUserTrackingMode(_:animated:)/title",
          "value": "setUserTrackingMode:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setUserTrackingMode(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setUserTrackingMode:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSwitch/title",
          "value": "WKInterfaceSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/title",
          "value": "WKInterfaceDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSlider/title",
          "value": "WKInterfaceSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/title",
          "value": "WKInterfaceMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceLabel/title",
          "value": "WKInterfaceLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setRegion(_:)/title",
          "value": "setRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setRegion(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setVisibleMapRect(_:)/title",
          "value": "setVisibleMapRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setVisibleMapRect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVisibleMapRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:)/title",
          "value": "addAnnotation:withPinColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAnnotation:withPinColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePaymentButton/title",
          "value": "WKInterfacePaymentButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePaymentButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfacePaymentButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePaymentButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfacePaymentButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceAuthorizationAppleIDButton/title",
          "value": "WKInterfaceAuthorizationAppleIDButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceAuthorizationAppleIDButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceAuthorizationAppleIDButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceAuthorizationAppleIDButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceAuthorizationAppleIDButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/title",
          "value": "WKInterfaceMapPinColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMapPinColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMapPinColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1UserTrackingMode/title",
          "value": "WKInterfaceMapUserTrackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1UserTrackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMapUserTrackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1UserTrackingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceMapUserTrackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/title",
          "value": "WKInterfaceTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setShowsUserHeading(_:)/title",
          "value": "setShowsUserHeading:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1setShowsUserHeading(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setShowsUserHeading:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1removeAllAnnotations()/title",
          "value": "removeAllAnnotations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1removeAllAnnotations()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllAnnotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceActivityRing/title",
          "value": "WKInterfaceActivityRing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceActivityRing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceActivityRing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceActivityRing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceActivityRing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkinterfacemap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkinterfacemap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
