{
  "abstract": [
    {
      "text": "Template images that you can use for menus.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Elevate important items out of such menus and into the relevant screen or a settings screen.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKMenuItemIcon",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKMenuItemIcon"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKMenuItemIcon"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKMenuItemIcon"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-6pb4t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to configure actions for your interface controller’s menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-1q2zj": {
      "abstract": [
        {
          "text": "Adds an action to the context menu by using an image provided by your WatchKit extension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-1q2zj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMenuItemWithImage:title:action:"
        }
      ],
      "role": "symbol",
      "title": "addMenuItem(with:title:action:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/addmenuitem(with:title:action:)-1q2zj"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-6pb4t": {
      "abstract": [
        {
          "text": "Adds an action to the context menu using a system-provided icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKMenuItemIcon",
          "text": "WKMenuItemIcon"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-6pb4t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMenuItemWithItemIcon:title:action:"
        }
      ],
      "role": "symbol",
      "title": "addMenuItem(with:title:action:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/addmenuitem(with:title:action:)-6pb4t"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(withImageNamed:title:action:)": {
      "abstract": [
        {
          "text": "Adds an action to the context menu using an existing image resource in your Watch app bundle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withImageNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(withImageNamed:title:action:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMenuItemWithImageNamed:title:action:"
        }
      ],
      "role": "symbol",
      "title": "addMenuItem(withImageNamed:title:action:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/addmenuitem(withimagenamed:title:action:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/beginGlanceUpdates()": {
      "abstract": [
        {
          "text": "Tells the system that you are about to start a potentially lengthy update task for your glance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGlanceUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/beginGlanceUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginGlanceUpdates"
        }
      ],
      "role": "symbol",
      "title": "beginGlanceUpdates()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/beginglanceupdates()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/clearAllMenuItems()": {
      "abstract": [
        {
          "text": "Removes all programmatically added actions from the context menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearAllMenuItems"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/clearAllMenuItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearAllMenuItems"
        }
      ],
      "role": "symbol",
      "title": "clearAllMenuItems()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/clearallmenuitems()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/endGlanceUpdates()": {
      "abstract": [
        {
          "text": "Tells the system that you finished updating your glance content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGlanceUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/endGlanceUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endGlanceUpdates"
        }
      ],
      "role": "symbol",
      "title": "endGlanceUpdates()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/endglanceupdates()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/handleUserActivity(_:)": {
      "abstract": [
        {
          "text": "Responds to Handoff–related activity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleUserActivity"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/handleUserActivity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleUserActivity:"
        }
      ],
      "role": "symbol",
      "title": "handleUserActivity(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/handleuseractivity(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/presentController(_:)": {
      "abstract": [
        {
          "text": "Presents a page-based interface modally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentController"
        },
        {
          "kind": "text",
          "text": "([(name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": ")])"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/presentController(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "presentController(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/presentcontroller(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/reloadRootControllers(withNames:contexts:)": {
      "abstract": [
        {
          "text": "Loads the specified interface controllers and rebuilds the app’s page-based interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadRootControllers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "contexts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/reloadRootControllers(withNames:contexts:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadRootControllersWithNames:contexts:"
        }
      ],
      "role": "symbol",
      "title": "reloadRootControllers(withNames:contexts:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/reloadrootcontrollers(withnames:contexts:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/updateUserActivity(_:userInfo:webpageURL:)": {
      "abstract": [
        {
          "text": "Registers the current user activity with the system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateUserActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "webpageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/updateUserActivity(_:userInfo:webpageURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateUserActivity:userInfo:webpageURL:"
        }
      ],
      "role": "symbol",
      "title": "updateUserActivity(_:userInfo:webpageURL:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/updateuseractivity(_:userinfo:webpageurl:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon": {
      "abstract": [
        {
          "text": "Template images that you can use for menus.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKMenuItemIcon"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIcon"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept": {
      "abstract": [
        {
          "text": "The icon indicating an action to accept an event or item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accept"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconAccept"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.accept",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/accept"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add": {
      "abstract": [
        {
          "text": "The icon indicating an action for adding an item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconAdd"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.add",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/add"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block": {
      "abstract": [
        {
          "text": "The icon indicating an action to block or prevent something from happening.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "block"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconBlock"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.block",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/block"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline": {
      "abstract": [
        {
          "text": "The icon indicating an action to decline or cancel an event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decline"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconDecline"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.decline",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/decline"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info": {
      "abstract": [
        {
          "text": "The icon indicating an action to retrieve more information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconInfo"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.info",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/info"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/init(rawvalue:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe": {
      "abstract": [
        {
          "text": "The icon indicating an answer of maybe for an action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maybe"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMaybe"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.maybe",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/maybe"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more": {
      "abstract": [
        {
          "text": "The icon indicating that more actions or options are available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "more"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMore"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.more",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/more"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute": {
      "abstract": [
        {
          "text": "The icon indicating an action to mute the sound.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mute"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconMute"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.mute",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/mute"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause": {
      "abstract": [
        {
          "text": "The icon indicating an action to pause playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconPause"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.pause",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/pause"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play": {
      "abstract": [
        {
          "text": "The icon indicating an action to play some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconPlay"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.play",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/play"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat": {
      "abstract": [
        {
          "text": "The icon indicating that played content should repeat in a loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconRepeat"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.repeat",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/repeat"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume": {
      "abstract": [
        {
          "text": "The icon indicating an action to resume playing some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconResume"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.resume",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/resume"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share": {
      "abstract": [
        {
          "text": "The icon indicating an action to share content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "share"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconShare"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.share",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/share"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle": {
      "abstract": [
        {
          "text": "The icon indicating an action to shuffle content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shuffle"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconShuffle"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.shuffle",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/shuffle"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker": {
      "abstract": [
        {
          "text": "The icon indicating audio output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speaker"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconSpeaker"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.speaker",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/speaker"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash": {
      "abstract": [
        {
          "text": "The icon indicating an action to delete some content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trash"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMenuItemIconTrash"
        }
      ],
      "role": "symbol",
      "title": "WKMenuItemIcon.trash",
      "type": "topic",
      "url": "/documentation/watchkit/wkmenuitemicon/trash"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/text-response-key": {
      "abstract": [
        {
          "text": "Keys for retrieving text response information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/text-response-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Response Key",
      "type": "topic",
      "url": "/documentation/watchkit/text-response-key"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/text-response-key",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(withImageNamed:title:action:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-6pb4t",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-1q2zj",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/beginGlanceUpdates()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/clearAllMenuItems()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/endGlanceUpdates()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/handleUserActivity(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/presentController(_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/reloadRootControllers(withNames:contexts:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/updateUserActivity(_:userInfo:webpageURL:)"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKMenuItemIcon"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/accept",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/add",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/block",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/decline",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/info",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/maybe",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/more",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/mute",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/pause",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/play",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/repeat",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/resume",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/share",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/shuffle",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/speaker",
                "doc://com.apple.watchkit/documentation/WatchKit/WKMenuItemIcon/trash"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/text-response-key",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(withImageNamed:title:action:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-6pb4t",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/addMenuItem(with:title:action:)-1q2zj",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/beginGlanceUpdates()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/clearAllMenuItems()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/endGlanceUpdates()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/handleUserActivity(_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/reloadRootControllers(withNames:contexts:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/updateUserActivity(_:userInfo:webpageURL:)"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKMenuItemIcon"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Elevate important items out of such menus and into the relevant screen or a settings screen.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1trash/title",
          "value": "WKMenuItemIconTrash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1trash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconTrash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/title",
          "value": "WKMenuItemIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1reloadRootControllers(withNames:contexts:)/title",
          "value": "reloadRootControllersWithNames:contexts:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1reloadRootControllers(withNames:contexts:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "reloadRootControllersWithNames:contexts:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1more/title",
          "value": "WKMenuItemIconMore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1more/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1accept/title",
          "value": "WKMenuItemIconAccept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1accept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconAccept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1pause/title",
          "value": "WKMenuItemIconPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1maybe/title",
          "value": "WKMenuItemIconMaybe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1maybe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMaybe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1mute/title",
          "value": "WKMenuItemIconMute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1mute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconMute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(withImageNamed:title:action:)/title",
          "value": "addMenuItemWithImageNamed:title:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(withImageNamed:title:action:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMenuItemWithImageNamed:title:action:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1speaker/title",
          "value": "WKMenuItemIconSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1speaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1share/title",
          "value": "WKMenuItemIconShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1share/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1beginGlanceUpdates()/title",
          "value": "beginGlanceUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1beginGlanceUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginGlanceUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1handleUserActivity(_:)/title",
          "value": "handleUserActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1handleUserActivity(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleUserActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1block/title",
          "value": "WKMenuItemIconBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1block/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1play/title",
          "value": "WKMenuItemIconPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1resume/title",
          "value": "WKMenuItemIconResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1resume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1repeat/title",
          "value": "WKMenuItemIconRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1clearAllMenuItems()/title",
          "value": "clearAllMenuItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1clearAllMenuItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearAllMenuItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1info/title",
          "value": "WKMenuItemIconInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1decline/title",
          "value": "WKMenuItemIconDecline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1decline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconDecline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1endGlanceUpdates()/title",
          "value": "endGlanceUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1endGlanceUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endGlanceUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1shuffle/title",
          "value": "WKMenuItemIconShuffle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1shuffle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconShuffle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1updateUserActivity(_:userInfo:webpageURL:)/title",
          "value": "updateUserActivity:userInfo:webpageURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1updateUserActivity(_:userInfo:webpageURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateUserActivity:userInfo:webpageURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(with:title:action:)-1q2zj/title",
          "value": "addMenuItemWithImage:title:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(with:title:action:)-1q2zj/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMenuItemWithImage:title:action:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1add/title",
          "value": "WKMenuItemIconAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKMenuItemIcon~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMenuItemIconAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(with:title:action:)-6pb4t/title",
          "value": "addMenuItemWithItemIcon:title:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1addMenuItem(with:title:action:)-6pb4t/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMenuItemWithItemIcon:title:action:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkmenuitemicon"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkmenuitemicon"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
