{
  "abstract": [
    {
      "text": "A gesture recognizer that interprets a touch event that moves around the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKPanGestureRecognizer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKPanGestureRecognizer"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKPanGestureRecognizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKPanGestureRecognizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKPanGestureRecognizer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In watchOS, a pan gesture must track exactly one touch event, but that touch event may move freely. Pan gestures are often used to drag content around a given area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You do not create instances of this class programmatically. Instead, add a pan gesture recognizer to your Watch app’s storyboard file, dropping it onto a specific interface object. Touches occurring within the bounds of that interface object are tracked by the gesture recognizer and reported to an action method you define on the parent interface controller. For information on defining your action method and connecting it to your gesture recognizer, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "State-Changes-for-a-Pan-Gesture",
          "level": 3,
          "text": "State Changes for a Pan Gesture",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2557623",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A pan gesture recognizer tracks touch events continuously, and therefore has many potential state changes. A pan gesture does not transition to the Began state until after the touch event starts moving. After that, it may transition to the Changed state, to the Ended, state, to the Failed state, or to the Cancelled state. The two most common state transition sequences are as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Possible —> Began —> [Changed…] —> Ended",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Possible —> Began —> [Changed…] —> Failed",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The Changed state is optional and may occur multiple times before the Ended, Failed, or Cancelled state is reached. The gesture recognizer calls its action method at each state transition. For more information on implementing continuous gesture recognizers, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interface-Builder-Attributes",
          "level": 3,
          "text": "Interface Builder Attributes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode lets you configure information about your gesture recognizer in your storyboard file. A pan gesture recognizer defines no attributes of its own, but you can configure attributes of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " parent class. For information about those attributes, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKCrownDelegate": {
      "abstract": [
        {
          "text": "A collection of methods you can implement to track the user’s interaction with the digital crown, receiving notifications when the user rotates the crown or when rotation stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKCrownDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKCrownDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKCrownDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKCrownDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkcrowndelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKCrownSequencer": {
      "abstract": [
        {
          "text": "An object that reports the current state of the digital crown, including its rotational speed when it is in motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKCrownSequencer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKCrownSequencer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKCrownSequencer"
        }
      ],
      "role": "symbol",
      "title": "WKCrownSequencer",
      "type": "topic",
      "url": "/documentation/watchkit/wkcrownsequencer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer": {
      "abstract": [
        {
          "text": "The base class for all other gesture recognizer classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "WKGestureRecognizer",
      "type": "topic",
      "url": "/documentation/watchkit/wkgesturerecognizer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKLongPressGestureRecognizer": {
      "abstract": [
        {
          "text": "A gesture recognizer that interprets a touch event that occurs in the same relative area for an extended period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKLongPressGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKLongPressGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKLongPressGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "WKLongPressGestureRecognizer",
      "type": "topic",
      "url": "/documentation/watchkit/wklongpressgesturerecognizer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer": {
      "abstract": [
        {
          "text": "A gesture recognizer that interprets a touch event that moves around the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKPanGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPanGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "WKPanGestureRecognizer",
      "type": "topic",
      "url": "/documentation/watchkit/wkpangesturerecognizer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/translationInObject()": {
      "abstract": [
        {
          "text": "The amount of translation for the pan gesture in the current object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translationInObject"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/translationInObject()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translationInObject"
        }
      ],
      "role": "symbol",
      "title": "translationInObject()",
      "type": "topic",
      "url": "/documentation/watchkit/wkpangesturerecognizer/translationinobject()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/velocityInObject()": {
      "abstract": [
        {
          "text": "The velocity of the pan gesture in the current object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "velocityInObject"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/velocityInObject()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "velocityInObject"
        }
      ],
      "role": "symbol",
      "title": "velocityInObject()",
      "type": "topic",
      "url": "/documentation/watchkit/wkpangesturerecognizer/velocityinobject()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSwipeGestureRecognizer": {
      "abstract": [
        {
          "text": "A gesture recognizer that interprets swiping gestures in one or more directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKSwipeGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSwipeGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSwipeGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "WKSwipeGestureRecognizer",
      "type": "topic",
      "url": "/documentation/watchkit/wkswipegesturerecognizer"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTapGestureRecognizer": {
      "abstract": [
        {
          "text": "A gesture recognizer that interprets a touch event occurring and ending in approximately the same area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTapGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTapGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTapGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "WKTapGestureRecognizer",
      "type": "topic",
      "url": "/documentation/watchkit/wktapgesturerecognizer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-2557623": {
      "alt": null,
      "identifier": "media-2557623",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/eadbf2c2039e5658266f0bc849dbbbdc/media-2557623@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKCrownSequencer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKCrownDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKLongPressGestureRecognizer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSwipeGestureRecognizer",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTapGestureRecognizer"
      ],
      "title": "Event handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tracking-the-Location-and-Velocity-of-the-Gesture",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/translationInObject()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/velocityInObject()"
      ],
      "title": "Tracking the Location and Velocity of the Gesture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKPanGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tracking-the-Location-and-Velocity-of-the-Gesture",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/translationInObject()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKPanGestureRecognizer/velocityInObject()"
              ],
              "title": "Tracking the Location and Velocity of the Gesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKCrownSequencer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKCrownDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKLongPressGestureRecognizer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSwipeGestureRecognizer",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTapGestureRecognizer"
              ],
              "title": "Event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKPanGestureRecognizer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKGestureRecognizer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKGestureRecognizer",
                    "text": "WKGestureRecognizer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTapGestureRecognizer/title",
          "value": "WKTapGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTapGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTapGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer/title",
          "value": "WKPanGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSwipeGestureRecognizer/title",
          "value": "WKSwipeGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSwipeGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSwipeGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSwipeGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSwipeGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKGestureRecognizer/title",
          "value": "WKGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownSequencer/title",
          "value": "WKCrownSequencer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownSequencer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKCrownSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownSequencer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKCrownSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer~1velocityInObject()/title",
          "value": "velocityInObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer~1velocityInObject()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "velocityInObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKLongPressGestureRecognizer/title",
          "value": "WKLongPressGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKLongPressGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKLongPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKLongPressGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKLongPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer~1translationInObject()/title",
          "value": "translationInObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPanGestureRecognizer~1translationInObject()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "translationInObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownDelegate/title",
          "value": "WKCrownDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKCrownDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKCrownDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKCrownDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkpangesturerecognizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkpangesturerecognizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
