{
  "abstract": [
    {
      "text": "The reason for a background snapshot task.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKSnapshotReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKSnapshotReason"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKSnapshotReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKSnapshotReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKSnapshotReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason": {
      "abstract": [
        {
          "text": "The reason for a background snapshot task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKSnapshotReason"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReason"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appBackgrounded": {
      "abstract": [
        {
          "text": "The app transitioned from the foreground to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appBackgrounded"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appBackgrounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReasonAppBackgrounded"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason.appBackgrounded",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/appbackgrounded"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appScheduled": {
      "abstract": [
        {
          "text": "The app scheduled this snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appScheduled"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appScheduled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReasonAppScheduled"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason.appScheduled",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/appscheduled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/complicationUpdate": {
      "abstract": [
        {
          "text": "The app updated the complication timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complicationUpdate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/complicationUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReasonComplicationUpdate"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason.complicationUpdate",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/complicationupdate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/init(rawvalue:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/prelaunch": {
      "abstract": [
        {
          "text": "The system needs a snapshot for the dock, but the app has not been launched yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prelaunch"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/prelaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReasonPrelaunch"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason.prelaunch",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/prelaunch"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/returnToDefaultState": {
      "abstract": [
        {
          "text": "It has been more than an hour since the user’s last interaction with the app; the app’s snapshot should return to its default state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnToDefaultState"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/returnToDefaultState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKSnapshotReasonReturnToDefaultState"
        }
      ],
      "role": "symbol",
      "title": "WKSnapshotReason.returnToDefaultState",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotreason/returntodefaultstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/reasonForSnapshot": {
      "abstract": [
        {
          "text": "The reason for taking the upcoming snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reasonForSnapshot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKSnapshotReason",
          "text": "WKSnapshotReason"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/reasonForSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reasonForSnapshot"
        }
      ],
      "role": "symbol",
      "title": "reasonForSnapshot",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotrefreshbackgroundtask/reasonforsnapshot"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/returnToDefaultState": {
      "abstract": [
        {
          "text": "A Boolean value indicating that the app should return to its default state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnToDefaultState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/returnToDefaultState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnToDefaultState"
        }
      ],
      "role": "symbol",
      "title": "returnToDefaultState",
      "type": "topic",
      "url": "/documentation/watchkit/wksnapshotrefreshbackgroundtask/returntodefaultstate"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/reasonForSnapshot",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/returnToDefaultState"
      ],
      "title": "Instance properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appBackgrounded",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appScheduled",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/complicationUpdate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/prelaunch",
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/returnToDefaultState"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKSnapshotReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appBackgrounded",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/appScheduled",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/complicationUpdate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/prelaunch",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotReason/returnToDefaultState"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/reasonForSnapshot",
                "doc://com.apple.watchkit/documentation/WatchKit/WKSnapshotRefreshBackgroundTask/returnToDefaultState"
              ],
              "title": "Instance properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKSnapshotReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason/title",
          "value": "WKSnapshotReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1returnToDefaultState/title",
          "value": "WKSnapshotReasonReturnToDefaultState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1returnToDefaultState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReasonReturnToDefaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotRefreshBackgroundTask~1reasonForSnapshot/title",
          "value": "reasonForSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotRefreshBackgroundTask~1reasonForSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reasonForSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1appScheduled/title",
          "value": "WKSnapshotReasonAppScheduled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1appScheduled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReasonAppScheduled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1prelaunch/title",
          "value": "WKSnapshotReasonPrelaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1prelaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReasonPrelaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1appBackgrounded/title",
          "value": "WKSnapshotReasonAppBackgrounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1appBackgrounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReasonAppBackgrounded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotRefreshBackgroundTask~1returnToDefaultState/title",
          "value": "returnToDefaultState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotRefreshBackgroundTask~1returnToDefaultState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnToDefaultState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1complicationUpdate/title",
          "value": "WKSnapshotReasonComplicationUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKSnapshotReason~1complicationUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKSnapshotReasonComplicationUpdate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wksnapshotreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wksnapshotreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
