{
  "abstract": [
    {
      "text": "Constants that specify a text field’s semantic meaning.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@WKTextContentType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WKTextContentType"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKTextContentType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WKTextContentType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)": {
      "abstract": [
        {
          "text": "Sets the text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTextContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTextContentType:"
        }
      ],
      "role": "symbol",
      "title": "setTextContentType(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacetextfield/settextcontenttype(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType": {
      "abstract": [
        {
          "text": "Constants that specify a text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "role": "symbol",
      "title": "WKTextContentType",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/URL": {
      "abstract": [
        {
          "text": "A URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/URL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeURL"
        }
      ],
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/url"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity": {
      "abstract": [
        {
          "text": "The name of a city.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressCity"
        }
      ],
      "role": "symbol",
      "title": "addressCity",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addresscity"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState": {
      "abstract": [
        {
          "text": "The name of a city and state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCityAndState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressCityAndState"
        }
      ],
      "role": "symbol",
      "title": "addressCityAndState",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addresscityandstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState": {
      "abstract": [
        {
          "text": "The name of a state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressState"
        }
      ],
      "role": "symbol",
      "title": "addressState",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addressstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName": {
      "abstract": [
        {
          "text": "The name of a country or region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeCountryName"
        }
      ],
      "role": "symbol",
      "title": "countryName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/countryname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber": {
      "abstract": [
        {
          "text": "A credit card number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeCreditCardNumber"
        }
      ],
      "role": "symbol",
      "title": "creditCardNumber",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/creditcardnumber"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/emailAddress": {
      "abstract": [
        {
          "text": "An email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/emailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeEmailAddress"
        }
      ],
      "role": "symbol",
      "title": "emailAddress",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/emailaddress"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/familyName": {
      "abstract": [
        {
          "text": "A last name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "familyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/familyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeFamilyName"
        }
      ],
      "role": "symbol",
      "title": "familyName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/familyname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress": {
      "abstract": [
        {
          "text": "The full street address for a location, including the unit or suite number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullStreetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeFullStreetAddress"
        }
      ],
      "role": "symbol",
      "title": "fullStreetAddress",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/fullstreetaddress"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/givenName": {
      "abstract": [
        {
          "text": "A given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "givenName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/givenName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeGivenName"
        }
      ],
      "role": "symbol",
      "title": "givenName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/givenname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Returns a newly instantiated content type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/init(rawvalue:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/jobTitle": {
      "abstract": [
        {
          "text": "A job title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/jobTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeJobTitle"
        }
      ],
      "role": "symbol",
      "title": "jobTitle",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/jobtitle"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location": {
      "abstract": [
        {
          "text": "A point of interest, address, or other identifiable location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeLocation"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/location"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/middleName": {
      "abstract": [
        {
          "text": "A middle name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/middleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeMiddleName"
        }
      ],
      "role": "symbol",
      "title": "middleName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/middlename"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/name": {
      "abstract": [
        {
          "text": "A full name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeName"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/name"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/namePrefix": {
      "abstract": [
        {
          "text": "A title or prefix for a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "namePrefix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/namePrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeNamePrefix"
        }
      ],
      "role": "symbol",
      "title": "namePrefix",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/nameprefix"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nameSuffix": {
      "abstract": [
        {
          "text": "A suffix for a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nameSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeNameSuffix"
        }
      ],
      "role": "symbol",
      "title": "nameSuffix",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/namesuffix"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword": {
      "abstract": [
        {
          "text": "A new password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeNewPassword"
        }
      ],
      "role": "symbol",
      "title": "newPassword",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/newpassword"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nickname": {
      "abstract": [
        {
          "text": "A nickname.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickname"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nickname",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeNickname"
        }
      ],
      "role": "symbol",
      "title": "nickname",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/nickname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode": {
      "abstract": [
        {
          "text": "A one-time code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeOneTimeCode"
        }
      ],
      "role": "symbol",
      "title": "oneTimeCode",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/onetimecode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/organizationName": {
      "abstract": [
        {
          "text": "An organization’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "organizationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/organizationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeOrganizationName"
        }
      ],
      "role": "symbol",
      "title": "organizationName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/organizationname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password": {
      "abstract": [
        {
          "text": "An existing password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypePassword"
        }
      ],
      "role": "symbol",
      "title": "password",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/password"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode": {
      "abstract": [
        {
          "text": "A postal code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypePostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/postalcode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1": {
      "abstract": [
        {
          "text": "The first line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeStreetAddressLine1"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine1",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/streetaddressline1"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2": {
      "abstract": [
        {
          "text": "The second line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeStreetAddressLine2"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine2",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/streetaddressline2"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality": {
      "abstract": [
        {
          "text": "The sublocality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sublocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeSublocality"
        }
      ],
      "role": "symbol",
      "title": "sublocality",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/sublocality"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber": {
      "abstract": [
        {
          "text": "A telephone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telephoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeTelephoneNumber"
        }
      ],
      "role": "symbol",
      "title": "telephoneNumber",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/telephonenumber"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/username": {
      "abstract": [
        {
          "text": "An account or login name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/username",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeUsername"
        }
      ],
      "role": "symbol",
      "title": "username",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/username"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-Content-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)"
      ],
      "title": "Specifying the Content Type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Name",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/name",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/namePrefix",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/givenName",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/middleName",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/familyName",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nameSuffix",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nickname"
      ],
      "title": "Name"
    },
    {
      "anchor": "Employment",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/jobTitle",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/organizationName"
      ],
      "title": "Employment"
    },
    {
      "anchor": "Address",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode"
      ],
      "title": "Address"
    },
    {
      "anchor": "Contact-Information",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/emailAddress"
      ],
      "title": "Contact Information"
    },
    {
      "anchor": "Other",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/URL",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber"
      ],
      "title": "Other"
    },
    {
      "anchor": "Login-Credentials",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/username",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode"
      ],
      "title": "Login Credentials"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKTextContentType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Name",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/name",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/namePrefix",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/givenName",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/middleName",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/familyName",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nameSuffix",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/nickname"
              ],
              "title": "Name"
            },
            {
              "anchor": "Employment",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/jobTitle",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/organizationName"
              ],
              "title": "Employment"
            },
            {
              "anchor": "Address",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode"
              ],
              "title": "Address"
            },
            {
              "anchor": "Contact-Information",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/emailAddress"
              ],
              "title": "Contact Information"
            },
            {
              "anchor": "Other",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/URL",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber"
              ],
              "title": "Other"
            },
            {
              "anchor": "Login-Credentials",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/username",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode"
              ],
              "title": "Login Credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-Content-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)"
              ],
              "title": "Specifying the Content Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/title",
          "value": "WKTextContentTypePostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypePostalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1jobTitle/title",
          "value": "WKTextContentTypeJobTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1jobTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeJobTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1location/title",
          "value": "WKTextContentTypeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCity/title",
          "value": "WKTextContentTypeAddressCity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressCity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1creditCardNumber/title",
          "value": "WKTextContentTypeCreditCardNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1creditCardNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeCreditCardNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1username/title",
          "value": "WKTextContentTypeUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1username/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeUsername"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1sublocality/title",
          "value": "WKTextContentTypeSublocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1sublocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeSublocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1namePrefix/title",
          "value": "WKTextContentTypeNamePrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1namePrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNamePrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1nickname/title",
          "value": "WKTextContentTypeNickname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1nickname/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNickname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine2/title",
          "value": "WKTextContentTypeStreetAddressLine2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeStreetAddressLine2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine1/title",
          "value": "WKTextContentTypeStreetAddressLine1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeStreetAddressLine1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/title",
          "value": "WKTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1familyName/title",
          "value": "WKTextContentTypeFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1familyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1newPassword/title",
          "value": "WKTextContentTypeNewPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1newPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNewPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1name/title",
          "value": "WKTextContentTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1password/title",
          "value": "WKTextContentTypePassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1password/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypePassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1telephoneNumber/title",
          "value": "WKTextContentTypeTelephoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1telephoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeTelephoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1countryName/title",
          "value": "WKTextContentTypeCountryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1countryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeCountryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField~1setTextContentType(_:)/title",
          "value": "setTextContentType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField~1setTextContentType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTextContentType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1middleName/title",
          "value": "WKTextContentTypeMiddleName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1middleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeMiddleName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1emailAddress/title",
          "value": "WKTextContentTypeEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1emailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1nameSuffix/title",
          "value": "WKTextContentTypeNameSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1nameSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNameSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressState/title",
          "value": "WKTextContentTypeAddressState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCityAndState/title",
          "value": "WKTextContentTypeAddressCityAndState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCityAndState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressCityAndState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1givenName/title",
          "value": "WKTextContentTypeGivenName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1givenName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeGivenName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/title",
          "value": "WKTextContentTypeOneTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeOneTimeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1URL/title",
          "value": "WKTextContentTypeURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1URL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1fullStreetAddress/title",
          "value": "WKTextContentTypeFullStreetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1fullStreetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeFullStreetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1organizationName/title",
          "value": "WKTextContentTypeOrganizationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1organizationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeOrganizationName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wktextcontenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wktextcontenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
