{
  "abstract": [
    {
      "text": "An error code that indicates the GPU terminated the command buffer because a kernel function of tile shader used too many stack frames.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCommandBufferError@MTLCommandBufferErrorStackOverflow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "stackOverflow"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCommandBufferErrorStackOverflow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLCommandBufferError.Code.stackOverflow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "stackOverflow"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can set the largest number of stack frames your pipelines by configuring these properties:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "code": ".",
                      "type": "codeVoice"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor/maxCallStackDepth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for kernel functions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "code": ".",
                      "type": "codeVoice"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor/maxCallStackDepth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for tile shaders",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The command buffer error codes that indicate why the GPU doesn’t finish executing a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that indicate why a GPU is unable to finish running a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked": {
      "abstract": [
        {
          "text": "An error code that indicates the system has revoked the Metal device’s access because it’s responsible for too many timeouts or hangs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRevoked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessRevoked",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/accessrevoked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved": {
      "abstract": [
        {
          "text": "An error code that indicates a person physically removed the GPU device before the command buffer finished running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRemoved"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorDeviceRemoved"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.deviceRemoved",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/deviceremoved"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal": {
      "abstract": [
        {
          "text": "An error code that indicates the Metal framework has an internal problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.internal",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/internal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer has an invalid reference to resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidResource"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorInvalidResource"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.invalidResource",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/invalidresource"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU ran out of one or more of its internal resources that support memoryless render pass attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryless"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorMemoryless"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.memoryless",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/memoryless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorNone"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.none",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted": {
      "abstract": [
        {
          "text": "An error code that indicates a process doesn’t have access to a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notPermitted"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.notPermitted",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/notpermitted"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t have sufficient memory to execute a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorOutOfMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.outOfMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/outofmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer generated a page fault the GPU can’t service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageFault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorPageFault"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.pageFault",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/pagefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU terminated the command buffer because a kernel function of tile shader used too many stack frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stackOverflow"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorStackOverflow"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.stackOverflow",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/stackoverflow"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout": {
      "abstract": [
        {
          "text": "An error code that indicates the system interrupted and terminated the command buffer because it took more time to execute than the system allows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorTimeout"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.timeout",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/timeout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor": {
      "abstract": [
        {
          "text": "An instance describing the desired GPU state for a kernel call in a compute pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputePipelineDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComputePipelineDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLComputePipelineDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor/maxCallStackDepth": {
      "abstract": [
        {
          "text": "The maximum recursive call depth for dynamic library, visible, and intersection functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxCallStackDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineDescriptor/maxCallStackDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxCallStackDepth"
        }
      ],
      "role": "symbol",
      "title": "maxCallStackDepth",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinedescriptor/maxcallstackdepth"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor": {
      "abstract": [
        {
          "text": "An object that configures new render pipeline state objects for tile shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTileRenderPipelineDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTileRenderPipelineDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLTileRenderPipelineDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtltilerenderpipelinedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor/maxCallStackDepth": {
      "abstract": [
        {
          "text": "The maximum function call depth from the top-most shader function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxCallStackDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineDescriptor/maxCallStackDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxCallStackDepth"
        }
      ],
      "role": "symbol",
      "title": "maxCallStackDepth",
      "type": "topic",
      "url": "/documentation/metal/mtltilerenderpipelinedescriptor/maxcallstackdepth"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCommandBufferErrorStackOverflow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorStackOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLCommandBufferErrorStackOverflow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineDescriptor~1maxCallStackDepth/title",
          "value": "maxCallStackDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineDescriptor~1maxCallStackDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxCallStackDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineDescriptor~1maxCallStackDepth/title",
          "value": "maxCallStackDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineDescriptor~1maxCallStackDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxCallStackDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1outOfMemory/title",
          "value": "MTLCommandBufferErrorOutOfMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1outOfMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorOutOfMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1deviceRemoved/title",
          "value": "MTLCommandBufferErrorDeviceRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1deviceRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorDeviceRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1stackOverflow/title",
          "value": "MTLCommandBufferErrorStackOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1stackOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorStackOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1timeout/title",
          "value": "MTLCommandBufferErrorTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1timeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1notPermitted/title",
          "value": "MTLCommandBufferErrorNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1notPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1pageFault/title",
          "value": "MTLCommandBufferErrorPageFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1pageFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorPageFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineDescriptor/title",
          "value": "MTLComputePipelineDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1invalidResource/title",
          "value": "MTLCommandBufferErrorInvalidResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1invalidResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorInvalidResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1none/title",
          "value": "MTLCommandBufferErrorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1internal/title",
          "value": "MTLCommandBufferErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/title",
          "value": "MTLCommandBufferError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1memoryless/title",
          "value": "MTLCommandBufferErrorMemoryless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1memoryless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorMemoryless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineDescriptor/title",
          "value": "MTLTileRenderPipelineDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTileRenderPipelineDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTileRenderPipelineDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommandbuffererror-swift.struct/code/stackoverflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcommandbuffererror-swift.struct/code/stackoverflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
