{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPathStyle/NSPathStyleNavigationBar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPathStyle@NSPathStyleNavigationBar",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSPathStyleNavigationBar"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPathStyleNavigationBar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSPathStyleNavigationBar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSPathStyleNavigationBar"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The navigation bar display style and behavior. Similar to the ",
              "type": "text"
            },
            {
              "code": "NSPathStyleStandard",
              "type": "codeVoice"
            },
            {
              "text": " with the navigation bar drawing style. Also known as the breadcrumb style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style": {
      "abstract": [
        {
          "code": "NSPathStyle",
          "type": "codeVoice"
        },
        {
          "text": " constants represent the different visual and behavioral styles an ",
          "type": "text"
        },
        {
          "code": "NSPathControl",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "NSPathCell",
          "type": "codeVoice"
        },
        {
          "text": " object can have.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl.Style",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol/style"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathStylePopUp"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl.Style.popUp",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol/style/popup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/standard": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathStyleStandard"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl.Style.standard",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol/style/standard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathStyle/NSPathStyleNavigationBar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPathStyleNavigationBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathStyle/NSPathStyleNavigationBar",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPathStyleNavigationBar",
      "type": "topic",
      "url": "/documentation/appkit/nspathstyle/nspathstylenavigationbar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/standard",
        "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1popUp/title",
          "value": "NSPathStylePopUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1popUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathStylePopUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1standard/title",
          "value": "NSPathStyleStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathStyleStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style/title",
          "value": "NSPathStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspathstyle/nspathstylenavigationbar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
