{
  "abstract": [
    {
      "text": "The horizontal orientation.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/horizontal",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontHorizontalOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontOrientation@kCTFontHorizontalOrientation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontHorizontalOrientation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontOrientation",
        "text": "CTFontOrientation"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontHorizontalOrientation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Deprecated",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.5",
        "message": "Deprecated",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Deprecated",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "kCTFontHorizontalOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontHorizontalOrientation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontOrientation",
              "text": "CTFontOrientation"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation": {
      "abstract": [
        {
          "text": "The intended rendering orientation of the font for obtaining glyph metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "role": "symbol",
      "title": "CTFontOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/horizontal": {
      "abstract": [
        {
          "text": "The horizontal orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOrientationHorizontal"
        }
      ],
      "role": "symbol",
      "title": "CTFontOrientation.horizontal",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation/horizontal"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontDefaultOrientation": {
      "abstract": [
        {
          "text": "The native orientation of the font.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDefaultOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontOrientation",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontDefaultOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDefaultOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDefaultOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation/kctfontdefaultorientation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontHorizontalOrientation": {
      "abstract": [
        {
          "text": "The horizontal orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontHorizontalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontOrientation",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontHorizontalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontHorizontalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCTFontHorizontalOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation/kctfonthorizontalorientation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontVerticalOrientation": {
      "abstract": [
        {
          "text": "The vertical orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVerticalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontOrientation",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontVerticalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVerticalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVerticalOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation/kctfontverticalorientation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontDefaultOrientation",
        "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontVerticalOrientation"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontHorizontalOrientation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontHorizontalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontDefaultOrientation",
                "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/kCTFontVerticalOrientation"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontHorizontalOrientation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation/horizontal",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/title",
          "value": "CTFontOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1horizontal/title",
          "value": "kCTFontOrientationHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOrientationHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontHorizontalOrientation/title",
          "value": "kCTFontHorizontalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontHorizontalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontHorizontalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontVerticalOrientation/title",
          "value": "kCTFontVerticalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontVerticalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVerticalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontDefaultOrientation/title",
          "value": "kCTFontDefaultOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation~1kCTFontDefaultOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDefaultOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontorientation/kctfonthorizontalorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontorientation/kctfonthorizontalorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
