{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhone","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uibarmetrics/landscapephone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uibarmetrics/landscapephone"]}],"metadata":{"title":"landscapePhone","externalID":"c:@E@UIBarMetrics@UIBarMetricsLandscapePhone","platforms":[{"beta":false,"unavailable":false,"deprecatedAt":"8.0","deprecated":false,"renamed":"UIBarMetrics.compact","name":"iOS","introducedAt":"5.0"},{"introducedAt":"5.0","deprecatedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"renamed":"UIBarMetrics.compact","name":"iPadOS"},{"introducedAt":"13.1","deprecatedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"renamed":"UIBarMetrics.compact","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"}],"role":"symbol","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapePhone","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics"}],"roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsLandscapePhone"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/default","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/defaultPrompt","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compactPrompt","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhonePrompt"],"anchor":"Constants","title":"Constants","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics"]]},"abstract":[{"type":"text","text":"Specifies metrics for landscape orientation using the phone idiom."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact"},{"type":"text","text":" instead."}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapePhone"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics":{"navigatorTitle":[{"text":"UIBarMetrics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarMetrics","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uibarmetrics","title":"UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constants to specify metrics to use for appearance."}]},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhonePrompt":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhonePrompt","title":"landscapePhonePrompt","type":"topic","url":"/documentation/uikit/uibarmetrics/landscapephoneprompt","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsLandscapePhonePrompt"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapePhonePrompt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics"}],"deprecated":true,"abstract":[{"type":"text","text":"Specifies metrics for landscape orientation using the phone idiom for bars with the prompt property, such as "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar","type":"reference"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact","abstract":[{"type":"text","text":"Specifies metrics when using the phone idiom."}],"navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsCompact"}],"type":"topic","url":"/documentation/uikit/uibarmetrics/compact","kind":"symbol","title":"UIBarMetrics.compact","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compact"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/defaultPrompt":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/defaultPrompt","abstract":[{"type":"text","text":"Specifies default metrics for the device for bars with the prompt property, such as "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsDefaultPrompt"}],"type":"topic","url":"/documentation/uikit/uibarmetrics/defaultprompt","kind":"symbol","title":"UIBarMetrics.defaultPrompt","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPrompt"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/default":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/default","title":"UIBarMetrics.default","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"text":"Specifies default metrics for the device.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsDefault"}],"url":"/documentation/uikit/uibarmetrics/default"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compactPrompt":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compactPrompt","abstract":[{"type":"text","text":"Specifies metrics for bars with the prompt property when using the phone idiom, such as "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsCompactPrompt"}],"type":"topic","url":"/documentation/uikit/uibarmetrics/compactprompt","kind":"symbol","title":"UIBarMetrics.compactPrompt","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compactPrompt"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhone":{"navigatorTitle":[{"kind":"identifier","text":"UIBarMetricsLandscapePhone"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhone","url":"/documentation/uikit/uibarmetrics/landscapephone","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapePhone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"}],"abstract":[{"type":"text","text":"Specifies metrics for landscape orientation using the phone idiom."}],"title":"landscapePhone","type":"topic","role":"symbol","deprecated":true,"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"deprecatedAt":"8.0","introducedAt":"5.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"deprecatedAt":"8.0","introducedAt":"5.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"deprecatedAt":"13.1","introducedAt":"13.1","beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"UIBarMetricsLandscapePhone","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UIBarMetricsLandscapePhone"}],"path":"/metadata/fragments"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/default","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/defaultPrompt","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compactPrompt","doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/landscapePhonePrompt"],"title":"Constants"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"UIBarMetricsLandscapePhone","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/deprecationSummary","value":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics/compact","isActive":true,"type":"reference"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/title","value":"UIBarMetrics","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/fragments","value":[{"kind":"identifier","text":"UIBarMetrics"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/navigatorTitle","value":[{"text":"UIBarMetrics","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1landscapePhonePrompt/title","value":"UIBarMetricsLandscapePhonePrompt","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1landscapePhonePrompt/fragments","value":[{"kind":"identifier","text":"UIBarMetricsLandscapePhonePrompt"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1compact/title","value":"UIBarMetricsCompact","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1compact/fragments","value":[{"kind":"identifier","text":"UIBarMetricsCompact"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1defaultPrompt/title","value":"UIBarMetricsDefaultPrompt","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1defaultPrompt/fragments","value":[{"text":"UIBarMetricsDefaultPrompt","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","value":"UISearchBar","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","value":"UINavigationBar","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","value":[{"text":"UINavigationBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","value":[{"text":"UINavigationBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1default/title","value":"UIBarMetricsDefault","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1default/fragments","value":[{"kind":"identifier","text":"UIBarMetricsDefault"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1compactPrompt/title","value":"UIBarMetricsCompactPrompt"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1compactPrompt/fragments","value":[{"text":"UIBarMetricsCompactPrompt","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1landscapePhone/title","value":"UIBarMetricsLandscapePhone"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics~1landscapePhone/fragments","value":[{"text":"UIBarMetricsLandscapePhone","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}