{
  "abstract": [
    {
      "text": "For rectangular coordinates, negative is back and positive is front. The units are specified by the ",
      "type": "text"
    },
    {
      "code": "mChannelFlags",
      "type": "codeVoice"
    },
    {
      "text": " field.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_BackFront"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioChannelCoordinateIndex@kAudioChannelCoordinates_BackFront",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "coordinates_BackFront"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelCoordinates_BackFront"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AudioChannelCoordinateIndex.coordinates_BackFront"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "coordinates_BackFront"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex": {
      "abstract": [
        {
          "text": "Indexes the fields of the ",
          "type": "text"
        },
        {
          "code": "mCoordinates",
          "type": "codeVoice"
        },
        {
          "text": " array in an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelCoordinateIndex",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth": {
      "abstract": [
        {
          "text": "For spherical coordinates, ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " is front center, positive is right, negative is left, and measurements are in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Azimuth"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Azimuth",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_azimuth"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_BackFront": {
      "abstract": [
        {
          "text": "For rectangular coordinates, negative is back and positive is front. The units are specified by the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_BackFront"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_BackFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_BackFront"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelCoordinateIndex.coordinates_BackFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_backfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance": {
      "abstract": [
        {
          "text": "For spherical coordinates, distance is radially from the center. The units are specified by the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "code": "AudioChannelDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Distance"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Distance",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_distance"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_DownUp": {
      "abstract": [
        {
          "text": "For rectangular coordinates, negative is below ground level, ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " is ground level, and positive is above ground level. The units are specified by the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_DownUp"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_DownUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_DownUp"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelCoordinateIndex.coordinates_DownUp",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_downup"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation": {
      "abstract": [
        {
          "text": "For spherical coordinates, ",
          "type": "text"
        },
        {
          "code": "+90",
          "type": "codeVoice"
        },
        {
          "text": " is zenith, ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " is horizontal, ",
          "type": "text"
        },
        {
          "code": "-90",
          "type": "codeVoice"
        },
        {
          "text": " is nadir, and measurements are in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Elevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Elevation"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Elevation",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_elevation"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_LeftRight": {
      "abstract": [
        {
          "text": "For rectangular coordinates, negative is left and positive is right. The units are specified by the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "code": "AudioChannelDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_LeftRight"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_LeftRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_LeftRight"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelCoordinateIndex.coordinates_LeftRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_leftright"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription": {
      "abstract": [
        {
          "text": "A structure that describes a channel of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Coordinates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_DownUp",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_LeftRight",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation"
      ],
      "title": "Coordinates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelCoordinates_BackFront"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_BackFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Coordinates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_DownUp",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_LeftRight",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation"
              ],
              "title": "Coordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelCoordinates_BackFront"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_DownUp/title",
          "value": "kAudioChannelCoordinates_DownUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_DownUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_DownUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/title",
          "value": "AudioChannelCoordinateIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelCoordinateIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelCoordinateIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_LeftRight/title",
          "value": "kAudioChannelCoordinates_LeftRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_LeftRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_LeftRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/title",
          "value": "AudioChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_BackFront/title",
          "value": "kAudioChannelCoordinates_BackFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_BackFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_BackFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Distance/title",
          "value": "kAudioChannelCoordinates_Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Distance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Azimuth/title",
          "value": "kAudioChannelCoordinates_Azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Azimuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Elevation/title",
          "value": "kAudioChannelCoordinates_Elevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Elevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Elevation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_backfront"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_backfront"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
