{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents"},"metadata":{"title":"workoutEvents","role":"symbol","navigatorTitle":[{"text":"workoutEvents","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"workoutEvents"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)HKWorkoutEvent","kind":"typeIdentifier","text":"HKWorkoutEvent"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)HKWorkoutBuilder(py)workoutEvents","symbolKind":"property","platforms":[{"unavailable":false,"introducedAt":"12.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"12.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS","introducedAt":"5.0"}],"modules":[{"name":"HealthKit"}]},"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)"],"generated":true,"title":"Adding events to the workout","anchor":"Adding-events-to-the-workout"}],"variants":[{"paths":["/documentation/healthkit/hkworkoutbuilder/workoutevents"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkworkoutbuilder/workoutevents"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The list of events added to the workout."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutEvents","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKWorkoutEvent","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent","text":"HKWorkoutEvent","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"mentions":["doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions"],"kind":"mentions"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)","type":"topic","role":"symbol","title":"addWorkoutEvents(_:completion:)","navigatorTitle":[{"text":"addWorkoutEvents:completion:","kind":"identifier"}],"url":"/documentation/healthkit/hkworkoutbuilder/addworkoutevents(_:completion:)","kind":"symbol","abstract":[{"text":"Adds a workout event to the builder.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addWorkoutEvents","kind":"identifier"},{"text":"([","kind":"text"},{"text":"HKWorkoutEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutEvent"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder":{"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutBuilder"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutBuilder"}],"role":"symbol","abstract":[{"text":"A builder object that incrementally constructs a workout.","type":"text"}],"title":"HKWorkoutBuilder","url":"/documentation/healthkit/hkworkoutbuilder"},"doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions":{"abstract":[{"text":"Track a workout on Apple Watch.","type":"text"}],"role":"article","title":"Running workout sessions","identifier":"doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions","type":"topic","url":"/documentation/healthkit/running-workout-sessions","kind":"article"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutEvents","kind":"identifier"},{"text":": [","kind":"text"},{"text":"HKWorkoutEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutEvent"},{"text":"]","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The list of events added to the workout."}],"role":"symbol","url":"/documentation/healthkit/hkworkoutbuilder/workoutevents","navigatorTitle":[{"text":"workoutEvents","kind":"identifier"}],"title":"workoutEvents","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent":{"url":"/documentation/healthkit/hkworkoutevent","title":"HKWorkoutEvent","abstract":[{"text":"An object representing an important event during a workout.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutEvent"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutEvent"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"12.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"12.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS","introducedAt":"5.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"workoutEvents","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"workoutEvents"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Adding-events-to-the-workout","title":"Adding events to the workout","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<HKWorkoutEvent *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"workoutEvents","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]},"op":"replace"},{"op":"replace","value":"addWorkoutEvents:completion:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutEvents(_:completion:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addWorkoutEvents:completion:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutEvents(_:completion:)/fragments"},{"op":"replace","value":"HKWorkoutBuilder","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutBuilder"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutBuilder"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/navigatorTitle"},{"op":"replace","value":"workoutEvents","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutEvents/title"},{"op":"replace","value":[{"kind":"identifier","text":"workoutEvents"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutEvents/fragments"},{"op":"replace","value":"HKWorkoutEvent","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutEvent"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments"},{"op":"replace","value":[{"text":"HKWorkoutEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}