{
  "abstract": [
    {
      "text": "Associate an iOS device with an accessory’s network to deliver network configuration information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/configuring-a-wi-fi-accessory-to-join-a-network"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.2",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.2",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "12.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Configuring a Wi-Fi accessory to join a network"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re building a Wi-Fi accessory, getting it to join the user’s network can be a challenge.  The best way to accomplish this is by using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the MFi Wireless Accessory Configuration process.  If you can’t use that process, this sample demonstrates an alternative method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample uses a macOS app to act as an accessory and an iOS app running on an iOS device to configure that accessory.  The goal for the iOS app is to deliver network information to the accessory so it can join the user’s standard Wi-Fi network.  To do that, the iOS app needs to deliver the user’s network SSID and its passphrase to the accessory.  After receiving this information, the accessory can use it to associate itself with the same network as the iOS device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After downloading the sample, follow these steps to configure it for use:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The macOS target is ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In macOS, set up internet sharing",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "(see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/guide/mac-help/share-internet-connection-mac-network-users-mchlp1540/mac",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ").",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the SSID to ",
                      "type": "text"
                    },
                    {
                      "code": "AccessoryWiFi",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and the passphrase to ",
                      "type": "text"
                    },
                    {
                      "code": "embedded1",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure Internet Sharing to share your connection from Ethernet to computers using Wi-Fi.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The iOS target is ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessorySetup",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and requires the use of a physical device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When running the iOS target, you need to change the bundle identifier so that Xcode can create a unique provisioning profile with the project entitlements for your team.  Do this in the Xcode Signing & Capabilities pane by altering the Bundle Identifier text field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 2,
          "type": "orderedList"
        },
        {
          "anchor": "Run-the-sample-code-project",
          "level": 3,
          "text": "Run the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The macOS app creates a QR code and a network listener. The QR code contains the accessory network information. The iOS app scans the QR code and sends that network information to the ",
              "type": "text"
            },
            {
              "code": "BrandXAccessory",
              "type": "codeVoice"
            },
            {
              "text": " app for network configuration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Build and run the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Build and run the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessorySetup",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app on an iOS device, and associate the device with the user’s network.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the  ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": "  app, click Next to embed the accessory network information in a QR code.  A QR code appears with the following encoded network information:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "SSID of the accessory network: AccessoryWiFi",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Passphrase of the accessory network: embedded1",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Service URL for ",
                              "type": "text"
                            },
                            {
                              "code": "NWConnection",
                              "type": "codeVoice"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "TLS PSK",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "TLS PSK identity",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Capture Accessory Network Info to bring up a QR code capture session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Point the iOS device’s camera at the QR code in the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app to capture, decode, and save the QR data.  Tap Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Get Network Info to capture the user’s network SSID. Tap Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Associate to Accessory Network.  ",
                      "type": "text"
                    },
                    {
                      "code": "NEHotspotConfiguration",
                      "type": "codeVoice"
                    },
                    {
                      "text": " creates a Wi-Fi configuration with the accessory’s network data from the QR code, applies it to the device, and updates the device’s screen when the association finishes. Tap Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Confirm Network to confirm the device’s association with the accessory network. Tap Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app, click Start Listener so the ",
                      "type": "text"
                    },
                    {
                      "code": "NWListener",
                      "type": "codeVoice"
                    },
                    {
                      "text": " begins listening for incoming connections from the iOS app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Enter Network Passphrase and enter the passphrase for the user’s network. Tap Set Passphrase.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In  the iOS app, tap Send Network Data. The sample sends the passphrase to the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app, along with the user’s network SSID.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the ",
                      "type": "text"
                    },
                    {
                      "code": "BrandXAccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " app, the view displays the SSID and passphrase of the user’s network.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the iOS app, tap Next, and then tap Remove Network Configuration to disassociate from the accessory network and rejoin the user’s network.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser": {
      "abstract": [
        {
          "text": "An object you use to scan for wireless accessories and configure them for use with the user’s app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryBrowser"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAWiFiUnconfiguredAccessoryBrowser",
      "type": "topic",
      "url": "/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/hotspot-helper": {
      "abstract": [
        {
          "text": "Integrate your app with the iOS hotspot network subsystem.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/hotspot-helper",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hotspot helper",
      "type": "topic",
      "url": "/documentation/networkextension/hotspot-helper"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/wi-fi-configuration": {
      "abstract": [
        {
          "text": "Add persistent Wi-Fi configurations, or temporarily move the device to a specific Wi-Fi network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/wi-fi-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wi-Fi configuration",
      "type": "topic",
      "url": "/documentation/networkextension/wi-fi-configuration"
    },
    "fc33836bc209/ConfiguringAWiFiAccessoryToJoinANetwork.zip": {
      "checksum": "fc33836bc209f0fc5ad8116f337027b2547f47a2676c15684e2fc719f08a88e8854197f1ea8a51753ae9764604176901627e279f6d2a970924aee04fe0aefe2c",
      "identifier": "fc33836bc209/ConfiguringAWiFiAccessoryToJoinANetwork.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/fc33836bc209/ConfiguringAWiFiAccessoryToJoinANetwork.zip"
    },
    "https://support.apple.com/guide/mac-help/share-internet-connection-mac-network-users-mchlp1540/mac": {
      "identifier": "https://support.apple.com/guide/mac-help/share-internet-connection-mac-network-users-mchlp1540/mac",
      "title": "Share the internet connection on Mac with other network users",
      "titleInlineContent": [
        {
          "text": "Share the internet connection on Mac with other network users",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/mac-help/share-internet-connection-mac-network-users-mchlp1540/mac"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "fc33836bc209/ConfiguringAWiFiAccessoryToJoinANetwork.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Wi-Fi-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/wi-fi-configuration",
        "doc://com.apple.networkextension/documentation/NetworkExtension/hotspot-helper"
      ],
      "title": "Wi-Fi management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Wi-Fi-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/wi-fi-configuration",
                "doc://com.apple.networkextension/documentation/NetworkExtension/hotspot-helper"
              ],
              "title": "Wi-Fi management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowser/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryBrowser"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/configuring-a-wi-fi-accessory-to-join-a-network"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/configuring-a-wi-fi-accessory-to-join-a-network"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
