{
  "abstract": [
    {
      "text": "Create and manage a system-wide DNS configuration that uses built-in encrypted DNS protocols.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/dns-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DNS settings"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the DNS Settings feature in macOS and iOS, your app can create and manage a configuration that uses one of the built-in DNS protocols: DNS-over-TLS or DNS-over-HTTPS. The user must explictly enable your configuration in order to use the server you specify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension": {
      "abstract": [
        {
          "text": "The APIs an app can use to customize networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
      "kind": "symbol",
      "role": "symbol",
      "title": "Network Extensions Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverHTTPSSettings": {
      "abstract": [
        {
          "text": "The DNS resolver settings for a DNS-over-HTTPS server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEDNSOverHTTPSSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverHTTPSSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEDNSOverHTTPSSettings"
        }
      ],
      "role": "symbol",
      "title": "NEDNSOverHTTPSSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nednsoverhttpssettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverTLSSettings": {
      "abstract": [
        {
          "text": "The DNS resolver settings for a DNS-over-TLS server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEDNSOverTLSSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverTLSSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEDNSOverTLSSettings"
        }
      ],
      "role": "symbol",
      "title": "NEDNSOverTLSSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nednsovertlssettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager": {
      "abstract": [
        {
          "text": "An object you use to create and manage a DNS settings configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEDNSSettingsManager"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEDNSSettingsManager"
        }
      ],
      "role": "symbol",
      "title": "NEDNSSettingsManager",
      "type": "topic",
      "url": "/documentation/networkextension/nednssettingsmanager"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/dns-proxy-provider": {
      "abstract": [
        {
          "text": "Create an on-device DNS proxy using a custom protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/dns-proxy-provider",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS proxy provider",
      "type": "topic",
      "url": "/documentation/networkextension/dns-proxy-provider"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "DNS-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/dns-proxy-provider"
      ],
      "title": "DNS configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "DNS-configuration",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverHTTPSSettings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverTLSSettings"
      ],
      "title": "DNS configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "DNS-configuration",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSSettingsManager",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverHTTPSSettings",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEDNSOverTLSSettings"
              ],
              "title": "DNS configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "DNS-configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/dns-proxy-provider"
              ],
              "title": "DNS configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/title",
          "value": "NEDNSSettingsManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSSettingsManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSSettingsManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSSettingsManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverTLSSettings/title",
          "value": "NEDNSOverTLSSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverTLSSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSOverTLSSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverTLSSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSOverTLSSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverHTTPSSettings/title",
          "value": "NEDNSOverHTTPSSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverHTTPSSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSOverHTTPSSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEDNSOverHTTPSSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEDNSOverHTTPSSettings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/dns-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/dns-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
