{
  "abstract": [
    {
      "text": "An error that the app proxy flow encounters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC19NEAppProxyFlowErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEAppProxyFlowError"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEAppProxyFlowError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NEAppProxyFlowError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain": {
      "abstract": [
        {
          "text": "The domain used for app proxy errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyErrorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyerrordomain"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct": {
      "abstract": [
        {
          "text": "An error that the app proxy flow encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyFlowError"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that the app proxy flow API declares.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyFlowError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/aborted": {
      "abstract": [
        {
          "text": "The flow was aborted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aborted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/aborted",
      "kind": "symbol",
      "role": "symbol",
      "title": "aborted",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/aborted"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/datagramTooLarge": {
      "abstract": [
        {
          "text": "A caller attempted to write a datagram that was larger than the socket’s receive window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datagramTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/datagramTooLarge",
      "kind": "symbol",
      "role": "symbol",
      "title": "datagramTooLarge",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/datagramtoolarge"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/errordomain"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/hostUnreachable": {
      "abstract": [
        {
          "text": "An attempt to reach the remote endpoint of the flow failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostUnreachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/hostUnreachable",
      "kind": "symbol",
      "role": "symbol",
      "title": "hostUnreachable",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/hostunreachable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/internal": {
      "abstract": [
        {
          "text": "An internal error occurred while handling the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/internal",
      "kind": "symbol",
      "role": "symbol",
      "title": "internal",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/internal"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/invalidArgument": {
      "abstract": [
        {
          "text": "A proxy flow method received an invalid argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/invalidargument"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/notConnected": {
      "abstract": [
        {
          "text": "The flow is not fully opened.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/notConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "notConnected",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/notconnected"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/peerReset": {
      "abstract": [
        {
          "text": "The remote peer closed the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerReset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/peerReset",
      "kind": "symbol",
      "role": "symbol",
      "title": "peerReset",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/peerreset"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/readAlreadyPending": {
      "abstract": [
        {
          "text": "A read operation on the flow is already pending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAlreadyPending"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/readAlreadyPending",
      "kind": "symbol",
      "role": "symbol",
      "title": "readAlreadyPending",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/readalreadypending"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/refused": {
      "abstract": [
        {
          "text": "Connecting the flow to its remote endpoint failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/refused",
      "kind": "symbol",
      "role": "symbol",
      "title": "refused",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/refused"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/timedOut": {
      "abstract": [
        {
          "text": "The flow timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC19NEAppProxyFlowErrorLeV",
          "text": "NEAppProxyFlowError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEAppProxyFlowError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/timedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "timedOut",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflowerror-swift.struct/timedout"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyErrorDomain",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-error-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/Code"
      ],
      "title": "Accessing error properties"
    },
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/notConnected",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/peerReset",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/hostUnreachable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/invalidArgument",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/aborted",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/refused",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/timedOut",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/internal",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/datagramTooLarge",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/readAlreadyPending"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlowError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyErrorDomain/title",
          "value": "NEAppProxyErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/title",
          "value": "NEAppProxyFlowError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlowError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyFlowError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neappproxyflowerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
