{
  "abstract": [
    {
      "text": "The abstract base class for types that represent flows of network data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEFilterFlow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEFilterFlow"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEFilterFlow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NEFilterFlow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow": {
      "abstract": [
        {
          "text": "A flow of network data, originating from a WebKit-based browser, that the filter examines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterBrowserFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterBrowserFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterBrowserFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterbrowserflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict": {
      "abstract": [
        {
          "text": "The result from a filter control provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterControlVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterControlVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterControlVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltercontrolverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provder for subsequent chunks of data on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterDataVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow": {
      "abstract": [
        {
          "text": "The abstract base class for types that represent flows of network data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/direction": {
      "abstract": [
        {
          "text": "The initial direction of the flow: incoming or outgoing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "direction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NETrafficDirection",
          "text": "NETrafficDirection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/direction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "direction"
        }
      ],
      "role": "symbol",
      "title": "direction",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/direction"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/identifier": {
      "abstract": [
        {
          "text": "The unique identifier of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/identifier"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppAuditToken": {
      "abstract": [
        {
          "text": "The audit token of the source application of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAppAuditToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppAuditToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAppAuditToken"
        }
      ],
      "role": "symbol",
      "title": "sourceAppAuditToken",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/sourceappaudittoken"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppIdentifier": {
      "abstract": [
        {
          "text": "A string containing the identifier of the source app of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAppIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAppIdentifier"
        }
      ],
      "role": "symbol",
      "title": "sourceAppIdentifier",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/sourceappidentifier"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppUniqueIdentifier": {
      "abstract": [
        {
          "text": "A byte string that uniquely identifies the binary for each build of the app that is the source of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAppUniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppUniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAppUniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "sourceAppUniqueIdentifier",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/sourceappuniqueidentifier"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppVersion": {
      "abstract": [
        {
          "text": "The short version string of the app that is the source of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAppVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAppVersion"
        }
      ],
      "role": "symbol",
      "title": "sourceAppVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/sourceappversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceProcessAuditToken": {
      "abstract": [
        {
          "text": "The audit token of the process that created the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceProcessAuditToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceProcessAuditToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceProcessAuditToken"
        }
      ],
      "role": "symbol",
      "title": "sourceProcessAuditToken",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/sourceprocessaudittoken"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/url": {
      "abstract": [
        {
          "text": "The flow’s HTTP URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow/url"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlowBytesMax": {
      "abstract": [
        {
          "text": "The maximum number of bytes to pass or peek for a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterFlowBytesMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlowBytesMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterFlowBytesMax"
        }
      ],
      "role": "symbol",
      "title": "NEFilterFlowBytesMax",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflowbytesmax"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provder after the initial examination of a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterNewFlowVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provider after the user requests remediation for a blocked flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterRemediationVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterRemediationVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterRemediationVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterremediationverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport": {
      "abstract": [
        {
          "text": "The report of the data provider’s action on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow": {
      "abstract": [
        {
          "text": "A flow of network data that the filter examines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterSocketFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterSocketFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterSocketFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltersocketflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict": {
      "abstract": [
        {
          "text": "The abstract base class for filter verdict classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection": {
      "abstract": [
        {
          "text": "A type to represent the direction of network traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NETrafficDirection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETrafficDirection"
        }
      ],
      "role": "symbol",
      "title": "NETrafficDirection",
      "type": "topic",
      "url": "/documentation/networkextension/netrafficdirection"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flow-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport"
      ],
      "title": "Flow handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-flow-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/url",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/identifier",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/direction",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlowBytesMax"
      ],
      "title": "Inspecting flow properties"
    },
    {
      "anchor": "Source-app-identification",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppUniqueIdentifier",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppIdentifier",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppVersion",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppAuditToken",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceProcessAuditToken"
      ],
      "title": "Source app identification"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEFilterFlow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-flow-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/url",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/identifier",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/direction",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlowBytesMax"
              ],
              "title": "Inspecting flow properties"
            },
            {
              "anchor": "Source-app-identification",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppUniqueIdentifier",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppIdentifier",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppVersion",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceAppAuditToken",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow/sourceProcessAuditToken"
              ],
              "title": "Source app identification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Flow-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport"
              ],
              "title": "Flow handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEFilterFlow"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/title",
          "value": "NEFilterDataVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/title",
          "value": "NEFilterControlVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterControlVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterControlVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppUniqueIdentifier/title",
          "value": "sourceAppUniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppUniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAppUniqueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/title",
          "value": "NEFilterReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/title",
          "value": "NETrafficDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETrafficDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NETrafficDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1direction/title",
          "value": "direction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1direction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "direction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/title",
          "value": "NEFilterFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/title",
          "value": "NEFilterSocketFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSocketFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSocketFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/title",
          "value": "NEFilterBrowserFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterBrowserFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterBrowserFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppIdentifier/title",
          "value": "sourceAppIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAppIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/title",
          "value": "NEFilterRemediationVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRemediationVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRemediationVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceProcessAuditToken/title",
          "value": "sourceProcessAuditToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceProcessAuditToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceProcessAuditToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/title",
          "value": "NEFilterNewFlowVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/title",
          "value": "NEFilterVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlowBytesMax/title",
          "value": "NEFilterFlowBytesMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlowBytesMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlowBytesMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppAuditToken/title",
          "value": "sourceAppAuditToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppAuditToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAppAuditToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppVersion/title",
          "value": "sourceAppVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow~1sourceAppVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAppVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefilterflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefilterflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
