{
  "abstract": [
    {
      "text": "The result from a filter data provder after the initial examination of a flow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEFilterNewFlowVerdict",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEFilterNewFlowVerdict"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEFilterNewFlowVerdict"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NEFilterNewFlowVerdict"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow": {
      "abstract": [
        {
          "text": "A flow of network data, originating from a WebKit-based browser, that the filter examines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterBrowserFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterBrowserFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterBrowserFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterbrowserflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict": {
      "abstract": [
        {
          "text": "The result from a filter control provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterControlVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterControlVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterControlVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltercontrolverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provder for subsequent chunks of data on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterDataVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterDataVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterdataverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow": {
      "abstract": [
        {
          "text": "The abstract base class for types that represent flows of network data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provder after the initial examination of a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterNewFlowVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/allow()": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that the all of the new flow’s data should be allowed to pass to its final destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allow"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/allow()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowVerdict"
        }
      ],
      "role": "symbol",
      "title": "allow()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/allow()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/drop()": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that all of the new flow’s data should dropped, and the user should not be given the opportunity to request access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/drop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropVerdict"
        }
      ],
      "role": "symbol",
      "title": "drop()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/drop()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that the filter needs to make a decision about a new flow after seeing a portion of the flow’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterDataVerdict"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFilterInbound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "peekInboundBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filterOutbound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "peekOutboundBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filterDataVerdictWithFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:"
        }
      ],
      "role": "symbol",
      "title": "filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/filterdataverdict(withfilterinbound:peekinboundbytes:filteroutbound:peekoutboundbytes:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/needRules()": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that the Filter Data Provider needs more information before it can make a decision about a new flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needRules"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/needRules()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needRulesVerdict"
        }
      ],
      "role": "symbol",
      "title": "needRules()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/needrules()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/pause()": {
      "abstract": [
        {
          "text": "Creates a verdict that tells the system to pause the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseVerdict"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/pause()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that all of the new flow’s data should be dropped, but allow the user to request access by tapping or clicking on a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remediateVerdict"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRemediationURLMapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "remediationButtonTextMapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
        }
      ],
      "role": "symbol",
      "title": "remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/remediateverdict(withremediationurlmapkey:remediationbuttontextmapkey:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/statisticsReportFrequency": {
      "abstract": [
        {
          "text": "The frequency at which the data provider receives reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statisticsReportFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterReport",
          "text": "NEFilterReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEFilterReportFrequency",
          "text": "Frequency"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/statisticsReportFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statisticsReportFrequency"
        }
      ],
      "role": "symbol",
      "title": "statisticsReportFrequency",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/statisticsreportfrequency"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/urlAppendStringVerdict(withMapKey:)": {
      "abstract": [
        {
          "text": "Create a verdict that indicates to the system that all of the new flow’s data should be allowed to pass to its final destination, but a string should first be appended to the new flow’s request URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlAppendStringVerdict"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMapKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterNewFlowVerdict",
          "text": "NEFilterNewFlowVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/urlAppendStringVerdict(withMapKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLAppendStringVerdictWithMapKey:"
        }
      ],
      "role": "symbol",
      "title": "urlAppendStringVerdict(withMapKey:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefilternewflowverdict/urlappendstringverdict(withmapkey:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict": {
      "abstract": [
        {
          "text": "The result from a filter data provider after the user requests remediation for a blocked flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterRemediationVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterRemediationVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterRemediationVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterremediationverdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport": {
      "abstract": [
        {
          "text": "The report of the data provider’s action on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Frequency": {
      "abstract": [
        {
          "text": "An enumeration that represents the frequency of filter report delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Frequency"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Frequency"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Frequency",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/frequency"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow": {
      "abstract": [
        {
          "text": "A flow of network data that the filter examines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterSocketFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterSocketFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterSocketFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltersocketflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict": {
      "abstract": [
        {
          "text": "The abstract base class for filter verdict classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterVerdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterVerdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterVerdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterverdict"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flow-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport"
      ],
      "title": "Flow handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-new-flow-verdicts",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/allow()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/drop()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/pause()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/needRules()",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/urlAppendStringVerdict(withMapKey:)"
      ],
      "title": "Creating new flow verdicts"
    },
    {
      "anchor": "Inspecting-new-flow-verdict-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/statisticsReportFrequency",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Frequency"
      ],
      "title": "Inspecting new flow verdict properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEFilterNewFlowVerdict"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-new-flow-verdicts",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/allow()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/drop()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/pause()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/needRules()",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/urlAppendStringVerdict(withMapKey:)"
              ],
              "title": "Creating new flow verdicts"
            },
            {
              "anchor": "Inspecting-new-flow-verdict-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterNewFlowVerdict/statisticsReportFrequency",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Frequency"
              ],
              "title": "Inspecting new flow verdict properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Flow-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterBrowserFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSocketFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterDataVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterControlVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRemediationVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport"
              ],
              "title": "Flow handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEFilterNewFlowVerdict"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterVerdict",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NEFilterVerdict",
                    "text": "NEFilterVerdict"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/title",
          "value": "NEFilterRemediationVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRemediationVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRemediationVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRemediationVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/title",
          "value": "NEFilterFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1statisticsReportFrequency/title",
          "value": "statisticsReportFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1statisticsReportFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statisticsReportFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1needRules()/title",
          "value": "needRulesVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1needRules()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "needRulesVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Frequency/title",
          "value": "NEFilterReportFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Frequency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)/title",
          "value": "filterDataVerdictWithFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1filterDataVerdict(withFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "filterDataVerdictWithFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/title",
          "value": "NEFilterNewFlowVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterNewFlowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)/title",
          "value": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1remediateVerdict(withRemediationURLMapKey:remediationButtonTextMapKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "remediateVerdictWithRemediationURLMapKey:remediationButtonTextMapKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1allow()/title",
          "value": "allowVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1allow()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allowVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/title",
          "value": "NEFilterControlVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterControlVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterControlVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterControlVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/title",
          "value": "NEFilterVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/title",
          "value": "NEFilterSocketFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSocketFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSocketFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSocketFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/title",
          "value": "NEFilterBrowserFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterBrowserFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterBrowserFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterBrowserFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1drop()/title",
          "value": "dropVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1drop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dropVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/title",
          "value": "NEFilterReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/title",
          "value": "NEFilterDataVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterDataVerdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterDataVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1pause()/title",
          "value": "pauseVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pauseVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1urlAppendStringVerdict(withMapKey:)/title",
          "value": "URLAppendStringVerdictWithMapKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterNewFlowVerdict~1urlAppendStringVerdict(withMapKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "URLAppendStringVerdictWithMapKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefilternewflowverdict"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefilternewflowverdict"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
