{
  "abstract": [
    {
      "text": "An enumeration of constants that define Wi-Fi hotspot network security types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotNetworkSecurityType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEHotspotNetworkSecurityType"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotNetworkSecurityType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEHotspotNetworkSecurityType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/bssid": {
      "abstract": [
        {
          "text": "The BSSID for the Wi-Fi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/bssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BSSID"
        }
      ],
      "role": "symbol",
      "title": "bssid",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/bssid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didAutoJoin": {
      "abstract": [
        {
          "text": "Indicates whether the network was joined automatically or was joined explicitly by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didAutoJoin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didAutoJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoJoined"
        }
      ],
      "role": "symbol",
      "title": "didAutoJoin",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/didautojoin"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didJustJoin": {
      "abstract": [
        {
          "text": "Indicates whether the network was just joined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didJustJoin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didJustJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "justJoined"
        }
      ],
      "role": "symbol",
      "title": "didJustJoin",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/didjustjoin"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isChosenHelper": {
      "abstract": [
        {
          "text": "Indicates whether the calling Hotspot Helper is the chosen helper for this network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isChosenHelper"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isChosenHelper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chosenHelper"
        }
      ],
      "role": "symbol",
      "title": "isChosenHelper",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/ischosenhelper"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isSecure": {
      "abstract": [
        {
          "text": "Indicates whether the network is secure",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSecure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isSecure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secure"
        }
      ],
      "role": "symbol",
      "title": "isSecure",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/issecure"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/securityType": {
      "abstract": [
        {
          "text": "The type of security used by the Wi-Fi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEHotspotNetworkSecurityType",
          "text": "NEHotspotNetworkSecurityType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/securityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "securityType"
        }
      ],
      "role": "symbol",
      "title": "securityType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/securitytype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/signalStrength": {
      "abstract": [
        {
          "text": "The recent signal strength for the Wi-Fi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signalStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/signalStrength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signalStrength"
        }
      ],
      "role": "symbol",
      "title": "signalStrength",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/signalstrength"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/ssid": {
      "abstract": [
        {
          "text": "The SSID for the Wi-Fi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/ssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSID"
        }
      ],
      "role": "symbol",
      "title": "ssid",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetwork/ssid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType": {
      "abstract": [
        {
          "text": "An enumeration of constants that define Wi-Fi hotspot network security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP": {
      "abstract": [
        {
          "text": "A security type to represent use of Wired Equivalent Privacy (WEP).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WEP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeWEP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.WEP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/wep"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise": {
      "abstract": [
        {
          "text": "A security type to represent use of Wi-Fi protected access (WPA), WPA2, and WPA3 standards using enterprise-level seciurity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterprise"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeEnterprise"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.enterprise",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/enterprise"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open": {
      "abstract": [
        {
          "text": "A security type to represent an open network with no security protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeOpen"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.open",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/open"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal": {
      "abstract": [
        {
          "text": "A security type to represent use of Wi-Fi protected access (WPA), WPA2, and WPA3 standards using a pre-shared secret.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personal"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypePersonal"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.personal",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/personal"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown": {
      "abstract": [
        {
          "text": "A value that represents an unknown security type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.unknown",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/unknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/ssid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/bssid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/signalStrength",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isSecure",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didAutoJoin",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didJustJoin",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isChosenHelper",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/securityType"
      ],
      "title": "Network information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Security-types",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown"
      ],
      "title": "Security types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEHotspotNetworkSecurityType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Security-types",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown"
              ],
              "title": "Security types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/ssid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/bssid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/signalStrength",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isSecure",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didAutoJoin",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/didJustJoin",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/isChosenHelper",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetwork/securityType"
              ],
              "title": "Network information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEHotspotNetworkSecurityType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1didJustJoin/title",
          "value": "justJoined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1didJustJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "justJoined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1personal/title",
          "value": "NEHotspotNetworkSecurityTypePersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypePersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1unknown/title",
          "value": "NEHotspotNetworkSecurityTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1isChosenHelper/title",
          "value": "chosenHelper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1isChosenHelper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chosenHelper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1enterprise/title",
          "value": "NEHotspotNetworkSecurityTypeEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1WEP/title",
          "value": "NEHotspotNetworkSecurityTypeWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1WEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1signalStrength/title",
          "value": "signalStrength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1signalStrength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signalStrength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1bssid/title",
          "value": "BSSID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1bssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BSSID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1isSecure/title",
          "value": "secure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1isSecure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1securityType/title",
          "value": "securityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1securityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1open/title",
          "value": "NEHotspotNetworkSecurityTypeOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1open/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/title",
          "value": "NEHotspotNetworkSecurityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1didAutoJoin/title",
          "value": "autoJoined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1didAutoJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoJoined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1ssid/title",
          "value": "SSID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetwork~1ssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspotnetworksecuritytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspotnetworksecuritytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
