{
  "abstract": [
    {
      "text": "Error values returned by hotspot configuration manager methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotConfigurationError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationError"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEHotspotConfigurationError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError": {
      "abstract": [
        {
          "text": "Error values returned by hotspot configuration manager methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationError"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/alreadyAssociated": {
      "abstract": [
        {
          "text": "The configuration is already associated with the hotspot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyAssociated"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/alreadyAssociated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorAlreadyAssociated"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.alreadyAssociated",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/alreadyassociated"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/applicationIsNotInForeground": {
      "abstract": [
        {
          "text": "The application is not running in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIsNotInForeground"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/applicationIsNotInForeground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorApplicationIsNotInForeground"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.applicationIsNotInForeground",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/applicationisnotinforeground"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/internal": {
      "abstract": [
        {
          "text": "Internal error, otherwise undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.internal",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/internal"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalid": {
      "abstract": [
        {
          "text": "The configuration is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalid",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidEAPSettings": {
      "abstract": [
        {
          "text": "EAP settings are not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEAPSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidEAPSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidEAPSettings"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidEAPSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalideapsettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20DomainName": {
      "abstract": [
        {
          "text": "The HS 2.0 domain name is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHS20DomainName"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20DomainName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidHS20DomainName"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidHS20DomainName",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidhs20domainname"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20Settings": {
      "abstract": [
        {
          "text": "The HS 2.0 settings are not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHS20Settings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20Settings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidHS20Settings"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidHS20Settings",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidhs20settings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSID": {
      "abstract": [
        {
          "text": "The SSID value is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSSID"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidSSID"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidSSID",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidssid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSIDPrefix": {
      "abstract": [
        {
          "text": "The SSID prefix used to create the hotspot configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSSIDPrefix"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSIDPrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidSSIDPrefix"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidSSIDPrefix",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidssidprefix"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWEPPassphrase": {
      "abstract": [
        {
          "text": "The WEP passphrase is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWEPPassphrase"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWEPPassphrase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidWEPPassphrase"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidWEPPassphrase",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidweppassphrase"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWPAPassphrase": {
      "abstract": [
        {
          "text": "The WPA passphrase is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWPAPassphrase"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWPAPassphrase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorInvalidWPAPassphrase"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.invalidWPAPassphrase",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/invalidwpapassphrase"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/joinOnceNotSupported": {
      "abstract": [
        {
          "text": "The join-once option isn’t support for EAP configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "joinOnceNotSupported"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/joinOnceNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorJoinOnceNotSupported"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.joinOnceNotSupported",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/joinoncenotsupported"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/pending": {
      "abstract": [
        {
          "text": "The network configuration action has not completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorPending"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.pending",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/pending"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemConfiguration": {
      "abstract": [
        {
          "text": "The system configuration is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemConfiguration"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorSystemConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.systemConfiguration",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/systemconfiguration"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemDenied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemDenied"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorSystemDenied"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.systemDenied",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/systemdenied"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/unknown": {
      "abstract": [
        {
          "text": "An unknown error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.unknown",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/unknown"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userDenied": {
      "abstract": [
        {
          "text": "The user has refused the network configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDenied"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorUserDenied"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.userDenied",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/userdenied"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userUnauthorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorUserUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationError.userUnauthorized",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerror/userunauthorized"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationErrorDomain": {
      "abstract": [
        {
          "text": "The domain string for errors involving hotspot configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotConfigurationErrorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSID",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWPAPassphrase",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWEPPassphrase",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidEAPSettings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20Settings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20DomainName",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSIDPrefix",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userDenied",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/internal",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/pending",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemConfiguration",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/unknown",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/joinOnceNotSupported",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/alreadyAssociated",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/applicationIsNotInForeground"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemDenied",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userUnauthorized"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEHotspotConfigurationError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSID",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWPAPassphrase",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidWEPPassphrase",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidEAPSettings",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20Settings",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidHS20DomainName",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/invalidSSIDPrefix",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userDenied",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/internal",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/pending",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemConfiguration",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/unknown",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/joinOnceNotSupported",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/alreadyAssociated",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/applicationIsNotInForeground"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/systemDenied",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationError/userUnauthorized"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEHotspotConfigurationError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1unknown/title",
          "value": "NEHotspotConfigurationErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1joinOnceNotSupported/title",
          "value": "NEHotspotConfigurationErrorJoinOnceNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1joinOnceNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorJoinOnceNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1alreadyAssociated/title",
          "value": "NEHotspotConfigurationErrorAlreadyAssociated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1alreadyAssociated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorAlreadyAssociated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError/title",
          "value": "NEHotspotConfigurationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidSSIDPrefix/title",
          "value": "NEHotspotConfigurationErrorInvalidSSIDPrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidSSIDPrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidSSIDPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalid/title",
          "value": "NEHotspotConfigurationErrorInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1userUnauthorized/title",
          "value": "NEHotspotConfigurationErrorUserUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1userUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorUserUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidEAPSettings/title",
          "value": "NEHotspotConfigurationErrorInvalidEAPSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidEAPSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidSSID/title",
          "value": "NEHotspotConfigurationErrorInvalidSSID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidSSID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidSSID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1internal/title",
          "value": "NEHotspotConfigurationErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationErrorDomain/title",
          "value": "NEHotspotConfigurationErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1userDenied/title",
          "value": "NEHotspotConfigurationErrorUserDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1userDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorUserDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidHS20DomainName/title",
          "value": "NEHotspotConfigurationErrorInvalidHS20DomainName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidHS20DomainName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidHS20DomainName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1systemConfiguration/title",
          "value": "NEHotspotConfigurationErrorSystemConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1systemConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorSystemConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidWPAPassphrase/title",
          "value": "NEHotspotConfigurationErrorInvalidWPAPassphrase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidWPAPassphrase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidWPAPassphrase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1applicationIsNotInForeground/title",
          "value": "NEHotspotConfigurationErrorApplicationIsNotInForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1applicationIsNotInForeground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorApplicationIsNotInForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1pending/title",
          "value": "NEHotspotConfigurationErrorPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1systemDenied/title",
          "value": "NEHotspotConfigurationErrorSystemDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1systemDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorSystemDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidHS20Settings/title",
          "value": "NEHotspotConfigurationErrorInvalidHS20Settings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidHS20Settings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidHS20Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidWEPPassphrase/title",
          "value": "NEHotspotConfigurationErrorInvalidWEPPassphrase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotConfigurationError~1invalidWEPPassphrase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationErrorInvalidWEPPassphrase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspotconfigurationerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspotconfigurationerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
