{
  "abstract": [
    {
      "text": "Reasons why the provider extension was stopped.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEProviderStopReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEProviderStopReason"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEProviderStopReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEProviderStopReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEProviderStopReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "NEProviderStopReasonUserLogout",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "NEProviderStopReasonUserSwitch",
              "type": "codeVoice"
            },
            {
              "text": " are available only in macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason": {
      "abstract": [
        {
          "text": "Reasons why the provider extension was stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEProviderStopReason"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReason"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/appUpdate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appUpdate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/appUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonAppUpdate"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.appUpdate",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/appupdate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/authenticationCanceled": {
      "abstract": [
        {
          "text": "The authentication process was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationCanceled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/authenticationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonAuthenticationCanceled"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.authenticationCanceled",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/authenticationcanceled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationDisabled": {
      "abstract": [
        {
          "text": "The configuration was disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonConfigurationDisabled"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationFailed": {
      "abstract": [
        {
          "text": "The configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonConfigurationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.configurationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/configurationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationRemoved": {
      "abstract": [
        {
          "text": "The configuration was removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationRemoved"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonConfigurationRemoved"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.configurationRemoved",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/configurationremoved"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/connectionFailed": {
      "abstract": [
        {
          "text": "The connection failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/connectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.connectionFailed",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/connectionfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/idleTimeout": {
      "abstract": [
        {
          "text": "The session timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idleTimeout"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/idleTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonIdleTimeout"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.idleTimeout",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/idletimeout"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/internalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonInternalError"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.internalError",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/internalerror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/noNetworkAvailable": {
      "abstract": [
        {
          "text": "No network connectivity is currently available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noNetworkAvailable"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/noNetworkAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonNoNetworkAvailable"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.noNetworkAvailable",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/nonetworkavailable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/none": {
      "abstract": [
        {
          "text": "No specific reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonNone"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.none",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/none"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerDisabled": {
      "abstract": [
        {
          "text": "The provider was disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonProviderDisabled"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.providerDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/providerdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerFailed": {
      "abstract": [
        {
          "text": "The provider failed to function correctly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonProviderFailed"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.providerFailed",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/providerfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/sleep": {
      "abstract": [
        {
          "text": "A stop reason indicating the configuration enabled disconnect on sleep and the device went to sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleep"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/sleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonSleep"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.sleep",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/sleep"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/superceded": {
      "abstract": [
        {
          "text": "The configuration was superceded by a higher-priority configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "superceded"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/superceded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonSuperceded"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.superceded",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/superceded"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/unrecoverableNetworkChange": {
      "abstract": [
        {
          "text": "The device’s network connectivity changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecoverableNetworkChange"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/unrecoverableNetworkChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonUnrecoverableNetworkChange"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.unrecoverableNetworkChange",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/unrecoverablenetworkchange"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userInitiated": {
      "abstract": [
        {
          "text": "The user stopped the provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInitiated"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userInitiated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonUserInitiated"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.userInitiated",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/userinitiated"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userLogout": {
      "abstract": [
        {
          "text": "The user logged out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userLogout"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userLogout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonUserLogout"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.userLogout",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/userlogout"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userSwitch": {
      "abstract": [
        {
          "text": "The current console user changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userSwitch"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEProviderStopReasonUserSwitch"
        }
      ],
      "role": "symbol",
      "title": "NEProviderStopReason.userSwitch",
      "type": "topic",
      "url": "/documentation/networkextension/neproviderstopreason/userswitch"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Stop-Reasons",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/none",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userInitiated",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/noNetworkAvailable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/unrecoverableNetworkChange",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/authenticationCanceled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/idleTimeout",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationRemoved",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/superceded",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userLogout",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userSwitch",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/appUpdate",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/connectionFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/sleep"
      ],
      "title": "Stop Reasons"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/internalError"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEProviderStopReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stop-Reasons",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/none",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userInitiated",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/noNetworkAvailable",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/unrecoverableNetworkChange",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/providerDisabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/authenticationCanceled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/idleTimeout",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationDisabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/configurationRemoved",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/superceded",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userLogout",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/userSwitch",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/appUpdate",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/connectionFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/sleep"
              ],
              "title": "Stop Reasons"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEProviderStopReason/internalError"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEProviderStopReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1connectionFailed/title",
          "value": "NEProviderStopReasonConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1connectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationRemoved/title",
          "value": "NEProviderStopReasonConfigurationRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonConfigurationRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason/title",
          "value": "NEProviderStopReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1internalError/title",
          "value": "NEProviderStopReasonInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1unrecoverableNetworkChange/title",
          "value": "NEProviderStopReasonUnrecoverableNetworkChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1unrecoverableNetworkChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonUnrecoverableNetworkChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1providerFailed/title",
          "value": "NEProviderStopReasonProviderFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1providerFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonProviderFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1authenticationCanceled/title",
          "value": "NEProviderStopReasonAuthenticationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1authenticationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonAuthenticationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationDisabled/title",
          "value": "NEProviderStopReasonConfigurationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonConfigurationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userSwitch/title",
          "value": "NEProviderStopReasonUserSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonUserSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1providerDisabled/title",
          "value": "NEProviderStopReasonProviderDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1providerDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonProviderDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationFailed/title",
          "value": "NEProviderStopReasonConfigurationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1configurationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonConfigurationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userLogout/title",
          "value": "NEProviderStopReasonUserLogout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userLogout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonUserLogout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1none/title",
          "value": "NEProviderStopReasonNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1sleep/title",
          "value": "NEProviderStopReasonSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1sleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1superceded/title",
          "value": "NEProviderStopReasonSuperceded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1superceded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonSuperceded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1idleTimeout/title",
          "value": "NEProviderStopReasonIdleTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1idleTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonIdleTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1noNetworkAvailable/title",
          "value": "NEProviderStopReasonNoNetworkAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1noNetworkAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonNoNetworkAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userInitiated/title",
          "value": "NEProviderStopReasonUserInitiated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1userInitiated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonUserInitiated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1appUpdate/title",
          "value": "NEProviderStopReasonAppUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEProviderStopReason~1appUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEProviderStopReasonAppUpdate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neproviderstopreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neproviderstopreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
