{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2IntegrityAlgorithm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2IntegrityAlgorithm"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2IntegrityAlgorithm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEVPNIKEv2IntegrityAlgorithm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup": {
      "abstract": [
        {
          "text": "An enumeration of Diffie-Hellman group values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm": {
      "abstract": [
        {
          "text": "An enumeration of encryption algorithm values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160": {
      "abstract": [
        {
          "text": "SHA-1 160-bit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA160"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA160",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha160"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256": {
      "abstract": [
        {
          "text": "SHA-2 256-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA256"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA256"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA256",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha256"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384": {
      "abstract": [
        {
          "text": "SHA-2 384-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA384"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA384"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA384",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha384"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512": {
      "abstract": [
        {
          "text": "SHA-2 512-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA512"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA512"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA512",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha512"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96": {
      "abstract": [
        {
          "text": "SHA-1 96-bit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA96"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA96"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA96",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha96"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup": {
      "abstract": [
        {
          "text": "The Diffie Hellman group used by the Security Association.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diffieHellmanGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2DiffieHellmanGroup",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diffieHellmanGroup"
        }
      ],
      "role": "symbol",
      "title": "diffieHellmanGroup",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/diffiehellmangroup"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm": {
      "abstract": [
        {
          "text": "The algorithm used by the Security Association to encrypt and decrypt data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2EncryptionAlgorithm",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "encryptionAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/encryptionalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm": {
      "abstract": [
        {
          "text": "The algorithm used by the Security Association to verify the integrity of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integrityAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2IntegrityAlgorithm",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "integrityAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "integrityAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/integrityalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes": {
      "abstract": [
        {
          "text": "The duration of the lifetime of the Security Association, in minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetimeMinutes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetimeMinutes"
        }
      ],
      "role": "symbol",
      "title": "lifetimeMinutes",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/lifetimeminutes"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IKEv2-Security-Association-parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes"
      ],
      "title": "IKEv2 Security Association parameters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Integrity-algorithms",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512"
      ],
      "title": "Integrity algorithms"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2IntegrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Integrity-algorithms",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512"
              ],
              "title": "Integrity algorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IKEv2-Security-Association-parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes"
              ],
              "title": "IKEv2 Security Association parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2IntegrityAlgorithm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1encryptionAlgorithm/title",
          "value": "encryptionAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1encryptionAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1integrityAlgorithm/title",
          "value": "integrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1integrityAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "integrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA512/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA384/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1lifetimeMinutes/title",
          "value": "lifetimeMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1lifetimeMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetimeMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA96/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/title",
          "value": "NEVPNIKEv2IntegrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1diffieHellmanGroup/title",
          "value": "diffieHellmanGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1diffieHellmanGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA256/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA160/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/title",
          "value": "NEVPNIKEv2EncryptionAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2integrityalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2integrityalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
