{
  "abstract": [
    {
      "text": "Information about an error encountered while configuring or using a VPN.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC10NEVPNErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNError"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NEVPNError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct": {
      "abstract": [
        {
          "text": "Information about an error encountered while configuring or using a VPN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that indicate the source of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN configuration associated with the VPN manager isn’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN configuration associated with the VPN manager object is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed": {
      "abstract": [
        {
          "text": "An error code that indicates an error occurred while reading or writing the Network Extension preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationReadWriteFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationReadWriteFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationreadwritefailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale": {
      "abstract": [
        {
          "text": "An error code that indicates another process modfied the VPN configuration since the last time the app loaded the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationStale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationStale",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationstale"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown": {
      "abstract": [
        {
          "text": "An error code that indicates that unspecified error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUnknown",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationunknown"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the connection to the VPN server failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/connectionfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/errordomain"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Inspecting-error-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code"
      ],
      "title": "Inspecting error properties"
    },
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/title",
          "value": "NEVPNError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
