{
  "abstract": [
    {
      "text": "An enumeration of values for the frequency at which the IKEv2 client runs the dead peer detection algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2DeadPeerDetectionRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2DeadPeerDetectionRate"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2DeadPeerDetectionRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEVPNIKEv2DeadPeerDetectionRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate": {
      "abstract": [
        {
          "text": "An enumeration of values for the frequency at which the IKEv2 client runs the dead peer detection algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/high": {
      "abstract": [
        {
          "text": "Run dead peer detection once every 1 minute. If the peer does not respond, retry 5 times at 1 second intervals before declaring the peer dead and terminating the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRateHigh"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate.high",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate/high"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/low": {
      "abstract": [
        {
          "text": "Run dead peer detection once every 30 minutes. If the peer does not respond, retry 5 times at 1 second intervals before declaring the peer dead and terminating the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRateLow"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate.low",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate/low"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/medium": {
      "abstract": [
        {
          "text": "Run dead peer detection once every 10 minutes. If the peer does not respond, retry 5 times at 1 second intervals before declaring the peer dead and terminating the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRateMedium"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate.medium",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate/medium"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/none": {
      "abstract": [
        {
          "text": "Do not perform dead peer detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRateNone"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate.none",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate/none"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate": {
      "abstract": [
        {
          "text": "The frequency at which the IKEv2 client will run the dead peer detection algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deadPeerDetectionRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2DeadPeerDetectionRate",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deadPeerDetectionRate"
        }
      ],
      "role": "symbol",
      "title": "deadPeerDetectionRate",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/deadpeerdetectionrate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not MOBIKE should be disabled for the IKEv2 sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableMOBIKE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableMOBIKE"
        }
      ],
      "role": "symbol",
      "title": "disableMOBIKE",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/disablemobike"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not IKEv2 server redirects are disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableRedirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableRedirect"
        }
      ],
      "role": "symbol",
      "title": "disableRedirect",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/disableredirect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not Perfect Forward Secrecy is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enablePFS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enablePFS"
        }
      ],
      "role": "symbol",
      "title": "enablePFS",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/enablepfs"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck": {
      "abstract": [
        {
          "text": "Enable revocation checking of the IKEv2 server certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableRevocationCheck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableRevocationCheck"
        }
      ],
      "role": "symbol",
      "title": "enableRevocationCheck",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/enablerevocationcheck"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu": {
      "abstract": [
        {
          "text": "The Maximum Transmission Unit (MTU) size in bytes to assign to the tunnel interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mtu"
        }
      ],
      "role": "symbol",
      "title": "mtu",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/mtu"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck": {
      "abstract": [
        {
          "text": "Require a “not revoked” result when checking if the certificate identifying the server is revoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strictRevocationCheck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strictRevocationCheck"
        }
      ],
      "role": "symbol",
      "title": "strictRevocationCheck",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/strictrevocationcheck"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not the IKEv2 client should use the INTERNAL_IP4_SUBNET and/or INTERNAL_IP6_SUBNET attributes sent by the IKEv2 server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useConfigurationAttributeInternalIPSubnet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useConfigurationAttributeInternalIPSubnet"
        }
      ],
      "role": "symbol",
      "title": "useConfigurationAttributeInternalIPSubnet",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/useconfigurationattributeinternalipsubnet"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-other-IKEv2-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu"
      ],
      "title": "Accessing other IKEv2 properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Detection-rates",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/none",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/low",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/medium",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/high"
      ],
      "title": "Detection rates"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Detection-rates",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/none",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/low",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/medium",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate/high"
              ],
              "title": "Detection rates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-other-IKEv2-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu"
              ],
              "title": "Accessing other IKEv2 properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2DeadPeerDetectionRate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enablePFS/title",
          "value": "enablePFS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enablePFS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enablePFS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1high/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRateHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRateHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1low/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRateLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRateLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1useConfigurationAttributeInternalIPSubnet/title",
          "value": "useConfigurationAttributeInternalIPSubnet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1useConfigurationAttributeInternalIPSubnet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "useConfigurationAttributeInternalIPSubnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableMOBIKE/title",
          "value": "disableMOBIKE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableMOBIKE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableMOBIKE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1medium/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRateMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRateMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1mtu/title",
          "value": "mtu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1mtu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mtu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableRevocationCheck/title",
          "value": "enableRevocationCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableRevocationCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableRevocationCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1deadPeerDetectionRate/title",
          "value": "deadPeerDetectionRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1deadPeerDetectionRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1strictRevocationCheck/title",
          "value": "strictRevocationCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1strictRevocationCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strictRevocationCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableRedirect/title",
          "value": "disableRedirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableRedirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableRedirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1none/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRateNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2deadpeerdetectionrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2deadpeerdetectionrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
