{
  "abstract": [
    {
      "text": "An enumeration of Diffie-Hellman group values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2DiffieHellmanGroup",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2DiffieHellmanGroup"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2DiffieHellmanGroup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEVPNIKEv2DiffieHellmanGroup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup": {
      "abstract": [
        {
          "text": "An enumeration of Diffie-Hellman group values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group1": {
      "abstract": [
        {
          "text": "Diffie Hellman group 1 (768-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group1"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup1"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group1",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group1"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group14": {
      "abstract": [
        {
          "text": "Diffie Hellman group 14 (2048-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group14"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup14"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group14",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group14"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group15": {
      "abstract": [
        {
          "text": "Diffie Hellman group 15 (3072-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group15"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup15"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group15",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group15"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group16": {
      "abstract": [
        {
          "text": "Diffie Hellman group 16 (4096-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group16"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup16"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group16",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group16"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group17": {
      "abstract": [
        {
          "text": "Diffie Hellman group 17 (6144-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group17"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group17",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup17"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group17",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group17"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group18": {
      "abstract": [
        {
          "text": "Diffie Hellman group 18 (8192-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group18"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group18",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup18"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group18",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group18"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group19": {
      "abstract": [
        {
          "text": "Diffie Hellman group 19 (256-bit random elliptic curve group over GF[P] [ECP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group19"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group19",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup19"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group19",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group19"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group2": {
      "abstract": [
        {
          "text": "Diffie Hellman group 2 (1024-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group2"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup2"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group2",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group2"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group20": {
      "abstract": [
        {
          "text": "Diffie Hellman group 20 (384-bit random elliptic curve group over GF[P] [ECP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group20"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group20",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup20"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group20",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group20"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group21": {
      "abstract": [
        {
          "text": "Diffie Hellman group 21 (521-bit random elliptic curve group over GF[P] [ECP]).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group21"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group21",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup21"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group21",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group21"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group31": {
      "abstract": [
        {
          "text": "Diffie Hellman group 31 (Curve 25519).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group31"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group31",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup31"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group31",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group31"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group32": {
      "abstract": [
        {
          "text": "Diffie Hellman group 32 (Curve 448).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group32"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup32"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group32",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group32"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group5": {
      "abstract": [
        {
          "text": "Diffie Hellman group 5 (1536-bit modular exponential [MODP]).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group5"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroup5"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.group5",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/group5"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/groupInvalid": {
      "abstract": [
        {
          "text": "A value indicating the group is not a valid Diffie-Hellman group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/groupInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DiffieHellmanGroupInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DiffieHellmanGroup.groupInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/groupinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2diffiehellmangroup/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm": {
      "abstract": [
        {
          "text": "An enumeration of encryption algorithm values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup": {
      "abstract": [
        {
          "text": "The Diffie Hellman group used by the Security Association.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diffieHellmanGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2DiffieHellmanGroup",
          "text": "NEVPNIKEv2DiffieHellmanGroup"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diffieHellmanGroup"
        }
      ],
      "role": "symbol",
      "title": "diffieHellmanGroup",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/diffiehellmangroup"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm": {
      "abstract": [
        {
          "text": "The algorithm used by the Security Association to encrypt and decrypt data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2EncryptionAlgorithm",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "encryptionAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/encryptionalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm": {
      "abstract": [
        {
          "text": "The algorithm used by the Security Association to verify the integrity of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integrityAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2IntegrityAlgorithm",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "integrityAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "integrityAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/integrityalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes": {
      "abstract": [
        {
          "text": "The duration of the lifetime of the Security Association, in minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetimeMinutes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetimeMinutes"
        }
      ],
      "role": "symbol",
      "title": "lifetimeMinutes",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters/lifetimeminutes"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IKEv2-Security-Association-parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes"
      ],
      "title": "IKEv2 Security Association parameters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Diffie-Hellman-groups",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/groupInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group1",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group2",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group5",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group14",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group15",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group16",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group17",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group18",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group19",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group20",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group21",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group31",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group32"
      ],
      "title": "Diffie-Hellman groups"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Diffie-Hellman-groups",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/groupInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group1",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group2",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group5",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group14",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group15",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group16",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group17",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group18",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group19",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group20",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group21",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group31",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DiffieHellmanGroup/group32"
              ],
              "title": "Diffie-Hellman groups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IKEv2-Security-Association-parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/encryptionAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/integrityAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/diffieHellmanGroup",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters/lifetimeMinutes"
              ],
              "title": "IKEv2 Security Association parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2DiffieHellmanGroup"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/title",
          "value": "NEVPNIKEv2IntegrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group2/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group19/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup19"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group19/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup19"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1encryptionAlgorithm/title",
          "value": "encryptionAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1encryptionAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group20/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup20"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group20/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup20"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group32/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group1/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1diffieHellmanGroup/title",
          "value": "diffieHellmanGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1diffieHellmanGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diffieHellmanGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group15/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup15"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group15/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup15"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1groupInvalid/title",
          "value": "NEVPNIKEv2DiffieHellmanGroupInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1groupInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroupInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group14/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1lifetimeMinutes/title",
          "value": "lifetimeMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1lifetimeMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetimeMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1integrityAlgorithm/title",
          "value": "integrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters~1integrityAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "integrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group31/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup31"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group31/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup31"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group21/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup21"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group21/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup21"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group17/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup17"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group17/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup17"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group5/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group18/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup18"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group18/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup18"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/title",
          "value": "NEVPNIKEv2EncryptionAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group16/title",
          "value": "NEVPNIKEv2DiffieHellmanGroup16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DiffieHellmanGroup~1group16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DiffieHellmanGroup16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2diffiehellmangroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2diffiehellmangroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
