{
  "abstract": [
    {
      "text": "Error codes specific to VPN connections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNConnectionError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNConnectionError"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNConnectionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NEVPNConnectionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnection/fetchLastDisconnectError(completionHandler:)": {
      "abstract": [
        {
          "text": "Retrives the most recent error that caused the VPN to disconnect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchLastDisconnectError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnection/fetchLastDisconnectError(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchLastDisconnectErrorWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "fetchLastDisconnectError(completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnection/fetchlastdisconnecterror(completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError": {
      "abstract": [
        {
          "text": "Error codes specific to VPN connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNConnectionError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionError"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the VPN server rejected the user credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.authenticationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/authenticationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateExpired": {
      "abstract": [
        {
          "text": "An error code that indicates the client certfiicate’s validity period has passed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientCertificateExpired"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorClientCertificateExpired"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.clientCertificateExpired",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/clientcertificateexpired"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the client certfiicate is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientCertificateInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorClientCertificateInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.clientCertificateInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/clientcertificateinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateNotYetValid": {
      "abstract": [
        {
          "text": "An error code that indicates the client certfiicate won’t be valid until some time in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientCertificateNotYetValid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateNotYetValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorClientCertificateNotYetValid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.clientCertificateNotYetValid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/clientcertificatenotyetvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorConfigurationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.configurationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/configurationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the system couldn’t find a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationNotFound"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorConfigurationNotFound"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.configurationNotFound",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/configurationnotfound"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/init(rawvalue:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the negotiation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negotiationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorNegotiationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.negotiationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/negotiationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the system isn’t connected to a network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noNetworkAvailable"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorNoNetworkAvailable"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.noNetworkAvailable",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/nonetworkavailable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept": {
      "abstract": [
        {
          "text": "An error code that indicates the system slept for an extended period of time, causing the VPN connection to terminate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overslept"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorOverslept"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.overslept",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/overslept"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginDisabled": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN plugin isn’t available or needs an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pluginDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorPluginDisabled"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.pluginDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/plugindisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN plugin failed unexpectedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pluginFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorPluginFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.pluginFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/pluginfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverAddressResolutionFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the system couldn’t determine the VPN server address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverAddressResolutionFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverAddressResolutionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerAddressResolutionFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverAddressResolutionFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/serveraddressresolutionfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateExpired": {
      "abstract": [
        {
          "text": "An error code that indicates the server certfiicate’s validity period has passed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverCertificateExpired"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerCertificateExpired"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverCertificateExpired",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/servercertificateexpired"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the server certfiicate is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverCertificateInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerCertificateInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverCertificateInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/servercertificateinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateNotYetValid": {
      "abstract": [
        {
          "text": "An error code that indicates the server certfiicate won’t be valid until some time in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverCertificateNotYetValid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateNotYetValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerCertificateNotYetValid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverCertificateNotYetValid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/servercertificatenotyetvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDead": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the VPN server has stopped responding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverDead"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerDead"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverDead",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/serverdead"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDisconnected": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the VPN server terminated the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverDisconnected"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerDisconnected"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverDisconnected",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/serverdisconnected"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverNotResponding": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the VPN server isn’t responding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverNotResponding"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverNotResponding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorServerNotResponding"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.serverNotResponding",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/servernotresponding"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange": {
      "abstract": [
        {
          "text": "An error code that indicates network conditions changed such that the VPN connection needed to terminate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecoverableNetworkChange"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.unrecoverableNetworkChange",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/unrecoverablenetworkchange"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors resulting from VPN connection calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionErrorDomain",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnection/fetchLastDisconnectError(completionHandler:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionErrorDomain"
      ],
      "title": "Handling errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "General-error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed"
      ],
      "title": "General error codes"
    },
    {
      "anchor": "VPN-server-error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverAddressResolutionFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverNotResponding",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDead",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDisconnected"
      ],
      "title": "VPN server error codes"
    },
    {
      "anchor": "Plugin-error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginDisabled"
      ],
      "title": "Plugin error codes"
    },
    {
      "anchor": "Client-certificate-error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateNotYetValid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateExpired"
      ],
      "title": "Client certificate error codes"
    },
    {
      "anchor": "Server-certificate-error-codes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateNotYetValid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateExpired"
      ],
      "title": "Server certificate error codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNConnectionError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "General-error-codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed"
              ],
              "title": "General error codes"
            },
            {
              "anchor": "VPN-server-error-codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverAddressResolutionFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverNotResponding",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDead",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverDisconnected"
              ],
              "title": "VPN server error codes"
            },
            {
              "anchor": "Plugin-error-codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/pluginDisabled"
              ],
              "title": "Plugin error codes"
            },
            {
              "anchor": "Client-certificate-error-codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateNotYetValid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/clientCertificateExpired"
              ],
              "title": "Client certificate error codes"
            },
            {
              "anchor": "Server-certificate-error-codes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateNotYetValid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/serverCertificateExpired"
              ],
              "title": "Server certificate error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnection/fetchLastDisconnectError(completionHandler:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionErrorDomain"
              ],
              "title": "Handling errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEVPNConnectionError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateInvalid/title",
          "value": "NEVPNConnectionErrorClientCertificateInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorClientCertificateInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationFailed/title",
          "value": "NEVPNConnectionErrorConfigurationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorConfigurationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateExpired/title",
          "value": "NEVPNConnectionErrorServerCertificateExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerCertificateExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1pluginDisabled/title",
          "value": "NEVPNConnectionErrorPluginDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1pluginDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorPluginDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverNotResponding/title",
          "value": "NEVPNConnectionErrorServerNotResponding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverNotResponding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerNotResponding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationNotFound/title",
          "value": "NEVPNConnectionErrorConfigurationNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorConfigurationNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1noNetworkAvailable/title",
          "value": "NEVPNConnectionErrorNoNetworkAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1noNetworkAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorNoNetworkAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1pluginFailed/title",
          "value": "NEVPNConnectionErrorPluginFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1pluginFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorPluginFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateNotYetValid/title",
          "value": "NEVPNConnectionErrorServerCertificateNotYetValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateNotYetValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerCertificateNotYetValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1authenticationFailed/title",
          "value": "NEVPNConnectionErrorAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1authenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/title",
          "value": "NEVPNConnectionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateInvalid/title",
          "value": "NEVPNConnectionErrorServerCertificateInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverCertificateInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerCertificateInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1negotiationFailed/title",
          "value": "NEVPNConnectionErrorNegotiationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1negotiationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorNegotiationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateExpired/title",
          "value": "NEVPNConnectionErrorClientCertificateExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorClientCertificateExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverDisconnected/title",
          "value": "NEVPNConnectionErrorServerDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverAddressResolutionFailed/title",
          "value": "NEVPNConnectionErrorServerAddressResolutionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverAddressResolutionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerAddressResolutionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverDead/title",
          "value": "NEVPNConnectionErrorServerDead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1serverDead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorServerDead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateNotYetValid/title",
          "value": "NEVPNConnectionErrorClientCertificateNotYetValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1clientCertificateNotYetValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorClientCertificateNotYetValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1unrecoverableNetworkChange/title",
          "value": "NEVPNConnectionErrorUnrecoverableNetworkChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1unrecoverableNetworkChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1overslept/title",
          "value": "NEVPNConnectionErrorOverslept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1overslept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorOverslept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnection~1fetchLastDisconnectError(completionHandler:)/title",
          "value": "fetchLastDisconnectErrorWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnection~1fetchLastDisconnectError(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fetchLastDisconnectErrorWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionErrorDomain/title",
          "value": "NEVPNConnectionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnconnectionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnconnectionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
