{
  "abstract": [
    {
      "text": "Settings for an IKEv2 VPN configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEVPNProtocolIKEv2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NEVPNProtocolIKEv2"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNProtocolIKEv2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NEVPNProtocolIKEv2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIKEv2"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instances of this class are thread safe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType": {
      "abstract": [
        {
          "text": "An enumeration of certificate type values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateType"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate": {
      "abstract": [
        {
          "text": "An enumeration of values for the frequency at which the IKEv2 client runs the dead peer detection algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2DeadPeerDetectionRate",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2deadpeerdetectionrate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters": {
      "abstract": [
        {
          "text": "Parameters for an IKEv2 Security Association.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2SecurityAssociationParameters"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2SecurityAssociationParameters"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2SecurityAssociationParameters",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2securityassociationparameters"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2TLSVersion": {
      "abstract": [
        {
          "text": "An enumeration of TLS Versions for use in EAP-TLS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2TLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2TLSVersion"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2TLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2tlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNManager": {
      "abstract": [
        {
          "text": "An object to create and manage a Personal VPN configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNManager"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNManager"
        }
      ],
      "role": "symbol",
      "title": "NEVPNManager",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnmanager"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocol": {
      "abstract": [
        {
          "text": "Settings common to both IKEv2 and IPsec VPN configurations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNProtocol"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNProtocol"
        }
      ],
      "role": "symbol",
      "title": "NEVPNProtocol",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocol"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2": {
      "abstract": [
        {
          "text": "Settings for an IKEv2 VPN configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNProtocolIKEv2"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNProtocolIKEv2"
        }
      ],
      "role": "symbol",
      "title": "NEVPNProtocolIKEv2",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/certificateType": {
      "abstract": [
        {
          "text": "The type of the certificate in the identity configured in ",
          "type": "text"
        },
        {
          "code": "identityReference",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "identityData",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificateType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2CertificateType",
          "text": "NEVPNIKEv2CertificateType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/certificateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "certificateType"
        }
      ],
      "role": "symbol",
      "title": "certificateType",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/certificatetype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/childSecurityAssociationParameters": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the parameters for the child IPSec security associations to be negotiated for each IKEv2 policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childSecurityAssociationParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEVPNIKEv2SecurityAssociationParameters",
          "text": "NEVPNIKEv2SecurityAssociationParameters"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/childSecurityAssociationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "childSecurityAssociationParameters"
        }
      ],
      "role": "symbol",
      "title": "childSecurityAssociationParameters",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/childsecurityassociationparameters"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate": {
      "abstract": [
        {
          "text": "The frequency at which the IKEv2 client will run the dead peer detection algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deadPeerDetectionRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2DeadPeerDetectionRate",
          "text": "NEVPNIKEv2DeadPeerDetectionRate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deadPeerDetectionRate"
        }
      ],
      "role": "symbol",
      "title": "deadPeerDetectionRate",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/deadpeerdetectionrate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not MOBIKE should be disabled for the IKEv2 sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableMOBIKE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableMOBIKE"
        }
      ],
      "role": "symbol",
      "title": "disableMOBIKE",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/disablemobike"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not IKEv2 server redirects are disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableRedirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableRedirect"
        }
      ],
      "role": "symbol",
      "title": "disableRedirect",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/disableredirect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableFallback": {
      "abstract": [
        {
          "text": "A property to enable the use of cellular data when Wi-Fi connectivity is poor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableFallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableFallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableFallback"
        }
      ],
      "role": "symbol",
      "title": "enableFallback",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/enablefallback"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not Perfect Forward Secrecy is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enablePFS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enablePFS"
        }
      ],
      "role": "symbol",
      "title": "enablePFS",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/enablepfs"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck": {
      "abstract": [
        {
          "text": "Enable revocation checking of the IKEv2 server certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableRevocationCheck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableRevocationCheck"
        }
      ],
      "role": "symbol",
      "title": "enableRevocationCheck",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/enablerevocationcheck"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ikeSecurityAssociationParameters": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the parameters for the initial IKE security association to be negotiated with the IKEv2 server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ikeSecurityAssociationParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEVPNIKEv2SecurityAssociationParameters",
          "text": "NEVPNIKEv2SecurityAssociationParameters"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ikeSecurityAssociationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKESecurityAssociationParameters"
        }
      ],
      "role": "symbol",
      "title": "ikeSecurityAssociationParameters",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/ikesecurityassociationparameters"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/maximumTLSVersion": {
      "abstract": [
        {
          "text": "The minimum TLS version to allow for EAP-TLS authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumTLSVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2TLSVersion",
          "text": "NEVPNIKEv2TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/maximumTLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumTLSVersion"
        }
      ],
      "role": "symbol",
      "title": "maximumTLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/maximumtlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/minimumTLSVersion": {
      "abstract": [
        {
          "text": "The minimum TLS version to allow for EAP-TLS authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumTLSVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNIKEv2TLSVersion",
          "text": "NEVPNIKEv2TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/minimumTLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumTLSVersion"
        }
      ],
      "role": "symbol",
      "title": "minimumTLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/minimumtlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu": {
      "abstract": [
        {
          "text": "The Maximum Transmission Unit (MTU) size in bytes to assign to the tunnel interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mtu"
        }
      ],
      "role": "symbol",
      "title": "mtu",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/mtu"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ppkConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ppkConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEVPNIKEv2PPKConfiguration",
          "text": "NEVPNIKEv2PPKConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ppkConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ppkConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ppkConfiguration",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/ppkconfiguration"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateCommonName": {
      "abstract": [
        {
          "text": "A string containing the value of the Subject Common Name field of the IKEv2 server’s certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverCertificateCommonName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateCommonName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverCertificateCommonName"
        }
      ],
      "role": "symbol",
      "title": "serverCertificateCommonName",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/servercertificatecommonname"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateIssuerCommonName": {
      "abstract": [
        {
          "text": "A string containing the value of the Subject Common Name field of the Certificate Authority certificate that issued the IKEv2 server’s certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverCertificateIssuerCommonName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateIssuerCommonName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverCertificateIssuerCommonName"
        }
      ],
      "role": "symbol",
      "title": "serverCertificateIssuerCommonName",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/servercertificateissuercommonname"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck": {
      "abstract": [
        {
          "text": "Require a “not revoked” result when checking if the certificate identifying the server is revoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strictRevocationCheck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strictRevocationCheck"
        }
      ],
      "role": "symbol",
      "title": "strictRevocationCheck",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/strictrevocationcheck"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet": {
      "abstract": [
        {
          "text": "A Boolean indicating whether or not the IKEv2 client should use the INTERNAL_IP4_SUBNET and/or INTERNAL_IP6_SUBNET attributes sent by the IKEv2 server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useConfigurationAttributeInternalIPSubnet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useConfigurationAttributeInternalIPSubnet"
        }
      ],
      "role": "symbol",
      "title": "useConfigurationAttributeInternalIPSubnet",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolikev2/useconfigurationattributeinternalipsubnet"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec": {
      "abstract": [
        {
          "text": "Settings for an IPsec VPN configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNProtocolIPSec"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNProtocolIPSec"
        }
      ],
      "role": "symbol",
      "title": "NEVPNProtocolIPSec",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnprotocolipsec"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/vpn-on-demand-rules": {
      "abstract": [
        {
          "text": "Set up VPN On Demand.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/vpn-on-demand-rules",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VPN On Demand Rules",
      "type": "topic",
      "url": "/documentation/networkextension/vpn-on-demand-rules"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "VPN-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNManager",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocol",
        "doc://com.apple.networkextension/documentation/NetworkExtension/vpn-on-demand-rules"
      ],
      "title": "VPN configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-IKEv2-Security-Association-parameters",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ikeSecurityAssociationParameters",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/childSecurityAssociationParameters",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters"
      ],
      "title": "Accessing IKEv2 Security Association parameters"
    },
    {
      "anchor": "Accessing-certificate-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateIssuerCommonName",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateCommonName",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/certificateType",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType"
      ],
      "title": "Accessing certificate properties"
    },
    {
      "anchor": "Accessing-TLS-version-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/minimumTLSVersion",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/maximumTLSVersion",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2TLSVersion"
      ],
      "title": "Accessing TLS version properties"
    },
    {
      "anchor": "Accessing-other-IKEv2-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu"
      ],
      "title": "Accessing other IKEv2 properties"
    },
    {
      "anchor": "Supporting-Wi-Fi-assist",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableFallback"
      ],
      "title": "Supporting Wi-Fi assist"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ppkConfiguration"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNProtocolIKEv2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIKEv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIKEv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-IKEv2-Security-Association-parameters",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ikeSecurityAssociationParameters",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/childSecurityAssociationParameters",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2SecurityAssociationParameters"
              ],
              "title": "Accessing IKEv2 Security Association parameters"
            },
            {
              "anchor": "Accessing-certificate-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateIssuerCommonName",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/serverCertificateCommonName",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/certificateType",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType"
              ],
              "title": "Accessing certificate properties"
            },
            {
              "anchor": "Accessing-TLS-version-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/minimumTLSVersion",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/maximumTLSVersion",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2TLSVersion"
              ],
              "title": "Accessing TLS version properties"
            },
            {
              "anchor": "Accessing-other-IKEv2-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/deadPeerDetectionRate",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2DeadPeerDetectionRate",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/useConfigurationAttributeInternalIPSubnet",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableMOBIKE",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/disableRedirect",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enablePFS",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableRevocationCheck",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/strictRevocationCheck",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/mtu"
              ],
              "title": "Accessing other IKEv2 properties"
            },
            {
              "anchor": "Supporting-Wi-Fi-assist",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/enableFallback"
              ],
              "title": "Supporting Wi-Fi assist"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIKEv2/ppkConfiguration"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "VPN-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNManager",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocol",
                "doc://com.apple.networkextension/documentation/NetworkExtension/vpn-on-demand-rules"
              ],
              "title": "VPN configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NEVPNProtocolIKEv2"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNProtocolIPSec",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NEVPNProtocolIPSec",
                    "text": "NEVPNProtocolIPSec"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1certificateType/title",
          "value": "certificateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1certificateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "certificateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableRedirect/title",
          "value": "disableRedirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableRedirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableRedirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enablePFS/title",
          "value": "enablePFS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enablePFS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enablePFS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1ppkConfiguration/title",
          "value": "ppkConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1ppkConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ppkConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1serverCertificateCommonName/title",
          "value": "serverCertificateCommonName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1serverCertificateCommonName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverCertificateCommonName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/title",
          "value": "NEVPNIKEv2CertificateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocol/title",
          "value": "NEVPNProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1ikeSecurityAssociationParameters/title",
          "value": "IKESecurityAssociationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1ikeSecurityAssociationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKESecurityAssociationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableRevocationCheck/title",
          "value": "enableRevocationCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableRevocationCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableRevocationCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableMOBIKE/title",
          "value": "disableMOBIKE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1disableMOBIKE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableMOBIKE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIPSec/title",
          "value": "NEVPNProtocolIPSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIPSec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIPSec/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1strictRevocationCheck/title",
          "value": "strictRevocationCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1strictRevocationCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strictRevocationCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNManager/title",
          "value": "NEVPNManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1childSecurityAssociationParameters/title",
          "value": "childSecurityAssociationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1childSecurityAssociationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "childSecurityAssociationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1deadPeerDetectionRate/title",
          "value": "deadPeerDetectionRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1deadPeerDetectionRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1minimumTLSVersion/title",
          "value": "minimumTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1minimumTLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableFallback/title",
          "value": "enableFallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1enableFallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableFallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2TLSVersion/title",
          "value": "NEVPNIKEv2TLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2TLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2TLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2TLSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2TLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1maximumTLSVersion/title",
          "value": "maximumTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1maximumTLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1useConfigurationAttributeInternalIPSubnet/title",
          "value": "useConfigurationAttributeInternalIPSubnet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1useConfigurationAttributeInternalIPSubnet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "useConfigurationAttributeInternalIPSubnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2/title",
          "value": "NEVPNProtocolIKEv2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIKEv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNProtocolIKEv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1mtu/title",
          "value": "mtu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1mtu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mtu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters/title",
          "value": "NEVPNIKEv2SecurityAssociationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2SecurityAssociationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2SecurityAssociationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2SecurityAssociationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1serverCertificateIssuerCommonName/title",
          "value": "serverCertificateIssuerCommonName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNProtocolIKEv2~1serverCertificateIssuerCommonName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverCertificateIssuerCommonName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/title",
          "value": "NEVPNIKEv2DeadPeerDetectionRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2DeadPeerDetectionRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2DeadPeerDetectionRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnprotocolikev2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnprotocolikev2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
