{
  "abstract": [
    {
      "text": "An object to manage a TCP connection, with or without TLS.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "type from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " framework instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NWTCPConnection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NWTCPConnection"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NWTCPConnection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.11",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "17.0",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use `nw_connection_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NWTCPConnection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NWTCPConnection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/Network"
    },
    "doc://com.apple.documentation/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_nw_connection",
          "text": "OS_nw_connection"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/Network/nw_connection_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection": {
      "abstract": [
        {
          "text": "An object to manage a TCP connection, with or without TLS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWTCPConnection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWTCPConnection"
        }
      ],
      "role": "symbol",
      "title": "NWTCPConnection",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/cancel()": {
      "abstract": [
        {
          "text": "Cancel the connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/cancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/cancel()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/connectedPath": {
      "abstract": [
        {
          "text": "The network path over which the connection was established.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectedPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWPath",
          "text": "NWPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/connectedPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connectedPath"
        }
      ],
      "role": "symbol",
      "title": "connectedPath",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/connectedpath"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/endpoint": {
      "abstract": [
        {
          "text": "The destination endpoint with which this connection was created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/endpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endpoint"
        }
      ],
      "role": "symbol",
      "title": "endpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/endpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/error": {
      "abstract": [
        {
          "text": "The connection-wide error property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/error"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/hasBetterPath": {
      "abstract": [
        {
          "text": "If a connection has a better path, new connections would use a different interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasBetterPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/hasBetterPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasBetterPath"
        }
      ],
      "role": "symbol",
      "title": "hasBetterPath",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/hasbetterpath"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/init(upgradeFor:)": {
      "abstract": [
        {
          "text": "This convenience initializer can be used to create a new connection that will only be connected if there exists a better path (as determined by the system) to the remote endpoint of the original connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "upgradeFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWTCPConnection",
          "text": "NWTCPConnection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/init(upgradeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUpgradeForConnection:"
        }
      ],
      "role": "symbol",
      "title": "init(upgradeFor:)",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/init(upgradefor:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/isViable": {
      "abstract": [
        {
          "text": "The viability of a TCP connection indicates whether or not data can be transferred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isViable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/isViable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viable"
        }
      ],
      "role": "symbol",
      "title": "isViable",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/isviable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/localAddress": {
      "abstract": [
        {
          "text": "The IP address endpoint from which the connection was established.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/localAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localAddress"
        }
      ],
      "role": "symbol",
      "title": "localAddress",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/localaddress"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readLength(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Read a certain number of bytes on a connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readLength(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readLength:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readLength(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/readlength(_:completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readMinimumLength(_:maximumLength:completionHandler:)": {
      "abstract": [
        {
          "text": "Read the requested range of bytes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readMinimumLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maximumLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readMinimumLength(_:maximumLength:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readMinimumLength:maximumLength:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readMinimumLength(_:maximumLength:completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/readminimumlength(_:maximumlength:completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/remoteAddress": {
      "abstract": [
        {
          "text": "The IP address endpoint to which the connection was established.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/remoteAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remoteAddress"
        }
      ],
      "role": "symbol",
      "title": "remoteAddress",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/remoteaddress"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/state": {
      "abstract": [
        {
          "text": "The status of the connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NWTCPConnectionState",
          "text": "NWTCPConnectionState"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/state"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/txtRecord": {
      "abstract": [
        {
          "text": "The TXT record associated with a connected Bonjour service endpoint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "txtRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/txtRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "txtRecord"
        }
      ],
      "role": "symbol",
      "title": "txtRecord",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/txtrecord"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/write(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Write the data to the connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/write(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "write:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "write(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/write(_:completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/writeClose()": {
      "abstract": [
        {
          "text": "Close the connection for writing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeClose"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/writeClose()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeClose"
        }
      ],
      "role": "symbol",
      "title": "writeClose()",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnection/writeclose()"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionAuthenticationDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol to customize the TLS authentication done by a connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWTCPConnectionAuthenticationDelegate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionAuthenticationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWTCPConnectionAuthenticationDelegate"
        }
      ],
      "role": "symbol",
      "title": "NWTCPConnectionAuthenticationDelegate",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnectionauthenticationdelegate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionState": {
      "abstract": [
        {
          "text": "Defined connection states. New types may be defined in the future.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWTCPConnectionState"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWTCPConnectionState"
        }
      ],
      "role": "symbol",
      "title": "NWTCPConnectionState",
      "type": "topic",
      "url": "/documentation/networkextension/nwtcpconnectionstate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWTLSParameters": {
      "abstract": [
        {
          "text": "TLS properties for creating a connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWTLSParameters"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWTLSParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWTLSParameters"
        }
      ],
      "role": "symbol",
      "title": "NWTLSParameters",
      "type": "topic",
      "url": "/documentation/networkextension/nwtlsparameters"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "TCP-connections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTLSParameters",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionAuthenticationDelegate"
      ],
      "title": "TCP connections"
    }
  ],
  "topicSections": [
    {
      "anchor": "Monitoring-the-connection-status",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/state",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionState",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/isViable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/error"
      ],
      "title": "Monitoring the connection status"
    },
    {
      "anchor": "Transferring-data",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readMinimumLength(_:maximumLength:completionHandler:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readLength(_:completionHandler:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/write(_:completionHandler:)",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/writeClose()"
      ],
      "title": "Transferring data"
    },
    {
      "anchor": "Canceling-the-connection",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/cancel()"
      ],
      "title": "Canceling the connection"
    },
    {
      "anchor": "Responding-to-network-changes",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/hasBetterPath",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/init(upgradeFor:)"
      ],
      "title": "Responding to network changes"
    },
    {
      "anchor": "Getting-connection-properties",
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/endpoint",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/localAddress",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/remoteAddress",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/connectedPath",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/txtRecord"
      ],
      "title": "Getting connection properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NWTCPConnection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Monitoring-the-connection-status",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/state",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionState",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/isViable",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/error"
              ],
              "title": "Monitoring the connection status"
            },
            {
              "anchor": "Transferring-data",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readMinimumLength(_:maximumLength:completionHandler:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/readLength(_:completionHandler:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/write(_:completionHandler:)",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/writeClose()"
              ],
              "title": "Transferring data"
            },
            {
              "anchor": "Canceling-the-connection",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/cancel()"
              ],
              "title": "Canceling the connection"
            },
            {
              "anchor": "Responding-to-network-changes",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/hasBetterPath",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/init(upgradeFor:)"
              ],
              "title": "Responding to network changes"
            },
            {
              "anchor": "Getting-connection-properties",
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/endpoint",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/localAddress",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/remoteAddress",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/connectedPath",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnection/txtRecord"
              ],
              "title": "Getting connection properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "TCP-connections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTLSParameters",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWTCPConnectionAuthenticationDelegate"
              ],
              "title": "TCP connections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NWTCPConnection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "type from the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionState/title",
          "value": "NWTCPConnectionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1init(upgradeFor:)/title",
          "value": "initWithUpgradeForConnection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1init(upgradeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUpgradeForConnection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1write(_:completionHandler:)/title",
          "value": "write:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1write(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "write:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1readLength(_:completionHandler:)/title",
          "value": "readLength:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1readLength(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readLength:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1localAddress/title",
          "value": "localAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1localAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1writeClose()/title",
          "value": "writeClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1writeClose()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1readMinimumLength(_:maximumLength:completionHandler:)/title",
          "value": "readMinimumLength:maximumLength:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1readMinimumLength(_:maximumLength:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readMinimumLength:maximumLength:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection/title",
          "value": "NWTCPConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1cancel()/title",
          "value": "cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1cancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1isViable/title",
          "value": "viable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1isViable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "viable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1remoteAddress/title",
          "value": "remoteAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1remoteAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTLSParameters/title",
          "value": "NWTLSParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTLSParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTLSParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTLSParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTLSParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionAuthenticationDelegate/title",
          "value": "NWTCPConnectionAuthenticationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionAuthenticationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnectionAuthenticationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnectionAuthenticationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWTCPConnectionAuthenticationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1error/title",
          "value": "error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1endpoint/title",
          "value": "endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1endpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_connection",
              "text": "NSObject<OS_nw_connection>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1txtRecord/title",
          "value": "txtRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1txtRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "txtRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1hasBetterPath/title",
          "value": "hasBetterPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1hasBetterPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasBetterPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1connectedPath/title",
          "value": "connectedPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWTCPConnection~1connectedPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "connectedPath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nwtcpconnection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nwtcpconnection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
