{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTouchesRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"mentions":["doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures"],"kind":"mentions"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"The default value is 1."}],"type":"paragraph"}]}],"sections":[],"metadata":{"modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTouchesRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","title":"numberOfTouchesRequired","externalID":"c:objc(cs)UITapGestureRecognizer(py)numberOfTouchesRequired","platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"3.2"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"3.2"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"numberOfTouchesRequired"}]},"variants":[{"paths":["/documentation/uikit/uitapgesturerecognizer/numberoftouchesrequired"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitapgesturerecognizer/numberoftouchesrequired"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"},"kind":"symbol","abstract":[{"text":"The number of fingers that the user must tap for gesture recognition.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer"]]},"seeAlsoSections":[{"generated":true,"title":"Configuring the gesture","anchor":"Configuring-the-gesture","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired"]}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures":{"type":"topic","kind":"article","role":"article","url":"/documentation/uikit/handling-tap-gestures","abstract":[{"text":"Use brief taps on the screen to implement button-like interactions with your content.","type":"text"}],"title":"Handling tap gestures","identifier":"doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures"},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTouchesRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfTouchesRequired","url":"/documentation/uikit/uitapgesturerecognizer/numberoftouchesrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfTouchesRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The number of fingers that the user must tap for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTapsRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfTapsRequired","url":"/documentation/uikit/uitapgesturerecognizer/numberoftapsrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfTapsRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The number of taps necessary for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired"},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer":{"navigatorTitle":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"kind":"symbol","abstract":[{"text":"A discrete gesture recognizer that interprets single or multiple taps.","type":"text"}],"url":"/documentation/uikit/uitapgesturerecognizer","identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer","title":"UITapGestureRecognizer","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITapGestureRecognizer"}]},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"buttonMaskRequired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ButtonMask","preciseIdentifier":"c:@E@UIEventButtonMask"}],"title":"buttonMaskRequired","url":"/documentation/uikit/uitapgesturerecognizer/buttonmaskrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buttonMaskRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The bit mask of the buttons the user must press for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","deprecated":false,"introducedAt":"3.2","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"3.2","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"numberOfTouchesRequired","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"numberOfTouchesRequired","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer"]]},"path":"/hierarchy","op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired"],"title":"Configuring the gesture","anchor":"Configuring-the-gesture","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"numberOfTouchesRequired","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/title","value":"numberOfTouchesRequired"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/fragments","value":[{"kind":"identifier","text":"numberOfTouchesRequired"}]},{"op":"replace","value":"numberOfTapsRequired","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/title"},{"op":"replace","value":[{"kind":"identifier","text":"numberOfTapsRequired"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/fragments"},{"op":"replace","value":"UITapGestureRecognizer","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/title"},{"op":"replace","value":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/navigatorTitle"},{"op":"replace","value":"buttonMaskRequired","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/title"},{"op":"replace","value":[{"text":"buttonMaskRequired","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}