{"abstract":[{"type":"text","text":"The number of taps necessary for gesture recognition."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer"]]},"variants":[{"paths":["/documentation/uikit/uitapgesturerecognizer/numberoftapsrequired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitapgesturerecognizer/numberoftapsrequired"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(cs)UITapGestureRecognizer(py)numberOfTapsRequired","title":"numberOfTapsRequired","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTapsRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":[{"deprecated":false,"introducedAt":"3.2","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"3.2","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfTapsRequired"}],"roleHeading":"Instance Property","modules":[{"name":"UIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"numberOfTapsRequired","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures"]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The default value is 1."}],"type":"paragraph"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"],"anchor":"Configuring-the-gesture","title":"Configuring the gesture"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired"},"references":{"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTapsRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfTapsRequired","url":"/documentation/uikit/uitapgesturerecognizer/numberoftapsrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfTapsRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The number of taps necessary for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired"},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"buttonMaskRequired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ButtonMask","preciseIdentifier":"c:@E@UIEventButtonMask"}],"title":"buttonMaskRequired","url":"/documentation/uikit/uitapgesturerecognizer/buttonmaskrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buttonMaskRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The bit mask of the buttons the user must press for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired"},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer":{"navigatorTitle":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"kind":"symbol","abstract":[{"text":"A discrete gesture recognizer that interprets single or multiple taps.","type":"text"}],"url":"/documentation/uikit/uitapgesturerecognizer","identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer","title":"UITapGestureRecognizer","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITapGestureRecognizer"}]},"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfTouchesRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfTouchesRequired","url":"/documentation/uikit/uitapgesturerecognizer/numberoftouchesrequired","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfTouchesRequired"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The number of fingers that the user must tap for gesture recognition."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"},"doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures":{"type":"topic","kind":"article","role":"article","url":"/documentation/uikit/handling-tap-gestures","abstract":[{"text":"Use brief taps on the screen to implement button-like interactions with your content.","type":"text"}],"title":"Handling tap gestures","identifier":"doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"introducedAt":"3.2","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"3.2","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"numberOfTapsRequired","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"numberOfTapsRequired","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Configuring the gesture","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired","doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"],"anchor":"Configuring-the-gesture"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"numberOfTapsRequired","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"numberOfTapsRequired","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/title"},{"value":[{"text":"numberOfTapsRequired","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/fragments"},{"value":"buttonMaskRequired","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/title"},{"value":[{"kind":"identifier","text":"buttonMaskRequired"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/fragments"},{"value":"UITapGestureRecognizer","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/title"},{"value":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/fragments"},{"value":[{"kind":"identifier","text":"UITapGestureRecognizer"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/navigatorTitle"},{"value":"numberOfTouchesRequired","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/title"},{"value":[{"kind":"identifier","text":"numberOfTouchesRequired"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}