{
  "abstract": [
    {
      "text": "Watch for TXT record changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType/TXT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CFNetServiceMonitorType@kCFNetServiceMonitorTXT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TXT"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFNetServiceMonitorTXT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CFNetServiceMonitorType.TXT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TXT"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType": {
      "abstract": [
        {
          "text": "Record type specifier used to tell a service monitor the type of record changes to watch for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorType",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitortype"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType/TXT": {
      "abstract": [
        {
          "text": "Watch for TXT record changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TXT"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType/TXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServiceMonitorTXT"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorType.TXT",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitortype/txt"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFNetServiceMonitorTXT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServiceMonitorTXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCFNetServiceMonitorTXT"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/title",
          "value": "CFNetServiceMonitorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType~1TXT/title",
          "value": "kCFNetServiceMonitorTXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType~1TXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServiceMonitorTXT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetservicemonitortype/txt"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetservicemonitortype/txt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
