{
  "abstract": [
    {
      "text": "Options for creating clusters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/clustering-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Clustering Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify these options for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)": {
      "abstract": [
        {
          "text": "Groups categories or words (tokens) into the specified sets of clusters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapApplyClusters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapApplyClusters"
        }
      ],
      "role": "symbol",
      "title": "LSMMapApplyClusters(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapapplyclusters(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)": {
      "abstract": [
        {
          "text": "Compiles the map into executable form and puts it into mapping mode, preparing it for the classification of texts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapCompile"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapCompile"
        }
      ],
      "role": "symbol",
      "title": "LSMMapCompile(_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapcompile(_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Computes a set of clusters that group similar categories or words.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapCreateClusters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapCreateClusters"
        }
      ],
      "role": "symbol",
      "title": "LSMMapCreateClusters(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapcreateclusters(_:_:_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterAgglomerative": {
      "abstract": [
        {
          "text": "An option that specifies to cluster using an agglomerative algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMClusterAgglomerative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterAgglomerative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMClusterAgglomerative"
        }
      ],
      "role": "symbol",
      "title": "kLSMClusterAgglomerative",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmclusteragglomerative"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterCategories": {
      "abstract": [
        {
          "text": "An option that specifies to cluster categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMClusterCategories"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMClusterCategories"
        }
      ],
      "role": "symbol",
      "title": "kLSMClusterCategories",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmclustercategories"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterKMeans": {
      "abstract": [
        {
          "text": "An option that specifies to cluster using a k-means algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMClusterKMeans"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterKMeans",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMClusterKMeans"
        }
      ],
      "role": "symbol",
      "title": "kLSMClusterKMeans",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmclusterkmeans"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterTokens": {
      "abstract": [
        {
          "text": "An option that specifies to cluster binary tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMClusterTokens"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterTokens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMClusterTokens"
        }
      ],
      "role": "symbol",
      "title": "kLSMClusterTokens",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmclustertokens"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterWords": {
      "abstract": [
        {
          "text": "An option that specifies to cluster words.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMClusterWords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterWords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMClusterWords"
        }
      ],
      "role": "symbol",
      "title": "kLSMClusterWords",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmclusterwords"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-Classification-Mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)"
      ],
      "title": "Starting Classification Mode"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterCategories",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterWords",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterTokens",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterKMeans",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterAgglomerative"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterCategories",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterWords",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterTokens",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterKMeans",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMClusterAgglomerative"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-Classification-Mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)"
              ],
              "title": "Starting Classification Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCompile(_:)/title",
          "value": "LSMMapCompile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCompile(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCompile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateClusters(_:_:_:_:_:)/title",
          "value": "LSMMapCreateClusters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateClusters(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCreateClusters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterWords/title",
          "value": "kLSMClusterWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterWords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMClusterWords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterTokens/title",
          "value": "kLSMClusterTokens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterTokens/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMClusterTokens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterCategories/title",
          "value": "kLSMClusterCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMClusterCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapApplyClusters(_:_:)/title",
          "value": "LSMMapApplyClusters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapApplyClusters(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapApplyClusters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterKMeans/title",
          "value": "kLSMClusterKMeans"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterKMeans/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMClusterKMeans"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterAgglomerative/title",
          "value": "kLSMClusterAgglomerative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMClusterAgglomerative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMClusterAgglomerative"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/clustering-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/clustering-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
