{
  "abstract": [
    {
      "text": "Error codes in Latent Semantic Mapping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/error-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Codes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadCluster": {
      "abstract": [
        {
          "text": "An error code that indicates the specified clusters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapBadCluster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadCluster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapBadCluster"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapBadCluster",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapbadcluster"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadPath": {
      "abstract": [
        {
          "text": "An error code that indicates the specified URL doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapBadPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapBadPath"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapBadPath",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapbadpath"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapNoSuchCategory": {
      "abstract": [
        {
          "text": "An error code that indicates an invalid category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapNoSuchCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapNoSuchCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapNoSuchCategory"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapNoSuchCategory",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapnosuchcategory"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOutOfState": {
      "abstract": [
        {
          "text": "An error code that indicates you can’t issue the call in the current map state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapOutOfState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOutOfState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapOutOfState"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapOutOfState",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapoutofstate"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOverflow": {
      "abstract": [
        {
          "text": "An error code that indicates you can’t add more data to the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapOverflow"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapOverflow",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapoverflow"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapWriteError": {
      "abstract": [
        {
          "text": "An error code that indicates a map writing error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapWriteError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapWriteError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapWriteError"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapWriteError",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapwriteerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOutOfState",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapNoSuchCategory",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapWriteError",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadPath",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadCluster",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOverflow"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOutOfState",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapNoSuchCategory",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapWriteError",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadPath",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapBadCluster",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapOverflow"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapOutOfState/title",
          "value": "kLSMMapOutOfState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapOutOfState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapOutOfState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapBadCluster/title",
          "value": "kLSMMapBadCluster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapBadCluster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapBadCluster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapNoSuchCategory/title",
          "value": "kLSMMapNoSuchCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapNoSuchCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapNoSuchCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapWriteError/title",
          "value": "kLSMMapWriteError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapWriteError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapWriteError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapBadPath/title",
          "value": "kLSMMapBadPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapBadPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapBadPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapOverflow/title",
          "value": "kLSMMapOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapOverflow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
