{
  "abstract": [
    {
      "text": "A key that specifies the number of iterations to compute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kLSMIterationsKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kLSMIterationsKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kLSMIterationsKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kLSMIterationsKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kLSMIterationsKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense": {
      "abstract": [
        {
          "text": "A value that specifies to perform a singular value decomposition (SVD) on a dense matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmDense"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmDense"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmDense",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmdense"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey": {
      "abstract": [
        {
          "text": "A key that specifies which algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse": {
      "abstract": [
        {
          "text": "A value that specifies to perform a singular value decomposition (SVD) on a sparse matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmSparse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmSparse"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmSparse",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmsparse"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of singular values to compute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMDimensionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMDimensionKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMDimensionKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmdimensionkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of iterations to compute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMIterationsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMIterationsKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMIterationsKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmiterationskey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble": {
      "abstract": [
        {
          "text": "A value that specifies to use double arithmetic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionDouble"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionDouble"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionDouble",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisiondouble"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat": {
      "abstract": [
        {
          "text": "A value that specifies to use float arithmetic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionFloat"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionFloat",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisionfloat"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey": {
      "abstract": [
        {
          "text": "A key that specifies the precision to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisionkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of days between sweeping generations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMSweepAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMSweepAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMSweepAgeKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmsweepagekey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey": {
      "abstract": [
        {
          "text": "A key that specifies the minimum count to keep entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMSweepCutoffKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMSweepCutoffKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMSweepCutoffKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmsweepcutoffkey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kLSMIterationsKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMIterationsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kLSMIterationsKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionFloat/title",
          "value": "kLSMPrecisionFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmDense/title",
          "value": "kLSMAlgorithmDense"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmDense/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmDense"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMIterationsKey/title",
          "value": "kLSMIterationsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMIterationsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMIterationsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepCutoffKey/title",
          "value": "kLSMSweepCutoffKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepCutoffKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMSweepCutoffKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmSparse/title",
          "value": "kLSMAlgorithmSparse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmSparse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmSparse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmKey/title",
          "value": "kLSMAlgorithmKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionDouble/title",
          "value": "kLSMPrecisionDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionDouble/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepAgeKey/title",
          "value": "kLSMSweepAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMSweepAgeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMDimensionKey/title",
          "value": "kLSMDimensionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMDimensionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMDimensionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionKey/title",
          "value": "kLSMPrecisionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/klsmiterationskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/klsmiterationskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
