{
  "abstract": [
    {
      "text": "An option that specifies not to keep counts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapDiscardCounts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kLSMMapDiscardCounts@kLSMMapDiscardCounts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kLSMMapDiscardCounts"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kLSMMapDiscardCounts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kLSMMapDiscardCounts"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kLSMMapDiscardCounts"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you specify this option when loading the map, you must reload the map without this option before calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapStartTraining(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you specify this option when storing the map, the stored map can’t be retrained at all. This option can save a lot of memory or disk space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapStartTraining(_:)": {
      "abstract": [
        {
          "text": "Puts the map into training mode, preparing it for the addition of more categories or texts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapStartTraining"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapStartTraining(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapStartTraining"
        }
      ],
      "role": "symbol",
      "title": "LSMMapStartTraining(_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapstarttraining(_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapDiscardCounts": {
      "abstract": [
        {
          "text": "An option that specifies not to keep counts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapDiscardCounts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapDiscardCounts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapDiscardCounts"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapDiscardCounts",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmapdiscardcounts"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapHashText": {
      "abstract": [
        {
          "text": "An option that specifies to transform the text so it’s not human-readable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapHashText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapHashText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapHashText"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapHashText",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmaphashtext"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapLoadMutable": {
      "abstract": [
        {
          "text": "An option that specifies to load the map as mutable in training state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMMapLoadMutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapLoadMutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMMapLoadMutable"
        }
      ],
      "role": "symbol",
      "title": "kLSMMapLoadMutable",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmmaploadmutable"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapLoadMutable",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapHashText"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kLSMMapDiscardCounts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapDiscardCounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapLoadMutable",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMMapHashText"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kLSMMapDiscardCounts"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapStartTraining(_:)/title",
          "value": "LSMMapStartTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapStartTraining(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapStartTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapHashText/title",
          "value": "kLSMMapHashText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapHashText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapHashText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapLoadMutable/title",
          "value": "kLSMMapLoadMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapLoadMutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapLoadMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapDiscardCounts/title",
          "value": "kLSMMapDiscardCounts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMMapDiscardCounts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMMapDiscardCounts"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/klsmmapdiscardcounts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/klsmmapdiscardcounts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
