{
  "abstract": [
    {
      "text": "Computes a set of clusters that group similar categories or words.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@LSMMapCreateClusters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LSMMapCreateClusters"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@LSMMapRef",
        "text": "LSMMap"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFIndex",
        "text": "CFIndex"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFOptionFlags",
        "text": "CFOptionFlags"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ">?"
      }
    ],
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSMMapCreateClusters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "LSMMapCreateClusters(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LSMMapCreateClusters"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "alloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mapref"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@LSMMapRef",
              "text": "LSMMap"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "subset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "numClusters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFOptionFlags",
              "text": "CFOptionFlags"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ">?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "subset",
              "type": "codeVoice"
            },
            {
              "text": " is non-",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ", this function only performs clustering on the categories or words in ",
              "type": "text"
            },
            {
              "code": "subset",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)": {
      "abstract": [
        {
          "text": "Groups categories or words (tokens) into the specified sets of clusters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapApplyClusters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapApplyClusters"
        }
      ],
      "role": "symbol",
      "title": "LSMMapApplyClusters(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapapplyclusters(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)": {
      "abstract": [
        {
          "text": "Compiles the map into executable form and puts it into mapping mode, preparing it for the classification of texts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapCompile"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapCompile"
        }
      ],
      "role": "symbol",
      "title": "LSMMapCompile(_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapcompile(_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Computes a set of clusters that group similar categories or words.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapCreateClusters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateClusters(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapCreateClusters"
        }
      ],
      "role": "symbol",
      "title": "LSMMapCreateClusters(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapcreateclusters(_:_:_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/clustering-flags": {
      "abstract": [
        {
          "text": "Options for creating clusters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/clustering-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clustering Flags",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/clustering-flags"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags": {
      "abstract": [
        {
          "text": "A bitfield used for passing special allocation and other requests into Core Foundation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFOptionFlags",
      "type": "topic",
      "url": "/documentation/corefoundation/cfoptionflags"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-Classification-Mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/clustering-flags",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)"
      ],
      "title": "Starting Classification Mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSMMapCreateClusters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCreateClusters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-Classification-Mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCompile(_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/clustering-flags",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapApplyClusters(_:_:)"
              ],
              "title": "Starting Classification Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LSMMapCreateClusters"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alloc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@LSMMapRef",
                    "text": "LSMMapRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mapref"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "subset"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "numClusters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFOptionFlags",
                    "text": "CFOptionFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapApplyClusters(_:_:)/title",
          "value": "LSMMapApplyClusters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapApplyClusters(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapApplyClusters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCompile(_:)/title",
          "value": "LSMMapCompile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCompile(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCompile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateClusters(_:_:_:_:_:)/title",
          "value": "LSMMapCreateClusters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateClusters(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCreateClusters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmmapcreateclusters(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmmapcreateclusters(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
