{
  "abstract": [
    {
      "text": "Writes information about a map or text to a stream in text form.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToStream(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@LSMMapWriteToStream",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LSMMapWriteToStream"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@LSMMapRef",
        "text": "LSMMap"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@LSMTextRef",
        "text": "LSMText"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFWriteStreamRef",
        "text": "CFWriteStream"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFOptionFlags",
        "text": "CFOptionFlags"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSMMapWriteToStream"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "LSMMapWriteToStream(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LSMMapWriteToStream"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mapref"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@LSMMapRef",
              "text": "LSMMap"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "textref"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@LSMTextRef",
              "text": "LSMText"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "stream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFWriteStreamRef",
              "text": "CFWriteStream"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFOptionFlags",
              "text": "CFOptionFlags"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateFromURL(_:_:_:)": {
      "abstract": [
        {
          "text": "Loads a map from the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapCreateFromURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateFromURL(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapCreateFromURL"
        }
      ],
      "role": "symbol",
      "title": "LSMMapCreateFromURL(_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapcreatefromurl(_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToStream(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Writes information about a map or text to a stream in text form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapWriteToStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToStream(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapWriteToStream"
        }
      ],
      "role": "symbol",
      "title": "LSMMapWriteToStream(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapwritetostream(_:_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToURL(_:_:_:)": {
      "abstract": [
        {
          "text": "Compiles the map, if necessary, and stores it into the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapWriteToURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToURL(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapWriteToURL"
        }
      ],
      "role": "symbol",
      "title": "LSMMapWriteToURL(_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapwritetourl(_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText": {
      "abstract": [
        {
          "text": "An input text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "role": "symbol",
      "title": "LSMText",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtext"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/storage-flags": {
      "abstract": [
        {
          "text": "Options for loading and saving a map to a file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/storage-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storage Flags",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/storage-flags"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags": {
      "abstract": [
        {
          "text": "A bitfield used for passing special allocation and other requests into Core Foundation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFOptionFlags",
      "type": "topic",
      "url": "/documentation/corefoundation/cfoptionflags"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef": {
      "abstract": [
        {
          "text": "A reference to a writable stream object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFWriteStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFWriteStream",
      "type": "topic",
      "url": "/documentation/corefoundation/cfwritestream"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-and-Saving-a-Map",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateFromURL(_:_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToURL(_:_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/storage-flags"
      ],
      "title": "Loading and Saving a Map"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSMMapWriteToStream"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapWriteToStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-and-Saving-a-Map",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapCreateFromURL(_:_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapWriteToURL(_:_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/storage-flags"
              ],
              "title": "Loading and Saving a Map"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LSMMapWriteToStream"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@LSMMapRef",
                    "text": "LSMMapRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mapref"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@LSMTextRef",
                    "text": "LSMTextRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textref"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFWriteStreamRef",
                    "text": "CFWriteStreamRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "stream"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFOptionFlags",
                    "text": "CFOptionFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/title",
          "value": "LSMTextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapWriteToStream(_:_:_:_:)/title",
          "value": "LSMMapWriteToStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapWriteToStream(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapWriteToStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapWriteToURL(_:_:_:)/title",
          "value": "LSMMapWriteToURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapWriteToURL(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapWriteToURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateFromURL(_:_:_:)/title",
          "value": "LSMMapCreateFromURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapCreateFromURL(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapCreateFromURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFWriteStreamRef/title",
          "value": "CFWriteStreamRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmmapwritetostream(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmmapwritetostream(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
