{
  "abstract": [
    {
      "text": "An input text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@LSMTextRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LSMText"
      }
    ],
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSMText"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "LSMText"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LSMText"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is a mutable, opaque Core Foundation type that represents an input text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult": {
      "abstract": [
        {
          "text": "A result of a lookup in a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "role": "symbol",
      "title": "LSMResult",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmresult"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText": {
      "abstract": [
        {
          "text": "An input text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "role": "symbol",
      "title": "LSMText",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtext"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddToken(_:_:)": {
      "abstract": [
        {
          "text": "Adds an arbitrary binary token to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMTextAddToken"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddToken(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMTextAddToken"
        }
      ],
      "role": "symbol",
      "title": "LSMTextAddToken(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtextaddtoken(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWord(_:_:)": {
      "abstract": [
        {
          "text": "Adds a word to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMTextAddWord"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWord(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMTextAddWord"
        }
      ],
      "role": "symbol",
      "title": "LSMTextAddWord(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtextaddword(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWords(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Breaks a string into words using the specified locale, and adds the words to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMTextAddWords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFLocaleRef",
          "text": "CFLocale"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWords(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMTextAddWords"
        }
      ],
      "role": "symbol",
      "title": "LSMTextAddWords(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtextaddwords(_:_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextCreate(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMTextCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextCreate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMTextCreate"
        }
      ],
      "role": "symbol",
      "title": "LSMTextCreate(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtextcreate(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for Latent Semantic Mapping texts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMTextGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMTextGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "LSMTextGetTypeID()",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtextgettypeid()"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/parsing-flags": {
      "abstract": [
        {
          "text": "Options for parsing words to add to the text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/parsing-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Parsing Flags",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/parsing-flags"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-Classification",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult"
      ],
      "title": "Text Classification"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Text-Object",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextCreate(_:_:)"
      ],
      "title": "Creating a Text Object"
    },
    {
      "anchor": "Adding-to-the-Text",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddToken(_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWord(_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWords(_:_:_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/parsing-flags"
      ],
      "title": "Adding to the Text"
    },
    {
      "anchor": "Getting-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextGetTypeID()"
      ],
      "title": "Getting the Type Identifier"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSMTextRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Text-Object",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextCreate(_:_:)"
              ],
              "title": "Creating a Text Object"
            },
            {
              "anchor": "Adding-to-the-Text",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddToken(_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWord(_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextAddWords(_:_:_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/parsing-flags"
              ],
              "title": "Adding to the Text"
            },
            {
              "anchor": "Getting-the-Type-Identifier",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMTextGetTypeID()"
              ],
              "title": "Getting the Type Identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-Classification",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult"
              ],
              "title": "Text Classification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@__LSMText",
                    "text": "__LSMText"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "LSMTextRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/title",
          "value": "LSMResultRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddToken(_:_:)/title",
          "value": "LSMTextAddToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddToken(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextAddToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddWords(_:_:_:_:)/title",
          "value": "LSMTextAddWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddWords(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextAddWords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextCreate(_:_:)/title",
          "value": "LSMTextCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextCreate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextGetTypeID()/title",
          "value": "LSMTextGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddWord(_:_:)/title",
          "value": "LSMTextAddWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMTextAddWord(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextAddWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/title",
          "value": "LSMTextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmtext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/lsmtext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
