{
  "abstract": [
    {
      "text": "Special properties that determine a map’s behavior.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/map-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Map Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Latent Semantic Mapping interprets the following keys. All other keys starting with ",
              "type": "text"
            },
            {
              "code": "LSM",
              "type": "codeVoice"
            },
            {
              "text": " are reserved.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapGetProperties(_:)": {
      "abstract": [
        {
          "text": "Gets a dictionary of properties for the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapGetProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapGetProperties(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapGetProperties"
        }
      ],
      "role": "symbol",
      "title": "LSMMapGetProperties(_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapgetproperties(_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapSetProperties(_:_:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of properties for the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMapSetProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapSetProperties(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMapSetProperties"
        }
      ],
      "role": "symbol",
      "title": "LSMMapSetProperties(_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmapsetproperties(_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense": {
      "abstract": [
        {
          "text": "A value that specifies to perform a singular value decomposition (SVD) on a dense matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmDense"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmDense"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmDense",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmdense"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey": {
      "abstract": [
        {
          "text": "A key that specifies which algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse": {
      "abstract": [
        {
          "text": "A value that specifies to perform a singular value decomposition (SVD) on a sparse matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmSparse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMAlgorithmSparse"
        }
      ],
      "role": "symbol",
      "title": "kLSMAlgorithmSparse",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmalgorithmsparse"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of singular values to compute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMDimensionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMDimensionKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMDimensionKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmdimensionkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of iterations to compute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMIterationsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMIterationsKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMIterationsKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmiterationskey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble": {
      "abstract": [
        {
          "text": "A value that specifies to use double arithmetic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionDouble"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionDouble"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionDouble",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisiondouble"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat": {
      "abstract": [
        {
          "text": "A value that specifies to use float arithmetic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionFloat"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionFloat",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisionfloat"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey": {
      "abstract": [
        {
          "text": "A key that specifies the precision to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMPrecisionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMPrecisionKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMPrecisionKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmprecisionkey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey": {
      "abstract": [
        {
          "text": "A key that specifies the number of days between sweeping generations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMSweepAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMSweepAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMSweepAgeKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmsweepagekey"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey": {
      "abstract": [
        {
          "text": "A key that specifies the minimum count to keep entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMSweepCutoffKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMSweepCutoffKey"
        }
      ],
      "role": "symbol",
      "title": "kLSMSweepCutoffKey",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmsweepcutoffkey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-a-Maps-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapSetProperties(_:_:)",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapGetProperties(_:)"
      ],
      "title": "Managing a Map’s Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmDense",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMAlgorithmSparse",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionFloat",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMPrecisionDouble",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMDimensionKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMIterationsKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepAgeKey",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMSweepCutoffKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-a-Maps-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapSetProperties(_:_:)",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMapGetProperties(_:)"
              ],
              "title": "Managing a Map’s Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapGetProperties(_:)/title",
          "value": "LSMMapGetProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapGetProperties(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapGetProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionFloat/title",
          "value": "kLSMPrecisionFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMIterationsKey/title",
          "value": "kLSMIterationsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMIterationsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMIterationsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapSetProperties(_:_:)/title",
          "value": "LSMMapSetProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMapSetProperties(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapSetProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMDimensionKey/title",
          "value": "kLSMDimensionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMDimensionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMDimensionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepCutoffKey/title",
          "value": "kLSMSweepCutoffKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepCutoffKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMSweepCutoffKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepAgeKey/title",
          "value": "kLSMSweepAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMSweepAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMSweepAgeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmKey/title",
          "value": "kLSMAlgorithmKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmDense/title",
          "value": "kLSMAlgorithmDense"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmDense/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmDense"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionDouble/title",
          "value": "kLSMPrecisionDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionDouble/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmSparse/title",
          "value": "kLSMAlgorithmSparse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMAlgorithmSparse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMAlgorithmSparse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionKey/title",
          "value": "kLSMPrecisionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMPrecisionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMPrecisionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/map-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/map-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
