{
  "abstract": [
    {
      "text": "Options for creating a result.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/result-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Result Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify these options for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResultCreate(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult": {
      "abstract": [
        {
          "text": "A result of a lookup in a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "role": "symbol",
      "title": "LSMResult",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmresult"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResultCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the categories or words that best match when a text is mapped into a map, in decreasing order of likelihood.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMResultCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMMapRef",
          "text": "LSMMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMTextRef",
          "text": "LSMText"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LSMResultRef",
          "text": "LSMResult"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResultCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMResultCreate"
        }
      ],
      "role": "symbol",
      "title": "LSMResultCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmresultcreate(_:_:_:_:_:)"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMResultBestWords": {
      "abstract": [
        {
          "text": "Finds the words, rather than categories, that best match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLSMResultBestWords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMResultBestWords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLSMResultBestWords"
        }
      ],
      "role": "symbol",
      "title": "kLSMResultBestWords",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/klsmresultbestwords"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Result",
      "generated": true,
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResultCreate(_:_:_:_:_:)"
      ],
      "title": "Creating a Result"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMResultBestWords"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/kLSMResultBestWords"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Result",
              "generated": true,
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResultCreate(_:_:_:_:_:)"
              ],
              "title": "Creating a Result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/title",
          "value": "LSMResultRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResultCreate(_:_:_:_:_:)/title",
          "value": "LSMResultCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResultCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMResultBestWords/title",
          "value": "kLSMResultBestWords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1kLSMResultBestWords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLSMResultBestWords"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping/result-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping/result-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
