{
  "abstract": [
    {
      "text": "The error code that indicates an invalid billing address or billing name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/billingContactInvalidError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPaymentErrorCode@PKPaymentBillingContactInvalidError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "billingContactInvalidError"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentBillingContactInvalidError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPaymentError.Code.billingContactInvalidError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "billingContactInvalidError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this error code if the billing contact information on the Apple Pay sheet has an error in the address or name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError": {
      "abstract": [
        {
          "text": "An error type that you create to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code": {
      "abstract": [
        {
          "text": "An error code that you provide to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/billingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code that indicates an invalid billing address or billing name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingContactInvalidError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/billingContactInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentBillingContactInvalidError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.billingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/billingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeExpiredError": {
      "abstract": [
        {
          "text": "The error code that indicates an expired coupon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couponCodeExpiredError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeExpiredError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentCouponCodeExpiredError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.couponCodeExpiredError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/couponcodeexpirederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeInvalidError": {
      "abstract": [
        {
          "text": "The error code that indicates an invalid coupon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couponCodeInvalidError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentCouponCodeInvalidError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.couponCodeInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/couponcodeinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingAddressUnserviceableError": {
      "abstract": [
        {
          "text": "The error code that indicates an unserviceable shipping address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingAddressUnserviceableError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingAddressUnserviceableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentShippingAddressUnserviceableError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.shippingAddressUnserviceableError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/shippingaddressunserviceableerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code that indicates an invalid shipping address, email, phone, or name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingContactInvalidError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentShippingContactInvalidError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.shippingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/shippingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/unknownError": {
      "abstract": [
        {
          "text": "The error code that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentUnknownError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/unknownerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeExpiredError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeInvalidError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingAddressUnserviceableError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/unknownError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentBillingContactInvalidError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentBillingContactInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeExpiredError",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/couponCodeInvalidError",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingAddressUnserviceableError",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/unknownError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPaymentBillingContactInvalidError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingContactInvalidError/title",
          "value": "PKPaymentShippingContactInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingContactInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentShippingContactInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1couponCodeInvalidError/title",
          "value": "PKPaymentCouponCodeInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1couponCodeInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentCouponCodeInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1billingContactInvalidError/title",
          "value": "PKPaymentBillingContactInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1billingContactInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentBillingContactInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1unknownError/title",
          "value": "PKPaymentUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingAddressUnserviceableError/title",
          "value": "PKPaymentShippingAddressUnserviceableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingAddressUnserviceableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentShippingAddressUnserviceableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/title",
          "value": "PKPaymentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1couponCodeExpiredError/title",
          "value": "PKPaymentCouponCodeExpiredError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1couponCodeExpiredError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentCouponCodeExpiredError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymenterror/code/billingcontactinvaliderror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymenterror/code/billingcontactinvaliderror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
