{
  "abstract": [
    {
      "text": "The protocol you implement to respond to changes to a broadcast activity user interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)RPBroadcastActivityViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RPBroadcastActivityViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RPBroadcastActivityViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "RPBroadcastActivityViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to respond to changes to a broadcast activity user interface, represented by an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a user interface where users choose a broadcast service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewController"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastActivityViewController",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivityviewcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate for the broadcast activity view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)RPBroadcastActivityViewControllerDelegate",
          "text": "RPBroadcastActivityViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivityviewcontroller/delegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol you implement to respond to changes to a broadcast activity user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastActivityViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivityviewcontrollerdelegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate/broadcastActivityViewController(_:didFinishWith:error:)": {
      "abstract": [
        {
          "text": "Indicates that the broadcast activity view controller is ready to be dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastActivityViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPBroadcastActivityViewController",
          "text": "RPBroadcastActivityViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPBroadcastController",
          "text": "RPBroadcastController"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate/broadcastActivityViewController(_:didFinishWith:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastActivityViewController:didFinishWithBroadcastController:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "broadcastActivityViewController(_:didFinishWith:error:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivityviewcontrollerdelegate/broadcastactivityviewcontroller(_:didfinishwith:error:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController/delegate"
      ],
      "title": "Getting the Delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Connecting-to-a-Service",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate/broadcastActivityViewController(_:didFinishWith:error:)"
      ],
      "title": "Connecting to a Service"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RPBroadcastActivityViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Connecting-to-a-Service",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewControllerDelegate/broadcastActivityViewController(_:didFinishWith:error:)"
              ],
              "title": "Connecting to a Service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController/delegate"
              ],
              "title": "Getting the Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "RPBroadcastActivityViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewControllerDelegate~1broadcastActivityViewController(_:didFinishWith:error:)/title",
          "value": "broadcastActivityViewController:didFinishWithBroadcastController:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewControllerDelegate~1broadcastActivityViewController(_:didFinishWith:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastActivityViewController:didFinishWithBroadcastController:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewControllerDelegate/title",
          "value": "RPBroadcastActivityViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/title",
          "value": "RPBroadcastActivityViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastactivityviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastactivityviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
