{
  "abstract": [
    {
      "text": "The ReplayKit error domain codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@RPRecordingErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RPRecordingErrorCode"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RPRecordingErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "RPRecordingErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode": {
      "abstract": [
        {
          "text": "The ReplayKit error domain codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/equatable-implementations"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/rawrepresentable-implementations"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall": {
      "abstract": [
        {
          "text": "Unable to record due to an active phone call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePhoneCall"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorActivePhoneCall"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.activePhoneCall",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/activephonecall"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState": {
      "abstract": [
        {
          "text": "Attempted to start a recording that’s already in a recording state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStartInRecordingState"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorAttemptToStartInRecordingState"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.attemptToStartInRecordingState",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/attempttostartinrecordingstate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording": {
      "abstract": [
        {
          "text": "Attempted to stop a recording that’s not in a recording state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStopNonRecording"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorAttemptToStopNonRecording"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.attemptToStopNonRecording",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/attempttostopnonrecording"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession": {
      "abstract": [
        {
          "text": "Attempted to start a broadcast without a prior session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastInvalidSession"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorBroadcastInvalidSession"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.broadcastInvalidSession",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/broadcastinvalidsession"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed": {
      "abstract": [
        {
          "text": "The broadcast set up failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastSetupFailed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorBroadcastSetupFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.broadcastSetupFailed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/broadcastsetupfailed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay": {
      "abstract": [
        {
          "text": "Failed to start recording because CarPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carPlay"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCarPlay"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.carPlay",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/carplay"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful": {
      "abstract": [
        {
          "text": "Successfully saved the recording to the Camera Roll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSuccessful"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCodeSuccessful"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.codeSuccessful",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/codesuccessful"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize": {
      "abstract": [
        {
          "text": "Recording interrupted by multitasking and content resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentResize"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorContentResize"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.contentResize",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/contentresize"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled": {
      "abstract": [
        {
          "text": "Recording disabled via parental controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorDisabled"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.disabled",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/disabled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements": {
      "abstract": [
        {
          "text": "Recording failed due to missing entitlements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entitlements"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorEntitlements"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.entitlements",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/entitlements"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/exportClipToURLInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exportClipToURLInProgress"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/exportClipToURLInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorExportClipToURLInProgress"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.exportClipToURLInProgress",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/exportcliptourlinprogress"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed": {
      "abstract": [
        {
          "text": "Recording error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted": {
      "abstract": [
        {
          "text": "The recording failed because the app’s connection was interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInterrupted"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedApplicationConnectionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedApplicationConnectionInterrupted",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedapplicationconnectioninterrupted"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid": {
      "abstract": [
        {
          "text": "The recording failed because the app’s connection is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInvalid"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedApplicationConnectionInvalid"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedApplicationConnectionInvalid",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedapplicationconnectioninvalid"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled": {
      "abstract": [
        {
          "text": "The recording failed because the user canceled the export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterExportCanceled"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterExportCanceled"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterExportCanceled",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterexportcanceled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed": {
      "abstract": [
        {
          "text": "The recording failed due to an error exporting the movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterExportFailed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterExportFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterExportFailed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterexportfailed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterFailedToSave": {
      "abstract": [
        {
          "text": "The recording failed due to an asset writer failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterFailedToSave"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterFailedToSave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterFailedToSave"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterFailedToSave",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterfailedtosave"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterInWrongState": {
      "abstract": [
        {
          "text": "The recording failed because the asset writer is in an invalid state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterInWrongState"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterInWrongState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterInWrongState"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterInWrongState",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterinwrongstate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedIncorrectTimeStamps": {
      "abstract": [
        {
          "text": "The recording failed due to malformed start and end time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedIncorrectTimeStamps"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedIncorrectTimeStamps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedIncorrectTimeStamps"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedIncorrectTimeStamps",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedincorrecttimestamps"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedMediaServicesFailure": {
      "abstract": [
        {
          "text": "The recording failed due to a mediaservices daemon failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedMediaServicesFailure"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedMediaServicesFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedMediaServicesFailure"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedMediaServicesFailure",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedmediaservicesfailure"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoAssetWriter": {
      "abstract": [
        {
          "text": "The recording failed because there is no asset writer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedNoAssetWriter"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoAssetWriter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedNoAssetWriter"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedNoAssetWriter",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failednoassetwriter"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoMatchingApplicationContext": {
      "abstract": [
        {
          "text": "The context identifier doesn’t match the app identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedNoMatchingApplicationContext"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoMatchingApplicationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedNoMatchingApplicationContext"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedNoMatchingApplicationContext",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failednomatchingapplicationcontext"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToObtainURL": {
      "abstract": [
        {
          "text": "The recording failed due to a failure to obtain the URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToObtainURL"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToObtainURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToObtainURL"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToObtainURL",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtoobtainurl"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToProcessFirstSample": {
      "abstract": [
        {
          "text": "The recording failed because the asset writer failed to process the first media sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToProcessFirstSample"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToProcessFirstSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToProcessFirstSample"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToProcessFirstSample",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtoprocessfirstsample"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToRemoveFile": {
      "abstract": [
        {
          "text": "The recording failed because the temporary file wasn’t removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToRemoveFile"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToRemoveFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToRemoveFile"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToRemoveFile",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtoremovefile"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToSave": {
      "abstract": [
        {
          "text": "The recording failed to save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToSave"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToSave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToSave"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToSave",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtosave"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStart": {
      "abstract": [
        {
          "text": "Recording failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStart"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToStart"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToStart",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtostart"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStartCaptureStack": {
      "abstract": [
        {
          "text": "The system failed to configure the app for A/V recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartCaptureStack"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStartCaptureStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedToStartCaptureStack"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedToStartCaptureStack",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedtostartcapturestack"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/filePermissions": {
      "abstract": [
        {
          "text": "The recording failed due to a file permission error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filePermissions"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/filePermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFilePermissions"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.filePermissions",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/filepermissions"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/init(rawvalue:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/insufficientStorage": {
      "abstract": [
        {
          "text": "Not enough storage available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientStorage"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/insufficientStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorInsufficientStorage"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.insufficientStorage",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/insufficientstorage"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/interrupted": {
      "abstract": [
        {
          "text": "Recording interrupted by another app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interrupted"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/interrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorInterrupted"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.interrupted",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/interrupted"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/invalidParameter": {
      "abstract": [
        {
          "text": "The recording failed because of an invalid parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.invalidParameter",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/invalidparameter"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/photoFailure": {
      "abstract": [
        {
          "text": "Failed saving the video the Camera Roll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoFailure"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/photoFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorPhotoFailure"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.photoFailure",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/photofailure"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession": {
      "abstract": [
        {
          "text": "Attempted to start an invalid recording session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingInvalidSession"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorRecordingInvalidSession"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.recordingInvalidSession",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/recordinginvalidsession"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/systemDormancy": {
      "abstract": [
        {
          "text": "Recording forced to end by the user pressing the power button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemDormancy"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/systemDormancy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorSystemDormancy"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.systemDormancy",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/systemdormancy"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/unknown": {
      "abstract": [
        {
          "text": "Error cause unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.unknown",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/unknown"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/userDeclined": {
      "abstract": [
        {
          "text": "User declined recording request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDeclined"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/userDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorUserDeclined"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.userDeclined",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/userdeclined"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/videoMixingFailure": {
      "abstract": [
        {
          "text": "The recording failed due to an A/V mixing failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoMixingFailure"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/videoMixingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorVideoMixingFailure"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.videoMixingFailure",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/videomixingfailure"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi": {
      "abstract": [
        {
          "text": "The ReplayKit framework error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RPRecordingErrorDomain",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrordomain-5gi"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterFailedToSave",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterInWrongState",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedIncorrectTimeStamps",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedMediaServicesFailure",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoAssetWriter",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoMatchingApplicationContext",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToObtainURL",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToProcessFirstSample",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToRemoveFile",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStartCaptureStack",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStart",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToSave",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/filePermissions",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/insufficientStorage",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/interrupted",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/invalidParameter",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/photoFailure",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/systemDormancy",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/unknown",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/userDeclined",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/videoMixingFailure"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/exportClipToURLInProgress"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/Equatable-Implementations",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RPRecordingErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterFailedToSave",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterInWrongState",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedIncorrectTimeStamps",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedMediaServicesFailure",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoAssetWriter",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedNoMatchingApplicationContext",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToObtainURL",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToProcessFirstSample",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToRemoveFile",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStartCaptureStack",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToStart",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedToSave",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/filePermissions",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/insufficientStorage",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/interrupted",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/invalidParameter",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/photoFailure",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/systemDormancy",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/unknown",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/userDeclined",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/videoMixingFailure"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/exportClipToURLInProgress"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "RPRecordingErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "RPRecordingErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1recordingInvalidSession/title",
          "value": "RPRecordingErrorRecordingInvalidSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1recordingInvalidSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorRecordingInvalidSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failed/title",
          "value": "RPRecordingErrorFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToRemoveFile/title",
          "value": "RPRecordingErrorFailedToRemoveFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToRemoveFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToRemoveFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastInvalidSession/title",
          "value": "RPRecordingErrorBroadcastInvalidSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastInvalidSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorBroadcastInvalidSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedNoMatchingApplicationContext/title",
          "value": "RPRecordingErrorFailedNoMatchingApplicationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedNoMatchingApplicationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedNoMatchingApplicationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1systemDormancy/title",
          "value": "RPRecordingErrorSystemDormancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1systemDormancy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorSystemDormancy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToStartCaptureStack/title",
          "value": "RPRecordingErrorFailedToStartCaptureStack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToStartCaptureStack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToStartCaptureStack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterInWrongState/title",
          "value": "RPRecordingErrorFailedAssetWriterInWrongState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterInWrongState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterInWrongState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1invalidParameter/title",
          "value": "RPRecordingErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToProcessFirstSample/title",
          "value": "RPRecordingErrorFailedToProcessFirstSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToProcessFirstSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToProcessFirstSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedMediaServicesFailure/title",
          "value": "RPRecordingErrorFailedMediaServicesFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedMediaServicesFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedMediaServicesFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterFailedToSave/title",
          "value": "RPRecordingErrorFailedAssetWriterFailedToSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterFailedToSave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterFailedToSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1exportClipToURLInProgress/title",
          "value": "RPRecordingErrorExportClipToURLInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1exportClipToURLInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorExportClipToURLInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToSave/title",
          "value": "RPRecordingErrorFailedToSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToSave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1disabled/title",
          "value": "RPRecordingErrorDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToStart/title",
          "value": "RPRecordingErrorFailedToStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/title",
          "value": "RPRecordingErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1contentResize/title",
          "value": "RPRecordingErrorContentResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1contentResize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorContentResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1videoMixingFailure/title",
          "value": "RPRecordingErrorVideoMixingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1videoMixingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorVideoMixingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1activePhoneCall/title",
          "value": "RPRecordingErrorActivePhoneCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1activePhoneCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorActivePhoneCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1photoFailure/title",
          "value": "RPRecordingErrorPhotoFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1photoFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorPhotoFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1userDeclined/title",
          "value": "RPRecordingErrorUserDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1userDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorUserDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStopNonRecording/title",
          "value": "RPRecordingErrorAttemptToStopNonRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStopNonRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorAttemptToStopNonRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1entitlements/title",
          "value": "RPRecordingErrorEntitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1entitlements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorEntitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInterrupted/title",
          "value": "RPRecordingErrorFailedApplicationConnectionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedApplicationConnectionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1interrupted/title",
          "value": "RPRecordingErrorInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1interrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportCanceled/title",
          "value": "RPRecordingErrorFailedAssetWriterExportCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterExportCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStartInRecordingState/title",
          "value": "RPRecordingErrorAttemptToStartInRecordingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStartInRecordingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorAttemptToStartInRecordingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1unknown/title",
          "value": "RPRecordingErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastSetupFailed/title",
          "value": "RPRecordingErrorBroadcastSetupFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastSetupFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorBroadcastSetupFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToObtainURL/title",
          "value": "RPRecordingErrorFailedToObtainURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedToObtainURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedToObtainURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportFailed/title",
          "value": "RPRecordingErrorFailedAssetWriterExportFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterExportFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedNoAssetWriter/title",
          "value": "RPRecordingErrorFailedNoAssetWriter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedNoAssetWriter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedNoAssetWriter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1filePermissions/title",
          "value": "RPRecordingErrorFilePermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1filePermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1insufficientStorage/title",
          "value": "RPRecordingErrorInsufficientStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1insufficientStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorInsufficientStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInvalid/title",
          "value": "RPRecordingErrorFailedApplicationConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedApplicationConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1codeSuccessful/title",
          "value": "RPRecordingErrorCodeSuccessful"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1codeSuccessful/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCodeSuccessful"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1carPlay/title",
          "value": "RPRecordingErrorCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1carPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedIncorrectTimeStamps/title",
          "value": "RPRecordingErrorFailedIncorrectTimeStamps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedIncorrectTimeStamps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedIncorrectTimeStamps"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rprecordingerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rprecordingerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
