{
  "abstract": [
    {
      "text": "The shared recorder object that provides the ability to record audio and video of your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)RPScreenRecorder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RPScreenRecorder"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RPScreenRecorder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "RPScreenRecorder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps on a user’s device can share the recording function, with each app having its own instance of  ",
              "type": "text"
            },
            {
              "code": "RPScreenRecorder",
              "type": "codeVoice"
            },
            {
              "text": ". Your app can record the audio and video inside of the app, along with user commentary through the microphone. You get a reference to the recorder through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/shared()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function and use it to implement start-and-stop recording functionality. You can present a user interface (view controller) where a user can trim and preview recordings, and share them with other users. Only one app at a time can use the recorder on the user’s device. Your app can’t record video from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPCameraPosition": {
      "abstract": [
        {
          "text": "The position of the camera being accessed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPCameraPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPCameraPosition"
        }
      ],
      "role": "symbol",
      "title": "RPCameraPosition",
      "type": "topic",
      "url": "/documentation/replaykit/rpcameraposition"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController": {
      "abstract": [
        {
          "text": "An object that displays a user interface where users preview and edit a screen recording that you create with ReplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "role": "symbol",
      "title": "RPPreviewViewController",
      "type": "topic",
      "url": "/documentation/replaykit/rppreviewviewcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPSampleBufferType": {
      "abstract": [
        {
          "text": "The type of media clip sample being buffered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPSampleBufferType"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPSampleBufferType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPSampleBufferType"
        }
      ],
      "role": "symbol",
      "title": "RPSampleBufferType",
      "type": "topic",
      "url": "/documentation/replaykit/rpsamplebuffertype"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder": {
      "abstract": [
        {
          "text": "The shared recorder object that provides the ability to record audio and video of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorder",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPosition": {
      "abstract": [
        {
          "text": "The camera position to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@RPCameraPosition",
          "text": "RPCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraPosition"
        }
      ],
      "role": "symbol",
      "title": "cameraPosition",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/cameraposition"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPreviewView": {
      "abstract": [
        {
          "text": "A view containing the contents of the front-facing camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraPreviewView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPreviewView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraPreviewView"
        }
      ],
      "role": "symbol",
      "title": "cameraPreviewView",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/camerapreviewview"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/delegate": {
      "abstract": [
        {
          "text": "The delegate for the screen recorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)RPScreenRecorderDelegate",
          "text": "RPScreenRecorderDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/delegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/discardRecording(handler:)": {
      "abstract": [
        {
          "text": "Discards the current recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/discardRecording(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardRecordingWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "discardRecording(handler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/discardrecording(handler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/exportClip(to:duration:completionHandler:)": {
      "abstract": [
        {
          "text": "Exports a clip recording to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exportClip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/exportClip(to:duration:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exportClipToURL:duration:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "exportClip(to:duration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/exportclip(to:duration:completionhandler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/init"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the screen recorder is available for recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "available"
        }
      ],
      "role": "symbol",
      "title": "isAvailable",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/isavailable"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isCameraEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the camera is currently enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCameraEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isCameraEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraEnabled"
        }
      ],
      "role": "symbol",
      "title": "isCameraEnabled",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/iscameraenabled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isMicrophoneEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the microphone is currently enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMicrophoneEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isMicrophoneEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "microphoneEnabled"
        }
      ],
      "role": "symbol",
      "title": "isMicrophoneEnabled",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/ismicrophoneenabled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isRecording": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app is currently recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRecording"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recording"
        }
      ],
      "role": "symbol",
      "title": "isRecording",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/isrecording"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/shared()": {
      "abstract": [
        {
          "text": "Returns an app’s instance of the shared screen recorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
          "text": "RPScreenRecorder"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedRecorder"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/shared()"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startCapture(handler:completionHandler:)": {
      "abstract": [
        {
          "text": "Starts screen and audio capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@RPSampleBufferType",
          "text": "RPSampleBufferType"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startCapture(handler:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithHandler:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(handler:completionHandler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/startcapture(handler:completionhandler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startClipBuffering(completionHandler:)": {
      "abstract": [
        {
          "text": "Starts buffering a clip recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startClipBuffering"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startClipBuffering(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startClipBufferingWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "startClipBuffering(completionHandler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/startclipbuffering(completionhandler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(handler:)": {
      "abstract": [
        {
          "text": "Starts recording the app display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startRecordingWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "startRecording(handler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/startrecording(handler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(withMicrophoneEnabled:handler:)": {
      "abstract": [
        {
          "text": "Starts recording the app’s audio and video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMicrophoneEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(withMicrophoneEnabled:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startRecordingWithMicrophoneEnabled:handler:"
        }
      ],
      "role": "symbol",
      "title": "startRecording(withMicrophoneEnabled:handler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/startrecording(withmicrophoneenabled:handler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopCapture(handler:)": {
      "abstract": [
        {
          "text": "Stops screen capture",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopCapture(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopCaptureWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "stopCapture(handler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/stopcapture(handler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopClipBuffering(completionHandler:)": {
      "abstract": [
        {
          "text": "Stops buffering a clip recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopClipBuffering"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopClipBuffering(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopClipBufferingWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "stopClipBuffering(completionHandler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/stopclipbuffering(completionhandler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(handler:)": {
      "abstract": [
        {
          "text": "Stops the current recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
          "text": "RPPreviewViewController"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopRecordingWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "stopRecording(handler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/stoprecording(handler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(withOutput:completionHandler:)": {
      "abstract": [
        {
          "text": "Stops the current recording and writes the movie to the specified output URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(withOutput:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopRecordingWithOutputURL:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "stopRecording(withOutput:completionHandler:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/stoprecording(withoutput:completionhandler:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate": {
      "abstract": [
        {
          "text": "The protocol you implement to receive notifications from the screen recorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorderDelegate"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorderDelegate"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorderDelegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorderdelegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app": {
      "abstract": [
        {
          "text": "Share screen recordings, or broadcast live audio and video of your app, by adding ReplayKit to your macOS apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Recording and Streaming Your macOS App",
      "type": "topic",
      "url": "/documentation/replaykit/recording-and-streaming-your-macos-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Replay-Sharing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController"
      ],
      "title": "Replay Sharing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Shared-Recorder",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/shared()"
      ],
      "title": "Accessing the Shared Recorder"
    },
    {
      "anchor": "Inspecting-a-Screen-Recorder",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isAvailable",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isRecording",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isMicrophoneEnabled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isCameraEnabled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPreviewView",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPosition",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPCameraPosition",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/delegate",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate"
      ],
      "title": "Inspecting a Screen Recorder"
    },
    {
      "anchor": "Controlling-App-Recording",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(handler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(handler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(withOutput:completionHandler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startCapture(handler:completionHandler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPSampleBufferType",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopCapture(handler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/discardRecording(handler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(withMicrophoneEnabled:handler:)"
      ],
      "title": "Controlling App Recording"
    },
    {
      "anchor": "Performing-Clip-Recording",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startClipBuffering(completionHandler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopClipBuffering(completionHandler:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/exportClip(to:duration:completionHandler:)"
      ],
      "title": "Performing Clip Recording"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RPScreenRecorder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Shared-Recorder",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/shared()"
              ],
              "title": "Accessing the Shared Recorder"
            },
            {
              "anchor": "Inspecting-a-Screen-Recorder",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isAvailable",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isRecording",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isMicrophoneEnabled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/isCameraEnabled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPreviewView",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/cameraPosition",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPCameraPosition",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/delegate",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate"
              ],
              "title": "Inspecting a Screen Recorder"
            },
            {
              "anchor": "Controlling-App-Recording",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(handler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(handler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopRecording(withOutput:completionHandler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startCapture(handler:completionHandler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPSampleBufferType",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopCapture(handler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/discardRecording(handler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startRecording(withMicrophoneEnabled:handler:)"
              ],
              "title": "Controlling App Recording"
            },
            {
              "anchor": "Performing-Clip-Recording",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/startClipBuffering(completionHandler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/stopClipBuffering(completionHandler:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/exportClip(to:duration:completionHandler:)"
              ],
              "title": "Performing Clip Recording"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Replay-Sharing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController"
              ],
              "title": "Replay Sharing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "RPScreenRecorder"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isAvailable/title",
          "value": "available"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "available"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1cameraPreviewView/title",
          "value": "cameraPreviewView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1cameraPreviewView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/title",
          "value": "RPPreviewViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSampleBufferType/title",
          "value": "RPSampleBufferType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSampleBufferType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPSampleBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSampleBufferType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPSampleBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPCameraPosition/title",
          "value": "RPCameraPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPCameraPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPCameraPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPCameraPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPCameraPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isMicrophoneEnabled/title",
          "value": "microphoneEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isMicrophoneEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "microphoneEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startRecording(handler:)/title",
          "value": "startRecordingWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startRecording(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startRecordingWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1discardRecording(handler:)/title",
          "value": "discardRecordingWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1discardRecording(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardRecordingWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/title",
          "value": "RPScreenRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopClipBuffering(completionHandler:)/title",
          "value": "stopClipBufferingWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopClipBuffering(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopClipBufferingWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startCapture(handler:completionHandler:)/title",
          "value": "startCaptureWithHandler:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startCapture(handler:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithHandler:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isCameraEnabled/title",
          "value": "cameraEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isCameraEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1shared()/title",
          "value": "sharedRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startClipBuffering(completionHandler:)/title",
          "value": "startClipBufferingWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startClipBuffering(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startClipBufferingWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startRecording(withMicrophoneEnabled:handler:)/title",
          "value": "startRecordingWithMicrophoneEnabled:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1startRecording(withMicrophoneEnabled:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startRecordingWithMicrophoneEnabled:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopCapture(handler:)/title",
          "value": "stopCaptureWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopCapture(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopCaptureWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1cameraPosition/title",
          "value": "cameraPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1cameraPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopRecording(handler:)/title",
          "value": "stopRecordingWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopRecording(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopRecordingWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1exportClip(to:duration:completionHandler:)/title",
          "value": "exportClipToURL:duration:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1exportClip(to:duration:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "exportClipToURL:duration:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isRecording/title",
          "value": "recording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1isRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/title",
          "value": "RPScreenRecorderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopRecording(withOutput:completionHandler:)/title",
          "value": "stopRecordingWithOutputURL:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder~1stopRecording(withOutput:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopRecordingWithOutputURL:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpscreenrecorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rpscreenrecorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
