{
  "abstract": [
    {
      "text": "A number that represents the number of device types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/MLCDeviceTypeCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCDeviceType@MLCDeviceTypeCount",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MLCDeviceTypeCount"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCDeviceTypeCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MLCDeviceTypeCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MLCDeviceTypeCount"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType": {
      "abstract": [
        {
          "text": "A device type for execution of a neural network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDeviceType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDeviceType"
        }
      ],
      "role": "symbol",
      "title": "MLCDeviceType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/MLCDeviceTypeCount": {
      "abstract": [
        {
          "text": "A number that represents the number of device types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCDeviceTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/MLCDeviceTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCDeviceTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype/mlcdevicetypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/ane": {
      "abstract": [
        {
          "text": "A device type that represents the Apple Neural Engine.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ane"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/ane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDeviceTypeANE"
        }
      ],
      "role": "symbol",
      "title": "MLCDeviceType.ane",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype/ane"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/any": {
      "abstract": [
        {
          "text": "A device type that represents either the CPU or GPU.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDeviceTypeAny"
        }
      ],
      "role": "symbol",
      "title": "MLCDeviceType.any",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype/any"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/cpu": {
      "abstract": [
        {
          "text": "A device type that represents the CPU.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/cpu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDeviceTypeCPU"
        }
      ],
      "role": "symbol",
      "title": "MLCDeviceType.cpu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype/cpu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/gpu": {
      "abstract": [
        {
          "text": "A device type that represents the GPU.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gpu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/gpu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDeviceTypeGPU"
        }
      ],
      "role": "symbol",
      "title": "MLCDeviceType.gpu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevicetype/gpu"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/any",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/cpu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/gpu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDeviceType/ane"
      ],
      "title": "Device Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1cpu/title",
          "value": "MLCDeviceTypeCPU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1cpu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceTypeCPU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType/title",
          "value": "MLCDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1ane/title",
          "value": "MLCDeviceTypeANE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1ane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceTypeANE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1gpu/title",
          "value": "MLCDeviceTypeGPU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1gpu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceTypeGPU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1any/title",
          "value": "MLCDeviceTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDeviceType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDeviceTypeAny"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcdevicetype/mlcdevicetypecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
