{
  "abstract": [
    {
      "text": "Control app launch, execution, and termination.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/app-execution"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "App execution"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app interacts with the system during normal execution by calling system APIs. However, you need to communicate information about how to execute your app before you have access to these API calls. For example, you may need to specify under what conditions your app can launch, the environment that it should launch into, and what should happen when it terminates. You add keys to your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file to manage its execution.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings containing developer-specified task identifiers in reverse URL notation.",
          "type": "text"
        }
      ],
      "ideTitle": "Permitted background task scheduler identifiers",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers",
      "kind": "symbol",
      "name": "BGTaskSchedulerPermittedIdentifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTaskSchedulerPermittedIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "BGTaskSchedulerPermittedIdentifiers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/bgtaskschedulerpermittedidentifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable": {
      "abstract": [
        {
          "text": "The name of the bundle’s executable file.",
          "type": "text"
        }
      ],
      "ideTitle": "Executable file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
      "kind": "symbol",
      "name": "CFBundleExecutable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleExecutable"
        }
      ],
      "role": "symbol",
      "title": "CFBundleExecutable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleexecutable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction": {
      "abstract": [
        {
          "text": "The function to use when dynamically registering a plug-in.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in dynamic registration function name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
      "kind": "symbol",
      "name": "CFPlugInDynamicRegisterFunction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInDynamicRegisterFunction"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInDynamicRegisterFunction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugindynamicregisterfunction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the host loads this plug-in.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in should be registered dynamically",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
      "kind": "symbol",
      "name": "CFPlugInDynamicRegistration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInDynamicRegistration"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInDynamicRegistration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugindynamicregistration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories": {
      "abstract": [
        {
          "text": "The interfaces supported by the plug-in for static registration.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in factory interfaces",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
      "kind": "symbol",
      "name": "CFPlugInFactories",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInFactories"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInFactories",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfpluginfactories"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes": {
      "abstract": [
        {
          "text": "One or more groups of interfaces supported by the plug-in for static registration.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes",
      "kind": "symbol",
      "name": "CFPlugInTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInTypes"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugintypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction": {
      "abstract": [
        {
          "text": "The name of the function to call to unload the plug-in code from memory.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in unload function name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction",
      "kind": "symbol",
      "name": "CFPlugInUnloadFunction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInUnloadFunction"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInUnloadFunction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfpluginunloadfunction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the class that implements the complication data source protocol.",
          "type": "text"
        }
      ],
      "ideTitle": "ClockKit Complication - Principal Class",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
      "kind": "symbol",
      "name": "CLKComplicationPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/clkcomplicationprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "ClockKit Complication - Supported Families",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "name": "CLKComplicationSupportedFamilies",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationSupportedFamilies"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/clkcomplicationsupportedfamilies"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority": {
      "abstract": [
        {
          "text": "An array of the architectures that the app supports, arranged according to their preferred usage.",
          "type": "text"
        }
      ],
      "ideTitle": "Architecture priority",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
      "kind": "symbol",
      "name": "LSArchitecturePriority",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSArchitecturePriority"
        }
      ],
      "role": "symbol",
      "title": "LSArchitecturePriority",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsarchitecturepriority"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app runs only in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Application is background only",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly",
      "kind": "symbol",
      "name": "LSBackgroundOnly",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSBackgroundOnly"
        }
      ],
      "role": "symbol",
      "title": "LSBackgroundOnly",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsbackgroundonly"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment": {
      "abstract": [
        {
          "text": "Environment variables to set before launching the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Environment variables",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment",
      "kind": "symbol",
      "name": "LSEnvironment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSEnvironment"
        }
      ],
      "role": "symbol",
      "title": "LSEnvironment",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsenvironment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is notified when a child process dies.",
          "type": "text"
        }
      ],
      "ideTitle": "Application should get App Died events",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents",
      "kind": "symbol",
      "name": "LSGetAppDiedEvents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSGetAppDiedEvents"
        }
      ],
      "role": "symbol",
      "title": "LSGetAppDiedEvents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsgetappdiedevents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether more than one user can launch the app simultaneously.",
          "type": "text"
        }
      ],
      "ideTitle": "Application prohibits multiple instances",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
      "kind": "symbol",
      "name": "LSMultipleInstancesProhibited",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMultipleInstancesProhibited"
        }
      ],
      "role": "symbol",
      "title": "LSMultipleInstancesProhibited",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsmultipleinstancesprohibited"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to require the execution of the app’s native architecture when multiple architectures are available.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires native environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
      "kind": "symbol",
      "name": "LSRequiresNativeExecution",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresNativeExecution"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresNativeExecution",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresnativeexecution"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip": {
      "abstract": [
        {
          "text": "A collection of keys that an App Clip uses to get additional capabilities.",
          "type": "text"
        }
      ],
      "ideTitle": "App Clip",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip",
      "kind": "symbol",
      "name": "NSAppClip",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppClip"
        }
      ],
      "role": "symbol",
      "title": "NSAppClip",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappclip"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDockTilePlugIn": {
      "abstract": [
        {
          "text": "The name of the app’s plug-in bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Dock Tile plugin path",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDockTilePlugIn",
      "kind": "symbol",
      "name": "NSDockTilePlugIn",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDockTilePlugIn"
        }
      ],
      "role": "symbol",
      "title": "NSDockTilePlugIn",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsdocktileplugin"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityEarlyBoot": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityEarlyBoot",
      "kind": "symbol",
      "name": "NSEndpointSecurityEarlyBoot",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEndpointSecurityEarlyBoot"
        }
      ],
      "role": "symbol",
      "title": "NSEndpointSecurityEarlyBoot",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsendpointsecurityearlyboot"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityRebootRequired": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityRebootRequired",
      "kind": "symbol",
      "name": "NSEndpointSecurityRebootRequired",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEndpointSecurityRebootRequired"
        }
      ],
      "role": "symbol",
      "title": "NSEndpointSecurityRebootRequired",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsendpointsecurityrebootrequired"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the bundle’s main executable class.",
          "type": "text"
        }
      ],
      "ideTitle": "Principal class",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
      "kind": "symbol",
      "name": "NSPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices": {
      "abstract": [
        {
          "text": "The services provided by an app.",
          "type": "text"
        }
      ],
      "ideTitle": "Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
      "kind": "symbol",
      "name": "NSServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServices"
        }
      ],
      "role": "symbol",
      "title": "NSServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the system may terminate the app to log out or shut down more quickly.",
          "type": "text"
        }
      ],
      "ideTitle": "Application can be killed immediately after launch",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
      "kind": "symbol",
      "name": "NSSupportsSuddenTermination",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsSuddenTermination"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsSuddenTermination",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportssuddentermination"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a watchOS app should opt out of automatically launching when its companion iOS app starts playing audio content.",
          "type": "text"
        }
      ],
      "ideTitle": "Opt out of Auto-launch Audio App (Watch)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
      "kind": "symbol",
      "name": "PUICAutoLaunchAudioOptOut",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PUICAutoLaunchAudioOptOut"
        }
      ],
      "role": "symbol",
      "title": "PUICAutoLaunchAudioOptOut",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/puicautolaunchaudiooptout"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app terminates, rather than moves to the background, when the app quits.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "Application does not run in background",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend",
      "kind": "symbol",
      "name": "UIApplicationExitsOnSuspend",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationExitsOnSuspend"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationExitsOnSuspend",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationexitsonsuspend"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems",
      "kind": "symbol",
      "name": "UIApplicationShortcutItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItems"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget": {
      "abstract": [
        {
          "text": "The bundle ID of the widget that’s available as a Home screen quick action in apps that have more than one widget.",
          "type": "text"
        }
      ],
      "ideTitle": "Home Screen Widget",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget",
      "kind": "symbol",
      "name": "UIApplicationShortcutWidget",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutWidget"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutWidget",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutwidget"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes": {
      "abstract": [
        {
          "text": "Services provided by an app that require it to run in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Required background modes",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
      "kind": "symbol",
      "name": "UIBackgroundModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundModes"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uibackgroundmodes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities": {
      "abstract": [
        {
          "text": "The device-related features that your app requires to run.",
          "type": "text"
        }
      ],
      "ideTitle": "Required device capabilities",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
      "kind": "symbol",
      "name": "UIRequiredDeviceCapabilities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiredDeviceCapabilities"
        }
      ],
      "role": "symbol",
      "title": "UIRequiredDeviceCapabilities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequireddevicecapabilities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes": {
      "abstract": [
        {
          "text": "The services a watchOS app provides that require it to continue running in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Required background modes (Watch)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
      "kind": "symbol",
      "name": "WKBackgroundModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKBackgroundModes"
        }
      ],
      "role": "symbol",
      "title": "WKBackgroundModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkbackgroundmodes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName": {
      "abstract": [
        {
          "text": "The name of your watchOS app’s extension delegate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
      "kind": "symbol",
      "name": "WKExtensionDelegateClassName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegateClassName"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegateClassName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkextensiondelegateclassname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "name": "WKPrefersNetworkUponForeground",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPrefersNetworkUponForeground"
        }
      ],
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkprefersnetworkuponforeground"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user can install and run the watchOS app independently of its iOS companion app.",
          "type": "text"
        }
      ],
      "ideTitle": "App can run independently of companion iPhone app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
      "kind": "symbol",
      "name": "WKRunsIndependentlyOfCompanionApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKRunsIndependentlyOfCompanionApp"
        }
      ],
      "role": "symbol",
      "title": "WKRunsIndependentlyOfCompanionApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkrunsindependentlyofcompanionapp"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a watch-only app.",
          "type": "text"
        }
      ],
      "ideTitle": "App is only available as a standalone watchOS app",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
      "kind": "symbol",
      "name": "WKWatchOnly",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchOnly"
        }
      ],
      "role": "symbol",
      "title": "WKWatchOnly",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchonly"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration": {
      "abstract": [
        {
          "text": "Define basic characteristics of a bundle, like its name, type, and version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bundle configuration",
      "type": "topic",
      "url": "/documentation/bundleresources/bundle-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/user-interface": {
      "abstract": [
        {
          "text": "Configure an app’s scenes, storyboards, icons, fonts, and other user interface elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/user-interface",
      "kind": "article",
      "role": "collectionGroup",
      "title": "User interface",
      "type": "topic",
      "url": "/documentation/bundleresources/user-interface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/user-interface"
      ],
      "title": "Core settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Launch",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
      ],
      "title": "Launch"
    },
    {
      "anchor": "Launch-conditions",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Launch conditions"
    },
    {
      "anchor": "Extensions-and-services",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
      ],
      "title": "Extensions and services"
    },
    {
      "anchor": "App-clips",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip"
      ],
      "title": "App clips"
    },
    {
      "anchor": "Background-execution",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly"
      ],
      "title": "Background execution"
    },
    {
      "anchor": "Endpoint-security",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityEarlyBoot",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityRebootRequired"
      ],
      "title": "Endpoint security"
    },
    {
      "anchor": "Plug-in-support",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDockTilePlugIn"
      ],
      "title": "Plug-in support"
    },
    {
      "anchor": "Plug-in-configuration",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction"
      ],
      "title": "Plug-in configuration"
    },
    {
      "anchor": "Termination",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend"
      ],
      "title": "Termination"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Launch",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
              ],
              "title": "Launch"
            },
            {
              "anchor": "Launch-conditions",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiredDeviceCapabilities",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMultipleInstancesProhibited",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSArchitecturePriority",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresNativeExecution",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKRunsIndependentlyOfCompanionApp",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchOnly",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/PUICAutoLaunchAudioOptOut",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Launch conditions"
            },
            {
              "anchor": "Extensions-and-services",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
              ],
              "title": "Extensions and services"
            },
            {
              "anchor": "App-clips",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip"
              ],
              "title": "App clips"
            },
            {
              "anchor": "Background-execution",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly"
              ],
              "title": "Background execution"
            },
            {
              "anchor": "Endpoint-security",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityEarlyBoot",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSEndpointSecurityRebootRequired"
              ],
              "title": "Endpoint security"
            },
            {
              "anchor": "Plug-in-support",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDockTilePlugIn"
              ],
              "title": "Plug-in support"
            },
            {
              "anchor": "Plug-in-configuration",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction"
              ],
              "title": "Plug-in configuration"
            },
            {
              "anchor": "Termination",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend"
              ],
              "title": "Termination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/user-interface"
              ],
              "title": "Core settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/title",
          "value": "PUICAutoLaunchAudioOptOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1PUICAutoLaunchAudioOptOut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PUICAutoLaunchAudioOptOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSGetAppDiedEvents/title",
          "value": "LSGetAppDiedEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSGetAppDiedEvents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSGetAppDiedEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/title",
          "value": "LSMultipleInstancesProhibited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMultipleInstancesProhibited/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMultipleInstancesProhibited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/title",
          "value": "WKExtensionDelegateClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegateClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/title",
          "value": "UIApplicationShortcutWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSEndpointSecurityRebootRequired/title",
          "value": "NSEndpointSecurityRebootRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSEndpointSecurityRebootRequired/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEndpointSecurityRebootRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSEnvironment/title",
          "value": "LSEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/title",
          "value": "UIRequiredDeviceCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiredDeviceCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiredDeviceCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationPrincipalClass/title",
          "value": "CLKComplicationPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKBackgroundModes/title",
          "value": "WKBackgroundModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKBackgroundModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKBackgroundModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSEndpointSecurityEarlyBoot/title",
          "value": "NSEndpointSecurityEarlyBoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSEndpointSecurityEarlyBoot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEndpointSecurityEarlyBoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInTypes/title",
          "value": "CFPlugInTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BGTaskSchedulerPermittedIdentifiers/title",
          "value": "BGTaskSchedulerPermittedIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BGTaskSchedulerPermittedIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskSchedulerPermittedIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/title",
          "value": "CLKComplicationSupportedFamilies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationSupportedFamilies/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationSupportedFamilies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/title",
          "value": "LSRequiresNativeExecution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresNativeExecution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresNativeExecution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDockTilePlugIn/title",
          "value": "NSDockTilePlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDockTilePlugIn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockTilePlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/title",
          "value": "WKRunsIndependentlyOfCompanionApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKRunsIndependentlyOfCompanionApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKRunsIndependentlyOfCompanionApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/title",
          "value": "LSArchitecturePriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSArchitecturePriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSArchitecturePriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleExecutable/title",
          "value": "CFBundleExecutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleExecutable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleExecutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInUnloadFunction/title",
          "value": "CFPlugInUnloadFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInUnloadFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInUnloadFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBackgroundOnly/title",
          "value": "LSBackgroundOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBackgroundOnly/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSBackgroundOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationExitsOnSuspend/title",
          "value": "UIApplicationExitsOnSuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationExitsOnSuspend/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationExitsOnSuspend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInFactories/title",
          "value": "CFPlugInFactories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInFactories/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInFactories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/title",
          "value": "WKWatchOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchOnly/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/title",
          "value": "UIApplicationShortcutItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIBackgroundModes/title",
          "value": "UIBackgroundModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIBackgroundModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegisterFunction/title",
          "value": "CFPlugInDynamicRegisterFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegisterFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInDynamicRegisterFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegistration/title",
          "value": "CFPlugInDynamicRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInDynamicRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsSuddenTermination/title",
          "value": "NSSupportsSuddenTermination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsSuddenTermination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsSuddenTermination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip/title",
          "value": "NSAppClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/title",
          "value": "WKPrefersNetworkUponForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKPrefersNetworkUponForeground/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPrefersNetworkUponForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrincipalClass/title",
          "value": "NSPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrincipalClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-execution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-execution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
