{
  "abstract": [
    {
      "text": "A data structure that represents the root object in a privacy manifest file.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:App_Privacy_Configuration",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "App Privacy Configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List",
    "symbolKind": "struct",
    "title": "App Privacy Configuration"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "App Privacy Configuration",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the keys and values in this object in the privacy manifest for your app or third-party SDK.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the privacy accessed API your app or third-party SDK uses.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Accessed API Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes",
      "kind": "symbol",
      "name": "NSPrivacyAccessedAPITypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyAccessedAPITypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyAccessedAPITypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the categories of private data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Nutrition Label Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app or third-party SDK uses data for tracking.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Tracking Enabled",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking",
      "kind": "symbol",
      "name": "NSPrivacyTracking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyTracking"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyTracking",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacytracking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains": {
      "abstract": [
        {
          "text": "A list of the internet domains your app or third-party SDK uses for tracking.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Tracking Domains",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains",
      "kind": "symbol",
      "name": "NSPrivacyTrackingDomains",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyTrackingDomains"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyTrackingDomains",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacytrackingdomains"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk": {
      "abstract": [
        {
          "text": "Report the data you collect and the required reasons API you use in your app or third-party SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
      "kind": "article",
      "role": "article",
      "title": "Adding a privacy manifest to your app or third-party SDK",
      "type": "topic",
      "url": "/documentation/bundleresources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests": {
      "abstract": [
        {
          "text": "Declare the data collected by your app or by third-party SDKs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
      "kind": "article",
      "role": "article",
      "title": "Describing data use in privacy manifests",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-data-use-in-privacy-manifests"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api": {
      "abstract": [
        {
          "text": "Ensure your use of covered API is consistent with policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
      "kind": "article",
      "role": "article",
      "title": "Describing use of required reason API",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-use-of-required-reason-api"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files": {
      "abstract": [
        {
          "text": "Describe the data your app or third-party SDK collects and the reasons required APIs it uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Privacy manifest files",
      "type": "topic",
      "url": "/documentation/bundleresources/privacy-manifest-files"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Describing-privacy-accessed-API-use",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes"
      ],
      "title": "Describing privacy accessed API use"
    },
    {
      "anchor": "Describing-collected-data",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes"
      ],
      "title": "Describing collected data"
    },
    {
      "anchor": "Declaring-tracking",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains"
      ],
      "title": "Declaring tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Describing-privacy-accessed-API-use",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes"
              ],
              "title": "Describing privacy accessed API use"
            },
            {
              "anchor": "Describing-collected-data",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes"
              ],
              "title": "Describing collected data"
            },
            {
              "anchor": "Declaring-tracking",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains"
              ],
              "title": "Declaring tracking"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
                "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
                "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTrackingDomains/title",
          "value": "NSPrivacyTrackingDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTrackingDomains/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyTrackingDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/title",
          "value": "NSPrivacyCollectedDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTracking/title",
          "value": "NSPrivacyTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes/title",
          "value": "NSPrivacyAccessedAPITypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyAccessedAPITypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
