{
  "abstract": [
    {
      "text": "The root object for a universal links service definition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/applinks"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ul:applinks",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "applinks"
      }
    ],
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applinks"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "applinks"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "14.0.0",
          "name": "defaults",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.Defaults",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "9.0.0",
          "name": "details",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.Details",
              "text": "applinks.Details"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.5.0",
          "name": "substitutionVariables",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.SubstitutionVariables",
              "text": "applinks.SubstitutionVariables"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this object to define the universal links you want to associate with your domain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The object contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The global pattern-matching settings to use as defaults for all universal links in the domain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "defaults",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "code": "Details",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects that define the apps and the universal links they handle for the domain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "details",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Custom variables to use for simplifying complex pattern matches. Each name acts as a variable that the system replaces with each string in the associated string array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "substitutionVariables",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Add the JSON code to your ",
              "type": "text"
            },
            {
              "code": "apple-app-site-association",
              "type": "codeVoice"
            },
            {
              "text": " file along with the app identifiers for the apps that you designate to handle universal links for your domain.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This example code shows a universal links section in an association file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "\"applinks\": {",
            "  \"details\": [",
            "    {",
            "      \"appIDs\": [ \"ABCDE12345.com.example.app\", \"ABCDE12345.com.example.app2\" ],",
            "      \"components\": [",
            "        {",
            "          \"#\": \"no_universal_links\",",
            "          \"exclude\": true,",
            "          \"comment\": \"Matches any URL whose fragment equals no_universal_links and instructs the system not to open it as a universal link\"",
            "        },",
            "        {",
            "          \"/\": \"/buy/*\",",
            "          \"comment\": \"Matches any URL whose path starts with /buy/\"",
            "        },",
            "        {",
            "          \"/\": \"/help/website/*\",",
            "          \"exclude\": true,",
            "          \"comment\": \"Matches any URL whose path starts with /help/website/ and instructs the system not to open it as a universal link\"",
            "        },",
            "        {",
            "          \"/\": \"/help/*\",",
            "          \"?\": { \"articleNumber\": \"????\" },",
            "          \"comment\": \"Matches any URL whose path starts with /help/ and that has a query item with name 'articleNumber' and a value of exactly 4 characters\"",
            "        }",
            "      ]",
            "    }",
            "  ]",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary": {
      "abstract": [
        {
          "text": "An object that defines the default settings to use for universal links pattern matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "role": "symbol",
      "title": "applinks.Defaults",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/defaults-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary": {
      "abstract": [
        {
          "text": "A list of apps and the universal links they handle for a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary": {
      "abstract": [
        {
          "text": "A list of named strings and an associated array of string values that define custom substitution variables to use for URL pattern matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.SubstitutionVariables"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.SubstitutionVariables"
        }
      ],
      "role": "symbol",
      "title": "applinks.SubstitutionVariables",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/substitutionvariables-swift.dictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Universal-links-definitions",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary"
      ],
      "title": "Universal links definitions"
    },
    {
      "anchor": "Pattern-matching-defaults",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary"
      ],
      "title": "Pattern-matching defaults"
    },
    {
      "anchor": "Substitution-variables",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary"
      ],
      "title": "Substitution variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Object"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Universal-links-definitions",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary"
              ],
              "title": "Universal links definitions"
            },
            {
              "anchor": "Pattern-matching-defaults",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary"
              ],
              "title": "Pattern-matching defaults"
            },
            {
              "anchor": "Substitution-variables",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary"
              ],
              "title": "Substitution variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "object "
                  },
                  {
                    "kind": "identifier",
                    "text": "applinks"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "14.0.0",
                "name": "defaults",
                "required": false,
                "type": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Defaults",
                    "text": "applinks.Defaults"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "9.0.0",
                "name": "details",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "["
                  },
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Details",
                    "text": "applinks.Details"
                  },
                  {
                    "kind": "text",
                    "text": "]"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.5.0",
                "name": "substitutionVariables",
                "required": false,
                "type": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/SubstitutionVariables-swift.dictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.SubstitutionVariables",
                    "text": "applinks.SubstitutionVariables"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/title",
          "value": "applinks.Details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1SubstitutionVariables-swift.dictionary/title",
          "value": "applinks.SubstitutionVariables"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1SubstitutionVariables-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.SubstitutionVariables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1SubstitutionVariables-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.SubstitutionVariables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/title",
          "value": "applinks.Defaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/applinks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/applinks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
