{
  "abstract": [
    {
      "text": "Define basic characteristics of a bundle, like its name, type, and version.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Bundle configuration"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file associated with a bundle tells you how to interpret the bundle’s contents. The file describes fundamental features, like whether the bundle contains an app, a framework, or something else. It also includes identifying characteristics of the bundle, like an identifier, a human-readable name, and a version.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor": {
      "abstract": [
        {
          "text": "The name of the bundle’s HTML help file.",
          "type": "text"
        }
      ],
      "ideTitle": "Help file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor",
      "kind": "symbol",
      "name": "CFAppleHelpAnchor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFAppleHelpAnchor"
        }
      ],
      "role": "symbol",
      "title": "CFAppleHelpAnchor",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfapplehelpanchor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the bundle supports the retrieval of localized strings from frameworks.",
          "type": "text"
        }
      ],
      "ideTitle": "Localized resources can be mixed",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations",
      "kind": "symbol",
      "name": "CFBundleAllowMixedLocalizations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleAllowMixedLocalizations"
        }
      ],
      "role": "symbol",
      "title": "CFBundleAllowMixedLocalizations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleallowmixedlocalizations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion": {
      "abstract": [
        {
          "text": "The default language and region for the bundle, as a language ID.",
          "type": "text"
        }
      ],
      "ideTitle": "Localization native development region",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
      "kind": "symbol",
      "name": "CFBundleDevelopmentRegion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDevelopmentRegion"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDevelopmentRegion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledevelopmentregion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDisplayName": {
      "abstract": [
        {
          "text": "The user-visible name for the bundle, used by Siri and visible on the iOS Home screen.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle display name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDisplayName",
      "kind": "symbol",
      "name": "CFBundleDisplayName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDisplayName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDisplayName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledisplayname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder": {
      "abstract": [
        {
          "text": "The name of the folder containing the bundle’s help files.",
          "type": "text"
        }
      ],
      "ideTitle": "Help Book directory name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder",
      "kind": "symbol",
      "name": "CFBundleHelpBookFolder",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleHelpBookFolder"
        }
      ],
      "role": "symbol",
      "title": "CFBundleHelpBookFolder",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlehelpbookfolder"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName": {
      "abstract": [
        {
          "text": "The name of the help file that will be opened in Help Viewer.",
          "type": "text"
        }
      ],
      "ideTitle": "Help Book identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName",
      "kind": "symbol",
      "name": "CFBundleHelpBookName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleHelpBookName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleHelpBookName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlehelpbookname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
      "kind": "symbol",
      "name": "CFBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleInfoDictionaryVersion": {
      "abstract": [
        {
          "text": "The current version of the Information Property List structure.",
          "type": "text"
        }
      ],
      "ideTitle": "InfoDictionary version",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleInfoDictionaryVersion",
      "kind": "symbol",
      "name": "CFBundleInfoDictionaryVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleInfoDictionaryVersion"
        }
      ],
      "role": "symbol",
      "title": "CFBundleInfoDictionaryVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleinfodictionaryversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations": {
      "abstract": [
        {
          "text": "The localizations handled manually by your app.",
          "type": "text"
        }
      ],
      "ideTitle": "Localizations",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
      "kind": "symbol",
      "name": "CFBundleLocalizations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleLocalizations"
        }
      ],
      "role": "symbol",
      "title": "CFBundleLocalizations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlelocalizations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleName": {
      "abstract": [
        {
          "text": "A user-visible short name for the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleName",
      "kind": "symbol",
      "name": "CFBundleName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType": {
      "abstract": [
        {
          "text": "The type of bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle OS Type code",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType",
      "kind": "symbol",
      "name": "CFBundlePackageType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundlePackageType"
        }
      ],
      "role": "symbol",
      "title": "CFBundlePackageType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlepackagetype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleShortVersionString": {
      "abstract": [
        {
          "text": "The release or version number of the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle versions string, short",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleShortVersionString",
      "kind": "symbol",
      "name": "CFBundleShortVersionString",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleShortVersionString"
        }
      ],
      "role": "symbol",
      "title": "CFBundleShortVersionString",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleshortversionstring"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleSpokenName": {
      "abstract": [
        {
          "text": "A replacement for the app name in text-to-speech operations.",
          "type": "text"
        }
      ],
      "ideTitle": "Accessibility Bundle Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleSpokenName",
      "kind": "symbol",
      "name": "CFBundleSpokenName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleSpokenName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleSpokenName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlespokenname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleVersion": {
      "abstract": [
        {
          "text": "The version of the build that identifies an iteration of the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle version",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleVersion",
      "kind": "symbol",
      "name": "CFBundleVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleVersion"
        }
      ],
      "role": "symbol",
      "title": "CFBundleVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType": {
      "abstract": [
        {
          "text": "The category that best describes your app for the App Store.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType",
      "kind": "symbol",
      "name": "LSApplicationCategoryType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSApplicationCategoryType"
        }
      ],
      "role": "symbol",
      "title": "LSApplicationCategoryType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsapplicationcategorytype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in macOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system version",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
      "kind": "symbol",
      "name": "LSMinimumSystemVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersion"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture": {
      "abstract": [
        {
          "text": "The minimum version of macOS required for the app to run on a set of architectures.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system versions, per-architecture",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
      "kind": "symbol",
      "name": "LSMinimumSystemVersionByArchitecture",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersionByArchitecture"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersionByArchitecture",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversionbyarchitecture"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app must run in iOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires iPhone environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
      "kind": "symbol",
      "name": "LSRequiresIPhoneOS",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresIPhoneOS"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresIPhoneOS",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresiphoneos"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in iOS, iPadOS, tvOS, and watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
      "kind": "symbol",
      "name": "MinimumOSVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MinimumOSVersion"
        }
      ],
      "role": "symbol",
      "title": "MinimumOSVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/minimumosversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHumanReadableCopyright": {
      "abstract": [
        {
          "text": "A human-readable copyright notice for the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Copyright (human-readable)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHumanReadableCopyright",
      "kind": "symbol",
      "name": "NSHumanReadableCopyright",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHumanReadableCopyright"
        }
      ],
      "role": "symbol",
      "title": "NSHumanReadableCopyright",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshumanreadablecopyright"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable": {
      "abstract": [
        {
          "text": "A Boolean value that enables the Caps Lock key to switch between Latin and non-Latin input sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable",
      "kind": "symbol",
      "name": "TICapsLockLanguageSwitchCapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TICapsLockLanguageSwitchCapable"
        }
      ],
      "role": "symbol",
      "title": "TICapsLockLanguageSwitchCapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ticapslocklanguageswitchcapable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKAppBundleIdentifier": {
      "abstract": [
        {
          "text": "The bundle ID of the watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKAppBundleIdentifier",
      "kind": "symbol",
      "name": "WKAppBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAppBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "WKAppBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkappbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
      "kind": "symbol",
      "name": "WKApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKCompanionAppBundleIdentifier": {
      "abstract": [
        {
          "text": "The bundle ID of the watchOS app’s companion iOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKCompanionAppBundleIdentifier",
      "kind": "symbol",
      "name": "WKCompanionAppBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKCompanionAppBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "WKCompanionAppBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkcompanionappbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the bundle is a watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp",
      "kind": "symbol",
      "name": "WKWatchKitApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchKitApp"
        }
      ],
      "role": "symbol",
      "title": "WKWatchKitApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchkitapp"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/app-execution": {
      "abstract": [
        {
          "text": "Control app launch, execution, and termination.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/app-execution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App execution",
      "type": "topic",
      "url": "/documentation/bundleresources/app-execution"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/user-interface": {
      "abstract": [
        {
          "text": "Configure an app’s scenes, storyboards, icons, fonts, and other user interface elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/user-interface",
      "kind": "article",
      "role": "collectionGroup",
      "title": "User interface",
      "type": "topic",
      "url": "/documentation/bundleresources/user-interface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/user-interface",
        "doc://com.apple.bundleresources/documentation/BundleResources/app-execution"
      ],
      "title": "Core settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Categorization",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType"
      ],
      "title": "Categorization"
    },
    {
      "anchor": "Identification",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKAppBundleIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKCompanionAppBundleIdentifier"
      ],
      "title": "Identification"
    },
    {
      "anchor": "Naming",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDisplayName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleSpokenName"
      ],
      "title": "Naming"
    },
    {
      "anchor": "Bundle-version",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleShortVersionString",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleInfoDictionaryVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHumanReadableCopyright"
      ],
      "title": "Bundle version"
    },
    {
      "anchor": "Operating-system-version",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
      ],
      "title": "Operating system version"
    },
    {
      "anchor": "Localization",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable"
      ],
      "title": "Localization"
    },
    {
      "anchor": "Help",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder"
      ],
      "title": "Help"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Categorization",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType"
              ],
              "title": "Categorization"
            },
            {
              "anchor": "Identification",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKAppBundleIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKCompanionAppBundleIdentifier"
              ],
              "title": "Identification"
            },
            {
              "anchor": "Naming",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDisplayName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleSpokenName"
              ],
              "title": "Naming"
            },
            {
              "anchor": "Bundle-version",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleShortVersionString",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleInfoDictionaryVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHumanReadableCopyright"
              ],
              "title": "Bundle version"
            },
            {
              "anchor": "Operating-system-version",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
              ],
              "title": "Operating system version"
            },
            {
              "anchor": "Localization",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable"
              ],
              "title": "Localization"
            },
            {
              "anchor": "Help",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder"
              ],
              "title": "Help"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/user-interface",
                "doc://com.apple.bundleresources/documentation/BundleResources/app-execution"
              ],
              "title": "Core settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleShortVersionString/title",
          "value": "CFBundleShortVersionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleShortVersionString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleShortVersionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/title",
          "value": "LSRequiresIPhoneOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresIPhoneOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/title",
          "value": "CFAppleHelpAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFAppleHelpAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/title",
          "value": "MinimumOSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MinimumOSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKAppBundleIdentifier/title",
          "value": "WKAppBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKAppBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAppBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1TICapsLockLanguageSwitchCapable/title",
          "value": "TICapsLockLanguageSwitchCapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1TICapsLockLanguageSwitchCapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TICapsLockLanguageSwitchCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHumanReadableCopyright/title",
          "value": "NSHumanReadableCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHumanReadableCopyright/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHumanReadableCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/title",
          "value": "WKWatchKitApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchKitApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundlePackageType/title",
          "value": "CFBundlePackageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundlePackageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundlePackageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/title",
          "value": "CFBundleHelpBookName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleHelpBookName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleInfoDictionaryVersion/title",
          "value": "CFBundleInfoDictionaryVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleInfoDictionaryVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleInfoDictionaryVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleVersion/title",
          "value": "CFBundleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKCompanionAppBundleIdentifier/title",
          "value": "WKCompanionAppBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKCompanionAppBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKCompanionAppBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleLocalizations/title",
          "value": "CFBundleLocalizations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleLocalizations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleLocalizations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleName/title",
          "value": "CFBundleName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/title",
          "value": "CFBundleHelpBookFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleHelpBookFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/title",
          "value": "LSMinimumSystemVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/title",
          "value": "LSMinimumSystemVersionByArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersionByArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDisplayName/title",
          "value": "CFBundleDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDisplayName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleSpokenName/title",
          "value": "CFBundleSpokenName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleSpokenName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleSpokenName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSApplicationCategoryType/title",
          "value": "LSApplicationCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSApplicationCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSApplicationCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleAllowMixedLocalizations/title",
          "value": "CFBundleAllowMixedLocalizations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleAllowMixedLocalizations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleAllowMixedLocalizations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDevelopmentRegion/title",
          "value": "CFBundleDevelopmentRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDevelopmentRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDevelopmentRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIdentifier/title",
          "value": "CFBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/bundle-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/bundle-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
