{
  "abstract": [
    {
      "text": "Regulate documents, URLs, and other kinds of data movement and storage.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/data-and-storage"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Data and storage"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system needs to know what kinds of data your app stores, provides, or consumes. Add keys to your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that declare your app’s data management capabilities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles": {
      "abstract": [
        {
          "text": "Describes the files or directories the app installs on the system.",
          "type": "text"
        }
      ],
      "ideTitle": "Installation files",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
      "kind": "symbol",
      "name": "APFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFiles"
        }
      ],
      "role": "symbol",
      "title": "APFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL": {
      "abstract": [
        {
          "text": "The base path to the files or folders that the app installs.",
          "type": "text"
        }
      ],
      "ideTitle": "Installation directory base file URL",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
      "kind": "symbol",
      "name": "APInstallerURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APInstallerURL"
        }
      ],
      "role": "symbol",
      "title": "APInstallerURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apinstallerurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAInitialDownloadRestrictions": {
      "abstract": [
        {
          "text": "The restrictions that apply to the set of assets that download immediately after app installation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAInitialDownloadRestrictions",
      "kind": "symbol",
      "name": "BAInitialDownloadRestrictions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAInitialDownloadRestrictions"
        }
      ],
      "role": "symbol",
      "title": "BAInitialDownloadRestrictions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/bainitialdownloadrestrictions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAManifestURL": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAManifestURL",
      "kind": "symbol",
      "name": "BAManifestURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAManifestURL"
        }
      ],
      "role": "symbol",
      "title": "BAManifestURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/bamanifesturl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAMaxInstallSize": {
      "abstract": [
        {
          "text": "The combined size, on disk, of your app bundle and the assets that download immediately after app installation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAMaxInstallSize",
      "kind": "symbol",
      "name": "BAMaxInstallSize",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAMaxInstallSize"
        }
      ],
      "role": "symbol",
      "title": "BAMaxInstallSize",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/bamaxinstallsize"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes": {
      "abstract": [
        {
          "text": "The document types supported by the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Document types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
      "kind": "symbol",
      "name": "CFBundleDocumentTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDocumentTypes"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDocumentTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes": {
      "abstract": [
        {
          "text": "A list of URL schemes (http, ftp, and so on) supported by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "URL types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes",
      "kind": "symbol",
      "name": "CFBundleURLTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleURLTypes"
        }
      ],
      "role": "symbol",
      "title": "CFBundleURLTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleurltypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "name": "CKSharingSupported",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingSupported"
        }
      ],
      "role": "symbol",
      "title": "CKSharingSupported",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cksharingsupported"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app’s resources files should be mapped into memory.",
          "type": "text"
        }
      ],
      "ideTitle": "Resources should be file-mapped",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
      "kind": "symbol",
      "name": "CSResourcesFileMapped",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSResourcesFileMapped"
        }
      ],
      "role": "symbol",
      "title": "CSResourcesFileMapped",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/csresourcesfilemapped"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBundleContainsCoreMLmlmodelc": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app contains a Core ML model to optimize loading the model.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle contains CoreML models",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBundleContainsCoreMLmlmodelc",
      "kind": "symbol",
      "name": "LSBundleContainsCoreMLmlmodelc",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSBundleContainsCoreMLmlmodelc"
        }
      ],
      "role": "symbol",
      "title": "LSBundleContainsCoreMLmlmodelc",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsbundlecontainscoremlmlmodelc"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the files this app creates are quarantined by default.",
          "type": "text"
        }
      ],
      "ideTitle": "File quarantine enabled",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled",
      "kind": "symbol",
      "name": "LSFileQuarantineEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSFileQuarantineEnabled"
        }
      ],
      "role": "symbol",
      "title": "LSFileQuarantineEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsfilequarantineenabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app may open the original document from a file provider, rather than a copy of the document.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports opening documents in place",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace",
      "kind": "symbol",
      "name": "LSSupportsOpeningDocumentsInPlace",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSSupportsOpeningDocumentsInPlace"
        }
      ],
      "role": "symbol",
      "title": "LSSupportsOpeningDocumentsInPlace",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lssupportsopeningdocumentsinplace"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint": {
      "abstract": [
        {
          "text": "The URL where Private Click Measurement and SKAdNetwork send attribution information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint",
      "kind": "symbol",
      "name": "NSAdvertisingAttributionReportEndpoint",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAdvertisingAttributionReportEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NSAdvertisingAttributionReportEndpoint",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsadvertisingattributionreportendpoint"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity": {
      "abstract": [
        {
          "text": "A description of changes made to the default security for HTTP connections.",
          "type": "text"
        }
      ],
      "ideTitle": "App Transport Security Settings",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
      "kind": "symbol",
      "name": "NSAppTransportSecurity",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppTransportSecurity"
        }
      ],
      "role": "symbol",
      "title": "NSAppTransportSecurity",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsapptransportsecurity"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices": {
      "abstract": [
        {
          "text": "Bonjour service types browsed by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Bonjour services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
      "kind": "symbol",
      "name": "NSBonjourServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBonjourServices"
        }
      ],
      "role": "symbol",
      "title": "NSBonjourServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsbonjourservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system should download documents before handing them over to the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents",
      "kind": "symbol",
      "name": "NSDownloadsUbiquitousContents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownloadsUbiquitousContents"
        }
      ],
      "role": "symbol",
      "title": "NSDownloadsUbiquitousContents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsdownloadsubiquitouscontents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSJavaRoot": {
      "abstract": [
        {
          "text": "The root directory for the app’s Java class files.",
          "type": "text"
        }
      ],
      "ideTitle": "Java root directory",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSJavaRoot",
      "kind": "symbol",
      "name": "NSJavaRoot",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSJavaRoot"
        }
      ],
      "role": "symbol",
      "title": "NSJavaRoot",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsjavaroot"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app continues working if the system purges the local storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
      "kind": "symbol",
      "name": "NSSupportsPurgeableLocalStorage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsPurgeableLocalStorage"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsPurgeableLocalStorage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportspurgeablelocalstorage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app shares files.",
          "type": "text"
        }
      ],
      "ideTitle": "Application supports iTunes file sharing",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
      "kind": "symbol",
      "name": "UIFileSharingEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFileSharingEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIFileSharingEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uifilesharingenabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a document-based app.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Document Browser",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
      "kind": "symbol",
      "name": "UISupportsDocumentBrowser",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsDocumentBrowser"
        }
      ],
      "role": "symbol",
      "title": "UISupportsDocumentBrowser",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportsdocumentbrowser"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations": {
      "abstract": [
        {
          "text": "The uniform type identifiers owned and exported by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Exported Type UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
      "kind": "symbol",
      "name": "UTExportedTypeDeclarations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTExportedTypeDeclarations"
        }
      ],
      "role": "symbol",
      "title": "UTExportedTypeDeclarations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTImportedTypeDeclarations": {
      "abstract": [
        {
          "text": "The uniform type identifiers inherently supported, but not owned, by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Imported Type UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTImportedTypeDeclarations",
      "kind": "symbol",
      "name": "UTImportedTypeDeclarations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTImportedTypeDeclarations"
        }
      ],
      "role": "symbol",
      "title": "UTImportedTypeDeclarations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utimportedtypedeclarations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/app-services": {
      "abstract": [
        {
          "text": "Configure services provided by the app, like support for giving directions or using game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/app-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App services",
      "type": "topic",
      "url": "/documentation/bundleresources/app-services"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/kernel-and-drivers": {
      "abstract": [
        {
          "text": "Configure device drivers provided by the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/kernel-and-drivers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Kernel and drivers",
      "type": "topic",
      "url": "/documentation/bundleresources/kernel-and-drivers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources": {
      "abstract": [
        {
          "text": "Control an app’s access to protected system services and user data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Protected resources",
      "type": "topic",
      "url": "/documentation/bundleresources/protected-resources"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
        "doc://com.apple.bundleresources/documentation/BundleResources/app-services",
        "doc://com.apple.bundleresources/documentation/BundleResources/kernel-and-drivers"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Documents",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
      ],
      "title": "Documents"
    },
    {
      "anchor": "URL-schemes",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes"
      ],
      "title": "URL schemes"
    },
    {
      "anchor": "Universal-type-identifiers",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTImportedTypeDeclarations"
      ],
      "title": "Universal type identifiers"
    },
    {
      "anchor": "Network",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Network"
    },
    {
      "anchor": "Background-downloads",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAInitialDownloadRestrictions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAMaxInstallSize",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAManifestURL"
      ],
      "title": "Background downloads"
    },
    {
      "anchor": "Storage",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
      ],
      "title": "Storage"
    },
    {
      "anchor": "CoreML-models",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBundleContainsCoreMLmlmodelc"
      ],
      "title": "CoreML models"
    },
    {
      "anchor": "Java",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSJavaRoot"
      ],
      "title": "Java"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Documents",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
              ],
              "title": "Documents"
            },
            {
              "anchor": "URL-schemes",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleURLTypes"
              ],
              "title": "URL schemes"
            },
            {
              "anchor": "Universal-type-identifiers",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTImportedTypeDeclarations"
              ],
              "title": "Universal type identifiers"
            },
            {
              "anchor": "Network",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported"
              ],
              "title": "Network"
            },
            {
              "anchor": "Background-downloads",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAInitialDownloadRestrictions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAMaxInstallSize",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BAManifestURL"
              ],
              "title": "Background downloads"
            },
            {
              "anchor": "Storage",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
              ],
              "title": "Storage"
            },
            {
              "anchor": "CoreML-models",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBundleContainsCoreMLmlmodelc"
              ],
              "title": "CoreML models"
            },
            {
              "anchor": "Java",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSJavaRoot"
              ],
              "title": "Java"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
                "doc://com.apple.bundleresources/documentation/BundleResources/app-services",
                "doc://com.apple.bundleresources/documentation/BundleResources/kernel-and-drivers"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTImportedTypeDeclarations/title",
          "value": "UTImportedTypeDeclarations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTImportedTypeDeclarations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTImportedTypeDeclarations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/title",
          "value": "NSAppTransportSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppTransportSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIFileSharingEnabled/title",
          "value": "UIFileSharingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIFileSharingEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFileSharingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSFileQuarantineEnabled/title",
          "value": "LSFileQuarantineEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSFileQuarantineEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSFileQuarantineEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/title",
          "value": "NSDownloadsUbiquitousContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownloadsUbiquitousContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsDocumentBrowser/title",
          "value": "UISupportsDocumentBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsDocumentBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsDocumentBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsPurgeableLocalStorage/title",
          "value": "NSSupportsPurgeableLocalStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsPurgeableLocalStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsPurgeableLocalStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAManifestURL/title",
          "value": "BAManifestURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAManifestURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAManifestURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleURLTypes/title",
          "value": "CFBundleURLTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleURLTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleURLTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAdvertisingAttributionReportEndpoint/title",
          "value": "NSAdvertisingAttributionReportEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAdvertisingAttributionReportEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAdvertisingAttributionReportEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSJavaRoot/title",
          "value": "NSJavaRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSJavaRoot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSJavaRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAMaxInstallSize/title",
          "value": "BAMaxInstallSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAMaxInstallSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAMaxInstallSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/title",
          "value": "APFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APInstallerURL/title",
          "value": "APInstallerURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APInstallerURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APInstallerURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/title",
          "value": "CFBundleDocumentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDocumentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CKSharingSupported/title",
          "value": "CKSharingSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CKSharingSupported/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBundleContainsCoreMLmlmodelc/title",
          "value": "LSBundleContainsCoreMLmlmodelc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBundleContainsCoreMLmlmodelc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSBundleContainsCoreMLmlmodelc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSSupportsOpeningDocumentsInPlace/title",
          "value": "LSSupportsOpeningDocumentsInPlace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSSupportsOpeningDocumentsInPlace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSSupportsOpeningDocumentsInPlace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSBonjourServices/title",
          "value": "NSBonjourServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSBonjourServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBonjourServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/title",
          "value": "UTExportedTypeDeclarations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTExportedTypeDeclarations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAInitialDownloadRestrictions/title",
          "value": "BAInitialDownloadRestrictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BAInitialDownloadRestrictions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAInitialDownloadRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CSResourcesFileMapped/title",
          "value": "CSResourcesFileMapped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CSResourcesFileMapped/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSResourcesFileMapped"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/data-and-storage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/data-and-storage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
