{
  "abstract": [
    {
      "text": "Declare the data collected by your app or by third-party SDKs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Describing data use in privacy manifests"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Record the categories of data that your app or third-party SDK collects about the person using the app, and the reasons it collects the data. App developers can use Xcode to create a privacy report, summarizing the information about collected data in their app and the third-party SDKs the app links to.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Describe-the-data-your-app-or-third-party-SDK-collects",
          "level": 3,
          "text": "Describe the data your app or third-party SDK collects",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For each type of data your app or third-party SDK collects, add a dictionary to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array in your privacy information file. Add the following keys to the dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that identifies the type of data your app or third-party SDK collects. Choose the value from the list of data types below that matches the data your app or third-party SDK collects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean that indicates whether your app or third-party SDK links this data type to the user’s identity. For more information, see Data linked to the user in ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://developer.apple.com/app-store/app-privacy-details/#linked-data",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean that indicates whether your app or third-party SDK uses this data type to track.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of strings that lists the reasons your app or third-party SDK collects the data. Choose values from the list of purposes below that match the reasons your app or third-party SDK collects this data type.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode won’t generate a privacy report correctly if you define your own collected data types for the ",
              "type": "text"
            },
            {
              "code": "NSPrivacyCollectedDataType",
              "type": "codeVoice"
            },
            {
              "text": " key, or provide your own reasons for the ",
              "type": "text"
            },
            {
              "code": "NSPrivacyCollectedDataTypePurposes",
              "type": "codeVoice"
            },
            {
              "text": " key. Use values listed in the documentation for the keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-your-apps-privacy-report",
          "level": 3,
          "text": "Create your app’s privacy report",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode can create a privacy report by aggregating the privacy manifests from your app and the third-party SDKs it links to. Use the privacy report to better understand all of the data collected by your app and whether it tracks. Create the privacy report for your app by doing the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open your project in Xcode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Product > Archive. Xcode creates the archive and reveals it in the organizer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Control-click the archive in the organizer and choose Generate Privacy Report.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose a location to save the privacy report.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Switch to Finder.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Navigate to the location where you saved the privacy report, and double-click to open the report in Preview.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The privacy report is organized in a similar way to Privacy Nutrition Labels. Refer to this report when you provide your app’s privacy details in App Store Connect. For more information on providing your app’s privacy details, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-store/app-privacy-details/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the categories of private data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Nutrition Label Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType": {
      "abstract": [
        {
          "text": "A string that identifies the type of data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Collected Data Type",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataType"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether your app or third-party SDK links this data type to the user’s identity.",
          "type": "text"
        }
      ],
      "ideTitle": "Linked to User",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypeLinked",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypeLinked"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypeLinked",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypelinked"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes": {
      "abstract": [
        {
          "text": "An array of strings that identify reasons your app or third-party SDK collects private data.",
          "type": "text"
        }
      ],
      "ideTitle": "Collection Purposes",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypePurposes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypePurposes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypePurposes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypepurposes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether your app or third-party SDK uses this data type to track.",
          "type": "text"
        }
      ],
      "ideTitle": "Used for Tracking",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypeTracking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypeTracking"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypeTracking",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypetracking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk": {
      "abstract": [
        {
          "text": "Report the data you collect and the required reasons API you use in your app or third-party SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
      "kind": "article",
      "role": "article",
      "title": "Adding a privacy manifest to your app or third-party SDK",
      "type": "topic",
      "url": "/documentation/bundleresources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api": {
      "abstract": [
        {
          "text": "Ensure your use of covered API is consistent with policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
      "kind": "article",
      "role": "article",
      "title": "Describing use of required reason API",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-use-of-required-reason-api"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files": {
      "abstract": [
        {
          "text": "Describe the data your app or third-party SDK collects and the reasons required APIs it uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/privacy-manifest-files",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Privacy manifest files",
      "type": "topic",
      "url": "/documentation/bundleresources/privacy-manifest-files"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/app-store/app-privacy-details/": {
      "identifier": "https://developer.apple.com/app-store/app-privacy-details/",
      "title": "App privacy details on the App Store",
      "titleInlineContent": [
        {
          "text": "App privacy details on the App Store",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/app-privacy-details/"
    },
    "https://developer.apple.com/app-store/app-privacy-details/#linked-data": {
      "identifier": "https://developer.apple.com/app-store/app-privacy-details/#linked-data",
      "title": "App privacy details on the App Store",
      "titleInlineContent": [
        {
          "text": "App privacy details on the App Store",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/app-privacy-details/#linked-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/adding-a-privacy-manifest-to-your-app-or-third-party-sdk",
                "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeLinked/title",
          "value": "NSPrivacyCollectedDataTypeLinked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeLinked/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypeLinked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/title",
          "value": "NSPrivacyCollectedDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/title",
          "value": "NSPrivacyCollectedDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeTracking/title",
          "value": "NSPrivacyCollectedDataTypeTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypeTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/title",
          "value": "NSPrivacyCollectedDataTypePurposes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypePurposes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/describing-data-use-in-privacy-manifests"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/describing-data-use-in-privacy-manifests"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
