{
  "abstract": [
    {
      "text": "Configure device drivers provided by the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/kernel-and-drivers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Kernel and drivers"
  },
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities": {
      "abstract": [
        {
          "text": "One or more groups of attributes that tell the system about the devices your driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities",
      "kind": "symbol",
      "name": "IOKitPersonalities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOKitPersonalities"
        }
      ],
      "role": "symbol",
      "title": "IOKitPersonalities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iokitpersonalities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPCITunnelCompatible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your driver supports Thunderbolt devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPCITunnelCompatible",
      "kind": "symbol",
      "name": "IOPCITunnelCompatible",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOPCITunnelCompatible"
        }
      ],
      "role": "symbol",
      "title": "IOPCITunnelCompatible",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iopcitunnelcompatible"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleCompatibleVersion": {
      "abstract": [
        {
          "text": "The backward limit of compatibility for the current driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleCompatibleVersion",
      "kind": "symbol",
      "name": "OSBundleCompatibleVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSBundleCompatibleVersion"
        }
      ],
      "role": "symbol",
      "title": "OSBundleCompatibleVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/osbundlecompatibleversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleLibraries": {
      "abstract": [
        {
          "text": "The drivers that the system must load before your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleLibraries",
      "kind": "symbol",
      "name": "OSBundleLibraries",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSBundleLibraries"
        }
      ],
      "role": "symbol",
      "title": "OSBundleLibraries",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/osbundlelibraries"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/app-services": {
      "abstract": [
        {
          "text": "Configure services provided by the app, like support for giving directions or using game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/app-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App services",
      "type": "topic",
      "url": "/documentation/bundleresources/app-services"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/data-and-storage": {
      "abstract": [
        {
          "text": "Regulate documents, URLs, and other kinds of data movement and storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/data-and-storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data and storage",
      "type": "topic",
      "url": "/documentation/bundleresources/data-and-storage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources": {
      "abstract": [
        {
          "text": "Control an app’s access to protected system services and user data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Protected resources",
      "type": "topic",
      "url": "/documentation/bundleresources/protected-resources"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
        "doc://com.apple.bundleresources/documentation/BundleResources/data-and-storage",
        "doc://com.apple.bundleresources/documentation/BundleResources/app-services"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Driver-personalities",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities"
      ],
      "title": "Driver personalities"
    },
    {
      "anchor": "Kext-dependencies",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleCompatibleVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleLibraries"
      ],
      "title": "Kext dependencies"
    },
    {
      "anchor": "Thunderbolt-compatibility",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPCITunnelCompatible"
      ],
      "title": "Thunderbolt compatibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Driver-personalities",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities"
              ],
              "title": "Driver personalities"
            },
            {
              "anchor": "Kext-dependencies",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleCompatibleVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/OSBundleLibraries"
              ],
              "title": "Kext dependencies"
            },
            {
              "anchor": "Thunderbolt-compatibility",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPCITunnelCompatible"
              ],
              "title": "Thunderbolt compatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/protected-resources",
                "doc://com.apple.bundleresources/documentation/BundleResources/data-and-storage",
                "doc://com.apple.bundleresources/documentation/BundleResources/app-services"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1OSBundleLibraries/title",
          "value": "OSBundleLibraries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1OSBundleLibraries/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSBundleLibraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPCITunnelCompatible/title",
          "value": "IOPCITunnelCompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPCITunnelCompatible/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPCITunnelCompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOKitPersonalities/title",
          "value": "IOKitPersonalities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOKitPersonalities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOKitPersonalities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1OSBundleCompatibleVersion/title",
          "value": "OSBundleCompatibleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1OSBundleCompatibleVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSBundleCompatibleVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/kernel-and-drivers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/kernel-and-drivers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
