{
  "abstract": [
    {
      "text": "Extend the capabilities of macOS from user space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/system-extensions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "System Extensions"
  },
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.device": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the driver provides a HID-related service to the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.device",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.hid.device",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.hid.device"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.hid.device",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.hid.device"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.eventservice": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the driver provides a HID-related event service to the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.eventservice",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.hid.eventservice",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.hid.eventservice"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.hid.eventservice",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.hid.eventservice"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.hid": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the driver communicates with human interface devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.hid",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.transport.hid",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.transport.hid"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.transport.hid",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.hid"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client": {
      "abstract": [
        {
          "text": "The entitlement required to monitor system events for potentially malicious activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client",
      "kind": "symbol",
      "name": "com.apple.developer.endpoint-security.client",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.endpoint-security.client"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.endpoint-security.client",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.endpoint-security.client"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.hid.virtual.device": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the driver creates a virtual HID device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.hid.virtual.device",
      "kind": "symbol",
      "name": "com.apple.developer.hid.virtual.device",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.hid.virtual.device"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.hid.virtual.device",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.hid.virtual.device"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app has permission to activate or deactivate system extensions.",
          "type": "text"
        }
      ],
      "ideTitle": "System Extension Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install",
      "kind": "symbol",
      "name": "com.apple.developer.system-extension.install",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.system-extension.install"
        }
      ],
      "role": "symbol",
      "title": "System Extension Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.system-extension.install"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether other development teams may distribute a system extension you create.",
          "type": "text"
        }
      ],
      "ideTitle": "System Extension Redistributable Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable",
      "kind": "symbol",
      "name": "com.apple.developer.system-extension.redistributable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.system-extension.redistributable"
        }
      ],
      "role": "symbol",
      "title": "System Extension Redistributable Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.system-extension.redistributable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/driverkit": {
      "abstract": [
        {
          "text": "Develop device drivers in macOS and iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/driverkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DriverKit",
      "type": "topic",
      "url": "/documentation/bundleresources/driverkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/driverkit"
      ],
      "title": "System"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Endpoint-Security",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client"
      ],
      "title": "Endpoint Security"
    },
    {
      "anchor": "Human-Interface-Device-Drivers",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.device",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.eventservice",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.hid",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.hid.virtual.device"
      ],
      "title": "Human Interface Device Drivers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Endpoint-Security",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client"
              ],
              "title": "Endpoint Security"
            },
            {
              "anchor": "Human-Interface-Device-Drivers",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.device",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.hid.eventservice",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.hid",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.hid.virtual.device"
              ],
              "title": "Human Interface Device Drivers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/driverkit"
              ],
              "title": "System"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.hid.eventservice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.hid.eventservice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.system-extension.redistributable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.system-extension.redistributable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.endpoint-security.client/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.endpoint-security.client"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.system-extension.install/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.system-extension.install"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.hid/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.hid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.hid.device/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.hid.device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.hid.virtual.device/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.hid.virtual.device"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/system-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/system-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
