{
  "abstract": [
    {
      "text": "Configure an app’s scenes, storyboards, icons, fonts, and other user interface elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/user-interface"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "User interface"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You define the user interface that your app presents during normal operation with a combination of code and storyboards. However, the system needs to know a few things about your app’s user interface before execution begins. For example, on some platforms, you have to specify what device orientations your app supports and what the system should display while your app launches. You add keys to your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file to control certain aspects of its user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ATSApplicationFontsPath": {
      "abstract": [
        {
          "text": "The location of a font file or folder of fonts in the bundle’s Resources folder.",
          "type": "text"
        }
      ],
      "ideTitle": "Application fonts resource path",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ATSApplicationFontsPath",
      "kind": "symbol",
      "name": "ATSApplicationFontsPath",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATSApplicationFontsPath"
        }
      ],
      "role": "symbol",
      "title": "ATSApplicationFontsPath",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/atsapplicationfontspath"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile": {
      "abstract": [
        {
          "text": "The file containing the bundle’s icon.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
      "kind": "symbol",
      "name": "CFBundleIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconFile"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles": {
      "abstract": [
        {
          "text": "The names of the bundle’s icon image files.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
      "kind": "symbol",
      "name": "CFBundleIconFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconFiles"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName": {
      "abstract": [
        {
          "text": "The name of the asset that represents the app icon.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName",
      "kind": "symbol",
      "name": "CFBundleIconName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons": {
      "abstract": [
        {
          "text": "Information about all of the icons used by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files (iOS 5)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
      "kind": "symbol",
      "name": "CFBundleIcons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIcons"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIcons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy": {
      "abstract": [
        {
          "text": "The preferred system action when an external GPU is connected from the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
      "kind": "symbol",
      "name": "GPUEjectPolicy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GPUEjectPolicy"
        }
      ],
      "role": "symbol",
      "title": "GPUEjectPolicy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gpuejectpolicy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy": {
      "abstract": [
        {
          "text": "The app’s preference for whether it wants to use external graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy",
      "kind": "symbol",
      "name": "GPUSelectionPolicy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GPUSelectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "GPUSelectionPolicy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gpuselectionpolicy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is an agent app that runs in the background and doesn’t appear in the Dock.",
          "type": "text"
        }
      ],
      "ideTitle": "Application is agent (UIElement)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
      "kind": "symbol",
      "name": "LSUIElement",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIElement"
        }
      ],
      "role": "symbol",
      "title": "LSUIElement",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuielement"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode": {
      "abstract": [
        {
          "text": "The initial user-interface mode for the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Application UI Presentation Mode",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
      "kind": "symbol",
      "name": "LSUIPresentationMode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIPresentationMode"
        }
      ],
      "role": "symbol",
      "title": "LSUIPresentationMode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuipresentationmode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName": {
      "abstract": [
        {
          "text": "The name of a color in an asset catalog to use for a target’s global accent color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
      "kind": "symbol",
      "name": "NSAccentColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccentColorName"
        }
      ],
      "role": "symbol",
      "title": "NSAccentColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccentcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Cocoa app supports high-resolution displays.",
          "type": "text"
        }
      ],
      "ideTitle": "High Resolution Capable",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable",
      "kind": "symbol",
      "name": "NSHighResolutionCapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHighResolutionCapable"
        }
      ],
      "role": "symbol",
      "title": "NSHighResolutionCapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshighresolutioncapable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile": {
      "abstract": [
        {
          "text": "The name of an app’s main user interface file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main nib file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
      "kind": "symbol",
      "name": "NSMainNibFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainNibFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainNibFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainnibfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of an app’s storyboard resource file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
      "kind": "symbol",
      "name": "NSMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "NSMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsmainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconFile": {
      "abstract": [
        {
          "text": "The name of an image file used to represent a preference pane in the System Preferences app.",
          "type": "text"
        }
      ],
      "ideTitle": "Preference Pane icon file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconFile",
      "kind": "symbol",
      "name": "NSPrefPaneIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefPaneIconFile"
        }
      ],
      "role": "symbol",
      "title": "NSPrefPaneIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprefpaneiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconLabel": {
      "abstract": [
        {
          "text": "The name of a preference pane displayed beneath the preference pane icon in the System Preferences app.",
          "type": "text"
        }
      ],
      "ideTitle": "Preference Pane icon label",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconLabel",
      "kind": "symbol",
      "name": "NSPrefPaneIconLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefPaneIconLabel"
        }
      ],
      "role": "symbol",
      "title": "NSPrefPaneIconLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprefpaneiconlabel"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app prefers to run in compatibility mode when necessary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
      "kind": "symbol",
      "name": "NSPrefersDisplaySafeAreaCompatibilityMode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefersDisplaySafeAreaCompatibilityMode"
        }
      ],
      "role": "symbol",
      "title": "NSPrefersDisplaySafeAreaCompatibilityMode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprefersdisplaysafeareacompatibilitymode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether an OpenGL app may utilize the integrated GPU.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Automatic Graphics Switching",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
      "kind": "symbol",
      "name": "NSSupportsAutomaticGraphicsSwitching",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsAutomaticGraphicsSwitching"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsAutomaticGraphicsSwitching",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportsautomaticgraphicsswitching"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName": {
      "abstract": [
        {
          "text": "The name of a color in an asset catalog to use for a widget’s configuration interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName",
      "kind": "symbol",
      "name": "NSWidgetBackgroundColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWidgetBackgroundColorName"
        }
      ],
      "role": "symbol",
      "title": "NSWidgetBackgroundColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nswidgetbackgroundcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a Quick Look app’s generator can be run in threads other than the main thread.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look needs to be run in main thread",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
      "kind": "symbol",
      "name": "QLNeedsToBeRunInMainThread",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLNeedsToBeRunInMainThread"
        }
      ],
      "role": "symbol",
      "title": "QLNeedsToBeRunInMainThread",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlneedstoberuninmainthread"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight": {
      "abstract": [
        {
          "text": "A hint at the height, in points, of a Quick Look app’s previews.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look preview height",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight",
      "kind": "symbol",
      "name": "QLPreviewHeight",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewHeight"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewHeight",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlpreviewheight"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth": {
      "abstract": [
        {
          "text": "A hint at the width, in points, of a Quick Look app’s previews.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look preview width",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
      "kind": "symbol",
      "name": "QLPreviewWidth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewWidth"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewWidth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlpreviewwidth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a Quick Look app’s  generator can handle concurrent thumbnail and preview requests.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look supports concurrent requests",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
      "kind": "symbol",
      "name": "QLSupportsConcurrentRequests",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLSupportsConcurrentRequests"
        }
      ],
      "role": "symbol",
      "title": "QLSupportsConcurrentRequests",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlsupportsconcurrentrequests"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize": {
      "abstract": [
        {
          "text": "The minimum size, in points, along one dimension of thumbnails for a Quick Look app’s generator.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look thumbnail minimum size",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize",
      "kind": "symbol",
      "name": "QLThumbnailMinimumSize",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailMinimumSize"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailMinimumSize",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlthumbnailminimumsize"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppFonts": {
      "abstract": [
        {
          "text": "App-specific font files located in the bundle and that the system loads at runtime.",
          "type": "text"
        }
      ],
      "ideTitle": "Fonts provided by application",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppFonts",
      "kind": "symbol",
      "name": "UIAppFonts",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppFonts"
        }
      ],
      "role": "symbol",
      "title": "UIAppFonts",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiappfonts"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app supports HDR mode on Apple TV 4K.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports HDR color mode",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
      "kind": "symbol",
      "name": "UIAppSupportsHDR",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppSupportsHDR"
        }
      ],
      "role": "symbol",
      "title": "UIAppSupportsHDR",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiappsupportshdr"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole": {
      "abstract": [
        {
          "text": "The preferred initial scene session role for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
      "kind": "symbol",
      "name": "UIApplicationPreferredDefaultSceneSessionRole",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationPreferredDefaultSceneSessionRole"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationPreferredDefaultSceneSessionRole",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationpreferreddefaultscenesessionrole"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsIndirectInputEvents": {
      "abstract": [
        {
          "text": "A Boolean value indicating that the app generally supports indirect input mechanisms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsIndirectInputEvents",
      "kind": "symbol",
      "name": "UIApplicationSupportsIndirectInputEvents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSupportsIndirectInputEvents"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSupportsIndirectInputEvents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationsupportsindirectinputevents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIInterfaceOrientation": {
      "abstract": [
        {
          "text": "The initial orientation of the app’s user interface.",
          "type": "text"
        }
      ],
      "ideTitle": "Initial interface orientation",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIInterfaceOrientation",
      "kind": "symbol",
      "name": "UIInterfaceOrientation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiinterfaceorientation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages": {
      "abstract": [
        {
          "text": "A dictionary containing information about launch images.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages",
      "kind": "symbol",
      "name": "UILaunchImages",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImages"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImages",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen": {
      "abstract": [
        {
          "text": "The user interface to show while an app launches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
      "kind": "symbol",
      "name": "UILaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName": {
      "abstract": [
        {
          "text": "The filename of the storyboard from which to generate the app’s launch image.",
          "type": "text"
        }
      ],
      "ideTitle": "Launch screen interface file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
      "kind": "symbol",
      "name": "UILaunchStoryboardName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardName"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboardname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards": {
      "abstract": [
        {
          "text": "The launch storyboard to use to generate a launch image when your app opens from a supported scheme.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
      "kind": "symbol",
      "name": "UILaunchStoryboards",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboards"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboards",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "name": "UILaunchToFullScreenByDefaultOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchToFullScreenByDefaultOnMac"
        }
      ],
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchtofullscreenbydefaultonmac"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile": {
      "abstract": [
        {
          "text": "The name of the app’s main storyboard file.",
          "type": "text"
        }
      ],
      "ideTitle": "Main storyboard file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
      "kind": "symbol",
      "name": "UIMainStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMainStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "UIMainStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uimainstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPreferredDefaultInterfaceOrientation": {
      "abstract": [
        {
          "text": "A string that indicates the preferred initial interface orientation for iPad and iPhone apps running on visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPreferredDefaultInterfaceOrientation",
      "kind": "symbol",
      "name": "UIPreferredDefaultInterfaceOrientation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPreferredDefaultInterfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "UIPreferredDefaultInterfaceOrientation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uipreferreddefaultinterfaceorientation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app’s icon contains a shine effect.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon already includes gloss effects",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon",
      "kind": "symbol",
      "name": "UIPrerenderedIcon",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrerenderedIcon"
        }
      ],
      "role": "symbol",
      "title": "UIPrerenderedIcon",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiprerenderedicon"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an iPad app is capable of sharing the screen with other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
      "kind": "symbol",
      "name": "UIRequiresFullScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRequiresFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIRequiresFullScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uirequiresfullscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system initially hides the status bar when the app launches.",
          "type": "text"
        }
      ],
      "ideTitle": "Status bar is initially hidden",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarHidden",
      "kind": "symbol",
      "name": "UIStatusBarHidden",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarHidden"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarHidden",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uistatusbarhidden"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarStyle": {
      "abstract": [
        {
          "text": "The style of the status bar as the app launches.",
          "type": "text"
        }
      ],
      "ideTitle": "Status bar style",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarStyle",
      "kind": "symbol",
      "name": "UIStatusBarStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uistatusbarstyle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarTintParameters": {
      "abstract": [
        {
          "text": "The status bar tint.",
          "type": "text"
        }
      ],
      "ideTitle": "Status bar tinting parameters",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarTintParameters",
      "kind": "symbol",
      "name": "UIStatusBarTintParameters",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarTintParameters"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarTintParameters",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uistatusbartintparameters"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations": {
      "abstract": [
        {
          "text": "The interface orientations supported by your app.",
          "type": "text"
        }
      ],
      "ideTitle": "Supported interface orientations",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations",
      "kind": "symbol",
      "name": "UISupportedInterfaceOrientations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportedInterfaceOrientations"
        }
      ],
      "role": "symbol",
      "title": "UISupportedInterfaceOrientations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportedinterfaceorientations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if an iOS or iPadOS app appears as full screen in Assistive Access.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports full screen in Assistive Access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
      "kind": "symbol",
      "name": "UISupportsFullScreenInAssistiveAccess",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsFullScreenInAssistiveAccess"
        }
      ],
      "role": "symbol",
      "title": "UISupportsFullScreenInAssistiveAccess",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportsfullscreeninassistiveaccess"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
      "kind": "symbol",
      "name": "UISupportsTrueScreenSizeOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsTrueScreenSizeOnMac"
        }
      ],
      "role": "symbol",
      "title": "UISupportsTrueScreenSizeOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportstruescreensizeonmac"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle": {
      "abstract": [
        {
          "text": "The user interface style for the app.",
          "type": "text"
        }
      ],
      "ideTitle": "User Interface Style",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle",
      "kind": "symbol",
      "name": "UIUserInterfaceStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiuserinterfacestyle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewControllerBasedStatusBarAppearance": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system bases the appearance of the status bar on the style preferred by the current view controller.",
          "type": "text"
        }
      ],
      "ideTitle": "View controller-based status bar appearance",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewControllerBasedStatusBarAppearance",
      "kind": "symbol",
      "name": "UIViewControllerBasedStatusBarAppearance",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerBasedStatusBarAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerBasedStatusBarAppearance",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiviewcontrollerbasedstatusbarappearance"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Animation layers use antialiasing when drawing a layer that isn’t aligned to pixel boundaries.",
          "type": "text"
        }
      ],
      "ideTitle": "Renders with edge antialiasing",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
      "kind": "symbol",
      "name": "UIViewEdgeAntialiasing",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewEdgeAntialiasing"
        }
      ],
      "role": "symbol",
      "title": "UIViewEdgeAntialiasing",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiviewedgeantialiasing"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Animation sublayers inherit the opacity of their superlayer.",
          "type": "text"
        }
      ],
      "ideTitle": "Renders with group opacity",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
      "kind": "symbol",
      "name": "UIViewGroupOpacity",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewGroupOpacity"
        }
      ],
      "role": "symbol",
      "title": "UIViewGroupOpacity",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiviewgroupopacity"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle": {
      "abstract": [
        {
          "text": "The app’s white-point adaptivity style, enabled on devices with True Tone displays.",
          "type": "text"
        }
      ],
      "ideTitle": "White Point Adaptivity Style",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
      "kind": "symbol",
      "name": "UIWhitePointAdaptivityStyle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWhitePointAdaptivityStyle"
        }
      ],
      "role": "symbol",
      "title": "UIWhitePointAdaptivityStyle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiwhitepointadaptivitystyle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/app-execution": {
      "abstract": [
        {
          "text": "Control app launch, execution, and termination.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/app-execution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App execution",
      "type": "topic",
      "url": "/documentation/bundleresources/app-execution"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration": {
      "abstract": [
        {
          "text": "Define basic characteristics of a bundle, like its name, type, and version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bundle configuration",
      "type": "topic",
      "url": "/documentation/bundleresources/bundle-configuration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/app-execution"
      ],
      "title": "Core settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Main-user-interface",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
      ],
      "title": "Main user interface"
    },
    {
      "anchor": "Launch-interface",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
      ],
      "title": "Launch interface"
    },
    {
      "anchor": "Icons",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon"
      ],
      "title": "Icons"
    },
    {
      "anchor": "Orientation",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIInterfaceOrientation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPreferredDefaultInterfaceOrientation"
      ],
      "title": "Orientation"
    },
    {
      "anchor": "Styling",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName"
      ],
      "title": "Styling"
    },
    {
      "anchor": "Fonts",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ATSApplicationFontsPath",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppFonts"
      ],
      "title": "Fonts"
    },
    {
      "anchor": "Status-bar",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarHidden",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarStyle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarTintParameters",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewControllerBasedStatusBarAppearance"
      ],
      "title": "Status bar"
    },
    {
      "anchor": "Pointer-interactions",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsIndirectInputEvents"
      ],
      "title": "Pointer interactions"
    },
    {
      "anchor": "Preferences",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconLabel"
      ],
      "title": "Preferences"
    },
    {
      "anchor": "Graphics",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy"
      ],
      "title": "Graphics"
    },
    {
      "anchor": "QuickLook",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize"
      ],
      "title": "QuickLook"
    },
    {
      "anchor": "Deprecated-keys",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages"
      ],
      "title": "Deprecated keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Main-user-interface",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationPreferredDefaultSceneSessionRole",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIMainStoryboardFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSMainNibFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIElement",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
              ],
              "title": "Main user interface"
            },
            {
              "anchor": "Launch-interface",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
              ],
              "title": "Launch interface"
            },
            {
              "anchor": "Icons",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon"
              ],
              "title": "Icons"
            },
            {
              "anchor": "Orientation",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIInterfaceOrientation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportedInterfaceOrientations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPreferredDefaultInterfaceOrientation"
              ],
              "title": "Orientation"
            },
            {
              "anchor": "Styling",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIUserInterfaceStyle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewEdgeAntialiasing",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIWhitePointAdaptivityStyle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewGroupOpacity",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefersDisplaySafeAreaCompatibilityMode",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccentColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetBackgroundColorName"
              ],
              "title": "Styling"
            },
            {
              "anchor": "Fonts",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ATSApplicationFontsPath",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppFonts"
              ],
              "title": "Fonts"
            },
            {
              "anchor": "Status-bar",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarHidden",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarStyle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIStatusBarTintParameters",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIViewControllerBasedStatusBarAppearance"
              ],
              "title": "Status bar"
            },
            {
              "anchor": "Pointer-interactions",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSupportsIndirectInputEvents"
              ],
              "title": "Pointer interactions"
            },
            {
              "anchor": "Preferences",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrefPaneIconLabel"
              ],
              "title": "Preferences"
            },
            {
              "anchor": "Graphics",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy"
              ],
              "title": "Graphics"
            },
            {
              "anchor": "QuickLook",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize"
              ],
              "title": "QuickLook"
            },
            {
              "anchor": "Deprecated-keys",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages"
              ],
              "title": "Deprecated keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/bundle-configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/app-execution"
              ],
              "title": "Core settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLNeedsToBeRunInMainThread/title",
          "value": "QLNeedsToBeRunInMainThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLNeedsToBeRunInMainThread/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLNeedsToBeRunInMainThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/title",
          "value": "UILaunchStoryboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarTintParameters/title",
          "value": "UIStatusBarTintParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarTintParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarTintParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/title",
          "value": "NSMainNibFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainNibFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainNibFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/title",
          "value": "UISupportsTrueScreenSizeOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsTrueScreenSizeOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsTrueScreenSizeOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccentColorName/title",
          "value": "NSAccentColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccentColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccentColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsFullScreenInAssistiveAccess/title",
          "value": "UISupportsFullScreenInAssistiveAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsFullScreenInAssistiveAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsFullScreenInAssistiveAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefPaneIconLabel/title",
          "value": "NSPrefPaneIconLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefPaneIconLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneIconLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppSupportsHDR/title",
          "value": "UIAppSupportsHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppSupportsHDR/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppSupportsHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewControllerBasedStatusBarAppearance/title",
          "value": "UIViewControllerBasedStatusBarAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewControllerBasedStatusBarAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerBasedStatusBarAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/title",
          "value": "LSUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLThumbnailMinimumSize/title",
          "value": "QLThumbnailMinimumSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLThumbnailMinimumSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailMinimumSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/title",
          "value": "NSMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefPaneIconFile/title",
          "value": "NSPrefPaneIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefPaneIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedInterfaceOrientations/title",
          "value": "UISupportedInterfaceOrientations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportedInterfaceOrientations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportedInterfaceOrientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppFonts/title",
          "value": "UIAppFonts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppFonts/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppFonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewGroupOpacity/title",
          "value": "UIViewGroupOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewGroupOpacity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewGroupOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarHidden/title",
          "value": "UIStatusBarHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarHidden/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewEdgeAntialiasing/title",
          "value": "UIViewEdgeAntialiasing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIViewEdgeAntialiasing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewEdgeAntialiasing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewWidth/title",
          "value": "QLPreviewWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/title",
          "value": "UIApplicationPreferredDefaultSceneSessionRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationPreferredDefaultSceneSessionRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationPreferredDefaultSceneSessionRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPreferredDefaultInterfaceOrientation/title",
          "value": "UIPreferredDefaultInterfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPreferredDefaultInterfaceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreferredDefaultInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFiles/title",
          "value": "CFBundleIconFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/title",
          "value": "UILaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUSelectionPolicy/title",
          "value": "GPUSelectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUSelectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GPUSelectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/title",
          "value": "UIRequiresFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIRequiresFullScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRequiresFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/title",
          "value": "CFBundleIcons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIcons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/title",
          "value": "UILaunchStoryboardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/title",
          "value": "LSUIPresentationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIPresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSupportsIndirectInputEvents/title",
          "value": "UIApplicationSupportsIndirectInputEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSupportsIndirectInputEvents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSupportsIndirectInputEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetBackgroundColorName/title",
          "value": "NSWidgetBackgroundColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetBackgroundColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWidgetBackgroundColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefersDisplaySafeAreaCompatibilityMode/title",
          "value": "NSPrefersDisplaySafeAreaCompatibilityMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrefersDisplaySafeAreaCompatibilityMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefersDisplaySafeAreaCompatibilityMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarStyle/title",
          "value": "UIStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIStatusBarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsAutomaticGraphicsSwitching/title",
          "value": "NSSupportsAutomaticGraphicsSwitching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsAutomaticGraphicsSwitching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsAutomaticGraphicsSwitching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFile/title",
          "value": "CFBundleIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages/title",
          "value": "UILaunchImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUEjectPolicy/title",
          "value": "GPUEjectPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUEjectPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GPUEjectPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIUserInterfaceStyle/title",
          "value": "UIUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIUserInterfaceStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIInterfaceOrientation/title",
          "value": "UIInterfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIInterfaceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconName/title",
          "value": "CFBundleIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPrerenderedIcon/title",
          "value": "UIPrerenderedIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPrerenderedIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrerenderedIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHighResolutionCapable/title",
          "value": "NSHighResolutionCapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHighResolutionCapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHighResolutionCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIWhitePointAdaptivityStyle/title",
          "value": "UIWhitePointAdaptivityStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIWhitePointAdaptivityStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWhitePointAdaptivityStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewHeight/title",
          "value": "QLPreviewHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewHeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ATSApplicationFontsPath/title",
          "value": "ATSApplicationFontsPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ATSApplicationFontsPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATSApplicationFontsPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/title",
          "value": "UILaunchToFullScreenByDefaultOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchToFullScreenByDefaultOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/title",
          "value": "UIMainStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIMainStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMainStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLSupportsConcurrentRequests/title",
          "value": "QLSupportsConcurrentRequests"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLSupportsConcurrentRequests/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLSupportsConcurrentRequests"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/user-interface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/user-interface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
