{
  "abstract": [
    {
      "text": "The configuration for the pass is invalid for either Wallet or the reader.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/invalidConfigurationError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKAddSecureElementPassErrorCode@PKAddSecureElementPassInvalidConfigurationError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidConfigurationError"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAddSecureElementPassInvalidConfigurationError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKAddSecureElementPassError.Code.invalidConfigurationError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidConfigurationError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError": {
      "abstract": [
        {
          "text": "An error object that PassKit uses when it adds Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code": {
      "abstract": [
        {
          "text": "Error codes for problems that occur when you add a secure element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotReadyError": {
      "abstract": [
        {
          "text": "The reader for the pass isn’t ready to start pairing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotReadyError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotReadyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassDeviceNotReadyError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.deviceNotReadyError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/devicenotreadyerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotSupportedError": {
      "abstract": [
        {
          "text": "The reader for the pass isn’t supported or has an invalid version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotSupportedError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotSupportedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassDeviceNotSupportedError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.deviceNotSupportedError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/devicenotsupportederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/genericError": {
      "abstract": [
        {
          "text": "Represents the default error case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/genericError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassGenericError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.genericError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/genericerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/invalidConfigurationError": {
      "abstract": [
        {
          "text": "The configuration for the pass is invalid for either Wallet or the reader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/invalidConfigurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassInvalidConfigurationError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.invalidConfigurationError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/invalidconfigurationerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/osVersionNotSupportedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osVersionNotSupportedError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/osVersionNotSupportedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassOSVersionNotSupportedError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.osVersionNotSupportedError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/osversionnotsupportederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unavailableError": {
      "abstract": [
        {
          "text": "Provisioning for secure element passes isn’t available on the device, or the app is missing the entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailableError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unavailableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassUnavailableError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.unavailableError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/unavailableerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unknownError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/unknownerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/userCanceledError": {
      "abstract": [
        {
          "text": "The user canceled adding the pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/userCanceledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassUserCanceledError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code.userCanceledError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code/usercancelederror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotReadyError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotSupportedError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/genericError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/osVersionNotSupportedError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unavailableError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/userCanceledError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unknownError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAddSecureElementPassInvalidConfigurationError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassInvalidConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotReadyError",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/deviceNotSupportedError",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/genericError",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/osVersionNotSupportedError",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/unavailableError",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code/userCanceledError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKAddSecureElementPassInvalidConfigurationError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1deviceNotReadyError/title",
          "value": "PKAddSecureElementPassDeviceNotReadyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1deviceNotReadyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassDeviceNotReadyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1osVersionNotSupportedError/title",
          "value": "PKAddSecureElementPassOSVersionNotSupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1osVersionNotSupportedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassOSVersionNotSupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/title",
          "value": "PKAddSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1deviceNotSupportedError/title",
          "value": "PKAddSecureElementPassDeviceNotSupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1deviceNotSupportedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassDeviceNotSupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1userCanceledError/title",
          "value": "PKAddSecureElementPassUserCanceledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1userCanceledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassUserCanceledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1unavailableError/title",
          "value": "PKAddSecureElementPassUnavailableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1unavailableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassUnavailableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1genericError/title",
          "value": "PKAddSecureElementPassGenericError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1genericError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassGenericError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1invalidConfigurationError/title",
          "value": "PKAddSecureElementPassInvalidConfigurationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code~1invalidConfigurationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassInvalidConfigurationError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddsecureelementpasserror/code/invalidconfigurationerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkaddsecureelementpasserror/code/invalidconfigurationerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
