{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the currently paired and active Apple Watch has installed the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WCSession(py)watchAppInstalled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isWatchAppInstalled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "watchAppInstalled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isWatchAppInstalled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isWatchAppInstalled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The user can choose to install only a subset of available apps on Apple Watch. The value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the Watch app associated with the current iOS app is installed on the user’s Apple Watch or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when it is not installed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value in this property is valid only for a configured session that has been activated successfully. If the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is available, its value must be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When the session becomes inactive or deactivated, you should ignore the value in this property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession": {
      "abstract": [
        {
          "text": "The object that initiates communication between a WatchKit extension and its companion iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "role": "symbol",
      "title": "WCSession",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState": {
      "abstract": [
        {
          "text": "The current activation state of the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCSessionActivationState",
          "text": "WCSessionActivationState"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activationState"
        }
      ],
      "role": "symbol",
      "title": "activationState",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/activationstate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the paired iPhone must be in an unlocked state to be reachable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        }
      ],
      "role": "symbol",
      "title": "iOSDeviceNeedsUnlockAfterRebootForReachability",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iosdeviceneedsunlockafterrebootforreachability"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the companion has installed the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCompanionAppInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "companionAppInstalled"
        }
      ],
      "role": "symbol",
      "title": "isCompanionAppInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iscompanionappinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Watch app’s complication is in use on the currently paired and active Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isComplicationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "complicationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isComplicationEnabled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iscomplicationenabled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the current iPhone has a paired Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paired"
        }
      ],
      "role": "symbol",
      "title": "isPaired",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/ispaired"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the currently paired and active Apple Watch has installed the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWatchAppInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "watchAppInstalled"
        }
      ],
      "role": "symbol",
      "title": "isWatchAppInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iswatchappinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL": {
      "abstract": [
        {
          "text": "A directory for storing information specific to the currently paired and active Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchDirectoryURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "watchDirectoryURL"
        }
      ],
      "role": "symbol",
      "title": "watchDirectoryURL",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/watchdirectoryurl"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated": {
      "abstract": [
        {
          "text": "The session is active and the Watch app and iOS app may communicate with each other freely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activated"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationStateActivated"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState.activated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate/activated"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Paired-Device-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL"
      ],
      "title": "Getting the Paired Device Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "watchAppInstalled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchAppInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Paired-Device-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL"
              ],
              "title": "Getting the Paired Device Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isWatchAppInstalled"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "watchAppInstalled"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1activated/title",
          "value": "WCSessionActivationStateActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1activated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationStateActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1watchDirectoryURL/title",
          "value": "watchDirectoryURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1watchDirectoryURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchDirectoryURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/title",
          "value": "WCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1iOSDeviceNeedsUnlockAfterRebootForReachability/title",
          "value": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1iOSDeviceNeedsUnlockAfterRebootForReachability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isCompanionAppInstalled/title",
          "value": "companionAppInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isCompanionAppInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "companionAppInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1activationState/title",
          "value": "activationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1activationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isWatchAppInstalled/title",
          "value": "watchAppInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isWatchAppInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchAppInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isComplicationEnabled/title",
          "value": "complicationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isComplicationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "complicationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isPaired/title",
          "value": "paired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/iswatchappinstalled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/iswatchappinstalled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
