{
  "abstract": [
    {
      "text": "The number of remaining times you can send complication data from the iOS app to the WatchKit extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/remainingComplicationUserInfoTransfers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WCSession(py)remainingComplicationUserInfoTransfers",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remainingComplicationUserInfoTransfers"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "remainingComplicationUserInfoTransfers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "remainingComplicationUserInfoTransfers"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remainingComplicationUserInfoTransfers"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The number of remaining times that you can call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " during the current day. If this property is set to 0, any additional calls to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferUserInfo(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the complication is on the active watch face, you are given 50 transfers a day. If the complication is not active, this property defaults to 0.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession": {
      "abstract": [
        {
          "text": "The object that initiates communication between a WatchKit extension and its companion iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "role": "symbol",
      "title": "WCSession",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/remainingComplicationUserInfoTransfers": {
      "abstract": [
        {
          "text": "The number of remaining times you can send complication data from the iOS app to the WatchKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remainingComplicationUserInfoTransfers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/remainingComplicationUserInfoTransfers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remainingComplicationUserInfoTransfers"
        }
      ],
      "role": "symbol",
      "title": "remainingComplicationUserInfoTransfers",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/remainingcomplicationuserinfotransfers"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)": {
      "abstract": [
        {
          "text": "Sends complication-related data from the iOS app to the WatchKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferCurrentComplicationUserInfo"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
          "text": "WCSessionUserInfoTransfer"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transferCurrentComplicationUserInfo:"
        }
      ],
      "role": "symbol",
      "title": "transferCurrentComplicationUserInfo(_:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/transfercurrentcomplicationuserinfo(_:)"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferUserInfo(_:)": {
      "abstract": [
        {
          "text": "Sends the specified data dictionary to the counterpart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferUserInfo"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
          "text": "WCSessionUserInfoTransfer"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferUserInfo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transferUserInfo:"
        }
      ],
      "role": "symbol",
      "title": "transferUserInfo(_:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/transferuserinfo(_:)"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-Complication-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)"
      ],
      "title": "Updating Complication Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "remainingComplicationUserInfoTransfers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remainingComplicationUserInfoTransfers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-Complication-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/transferCurrentComplicationUserInfo(_:)"
              ],
              "title": "Updating Complication Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "remainingComplicationUserInfoTransfers"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1remainingComplicationUserInfoTransfers/title",
          "value": "remainingComplicationUserInfoTransfers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1remainingComplicationUserInfoTransfers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remainingComplicationUserInfoTransfers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1transferCurrentComplicationUserInfo(_:)/title",
          "value": "transferCurrentComplicationUserInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1transferCurrentComplicationUserInfo(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "transferCurrentComplicationUserInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/title",
          "value": "WCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1transferUserInfo(_:)/title",
          "value": "transferUserInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1transferUserInfo(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "transferUserInfo:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/remainingcomplicationuserinfotransfers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/remainingcomplicationuserinfotransfers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
