{
  "abstract": [
    {
      "text": "A directory for storing information specific to the currently paired and active Apple Watch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WCSession(py)watchDirectoryURL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "watchDirectoryURL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "watchDirectoryURL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "watchDirectoryURL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "watchDirectoryURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must activate the current session before accessing this URL. Use this directory to store preferences, files, and other data that is relevant to the specific instance of your Watch app running on the currently paired Apple Watch. If more than one Apple Watch is paired with the same iPhone, the URL in this directory changes when the active Apple Watch changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the value in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the URL in this directory is undefined and should not be used. When a session is active or inactive, the URL corresponds to the directory for the most recently paired Apple Watch. Even when the session becomes inactive, the URL remains valid so that you have time to update your data files before the final deactivation occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the user uninstalls your app or unpairs their Apple Watch, iOS deletes this directory and its contents. If there is no paired watch, the value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession": {
      "abstract": [
        {
          "text": "The object that initiates communication between a WatchKit extension and its companion iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "role": "symbol",
      "title": "WCSession",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState": {
      "abstract": [
        {
          "text": "The current activation state of the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCSessionActivationState",
          "text": "WCSessionActivationState"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/activationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activationState"
        }
      ],
      "role": "symbol",
      "title": "activationState",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/activationstate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the paired iPhone must be in an unlocked state to be reachable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        }
      ],
      "role": "symbol",
      "title": "iOSDeviceNeedsUnlockAfterRebootForReachability",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iosdeviceneedsunlockafterrebootforreachability"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the companion has installed the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCompanionAppInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "companionAppInstalled"
        }
      ],
      "role": "symbol",
      "title": "isCompanionAppInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iscompanionappinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Watch app’s complication is in use on the currently paired and active Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isComplicationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "complicationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isComplicationEnabled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iscomplicationenabled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the current iPhone has a paired Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paired"
        }
      ],
      "role": "symbol",
      "title": "isPaired",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/ispaired"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the currently paired and active Apple Watch has installed the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWatchAppInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "watchAppInstalled"
        }
      ],
      "role": "symbol",
      "title": "isWatchAppInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/iswatchappinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL": {
      "abstract": [
        {
          "text": "A directory for storing information specific to the currently paired and active Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchDirectoryURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/watchDirectoryURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "watchDirectoryURL"
        }
      ],
      "role": "symbol",
      "title": "watchDirectoryURL",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession/watchdirectoryurl"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated": {
      "abstract": [
        {
          "text": "The session is not activated. When in this state, no communication occurs between the Watch app and iOS app. It is a programmer error to try to send data to the counterpart app while in this state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notActivated"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationStateNotActivated"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState.notActivated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate/notactivated"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Paired-Device-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled"
      ],
      "title": "Getting the Paired Device Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "watchDirectoryURL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchDirectoryURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Paired-Device-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isPaired",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/iOSDeviceNeedsUnlockAfterRebootForReachability",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isWatchAppInstalled",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isCompanionAppInstalled",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession/isComplicationEnabled"
              ],
              "title": "Getting the Paired Device Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "watchDirectoryURL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isComplicationEnabled/title",
          "value": "complicationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isComplicationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "complicationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1notActivated/title",
          "value": "WCSessionActivationStateNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1notActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationStateNotActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isWatchAppInstalled/title",
          "value": "watchAppInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isWatchAppInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchAppInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isCompanionAppInstalled/title",
          "value": "companionAppInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isCompanionAppInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "companionAppInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1activationState/title",
          "value": "activationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1activationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1iOSDeviceNeedsUnlockAfterRebootForReachability/title",
          "value": "iOSDeviceNeedsUnlockAfterRebootForReachability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1iOSDeviceNeedsUnlockAfterRebootForReachability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iOSDeviceNeedsUnlockAfterRebootForReachability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1watchDirectoryURL/title",
          "value": "watchDirectoryURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1watchDirectoryURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "watchDirectoryURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/title",
          "value": "WCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isPaired/title",
          "value": "paired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession~1isPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/watchdirectoryurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcsession/watchdirectoryurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
