{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "B_Yp",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " value in the conversion matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImage_ARGBToYpCbCrMatrix@FI@B_Yp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "B_Yp"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "B_Yp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "B_Yp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "B_Yp"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix": {
      "abstract": [
        {
          "text": "The 3 x 3 matrix that the vImage library uses to convert from RGB to YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImage_ARGBToYpCbCrMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Cb_R_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Cb_R_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Cb_R_Cr"
        }
      ],
      "role": "symbol",
      "title": "B_Cb_R_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_cb_r_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Cr"
        }
      ],
      "role": "symbol",
      "title": "B_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Yp"
        }
      ],
      "role": "symbol",
      "title": "B_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Cb",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Cb"
        }
      ],
      "role": "symbol",
      "title": "G_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Cr"
        }
      ],
      "role": "symbol",
      "title": "G_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Yp"
        }
      ],
      "role": "symbol",
      "title": "G_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "R_Cb",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "R_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "R_Cb"
        }
      ],
      "role": "symbol",
      "title": "R_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/r_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "R_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "R_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "R_Yp"
        }
      ],
      "role": "symbol",
      "title": "R_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/r_yp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Conversion-matrix-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr"
      ],
      "title": "Conversion matrix elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "B_Yp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Conversion-matrix-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr"
              ],
              "title": "Conversion matrix elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "B_Yp"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Cb/title",
          "value": "R_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "R_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cr/title",
          "value": "B_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cb/title",
          "value": "G_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Yp/title",
          "value": "R_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "R_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Yp/title",
          "value": "B_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cb_R_Cr/title",
          "value": "B_Cb_R_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cb_R_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Cb_R_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Yp/title",
          "value": "G_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cr/title",
          "value": "G_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/title",
          "value": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_yp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_yp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
