{"abstract":[{"text":"Tells the delegate that the person selected a sharing service for the current item.","type":"text"}],"variants":[{"paths":["/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:didchoose:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:didchoose:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"sharingServicePicker:didChooseSharingService:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)NSSharingServicePickerDelegate(im)sharingServicePicker:didChooseSharingService:","title":"sharingServicePicker(_:didChoose:)","modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.8"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingServicePicker"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSSharingServicePicker","kind":"typeIdentifier","text":"NSSharingServicePicker"},{"kind":"text","text":", "},{"text":"didChoose","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSSharingService","text":"NSSharingService","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method"},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)"],"title":"Customizing Behavior","anchor":"Customizing-Behavior"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingServicePicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sharingServicePicker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","text":"NSSharingServicePicker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChoose"},{"kind":"text","text":" "},{"kind":"internalParam","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","text":"NSSharingService","preciseIdentifier":"c:objc(cs)NSSharingService"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"name":"sharingServicePicker","content":[{"inlineContent":[{"type":"text","text":"The sharing service picker."}],"type":"paragraph"}]},{"name":"service","content":[{"inlineContent":[{"type":"text","text":"The selected sharing service. Invoked to give the delegate to the sharing service that is about to be executed."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"After someone chooses a service, the sharing service picker calls this method to let you know which service they picked. The sharing service receives the item sometime after this method returns.","type":"text"}]}],"kind":"content"}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePicker","kind":"identifier"}],"title":"NSSharingServicePicker","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","abstract":[{"type":"text","text":"A list of sharing services that the user can choose from."}],"role":"symbol","url":"/documentation/appkit/nssharingservicepicker","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSSharingServicePicker","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSharingService":{"navigatorTitle":[{"text":"NSSharingService","kind":"identifier"}],"title":"NSSharingService","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingService","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","abstract":[{"text":"An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nssharingservice","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)":{"url":"/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:delegatefor:)","kind":"symbol","abstract":[{"text":"Asks your delegate to provide an object that the selected sharing service can use as its delegate.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingServicePicker:delegateForSharingService:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharingServicePicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker"},{"text":", ","kind":"text"},{"text":"delegateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService"},{"text":") -> (any ","kind":"text"},{"text":"NSSharingServiceDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServiceDelegate"},{"text":")?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)","title":"sharingServicePicker(_:delegateFor:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)":{"url":"/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:didchoose:)","kind":"symbol","abstract":[{"text":"Tells the delegate that the person selected a sharing service for the current item.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingServicePicker:didChooseSharingService:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharingServicePicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker"},{"text":", ","kind":"text"},{"text":"didChoose","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)","title":"sharingServicePicker(_:didChoose:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate":{"abstract":[{"type":"text","text":"An interface for managing content for the macOS share sheet."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickerdelegate","role":"symbol","title":"NSSharingServicePickerDelegate"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","op":"replace","value":"sharingServicePicker:didChooseSharingService:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sharingServicePicker:didChooseSharingService:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)"],"anchor":"Customizing-Behavior","title":"Customizing Behavior"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sharingServicePicker:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","text":"NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sharingServicePicker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChooseSharingService:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService","text":"NSSharingService"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"service"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sharing service picker."}]}],"name":"sharingServicePicker"},{"content":[{"inlineContent":[{"text":"The selected sharing service. Invoked to give the delegate to the sharing service that is about to be executed.","type":"text"}],"type":"paragraph"}],"name":"service"}]},"path":"/primaryContentSections/1","op":"replace"},{"value":"NSSharingServicePicker","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/title"},{"value":[{"text":"NSSharingServicePicker","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/fragments"},{"value":[{"kind":"identifier","text":"NSSharingServicePicker"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/navigatorTitle"},{"value":"NSSharingService","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title"},{"value":[{"text":"NSSharingService","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments"},{"value":[{"kind":"identifier","text":"NSSharingService"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle"},{"value":"sharingServicePicker:delegateForSharingService:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:delegateFor:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sharingServicePicker:delegateForSharingService:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:delegateFor:)/fragments"},{"value":"sharingServicePicker:didChooseSharingService:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:didChoose:)/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:didChoose:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sharingServicePicker:didChooseSharingService:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/title","op":"replace","value":"NSSharingServicePickerDelegate"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"NSSharingServicePickerDelegate"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/navigatorTitle","op":"replace","value":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}