{"seeAlsoSections":[{"generated":true,"anchor":"Customizing-Behavior","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)"],"title":"Customizing Behavior"}],"variants":[{"paths":["/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:delegatefor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:delegatefor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)"},"sections":[],"metadata":{"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sharingServicePicker:delegateForSharingService:"}],"symbolKind":"method","externalID":"c:objc(pl)NSSharingServicePickerDelegate(im)sharingServicePicker:delegateForSharingService:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingServicePicker"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSSharingServicePicker","kind":"typeIdentifier","text":"NSSharingServicePicker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegateFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSSharingService","kind":"typeIdentifier","text":"NSSharingService"},{"kind":"text","text":") -> (any "},{"preciseIdentifier":"c:objc(pl)NSSharingServiceDelegate","kind":"typeIdentifier","text":"NSSharingServiceDelegate"},{"kind":"text","text":")?"}],"title":"sharingServicePicker(_:delegateFor:)","platforms":[{"beta":false,"name":"macOS","introducedAt":"10.8","unavailable":false,"deprecated":false}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Asks your delegate to provide an object that the selected sharing service can use as its delegate.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingServicePicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sharingServicePicker"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker","text":"NSSharingServicePicker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegateFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sharingService"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService","text":"NSSharingService"},{"kind":"text","text":") -> (any "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServiceDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServiceDelegate","text":"NSSharingServiceDelegate"},{"kind":"text","text":")?"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The sharing service picker."}],"type":"paragraph"}],"name":"sharingServicePicker"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The selected sharing service.","type":"text"}]}],"name":"sharingService"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"An object that adopts the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServiceDelegate","type":"reference","isActive":true},{"text":" protocol.","type":"text"}]}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"text":"The sharing service assigns the returned object to its ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService/delegate","isActive":true,"type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePicker","kind":"identifier"}],"title":"NSSharingServicePicker","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","abstract":[{"type":"text","text":"A list of sharing services that the user can choose from."}],"role":"symbol","url":"/documentation/appkit/nssharingservicepicker","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSSharingServicePicker","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)":{"url":"/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:delegatefor:)","kind":"symbol","abstract":[{"text":"Asks your delegate to provide an object that the selected sharing service can use as its delegate.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingServicePicker:delegateForSharingService:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharingServicePicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker"},{"text":", ","kind":"text"},{"text":"delegateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService"},{"text":") -> (any ","kind":"text"},{"text":"NSSharingServiceDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServiceDelegate"},{"text":")?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:delegateFor:)","title":"sharingServicePicker(_:delegateFor:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingService/delegate":{"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService/delegate","abstract":[{"text":"Specifies the delegate of the sharing service.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"NSSharingServiceDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServiceDelegate"},{"text":")?","kind":"text"}],"type":"topic","title":"delegate","url":"/documentation/appkit/nssharingservice/delegate","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)":{"url":"/documentation/appkit/nssharingservicepickerdelegate/sharingservicepicker(_:didchoose:)","kind":"symbol","abstract":[{"text":"Tells the delegate that the person selected a sharing service for the current item.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingServicePicker:didChooseSharingService:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharingServicePicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingServicePicker","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePicker"},{"text":", ","kind":"text"},{"text":"didChoose","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingService","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingService"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)","title":"sharingServicePicker(_:didChoose:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingService":{"navigatorTitle":[{"text":"NSSharingService","kind":"identifier"}],"title":"NSSharingService","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingService","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","abstract":[{"text":"An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nssharingservice","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate":{"abstract":[{"type":"text","text":"An interface for managing content for the macOS share sheet."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickerdelegate","role":"symbol","title":"NSSharingServicePickerDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServiceDelegate":{"url":"/documentation/appkit/nssharingservicedelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServiceDelegate","kind":"identifier"}],"title":"NSSharingServiceDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSSharingServiceDelegate","kind":"identifier"}],"abstract":[{"text":"A set of methods that you use to customize the position and animation of a share sheet, and to be notified whether the item is successfully shared.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"sharingServicePicker:delegateForSharingService:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sharingServicePicker:delegateForSharingService:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate/sharingServicePicker(_:didChoose:)"],"title":"Customizing Behavior","generated":true,"anchor":"Customizing-Behavior"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<NSSharingServiceDelegate>","preciseIdentifier":"c:Qoobjc(pl)NSSharingServiceDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sharingServicePicker:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingServicePicker","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","preciseIdentifier":"c:objc(cs)NSSharingServicePicker","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sharingServicePicker","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegateForSharingService:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSharingService","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingService","preciseIdentifier":"c:objc(cs)NSSharingService","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sharingService","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The sharing service picker.","type":"text"}]}],"name":"sharingServicePicker"},{"content":[{"inlineContent":[{"text":"The selected sharing service.","type":"text"}],"type":"paragraph"}],"name":"sharingService"}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that adopts the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServiceDelegate","isActive":true,"type":"reference"},{"type":"text","text":" protocol."}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/title","value":"NSSharingServicePicker"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/fragments","value":[{"kind":"identifier","text":"NSSharingServicePicker"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/navigatorTitle","value":[{"kind":"identifier","text":"NSSharingServicePicker"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:delegateFor:)/title","value":"sharingServicePicker:delegateForSharingService:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:delegateFor:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sharingServicePicker:delegateForSharingService:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1delegate/title","value":"delegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1delegate/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:didChoose:)/title","value":"sharingServicePicker:didChooseSharingService:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sharingServicePicker:didChooseSharingService:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate~1sharingServicePicker(_:didChoose:)/fragments"},{"op":"replace","value":"NSSharingService","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSSharingService"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments"},{"op":"replace","value":[{"text":"NSSharingService","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle"},{"op":"replace","value":"NSSharingServicePickerDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/title"},{"op":"replace","value":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSSharingServicePickerDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/navigatorTitle"},{"op":"replace","value":"NSSharingServiceDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServiceDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSSharingServiceDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServiceDelegate/fragments"},{"op":"replace","value":[{"text":"NSSharingServiceDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServiceDelegate/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}