{
  "abstract": [
    {
      "text": "Finishes the animations and returns the animator to the inactive state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/finishAnimation(at:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIViewAnimating(im)finishAnimationAtPosition:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "finishAnimation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "at"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIViewAnimatingPosition",
        "text": "UIViewAnimatingPosition"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "finishAnimationAtPosition:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "finishAnimation(at:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "finishAnimation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "at"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "finalPosition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIViewAnimatingPosition",
              "text": "UIViewAnimatingPosition"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The final position for any view properties. Specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition/current",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to leave the view properties unchanged from their current values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "finalPosition"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After putting the animator object into the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/stopped",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state, call this method to perform any final cleanup tasks. It is a programmer error to call this method at any time except after a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/stopAnimation(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method where you pass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the ",
              "type": "text"
            },
            {
              "code": "withoutFinishing",
              "type": "codeVoice"
            },
            {
              "text": " parameter. Calling this method is not required, but is recommended in cases where you want to ensure that completion blocks or other final tasks are performed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Implementations of this method are responsible for setting the state of the animator object to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/inactive",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and for performing any final cleanup tasks, such as executing completion blocks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating": {
      "abstract": [
        {
          "text": "An interface for implementing custom animator objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/finishAnimation(at:)": {
      "abstract": [
        {
          "text": "Finishes the animations and returns the animator to the inactive state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimatingPosition",
          "text": "UIViewAnimatingPosition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/finishAnimation(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishAnimationAtPosition:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "finishAnimation(at:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating/finishanimation(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/pauseAnimation()": {
      "abstract": [
        {
          "text": "Pauses a running animation at its current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAnimation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/pauseAnimation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseAnimation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pauseAnimation()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating/pauseanimation()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation()": {
      "abstract": [
        {
          "text": "Starts the animation from its current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAnimation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAnimation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startAnimation()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating/startanimation()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation(afterDelay:)": {
      "abstract": [
        {
          "text": "Starts the animation after the specified delay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "afterDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation(afterDelay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAnimationAfterDelay:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startAnimation(afterDelay:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating/startanimation(afterdelay:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/stopAnimation(_:)": {
      "abstract": [
        {
          "text": "Stops the animations at their current positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/stopAnimation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopAnimation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "stopAnimation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating/stopanimation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition": {
      "abstract": [
        {
          "text": "Constants indicating positions within the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewAnimatingPosition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimatingPosition"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimatingPosition",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimatingposition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition/current": {
      "abstract": [
        {
          "text": "The current position. Use this constant when you want the most recent value set by an animator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition/current",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimatingPositionCurrent"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimatingPosition.current",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimatingposition/current"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/inactive": {
      "abstract": [
        {
          "text": "The animations have not yet started executing. This is the initial state of the animator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inactive"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/inactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimatingStateInactive"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimatingState.inactive",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimatingstate/inactive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/stopped": {
      "abstract": [
        {
          "text": "The animation is stopped. Putting an animation into this state ends the animation and leaves any animatable properties at their current values, instead of updating them to their intended final values. An animation cannot be started while in this state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingState/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimatingStateStopped"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimatingState.stopped",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimatingstate/stopped"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-and-stopping-the-animations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation(afterDelay:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/pauseAnimation()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/stopAnimation(_:)"
      ],
      "title": "Starting and stopping the animations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "finishAnimationAtPosition:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishAnimationAtPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-and-stopping-the-animations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/startAnimation(afterDelay:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/pauseAnimation()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating/stopAnimation(_:)"
              ],
              "title": "Starting and stopping the animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "finishAnimationAtPosition:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIViewAnimatingPosition",
                    "text": "UIViewAnimatingPosition"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "finalPosition"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The final position for any view properties. Specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimatingPosition/current",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to leave the view properties unchanged from their current values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "finalPosition"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1pauseAnimation()/title",
          "value": "pauseAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1pauseAnimation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingState~1inactive/title",
          "value": "UIViewAnimatingStateInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingState~1inactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimatingStateInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingPosition~1current/title",
          "value": "UIViewAnimatingPositionCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingPosition~1current/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimatingPositionCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1finishAnimation(at:)/title",
          "value": "finishAnimationAtPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1finishAnimation(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishAnimationAtPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/title",
          "value": "UIViewAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1startAnimation()/title",
          "value": "startAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1startAnimation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingPosition/title",
          "value": "UIViewAnimatingPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimatingPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimatingPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingState~1stopped/title",
          "value": "UIViewAnimatingStateStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimatingState~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimatingStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1stopAnimation(_:)/title",
          "value": "stopAnimation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1stopAnimation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopAnimation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1startAnimation(afterDelay:)/title",
          "value": "startAnimationAfterDelay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating~1startAnimation(afterDelay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAnimationAfterDelay:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewanimating/finishanimation(at:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewanimating/finishanimation(at:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
