{
  "abstract": [
    {
      "text": "The value that represents a selection in the left direction along the current line.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/left"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextSelectionNavigationDirection@NSTextSelectionNavigationDirectionLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "left"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextSelectionNavigationDirectionLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextSelectionNavigation.Direction.left"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "left"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation": {
      "abstract": [
        {
          "text": "An interface you use to expose methods for obtaining results from actions performed on text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction": {
      "abstract": [
        {
          "text": "Values that describe the direction of a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/backward": {
      "abstract": [
        {
          "text": "The value that represents a backward selection based on the flow of text stored in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backward"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/backward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionBackward"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.backward",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/backward"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/down": {
      "abstract": [
        {
          "text": "The value that represents a selection in the down direction, below the current line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.down",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/down"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/forward": {
      "abstract": [
        {
          "text": "The value that represents a logical forward selection based on the flow of text stored in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forward"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/forward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionForward"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.forward",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/forward"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/left": {
      "abstract": [
        {
          "text": "The value that represents a selection in the left direction along the current line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionLeft"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.left",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/right": {
      "abstract": [
        {
          "text": "The value that represents a selection in the right direction along the current line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionRight"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.right",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/up": {
      "abstract": [
        {
          "text": "The value that represents a selection in the up direction, above the current line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction.up",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction/up"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation-directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/forward",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/backward",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/right",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/up",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/down"
      ],
      "title": "Navigation directions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionNavigationDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation-directions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/forward",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/backward",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/right",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/up",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction/down"
              ],
              "title": "Navigation directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionNavigationDirectionLeft"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1forward/title",
          "value": "NSTextSelectionNavigationDirectionForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1forward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/title",
          "value": "NSTextSelectionNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1backward/title",
          "value": "NSTextSelectionNavigationDirectionBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1backward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1down/title",
          "value": "NSTextSelectionNavigationDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1left/title",
          "value": "NSTextSelectionNavigationDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/title",
          "value": "NSTextSelectionNavigationDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1up/title",
          "value": "NSTextSelectionNavigationDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1right/title",
          "value": "NSTextSelectionNavigationDirectionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirectionRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextselectionnavigation/direction/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextselectionnavigation/direction/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
