{
  "abstract": [
    {
      "text": "Specifies the begin time of the receiver in relation to its parent object, if applicable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/beginTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CAMediaTiming(py)beginTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beginTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTimeInterval",
        "text": "CFTimeInterval"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beginTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "beginTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beginTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTimeInterval",
              "text": "CFTimeInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Defaults to 0.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/beginTime": {
      "abstract": [
        {
          "text": "Specifies the begin time of the receiver in relation to its parent object, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/beginTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginTime"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "beginTime",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming/begintime"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/timeOffset": {
      "abstract": [
        {
          "text": "Specifies an additional time offset in active local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/timeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeOffset"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timeOffset",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming/timeoffset"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTimeInterval": {
      "abstract": [
        {
          "text": "Type used to represent elapsed time in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTimeInterval",
      "type": "topic",
      "url": "/documentation/corefoundation/cftimeinterval"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514",
      "title": "Core Animation Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Animation Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Animation-Start-Time",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/timeOffset"
      ],
      "title": "Animation Start Time"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beginTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beginTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Animation-Start-Time",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/timeOffset"
              ],
              "title": "Animation Start Time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTimeInterval",
                    "text": "CFTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "beginTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1beginTime/title",
          "value": "beginTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1beginTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beginTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1timeOffset/title",
          "value": "timeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1timeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeOffset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/camediatiming/begintime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/camediatiming/begintime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
