{
  "abstract": [
    {
      "text": "The initializer can’t find the file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/fileNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC15SKTestErrorCodeLeV12fileNotFoundSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fileNotFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
        "text": "SKTestError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKTestErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "fileNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fileNotFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
              "text": "SKTestError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKTestErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError": {
      "abstract": [
        {
          "text": "Information about an error that the testing environment returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestError"
        }
      ],
      "role": "symbol",
      "title": "SKTestError",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code": {
      "abstract": [
        {
          "text": "Error codes in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/fileNotFound": {
      "abstract": [
        {
          "text": "The initializer can’t find the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/fileNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileNotFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/filenotfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidAction": {
      "abstract": [
        {
          "text": "The action is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAction",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/invalidaction"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductIdentifier": {
      "abstract": [
        {
          "text": "The product identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidProductIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidProductIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/invalidproductidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductType": {
      "abstract": [
        {
          "text": "The product type is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidProductType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductType",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidProductType",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/invalidproducttype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidURL": {
      "abstract": [
        {
          "text": "The URL is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidURL",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/invalidurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noSubscriptionFound": {
      "abstract": [
        {
          "text": "The test environment didn’t find a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSubscriptionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noSubscriptionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSubscriptionFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/nosubscriptionfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noTransactionFound": {
      "abstract": [
        {
          "text": "The test environment didn’t find a transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noTransactionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noTransactionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "noTransactionFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/notransactionfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/serviceUnavailable": {
      "abstract": [
        {
          "text": "The service isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC15SKTestErrorCodeLeV",
          "text": "SKTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/serviceUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serviceUnavailable",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/serviceunavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidAction",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidProductType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/invalidURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noSubscriptionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/noTransactionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/serviceUnavailable",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/title",
          "value": "SKTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktesterror/filenotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
