{
  "abstract": [
    {
      "text": "Indicates a set of certificates or certificates and private keys.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/SecExternalItemType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeAggregate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecExternalItemType@kSecItemTypeAggregate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "itemTypeAggregate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSecItemTypeAggregate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SecExternalItemType.itemTypeAggregate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "itemTypeAggregate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Possible values include ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " formats (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat": {
      "abstract": [
        {
          "text": "The external format of a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat",
      "type": "topic",
      "url": "/documentation/security/secexternalformat"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence": {
      "abstract": [
        {
          "text": "Sequence of certificates and keys with PEM armor. PEM armor refers to a way of expressing binary data as an ASCII string so that it can be transferred over text-only channels such as email. This is the default format for multiple items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPEMSequence"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPEMSequence"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPEMSequence",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpemsequence"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12": {
      "abstract": [
        {
          "text": "Set of certificates and private keys. PKCS12 is the Personal Information Exchange Syntax from RSA Security, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPKCS12"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPKCS12"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPKCS12",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpkcs12"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7": {
      "abstract": [
        {
          "text": "Sequence of certificates, no PEM armor. PKCS7 is the Cryptographic Message Syntax Standard from RSA Security, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPKCS7"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPKCS7"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPKCS7",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpkcs7"
    },
    "doc://com.apple.security/documentation/Security/SecExternalItemType": {
      "abstract": [
        {
          "text": "The import item type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecExternalItemType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecExternalItemType"
        }
      ],
      "role": "symbol",
      "title": "SecExternalItemType",
      "type": "topic",
      "url": "/documentation/security/secexternalitemtype"
    },
    "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeAggregate": {
      "abstract": [
        {
          "text": "Indicates a set of certificates or certificates and private keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemTypeAggregate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeAggregate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecItemTypeAggregate"
        }
      ],
      "role": "symbol",
      "title": "SecExternalItemType.itemTypeAggregate",
      "type": "topic",
      "url": "/documentation/security/secexternalitemtype/itemtypeaggregate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSecItemTypeAggregate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecItemTypeAggregate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security",
                "doc://com.apple.security/documentation/Security/SecExternalItemType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSecItemTypeAggregate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS12/title",
          "value": "kSecFormatPKCS12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPKCS12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS7/title",
          "value": "kSecFormatPKCS7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPKCS7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType~1itemTypeAggregate/title",
          "value": "kSecItemTypeAggregate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType~1itemTypeAggregate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecItemTypeAggregate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPEMSequence/title",
          "value": "kSecFormatPEMSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPEMSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPEMSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/title",
          "value": "SecExternalItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/title",
          "value": "SecExternalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secexternalitemtype/itemtypeaggregate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secexternalitemtype/itemtypeaggregate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
