{
  "abstract": [
    {
      "text": "Returns a range of indexes for the table view’s columns that lie wholly or partially within the horizontal boundaries of the specified rectangle.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnIndexes(in:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnsInRect:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTableView(im)columnsInRect:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "columnsInRect:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "columnsInRect:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "columnsInRect:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "columnsInRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A rectangle in the coordinate system of the table view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rect"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A range of indexes for the table view’s columns that lie wholly or partially within the horizontal boundaries of ",
              "type": "text"
            },
            {
              "code": "aRect",
              "type": "codeVoice"
            },
            {
              "text": ". If the width or height of ",
              "type": "text"
            },
            {
              "code": "aRect",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ", returns an ",
              "type": "text"
            },
            {
              "code": "NSRange",
              "type": "codeVoice"
            },
            {
              "text": " whose length is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The location of the range is the first such column’s index, and the length is the number of columns that lie in ",
              "type": "text"
            },
            {
              "code": "aRect",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/autoresizesAllColumnsToFit": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if the table view proportionally resizes its columns to fit when its superview’s frame changes, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/false",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if it only resizes the last column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "autoresizesAllColumnsToFit"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/autoresizesAllColumnsToFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoresizesAllColumnsToFit"
        }
      ],
      "role": "symbol",
      "title": "autoresizesAllColumnsToFit",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/autoresizesallcolumnstofit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnIndexes(in:)": {
      "abstract": [
        {
          "text": "Returns the indexes of the table view’s columns that intersect the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnIndexes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnIndexes(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnIndexesInRect:"
        }
      ],
      "role": "symbol",
      "title": "columnIndexes(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnindexes(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnsInRect:": {
      "abstract": [
        {
          "text": "Returns a range of indexes for the table view’s columns that lie wholly or partially within the horizontal boundaries of the specified rectangle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "columnsInRect:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnsInRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnsInRect:"
        }
      ],
      "role": "symbol",
      "title": "columnsInRect:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnsinrect:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/dragImageForRows:event:dragImageOffset:": {
      "abstract": [
        {
          "text": "Computes and returns an image to use for dragging.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dragImageForRows:event:dragImageOffset:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/dragImageForRows:event:dragImageOffset:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragImageForRows:event:dragImageOffset:"
        }
      ],
      "role": "symbol",
      "title": "dragImageForRows:event:dragImageOffset:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/dragimageforrows:event:dragimageoffset:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/drawsGrid": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the table view draws a grid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "drawsGrid"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/drawsGrid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawsGrid"
        }
      ],
      "role": "symbol",
      "title": "drawsGrid",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/drawsgrid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/focusedColumn()": {
      "abstract": [
        {
          "text": "Returns the currently focused column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedColumn"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/focusedColumn()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusedColumn"
        }
      ],
      "role": "symbol",
      "title": "focusedColumn()",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/focusedcolumn()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/performClickOnCell(atColumn:row:)": {
      "abstract": [
        {
          "text": "Performs a click action on the cell at the specified row and column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performClickOnCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/performClickOnCell(atColumn:row:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performClickOnCellAtColumn:row:"
        }
      ],
      "role": "symbol",
      "title": "performClickOnCell(atColumn:row:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/performclickoncell(atcolumn:row:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/preparedCell(atColumn:row:)": {
      "abstract": [
        {
          "text": "Returns the fully prepared cell that the table view will use for drawing or processing of the specified row and column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preparedCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCell",
          "text": "NSCell"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/preparedCell(atColumn:row:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preparedCellAtColumn:row:"
        }
      ],
      "role": "symbol",
      "title": "preparedCell(atColumn:row:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/preparedcell(atcolumn:row:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/rows(in:)": {
      "abstract": [
        {
          "text": "Returns a range of indexes for the rows that lie wholly or partially within the vertical boundaries of the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rows(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowsInRect:"
        }
      ],
      "role": "symbol",
      "title": "rows(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rows(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectColumn:byExtendingSelection:": {
      "abstract": [
        {
          "text": "Selects the column at the specified index, optionally extending any existing selection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectColumn:byExtendingSelection:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectColumn:byExtendingSelection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectColumn:byExtendingSelection:"
        }
      ],
      "role": "symbol",
      "title": "selectColumn:byExtendingSelection:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/selectcolumn:byextendingselection:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectRow:byExtendingSelection:": {
      "abstract": [
        {
          "text": "Selects a row at the specified index, optionally extending any existing selection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectRow:byExtendingSelection:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectRow:byExtendingSelection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectRow:byExtendingSelection:"
        }
      ],
      "role": "symbol",
      "title": "selectRow:byExtendingSelection:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/selectrow:byextendingselection:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedColumnEnumerator": {
      "abstract": [
        {
          "text": "This method has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectedColumnEnumerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedColumnEnumerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedColumnEnumerator"
        }
      ],
      "role": "symbol",
      "title": "selectedColumnEnumerator",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/selectedcolumnenumerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedRowEnumerator": {
      "abstract": [
        {
          "text": "This method has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectedRowEnumerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedRowEnumerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedRowEnumerator"
        }
      ],
      "role": "symbol",
      "title": "selectedRowEnumerator",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/selectedrowenumerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/setAutoresizesAllColumnsToFit:": {
      "abstract": [
        {
          "text": "Controls whether the table view proportionally resizes its columns to fit when its superview’s frame changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setAutoresizesAllColumnsToFit:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/setAutoresizesAllColumnsToFit:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAutoresizesAllColumnsToFit:"
        }
      ],
      "role": "symbol",
      "title": "setAutoresizesAllColumnsToFit:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/setautoresizesallcolumnstofit:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/setDrawsGrid:": {
      "abstract": [
        {
          "text": "Sets whether the table view draws a grid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDrawsGrid:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/setDrawsGrid:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDrawsGrid:"
        }
      ],
      "role": "symbol",
      "title": "setDrawsGrid:",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/setdrawsgrid:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/setFocusedColumn(_:)": {
      "abstract": [
        {
          "text": "Sets the currently focused column to the specified index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFocusedColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/setFocusedColumn(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFocusedColumn:"
        }
      ],
      "role": "symbol",
      "title": "setFocusedColumn(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/setfocusedcolumn(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/shouldFocusCell(_:atColumn:row:)": {
      "abstract": [
        {
          "text": "Returns whether the fully prepared cell at the specified row and column can be made the focused cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldFocusCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCell",
          "text": "NSCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/shouldFocusCell(_:atColumn:row:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldFocusCell:atColumn:row:"
        }
      ],
      "role": "symbol",
      "title": "shouldFocusCell(_:atColumn:row:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/shouldfocuscell(_:atcolumn:row:)"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539424-tableview": {
      "abstract": [
        {
          "text": "Writes the specified rows to the specified pasteboard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539424-tableview",
      "kind": "symbol",
      "role": "symbol",
      "title": "tableView:writeRows:toPasteboard:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539424-tableview"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/rows(in:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/dragImageForRows:event:dragImageOffset:",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/setAutoresizesAllColumnsToFit:",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/autoresizesAllColumnsToFit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectColumn:byExtendingSelection:",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectRow:byExtendingSelection:",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1539424-tableview",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/setDrawsGrid:",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/drawsGrid",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedColumnEnumerator",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectedRowEnumerator",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/focusedColumn()",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/setFocusedColumn(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/shouldFocusCell(_:atColumn:row:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/performClickOnCell(atColumn:row:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/preparedCell(atColumn:row:)"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rows(in:)/title",
          "value": "rowsInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rows(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rowsInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1performClickOnCell(atColumn:row:)/title",
          "value": "performClickOnCellAtColumn:row:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1performClickOnCell(atColumn:row:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performClickOnCellAtColumn:row:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1focusedColumn()/title",
          "value": "focusedColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1focusedColumn()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "focusedColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1setFocusedColumn(_:)/title",
          "value": "setFocusedColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1setFocusedColumn(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFocusedColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1shouldFocusCell(_:atColumn:row:)/title",
          "value": "shouldFocusCell:atColumn:row:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1shouldFocusCell(_:atColumn:row:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldFocusCell:atColumn:row:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1preparedCell(atColumn:row:)/title",
          "value": "preparedCellAtColumn:row:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1preparedCell(atColumn:row:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "preparedCellAtColumn:row:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1columnIndexes(in:)/title",
          "value": "columnIndexesInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1columnIndexes(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "columnIndexesInRect:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableview/columnsinrect:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
