{
  "abstract": [
    {
      "text": "Contains the possible style values for a table view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSTableViewStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Style"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Style"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSTableView.Style"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Style"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum": {
      "abstract": [
        {
          "text": "Contains the possible style values for a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The system resolves the table view style based on the table view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/fullWidth": {
      "abstract": [
        {
          "text": "The table view style resolves to a full-width style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullWidth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/fullWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewStyleFullWidth"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style.fullWidth",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/fullwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/inset": {
      "abstract": [
        {
          "text": "The table view style resolves to an inset style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inset"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/inset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewStyleInset"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style.inset",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/inset"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/plain": {
      "abstract": [
        {
          "text": "The table view style resolves to a plain style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewStylePlain"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style.plain",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/plain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/sourceList": {
      "abstract": [
        {
          "text": "The table view style resolves to a source-list style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/sourceList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewStyleSourceList"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.Style.sourceList",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.enum/sourcelist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/backgroundColor": {
      "abstract": [
        {
          "text": "The color used to draw the background of the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/backgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveStyle": {
      "abstract": [
        {
          "text": "The effective style that the table uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewStyle",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveStyle"
        }
      ],
      "role": "symbol",
      "title": "effectiveStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/effectivestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridColor": {
      "abstract": [
        {
          "text": "The color used to draw grid lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gridColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gridColor"
        }
      ],
      "role": "symbol",
      "title": "gridColor",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/gridcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridStyleMask": {
      "abstract": [
        {
          "text": "The grid lines drawn by the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gridStyleMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewGridLineStyle",
          "text": "GridLineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridStyleMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gridStyleMask"
        }
      ],
      "role": "symbol",
      "title": "gridStyleMask",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/gridstylemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/indicatorImage(in:)": {
      "abstract": [
        {
          "text": "Returns the indicator image of the specified table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatorImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableColumn",
          "text": "NSTableColumn"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/indicatorImage(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatorImageInTableColumn:"
        }
      ],
      "role": "symbol",
      "title": "indicatorImage(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/indicatorimage(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/intercellSpacing": {
      "abstract": [
        {
          "text": "The horizontal and vertical spacing between cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intercellSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/intercellSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intercellSpacing"
        }
      ],
      "role": "symbol",
      "title": "intercellSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/intercellspacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight": {
      "abstract": [
        {
          "text": "The height of each row in the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowHeight"
        }
      ],
      "role": "symbol",
      "title": "rowHeight",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectionHighlightStyle-swift.property": {
      "abstract": [
        {
          "text": "The selection highlight style used by the table view to indicate row and column selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionHighlightStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewSelectionHighlightStyle",
          "text": "SelectionHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectionHighlightStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionHighlightStyle"
        }
      ],
      "role": "symbol",
      "title": "selectionHighlightStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/selectionhighlightstyle-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/setIndicatorImage(_:in:)": {
      "abstract": [
        {
          "text": "Sets the indicator image of the specified column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIndicatorImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableColumn",
          "text": "NSTableColumn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/setIndicatorImage(_:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIndicatorImage:inTableColumn:"
        }
      ],
      "role": "symbol",
      "title": "setIndicatorImage(_:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/setindicatorimage(_:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/style-swift.property": {
      "abstract": [
        {
          "text": "The style that the table view uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewStyle",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/style-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/style-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/usesAlternatingRowBackgroundColors": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the table view uses alternating row colors for its background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesAlternatingRowBackgroundColors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/usesAlternatingRowBackgroundColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesAlternatingRowBackgroundColors"
        }
      ],
      "role": "symbol",
      "title": "usesAlternatingRowBackgroundColors",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/usesalternatingrowbackgroundcolors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Display-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/intercellSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/backgroundColor",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/usesAlternatingRowBackgroundColors",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/style-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectionHighlightStyle-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridColor",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridStyleMask",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/indicatorImage(in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/setIndicatorImage(_:in:)"
      ],
      "title": "Setting Display Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Table-Styles",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/automatic",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/fullWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/inset",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/sourceList",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/plain"
      ],
      "title": "Table Styles"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableViewStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Table-Styles",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/automatic",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/fullWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/inset",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/sourceList",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/Style-swift.enum/plain"
              ],
              "title": "Table Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-Display-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/intercellSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/backgroundColor",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/usesAlternatingRowBackgroundColors",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/style-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/selectionHighlightStyle-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridColor",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/gridStyleMask",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/indicatorImage(in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/setIndicatorImage(_:in:)"
              ],
              "title": "Setting Display Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTableViewStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1fullWidth/title",
          "value": "NSTableViewStyleFullWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1fullWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyleFullWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1sourceList/title",
          "value": "NSTableViewStyleSourceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1sourceList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyleSourceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1gridColor/title",
          "value": "gridColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1gridColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gridColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum/title",
          "value": "NSTableViewStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1intercellSpacing/title",
          "value": "intercellSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1intercellSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intercellSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1style-swift.property/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1style-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1gridStyleMask/title",
          "value": "gridStyleMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1gridStyleMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gridStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1automatic/title",
          "value": "NSTableViewStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowHeight/title",
          "value": "rowHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1effectiveStyle/title",
          "value": "effectiveStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1effectiveStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1setIndicatorImage(_:in:)/title",
          "value": "setIndicatorImage:inTableColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1setIndicatorImage(_:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIndicatorImage:inTableColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1usesAlternatingRowBackgroundColors/title",
          "value": "usesAlternatingRowBackgroundColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1usesAlternatingRowBackgroundColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesAlternatingRowBackgroundColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1selectionHighlightStyle-swift.property/title",
          "value": "selectionHighlightStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1selectionHighlightStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionHighlightStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1inset/title",
          "value": "NSTableViewStyleInset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1inset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStyleInset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1indicatorImage(in:)/title",
          "value": "indicatorImageInTableColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1indicatorImage(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indicatorImageInTableColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1plain/title",
          "value": "NSTableViewStylePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1Style-swift.enum~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewStylePlain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableview/style-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableview/style-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
