{
  "abstract": [
    {
      "text": "The font is an OpenType format containing TrueType data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontFormat@kCTFontFormatOpenTypeTrueType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "openTypeTrueType"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontFormatOpenTypeTrueType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTFontFormat.openTypeTrueType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "openTypeTrueType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat": {
      "abstract": [
        {
          "text": "The recognized format of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap": {
      "abstract": [
        {
          "text": "The font is a bitmap-only format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitmap"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatBitmap"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.bitmap",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/bitmap"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript": {
      "abstract": [
        {
          "text": "The font is an OpenType format containing PostScript data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openTypePostScript"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatOpenTypePostScript"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.openTypePostScript",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/opentypepostscript"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType": {
      "abstract": [
        {
          "text": "The font is an OpenType format containing TrueType data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openTypeTrueType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatOpenTypeTrueType"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.openTypeTrueType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/opentypetruetype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript": {
      "abstract": [
        {
          "text": "The font is a recognized PostScript format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postScript"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatPostScript"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.postScript",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/postscript"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType": {
      "abstract": [
        {
          "text": "The font is a recognized TrueType format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trueType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatTrueType"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.trueType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/truetype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized": {
      "abstract": [
        {
          "text": "The font is not a recognized format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecognized"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.unrecognized",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/unrecognized"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap"
      ],
      "title": "Font Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontFormatOpenTypeTrueType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatOpenTypeTrueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap"
              ],
              "title": "Font Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontFormatOpenTypeTrueType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1bitmap/title",
          "value": "kCTFontFormatBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1bitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypeTrueType/title",
          "value": "kCTFontFormatOpenTypeTrueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypeTrueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatOpenTypeTrueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1postScript/title",
          "value": "kCTFontFormatPostScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1postScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatPostScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1unrecognized/title",
          "value": "kCTFontFormatUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1unrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1trueType/title",
          "value": "kCTFontFormatTrueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1trueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatTrueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/title",
          "value": "CTFontFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypePostScript/title",
          "value": "kCTFontFormatOpenTypePostScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypePostScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatOpenTypePostScript"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontformat/opentypetruetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontformat/opentypetruetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
