{
  "abstract": [
    {
      "text": "Create a new document view controller event based on a string value.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So15TVDocumentEventayABSScfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController": {
      "abstract": [
        {
          "text": "A view controller that represents a TVMLKit document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentViewController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event": {
      "abstract": [
        {
          "text": "Events that can be triggered on the document view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentViewController.Event",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller/event"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(_:)": {
      "abstract": [
        {
          "text": "Create a new document view controller event based on a string value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller/event/init(_:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(rawValue:)": {
      "abstract": [
        {
          "text": "Create an instance of a new document view controller event based on a string value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller/event/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializers-for-Document-View-Controller-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/Event/init(rawValue:)"
      ],
      "title": "Initializers for Document View Controller Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController~1Event/title",
          "value": "TVDocumentEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController~1Event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController~1Event/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/title",
          "value": "TVDocumentViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvdocumentviewcontroller/event/init(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
