{
  "abstract": [
    {
      "text": "A tab bar’s display mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UITabBarControllerMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Mode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Mode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITabBarController.Mode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Mode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController": {
      "abstract": [
        {
          "text": "A container view controller that manages a multiselection interface, where the selection determines which child view controller to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum": {
      "abstract": [
        {
          "text": "A tab bar’s display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Mode",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The system sets the display mode based on the tab’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarControllerModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Mode.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabBar": {
      "abstract": [
        {
          "text": "The system displays the content only as a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarControllerModeTabBar"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Mode.tabBar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.enum/tabbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabSidebar": {
      "abstract": [
        {
          "text": "The system displays the content as either a tab bar or a sidebar, depending on the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabSidebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabSidebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarControllerModeTabSidebar"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Mode.tabSidebar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.enum/tabsidebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class": {
      "abstract": [
        {
          "text": "An object for managing and configuring the sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sidebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Sidebar"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Sidebar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/sidebar-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Animating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Animating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Animating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Animating"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Sidebar.Animating",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/sidebar-swift.class/animating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/mode-swift.property": {
      "abstract": [
        {
          "text": "The display mode for a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITabBarControllerMode",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/mode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/mode-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/sidebar-swift.property": {
      "abstract": [
        {
          "text": "A tab bar’s corresponding sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarControllerSidebar",
          "text": "Sidebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/sidebar-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sidebar"
        }
      ],
      "role": "symbol",
      "title": "sidebar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/sidebar-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabSidebarItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabSidebarItem"
        }
      ],
      "role": "symbol",
      "title": "UITabSidebarItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabsidebaritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem/Request": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem/Request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "role": "symbol",
      "title": "UITabSidebarItem.Request",
      "type": "topic",
      "url": "/documentation/uikit/uitabsidebaritem/request"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITabSidebarScrollTarget"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITabSidebarScrollTarget",
      "type": "topic",
      "url": "/documentation/uikit/uitabsidebarscrolltarget"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-the-sidebar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/mode-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/sidebar-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class",
        "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem",
        "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem/Request",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Animating"
      ],
      "title": "Supporting the sidebar"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-modes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabBar",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabSidebar"
      ],
      "title": "Setting modes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabBarControllerMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-modes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabBar",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Mode-swift.enum/tabSidebar"
              ],
              "title": "Setting modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-the-sidebar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/mode-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/sidebar-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class",
                "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem",
                "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget",
                "doc://com.apple.uikit/documentation/UIKit/UITabSidebarItem/Request",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Animating"
              ],
              "title": "Supporting the sidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITabBarControllerMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1sidebar-swift.property/title",
          "value": "sidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1sidebar-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1mode-swift.property/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1mode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title",
          "value": "UITabBarController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1tabSidebar/title",
          "value": "UITabBarControllerModeTabSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1tabSidebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerModeTabSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem/title",
          "value": "UITabSidebarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabSidebarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabSidebarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem~1Request/title",
          "value": "UITabSidebarItemRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem~1Request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabSidebarItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabSidebarItem~1Request/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabSidebarItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Animating/title",
          "value": "UITabBarControllerSidebarAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Animating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebarAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Animating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebarAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/title",
          "value": "UITabBarControllerSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum/title",
          "value": "UITabBarControllerMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1automatic/title",
          "value": "UITabBarControllerModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1tabBar/title",
          "value": "UITabBarControllerModeTabBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Mode-swift.enum~1tabBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerModeTabBar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbarcontroller/mode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitabbarcontroller/mode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
