{"abstract":[{"type":"text","text":"The view controller that manages the More navigation interface."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbarcontroller/morenavigationcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbarcontroller/morenavigationcontroller"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreNavigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This property always contains a valid More navigation controller, even if a More button is not displayed on the screen. You can use the value of this property to select the More navigation controller in the tab bar interface or to compare it against the currently selected view controller."}],"type":"paragraph"},{"inlineContent":[{"text":"Do not add the object stored in this property to your tab bar interface manually. The More controller is displayed automatically by the tab bar controller as it is needed. You must also not look for the More navigation controller in the array of view controllers stored in the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","type":"reference"},{"text":" property. The tab bar controller does not include the More navigation controller in that array of objects.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"The More interface is not available in tvOS."}]}],"name":"Note","style":"note","type":"aside"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/moreNavigationController"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","doc://com.apple.uikit/documentation/UIKit/UITabBarController/setViewControllers(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UITabBarController/customizableViewControllers"],"title":"Managing the view controllers","anchor":"Managing-the-view-controllers","generated":true}],"metadata":{"navigatorTitle":[{"text":"moreNavigationController","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"UIKit"}],"title":"moreNavigationController","role":"symbol","externalID":"c:objc(cs)UITabBarController(py)moreNavigationController","roleHeading":"Instance Property","platforms":[{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreNavigationController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/customizableViewControllers":{"type":"topic","url":"/documentation/uikit/uitabbarcontroller/customizableviewcontrollers","abstract":[{"type":"text","text":"The subset of view controllers managed by this tab bar controller that can be customized."}],"navigatorTitle":[{"kind":"identifier","text":"customizableViewControllers"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/customizableViewControllers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customizableViewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]?"}],"title":"customizableViewControllers","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController":{"abstract":[{"type":"text","text":"A container view controller that manages a multiselection interface, where the selection determines which child view controller to display."}],"navigatorTitle":[{"text":"UITabBarController","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController","url":"/documentation/uikit/uitabbarcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarController","kind":"identifier"}],"role":"symbol","title":"UITabBarController","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationController":{"abstract":[{"text":"A container view controller that defines a stack-based scheme for navigating hierarchical content.","type":"text"}],"title":"UINavigationController","url":"/documentation/uikit/uinavigationcontroller","navigatorTitle":[{"kind":"identifier","text":"UINavigationController"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UINavigationController"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers":{"type":"topic","url":"/documentation/uikit/uitabbarcontroller/viewcontrollers","abstract":[{"type":"text","text":"An array of the root view controllers displayed by the tab bar interface."}],"navigatorTitle":[{"kind":"identifier","text":"viewControllers"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]?"}],"title":"viewControllers","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/setViewControllers(_:animated:)":{"type":"topic","url":"/documentation/uikit/uitabbarcontroller/setviewcontrollers(_:animated:)","abstract":[{"type":"text","text":"Sets the root view controllers of the tab bar controller."}],"navigatorTitle":[{"kind":"identifier","text":"setViewControllers:animated:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/setViewControllers(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setViewControllers"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"setViewControllers(_:animated:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/moreNavigationController":{"abstract":[{"type":"text","text":"The view controller that manages the More navigation interface."}],"role":"symbol","title":"moreNavigationController","url":"/documentation/uikit/uitabbarcontroller/morenavigationcontroller","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreNavigationController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"}],"navigatorTitle":[{"kind":"identifier","text":"moreNavigationController"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/moreNavigationController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"moreNavigationController","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"moreNavigationController","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Managing the view controllers","generated":true,"anchor":"Managing-the-view-controllers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","doc://com.apple.uikit/documentation/UIKit/UITabBarController/setViewControllers(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UITabBarController/customizableViewControllers"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController","kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"moreNavigationController"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"customizableViewControllers","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1customizableViewControllers/title","op":"replace"},{"value":[{"kind":"identifier","text":"customizableViewControllers"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1customizableViewControllers/fragments","op":"replace"},{"value":"UITabBarController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITabBarController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UITabBarController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle","op":"replace"},{"value":"UINavigationController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/title","op":"replace"},{"value":[{"kind":"identifier","text":"UINavigationController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UINavigationController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/navigatorTitle","op":"replace"},{"value":"viewControllers","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1viewControllers/title","op":"replace"},{"value":[{"text":"viewControllers","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1viewControllers/fragments","op":"replace"},{"value":"setViewControllers:animated:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1setViewControllers(_:animated:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setViewControllers:animated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1setViewControllers(_:animated:)/fragments","op":"replace"},{"value":"moreNavigationController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1moreNavigationController/title","op":"replace"},{"value":[{"kind":"identifier","text":"moreNavigationController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1moreNavigationController/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}