{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"This property nominally represents an index into the array of the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers"},{"type":"text","text":" property. However, if the selected view controller is currently the More navigation controller, this property contains the value "},{"type":"codeVoice","code":"NSNotFound"},{"text":". Setting this property changes the selected view controller to the one at the designated index in the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","type":"reference"},{"text":" array. To select the More navigation controller itself, you must change the value of the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedViewController","type":"reference"},{"text":" property instead.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"In versions of iOS prior to version 3.0, this property reflects the index of the selected tab bar item only. Attempting to set this value to an index of a view controller that is not visible in the tab bar, but is instead managed by the More navigation controller, has no effect.","type":"text"}],"type":"paragraph"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"The More interface is not available in tvOS."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)UITabBarController(py)selectedIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"selectedIndex"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false}],"title":"selectedIndex","modules":[{"name":"UIKit"}],"role":"symbol","symbolKind":"property"},"sections":[],"seeAlsoSections":[{"title":"Managing the selected tab","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedViewController"],"anchor":"Managing-the-selected-tab","generated":true}],"variants":[{"paths":["/documentation/uikit/uitabbarcontroller/selectedindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitabbarcontroller/selectedindex"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedIndex"},"abstract":[{"text":"The index of the view controller associated with the currently selected tab item.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers":{"type":"topic","url":"/documentation/uikit/uitabbarcontroller/viewcontrollers","abstract":[{"type":"text","text":"An array of the root view controllers displayed by the tab bar interface."}],"navigatorTitle":[{"kind":"identifier","text":"viewControllers"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/viewControllers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]?"}],"title":"viewControllers","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedViewController":{"kind":"symbol","type":"topic","role":"symbol","url":"/documentation/uikit/uitabbarcontroller/selectedviewcontroller","abstract":[{"type":"text","text":"The view controller associated with the currently selected tab item."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedViewController","title":"selectedViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"selectedViewController"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController":{"abstract":[{"type":"text","text":"A container view controller that manages a multiselection interface, where the selection determines which child view controller to display."}],"navigatorTitle":[{"text":"UITabBarController","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController","url":"/documentation/uikit/uitabbarcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarController","kind":"identifier"}],"role":"symbol","title":"UITabBarController","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedIndex":{"type":"topic","url":"/documentation/uikit/uitabbarcontroller/selectedindex","abstract":[{"type":"text","text":"The index of the view controller associated with the currently selected tab item."}],"navigatorTitle":[{"kind":"identifier","text":"selectedIndex"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"selectedIndex","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"introducedAt":"2.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"2.0","unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"selectedIndex"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"selectedIndex"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Managing the selected tab","anchor":"Managing-the-selected-tab","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/selectedViewController"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedIndex"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"viewControllers","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1viewControllers/title","op":"replace"},{"value":[{"text":"viewControllers","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1viewControllers/fragments","op":"replace"},{"value":"selectedViewController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1selectedViewController/title","op":"replace"},{"value":[{"kind":"identifier","text":"selectedViewController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1selectedViewController/fragments"},{"value":"UITabBarController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title"},{"value":[{"text":"UITabBarController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments"},{"value":[{"text":"UITabBarController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle"},{"value":"selectedIndex","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1selectedIndex/title"},{"value":[{"text":"selectedIndex","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1selectedIndex/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}