{"metadata":{"symbolKind":"method","modules":[{"name":"UIKit"}],"platforms":[{"introducedAt":"18.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"18.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"18.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"18.0","unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"2.0"}],"externalID":"c:objc(cs)UITabBarController(im)setTabs:animated:","navigatorTitle":[{"text":"setTabs:animated:","kind":"identifier"}],"title":"setTabs(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTabs"},{"kind":"text","text":"(["},{"text":"UITab","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITab"},{"text":"], ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbarcontroller/settabs(_:animated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbarcontroller/settabs(_:animated:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/setTabs(_:animated:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTabs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tabs","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"UITab","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITab","preciseIdentifier":"c:objc(cs)UITab"},{"text":"], ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITabBarController/setTabs(_:animated:)":{"role":"symbol","kind":"symbol","title":"setTabs(_:animated:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTabs","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITab","text":"UITab"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uitabbarcontroller/settabs(_:animated:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/setTabs(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setTabs:animated:"}],"abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UITabBarController":{"abstract":[{"type":"text","text":"A container view controller that manages a multiselection interface, where the selection determines which child view controller to display."}],"navigatorTitle":[{"text":"UITabBarController","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController","url":"/documentation/uikit/uitabbarcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarController","kind":"identifier"}],"role":"symbol","title":"UITabBarController","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITab":{"type":"topic","abstract":[{"type":"text","text":"An object that manages a tab in a tab bar."}],"kind":"symbol","url":"/documentation/uikit/uitab","navigatorTitle":[{"text":"UITab","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITab","role":"symbol","title":"UITab","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UITab","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"18.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"18.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"18.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"2.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"setTabs:animated:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTabs:animated:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController"]]}},{"op":"add","path":"/topicSections","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setTabs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<UITab *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"tabs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1setTabs(_:animated:)/title","value":"setTabs:animated:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1setTabs(_:animated:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTabs:animated:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title","value":"UITabBarController"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments","value":[{"text":"UITabBarController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle","value":[{"text":"UITabBarController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/title","value":"UITab"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/fragments","value":[{"kind":"identifier","text":"UITab"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/navigatorTitle","value":[{"kind":"identifier","text":"UITab"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}