{
  "abstract": [
    {
      "text": "A flag that indicates to enable asynchronous decompression.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableAsynchronousDecompression"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VTDecodeFrameFlags@kVTDecodeFrame_EnableAsynchronousDecompression",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kVTDecodeFrame_EnableAsynchronousDecompression"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTDecodeFrame_EnableAsynchronousDecompression"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kVTDecodeFrame_EnableAsynchronousDecompression"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kVTDecodeFrame_EnableAsynchronousDecompression"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With this bit cleared, the video decoder emits every frame before it returns. With the bit set, the decoder may process frames asynchronously, but it’s not compelled to do so.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags": {
      "abstract": [
        {
          "text": "Flags to pass to a decompression session and the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeFrameFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_1xRealTimePlayback": {
      "abstract": [
        {
          "text": "A flag that provides a hint to the video decoder that it’s ok to use a low-power mode that can’t decode faster than realtime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTDecodeFrame_1xRealTimePlayback"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_1xRealTimePlayback",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTDecodeFrame_1xRealTimePlayback",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags/kvtdecodeframe_1xrealtimeplayback"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_DoNotOutputFrame": {
      "abstract": [
        {
          "text": "A flag that provides a hint to the decompression session and video decoder not to return a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTDecodeFrame_DoNotOutputFrame"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_DoNotOutputFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTDecodeFrame_DoNotOutputFrame",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags/kvtdecodeframe_donotoutputframe"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableAsynchronousDecompression": {
      "abstract": [
        {
          "text": "A flag that indicates to enable asynchronous decompression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTDecodeFrame_EnableAsynchronousDecompression"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableAsynchronousDecompression",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTDecodeFrame_EnableAsynchronousDecompression",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags/kvtdecodeframe_enableasynchronousdecompression"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableTemporalProcessing": {
      "abstract": [
        {
          "text": "A flag that indicates to enable temporal processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTDecodeFrame_EnableTemporalProcessing"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableTemporalProcessing",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTDecodeFrame_EnableTemporalProcessing",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags/kvtdecodeframe_enabletemporalprocessing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_1xRealTimePlayback",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_DoNotOutputFrame",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags/kVTDecodeFrame_EnableTemporalProcessing"
      ],
      "title": "Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/title",
          "value": "VTDecodeFrameFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtdecodeframeflags/kvtdecodeframe_enableasynchronousdecompression"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
