{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"The default value is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbaritem/badgevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbaritem/badgevalue"]}],"seeAlsoSections":[{"title":"Configuring the item’s badge","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeColor","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setBadgeTextAttributes(_:for:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeTextAttributes(for:)"],"anchor":"Configuring-the-items-badge"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeValue"},"metadata":{"symbolKind":"property","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UITabBarItem(py)badgeValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"badgeValue","kind":"identifier"}],"platforms":[{"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"title":"badgeValue","role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The text that the item’s badge displays."}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeTextAttributes(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeTextAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":"."},{"text":"Key","preciseIdentifier":"c:@T@NSAttributedStringKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeTextAttributes(for:)","kind":"symbol","url":"/documentation/uikit/uitabbaritem/badgetextattributes(for:)","title":"badgeTextAttributes(for:)","abstract":[{"type":"text","text":"Returns the badge’s text attributes for the specified state."}],"navigatorTitle":[{"text":"badgeTextAttributesForState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badgeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeColor","kind":"symbol","url":"/documentation/uikit/uitabbaritem/badgecolor","title":"badgeColor","abstract":[{"type":"text","text":"The background color of the item’s badge."}],"navigatorTitle":[{"kind":"identifier","text":"badgeColor"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setBadgeTextAttributes(_:for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setBadgeTextAttributes"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey","text":"Key"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setBadgeTextAttributes(_:for:)","kind":"symbol","url":"/documentation/uikit/uitabbaritem/setbadgetextattributes(_:for:)","title":"setBadgeTextAttributes(_:for:)","abstract":[{"type":"text","text":"Registers text attributes that the badge uses for the specified state."}],"navigatorTitle":[{"kind":"identifier","text":"setBadgeTextAttributes:forState:"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeValue","kind":"symbol","url":"/documentation/uikit/uitabbaritem/badgevalue","title":"badgeValue","abstract":[{"text":"The text that the item’s badge displays.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"badgeValue"}]},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"2.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"2.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"badgeValue"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"badgeValue"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]}},{"op":"add","path":"/topicSections","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Configuring the item’s badge","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeColor","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setBadgeTextAttributes(_:for:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/badgeTextAttributes(for:)"],"anchor":"Configuring-the-items-badge","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"badgeValue","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"badgeTextAttributesForState:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeTextAttributes(for:)/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeTextAttributes(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"badgeTextAttributesForState:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeColor/title","value":"badgeColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeColor/fragments","value":[{"text":"badgeColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1setBadgeTextAttributes(_:for:)/title","value":"setBadgeTextAttributes:forState:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1setBadgeTextAttributes(_:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBadgeTextAttributes:forState:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeValue/title","value":"badgeValue"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1badgeValue/fragments","value":[{"text":"badgeValue","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"text":"UITabBarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"kind":"identifier","text":"UITabBarItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}