{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedUnselectedImage","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"abstract":[{"text":"Returns the finished unselected image.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Deprecated","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedSelectedImage","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setFinishedSelectedImage:withFinishedUnselectedImage:"],"anchor":"Deprecated"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image"},{"type":"text","text":" with "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal"},{"type":"text","text":" instead."}]}],"variants":[{"paths":["/documentation/uikit/uitabbaritem/finishedunselectedimage"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"finishedUnselectedImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The finished unselected image.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"UIKit"}],"platforms":[{"deprecatedAt":"7.0","introducedAt":"5.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"deprecatedAt":"7.0","introducedAt":"5.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"deprecatedAt":"13.1","introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false}],"externalID":"c:objc(cs)UITabBarItem(im)finishedUnselectedImage","navigatorTitle":[{"text":"finishedUnselectedImage","kind":"identifier"}],"role":"symbol","title":"finishedUnselectedImage","fragments":[{"text":"- ","kind":"text"},{"text":"finishedUnselectedImage","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setFinishedSelectedImage:withFinishedUnselectedImage:":{"navigatorTitle":[{"kind":"identifier","text":"setFinishedSelectedImage:withFinishedUnselectedImage:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFinishedSelectedImage:withFinishedUnselectedImage:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/setFinishedSelectedImage:withFinishedUnselectedImage:","kind":"symbol","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"Sets the finished selected and unselected images."}],"role":"symbol","title":"setFinishedSelectedImage:withFinishedUnselectedImage:","url":"/documentation/uikit/uitabbaritem/setfinishedselectedimage:withfinishedunselectedimage:"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedUnselectedImage":{"type":"topic","url":"/documentation/uikit/uitabbaritem/finishedunselectedimage","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedUnselectedImage","title":"finishedUnselectedImage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"finishedUnselectedImage"}],"abstract":[{"text":"Returns the finished unselected image.","type":"text"}],"deprecated":true,"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishedUnselectedImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uibaritem/image","type":"topic","abstract":[{"type":"text","text":"The image used to represent the item."}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal":{"navigatorTitle":[{"kind":"identifier","text":"UIImageRenderingModeAlwaysOriginal"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysOriginal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Always draw the original image, without treating it as a template."}],"role":"symbol","title":"UIImage.RenderingMode.alwaysOriginal","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/alwaysoriginal"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedSelectedImage":{"navigatorTitle":[{"kind":"identifier","text":"finishedSelectedImage"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishedSelectedImage"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/finishedSelectedImage","kind":"symbol","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"Returns the finished selected image."}],"role":"symbol","title":"finishedSelectedImage","url":"/documentation/uikit/uitabbaritem/finishedselectedimage"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1image/title","value":"image"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1image/fragments","value":[{"kind":"identifier","text":"image"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"text":"UITabBarItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"text":"UITabBarItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/title","value":"UIImageRenderingModeAlwaysOriginal","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/fragments","value":[{"text":"UIImageRenderingModeAlwaysOriginal","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"kind":"identifier","text":"UIImage"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}