{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Creates a tab bar item from a serialized instance.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbaritem/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbaritem/init(coder:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"coder","content":[{"type":"paragraph","inlineContent":[{"text":"The coder to use when deserializing the item.","type":"text"}]}]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"2.0","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"2.0","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"externalID":"c:objc(cs)UITabBarItem(im)initWithCoder:","symbolKind":"init","roleHeading":"Initializer","title":"init(coder:)","modules":[{"name":"UIKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"seeAlsoSections":[{"title":"Creating a tab bar item","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"],"anchor":"Creating-a-tab-bar-item","generated":true}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)":{"url":"/documentation/uikit/uitabbaritem/init(title:image:tag:)","role":"symbol","navigatorTitle":[{"text":"initWithTitle:image:tag:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Creates a tab bar item that displays a title and an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)","title":"init(title:image:tag:)"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)":{"abstract":[{"text":"Creates a tab bar item from a serialized instance.","type":"text"}],"url":"/documentation/uikit/uitabbaritem/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","title":"init(coder:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)":{"type":"topic","title":"init(tabBarSystemItem:tag:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","abstract":[{"type":"text","text":"Creates a tab bar item using a system-provided configuration."}],"url":"/documentation/uikit/uitabbaritem/init(tabbarsystemitem:tag:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tabBarSystemItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITabBarItem","kind":"typeIdentifier","text":"UITabBarItem"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UITabBarSystemItem","text":"SystemItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTabBarSystemItem:tag:","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder":{"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSCoder","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An abstract class that serves as the basis for objects that enable archiving and distribution of other objects."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","title":"NSCoder","url":"/documentation/foundation/nscoder","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()":{"abstract":[{"text":"Creates a tab bar item with a default configuration.","type":"text"}],"url":"/documentation/uikit/uitabbaritem/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init()","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem":{"title":"UITabBarItem.SystemItem","url":"/documentation/uikit/uitabbaritem/systemitem","abstract":[{"type":"text","text":"Constants that represent the system tab bar items."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem","navigatorTitle":[{"kind":"identifier","text":"SystemItem"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemItem"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)":{"navigatorTitle":[{"text":"initWithTitle:image:selectedImage:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","url":"/documentation/uikit/uitabbaritem/init(title:image:selectedimage:)","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"selectedImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Creates a tab bar item that toggles the image it displays when its selected state changes."}],"type":"topic","role":"symbol","title":"init(title:image:selectedImage:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"initWithCoder:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Creating-a-tab-bar-item","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"],"title":"Creating a tab bar item"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"coder","content":[{"inlineContent":[{"type":"text","text":"The coder to use when deserializing the item."}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/title","value":"initWithTitle:image:tag:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:image:tag:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/title","value":"initWithCoder:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/title","value":"initWithTabBarSystemItem:tag:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTabBarSystemItem:tag:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"kind":"identifier","text":"UITabBarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"text":"UITabBarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/title","value":"init"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/title","value":"UITabBarSystemItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/fragments","value":[{"text":"UITabBarSystemItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/navigatorTitle","value":[{"text":"UITabBarSystemItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/title","value":"initWithTitle:image:selectedImage:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTitle:image:selectedImage:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}