{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"title","content":[{"inlineContent":[{"text":"The item’s title.","type":"text"}],"type":"paragraph"}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The item’s source image."}],"type":"paragraph"}]},{"name":"tag","content":[{"type":"paragraph","inlineContent":[{"text":"An integer you use to identify the object.","type":"text"}]}]}]},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Use ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for ","type":"text"},{"code":"title","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"image","type":"codeVoice"},{"text":" to not display that element.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"By default, the item displays the same image regardless of its selected state. To display a different image for the selected state, set its ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","type":"reference"},{"text":" property. The item creates the images it displays from the alpha values in the source images. To prevent system tinting, use images with the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","type":"reference"},{"text":" rendering mode. The item clips any image that’s larger than its bounds.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Creates a tab bar item that displays a title and an image.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbaritem/init(title:image:tag:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbaritem/init(title:image:tag:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"UIKit"}],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(title:image:tag:)","externalID":"c:objc(cs)UITabBarItem(im)initWithTitle:image:tag:","navigatorTitle":[{"text":"initWithTitle:image:tag:","kind":"identifier"}],"role":"symbol","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"2.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}]},"seeAlsoSections":[{"generated":true,"title":"Creating a tab bar item","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"],"anchor":"Creating-a-tab-bar-item"}],"references":{"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal":{"navigatorTitle":[{"kind":"identifier","text":"UIImageRenderingModeAlwaysOriginal"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysOriginal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Always draw the original image, without treating it as a template."}],"role":"symbol","title":"UIImage.RenderingMode.alwaysOriginal","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/alwaysoriginal"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)":{"type":"topic","title":"init(tabBarSystemItem:tag:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","abstract":[{"type":"text","text":"Creates a tab bar item using a system-provided configuration."}],"url":"/documentation/uikit/uitabbaritem/init(tabbarsystemitem:tag:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tabBarSystemItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITabBarItem","kind":"typeIdentifier","text":"UITabBarItem"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UITabBarSystemItem","text":"SystemItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTabBarSystemItem:tag:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem":{"title":"UITabBarItem.SystemItem","url":"/documentation/uikit/uitabbaritem/systemitem","abstract":[{"type":"text","text":"Constants that represent the system tab bar items."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem","navigatorTitle":[{"kind":"identifier","text":"SystemItem"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemItem"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)":{"url":"/documentation/uikit/uitabbaritem/init(title:image:tag:)","role":"symbol","navigatorTitle":[{"text":"initWithTitle:image:tag:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Creates a tab bar item that displays a title and an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)","title":"init(title:image:tag:)"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)":{"abstract":[{"text":"Creates a tab bar item from a serialized instance.","type":"text"}],"url":"/documentation/uikit/uitabbaritem/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","title":"init(coder:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()":{"abstract":[{"text":"Creates a tab bar item with a default configuration.","type":"text"}],"url":"/documentation/uikit/uitabbaritem/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init()","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)":{"navigatorTitle":[{"text":"initWithTitle:image:selectedImage:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","url":"/documentation/uikit/uitabbaritem/init(title:image:selectedimage:)","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"selectedImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Creates a tab bar item that toggles the image it displays when its selected state changes."}],"type":"topic","role":"symbol","title":"init(title:image:selectedImage:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage":{"navigatorTitle":[{"kind":"identifier","text":"selectedImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The source image the item uses to generate its selected image."}],"role":"symbol","title":"selectedImage","url":"/documentation/uikit/uitabbaritem/selectedimage"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"initWithTitle:image:tag:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:image:tag:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Creating a tab bar item","anchor":"Creating-a-tab-bar-item","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tag:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tag","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"name":"title","content":[{"inlineContent":[{"text":"The item’s title.","type":"text"}],"type":"paragraph"}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The item’s source image."}],"type":"paragraph"}]},{"name":"tag","content":[{"inlineContent":[{"text":"An integer you use to identify the object.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"},{"value":"UIImageRenderingModeAlwaysOriginal","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/title","op":"replace"},{"value":[{"text":"UIImageRenderingModeAlwaysOriginal","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/fragments","op":"replace"},{"value":"initWithTabBarSystemItem:tag:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTabBarSystemItem:tag:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/fragments","op":"replace"},{"value":"UITabBarSystemItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITabBarSystemItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/fragments","op":"replace"},{"value":[{"text":"UITabBarSystemItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/navigatorTitle","op":"replace"},{"value":"initWithTitle:image:tag:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:image:tag:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/fragments","op":"replace"},{"value":"initWithCoder:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/fragments","op":"replace"},{"value":"init","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/fragments","op":"replace"},{"value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace"},{"value":"UITabBarItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","op":"replace"},{"value":[{"text":"UITabBarItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","op":"replace"},{"value":[{"text":"UITabBarItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","op":"replace"},{"value":"initWithTitle:image:selectedImage:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTitle:image:selectedImage:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/fragments","op":"replace"},{"value":"selectedImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/title","op":"replace"},{"value":[{"kind":"identifier","text":"selectedImage"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}