{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITabBarAppearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"When a tab bar displays the selected item, the appearance setting in this property overrides the settings in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIToolbar/scrollEdgeAppearance"},{"type":"text","text":" property of "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIToolbar"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"Use this property to apply a scroll edge appearance based on the tab bar item stored in the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem","isActive":true},{"text":" property. If the selected item’s ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","isActive":true},{"text":" property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", UIKit uses the tab bar’s scroll edge appearance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"anchor":"Configuring-the-items-appearance","title":"Configuring the item’s appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment"]}],"abstract":[{"text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar.","type":"text"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbaritem/scrolledgeappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbaritem/scrolledgeappearance"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"15.0","beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"introducedAt":"15.0","beta":false,"name":"iPadOS"},{"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","introducedAt":"15.0","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)UITabBarItem(py)scrollEdgeAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"title":"scrollEdgeAppearance","modules":[{"name":"UIKit"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","kind":"symbol","url":"/documentation/uikit/uitabbarappearance","navigatorTitle":[{"kind":"identifier","text":"UITabBarAppearance"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITabBarAppearance"}],"abstract":[{"text":"An object for customizing the appearance of a tab bar.","type":"text"}],"title":"UITabBarAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","title":"standardAppearance","abstract":[{"text":"The appearance settings for a tab bar.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbaritem/standardappearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment","title":"titlePositionAdjustment","abstract":[{"text":"The offset to apply to the title’s position.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbaritem/titlepositionadjustment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titlePositionAdjustment"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePositionAdjustment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIOffset","text":"UIOffset"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","kind":"symbol","url":"/documentation/uikit/uitabbaritem/scrolledgeappearance","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}],"abstract":[{"text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar.","type":"text"}],"title":"scrollEdgeAppearance"},"doc://com.apple.uikit/documentation/UIKit/UIToolbar/scrollEdgeAppearance":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIToolbar/scrollEdgeAppearance","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"url":"/documentation/uikit/uitoolbar/scrolledgeappearance","role":"symbol","title":"scrollEdgeAppearance","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIToolbarAppearance","kind":"typeIdentifier","text":"UIToolbarAppearance"},{"kind":"text","text":"?"}],"abstract":[{"text":"The appearance settings for a standard-height toolbar when the edge of scrollable content aligns with the edge of the toolbar.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem","title":"selectedItem","abstract":[{"text":"The currently selected item on the tab bar.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbar/selecteditem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedItem"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarItem","text":"UITabBarItem"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UIToolbar":{"type":"topic","abstract":[{"type":"text","text":"A control that displays one or more buttons along the bottom edge of your interface."}],"url":"/documentation/uikit/uitoolbar","identifier":"doc://com.apple.uikit/documentation/UIKit/UIToolbar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIToolbar","kind":"identifier"}],"navigatorTitle":[{"text":"UIToolbar","kind":"identifier"}],"title":"UIToolbar","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage":{"navigatorTitle":[{"kind":"identifier","text":"selectedImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The source image the item uses to generate its selected image."}],"role":"symbol","title":"selectedImage","url":"/documentation/uikit/uitabbaritem/selectedimage"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"15.0","deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"scrollEdgeAppearance"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"scrollEdgeAppearance"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Configuring-the-items-appearance","title":"Configuring the item’s appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"UITabBarAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/title"},{"op":"replace","value":[{"text":"UITabBarAppearance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UITabBarAppearance"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/navigatorTitle"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"kind":"identifier","text":"UITabBarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"kind":"identifier","text":"UITabBarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1standardAppearance/title","value":"standardAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1standardAppearance/fragments","value":[{"text":"standardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1titlePositionAdjustment/title","value":"titlePositionAdjustment"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1titlePositionAdjustment/fragments","value":[{"text":"titlePositionAdjustment","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/title","value":"scrollEdgeAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/fragments","value":[{"text":"scrollEdgeAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolbar~1scrollEdgeAppearance/title","value":"scrollEdgeAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolbar~1scrollEdgeAppearance/fragments","value":[{"text":"scrollEdgeAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedItem/title","value":"selectedItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedItem/fragments","value":[{"text":"selectedItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolbar/title","value":"UIToolbar"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolbar/fragments","value":[{"text":"UIToolbar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolbar/navigatorTitle","value":[{"text":"UIToolbar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/title","value":"selectedImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/fragments","value":[{"text":"selectedImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}