{"abstract":[{"type":"text","text":"The appearance settings for a tab bar."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","interfaceLanguage":"swift"},"metadata":{"title":"standardAppearance","platforms":[{"introducedAt":"13.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"13.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"13.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)UITabBarItem(py)standardAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment"],"anchor":"Configuring-the-items-appearance","generated":true,"title":"Configuring the item’s appearance"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"When a tab bar displays the selected item, the appearance setting in this property overrides the settings in the "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance","type":"reference"},{"type":"text","text":" property of "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Use this property to apply a tab bar appearance based on the tab bar item stored in the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem","isActive":true},{"type":"text","text":" property. If the selected item’s "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","isActive":true},{"type":"text","text":" property is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", UIKit uses the tab bar’s standard appearance."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbaritem/standardappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbaritem/standardappearance"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","kind":"symbol","url":"/documentation/uikit/uitabbarappearance","navigatorTitle":[{"kind":"identifier","text":"UITabBarAppearance"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITabBarAppearance"}],"abstract":[{"text":"An object for customizing the appearance of a tab bar.","type":"text"}],"title":"UITabBarAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/standardAppearance","title":"standardAppearance","abstract":[{"text":"The appearance settings for a tab bar.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbaritem/standardappearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment","title":"titlePositionAdjustment","abstract":[{"text":"The offset to apply to the title’s position.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbaritem/titlepositionadjustment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titlePositionAdjustment"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePositionAdjustment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIOffset","text":"UIOffset"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage":{"navigatorTitle":[{"kind":"identifier","text":"selectedImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The source image the item uses to generate its selected image."}],"role":"symbol","title":"selectedImage","url":"/documentation/uikit/uitabbaritem/selectedimage"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance","kind":"symbol","url":"/documentation/uikit/uitabbar/standardappearance","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"}],"abstract":[{"text":"The appearance settings for a standard-height tab bar.","type":"text"}],"title":"standardAppearance"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBar":{"kind":"symbol","role":"symbol","title":"UITabBar","navigatorTitle":[{"kind":"identifier","text":"UITabBar"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITabBar"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar","url":"/documentation/uikit/uitabbar","abstract":[{"type":"text","text":"A control that displays one or more buttons in a tab bar for selecting between different subtasks, views, or modes in an app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","kind":"symbol","url":"/documentation/uikit/uitabbaritem/scrolledgeappearance","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}],"abstract":[{"text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar.","type":"text"}],"title":"scrollEdgeAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedItem","title":"selectedItem","abstract":[{"text":"The currently selected item on the tab bar.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uitabbar/selecteditem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedItem"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarItem","text":"UITabBarItem"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"standardAppearance"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"standardAppearance"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarItem"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarItem/selectedImage","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBarItem/titlePositionAdjustment"],"anchor":"Configuring-the-items-appearance","generated":true,"title":"Configuring the item’s appearance"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":" * "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/title","op":"replace","value":"UITabBarAppearance"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/fragments","op":"replace","value":[{"kind":"identifier","text":"UITabBarAppearance"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/navigatorTitle","op":"replace","value":[{"text":"UITabBarAppearance","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1standardAppearance/title","op":"replace","value":"standardAppearance"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1standardAppearance/fragments","op":"replace","value":[{"text":"standardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1titlePositionAdjustment/title","value":"titlePositionAdjustment"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1titlePositionAdjustment/fragments","value":[{"text":"titlePositionAdjustment","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/title","value":"selectedImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1selectedImage/fragments","value":[{"text":"selectedImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/title","value":"standardAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/fragments","value":[{"text":"standardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/title","value":"UITabBar"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/fragments","value":[{"text":"UITabBar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/navigatorTitle","value":[{"kind":"identifier","text":"UITabBar"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/title","value":"scrollEdgeAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/fragments","value":[{"text":"scrollEdgeAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"text":"UITabBarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"text":"UITabBarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedItem/title","value":"selectedItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedItem/fragments","value":[{"kind":"identifier","text":"selectedItem"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}