{
  "abstract": [
    {
      "text": "Constants that represent the system tab bar items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UITabBarSystemItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SystemItem"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SystemItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITabBarItem.SystemItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SystemItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem": {
      "abstract": [
        {
          "text": "An object that describes an item in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem": {
      "abstract": [
        {
          "text": "Constants that represent the system tab bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks": {
      "abstract": [
        {
          "text": "The bookmarks system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmarks"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemBookmarks"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.bookmarks",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/bookmarks"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts": {
      "abstract": [
        {
          "text": "The contacts system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contacts"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemContacts"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.contacts",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/contacts"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads": {
      "abstract": [
        {
          "text": "The downloads system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloads"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemDownloads"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.downloads",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/downloads"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites": {
      "abstract": [
        {
          "text": "The favorites system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorites"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemFavorites"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.favorites",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/favorites"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured": {
      "abstract": [
        {
          "text": "The featured system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featured"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemFeatured"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.featured",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/featured"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history": {
      "abstract": [
        {
          "text": "The history system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "history"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemHistory"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.history",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/history"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more": {
      "abstract": [
        {
          "text": "The more system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "more"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMore"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.more",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/more"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent": {
      "abstract": [
        {
          "text": "The most recent system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostRecent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMostRecent"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.mostRecent",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/mostrecent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed": {
      "abstract": [
        {
          "text": "The most viewed system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostViewed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMostViewed"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.mostViewed",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/mostviewed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents": {
      "abstract": [
        {
          "text": "The recents system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recents"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemRecents"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.recents",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/recents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search": {
      "abstract": [
        {
          "text": "The search system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemSearch"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.search",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated": {
      "abstract": [
        {
          "text": "The top rated system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRated"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemTopRated"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.topRated",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/toprated"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()": {
      "abstract": [
        {
          "text": "Creates a tab bar item with a default configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a tab bar item from a serialized instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)": {
      "abstract": [
        {
          "text": "Creates a tab bar item using a system-provided configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tabBarSystemItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarItem",
          "text": "UITabBarItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITabBarSystemItem",
          "text": "SystemItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTabBarSystemItem:tag:"
        }
      ],
      "role": "symbol",
      "title": "init(tabBarSystemItem:tag:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/init(tabbarsystemitem:tag:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)": {
      "abstract": [
        {
          "text": "Creates a tab bar item that toggles the image it displays when its selected state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "selectedImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitle:image:selectedImage:"
        }
      ],
      "role": "symbol",
      "title": "init(title:image:selectedImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/init(title:image:selectedimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)": {
      "abstract": [
        {
          "text": "Creates a tab bar item that displays a title and an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitle:image:tag:"
        }
      ],
      "role": "symbol",
      "title": "init(title:image:tag:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/init(title:image:tag:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-tab-bar-item",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)"
      ],
      "title": "Creating a tab bar item"
    }
  ],
  "topicSections": [
    {
      "anchor": "System-items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated"
      ],
      "title": "System items"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabBarSystemItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "System-items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated"
              ],
              "title": "System items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-tab-bar-item",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(tabBarSystemItem:tag:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:tag:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(title:image:selectedImage:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init()",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/init(coder:)"
              ],
              "title": "Creating a tab bar item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITabBarSystemItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/title",
          "value": "initWithTitle:image:tag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:tag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitle:image:tag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1featured/title",
          "value": "UITabBarSystemItemFeatured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1featured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemFeatured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1downloads/title",
          "value": "UITabBarSystemItemDownloads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1downloads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemDownloads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/title",
          "value": "initWithTitle:image:selectedImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(title:image:selectedImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitle:image:selectedImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/title",
          "value": "UITabBarSystemItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title",
          "value": "UITabBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1search/title",
          "value": "UITabBarSystemItemSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1topRated/title",
          "value": "UITabBarSystemItemTopRated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1topRated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemTopRated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1recents/title",
          "value": "UITabBarSystemItemRecents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1recents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1history/title",
          "value": "UITabBarSystemItemHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1history/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1favorites/title",
          "value": "UITabBarSystemItemFavorites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1favorites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemFavorites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/title",
          "value": "initWithTabBarSystemItem:tag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(tabBarSystemItem:tag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTabBarSystemItem:tag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostRecent/title",
          "value": "UITabBarSystemItemMostRecent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostRecent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMostRecent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1bookmarks/title",
          "value": "UITabBarSystemItemBookmarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1bookmarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemBookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1contacts/title",
          "value": "UITabBarSystemItemContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1contacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostViewed/title",
          "value": "UITabBarSystemItemMostViewed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostViewed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMostViewed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1more/title",
          "value": "UITabBarSystemItemMore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1more/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbaritem/systemitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitabbaritem/systemitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
