{
  "abstract": [
    {
      "text": "The invitation has been sent, but it’s unclear if it was successfully delivered.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/sent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKParticipantScheduleStatus@EKParticipantScheduleStatusSent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sent"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKParticipantScheduleStatusSent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKParticipantScheduleStatus.sent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus": {
      "abstract": [
        {
          "text": "The participant’s scheduled status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatus"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/cannotDeliver": {
      "abstract": [
        {
          "text": "The invitation wasn’t delivered because the system is unsure of how to deliver it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotDeliver"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/cannotDeliver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusCannotDeliver"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.cannotDeliver",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/cannotdeliver"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/delivered": {
      "abstract": [
        {
          "text": "The invitation has been sent and successfully delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delivered"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/delivered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusDelivered"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.delivered",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/delivered"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/deliveryFailed": {
      "abstract": [
        {
          "text": "The invitation wasn’t delivered due to a temporary failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryFailed"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/deliveryFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusDeliveryFailed"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.deliveryFailed",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/deliveryfailed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/noPrivileges": {
      "abstract": [
        {
          "text": "The invitation wasn’t delivered because of insufficient privileges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPrivileges"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/noPrivileges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusNoPrivileges"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.noPrivileges",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/noprivileges"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/none": {
      "abstract": [
        {
          "text": "The invitation hasn’t been sent yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusNone"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.none",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/none"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/pending": {
      "abstract": [
        {
          "text": "The invitation is in the process of being sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusPending"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.pending",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/pending"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotAllowed": {
      "abstract": [
        {
          "text": "The invitation wasn’t delivered because scheduling with the participant isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusRecipientNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.recipientNotAllowed",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/recipientnotallowed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotRecognized": {
      "abstract": [
        {
          "text": "The invitation wasn’t delivered because the source doesn’t recognize the recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientNotRecognized"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotRecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusRecipientNotRecognized"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.recipientNotRecognized",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/recipientnotrecognized"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/sent": {
      "abstract": [
        {
          "text": "The invitation has been sent, but it’s unclear if it was successfully delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sent"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/sent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatusSent"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus.sent",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus/sent"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/none",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/pending",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/delivered",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotRecognized",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/noPrivileges",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/deliveryFailed",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/cannotDeliver",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotAllowed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKParticipantScheduleStatusSent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusSent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/none",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/pending",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/delivered",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotRecognized",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/noPrivileges",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/deliveryFailed",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/cannotDeliver",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus/recipientNotAllowed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKParticipantScheduleStatusSent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1delivered/title",
          "value": "EKParticipantScheduleStatusDelivered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1delivered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusDelivered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1deliveryFailed/title",
          "value": "EKParticipantScheduleStatusDeliveryFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1deliveryFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusDeliveryFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1cannotDeliver/title",
          "value": "EKParticipantScheduleStatusCannotDeliver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1cannotDeliver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusCannotDeliver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/title",
          "value": "EKParticipantScheduleStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1noPrivileges/title",
          "value": "EKParticipantScheduleStatusNoPrivileges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1noPrivileges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusNoPrivileges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1recipientNotRecognized/title",
          "value": "EKParticipantScheduleStatusRecipientNotRecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1recipientNotRecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusRecipientNotRecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1none/title",
          "value": "EKParticipantScheduleStatusNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1sent/title",
          "value": "EKParticipantScheduleStatusSent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1sent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusSent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1pending/title",
          "value": "EKParticipantScheduleStatusPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1recipientNotAllowed/title",
          "value": "EKParticipantScheduleStatusRecipientNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus~1recipientNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatusRecipientNotAllowed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekparticipantschedulestatus/sent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekparticipantschedulestatus/sent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
