{
  "abstract": [
    {
      "text": "ChaCha20 and Poly1305 (ChaCha20Poly1305).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmChaCha20Poly1305"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2EncryptionAlgorithm@NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "algorithmChaCha20Poly1305"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmChaCha20Poly1305"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "algorithmChaCha20Poly1305"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm": {
      "abstract": [
        {
          "text": "An enumeration of encryption algorithm values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithm3DES": {
      "abstract": [
        {
          "text": "Triple Data Encryption Algorithm (aka 3DES)",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithm3DES"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithm3DES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithm3DES"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithm3DES",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithm3des"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128": {
      "abstract": [
        {
          "text": "Advanced Encryption Standard 256-bit (AES256).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmAES128"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmAES128"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmAES128",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmaes128"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128GCM": {
      "abstract": [
        {
          "text": "Advanced Encryption Standard 128-bit Galois/Counter Mode (AES128GCM).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmAES128GCM"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128GCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmAES128GCM"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmAES128GCM",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmaes128gcm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256": {
      "abstract": [
        {
          "text": "Advanced Encryption Standard 256 bit (AES256).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmAES256"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmAES256"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmAES256",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmaes256"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256GCM": {
      "abstract": [
        {
          "text": "Advanced Encryption Standard 256-bit Galois/Counter Mode (AES256GCM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmAES256GCM"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256GCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmAES256GCM"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmAES256GCM",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmaes256gcm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmChaCha20Poly1305": {
      "abstract": [
        {
          "text": "ChaCha20 and Poly1305 (ChaCha20Poly1305).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmChaCha20Poly1305"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmChaCha20Poly1305",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmChaCha20Poly1305",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmchacha20poly1305"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmDES": {
      "abstract": [
        {
          "text": "Data Encryption Standard (DES)",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmDES"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmDES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2EncryptionAlgorithmDES"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2EncryptionAlgorithm.algorithmDES",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmdes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encryption-algorithms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmDES",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithm3DES",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128GCM",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256GCM"
      ],
      "title": "Encryption algorithms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encryption-algorithms",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmDES",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithm3DES",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES128GCM",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2EncryptionAlgorithm/algorithmAES256GCM"
              ],
              "title": "Encryption algorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES256GCM/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmAES256GCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES256GCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmAES256GCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithm3DES/title",
          "value": "NEVPNIKEv2EncryptionAlgorithm3DES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithm3DES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm3DES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES128GCM/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmAES128GCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES128GCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmAES128GCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/title",
          "value": "NEVPNIKEv2EncryptionAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmDES/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmDES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmDES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmDES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmChaCha20Poly1305/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmChaCha20Poly1305/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmChaCha20Poly1305"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES256/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmAES256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmAES256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES128/title",
          "value": "NEVPNIKEv2EncryptionAlgorithmAES128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2EncryptionAlgorithm~1algorithmAES128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2EncryptionAlgorithmAES128"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmchacha20poly1305"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2encryptionalgorithm/algorithmchacha20poly1305"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
