{
  "abstract": [
    {
      "text": "Prepare JSON chapters for HTTP Live Streaming.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/providing-javascript-object-notation-json-chapters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Providing JavaScript Object Notation (JSON) chapters"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Content providers supply chapter markers and other per-chapter meta data using the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "EXT-X-SESSION-DATA",
              "type": "codeVoice"
            },
            {
              "text": " tag in the HTTP Live Streaming (HLS) Multivariant Playlist.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Apple’s iOS, tvOS, and macOS platforms receive this metadata as JSON, a format that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "uses human-readable text to define data objects described in ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc7159",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This article is for informational purposes only. Apple may have patents,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "patent applications, trademarks, copyrights, or other intellectual property rights",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "covering subject matter in this document. The furnishing of this article doesn’t",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "give you a license to any patents, trademarks, copyrights, or other intellectual",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Organize-chapter-metadata",
          "level": 3,
          "text": "Organize chapter metadata",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Chapter data is information that describes a chapter using four different types:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "timing, titles, images, and general metadata. Keep the following in mind when designing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your chapter data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Each chapter requires a start time and may have an optional duration.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Each chapter may have multiple titles, images, and metadata items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Each title in a chapter has a unique ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://tools.ietf.org/html/bcp47",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "language tag.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Each metadata item in a chapter has a unique key and language.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Chapter metadata appears as an array of chapters. Each element in the array contains",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about that chapter. The first array element describes the first chapter,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the second element describes the second chapter, and so on.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each element in the chapter array is a JSON object called a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "chapter entry",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "chapter entry must contain a ",
              "type": "text"
            },
            {
              "code": "start-time",
              "type": "codeVoice"
            },
            {
              "text": ". The chapter entry should contain ",
              "type": "text"
            },
            {
              "code": "titles",
              "type": "codeVoice"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": ", and possibly ",
              "type": "text"
            },
            {
              "code": "metadata",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The chapter entry may contain an item named ",
              "type": "text"
            },
            {
              "code": "chapter",
              "type": "codeVoice"
            },
            {
              "text": " to promote human readability",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the JSON. It may also contain an item named ",
              "type": "text"
            },
            {
              "code": "duration",
              "type": "codeVoice"
            },
            {
              "text": ". Chapter entries are assumed",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to have a duration from ",
              "type": "text"
            },
            {
              "code": "start-time",
              "type": "codeVoice"
            },
            {
              "text": " to the ",
              "type": "text"
            },
            {
              "code": "start-time",
              "type": "codeVoice"
            },
            {
              "text": " of the next chapter entry,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "unless duration is specified. Chapter timing can overlap and nest, in which case",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "both ",
              "type": "text"
            },
            {
              "code": "start-time",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "duration",
              "type": "codeVoice"
            },
            {
              "text": " must be present.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Below is a simple three-chapter example of chapter data formatted as JSON. Only chapter",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "titles and start times are present. Each chapter title is in two different languages:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "English and Spanish.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[",
            "    {",
            "        \"chapter\": 1,",
            "        \"start-time\": 0,",
            "        \"titles\": [",
            "            {",
            "                \"language\": \"en\",",
            "                \"title\": \"birth\"",
            "            },",
            "            {",
            "                \"language\": \"es\",",
            "                \"title\": \"nacimiento\"",
            "            }",
            "        ]",
            "    },",
            "    {",
            "        \"chapter\": 2,",
            "        \"start-time\": 500.1,",
            "        \"titles\": [",
            "            {",
            "                \"language\": \"en\",",
            "                \"title\": \"life\"",
            "            },",
            "            {",
            "                \"language\": \"es\",",
            "                \"title\": \"vida\"",
            "            }",
            "        ]",
            "    },",
            "    {",
            "        \"chapter\": 3,",
            "        \"start-time\": 1200.2,",
            "        \"titles\": [",
            "            {",
            "                \"language\": \"en\",",
            "                \"title\": \"death\"",
            "            },",
            "            {",
            "                \"language\": \"es\",",
            "                \"title\": \"muerte\"",
            "            }",
            "        ]",
            "    }",
            "]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s the general layout of the JSON chapter data format. The JavaScript comments",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "aren’t legal JSON and are for illustrative purposes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[",
            "    {",
            "        \"chapter\": number,",
            "        \"start-time\": number,",
            "        \"duration\": number,",
            "        \"titles\": [",
            "            {",
            "                \"language\": string,",
            "                \"title\": string",
            "            },",
            "            // … (for each language for this chapter)",
            "        ],",
            "        \"images\": [",
            "            {",
            "                \"image-category\": string,",
            "                \"pixel-width\": number,",
            "                \"pixel-height\": number,",
            "                \"url\": string",
            "            },",
            "            // … (for each image type for this chapter)",
            "        ],",
            "        \"metadata\": [",
            "            {",
            "                \"key\": string,",
            "                \"value\": object | number | string | array,",
            "                \"language\": string,",
            "            },",
            "            // … for each metadata value for this chapter",
            "        ],",
            "    },",
            "    // … for each chapter",
            "]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-titles",
          "level": 3,
          "text": "Add titles",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Chapter entries may contain a ",
              "type": "text"
            },
            {
              "code": "titles",
              "type": "codeVoice"
            },
            {
              "text": " JSON array. Each element of a ",
              "type": "text"
            },
            {
              "code": "titles",
              "type": "codeVoice"
            },
            {
              "text": " array",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is a JSON object that must contain both a ",
              "type": "text"
            },
            {
              "code": "language",
              "type": "codeVoice"
            },
            {
              "text": " BCP 47 string and a ",
              "type": "text"
            },
            {
              "code": "title",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "string with the title for that chapter, written in the language specified by the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "language",
              "type": "codeVoice"
            },
            {
              "text": " string. All strings must be encoded using UTF-8. Set the language to ",
              "type": "text"
            },
            {
              "code": "“und”",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "if the title strings are language-neutral, such as a numeric string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-images",
          "level": 3,
          "text": "Add images",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Chapter entries may contain an ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": " JSON array. Each element of an ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": " array",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is a JSON object containing information about images for each chapter. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": " array may contain an element for a thumbnail image and an element for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an HD image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each element in an ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": " array must contain an ",
              "type": "text"
            },
            {
              "code": "image-category",
              "type": "codeVoice"
            },
            {
              "text": " string, a ",
              "type": "text"
            },
            {
              "code": "pixel-width",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "number, a ",
              "type": "text"
            },
            {
              "code": "pixel-height",
              "type": "codeVoice"
            },
            {
              "text": " number, and a ",
              "type": "text"
            },
            {
              "code": "url",
              "type": "codeVoice"
            },
            {
              "text": " string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "image-category",
              "type": "codeVoice"
            },
            {
              "text": " string should be the same across chapters for images that are",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "similar. In the three-chapter case mentioned above, you would use one string for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the thumbnails (",
              "type": "text"
            },
            {
              "code": "thumbnail",
              "type": "codeVoice"
            },
            {
              "text": ") and a different string for the HD images (",
              "type": "text"
            },
            {
              "code": "hd",
              "type": "codeVoice"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "url",
              "type": "codeVoice"
            },
            {
              "text": " string must be an absolute or relative URL to the image data associated",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with the chapter. Relative URLs are relative to the path that contained the JSON",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "chapter document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "images",
              "type": "codeVoice"
            },
            {
              "text": " files themselves may be in a variety of image formats. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "JPEG, PNG, and TIFF are all supported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-metadata",
          "level": 3,
          "text": "Add metadata",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Chapter entries may also contain a metadata JSON array. Each element of a ",
              "type": "text"
            },
            {
              "code": "metadata",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "array is a JSON object containing metadata for that chapter. Each metadata array",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "element contains a mandatory ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "value",
              "type": "codeVoice"
            },
            {
              "text": ", along with an optional ",
              "type": "text"
            },
            {
              "code": "language",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "BCP-47 string. The key element must be a string. The value element can be a string,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "number, array, or object. If any ",
              "type": "text"
            },
            {
              "code": "value",
              "type": "codeVoice"
            },
            {
              "text": " is a URI, it’s passed as-is. The system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "has no way to interpret a relative URI in that context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-a-main-playlist",
          "level": 3,
          "text": "Specify a main playlist",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "JSON-formatted chapter data must be specified in a main playlist using the ",
              "type": "text"
            },
            {
              "code": "EXT-X-SESSION-DATA",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tag for use in HTTP Live Streaming.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The DATA-ID attribute of the ",
              "type": "text"
            },
            {
              "code": "EXT-X-SESSION-DATA",
              "type": "codeVoice"
            },
            {
              "text": " must be ",
              "type": "text"
            },
            {
              "code": "com.apple.hls.chapters",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The URI attribute must point to the JSON-formatted chapter data. The URI may be absolute",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or relative to the path that contained the main playlist, as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "#EXT-X-SESSION-DATA:DATA-ID=\"com.apple.hls.chapters\",URI=\"http://meta.example.com/movie403/chapters.json\"",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Perform-validation",
          "level": 3,
          "text": "Perform validation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following JSON schema to validate your chapter data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "    \"$schema\": \"http://json-schema.org/draft-04/schema#\",",
            "    \"title\": \"HLS Chapter Data\",",
            "    \"description\": \"HLS chapter data format\",",
            "    \"type\": \"array\",",
            "    \"items\": {",
            "        \"description\": \"chapter entry\",",
            "        \"type\": \"object\",",
            "        \"properties\": {",
            "            \"chapter\": {",
            "                \"description\": \"Chapter number (optional)\",",
            "                \"type\": \"number\",",
            "                \"minimum\": 1",
            "            },",
            "            \"start-time\": {",
            "                \"description\": \"Chapter start time\",",
            "                \"type\": \"number\",",
            "                \"minimum\": 0",
            "            },",
            "            \"duration\": {",
            "                \"description\": \"Chapter duration (optional)\",",
            "                \"type\": \"number\",",
            "                \"minimum\": 0,",
            "                \"exclusiveMinimum\": true",
            "            },",
            "            \"titles\": {",
            "                \"description\": \"List of titles by language for chapter (optional)\",",
            "                \"type\": \"array\",",
            "                \"items\": {",
            "                    \"description\": \"Title object\",",
            "                    \"type\": \"object\",",
            "                    \"properties\": {",
            "                        \"language\": {",
            "                            \"description\": \"BCP 47 language code; und for undefined\",",
            "                            \"type\": \"string\"",
            "                        },",
            "                        \"title\": {",
            "                            \"description\": \"Chapter title string\",",
            "                            \"type\": \"string\"",
            "                        }",
            "                    },",
            "                    \"required\": [\"language\", \"title\"]",
            "                }",
            "            },",
            "            \"images\": {",
            "                \"description\": \"List of images for chapter (optional)\",",
            "                \"type\": \"array\",",
            "                \"items\": {",
            "                    \"description\": \"Image object\",",
            "                    \"type\": \"object\",",
            "                    \"properties\": {",
            "                        \"image-category\": {",
            "                            \"description\": \"Image category\",",
            "                            \"type\": \"string\"",
            "                        },",
            "                        \"pixel-width\": {",
            "                            \"description\": \"Pixel width\",",
            "                            \"type\": \"integer\",",
            "                            \"minimum\": 0,",
            "                            \"exclusiveMinimum\": true",
            "                        },",
            "                        \"pixel-height\": {",
            "                            \"description\": \"Pixel height\",",
            "                            \"type\": \"integer\",",
            "                            \"minimum\": 0,",
            "                            \"exclusiveMinimum\": true",
            "                        },",
            "                        \"url\": {",
            "                            \"description\": \"URL to image (relative or absolute)\",",
            "                            \"type\": \"string\"",
            "                        }",
            "                    },",
            "                    \"required\": [\"image-category\", \"pixel-width\", \"pixel-height\", \"url\"]",
            "                }",
            "            },",
            "            \"metadata\": {",
            "                \"description\": \"List of metadata entries for chapter (optional)\",",
            "                \"type\": \"array\",",
            "                \"items\": {",
            "                    \"description\": \"Metadata object\",",
            "                    \"type\": \"object\",",
            "                    \"properties\": {",
            "                        \"key\": {",
            "                            \"description\": \"Key value name\",",
            "                            \"type\": \"string\"",
            "                        },",
            "                        \"value\": {",
            "                            \"description\": \"Metadata value\",",
            "                            \"type\": [\"string\", \"number\", \"boolean\", \"array\", \"object\"]",
            "                        },",
            "                        \"language\": {",
            "                            \"description\": \"BCP 47 language code (optional)\",",
            "                            \"type\": \"string\"",
            "                        }",
            "                    },",
            "                    \"required\": [\"key\", \"value\"]",
            "                }",
            "            }",
            "        },",
            "        \"required\": [\"start-time\"]",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Test-and-access-chapter-data",
          "level": 3,
          "text": "Test and access chapter data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use QuickTime Player to quickly test your HLS streams with chapter data. QuickTime",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Player will display a chapter pop-up control (with images, if you have them). In",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "QuickTime Player, use File > Open Location or ⌘L to open a URL. QuickTime Player",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "displays your chapters in the order they appear in the JSON file, without sorting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or rearranging them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " contains details",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of how to access chapter data. The methods described return an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "objects, one object for each chapter. The order of the groups matches the order of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the JSON file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each ",
              "type": "text"
            },
            {
              "code": "AVTimedMetadataGroup",
              "type": "codeVoice"
            },
            {
              "text": " object has a start time, end time, and a list of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Every item from the titles, images, and metadata arrays in the JSON is in the list",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of metadata items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Images have an ",
              "type": "text"
            },
            {
              "code": "extraAttributes",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. This dictionary contains a key ",
              "type": "text"
            },
            {
              "code": "“iTunesImageResolution”",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "whose value is a dictionary that contains the ",
              "type": "text"
            },
            {
              "code": "pixel-width",
              "type": "codeVoice"
            },
            {
              "text": ",  ",
              "type": "text"
            },
            {
              "code": "pixel-height",
              "type": "codeVoice"
            },
            {
              "text": ", and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "image-category",
              "type": "codeVoice"
            },
            {
              "text": " from the JSON entry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The metadata item keys are placed in the key space ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataKeySpace/quickTimeMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This key space defines its key values to be expressed as reverse-DNS strings. This",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "allows you to define your own keys in a well-established way that avoids collisions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming": {
      "abstract": [
        {
          "text": "Send audio and video to iOS, tvOS, and macOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming",
      "kind": "article",
      "role": "collection",
      "title": "HTTP Live Streaming",
      "type": "topic",
      "url": "/documentation/http-live-streaming"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/about-the-common-media-application-format-with-http-live-streaming-hls": {
      "abstract": [
        {
          "text": "Learn the Common Media Application Format as it applies to HLS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/about-the-common-media-application-format-with-http-live-streaming-hls",
      "kind": "article",
      "role": "article",
      "title": "About the Common Media Application Format with HTTP Live Streaming (HLS)",
      "type": "topic",
      "url": "/documentation/http-live-streaming/about-the-common-media-application-format-with-http-live-streaming-hls"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/adjusting-anchor-loudness": {
      "abstract": [
        {
          "text": "Adjust anchor loudness when measurements of speech-gated loudness for a full mix",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "may be inaccurate, such as when speech activity is low.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/adjusting-anchor-loudness",
      "kind": "article",
      "role": "article",
      "title": "Adjusting anchor loudness",
      "type": "topic",
      "url": "/documentation/http-live-streaming/adjusting-anchor-loudness"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/enabling-low-latency-http-live-streaming-hls": {
      "abstract": [
        {
          "text": "Add Low-Latency HLS to your content streams to maintain scalability.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/enabling-low-latency-http-live-streaming-hls",
      "kind": "article",
      "role": "article",
      "title": "Enabling Low-Latency HTTP Live Streaming (HLS)",
      "type": "topic",
      "url": "/documentation/http-live-streaming/enabling-low-latency-http-live-streaming-hls"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/hls-authoring-specification-for-apple-devices": {
      "abstract": [
        {
          "text": "Learn the requirements for live and on-demand audio and video content delivery using",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "HLS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/hls-authoring-specification-for-apple-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HTTP Live Streaming (HLS) authoring specification for Apple devices",
      "type": "topic",
      "url": "/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/links-to-additional-specifications-and-videos": {
      "abstract": [
        {
          "text": "Review additional specifications and documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/links-to-additional-specifications-and-videos",
      "kind": "article",
      "role": "article",
      "title": "Links to additional specifications and videos",
      "type": "topic",
      "url": "/documentation/http-live-streaming/links-to-additional-specifications-and-videos"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/providing-metadata-for-xhe-aac-video-soundtracks": {
      "abstract": [
        {
          "text": "Ensure volume normalization by including metadata for loudness and dynamic range",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/providing-metadata-for-xhe-aac-video-soundtracks",
      "kind": "article",
      "role": "article",
      "title": "Providing metadata for xHE-AAC video soundtracks",
      "type": "topic",
      "url": "/documentation/http-live-streaming/providing-metadata-for-xhe-aac-video-soundtracks"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/using-content-protection-systems-with-hls": {
      "abstract": [
        {
          "text": "Adding encryption keys to media playlists",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/using-content-protection-systems-with-hls",
      "kind": "article",
      "role": "article",
      "title": "Using content protection systems with HLS",
      "type": "topic",
      "url": "/documentation/http-live-streaming/using-content-protection-systems-with-hls"
    },
    "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/videos-about-hls": {
      "abstract": [
        {
          "text": "Review informational videos about HTTP Live Streaming.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/videos-about-hls",
      "kind": "article",
      "role": "article",
      "title": "Videos about HLS",
      "type": "topic",
      "url": "/documentation/http-live-streaming/videos-about-hls"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAsset": {
      "abstract": [
        {
          "text": "An object that models timed audiovisual media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAsset",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAsset",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAsset"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem": {
      "abstract": [
        {
          "text": "A metadata item for an audiovisual asset or one of its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetadataItem",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVMetadataItem"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataKeySpace/quickTimeMetadata": {
      "abstract": [
        {
          "text": "The QuickTime metadata key space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKeySpace",
          "text": "AVMetadataKeySpace"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataKeySpace/quickTimeMetadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "quickTimeMetadata",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVMetadataKeySpace/quickTimeMetadata"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup": {
      "abstract": [
        {
          "text": "A collection of metadata items that are valid for use during a specific time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVTimedMetadataGroup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVTimedMetadataGroup",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVTimedMetadataGroup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://tools.ietf.org/html/bcp47": {
      "identifier": "https://tools.ietf.org/html/bcp47",
      "title": "BCP 47",
      "titleInlineContent": [
        {
          "text": "BCP 47",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/bcp47"
    },
    "https://tools.ietf.org/html/rfc7159": {
      "identifier": "https://tools.ietf.org/html/rfc7159",
      "title": "RFC 7159",
      "titleInlineContent": [
        {
          "text": "RFC 7159",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc7159"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifications-and-other-documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/hls-authoring-specification-for-apple-devices",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/using-content-protection-systems-with-hls",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/about-the-common-media-application-format-with-http-live-streaming-hls",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/enabling-low-latency-http-live-streaming-hls",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/links-to-additional-specifications-and-videos",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/videos-about-hls",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/providing-metadata-for-xhe-aac-video-soundtracks",
        "doc://com.apple.HTTP-Live-Streaming/documentation/HTTP-Live-Streaming/adjusting-anchor-loudness"
      ],
      "title": "Specifications and other documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVTimedMetadataGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVTimedMetadataGroup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMetadataGroup",
              "text": "AVMetadataGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVMetadataKeySpace~1quickTimeMetadata/title",
          "value": "AVMetadataKeySpaceQuickTimeMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVMetadataKeySpace~1quickTimeMetadata/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKeySpace",
              "text": "AVMetadataKeySpace"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetadataKeySpaceQuickTimeMetadata"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVAsset/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAsset"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVMetadataItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetadataItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
