{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImageAnimationStatus@kCGImageAnimationStatus_ParameterError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parameterError"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageAnimationStatus_ParameterError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CGImageAnimationStatus.parameterError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parameterError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the result of animating an image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocationFailure"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_AllocationFailure"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.allocationFailure",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/allocationfailure"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptInputImage"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_CorruptInputImage"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.corruptInputImage",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/corruptinputimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompleteInputImage"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_IncompleteInputImage"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.incompleteInputImage",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/incompleteinputimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterError"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_ParameterError"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.parameterError",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/parametererror"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedFormat"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_UnsupportedFormat"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.unsupportedFormat",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/unsupportedformat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animation-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat"
      ],
      "title": "Animation Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageAnimationStatus_ParameterError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_ParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animation-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat"
              ],
              "title": "Animation Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCGImageAnimationStatus_ParameterError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/title",
          "value": "CGImageAnimationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1incompleteInputImage/title",
          "value": "kCGImageAnimationStatus_IncompleteInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1incompleteInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_IncompleteInputImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1unsupportedFormat/title",
          "value": "kCGImageAnimationStatus_UnsupportedFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1unsupportedFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_UnsupportedFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1parameterError/title",
          "value": "kCGImageAnimationStatus_ParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1parameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_ParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1corruptInputImage/title",
          "value": "kCGImageAnimationStatus_CorruptInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1corruptInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_CorruptInputImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1allocationFailure/title",
          "value": "kCGImageAnimationStatus_AllocationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1allocationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_AllocationFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimageanimationstatus/parametererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimageanimationstatus/parametererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
