{
  "abstract": [
    {
      "text": "Reserved for when the error does not fit in another category above.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/unknownError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKSessionError@GKSessionUnknownError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknownError"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKSessionUnknownError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "3.0",
        "message": "No longer supported",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKSessionError.Code.unknownError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknownError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSession": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object provides the ability to discover and connect to nearby iOS devices using Bluetooth or Wi-fi.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "role": "symbol",
      "title": "GKSession",
      "type": "topic",
      "url": "/documentation/gamekit/gksession"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the session error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cancelledError": {
      "abstract": [
        {
          "text": "A peer that invited the session to connect to them canceled the connection request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelledError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cancelledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionCancelledError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.cancelledError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/cancellederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cannotEnableError": {
      "abstract": [
        {
          "text": "Bluetooth is not currently available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotEnableError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cannotEnableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionCannotEnableError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.cannotEnableError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/cannotenableerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionClosedError": {
      "abstract": [
        {
          "text": "The connection to another peer closed unexpectedly.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionClosedError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionClosedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionConnectionClosedError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.connectionClosedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/connectionclosederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionFailedError": {
      "abstract": [
        {
          "text": "The attempt to establish a connection with another peer failed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailedError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionFailedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionConnectionFailedError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.connectionFailedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/connectionfailederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectivityError": {
      "abstract": [
        {
          "text": "An error occurred in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object’s connection code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectivityError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectivityError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionConnectivityError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.connectivityError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/connectivityerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/dataTooBigError": {
      "abstract": [
        {
          "text": "The data your application attempted to send was too large for the session to transmit in a single call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataTooBigError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/dataTooBigError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionDataTooBigError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.dataTooBigError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/datatoobigerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/declinedError": {
      "abstract": [
        {
          "text": "The peer your application tried to connect to refused the connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declinedError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/declinedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionDeclinedError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.declinedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/declinederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/inProgressError": {
      "abstract": [
        {
          "text": "The peer your application attempted to connect to has already requested a connection to your session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgressError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/inProgressError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionInProgressError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.inProgressError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/inprogresserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/internalError": {
      "abstract": [
        {
          "text": "A serious error occurred inside ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionInternalError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.internalError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/internalerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/invalidParameterError": {
      "abstract": [
        {
          "text": "A parameter had an unexpected value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/invalidParameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionInvalidParameterError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.invalidParameterError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/invalidparametererror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/notConnectedError": {
      "abstract": [
        {
          "text": "Reserved for future use.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnectedError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/notConnectedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionNotConnectedError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.notConnectedError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/notconnectederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/peerNotFoundError": {
      "abstract": [
        {
          "text": "A peer with the specified ",
          "type": "text"
        },
        {
          "code": "peerID",
          "type": "codeVoice"
        },
        {
          "text": " string could not be found.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerNotFoundError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/peerNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionPeerNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.peerNotFoundError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/peernotfounderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/systemError": {
      "abstract": [
        {
          "text": "An error occurred outside of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object’s control, such as memory allocation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/systemError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionSystemError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.systemError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/systemerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/timedOutError": {
      "abstract": [
        {
          "text": "The operation could not be completed in the specified timeout period.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOutError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/timedOutError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionTimedOutError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.timedOutError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/timedouterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/transportError": {
      "abstract": [
        {
          "text": "An error occurred in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object’s transport code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/transportError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionTransportError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.transportError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/transporterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/unknownError": {
      "abstract": [
        {
          "text": "Reserved for when the error does not fit in another category above.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionUnknownError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code/unknownerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/invalidParameterError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/peerNotFoundError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/declinedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/timedOutError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cancelledError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionFailedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionClosedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/dataTooBigError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/notConnectedError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cannotEnableError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/inProgressError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectivityError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/transportError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/internalError",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/systemError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.4",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "3.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKSessionUnknownError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/invalidParameterError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/peerNotFoundError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/declinedError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/timedOutError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cancelledError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionFailedError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectionClosedError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/dataTooBigError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/notConnectedError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/cannotEnableError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/inProgressError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/connectivityError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/transportError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/internalError",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code/systemError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKSessionUnknownError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1cannotEnableError/title",
          "value": "GKSessionCannotEnableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1cannotEnableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionCannotEnableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1cancelledError/title",
          "value": "GKSessionCancelledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1cancelledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionCancelledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1inProgressError/title",
          "value": "GKSessionInProgressError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1inProgressError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionInProgressError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1declinedError/title",
          "value": "GKSessionDeclinedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1declinedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDeclinedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1peerNotFoundError/title",
          "value": "GKSessionPeerNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1peerNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionPeerNotFoundError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1transportError/title",
          "value": "GKSessionTransportError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1transportError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionTransportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1dataTooBigError/title",
          "value": "GKSessionDataTooBigError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1dataTooBigError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDataTooBigError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1unknownError/title",
          "value": "GKSessionUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectionFailedError/title",
          "value": "GKSessionConnectionFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectionFailedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionConnectionFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectivityError/title",
          "value": "GKSessionConnectivityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectivityError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionConnectivityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/title",
          "value": "GKSessionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1timedOutError/title",
          "value": "GKSessionTimedOutError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1timedOutError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionTimedOutError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectionClosedError/title",
          "value": "GKSessionConnectionClosedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1connectionClosedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionConnectionClosedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1invalidParameterError/title",
          "value": "GKSessionInvalidParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1invalidParameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionInvalidParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1systemError/title",
          "value": "GKSessionSystemError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1systemError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionSystemError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1notConnectedError/title",
          "value": "GKSessionNotConnectedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1notConnectedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionNotConnectedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1internalError/title",
          "value": "GKSessionInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/title",
          "value": "GKSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gksessionerror-swift.struct/code/unknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gksessionerror-swift.struct/code/unknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
