{
  "abstract": [
    {
      "text": "The identifier of the deleted record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So10CKDatabaseC8CloudKitE16RecordZoneChangeO8DeletionV8recordIDSo08CKRecordI0Cvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recordID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordID",
        "text": "ID"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "recordID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recordID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordID",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase": {
      "abstract": [
        {
          "text": "An object that represents a collection of record zones and subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange": {
      "abstract": [
        {
          "text": "Objects that indicate the type of record zone change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecordZoneChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecordZoneChange"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase.RecordZoneChange",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/recordzonechange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion": {
      "abstract": [
        {
          "text": "A record zone change that represents the deletion of a record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Deletion"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Deletion"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase.RecordZoneChange.Deletion",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/recordzonechange/deletion"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordID": {
      "abstract": [
        {
          "text": "The identifier of the deleted record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordID",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/recordzonechange/deletion/recordid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordType": {
      "abstract": [
        {
          "text": "The record type of the deleted record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE10RecordTypea",
          "text": "RecordType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordType",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordType",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/recordzonechange/deletion/recordtype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord": {
      "abstract": [
        {
          "text": "A collection of key-value pairs that store your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "role": "symbol",
      "title": "CKRecord",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a record in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKRecord.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-Deleted-Record",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/RecordZoneChange/Deletion/recordType"
      ],
      "title": "Identifying the Deleted Record"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/title",
          "value": "CKRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/title",
          "value": "CKRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/title",
          "value": "CKDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckdatabase/recordzonechange/deletion/recordid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
