{
  "abstract": [
    {
      "text": "A technique that uses LiDAR depth data to measure body height, in meters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNHumanBodyPose3DObservationHeightEstimation@VNHumanBodyPose3DObservationHeightEstimationMeasured",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "measured"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNHumanBodyPose3DObservation.HeightEstimation.measured"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "measured"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation": {
      "abstract": [
        {
          "text": "An observation that provides the 3D body points the request recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that identify body height estimation techniques.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HeightEstimation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HeightEstimation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured": {
      "abstract": [
        {
          "text": "A technique that uses LiDAR depth data to measure body height, in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measured"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation.measured",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/measured"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference": {
      "abstract": [
        {
          "text": "A technique that uses a reference height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reference"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservationHeightEstimationReference"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation.reference",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/reference"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Techniques",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference"
      ],
      "title": "Techniques"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Techniques",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference"
              ],
              "title": "Techniques"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1reference/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimationReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1reference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimationReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1measured/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1measured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/title",
          "value": "VNHumanBodyPose3DObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/measured"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/measured"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
