{
  "abstract": [
    {
      "text": "Learn how a node conforms to its coordinate systems.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/about-spritekit-coordinate-systems"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "About SpriteKit Coordinate Systems"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a node is placed in the node tree, its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property places it within a coordinate system provided by its parent. SpriteKit uses the same coordinate system on both iOS and macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Points-as-Position-Units",
          "level": 3,
          "text": "Points as Position Units",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a node is placed in the node tree, its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property places it within a coordinate system provided by its parent. SpriteKit uses the same coordinate system on both iOS and macOS. The figure below shows the SpriteKit coordinate system. Coordinate values are measured in points, as in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; where necessary, points are converted to pixels when the scene is rendered. A positive ",
              "type": "text"
            },
            {
              "code": "x",
              "type": "codeVoice"
            },
            {
              "text": " coordinate goes to the right and a positive ",
              "type": "text"
            },
            {
              "code": "y",
              "type": "codeVoice"
            },
            {
              "text": " coordinate goes up the screen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3044993",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Polar-Coordinate-Rotation",
          "level": 3,
          "text": "Polar Coordinate Rotation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SpriteKit also has a standard rotation convention.  shows the polar coordinate convention. An angle of ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " radians specifies the positive x axis. A positive angle is in the counterclockwise direction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3044989",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Nodes are rotated by setting their ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zRotation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the required angle in radians. If you prefer to work in degrees, the following code shows how you can write an extension to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that converts between the two. The following example rotates ",
              "type": "text"
            },
            {
              "code": "spriteNode",
              "type": "codeVoice"
            },
            {
              "text": " by 30 degrees counterclockwise.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension CGFloat {",
            "    func degreesToRadians() -> CGFloat {",
            "        return self * CGFloat.pi / 180",
            "    }",
            "}",
            "",
            "let rabbitTexture = SKTexture(imageNamed: \"rabbit.png\")",
            "",
            "let spriteNode = SKSpriteNode(texture: rabbitTexture)",
            "",
            "spriteNode.zRotation = CGFloat(30).degreesToRadians()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/AppKit"
    },
    "doc://com.apple.documentation/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/UIKit"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cgfloat": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/spritekit/sknode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/children": {
      "abstract": [
        {
          "text": "The node’s children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKNode",
          "text": "SKNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "children"
        }
      ],
      "role": "symbol",
      "title": "children",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/children"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/parent": {
      "abstract": [
        {
          "text": "The node’s parent node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKNode",
          "text": "SKNode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/parent"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position": {
      "abstract": [
        {
          "text": "The position of the node in its parent’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/position"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/scene": {
      "abstract": [
        {
          "text": "The scene node that contains this node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKScene",
          "text": "SKScene"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/scene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scene"
        }
      ],
      "role": "symbol",
      "title": "scene",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/scene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zRotation": {
      "abstract": [
        {
          "text": "The Euler rotation about the z axis (in radians).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zRotation"
        }
      ],
      "role": "symbol",
      "title": "zRotation",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/zrotation"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    },
    "media-3044989": {
      "alt": "Polar coordinate conventions (rotation)",
      "identifier": "media-3044989",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a22282ae53de69c37c5d90ca04a77365/media-3044989@2x.png"
        }
      ]
    },
    "media-3044993": {
      "alt": "SpriteKit coordinate system",
      "identifier": "media-3044993",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fde746ee70bec583c7760b74efe90ae0/media-3044993@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Related-Nodes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/scene",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/parent",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/children"
      ],
      "title": "Accessing Related Nodes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Related-Nodes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/scene",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/parent",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/children"
              ],
              "title": "Accessing Related Nodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1scene/title",
          "value": "scene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1scene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/title",
          "value": "SKNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1parent/title",
          "value": "parent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1zRotation/title",
          "value": "zRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1zRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1children/title",
          "value": "children"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "children"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/about-spritekit-coordinate-systems"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/about-spritekit-coordinate-systems"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
