{
  "abstract": [
    {
      "text": "Understand how SpriteKit layers your scene’s nodes from top to bottom.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/about-node-drawing-order"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "About Node Drawing Order"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The standard behavior for scene rendering follows a simple pair of rules (as shown in the figure below):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A parent draws its content before rendering its children.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Children are rendered in the order in which they appear in the child array.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2985165",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the figure above, the helicopter body and its components are all children of the ",
              "type": "text"
            },
            {
              "code": "sky",
              "type": "codeVoice"
            },
            {
              "text": " node. So the scene renders its content as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene renders itself, clearing its contents to its background color.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene renders the ",
                      "type": "text"
                    },
                    {
                      "code": "sky",
                      "type": "codeVoice"
                    },
                    {
                      "text": " node.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "sky",
                      "type": "codeVoice"
                    },
                    {
                      "text": " node renders its children—the helicopter body and its components—in the order they were added as children.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Draw-Order-Relative-to-the-Parent-Node",
          "level": 3,
          "text": "Draw Order Relative to the Parent Node",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Maintaining the order of a node’s children can be a lot of work. Instead, you can give each node an explicit height in the scene. You do this by setting a node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zPosition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. The ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " is the node’s height relative to its parent node, much as a node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property represents its x and y position relative to its parent’s position. So you use ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " to place a node above or below the parent’s position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you take ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " into account, here is how the node tree is rendered:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Each node’s global ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is calculated by recursively adding its ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to its parent’s ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Nodes are drawn in order from smallest ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to largest ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If two nodes share the same ",
                      "type": "text"
                    },
                    {
                      "code": "zPosition",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ancestors are rendered first, and siblings are rendered in child order.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Sibling-Order-Performance",
          "level": 3,
          "text": "Sibling Order Performance",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SpriteKit uses a deterministic rendering order based on the height nodes and their positions in the node tree. But, because the rendering order is so deterministic, SpriteKit may be unable to apply some rendering optimizations that it might otherwise apply. For example, it might be better if SpriteKit could gather all of the nodes that share the same texture and drawing mode and draw them with a single drawing pass. To enable these sorts of optimizations, you set the view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/ignoresSiblingOrder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you ignore sibling order, SpriteKit uses the graphics hardware to render the nodes so that they appear sorted by ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": ". It sorts nodes into a drawing order that reduces the number of draw calls needed to render the scene. But with this optimized drawing order, you cannot predict the rendering order for nodes that share the same height. The rendering order may change each time a new frame is rendered. In many cases, the drawing order of these nodes is not important. For example, if the nodes are at the same height but do not overlap on screen, they can be drawn in any order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The figure below shows an example of a tree that uses ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " to determine the rendering order. In this example, the body of the helicopter is at a height of 100, and its children are rendered relative to its height. The two rotor nodes share the same height but do not overlap.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3044936",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interleaved-Child-Nodes-from-Different-Parents",
          "level": 3,
          "text": "Interleaved Child Nodes from Different Parents",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because a child node’s ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " is added to its parent’s ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": ", you can interleave child nodes from different parent nodes. Listing 1 shows code that creates two square parent nodes, each with a circular child node. The first node has a ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 10 and its child node has a ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 10. The second node has a ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 15 and its child node also has a ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 10.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Once added to the scene, the child of the first node has an effective global ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 20 and the child of the second node has an effective global ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " of 25, giving an interleaving effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Interleaving composite nodes",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func addNodesTo(scene: SKScene,",
            "                color: SKColor, position: CGPoint,",
            "                parentZ: CGFloat, childZ: CGFloat) {",
            "    ",
            "    let diameter: CGFloat = 250",
            "    let rect = CGRect(origin: position,",
            "                      size: CGSize(width: diameter, height: diameter))",
            "     ",
            "    let parentNode = SKShapeNode(rect: rect)",
            "    let childNode = SKShapeNode(ellipseIn: rect.insetBy(dx: 10, dy: 10))",
            "  ",
            "    [(parentNode, scene, parentZ), (childNode, parentNode, childZ)].forEach {",
            "        node, parent, zPosition in",
            "        ",
            "        node.fillColor = color",
            "        node.strokeColor = .white",
            "        node.zPosition = zPosition",
            "        ",
            "        parent.addChild(node)",
            "    }",
            "}",
            "",
            "  ",
            "addNodesTo(scene: scene,",
            "           color: .red,",
            "           position: CGPoint(x: 300, y: 300),",
            "           parentZ: 10,",
            "           childZ: 10)",
            " ",
            "addNodesTo(scene: scene,",
            "           color: .blue,",
            "           position: CGPoint(x: 350, y: 250),",
            "           parentZ: 15,",
            "           childZ: 10)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The figure below shows the resulting scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3044935",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because ",
              "type": "text"
            },
            {
              "code": "zPosition",
              "type": "codeVoice"
            },
            {
              "text": " is additive across parent-child node relationships, you can use both tree order and ",
              "type": "text"
            },
            {
              "code": "zPositions",
              "type": "codeVoice"
            },
            {
              "text": " to determine your scene’s rendering order. When rendering a complex scene, you should disable the sorting behavior and use the ",
              "type": "text"
            },
            {
              "code": "zPositions",
              "type": "codeVoice"
            },
            {
              "text": " of nodes to create a deterministic scene order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " node classes alter the scene rendering behavior. The children of these nodes are rendered independently as a separate node tree, and the results are rendered into the tree that contains the crop or effect node. For more information, see Working with Other Node Types.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode": {
      "abstract": [
        {
          "text": "A node that masks pixels drawn by its children so that only some pixels are seen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCropNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCropNode"
        }
      ],
      "role": "symbol",
      "title": "SKCropNode",
      "type": "topic",
      "url": "/documentation/spritekit/skcropnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode": {
      "abstract": [
        {
          "text": "A node that renders its children into a separate buffer, optionally applying an effect, before drawing the final result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "role": "symbol",
      "title": "SKEffectNode",
      "type": "topic",
      "url": "/documentation/spritekit/skeffectnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/spritekit/sknode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position": {
      "abstract": [
        {
          "text": "The position of the node in its parent’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/position"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zPosition": {
      "abstract": [
        {
          "text": "The height of the node relative to its parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zPosition"
        }
      ],
      "role": "symbol",
      "title": "zPosition",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/zposition"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView/ignoresSiblingOrder": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether parent-child and sibling relationships affect the rendering order of nodes in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresSiblingOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/ignoresSiblingOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoresSiblingOrder"
        }
      ],
      "role": "symbol",
      "title": "ignoresSiblingOrder",
      "type": "topic",
      "url": "/documentation/spritekit/skview/ignoressiblingorder"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    },
    "media-2985165": {
      "alt": "Diagram showing that parent nodes are drawn before children",
      "identifier": "media-2985165",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/59b992e6a12c59338161ee35becdb9d6/media-2985165@2x.png"
        }
      ]
    },
    "media-3044935": {
      "alt": "Interleaved node hierarchies using zPosition",
      "identifier": "media-3044935",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b6b84ee1687ac7fcbba2b173c06f846d/media-3044935@2x.png"
        }
      ]
    },
    "media-3044936": {
      "alt": "Figure illustrating how depth-only rendering can improve performance",
      "identifier": "media-3044936",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/accfb2c789ccdf5490d1fe3358bcc5e4/media-3044936@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Draw-Order",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zPosition"
      ],
      "title": "Configuring Draw Order"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Draw-Order",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/zPosition"
              ],
              "title": "Configuring Draw Order"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/title",
          "value": "SKEffectNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1zPosition/title",
          "value": "zPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1zPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/title",
          "value": "SKNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1ignoresSiblingOrder/title",
          "value": "ignoresSiblingOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1ignoresSiblingOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoresSiblingOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/title",
          "value": "SKCropNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCropNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCropNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/about-node-drawing-order"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/about-node-drawing-order"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
