{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/creating-a-tile-map-programmatically"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Creating a Tile Map Programmatically"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The collection of functions you use to create a tile map node programmatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can create a tile map node much quicker by using Xcode’s SpriteKit Scene Editor.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/GameplayKit/GKNoiseMap": {
      "abstract": [
        {
          "text": "A sample of procedural noise data from which you can read noise values directly or create noise textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNoiseMap"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameplayKit/GKNoiseMap",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKNoiseMap",
      "type": "topic",
      "url": "/documentation/GameplayKit/GKNoiseMap"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode": {
      "abstract": [
        {
          "text": "A two-dimensional array of images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "role": "symbol",
      "title": "SKTileMapNode",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/enableAutomapping": {
      "abstract": [
        {
          "text": "When creating a tile map node programmatically, specifies whether the tile map uses automapping behavior like the scene editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableAutomapping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/enableAutomapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableAutomapping"
        }
      ],
      "role": "symbol",
      "title": "enableAutomapping",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/enableautomapping"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/fill(with:)": {
      "abstract": [
        {
          "text": "When creating a tile map node programmatically, this function performs a fill operation with the specified tile group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileGroup",
          "text": "SKTileGroup"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/fill(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillWithTileGroup:"
        }
      ],
      "role": "symbol",
      "title": "fill(with:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/fill(with:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:)": {
      "abstract": [
        {
          "text": "Creates and initializes a tile map node using the provided tile set with a specified number of columns and rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tileSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileSet",
          "text": "SKTileSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTileSet:columns:rows:tileSize:"
        }
      ],
      "role": "symbol",
      "title": "init(tileSet:columns:rows:tileSize:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/init(tileset:columns:rows:tilesize:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:fillWith:)": {
      "abstract": [
        {
          "text": "Creates and initializes a tile map node using the provided tile set with a specified number of columns and rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tileSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileSet",
          "text": "SKTileSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileGroup",
          "text": "SKTileGroup"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:fillWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTileSet:columns:rows:tileSize:fillWithTileGroup:"
        }
      ],
      "role": "symbol",
      "title": "init(tileSet:columns:rows:tileSize:fillWith:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/init(tileset:columns:rows:tilesize:fillwith:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:tileGroupLayout:)": {
      "abstract": [
        {
          "text": "Creates and initializes a tile map node using the provided tile set with a specified number of columns and rows. For a grid set type, the overall size, in points, of the node will be ",
          "type": "text"
        },
        {
          "code": "numberOfColumns * tileSize.width",
          "type": "codeVoice"
        },
        {
          "text": " wide and ",
          "type": "text"
        },
        {
          "code": "numberOfRows * tileSize.height",
          "type": "codeVoice"
        },
        {
          "text": " high.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tileSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileSet",
          "text": "SKTileSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileGroupLayout"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileGroup",
          "text": "SKTileGroup"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:tileGroupLayout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTileSet:columns:rows:tileSize:tileGroupLayout:"
        }
      ],
      "role": "symbol",
      "title": "init(tileSet:columns:rows:tileSize:tileGroupLayout:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/init(tileset:columns:rows:tilesize:tilegrouplayout:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:andTileDefinition:forColumn:row:)": {
      "abstract": [
        {
          "text": "Set the tile group and tile definition at the specified tile index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileGroup",
          "text": "SKTileGroup"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "andTileDefinition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileDefinition",
          "text": "SKTileDefinition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:andTileDefinition:forColumn:row:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileGroup:andTileDefinition:forColumn:row:"
        }
      ],
      "role": "symbol",
      "title": "setTileGroup(_:andTileDefinition:forColumn:row:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/settilegroup(_:andtiledefinition:forcolumn:row:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:forColumn:row:)": {
      "abstract": [
        {
          "text": "Set the tile group at the specified tile index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileGroup",
          "text": "SKTileGroup"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:forColumn:row:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileGroup:forColumn:row:"
        }
      ],
      "role": "symbol",
      "title": "setTileGroup(_:forColumn:row:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/settilegroup(_:forcolumn:row:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:"
        }
      ],
      "role": "symbol",
      "title": "tileMapNodeWithTileSet:columns:rows:tileSize:",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/tilemapnodewithtileset:columns:rows:tilesize:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:"
        }
      ],
      "role": "symbol",
      "title": "tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/tilemapnodewithtileset:columns:rows:tilesize:fillwithtilegroup:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:"
        }
      ],
      "role": "symbol",
      "title": "tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/tilemapnodewithtileset:columns:rows:tilesize:tilegrouplayout:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)": {
      "abstract": [
        {
          "text": "Creates a tile map node by allowing a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/GameplayKit/GKNoiseMap",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to choose its tiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tileMapNodes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tileSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileSet",
          "text": "SKTileSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoiseMap",
          "text": "GKNoiseMap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tileTypeNoiseMapThresholds"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileMapNode",
          "text": "SKTileMapNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tileMapNodesWithTileSet:columns:rows:tileSize:fromNoiseMap:tileTypeNoiseMapThresholds:"
        }
      ],
      "role": "symbol",
      "title": "tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode/tilemapnodes(tileset:columns:rows:tilesize:from:tiletypenoisemapthresholds:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Tile-Map",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:fillWith:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:tileGroupLayout:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)"
      ],
      "title": "Creating a Tile Map"
    },
    {
      "anchor": "Defining-a-Tile-Maps-Contents",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/enableAutomapping",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/fill(with:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:andTileDefinition:forColumn:row:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:forColumn:row:)"
      ],
      "title": "Defining a Tile Map’s Contents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Tile-Map",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:fillWith:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/init(tileSet:columns:rows:tileSize:tileGroupLayout:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:fillWithTileGroup:",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/tileMapNodeWithTileSet:columns:rows:tileSize:tileGroupLayout:"
              ],
              "title": "Creating a Tile Map"
            },
            {
              "anchor": "Defining-a-Tile-Maps-Contents",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/enableAutomapping",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/fill(with:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:andTileDefinition:forColumn:row:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode/setTileGroup(_:forColumn:row:)"
              ],
              "title": "Defining a Tile Map’s Contents"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameplayKit~1GKNoiseMap/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:)/title",
          "value": "initWithTileSet:columns:rows:tileSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTileSet:columns:rows:tileSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)/title",
          "value": "tileMapNodesWithTileSet:columns:rows:tileSize:fromNoiseMap:tileTypeNoiseMapThresholds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1tileMapNodes(tileSet:columns:rows:tileSize:from:tileTypeNoiseMapThresholds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tileMapNodesWithTileSet:columns:rows:tileSize:fromNoiseMap:tileTypeNoiseMapThresholds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/title",
          "value": "SKTileMapNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1setTileGroup(_:andTileDefinition:forColumn:row:)/title",
          "value": "setTileGroup:andTileDefinition:forColumn:row:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1setTileGroup(_:andTileDefinition:forColumn:row:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileGroup:andTileDefinition:forColumn:row:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1enableAutomapping/title",
          "value": "enableAutomapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1enableAutomapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableAutomapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1setTileGroup(_:forColumn:row:)/title",
          "value": "setTileGroup:forColumn:row:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1setTileGroup(_:forColumn:row:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileGroup:forColumn:row:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1fill(with:)/title",
          "value": "fillWithTileGroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1fill(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fillWithTileGroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:tileGroupLayout:)/title",
          "value": "initWithTileSet:columns:rows:tileSize:tileGroupLayout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:tileGroupLayout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTileSet:columns:rows:tileSize:tileGroupLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:fillWith:)/title",
          "value": "initWithTileSet:columns:rows:tileSize:fillWithTileGroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode~1init(tileSet:columns:rows:tileSize:fillWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTileSet:columns:rows:tileSize:fillWithTileGroup:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/creating-a-tile-map-programmatically"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/creating-a-tile-map-programmatically"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
