{
  "abstract": [
    {
      "text": "Create and assign a physics body to enable physics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-physics-bodies"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Getting Started with Physics Bodies"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object defines the shape and simulation parameters for a physics body in the system. When the scene simulates physics, it performs the calculations for all physics bodies connected to the scene tree. So, you create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, configure its properties, and then assign it to a node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/physicsBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are three kinds of physics bodies:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "dynamic volume",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " simulates a physical object with volume and mass that can be affected by forces and collisions in the system. Use dynamic volumes to represent items in the scene that need to move around and collide with each other.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "static volume",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " is similar to a dynamic volume, but its velocity is ignored and it is unaffected by forces or collisions. However, because it still has volume, other objects can bounce off it or interact with it. Use static volumes to represent items that take up space in the scene, but that should not be moved by the simulation. For example, you might use static volumes to represent the walls of a maze. While it is useful to think of static and dynamic volumes as distinct entities, in practice these are two different modes you can apply to any volume-based physics body. This can be useful because you can selectively enable or disable effects for a body.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "edge",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " is a static volume-less body. Edges are never moved by the simulation and their mass doesn’t matter. Edges are used to represent negative space within a scene (such as a hollow spot inside another entity) or an uncrossable, invisibly thin boundary. For example, edges are frequently used to represent the boundaries of your scene. The main difference between an edge and a volume is that an edge permits movement inside its own boundaries, while a volume is considered a solid object. If edges are moved through other means, they only interact with volumes, not with other edges.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "SpriteKit provides a few standard shapes—those based on arbitrary paths and those generated from the alpha channel of a texture. The following figure shows the shapes available:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2975399",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to generate the four physics bodies called out above:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let spaceShipTexture = SKTexture(imageNamed: \"spaceShip.png\")",
            "   ",
            "// Spaceship 1: circular physics body",
            "let circularSpaceShip = SKSpriteNode(texture: spaceShipTexture)",
            "circularSpaceShip.physicsBody = SKPhysicsBody(circleOfRadius: max(circularSpaceShip.size.width / 2,",
            "                                                                  circularSpaceShip.size.height / 2))",
            "   ",
            "// Spaceship 2: rectangular physics body",
            "let rectangularSpaceShip = SKSpriteNode(texture: spaceShipTexture)",
            "rectangularSpaceShip.physicsBody = SKPhysicsBody(rectangleOf: CGSize(width: circularSpaceShip.size.width,",
            "                                                                     height: circularSpaceShip.size.height))",
            "   ",
            "// Spaceship 3: polygonal physics body",
            "let polygonalSpaceShip = SKSpriteNode(texture: spaceShipTexture)",
            "let path = CGMutablePath()",
            "path.addLines(between: [CGPoint(x: -5, y: 37), CGPoint(x: 5, y: 37), CGPoint(x: 10, y: 20),",
            "                        CGPoint(x: 56, y: -5), CGPoint(x: 37, y: -35), CGPoint(x: 15, y: -30),",
            "                        CGPoint(x: 12, y: -37), CGPoint(x: -12, y: -37), CGPoint(x: -15, y: -30),",
            "                        CGPoint(x: -37, y: -35), CGPoint(x: -56, y: -5), CGPoint(x: -10, y: 20),",
            "                        CGPoint(x: -5, y: 37)])",
            "path.closeSubpath()",
            "polygonalSpaceShip.physicsBody = SKPhysicsBody(polygonFrom: path)",
            "  ",
            "// Spaceship 4: physics body using texture’s alpha channel",
            "let texturedSpaceShip = SKSpriteNode(texture: spaceShipTexture)",
            "texturedSpaceShip.physicsBody = SKPhysicsBody(texture: spaceShipTexture,",
            "                                              size: CGSize(width: circularSpaceShip.size.width,",
            "                                                           height: circularSpaceShip.size.height))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The shape of a physics body affects performance. A circular physics body offers the best performance and can be significantly faster than other physics bodies. If your simulation contains many physics bodies, circular bodies are the best solution. Rectangular and polygonal shapes improve collision accuracy with reduced speed. Physics bodies created from the alpha channel of a texture offer the best fidelity at the highest performance cost.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-and-Assign-Physics-Bodies",
          "level": 3,
          "text": "Create and Assign Physics Bodies",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A physics body is created by calling one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class methods. Each class method defines whether a volume-based or edge-based body is being created and what shape it has.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As soon as a node has its physics body set and is added to a scene, it begins to participate in the physics simulation. The following code shows how to create a simple scene containing a shape node that is the curvy ground and a sprite node—the rocket ship. The shape node’s physics body is created from its path and the sprite node’s physics body is created from the texture automatically generated by SpriteKit when the node was initialized. Because the ground node has its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody/isDynamic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", it is not affected by gravity and remains stationary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the rocket ship node and physics body",
            "let spriteNode = SKSpriteNode(imageNamed: \"rocketShip\")",
            "spriteNode.position = CGPoint(x: 320, y: 320)",
            "spriteNode.physicsBody = SKPhysicsBody(texture: spriteNode.texture!,",
            "                                       size: spriteNode.texture!.size())",
            "spriteNode.physicsBody?.usesPreciseCollisionDetection = true",
            "     ",
            "// Create the ground node and physics body",
            "var splinePoints = [CGPoint(x: 0, y: 500),",
            "                    CGPoint(x: 100, y: 50),",
            "                    CGPoint(x: 400, y: 110),",
            "                    CGPoint(x: 640, y: 20)]",
            "let ground = SKShapeNode(splinePoints: &splinePoints,",
            "                         count: splinePoints.count)",
            "ground.lineWidth = 5",
            "ground.physicsBody = SKPhysicsBody(edgeChainFrom: ground.path!)",
            "ground.physicsBody?.restitution = 0.75",
            "ground.physicsBody?.isDynamic = false",
            "     ",
            "// Add the two nodes to the scene",
            "scene.addChild(spriteNode)",
            "scene.addChild(ground)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After running for a few moments, the above code creates a scene that looks like the following illustration—the sprite node has come to rest in one of the valleys of the curvy ground line.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3045037",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/spritekit/sknode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/physicsBody": {
      "abstract": [
        {
          "text": "The physics body associated with the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicsBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPhysicsBody",
          "text": "SKPhysicsBody"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/physicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicsBody"
        }
      ],
      "role": "symbol",
      "title": "physicsBody",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/physicsbody"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody": {
      "abstract": [
        {
          "text": "An object that adds physics simulation to a node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsBody",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsbody"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody/isDynamic": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the physics body is moved by the physics simulation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDynamic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody/isDynamic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dynamic"
        }
      ],
      "role": "symbol",
      "title": "isDynamic",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsbody/isdynamic"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    },
    "media-2975399": {
      "alt": "Creating physics bodies for a sprite node",
      "identifier": "media-2975399",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f0cc8040ea87b83d1c3fe21b1c206aa8/media-2975399@2x.png"
        }
      ]
    },
    "media-3045037": {
      "alt": "Physics body from texture at rest",
      "identifier": "media-3045037",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/75df750718c03f966509fc49f60ae2a9/media-3045037@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/title",
          "value": "SKNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody~1isDynamic/title",
          "value": "dynamic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody~1isDynamic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dynamic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/title",
          "value": "SKPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1physicsBody/title",
          "value": "physicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1physicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicsBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/getting-started-with-physics-bodies"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/getting-started-with-physics-bodies"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
