{
  "abstract": [
    {
      "text": "Flatten a portion of your node hierarchy to a single texture to improve performance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/improving-the-performance-of-static-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Improving the Performance of Static Content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An effect node normally discards its private framebuffer after rendering is complete. Rendering the content is necessary because it typically changes every frame. However, if the content is static, discarding the rendered framebuffer is unnecessary, and it might make more sense to keep it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the content of the effect node is static, set the node’s ",
              "type": "text"
            },
            {
              "code": "shouldRasterize",
              "type": "codeVoice"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Setting this property causes the following changes in behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The framebuffer is not discarded at the end of rasterization. This also means that more memory is being used by the effect node, and rendering may take slightly longer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When a new frame is rendered, the framebuffer is rendered only if the contents of the effect node’s descendants have changed.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the effect node has a Core Image filter, changes to its properties no longer automatically update the framebuffer. You can force it to be updated by setting the ",
                      "type": "text"
                    },
                    {
                      "code": "shouldRasterize",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/false",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can use effect nodes to cache static content even when you aren’t applying a filter to the rendered image. This technique can be useful when the contents of a subtree are static and expensive to render.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode": {
      "abstract": [
        {
          "text": "A node that renders its children into a separate buffer, optionally applying an effect, before drawing the final result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "role": "symbol",
      "title": "SKEffectNode",
      "type": "topic",
      "url": "/documentation/spritekit/skeffectnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode/shouldRasterize": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the results of rendering the child nodes should be cached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldRasterize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode/shouldRasterize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldRasterize"
        }
      ],
      "role": "symbol",
      "title": "shouldRasterize",
      "type": "topic",
      "url": "/documentation/spritekit/skeffectnode/shouldrasterize"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flattening-an-Effect-Nodes-Child-Tree-for-Performance-Improvement",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode/shouldRasterize"
      ],
      "title": "Flattening an Effect Node’s Child Tree for Performance Improvement"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Flattening-an-Effect-Nodes-Child-Tree-for-Performance-Improvement",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode/shouldRasterize"
              ],
              "title": "Flattening an Effect Node’s Child Tree for Performance Improvement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode~1shouldRasterize/title",
          "value": "shouldRasterize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode~1shouldRasterize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldRasterize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/title",
          "value": "SKEffectNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/improving-the-performance-of-static-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/improving-the-performance-of-static-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
