{
  "abstract": [
    {
      "text": "Define the appearance or layout of scene content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Nodes for Scene Building"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SK3DNode": {
      "abstract": [
        {
          "text": "3D SceneKit content drawn as a flattened sprite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SK3DNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SK3DNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SK3DNode"
        }
      ],
      "role": "symbol",
      "title": "SK3DNode",
      "type": "topic",
      "url": "/documentation/spritekit/sk3dnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAudioNode": {
      "abstract": [
        {
          "text": "A node that plays audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAudioNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAudioNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAudioNode"
        }
      ],
      "role": "symbol",
      "title": "SKAudioNode",
      "type": "topic",
      "url": "/documentation/spritekit/skaudionode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKCameraNode": {
      "abstract": [
        {
          "text": "A node that determines which parts of the scene are visible within a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCameraNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKCameraNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCameraNode"
        }
      ],
      "role": "symbol",
      "title": "SKCameraNode",
      "type": "topic",
      "url": "/documentation/spritekit/skcameranode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode": {
      "abstract": [
        {
          "text": "A node that masks pixels drawn by its children so that only some pixels are seen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCropNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCropNode"
        }
      ],
      "role": "symbol",
      "title": "SKCropNode",
      "type": "topic",
      "url": "/documentation/spritekit/skcropnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode": {
      "abstract": [
        {
          "text": "A node that renders its children into a separate buffer, optionally applying an effect, before drawing the final result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEffectNode"
        }
      ],
      "role": "symbol",
      "title": "SKEffectNode",
      "type": "topic",
      "url": "/documentation/spritekit/skeffectnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode": {
      "abstract": [
        {
          "text": "A source of various particle effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "role": "symbol",
      "title": "SKEmitterNode",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode": {
      "abstract": [
        {
          "text": "A node that applies physics effects to nearby nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKFieldNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKFieldNode"
        }
      ],
      "role": "symbol",
      "title": "SKFieldNode",
      "type": "topic",
      "url": "/documentation/spritekit/skfieldnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode": {
      "abstract": [
        {
          "text": "A graphical element that draws text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelNode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelNode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLightNode": {
      "abstract": [
        {
          "text": "A node that lights surrounding nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLightNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLightNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLightNode"
        }
      ],
      "role": "symbol",
      "title": "SKLightNode",
      "type": "topic",
      "url": "/documentation/spritekit/sklightnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/spritekit/sknode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKReferenceNode": {
      "abstract": [
        {
          "text": "A node that’s defined in an archived ",
          "type": "text"
        },
        {
          "code": ".sks",
          "type": "codeVoice"
        },
        {
          "text": " file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKReferenceNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKReferenceNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKReferenceNode"
        }
      ],
      "role": "symbol",
      "title": "SKReferenceNode",
      "type": "topic",
      "url": "/documentation/spritekit/skreferencenode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene": {
      "abstract": [
        {
          "text": "An object that organizes all of the active SpriteKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "role": "symbol",
      "title": "SKScene",
      "type": "topic",
      "url": "/documentation/spritekit/skscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKShapeNode": {
      "abstract": [
        {
          "text": "A mathematical shape that can be stroked or filled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKShapeNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKShapeNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKShapeNode"
        }
      ],
      "role": "symbol",
      "title": "SKShapeNode",
      "type": "topic",
      "url": "/documentation/spritekit/skshapenode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode": {
      "abstract": [
        {
          "text": "An image or solid color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKSpriteNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSpriteNode"
        }
      ],
      "role": "symbol",
      "title": "SKSpriteNode",
      "type": "topic",
      "url": "/documentation/spritekit/skspritenode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode": {
      "abstract": [
        {
          "text": "A two-dimensional array of images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "role": "symbol",
      "title": "SKTileMapNode",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransformNode": {
      "abstract": [
        {
          "text": "A node that allows its children to rotate in 3D.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTransformNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransformNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTransformNode"
        }
      ],
      "role": "symbol",
      "title": "SKTransformNode",
      "type": "topic",
      "url": "/documentation/spritekit/sktransformnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKVideoNode": {
      "abstract": [
        {
          "text": "A graphical element that plays video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKVideoNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKVideoNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKVideoNode"
        }
      ],
      "role": "symbol",
      "title": "SKVideoNode",
      "type": "topic",
      "url": "/documentation/spritekit/skvideonode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view": {
      "abstract": [
        {
          "text": "Display visual content using SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
      "kind": "article",
      "role": "article",
      "title": "Drawing SpriteKit Content in a View",
      "type": "topic",
      "url": "/documentation/spritekit/drawing-spritekit-content-in-a-view"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-node-drawing-performance": {
      "abstract": [
        {
          "text": "Structure your nodes for maximum performance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-node-drawing-performance",
      "kind": "article",
      "role": "article",
      "title": "Maximizing Node Drawing Performance",
      "type": "topic",
      "url": "/documentation/spritekit/maximizing-node-drawing-performance"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/using-base-nodes-to-lay-out-spritekit-content": {
      "abstract": [
        {
          "text": "Use nonvisual nodes to define the layout of a scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/using-base-nodes-to-lay-out-spritekit-content",
      "kind": "article",
      "role": "article",
      "title": "Using Base Nodes to Lay Out SpriteKit Content",
      "type": "topic",
      "url": "/documentation/spritekit/using-base-nodes-to-lay-out-spritekit-content"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Provide a reference, point of view, or foundation to all things displayed in a scene.",
          "type": "text"
        }
      ],
      "anchor": "Base-Nodes",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/using-base-nodes-to-lay-out-spritekit-content",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKCameraNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKReferenceNode"
      ],
      "title": "Base Nodes"
    },
    {
      "abstract": [
        {
          "text": "Display images, shapes, particles, text, video, tiles, or even 3D content.",
          "type": "text"
        }
      ],
      "anchor": "Nodes-that-Draw",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-node-drawing-performance",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKShapeNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKVideoNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SK3DNode"
      ],
      "title": "Nodes that Draw"
    },
    {
      "abstract": [
        {
          "text": "Provide environmental effects to your scene, such as audio, lighting, or areas with specific physics characteristics.",
          "type": "text"
        }
      ],
      "anchor": "Nodes-for-Environmental-Effects",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAudioNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLightNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode"
      ],
      "title": "Nodes for Environmental Effects"
    },
    {
      "abstract": [
        {
          "text": "Modify the rendering of child nodes by cropping, applying Core Image filters, or performing 3D transformations.",
          "type": "text"
        }
      ],
      "anchor": "Nodes-that-Modify-Drawing",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransformNode"
      ],
      "title": "Nodes that Modify Drawing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Provide a reference, point of view, or foundation to all things displayed in a scene.",
                  "type": "text"
                }
              ],
              "anchor": "Base-Nodes",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/using-base-nodes-to-lay-out-spritekit-content",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKCameraNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKReferenceNode"
              ],
              "title": "Base Nodes"
            },
            {
              "abstract": [
                {
                  "text": "Display images, shapes, particles, text, video, tiles, or even 3D content.",
                  "type": "text"
                }
              ],
              "anchor": "Nodes-that-Draw",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-node-drawing-performance",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKShapeNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKVideoNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SK3DNode"
              ],
              "title": "Nodes that Draw"
            },
            {
              "abstract": [
                {
                  "text": "Provide environmental effects to your scene, such as audio, lighting, or areas with specific physics characteristics.",
                  "type": "text"
                }
              ],
              "anchor": "Nodes-for-Environmental-Effects",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAudioNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLightNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode"
              ],
              "title": "Nodes for Environmental Effects"
            },
            {
              "abstract": [
                {
                  "text": "Modify the rendering of child nodes by cropping, applying Core Image filters, or performing 3D transformations.",
                  "type": "text"
                }
              ],
              "anchor": "Nodes-that-Modify-Drawing",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEffectNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKCropNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransformNode"
              ],
              "title": "Nodes that Modify Drawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/title",
          "value": "SKSpriteNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSpriteNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSpriteNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/title",
          "value": "SKEffectNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEffectNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEffectNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SK3DNode/title",
          "value": "SK3DNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SK3DNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SK3DNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SK3DNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SK3DNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/title",
          "value": "SKLabelNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/title",
          "value": "SKCropNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCropNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCropNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCropNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransformNode/title",
          "value": "SKTransformNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransformNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransformNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransformNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransformNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAudioNode/title",
          "value": "SKAudioNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAudioNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAudioNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKVideoNode/title",
          "value": "SKVideoNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKVideoNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKVideoNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKVideoNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKVideoNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/title",
          "value": "SKTileMapNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/title",
          "value": "SKEmitterNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShapeNode/title",
          "value": "SKShapeNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShapeNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKShapeNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShapeNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKShapeNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCameraNode/title",
          "value": "SKCameraNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCameraNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCameraNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKCameraNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCameraNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReferenceNode/title",
          "value": "SKReferenceNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReferenceNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReferenceNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLightNode/title",
          "value": "SKLightNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLightNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLightNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLightNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLightNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/title",
          "value": "SKNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/title",
          "value": "SKFieldNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/title",
          "value": "SKScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/nodes-for-scene-building"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/nodes-for-scene-building"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
