{
  "abstract": [
    {
      "text": "Scale a sprite using nine-part algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/resizing-a-sprite-in-nine-parts"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Resizing a Sprite in Nine Parts"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The size of the sprite node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/frame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is determined by the values of these properties:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The sprite node’s ",
                      "type": "text"
                    },
                    {
                      "code": "size",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property holds its base (unscaled) size. When a sprite is initialized using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/init(imageNamed:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the value of this property is initialized to be equal to the size of the supplied image.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The base size is then scaled by the sprite’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/xScale",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/yScale",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties inherited from the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if the sprite node’s base size is 32 x 32 pixels and it has an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/xScale",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value of 1.0 and a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/yScale",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value of 2.0, the size of its frame is 32 x 64 pixels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The scaling values of the sprite node’s ancestors in the scene are also used to scale it. This changes the effective size of the sprite without changing its actual frame value. See ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "A Node Applies Many of Its Properties to Its Descendants",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When a sprite node’s frame is larger than its texture, the texture is stretched to cover its frame. Normally, the texture is stretched uniformly across the frame, as shown in the following figure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2983064",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "However, sometimes you want to use sprite nodes to build user interface elements, such as buttons or health indicators. Often, these elements contain fixed-size elements, such as end caps, that should not be stretched. In this case, use a portion of the texture without stretching, and then stretch the remaining part of the texture over the rest of the frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sprite’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which is specified in unit coordinates of the texture, controls the scaling behavior. The default value is a rectangle that covers the entire texture, which is why the entire texture is stretched across the frame. If you specify a rectangle that only covers a portion of the texture, you create a 3 x 3 grid. Each box in the grid has its own scaling behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The portions of the texture in the four corners of the grid are drawn without any scaling.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The center of the grid is scaled in both dimensions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The upper- and lower-middle parts are only scaled horizontally.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The left- and right-middle parts are only scaled vertically.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows a close-up view of a texture you might use to draw a user interface button. The complete texture is 28 x 28 pixels. The corner pieces are each 12 x 12 pixels and the center is 4 x 4 pixels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2983059",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how this button sprite would be initialized. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is computed based on the design of the texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let button = SKSpriteNode(imageNamed: \"stretchable_button.png\")",
                    "button.centerRect = CGRect(x: 12.0/28.0,",
                    "                           y: 12.0/28.0,",
                    "                           width: 4.0/28.0,",
                    "                           height: 4.0/28.0)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "SKSpriteNode *button = [SKSpriteNode spriteNodeWithImageNamed:@\"stretchable_button.png\"];",
                    "button.centerRect = CGRectMake(12.0/28.0, 12.0/28.0, 4.0/28.0, 4.0/28.0);"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Obj-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows that the corners remain the same, even when the button is drawn at different sizes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2983056",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/spritekit/sknode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/frame": {
      "abstract": [
        {
          "text": "A rectangle in the parent’s coordinate system that contains the node’s content, ignoring the node’s children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/frame"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/xScale": {
      "abstract": [
        {
          "text": "A scaling factor that multiplies the width of a node and its children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/xScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xScale"
        }
      ],
      "role": "symbol",
      "title": "xScale",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/xscale"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/yScale": {
      "abstract": [
        {
          "text": "A scaling factor that multiplies the height of a node and its children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNode/yScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yScale"
        }
      ],
      "role": "symbol",
      "title": "yScale",
      "type": "topic",
      "url": "/documentation/spritekit/sknode/yscale"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode": {
      "abstract": [
        {
          "text": "An image or solid color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKSpriteNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSpriteNode"
        }
      ],
      "role": "symbol",
      "title": "SKSpriteNode",
      "type": "topic",
      "url": "/documentation/spritekit/skspritenode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect": {
      "abstract": [
        {
          "text": "Enable nine-part stretching of the sprite’s texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerRect"
        }
      ],
      "role": "symbol",
      "title": "centerRect",
      "type": "topic",
      "url": "/documentation/spritekit/skspritenode/centerrect"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/init(imageNamed:)": {
      "abstract": [
        {
          "text": "Initializes a textured sprite using an image file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "imageNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/init(imageNamed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithImageNamed:"
        }
      ],
      "role": "symbol",
      "title": "init(imageNamed:)",
      "type": "topic",
      "url": "/documentation/spritekit/skspritenode/init(imagenamed:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    },
    "media-2983056": {
      "alt": "Applying the button texture to buttons of different sizes",
      "identifier": "media-2983056",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e3c8818cc34dee110c82affc7ee83e55/media-2983056@2x.png"
        }
      ]
    },
    "media-2983059": {
      "alt": "A stretchable button texture",
      "identifier": "media-2983059",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/78e21216dc794a904298a7a7d04ad735/media-2983059@2x.png"
        }
      ]
    },
    "media-2983064": {
      "alt": "A texture is stretched to cover the sprite’s frame",
      "identifier": "media-2983064",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/596d5f07d0cc6639848ddf4e620079d7/media-2983064@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scaling-a-Sprite-in-Nine-Parts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect"
      ],
      "title": "Scaling a Sprite in Nine Parts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scaling-a-Sprite-in-Nine-Parts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKSpriteNode/centerRect"
              ],
              "title": "Scaling a Sprite in Nine Parts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1yScale/title",
          "value": "yScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1yScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1xScale/title",
          "value": "xScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode~1xScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode~1centerRect/title",
          "value": "centerRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode~1centerRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/title",
          "value": "SKNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode~1init(imageNamed:)/title",
          "value": "initWithImageNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode~1init(imageNamed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithImageNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/title",
          "value": "SKSpriteNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSpriteNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSpriteNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSpriteNode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/resizing-a-sprite-in-nine-parts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/resizing-a-sprite-in-nine-parts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
