{
  "abstract": [
    {
      "text": "Implement per-frame app logic, such as the scene’s update function that’s called every frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/responding-to-frame-cycle-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Responding to Frame-Cycle Events"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a scene is presented via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", SpriteKit calls you every frame if you implement any of the functions shown in the following image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2975111",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t implement any of the frame-cycle functions, SpriteKit will only render the scene when something within it has changed, improving energy efficiency and allowing your game or app to perform other operations instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Decide-Which-Events-to-Implement",
          "level": 3,
          "text": "Decide Which Events to Implement",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each time through the rendering loop, the scene’s contents are updated and then rendered. You can’t override the rendering behavior; instead you update the nodes in the scene. However, the scene includes methods you can override to customize scene processing, and you can use actions and physics to alter properties of nodes in the tree. Here are the steps in the rendering loop:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/update(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method is called with the time elapsed so far in the simulation. This is the primary place to implement your own in-game simulation, including input handling, artificial intelligence, game scripting, and other similar game logic. Often, you use this method to make changes to nodes or to run actions on nodes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene processes actions on all the nodes in the tree. It finds any running actions and applies those changes to the tree. In practice, because of custom actions, you can also hook into the action mechanism to call your own code. You cannot directly control the order in which actions are processed or cause the scene to skip actions on certain nodes, except by removing the actions from those nodes or removing the nodes from the tree.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method is called after all actions for the frame have been processed.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene simulates physics on nodes in the tree that have physics bodies. Adding physics to nodes in a scene is described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", but the end result of simulating physics is that the position and rotation of nodes in the tree may be adjusted by the physics simulation. Your game can also receive callbacks when physics bodies come into contact with each other. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method is called after all physics bodies for the frame have been simulated.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene applies any constraints associated with nodes in the scene. Constraints are used to establish relationships in the scene. For example, you can apply a constraint that makes sure a node is always pointed at another node, regardless of how it is moved. By using constraints, you avoid needing to write a lot of custom code in your scene handling.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene calls its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didApplyConstraints()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene calls its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didFinishUpdate()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method. This is your last chance to make changes to the scene.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The scene is rendered.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Use-a-Scene-Delegate-Instead-of-Subclassing-a-Scene",
          "level": 3,
          "text": "Use a Scene Delegate Instead of Subclassing a Scene",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Subclassing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and overriding frame-cycle functions is a simple way to implement your app’s logic, but you avoid subclassing by using a delegate. All of the frame-cycle functions defined by ",
              "type": "text"
            },
            {
              "code": "SKScene",
              "type": "codeVoice"
            },
            {
              "text": " have an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol equivalent function. So, if you provide a scene delegate, the delegate’s frame-cycle methods are called instead of those on the scene. For example, an iOS app might use a view controller as the scene delegate. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/subclassing-scenes-versus-assigning-a-delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Implement-Post-Processing",
          "level": 3,
          "text": "Implement Post-Processing",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A scene can process the actions on the scene tree in any order. For this reason, if you have tasks that you need to run each frame and you need precise control over when they run, you should use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods to perform those tasks. Typically, you make changes during post-processing that require the final calculated positions of certain nodes in the tree. Your post-processing can take these positions and perform other useful work on the tree.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody": {
      "abstract": [
        {
          "text": "An object that adds physics simulation to a node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsBody",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsbody"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond when physics bodies come into contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsContactDelegate"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsContactDelegate"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsContactDelegate",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicscontactdelegate"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene": {
      "abstract": [
        {
          "text": "An object that organizes all of the active SpriteKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "role": "symbol",
      "title": "SKScene",
      "type": "topic",
      "url": "/documentation/spritekit/skscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didApplyConstraints()": {
      "abstract": [
        {
          "text": "Tells your app to peform any necessary logic after constraints are applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didApplyConstraints"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didApplyConstraints()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didApplyConstraints"
        }
      ],
      "role": "symbol",
      "title": "didApplyConstraints()",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/didapplyconstraints()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()": {
      "abstract": [
        {
          "text": "Tells your app to peform any necessary logic after scene actions are evaluated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didEvaluateActions"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didEvaluateActions"
        }
      ],
      "role": "symbol",
      "title": "didEvaluateActions()",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/didevaluateactions()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didFinishUpdate()": {
      "abstract": [
        {
          "text": "Tells your app to peform any necessary logic after the scene has finished all of the steps required to process animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFinishUpdate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didFinishUpdate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didFinishUpdate"
        }
      ],
      "role": "symbol",
      "title": "didFinishUpdate()",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/didfinishupdate()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()": {
      "abstract": [
        {
          "text": "Tells your app to peform any necessary logic after physics simulations are performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSimulatePhysics"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didSimulatePhysics"
        }
      ],
      "role": "symbol",
      "title": "didSimulatePhysics()",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/didsimulatephysics()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/update(_:)": {
      "abstract": [
        {
          "text": "Tells your app to perform any app-specific logic to update your scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/update(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "update:"
        }
      ],
      "role": "symbol",
      "title": "update(_:)",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/update(_:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneDelegate": {
      "abstract": [
        {
          "text": "Methods that, when implemented, allow any class to participate in the SpriteKit render loop callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKSceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "SKSceneDelegate",
      "type": "topic",
      "url": "/documentation/spritekit/skscenedelegate"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)": {
      "abstract": [
        {
          "text": "Presents a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKScene",
          "text": "SKScene"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentScene:"
        }
      ],
      "role": "symbol",
      "title": "presentScene(_:)",
      "type": "topic",
      "url": "/documentation/spritekit/skview/presentscene(_:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/subclassing-scenes-versus-assigning-a-delegate": {
      "abstract": [
        {
          "text": "Use a scene delegate to share app logic across various scenes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/subclassing-scenes-versus-assigning-a-delegate",
      "kind": "article",
      "role": "article",
      "title": "Subclassing Scenes Versus Assigning a Delegate",
      "type": "topic",
      "url": "/documentation/spritekit/subclassing-scenes-versus-assigning-a-delegate"
    },
    "media-2975111": {
      "alt": "Diagram showing the sequence of events that compose the scene update lifecycle",
      "identifier": "media-2975111",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/93eb4a2895a996eb9fc43048eb2c10a6/media-2975111@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Frame-Cycle-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/update(_:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didApplyConstraints()",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didFinishUpdate()"
      ],
      "title": "Responding to Frame-Cycle Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Frame-Cycle-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/update(_:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didEvaluateActions()",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didSimulatePhysics()",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didApplyConstraints()",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didFinishUpdate()"
              ],
              "title": "Responding to Frame-Cycle Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/title",
          "value": "SKPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didEvaluateActions()/title",
          "value": "didEvaluateActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didEvaluateActions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didEvaluateActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/title",
          "value": "SKPhysicsContactDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContactDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContactDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneDelegate/title",
          "value": "SKSceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didApplyConstraints()/title",
          "value": "didApplyConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didApplyConstraints()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didApplyConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:)/title",
          "value": "presentScene:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentScene:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didSimulatePhysics()/title",
          "value": "didSimulatePhysics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didSimulatePhysics()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didSimulatePhysics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1update(_:)/title",
          "value": "update:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1update(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "update:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/title",
          "value": "SKScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didFinishUpdate()/title",
          "value": "didFinishUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didFinishUpdate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didFinishUpdate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/responding-to-frame-cycle-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/responding-to-frame-cycle-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
