{
  "abstract": [
    {
      "text": "Configure the scale mode to determine how a scene is sized to fit its view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/scaling-a-scene-s-content-to-fit-the-view"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Scaling a Scene’s Content to Fit the View"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set the scene’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to determine how it’s sized according to the view that’s displaying it. For example, in iOS, ",
              "type": "text"
            },
            {
              "code": "scaleMode",
              "type": "codeVoice"
            },
            {
              "text": " determines the automatic resizing of your scene when the device changes orientation. In macOS, ",
              "type": "text"
            },
            {
              "code": "scaleMode",
              "type": "codeVoice"
            },
            {
              "text": " affects how your scene is scaled when the user changes the size or proportions of your app’s window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Decide-Which-Scale-Mode-Is-Best",
          "level": 3,
          "text": "Decide Which Scale Mode Is Best",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you design your game, you should decide on a strategy for handling the scene’s ",
              "type": "text"
            },
            {
              "code": "size",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. Here are the most common strategies:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate the scene with a constant size and never change it. Pick a scaling mode that lets the view scale the scene’s content. This gives the scene a predictable coordinate system and frame. You can then base your art assets and gameplay logic on this coordinate system.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adjust the size of the scene in your game. Where necessary, adjust your game logic and art assets to match the scene’s size.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/resizeFill",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". SpriteKit automatically resizes the scene so that it always matches the view’s size. Where necessary, adjust your game logic and art assets to match the scene’s size.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Set-a-Fixed-Aspect-Ratio",
          "level": 3,
          "text": "Set a Fixed Aspect Ratio",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1 shows a typical implementation for when you plan to use a constant-sized scene. This code specifies a method to be executed the first time that the scene is presented. It configures the scene’s properties, including its scaling mode, then adds content. In this example, the scale mode is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/aspectFit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which scales the contents equally in both dimensions and ensures that all of the scene’s contents are visible. Where necessary, this mode adds letter-boxing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Creating a constant-sized scene",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func createSceneContent() {",
                    "    scene.scaleMode = .aspectFit",
                    "    scene.backgroundColor = .black",
                    "    // Add additional scene contents here.  ",
                    "   ...",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)createSceneContent  ",
                    "{      ",
                    "    self.scaleMode = SKSceneScaleModeAspectFit;      ",
                    "    self.backgroundColor = [SKColor blackColor];  ",
                    "    // Add additional scene contents here.  ",
                    "    ...",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Obj-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Update-Your-Graphics-on-Scene-Resize",
          "level": 3,
          "text": "Update Your Graphics on Scene Resize",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you expect a scene’s size to change at runtime, then the initial scene size should be used to determine which art assets to use, as well as any game logic that is dependent on the scene size. Your game should also override the scene’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didChangeSize(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which is called whenever the scene changes size. When this method is called, you should update the scene’s contents to match the new size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene": {
      "abstract": [
        {
          "text": "An object that organizes all of the active SpriteKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "role": "symbol",
      "title": "SKScene",
      "type": "topic",
      "url": "/documentation/spritekit/skscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didChangeSize(_:)": {
      "abstract": [
        {
          "text": "Tells you when the scene’s size has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/didChangeSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didChangeSize:"
        }
      ],
      "role": "symbol",
      "title": "didChangeSize(_:)",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/didchangesize(_:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode": {
      "abstract": [
        {
          "text": "A setting that defines how the scene is mapped to the view that presents it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKSceneScaleMode",
          "text": "SKSceneScaleMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleMode"
        }
      ],
      "role": "symbol",
      "title": "scaleMode",
      "type": "topic",
      "url": "/documentation/spritekit/skscene/scalemode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode": {
      "abstract": [
        {
          "text": "The modes that determine how the scene’s area is mapped to the view that presents it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKSceneScaleMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSceneScaleMode"
        }
      ],
      "role": "symbol",
      "title": "SKSceneScaleMode",
      "type": "topic",
      "url": "/documentation/spritekit/skscenescalemode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/aspectFit": {
      "abstract": [
        {
          "text": "The scaling factor of each dimension is calculated and the smaller of the two is chosen. Each axis of the scene is scaled by the same scaling factor. This guarantees that the entire scene is visible but may require letterboxing in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aspectFit"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/aspectFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSceneScaleModeAspectFit"
        }
      ],
      "role": "symbol",
      "title": "SKSceneScaleMode.aspectFit",
      "type": "topic",
      "url": "/documentation/spritekit/skscenescalemode/aspectfit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/resizeFill": {
      "abstract": [
        {
          "text": "The scene is not scaled to match the view. Instead, the scene is automatically resized so that its dimensions always match those of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeFill"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode/resizeFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSceneScaleModeResizeFill"
        }
      ],
      "role": "symbol",
      "title": "SKSceneScaleMode.resizeFill",
      "type": "topic",
      "url": "/documentation/spritekit/skscenescalemode/resizefill"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stretching-Content-to-Fit-the-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode"
      ],
      "title": "Stretching Content to Fit the View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stretching-Content-to-Fit-the-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene/scaleMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode"
              ],
              "title": "Stretching Content to Fit the View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/title",
          "value": "SKScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode~1aspectFit/title",
          "value": "SKSceneScaleModeAspectFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode~1aspectFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleModeAspectFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode~1resizeFill/title",
          "value": "SKSceneScaleModeResizeFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode~1resizeFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleModeResizeFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1scaleMode/title",
          "value": "scaleMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1scaleMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didChangeSize(_:)/title",
          "value": "didChangeSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene~1didChangeSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didChangeSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/title",
          "value": "SKSceneScaleMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/scaling-a-scene-s-content-to-fit-the-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/scaling-a-scene-s-content-to-fit-the-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
