{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SK_AVAILABLE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@SK_AVAILABLE",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SK_AVAILABLE"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SK_AVAILABLE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "SK_AVAILABLE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SK_AVAILABLE"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKColor"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKColor",
      "type": "topic",
      "url": "/documentation/spritekit/skcolor-c.macro"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKVIEW_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKVIEW_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKVIEW_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKVIEW_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "SKVIEW_AVAILABLE",
      "type": "topic",
      "url": "/documentation/spritekit/skview_available"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SK_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SK_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_AVAILABLE",
      "type": "topic",
      "url": "/documentation/spritekit/sk_available"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SK_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SK_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXPORT",
      "type": "topic",
      "url": "/documentation/spritekit/sk_export"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SK_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SK_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SK_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SK_VERSION"
        }
      ],
      "role": "symbol",
      "title": "SK_VERSION",
      "type": "topic",
      "url": "/documentation/spritekit/sk_version"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SK_WEAK_LINK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_WEAK_LINK"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SK_WEAK_LINK",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_WEAK_LINK",
      "type": "topic",
      "url": "/documentation/spritekit/sk_weak_link"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-c.macro",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKVIEW_AVAILABLE",
        "doc://com.apple.spritekit/documentation/SpriteKit/SK_EXPORT",
        "doc://com.apple.spritekit/documentation/SpriteKit/SK_VERSION",
        "doc://com.apple.spritekit/documentation/SpriteKit/SK_WEAK_LINK"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKVIEW_AVAILABLE/title",
          "value": "SKVIEW_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKVIEW_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKVIEW_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SK_VERSION/title",
          "value": "SK_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SK_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SK_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sk_available"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
