{
  "abstract": [
    {
      "text": "Options that specify an attribute’s data type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKAttributeType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKAttributeType"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAttributeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SKAttributeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType": {
      "abstract": [
        {
          "text": "Options that specify an attribute’s data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAttributeType"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeType"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeFloat"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.float",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/float"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/halfFloat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "halfFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/halfFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeHalfFloat"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.halfFloat",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/halffloat"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/init(rawvalue:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeNone"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.none",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/none"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorFloat2"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorFloat2"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorFloat2",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorfloat2"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorFloat3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorFloat3"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorFloat3",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorfloat3"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorFloat4"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorFloat4"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorFloat4",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorfloat4"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorHalfFloat2"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorHalfFloat2"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorHalfFloat2",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorhalffloat2"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorHalfFloat3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorHalfFloat3"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorHalfFloat3",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorhalffloat3"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vectorHalfFloat4"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeTypeVectorHalfFloat4"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType.vectorHalfFloat4",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype/vectorhalffloat4"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/float",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/halfFloat",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/none",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat2",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat3",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat4",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat2",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat3",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat4"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAttributeType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/float",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/halfFloat",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/none",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat2",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat3",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorFloat4",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat2",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat3",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType/vectorHalfFloat4"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKAttributeType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1float/title",
          "value": "SKAttributeTypeFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1none/title",
          "value": "SKAttributeTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat3/title",
          "value": "SKAttributeTypeVectorFloat3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorFloat3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1halfFloat/title",
          "value": "SKAttributeTypeHalfFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1halfFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeHalfFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat2/title",
          "value": "SKAttributeTypeVectorHalfFloat2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorHalfFloat2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/title",
          "value": "SKAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat2/title",
          "value": "SKAttributeTypeVectorFloat2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorFloat2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat4/title",
          "value": "SKAttributeTypeVectorHalfFloat4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorHalfFloat4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat3/title",
          "value": "SKAttributeTypeVectorHalfFloat3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorHalfFloat3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorHalfFloat3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat4/title",
          "value": "SKAttributeTypeVectorFloat4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType~1vectorFloat4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeTypeVectorFloat4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
