{
  "abstract": [
    {
      "text": "An object that performs interpolation between values specified at different times (keyframes).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKKeyframeSequence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKKeyframeSequence"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKKeyframeSequence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKKeyframeSequence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.spritekit/documentation/SpriteKit/using-keyframe-sequence-to-effect-custom-interpolation",
        "doc://com.apple.spritekit/documentation/SpriteKit/animating-particle-properties-across-disparate-values"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The primary use for an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is to animate properties on particles emitted by an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, but it can also be used for your general interpolation needs across a discrete set of inputs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a keyframe sequence is used with an emitter node, particles determine their values by sampling the keyframe sequence. The sequence replaces the normal simulation performed by the emitter node.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode": {
      "abstract": [
        {
          "text": "A source of various particle effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "role": "symbol",
      "title": "SKEmitterNode",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode": {
      "abstract": [
        {
          "text": "The modes used to interpolate between keyframes in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKInterpolationMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKInterpolationMode"
        }
      ],
      "role": "symbol",
      "title": "SKInterpolationMode",
      "type": "topic",
      "url": "/documentation/spritekit/skinterpolationmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence": {
      "abstract": [
        {
          "text": "An object that performs interpolation between values specified at different times (keyframes).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKKeyframeSequence"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKKeyframeSequence"
        }
      ],
      "role": "symbol",
      "title": "SKKeyframeSequence",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/addKeyframeValue(_:time:)": {
      "abstract": [
        {
          "text": "Adds a keyframe to the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addKeyframeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/addKeyframeValue(_:time:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addKeyframeValue:time:"
        }
      ],
      "role": "symbol",
      "title": "addKeyframeValue(_:time:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/addkeyframevalue(_:time:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/count()": {
      "abstract": [
        {
          "text": "The number of keyframes in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/count()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count()",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/count()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeTime(for:)": {
      "abstract": [
        {
          "text": "Gets the time for a keyframe in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getKeyframeTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeTime(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getKeyframeTimeForIndex:"
        }
      ],
      "role": "symbol",
      "title": "getKeyframeTime(for:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/getkeyframetime(for:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeValue(for:)": {
      "abstract": [
        {
          "text": "Gets the value for a keyframe in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getKeyframeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeValue(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getKeyframeValueForIndex:"
        }
      ],
      "role": "symbol",
      "title": "getKeyframeValue(for:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/getkeyframevalue(for:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(capacity:)": {
      "abstract": [
        {
          "text": "Initializes a new keyframe sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "capacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(capacity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCapacity:"
        }
      ],
      "role": "symbol",
      "title": "init(capacity:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/init(capacity:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/init(coder:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(keyframeValues:times:)": {
      "abstract": [
        {
          "text": "Initializes a keyframe sequence with an initial set of values and times.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keyframeValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "times"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(keyframeValues:times:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKeyframeValues:times:"
        }
      ],
      "role": "symbol",
      "title": "init(keyframeValues:times:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/init(keyframevalues:times:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/interpolationMode": {
      "abstract": [
        {
          "text": "The mode used to determine how values for times between the keyframes are calculated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interpolationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKInterpolationMode",
          "text": "SKInterpolationMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/interpolationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interpolationMode"
        }
      ],
      "role": "symbol",
      "title": "interpolationMode",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/interpolationmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeKeyframe(at:)": {
      "abstract": [
        {
          "text": "Removes a keyframe from the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeKeyframe"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeKeyframe(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeKeyframeAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "removeKeyframe(at:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/removekeyframe(at:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeLastKeyframe()": {
      "abstract": [
        {
          "text": "Removes the last value in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeLastKeyframe"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeLastKeyframe()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeLastKeyframe"
        }
      ],
      "role": "symbol",
      "title": "removeLastKeyframe()",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/removelastkeyframe()"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/repeatMode": {
      "abstract": [
        {
          "text": "The mode used to determine how the keyframe sequence repeats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "repeatMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKRepeatMode",
          "text": "SKRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/repeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "repeatMode"
        }
      ],
      "role": "symbol",
      "title": "repeatMode",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/repeatmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/sample(atTime:)": {
      "abstract": [
        {
          "text": "Calculates the sample at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sample"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/sample(atTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleAtTime:"
        }
      ],
      "role": "symbol",
      "title": "sample(atTime:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/sample(attime:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeTime(_:for:)": {
      "abstract": [
        {
          "text": "Changes the time for a specific keyframe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyframeTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeTime(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyframeTime:forIndex:"
        }
      ],
      "role": "symbol",
      "title": "setKeyframeTime(_:for:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/setkeyframetime(_:for:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:for:)": {
      "abstract": [
        {
          "text": "Changes the value for a specific keyframe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyframeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyframeValue:forIndex:"
        }
      ],
      "role": "symbol",
      "title": "setKeyframeValue(_:for:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/setkeyframevalue(_:for:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:time:for:)": {
      "abstract": [
        {
          "text": "Replaces a keyframe in the sequence with a new keyframe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyframeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:time:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyframeValue:time:forIndex:"
        }
      ],
      "role": "symbol",
      "title": "setKeyframeValue(_:time:for:)",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence/setkeyframevalue(_:time:for:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRange": {
      "abstract": [
        {
          "text": "A definition of a range of floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRange"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRange"
        }
      ],
      "role": "symbol",
      "title": "SKRange",
      "type": "topic",
      "url": "/documentation/spritekit/skrange"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion": {
      "abstract": [
        {
          "text": "The definition of an arbitrary area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRegion"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRegion"
        }
      ],
      "role": "symbol",
      "title": "SKRegion",
      "type": "topic",
      "url": "/documentation/spritekit/skregion"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode": {
      "abstract": [
        {
          "text": "The modes used to determine how the sequence repeats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "SKRepeatMode",
      "type": "topic",
      "url": "/documentation/spritekit/skrepeatmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/animating-particle-properties-across-disparate-values": {
      "abstract": [
        {
          "text": "Supply keyframe sequences to do linear or nonlinear particle animations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/animating-particle-properties-across-disparate-values",
      "kind": "article",
      "role": "article",
      "title": "Animating Particle Properties Across Disparate Values",
      "type": "topic",
      "url": "/documentation/spritekit/animating-particle-properties-across-disparate-values"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/using-keyframe-sequence-to-effect-custom-interpolation": {
      "abstract": [
        {
          "text": "See a few examples of what keyframe sequence can do.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/using-keyframe-sequence-to-effect-custom-interpolation",
      "kind": "article",
      "role": "article",
      "title": "Using Keyframe Sequence to effect Custom Interpolation",
      "type": "topic",
      "url": "/documentation/spritekit/using-keyframe-sequence-to-effect-custom-interpolation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mathematical-Tools",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion"
      ],
      "title": "Mathematical Tools"
    }
  ],
  "topicSections": [
    {
      "anchor": "First-Steps",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/using-keyframe-sequence-to-effect-custom-interpolation",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(keyframeValues:times:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(capacity:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(coder:)"
      ],
      "title": "First Steps"
    },
    {
      "abstract": [
        {
          "text": "Define the composition of the keyframe sequence.",
          "type": "text"
        }
      ],
      "anchor": "Sequence-Building",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/addKeyframeValue(_:time:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeKeyframe(at:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeLastKeyframe()",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeTime(_:for:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:for:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:time:for:)"
      ],
      "title": "Sequence Building"
    },
    {
      "abstract": [
        {
          "text": "You run the sequence by sampling its output at a given time.",
          "type": "text"
        }
      ],
      "anchor": "Sequence-Running",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/sample(atTime:)"
      ],
      "title": "Sequence Running"
    },
    {
      "anchor": "Sequence-Information",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/count()",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeTime(for:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeValue(for:)"
      ],
      "title": "Sequence Information"
    },
    {
      "abstract": [
        {
          "text": "Modify sample output by defining a mode or repeat options.",
          "type": "text"
        }
      ],
      "anchor": "Interpolation-Modifiers",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/interpolationMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/repeatMode"
      ],
      "title": "Interpolation Modifiers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKKeyframeSequence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "First-Steps",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/using-keyframe-sequence-to-effect-custom-interpolation",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(keyframeValues:times:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(capacity:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/init(coder:)"
              ],
              "title": "First Steps"
            },
            {
              "abstract": [
                {
                  "text": "Define the composition of the keyframe sequence.",
                  "type": "text"
                }
              ],
              "anchor": "Sequence-Building",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/addKeyframeValue(_:time:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeKeyframe(at:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/removeLastKeyframe()",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeTime(_:for:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:for:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/setKeyframeValue(_:time:for:)"
              ],
              "title": "Sequence Building"
            },
            {
              "abstract": [
                {
                  "text": "You run the sequence by sampling its output at a given time.",
                  "type": "text"
                }
              ],
              "anchor": "Sequence-Running",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/sample(atTime:)"
              ],
              "title": "Sequence Running"
            },
            {
              "anchor": "Sequence-Information",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/count()",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeTime(for:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/getKeyframeValue(for:)"
              ],
              "title": "Sequence Information"
            },
            {
              "abstract": [
                {
                  "text": "Modify sample output by defining a mode or repeat options.",
                  "type": "text"
                }
              ],
              "anchor": "Interpolation-Modifiers",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/interpolationMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence/repeatMode"
              ],
              "title": "Interpolation Modifiers"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mathematical-Tools",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion"
              ],
              "title": "Mathematical Tools"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKKeyframeSequence"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1removeKeyframe(at:)/title",
          "value": "removeKeyframeAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1removeKeyframe(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeKeyframeAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1removeLastKeyframe()/title",
          "value": "removeLastKeyframe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1removeLastKeyframe()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeLastKeyframe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1getKeyframeValue(for:)/title",
          "value": "getKeyframeValueForIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1getKeyframeValue(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getKeyframeValueForIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/title",
          "value": "SKRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/title",
          "value": "SKEmitterNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/title",
          "value": "SKRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1count()/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1count()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/title",
          "value": "SKKeyframeSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1interpolationMode/title",
          "value": "interpolationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1interpolationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interpolationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1addKeyframeValue(_:time:)/title",
          "value": "addKeyframeValue:time:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1addKeyframeValue(_:time:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addKeyframeValue:time:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(keyframeValues:times:)/title",
          "value": "initWithKeyframeValues:times:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(keyframeValues:times:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKeyframeValues:times:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(capacity:)/title",
          "value": "initWithCapacity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(capacity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCapacity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/title",
          "value": "SKInterpolationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKInterpolationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKInterpolationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeValue(_:time:for:)/title",
          "value": "setKeyframeValue:time:forIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeValue(_:time:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyframeValue:time:forIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeValue(_:for:)/title",
          "value": "setKeyframeValue:forIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeValue(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyframeValue:forIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/title",
          "value": "SKRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeTime(_:for:)/title",
          "value": "setKeyframeTime:forIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1setKeyframeTime(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyframeTime:forIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1getKeyframeTime(for:)/title",
          "value": "getKeyframeTimeForIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1getKeyframeTime(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getKeyframeTimeForIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1repeatMode/title",
          "value": "repeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1repeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "repeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1sample(atTime:)/title",
          "value": "sampleAtTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence~1sample(atTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sampleAtTime:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skkeyframesequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skkeyframesequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
