{
  "abstract": [
    {
      "text": "An enumeration defining how neighboring tiles are automatically placed next to each other.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTileAdjacencyMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKTileAdjacencyMask"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTileAdjacencyMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SKTileAdjacencyMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask": {
      "abstract": [
        {
          "text": "An enumeration defining how neighboring tiles are automatically placed next to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "role": "symbol",
      "title": "SKTileAdjacencyMask",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyAll"
        }
      ],
      "role": "symbol",
      "title": "adjacencyAll",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyall"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyDown"
        }
      ],
      "role": "symbol",
      "title": "adjacencyDown",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencydown"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyDownEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyDownEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyDownEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencydownedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLeftEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLeftEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLeftEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyleftedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeftCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeftCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeftCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeftEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeftEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeftEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRight"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRightCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRightCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRightCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerrightcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRightEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRightEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRightEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerrightedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyRight"
        }
      ],
      "role": "symbol",
      "title": "adjacencyRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyRightEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyRightEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyRightEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyrightedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUp"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUp",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyup"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperLeftCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperLeftCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperLeftCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperleftcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperLeftEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperLeftEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperLeftEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperleftedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperRight"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperRightCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperRightCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperRightCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperrightcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperRightEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperRightEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperRightEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperrightedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyAll"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyAll",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencyall"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyDown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyDown"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyDown",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencydown"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyLowerLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyLowerLeft"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyLowerLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencylowerleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyLowerRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyLowerRight"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyLowerRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencylowerright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyUp"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyUp",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencyup"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyUpperLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyUpperLeft"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyUpperLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencyupperleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexFlatAdjacencyUpperRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexFlatAdjacencyUpperRight"
        }
      ],
      "role": "symbol",
      "title": "hexFlatAdjacencyUpperRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexflatadjacencyupperright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyAdd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyAdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyAdd"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyAdd",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencyadd"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyLeft"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencyleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyLowerLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyLowerLeft"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyLowerLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencylowerleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyLowerRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyLowerRight"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyLowerRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencylowerright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyRight"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencyright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyUpperLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyUpperLeft"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyUpperLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencyupperleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hexPointyAdjacencyUpperRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileHexPointyAdjacencyUpperRight"
        }
      ],
      "role": "symbol",
      "title": "hexPointyAdjacencyUpperRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/hexpointyadjacencyupperright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/init(rawvalue:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/adjacency": {
      "abstract": [
        {
          "text": "The adjacency requirement for this rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/adjacency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjacency"
        }
      ],
      "role": "symbol",
      "title": "adjacency",
      "type": "topic",
      "url": "/documentation/spritekit/sktilegrouprule/adjacency"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/name": {
      "abstract": [
        {
          "text": "A name associated with the tile group rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/spritekit/sktilegrouprule/name"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/tileDefinitions": {
      "abstract": [
        {
          "text": "The tile definitions used for this rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tileDefinitions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTileDefinition",
          "text": "SKTileDefinition"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/tileDefinitions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tileDefinitions"
        }
      ],
      "role": "symbol",
      "title": "tileDefinitions",
      "type": "topic",
      "url": "/documentation/spritekit/sktilegrouprule/tiledefinitions"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-or-Setting-Tile-Group-Rule-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/adjacency",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/name",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/tileDefinitions"
      ],
      "title": "Accessing or Setting Tile Group Rule Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Masks",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftCorner",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightCorner",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyAll",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyDown",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUp",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyAdd",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperRight"
      ],
      "title": "Masks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTileAdjacencyMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Masks",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftCorner",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeftEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightCorner",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperRightEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyAll",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyDown",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyLowerRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUp",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexFlatAdjacencyUpperRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyAdd",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyLowerRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/hexPointyAdjacencyUpperRight"
              ],
              "title": "Masks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-or-Setting-Tile-Group-Rule-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/adjacency",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/name",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule/tileDefinitions"
              ],
              "title": "Accessing or Setting Tile Group Rule Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKTileAdjacencyMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/title",
          "value": "SKTileAdjacencyMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyAll/title",
          "value": "SKTileAdjacencyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyLowerRight/title",
          "value": "SKTileHexFlatAdjacencyLowerRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyLowerRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyLowerRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUp/title",
          "value": "SKTileHexFlatAdjacencyUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRight/title",
          "value": "SKTileAdjacencyRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyUpperRight/title",
          "value": "SKTileHexPointyAdjacencyUpperRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyUpperRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyUpperRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyAll/title",
          "value": "SKTileHexFlatAdjacencyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUpperLeft/title",
          "value": "SKTileHexFlatAdjacencyUpperLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUpperLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyUpperLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyAdd/title",
          "value": "SKTileHexPointyAdjacencyAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyAdd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRightEdge/title",
          "value": "SKTileAdjacencyUpperRightEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRightEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperRightEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRight/title",
          "value": "SKTileAdjacencyLowerRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeftEdge/title",
          "value": "SKTileAdjacencyUpperLeftEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeftEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperLeftEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftCorner/title",
          "value": "SKTileAdjacencyLowerLeftCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeftCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUp/title",
          "value": "SKTileAdjacencyUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeft/title",
          "value": "SKTileAdjacencyLowerLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUpperRight/title",
          "value": "SKTileHexFlatAdjacencyUpperRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyUpperRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyUpperRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeftCorner/title",
          "value": "SKTileAdjacencyUpperLeftCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeftCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperLeftCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyLowerLeft/title",
          "value": "SKTileHexFlatAdjacencyLowerLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyLowerLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyLowerLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLowerRight/title",
          "value": "SKTileHexPointyAdjacencyLowerRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLowerRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyLowerRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyUpperLeft/title",
          "value": "SKTileHexPointyAdjacencyUpperLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyUpperLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyUpperLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRight/title",
          "value": "SKTileAdjacencyUpperRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLeft/title",
          "value": "SKTileHexPointyAdjacencyLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1adjacency/title",
          "value": "adjacency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1adjacency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adjacency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpEdge/title",
          "value": "SKTileAdjacencyUpEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightCorner/title",
          "value": "SKTileAdjacencyLowerRightCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRightCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDownEdge/title",
          "value": "SKTileAdjacencyDownEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDownEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyDownEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeftEdge/title",
          "value": "SKTileAdjacencyLeftEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeftEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLeftEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyDown/title",
          "value": "SKTileHexFlatAdjacencyDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexFlatAdjacencyDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexFlatAdjacencyDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeft/title",
          "value": "SKTileAdjacencyUpperLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyRight/title",
          "value": "SKTileHexPointyAdjacencyRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftEdge/title",
          "value": "SKTileAdjacencyLowerLeftEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeftEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLowerLeft/title",
          "value": "SKTileHexPointyAdjacencyLowerLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1hexPointyAdjacencyLowerLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileHexPointyAdjacencyLowerLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightEdge/title",
          "value": "SKTileAdjacencyLowerRightEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRightEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1tileDefinitions/title",
          "value": "tileDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule~1tileDefinitions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tileDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeft/title",
          "value": "SKTileAdjacencyLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDown/title",
          "value": "SKTileAdjacencyDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRightCorner/title",
          "value": "SKTileAdjacencyUpperRightCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperRightCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperRightCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRightEdge/title",
          "value": "SKTileAdjacencyRightEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRightEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyRightEdge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sktileadjacencymask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sktileadjacencymask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
