{
  "abstract": [
    {
      "text": "An object used to perform an animated transition to a new scene.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKTransition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKTransition"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTransition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKTransition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTransition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Scenes are the basic building blocks of games. Typically, you design self-contained scenes for the parts of your game, and then transition between these scenes as necessary. For example, you might create different scene classes to represent any or all of the following concepts:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A loading scene to display while other content is loaded",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A main menu scene to choose what kind of game the user wants to play",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A scene to configure the details of the specific kind of game the user chose",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A scene that provides the gameplay",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A scene displayed when gameplay ends",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you present a new scene in a view that is already presenting a scene, you have the option of using a transition to animate the change from the old scene to the new scene. Using a transition provides continuity so that the scene change is not quite so abrupt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition": {
      "abstract": [
        {
          "text": "An object used to perform an animated transition to a new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTransition"
        }
      ],
      "role": "symbol",
      "title": "SKTransition",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/crossFade(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a cross fade transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossFade"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/crossFade(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "crossFadeWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "crossFade(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/crossfade(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseHorizontal(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene appears as a pair of closing horizontal doors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorsCloseHorizontal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseHorizontal(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doorsCloseHorizontalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "doorsCloseHorizontal(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/doorsclosehorizontal(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseVertical(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene appears as a pair of closing vertical doors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorsCloseVertical"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseVertical(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doorsCloseVerticalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "doorsCloseVertical(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/doorsclosevertical(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenHorizontal(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene appears as a pair of opening horizontal doors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorsOpenHorizontal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenHorizontal(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doorsOpenHorizontalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "doorsOpenHorizontal(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/doorsopenhorizontal(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenVertical(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene appears as a pair of opening vertical doors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorsOpenVertical"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenVertical(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doorsOpenVerticalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "doorsOpenVertical(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/doorsopenvertical(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorway(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the previous scene disappears as a pair of opening doors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doorway"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorway(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doorwayWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "doorway(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/doorway(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(with:duration:)": {
      "abstract": [
        {
          "text": "Creates a transition that first fades to a constant color and then fades to the new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fade"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(with:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fadeWithColor:duration:"
        }
      ],
      "role": "symbol",
      "title": "fade(with:duration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/fade(with:duration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition that first fades to black and then fades to the new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fade"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fadeWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "fade(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/fade(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipHorizontal(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the two scenes are flipped across a horizontal line running through the center of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flipHorizontal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipHorizontal(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flipHorizontalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "flipHorizontal(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/fliphorizontal(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipVertical(withDuration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the two scenes are flipped across a vertical line running through the center of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flipVertical"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipVertical(withDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flipVerticalWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "flipVertical(withDuration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/flipvertical(withduration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/init(ciFilter:duration:)": {
      "abstract": [
        {
          "text": "Creates a transition that uses a Core Image filter to perform the transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ciFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/init(ciFilter:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitionWithCIFilter:duration:"
        }
      ],
      "role": "symbol",
      "title": "init(ciFilter:duration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/init(cifilter:duration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/moveIn(with:duration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene moves in on top of the old scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveIn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTransitionDirection",
          "text": "SKTransitionDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/moveIn(with:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveInWithDirection:duration:"
        }
      ],
      "role": "symbol",
      "title": "moveIn(with:duration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/movein(with:duration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesIncomingScene": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the incoming scene is paused during the transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausesIncomingScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesIncomingScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pausesIncomingScene"
        }
      ],
      "role": "symbol",
      "title": "pausesIncomingScene",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/pausesincomingscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesOutgoingScene": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the outgoing scene is paused during the transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausesOutgoingScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesOutgoingScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pausesOutgoingScene"
        }
      ],
      "role": "symbol",
      "title": "pausesOutgoingScene",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/pausesoutgoingscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/push(with:duration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the new scene moves in, pushing the old scene out of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "push"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTransitionDirection",
          "text": "SKTransitionDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/push(with:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushWithDirection:duration:"
        }
      ],
      "role": "symbol",
      "title": "push(with:duration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/push(with:duration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/reveal(with:duration:)": {
      "abstract": [
        {
          "text": "Creates a transition where the old scene moves out of the view, revealing the new scene underneath it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reveal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTransitionDirection",
          "text": "SKTransitionDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/reveal(with:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revealWithDirection:duration:"
        }
      ],
      "role": "symbol",
      "title": "reveal(with:duration:)",
      "type": "topic",
      "url": "/documentation/spritekit/sktransition/reveal(with:duration:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection": {
      "abstract": [
        {
          "text": "For some transitions, the direction in which the transition is performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTransitionDirection"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTransitionDirection"
        }
      ],
      "role": "symbol",
      "title": "SKTransitionDirection",
      "type": "topic",
      "url": "/documentation/spritekit/sktransitiondirection"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)": {
      "abstract": [
        {
          "text": "Presents a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKScene",
          "text": "SKScene"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentScene:"
        }
      ],
      "role": "symbol",
      "title": "presentScene(_:)",
      "type": "topic",
      "url": "/documentation/spritekit/skview/presentscene(_:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:transition:)": {
      "abstract": [
        {
          "text": "Transitions from the current scene to a new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKScene",
          "text": "SKScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTransition",
          "text": "SKTransition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:transition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentScene:transition:"
        }
      ],
      "role": "symbol",
      "title": "presentScene(_:transition:)",
      "type": "topic",
      "url": "/documentation/spritekit/skview/presentscene(_:transition:)"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView/scene": {
      "abstract": [
        {
          "text": "The scene currently presented by this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKScene",
          "text": "SKScene"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView/scene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scene"
        }
      ],
      "role": "symbol",
      "title": "scene",
      "type": "topic",
      "url": "/documentation/spritekit/skview/scene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/configuring-whether-animations-play-during-the-transition": {
      "abstract": [],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/configuring-whether-animations-play-during-the-transition",
      "kind": "article",
      "role": "article",
      "title": "Configuring Whether Animations Play During the Transition",
      "type": "topic",
      "url": "/documentation/spritekit/configuring-whether-animations-play-during-the-transition"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/transitioning-between-two-scenes": {
      "abstract": [],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/transitioning-between-two-scenes",
      "kind": "article",
      "role": "article",
      "title": "Transitioning Between Two Scenes",
      "type": "topic",
      "url": "/documentation/spritekit/transitioning-between-two-scenes"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-a-Scene",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKView/scene",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:transition:)"
      ],
      "title": "Displaying a Scene"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Transitions",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/transitioning-between-two-scenes",
        "doc://com.apple.spritekit/documentation/SpriteKit/configuring-whether-animations-play-during-the-transition",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/crossFade(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseHorizontal(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseVertical(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenHorizontal(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenVertical(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorway(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(with:duration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipHorizontal(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipVertical(withDuration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/moveIn(with:duration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/push(with:duration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/reveal(with:duration:)",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/init(ciFilter:duration:)"
      ],
      "title": "Creating Transitions"
    },
    {
      "anchor": "Pausing",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesIncomingScene",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesOutgoingScene"
      ],
      "title": "Pausing"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTransition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Transitions",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/transitioning-between-two-scenes",
                "doc://com.apple.spritekit/documentation/SpriteKit/configuring-whether-animations-play-during-the-transition",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/crossFade(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseHorizontal(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsCloseVertical(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenHorizontal(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorsOpenVertical(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/doorway(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(with:duration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/fade(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipHorizontal(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/flipVertical(withDuration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/moveIn(with:duration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/push(with:duration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/reveal(with:duration:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/init(ciFilter:duration:)"
              ],
              "title": "Creating Transitions"
            },
            {
              "anchor": "Pausing",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesIncomingScene",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransition/pausesOutgoingScene"
              ],
              "title": "Pausing"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-a-Scene",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKView/scene",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:)",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKView/presentScene(_:transition:)"
              ],
              "title": "Displaying a Scene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKTransition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1init(ciFilter:duration:)/title",
          "value": "transitionWithCIFilter:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1init(ciFilter:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "transitionWithCIFilter:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1crossFade(withDuration:)/title",
          "value": "crossFadeWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1crossFade(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "crossFadeWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsCloseHorizontal(withDuration:)/title",
          "value": "doorsCloseHorizontalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsCloseHorizontal(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "doorsCloseHorizontalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1flipHorizontal(withDuration:)/title",
          "value": "flipHorizontalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1flipHorizontal(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "flipHorizontalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1moveIn(with:duration:)/title",
          "value": "moveInWithDirection:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1moveIn(with:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "moveInWithDirection:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:transition:)/title",
          "value": "presentScene:transition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:transition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentScene:transition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsOpenHorizontal(withDuration:)/title",
          "value": "doorsOpenHorizontalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsOpenHorizontal(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "doorsOpenHorizontalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1reveal(with:duration:)/title",
          "value": "revealWithDirection:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1reveal(with:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "revealWithDirection:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/title",
          "value": "SKTransitionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransitionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransitionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1fade(with:duration:)/title",
          "value": "fadeWithColor:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1fade(with:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fadeWithColor:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1fade(withDuration:)/title",
          "value": "fadeWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1fade(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fadeWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsOpenVertical(withDuration:)/title",
          "value": "doorsOpenVerticalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsOpenVertical(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "doorsOpenVerticalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsCloseVertical(withDuration:)/title",
          "value": "doorsCloseVerticalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorsCloseVertical(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "doorsCloseVerticalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1flipVertical(withDuration:)/title",
          "value": "flipVerticalWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1flipVertical(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "flipVerticalWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1pausesOutgoingScene/title",
          "value": "pausesOutgoingScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1pausesOutgoingScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pausesOutgoingScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1push(with:duration:)/title",
          "value": "pushWithDirection:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1push(with:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pushWithDirection:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1scene/title",
          "value": "scene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1scene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:)/title",
          "value": "presentScene:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView~1presentScene(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentScene:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition/title",
          "value": "SKTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorway(withDuration:)/title",
          "value": "doorwayWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1doorway(withDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "doorwayWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1pausesIncomingScene/title",
          "value": "pausesIncomingScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransition~1pausesIncomingScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pausesIncomingScene"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sktransition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sktransition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
