{
  "abstract": [
    {
      "text": "Enumerations used across SpriteKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SpriteKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingMode": {
      "abstract": [
        {
          "text": "The modes that an action can use to adjust the apparent timing of the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKActionTimingMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKActionTimingMode"
        }
      ],
      "role": "symbol",
      "title": "SKActionTimingMode",
      "type": "topic",
      "url": "/documentation/spritekit/skactiontimingmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType": {
      "abstract": [
        {
          "text": "Options that specify an attribute’s data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAttributeType"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeType"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeType",
      "type": "topic",
      "url": "/documentation/spritekit/skattributetype"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode": {
      "abstract": [
        {
          "text": "The modes that describe how the source and destination pixel colors are used to calculate the new destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKBlendMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendMode"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode": {
      "abstract": [
        {
          "text": "The modes used to interpolate between keyframes in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKInterpolationMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKInterpolationMode"
        }
      ],
      "role": "symbol",
      "title": "SKInterpolationMode",
      "type": "topic",
      "url": "/documentation/spritekit/skinterpolationmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode": {
      "abstract": [
        {
          "text": "Options for aligning text horizontally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelHorizontalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelHorizontalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelHorizontalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelhorizontalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode": {
      "abstract": [
        {
          "text": "Options for aligning text vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKNodeFocusBehavior": {
      "abstract": [
        {
          "text": "Options for the focusable states of a SpriteKit node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNodeFocusBehavior"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKNodeFocusBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKNodeFocusBehavior"
        }
      ],
      "role": "symbol",
      "title": "SKNodeFocusBehavior",
      "type": "topic",
      "url": "/documentation/spritekit/sknodefocusbehavior"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKParticleRenderOrder": {
      "abstract": [
        {
          "text": "The order to use when the emitter’s particles are rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKParticleRenderOrder"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKParticleRenderOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKParticleRenderOrder"
        }
      ],
      "role": "symbol",
      "title": "SKParticleRenderOrder",
      "type": "topic",
      "url": "/documentation/spritekit/skparticlerenderorder"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode": {
      "abstract": [
        {
          "text": "The modes used to determine how the sequence repeats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "SKRepeatMode",
      "type": "topic",
      "url": "/documentation/spritekit/skrepeatmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode": {
      "abstract": [
        {
          "text": "The modes that determine how the scene’s area is mapped to the view that presents it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKSceneScaleMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKSceneScaleMode"
        }
      ],
      "role": "symbol",
      "title": "SKSceneScaleMode",
      "type": "topic",
      "url": "/documentation/spritekit/skscenescalemode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureFilteringMode": {
      "abstract": [
        {
          "text": "Texture filtering modes to use when the texture is drawn in a size other than its native size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTextureFilteringMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureFilteringMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTextureFilteringMode"
        }
      ],
      "role": "symbol",
      "title": "SKTextureFilteringMode",
      "type": "topic",
      "url": "/documentation/spritekit/sktexturefilteringmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask": {
      "abstract": [
        {
          "text": "An enumeration defining how neighboring tiles are automatically placed next to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "role": "symbol",
      "title": "SKTileAdjacencyMask",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinitionRotation": {
      "abstract": [
        {
          "text": "The allowed rotations for a given tile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileDefinitionRotation"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinitionRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileDefinitionRotation"
        }
      ],
      "role": "symbol",
      "title": "SKTileDefinitionRotation",
      "type": "topic",
      "url": "/documentation/spritekit/sktiledefinitionrotation"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSetType": {
      "abstract": [
        {
          "text": "An enumeration defining how tiles are arranged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileSetType"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSetType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileSetType"
        }
      ],
      "role": "symbol",
      "title": "SKTileSetType",
      "type": "topic",
      "url": "/documentation/spritekit/sktilesettype"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection": {
      "abstract": [
        {
          "text": "For some transitions, the direction in which the transition is performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTransitionDirection"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTransitionDirection"
        }
      ],
      "role": "symbol",
      "title": "SKTransitionDirection",
      "type": "topic",
      "url": "/documentation/spritekit/sktransitiondirection"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType": {
      "abstract": [
        {
          "text": "An enumerated type to identify the type of a uniform object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKUniformType"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformType"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants": {
      "abstract": [
        {
          "text": "Constants used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Constants",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-constants"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types": {
      "abstract": [
        {
          "text": "Data types used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Data Types",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-data-types"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases": {
      "abstract": [
        {
          "text": "Type aliases used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Type Aliases",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-type-aliases"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables": {
      "abstract": [
        {
          "text": "Global variables and macros used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Variables",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKParticleRenderOrder",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureFilteringMode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinitionRotation",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSetType",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKNodeFocusBehavior"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeType",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKInterpolationMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelHorizontalAlignmentMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKParticleRenderOrder",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKSceneScaleMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureFilteringMode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinitionRotation",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSetType",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTransitionDirection",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKNodeFocusBehavior"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/title",
          "value": "SKTransitionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransitionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTransitionDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTransitionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingMode/title",
          "value": "SKActionTimingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKActionTimingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKActionTimingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/title",
          "value": "SKSceneScaleMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKSceneScaleMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKSceneScaleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKParticleRenderOrder/title",
          "value": "SKParticleRenderOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKParticleRenderOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKParticleRenderOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKParticleRenderOrder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKParticleRenderOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinitionRotation/title",
          "value": "SKTileDefinitionRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinitionRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileDefinitionRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinitionRotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileDefinitionRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureFilteringMode/title",
          "value": "SKTextureFilteringMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureFilteringMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTextureFilteringMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureFilteringMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTextureFilteringMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/title",
          "value": "SKRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/title",
          "value": "SKUniformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNodeFocusBehavior/title",
          "value": "SKNodeFocusBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNodeFocusBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNodeFocusBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKNodeFocusBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKNodeFocusBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/title",
          "value": "SKTileAdjacencyMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/title",
          "value": "SKLabelHorizontalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelHorizontalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelHorizontalAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelHorizontalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/title",
          "value": "SKBlendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/title",
          "value": "SKInterpolationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKInterpolationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKInterpolationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKInterpolationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSetType/title",
          "value": "SKTileSetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSetType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileSetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSetType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileSetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/title",
          "value": "SKAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/title",
          "value": "SKLabelVerticalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/spritekit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/spritekit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
