{
  "abstract": [
    {
      "text": "Constants used across SpriteKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SpriteKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/PHYSICSKIT_MINUS_GL_IMPORTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHYSICSKIT_MINUS_GL_IMPORTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/PHYSICSKIT_MINUS_GL_IMPORTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHYSICSKIT_MINUS_GL_IMPORTS"
        }
      ],
      "role": "symbol",
      "title": "PHYSICSKIT_MINUS_GL_IMPORTS",
      "type": "topic",
      "url": "/documentation/spritekit/physicskit_minus_gl_imports"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types": {
      "abstract": [
        {
          "text": "Data types used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Data Types",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-data-types"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations": {
      "abstract": [
        {
          "text": "Enumerations used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Enumerations",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-enumerations"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases": {
      "abstract": [
        {
          "text": "Type aliases used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Type Aliases",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-type-aliases"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables": {
      "abstract": [
        {
          "text": "Global variables and macros used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Variables",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/PHYSICSKIT_MINUS_GL_IMPORTS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/PHYSICSKIT_MINUS_GL_IMPORTS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1PHYSICSKIT_MINUS_GL_IMPORTS/title",
          "value": "PHYSICSKIT_MINUS_GL_IMPORTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1PHYSICSKIT_MINUS_GL_IMPORTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHYSICSKIT_MINUS_GL_IMPORTS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/spritekit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/spritekit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
