{
  "abstract": [
    {
      "text": "Type aliases used across SpriteKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SpriteKit Type Aliases"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-swift.typealias": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKColor"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKColor"
        }
      ],
      "role": "symbol",
      "title": "SKColor",
      "type": "topic",
      "url": "/documentation/spritekit/skcolor-swift.typealias"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants": {
      "abstract": [
        {
          "text": "Constants used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Constants",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-constants"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types": {
      "abstract": [
        {
          "text": "Data types used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Data Types",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-data-types"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations": {
      "abstract": [
        {
          "text": "Enumerations used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Enumerations",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-enumerations"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables": {
      "abstract": [
        {
          "text": "Global variables and macros used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Variables",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKColor-swift.typealias"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/spritekit-type-aliases"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/spritekit-type-aliases"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
