{
  "abstract": [
    {
      "text": "Data types used across SpriteKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SpriteKit Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingFunction": {
      "abstract": [
        {
          "text": "The signature for the custom timing block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKActionTimingFunction"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKActionTimingFunction"
        }
      ],
      "role": "symbol",
      "title": "SKActionTimingFunction",
      "type": "topic",
      "url": "/documentation/spritekit/skactiontimingfunction"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldForceEvaluator": {
      "abstract": [
        {
          "text": "The definition for a custom block that processes a single physics body’s interaction with the field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKFieldForceEvaluator"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldForceEvaluator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKFieldForceEvaluator"
        }
      ],
      "role": "symbol",
      "title": "SKFieldForceEvaluator",
      "type": "topic",
      "url": "/documentation/spritekit/skfieldforceevaluator"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants": {
      "abstract": [
        {
          "text": "Constants used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Constants",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-constants"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations": {
      "abstract": [
        {
          "text": "Enumerations used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Enumerations",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-enumerations"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases": {
      "abstract": [
        {
          "text": "Type aliases used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Type Aliases",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-type-aliases"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables": {
      "abstract": [
        {
          "text": "Global variables and macros used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Variables",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-variables"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3": {
      "abstract": [
        {
          "text": "A floating point vector type used to perform physics calculations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_float3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_float3",
      "type": "topic",
      "url": "/documentation/spritekit/vector_float3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingFunction",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldForceEvaluator"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKActionTimingFunction",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldForceEvaluator",
                "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingFunction/title",
          "value": "SKActionTimingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKActionTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKActionTimingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKActionTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldForceEvaluator/title",
          "value": "SKFieldForceEvaluator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldForceEvaluator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldForceEvaluator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldForceEvaluator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldForceEvaluator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/spritekit-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/spritekit-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
