{
  "abstract": [
    {
      "text": "A universal identifier of the audio device linked to this device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/linkedCoreAudioDeviceUID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionDeviceProperties(py)linkedCoreAudioDeviceUID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "linkedCoreAudioDeviceUID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "linkedCoreAudioDeviceUID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "linkedCoreAudioDeviceUID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "linkedCoreAudioDeviceUID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The key for this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/deviceLinkedCoreAudioDeviceUID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties": {
      "abstract": [
        {
          "text": "An object that defines the properties of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDeviceProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/linkedCoreAudioDeviceUID": {
      "abstract": [
        {
          "text": "A universal identifier of the audio device linked to this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkedCoreAudioDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/linkedCoreAudioDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkedCoreAudioDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "linkedCoreAudioDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/linkedcoreaudiodeviceuid"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/model": {
      "abstract": [
        {
          "text": "A device model string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "model"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/model",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "model"
        }
      ],
      "role": "symbol",
      "title": "model",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/model"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/propertiesDictionary": {
      "abstract": [
        {
          "text": "A dictionary of properties for a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertiesDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
          "text": "CMIOExtensionPropertyState"
        },
        {
          "kind": "text",
          "text": "<AnyObject>]"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/propertiesDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertiesDictionary"
        }
      ],
      "role": "symbol",
      "title": "propertiesDictionary",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/propertiesdictionary"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/setPropertyState(_:forProperty:)": {
      "abstract": [
        {
          "text": "Sets the value of a device property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPropertyState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyState",
          "text": "CMIOExtensionPropertyState"
        },
        {
          "kind": "text",
          "text": "<AnyObject>?, "
        },
        {
          "kind": "externalParam",
          "text": "forProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/setPropertyState(_:forProperty:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPropertyState:forProperty:"
        }
      ],
      "role": "symbol",
      "title": "setPropertyState(_:forProperty:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/setpropertystate(_:forproperty:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-2ja7h": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device is in a suspended state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-2ja7h",
      "kind": "symbol",
      "role": "symbol",
      "title": "suspended",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/suspended-2ja7h"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-eru0": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device is in a suspended state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-eru0",
      "kind": "symbol",
      "role": "symbol",
      "title": "suspended",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/suspended-eru0"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-25qzh": {
      "abstract": [
        {
          "text": "The transport type of the device, such as USB or HDMI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "transportType"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-25qzh",
      "kind": "symbol",
      "role": "symbol",
      "title": "transportType",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/transporttype-25qzh"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-96gm": {
      "abstract": [
        {
          "text": "The transport type of the device, such as USB or HDMI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-96gm",
      "kind": "symbol",
      "role": "symbol",
      "title": "transportType",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties/transporttype-96gm"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/deviceLinkedCoreAudioDeviceUID": {
      "abstract": [
        {
          "text": "A property key for the UID of the linked Core Audio device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceLinkedCoreAudioDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/deviceLinkedCoreAudioDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyDeviceLinkedCoreAudioDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "deviceLinkedCoreAudioDeviceUID",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/devicelinkedcoreaudiodeviceuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Device-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/model",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-96gm",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-eru0",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/setPropertyState(_:forProperty:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/propertiesDictionary"
      ],
      "title": "Configuring Device Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "linkedCoreAudioDeviceUID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkedCoreAudioDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Device-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/model",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/transportType-25qzh",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/suspended-2ja7h",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/setPropertyState(_:forProperty:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties/propertiesDictionary"
              ],
              "title": "Configuring Device Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "linkedCoreAudioDeviceUID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1propertiesDictionary/title",
          "value": "propertiesDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1propertiesDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "propertiesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1deviceLinkedCoreAudioDeviceUID/title",
          "value": "CMIOExtensionPropertyDeviceLinkedCoreAudioDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1deviceLinkedCoreAudioDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyDeviceLinkedCoreAudioDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1model/title",
          "value": "model"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1model/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "model"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1linkedCoreAudioDeviceUID/title",
          "value": "linkedCoreAudioDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1linkedCoreAudioDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkedCoreAudioDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/title",
          "value": "CMIOExtensionDeviceProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1setPropertyState(_:forProperty:)/title",
          "value": "setPropertyState:forProperty:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties~1setPropertyState(_:forProperty:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPropertyState:forProperty:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensiondeviceproperties/linkedcoreaudiodeviceuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensiondeviceproperties/linkedcoreaudiodeviceuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
