{
  "abstract": [
    {
      "text": "Creates a named subscription for all records in a database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(subscriptionID:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "s:So22CKDatabaseSubscriptionC8CloudKitE14subscriptionIDABSS_tcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "subscriptionID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKSubscription",
        "text": "CKSubscription"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
        "text": "ID"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(subscriptionID:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "subscriptionID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKSubscription",
              "text": "CKSubscription"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The subscription’s name. It must be unique in the container, and must not be an empty string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "subscriptionID"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription": {
      "abstract": [
        {
          "text": "A subscription that generates push notifications when CloudKit modifies records in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabaseSubscription"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabaseSubscription"
        }
      ],
      "role": "symbol",
      "title": "CKDatabaseSubscription",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabasesubscription"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init()": {
      "abstract": [
        {
          "text": "Creates an empty database subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabasesubscription/init()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a database subscription from a serialized instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabasesubscription/init(coder:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(subscriptionID:)": {
      "abstract": [
        {
          "text": "Creates a named subscription for all records in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "subscriptionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(subscriptionID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(subscriptionID:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabasesubscription/init(subscriptionid:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription": {
      "abstract": [
        {
          "text": "An abstract base class for subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSubscription"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSubscription"
        }
      ],
      "role": "symbol",
      "title": "CKSubscription",
      "type": "topic",
      "url": "/documentation/cloudkit/cksubscription"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription/ID": {
      "abstract": [
        {
          "text": "A type that represents a subscription’s identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKSubscription.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/cksubscription/id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Database-Subscription",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init()",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseSubscription/init(coder:)"
      ],
      "title": "Creating a Database Subscription"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/title",
          "value": "CKSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription/title",
          "value": "CKDatabaseSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseSubscription~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckdatabasesubscription/init(subscriptionid:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
