{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentActivity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"This property contains a workout activity that’s currently in progress (an activity with an ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity/endDate","isActive":true,"type":"reference"},{"text":" property set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":"). If you end the activity — for example, by calling ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)","isActive":true,"type":"reference"},{"text":" — the system sets this property to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" until you begin a new activity.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"anchor":"Managing-workout-activities","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)"],"generated":true,"title":"Managing workout activities"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"abstract":[{"text":"The current workout activity.","type":"text"}],"kind":"symbol","variants":[{"paths":["/documentation/healthkit/hkworkoutsession/currentactivity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkworkoutsession/currentactivity"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"currentActivity","modules":[{"name":"HealthKit"}],"role":"symbol","roleHeading":"Instance Property","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"17.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"17.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"17.0","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","introducedAt":"9.0","beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentActivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity"}],"externalID":"c:objc(cs)HKWorkoutSession(py)currentActivity","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"currentActivity"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/currentActivity","interfaceLanguage":"swift"},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession":{"type":"topic","url":"/documentation/healthkit/hkworkoutsession","title":"HKWorkoutSession","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A session that tracks the user’s workout on Apple Watch."}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSession"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity":{"abstract":[{"text":"An object that describes an activity within a longer workout.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutActivity"}],"title":"HKWorkoutActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutActivity"}],"role":"symbol","url":"/documentation/healthkit/hkworkoutactivity","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity/endDate":{"url":"/documentation/healthkit/hkworkoutactivity/enddate","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity/endDate","kind":"symbol","title":"endDate","abstract":[{"text":"The activity’s end date and time.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"endDate","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)":{"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)","type":"topic","title":"endCurrentActivity(on:)","abstract":[{"type":"text","text":"Ends the current workout activity."}],"navigatorTitle":[{"kind":"identifier","text":"endCurrentActivityOnDate:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endCurrentActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":")"}],"url":"/documentation/healthkit/hkworkoutsession/endcurrentactivity(on:)","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)":{"title":"beginNewActivity(configuration:date:metadata:)","role":"symbol","navigatorTitle":[{"text":"beginNewActivityWithConfiguration:date:metadata:","kind":"identifier"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsession/beginnewactivity(configuration:date:metadata:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginNewActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKWorkoutConfiguration","kind":"typeIdentifier","text":"HKWorkoutConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"abstract":[{"type":"text","text":"Begins a new workout activity in the workout session."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/currentActivity":{"title":"currentActivity","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentActivity"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsession/currentactivity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/currentActivity","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentActivity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier","text":"HKWorkoutActivity"}],"abstract":[{"type":"text","text":"The current workout activity."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updateActivityWithUUID:endDate:completion:"}],"title":"updateActivity(uuid:end:completion:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"end","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Sets the end date for a workout activity that you’ve already added to the workout builder.","type":"text"}],"kind":"symbol","url":"/documentation/healthkit/hkworkoutbuilder/updateactivity(uuid:end:completion:)","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false},{"name":"watchOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"currentActivity","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"currentActivity"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)"],"title":"Managing workout activities","generated":true,"anchor":"Managing-workout-activities"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity","kind":"typeIdentifier","text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentActivity"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"HKWorkoutSession","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title"},{"value":[{"text":"HKWorkoutSession","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments"},{"value":[{"text":"HKWorkoutSession","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle"},{"value":"HKWorkoutActivity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title"},{"value":[{"text":"HKWorkoutActivity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments"},{"value":[{"kind":"identifier","text":"HKWorkoutActivity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle"},{"value":"endDate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity~1endDate/title"},{"value":[{"text":"endDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity~1endDate/fragments"},{"value":"endCurrentActivityOnDate:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1endCurrentActivity(on:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"endCurrentActivityOnDate:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1endCurrentActivity(on:)/fragments"},{"value":"beginNewActivityWithConfiguration:date:metadata:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1beginNewActivity(configuration:date:metadata:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginNewActivityWithConfiguration:date:metadata:"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1beginNewActivity(configuration:date:metadata:)/fragments"},{"value":"currentActivity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1currentActivity/title"},{"value":[{"kind":"identifier","text":"currentActivity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1currentActivity/fragments"},{"value":"updateActivityWithUUID:endDate:completion:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:end:completion:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateActivityWithUUID:endDate:completion:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:end:completion:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}