{"abstract":[{"type":"text","text":"The workout session’s delegate."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkworkoutsession/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkworkoutsession/delegate"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"metadata":{"title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"HKWorkoutSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)HKWorkoutSessionDelegate"},{"text":")?","kind":"text"}],"externalID":"c:objc(cs)HKWorkoutSession(py)delegate","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.0","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0","name":"watchOS"}],"modules":[{"name":"HealthKit"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/delegate","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate","preciseIdentifier":"c:objc(pl)HKWorkoutSessionDelegate","text":"HKWorkoutSessionDelegate","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The delegate receives notifications when a workout session’s state changes or when a workout session fails."}],"type":"paragraph"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"],"generated":true,"title":"Monitoring the session","anchor":"Monitoring-the-session"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsessiondelegate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate","role":"symbol","abstract":[{"text":"The session delegate protocol that defines an interface for receiving notifications about errors and changes in the workout session’s state.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"kind":"symbol","title":"HKWorkoutSessionDelegate"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/delegate":{"abstract":[{"type":"text","text":"The workout session’s delegate."}],"title":"delegate","type":"topic","url":"/documentation/healthkit/hkworkoutsession/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/delegate","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)HKWorkoutSessionDelegate","text":"HKWorkoutSessionDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession":{"type":"topic","url":"/documentation/healthkit/hkworkoutsession","title":"HKWorkoutSession","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A session that tracks the user’s workout on Apple Watch."}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSession"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"17.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"17.0"},{"introducedAt":"17.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"},{"introducedAt":"2.0","beta":false,"unavailable":false,"deprecated":false,"name":"watchOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"delegate","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"],"generated":true,"title":"Monitoring the session","anchor":"Monitoring-the-session"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)HKWorkoutSessionDelegate","text":"id<HKWorkoutSessionDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/title","value":"HKWorkoutSessionDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/fragments","value":[{"text":"HKWorkoutSessionDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/navigatorTitle","value":[{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1delegate/title","value":"delegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1delegate/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":"HKWorkoutSession","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title"},{"value":[{"kind":"identifier","text":"HKWorkoutSession"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments"},{"value":[{"text":"HKWorkoutSession","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}