{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"abstract":[{"text":"Sends the provided data to the remote workout session.","type":"text"}],"variants":[{"paths":["/documentation/healthkit/hkworkoutsession/sendtoremoteworkoutsession(data:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkworkoutsession/sendtoremoteworkoutsession(data:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/startMirroringToCompanionDevice(completion:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/stopMirroringToCompanionDevice(completion:)"],"title":"Working with remote workout sessions","generated":true,"anchor":"Working-with-remote-workout-sessions"}],"metadata":{"externalID":"c:objc(cs)HKWorkoutSession(im)sendDataToRemoteWorkoutSession:completion:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"sendDataToRemoteWorkoutSession:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendToRemoteWorkoutSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","title":"sendToRemoteWorkoutSession(data:completion:)","platforms":[{"name":"iOS","introducedAt":"17.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"17.0","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"beta":false,"introducedAt":"10.0","deprecated":false,"name":"watchOS"}],"modules":[{"name":"HealthKit"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/sendToRemoteWorkoutSession(data:completion:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendToRemoteWorkoutSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]},{"platforms":["iOS","iPadOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendToRemoteWorkoutSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A data object that contains the data your app is sending to the remote workout session.","type":"text"}],"type":"paragraph"}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block that the system calls when the send attempt is complete. The system passes the following parameters:","type":"text"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"code":"success","type":"codeVoice"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value that indicates whether the system successfully sent the data."}]}]}},{"term":{"inlineContent":[{"type":"codeVoice","code":"error"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"code":"sucess","type":"codeVoice"},{"text":" is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":", this contains an object that describes the error. Otherwise, it’s ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}}]}],"name":"completion"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"Call this method to send data to your remote workout session. You can send data from either the ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary","isActive":true,"type":"reference"},{"text":" session.","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["let archivedData = try? NSKeyedArchiver.archivedData(withRootObject: data, requiringSecureCoding: true)","guard let archivedData = archivedData, !archivedData.isEmpty else {","    // Handle the error here.","    fatalError(\"*** Encoded data is empty ***\")","}","","// Send the data to the companion iPhone.","Task {","    do {","        try await session.sendToRemoteWorkoutSession(data: archivedData)","    }","    catch {","        // Handle the error here.","        fatalError(\"*** An error occurred while sending the health data to the companion iPhone: \\(error.localizedDescription) ***\")","    }","}"]}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:s4Voida":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","title":"Void","url":"/documentation/Swift/Void","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"role":"symbol","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}]},"doc://com.apple.documentation/documentation/swift/false":{"abstract":[{"type":"text","text":"A false value."}],"identifier":"doc://com.apple.documentation/documentation/swift/false","url":"/documentation/swift/false","kind":"symbol","type":"topic","role":"symbol","title":"false"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession":{"type":"topic","url":"/documentation/healthkit/hkworkoutsession","title":"HKWorkoutSession","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A session that tracks the user’s workout on Apple Watch."}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSession"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","title":"Error","url":"/documentation/Swift/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Sendable","preciseIdentifier":"s:s8SendableP"}],"role":"symbol","abstract":[{"text":"A type representing an error value that can be thrown.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","title":"NSError","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"url":"/documentation/foundation/nserror","type":"topic"},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Data"}],"type":"topic","url":"/documentation/foundation/data","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","role":"symbol","abstract":[{"text":"A byte buffer in memory.","type":"text"}],"kind":"symbol","title":"Data"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","type":"topic","abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"kind":"symbol","url":"/documentation/objectivec/bool","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary":{"kind":"symbol","abstract":[{"type":"text","text":"A primary session running on watchOS."}],"url":"/documentation/healthkit/hkworkoutsessiontype/primary","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"primary"}],"title":"HKWorkoutSessionType.primary","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionTypePrimary"}]},"doc://com.externally.resolved.symbol/s:Sb":{"abstract":[{"text":"A value type whose instances are either `true` or `false`.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:Sb","url":"/documentation/Swift/Bool","kind":"symbol","type":"topic","role":"symbol","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored":{"kind":"symbol","abstract":[{"type":"text","text":"A mirrored session, running on the companion iOS device."}],"url":"/documentation/healthkit/hkworkoutsessiontype/mirrored","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"}],"title":"HKWorkoutSessionType.mirrored","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionTypeMirrored"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/startMirroringToCompanionDevice(completion:)":{"title":"startMirroringToCompanionDevice(completion:)","navigatorTitle":[{"text":"startMirroringToCompanionDeviceWithCompletion:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/startMirroringToCompanionDevice(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMirroringToCompanionDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Starts mirroring the workout session to the companion iOS device."}],"role":"symbol","type":"topic","url":"/documentation/healthkit/hkworkoutsession/startmirroringtocompaniondevice(completion:)","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/sendToRemoteWorkoutSession(data:completion:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/sendToRemoteWorkoutSession(data:completion:)","abstract":[{"type":"text","text":"Sends the provided data to the remote workout session."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendToRemoteWorkoutSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"/documentation/healthkit/hkworkoutsession/sendtoremoteworkoutsession(data:completion:)","navigatorTitle":[{"kind":"identifier","text":"sendDataToRemoteWorkoutSession:completion:"}],"type":"topic","kind":"symbol","title":"sendToRemoteWorkoutSession(data:completion:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/stopMirroringToCompanionDevice(completion:)":{"role":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/stopMirroringToCompanionDevice(completion:)","title":"stopMirroringToCompanionDevice(completion:)","kind":"symbol","url":"/documentation/healthkit/hkworkoutsession/stopmirroringtocompaniondevice(completion:)","abstract":[{"text":"Stops mirroring the workout session to the companion iOS device.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopMirroringToCompanionDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"stopMirroringToCompanionDeviceWithCompletion:"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"17.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"17.0","deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false},{"name":"watchOS","beta":false,"unavailable":false,"introducedAt":"10.0","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"sendDataToRemoteWorkoutSession:completion:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendDataToRemoteWorkoutSession:completion:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Working-with-remote-workout-sessions","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/startMirroringToCompanionDevice(completion:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/stopMirroringToCompanionDevice(completion:)"],"title":"Working with remote workout sessions"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sendDataToRemoteWorkoutSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":", "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"A data object that contains the data your app is sending to the remote workout session.","type":"text"}],"type":"paragraph"}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block that the system calls when the send attempt is complete. The system passes the following parameters:","type":"text"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"code":"success","type":"codeVoice"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"A Boolean value that indicates whether the system successfully sent the data.","type":"text"}]}]}},{"term":{"inlineContent":[{"code":"error","type":"codeVoice"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"sucess"},{"text":" is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":", this contains an object that describes the error. Otherwise, it’s ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}]}}]}],"name":"completion"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title","op":"replace","value":"HKWorkoutSession"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments","op":"replace","value":[{"text":"HKWorkoutSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle","op":"replace","value":[{"text":"HKWorkoutSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1primary/title","op":"replace","value":"HKWorkoutSessionTypePrimary"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1primary/fragments","op":"replace","value":[{"text":"HKWorkoutSessionTypePrimary","kind":"identifier"}]},{"value":"HKWorkoutSessionTypeMirrored","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1mirrored/title","op":"replace"},{"value":[{"kind":"identifier","text":"HKWorkoutSessionTypeMirrored"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1mirrored/fragments","op":"replace"},{"value":"startMirroringToCompanionDeviceWithCompletion:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1startMirroringToCompanionDevice(completion:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startMirroringToCompanionDeviceWithCompletion:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1startMirroringToCompanionDevice(completion:)/fragments","op":"replace"},{"value":"sendDataToRemoteWorkoutSession:completion:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1sendToRemoteWorkoutSession(data:completion:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"sendDataToRemoteWorkoutSession:completion:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1sendToRemoteWorkoutSession(data:completion:)/fragments","op":"replace"},{"value":"stopMirroringToCompanionDeviceWithCompletion:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1stopMirroringToCompanionDevice(completion:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopMirroringToCompanionDeviceWithCompletion:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1stopMirroringToCompanionDevice(completion:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}