{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/uuid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOUSBHostControllerInterface(py)uuid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "uuid"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4UUIDV",
        "text": "UUID"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "uuid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "uuid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "uuid"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4UUIDV",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterface"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterface"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterface",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/capabilities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostCIMessage",
          "text": "IOUSBHostCIMessage"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/capabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capabilities"
        }
      ],
      "role": "symbol",
      "title": "capabilities",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface/capabilities"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/controllerStateMachine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controllerStateMachine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOUSBHostCIControllerStateMachine",
          "text": "IOUSBHostCIControllerStateMachine"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/controllerStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controllerStateMachine"
        }
      ],
      "role": "symbol",
      "title": "controllerStateMachine",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface/controllerstatemachine"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/interruptRateHz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interruptRateHz"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/interruptRateHz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interruptRateHz"
        }
      ],
      "role": "symbol",
      "title": "interruptRateHz",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface/interruptratehz"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/queue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/queue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queue"
        }
      ],
      "role": "symbol",
      "title": "queue",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface/queue"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/uuid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/uuid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uuid"
        }
      ],
      "role": "symbol",
      "title": "uuid",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface/uuid"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV": {
      "abstract": [
        {
          "text": "A universally unique value to identify types, interfaces, and other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/foundation/uuid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/capabilities",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/controllerStateMachine",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/interruptRateHz",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/queue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "uuid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uuid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/capabilities",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/controllerStateMachine",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/interruptRateHz",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface/queue"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUUID",
                    "text": "NSUUID"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "uuid"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/title",
          "value": "IOUSBHostControllerInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1queue/title",
          "value": "queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1queue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1controllerStateMachine/title",
          "value": "controllerStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1controllerStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controllerStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1interruptRateHz/title",
          "value": "interruptRateHz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1interruptRateHz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interruptRateHz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1uuid/title",
          "value": "uuid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1uuid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uuid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1capabilities/title",
          "value": "capabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface~1capabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "capabilities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcontrollerinterface/uuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcontrollerinterface/uuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
