{
  "abstract": [
    {
      "text": "Language acquisition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ClassKit",
    "externalID": "c:@CLSContextTopicWorldLanguage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "worldLanguage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CLSContextTopic",
        "text": "CLSContextTopic"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSContextTopicWorldLanguage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "worldLanguage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "worldLanguage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLSContextTopic",
              "text": "CLSContextTopic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic": {
      "abstract": [
        {
          "text": "The areas of study to which contexts may relate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopic"
        }
      ],
      "role": "symbol",
      "title": "CLSContextTopic",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic": {
      "abstract": [
        {
          "text": "Arts and music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artsAndMusic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicArtsAndMusic"
        }
      ],
      "role": "symbol",
      "title": "artsAndMusic",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/artsandmusic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering": {
      "abstract": [
        {
          "text": "Computer science and engineering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computerScienceAndEngineering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicComputerScienceAndEngineering"
        }
      ],
      "role": "symbol",
      "title": "computerScienceAndEngineering",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/computerscienceandengineering"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness": {
      "abstract": [
        {
          "text": "Health and fitness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "healthAndFitness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicHealthAndFitness"
        }
      ],
      "role": "symbol",
      "title": "healthAndFitness",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/healthandfitness"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting": {
      "abstract": [
        {
          "text": "Literacy and writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "literacyAndWriting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicLiteracyAndWriting"
        }
      ],
      "role": "symbol",
      "title": "literacyAndWriting",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/literacyandwriting"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math": {
      "abstract": [
        {
          "text": "Mathematics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "math"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicMath"
        }
      ],
      "role": "symbol",
      "title": "math",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/math"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science": {
      "abstract": [
        {
          "text": "Science.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "science"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicScience"
        }
      ],
      "role": "symbol",
      "title": "science",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/science"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience": {
      "abstract": [
        {
          "text": "Social science.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "socialScience"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicSocialScience"
        }
      ],
      "role": "symbol",
      "title": "socialScience",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/socialscience"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage": {
      "abstract": [
        {
          "text": "Language acquisition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/worldLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextTopicWorldLanguage"
        }
      ],
      "role": "symbol",
      "title": "worldLanguage",
      "type": "topic",
      "url": "/documentation/classkit/clscontexttopic/worldlanguage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Context-Topics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience"
      ],
      "title": "Context Topics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSContextTopicWorldLanguage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicWorldLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Context-Topics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/artsAndMusic",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/computerScienceAndEngineering",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/healthAndFitness",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/literacyAndWriting",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/math",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/science",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic/socialScience"
              ],
              "title": "Context Topics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextTopic",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CLSContextTopic",
                    "text": "CLSContextTopic"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLSContextTopicWorldLanguage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1socialScience/title",
          "value": "CLSContextTopicSocialScience"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1socialScience/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicSocialScience"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1healthAndFitness/title",
          "value": "CLSContextTopicHealthAndFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1healthAndFitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicHealthAndFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1worldLanguage/title",
          "value": "CLSContextTopicWorldLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1worldLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicWorldLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/title",
          "value": "CLSContextTopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1computerScienceAndEngineering/title",
          "value": "CLSContextTopicComputerScienceAndEngineering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1computerScienceAndEngineering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicComputerScienceAndEngineering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1literacyAndWriting/title",
          "value": "CLSContextTopicLiteracyAndWriting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1literacyAndWriting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicLiteracyAndWriting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1science/title",
          "value": "CLSContextTopicScience"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1science/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicScience"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1artsAndMusic/title",
          "value": "CLSContextTopicArtsAndMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1artsAndMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicArtsAndMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1math/title",
          "value": "CLSContextTopicMath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextTopic~1math/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextTopicMath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clscontexttopic/worldlanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clscontexttopic/worldlanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
