{
  "abstract": [
    {
      "text": "The default index for a player on a controller.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/indexUnset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GCControllerPlayerIndex@GCControllerPlayerIndexUnset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "indexUnset"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCControllerPlayerIndexUnset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GCControllerPlayerIndex.indexUnset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "indexUnset"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex": {
      "abstract": [
        {
          "text": "The possible values for controller player indices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index1": {
      "abstract": [
        {
          "text": "Player one is using the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index1"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex1"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex.index1",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex/index1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index2": {
      "abstract": [
        {
          "text": "Player two is using the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index2"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex2"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex.index2",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex/index2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index3": {
      "abstract": [
        {
          "text": "Player three is using the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index3"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex3"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex.index3",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex/index3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index4": {
      "abstract": [
        {
          "text": "Player four is using the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index4"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndex4"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex.index4",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex/index4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/indexUnset": {
      "abstract": [
        {
          "text": "The default index for a player on a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexUnset"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/indexUnset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerPlayerIndexUnset"
        }
      ],
      "role": "symbol",
      "title": "GCControllerPlayerIndex.indexUnset",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerplayerindex/indexunset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Player-indices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index1",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index3",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index4"
      ],
      "title": "Player indices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCControllerPlayerIndexUnset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndexUnset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Player-indices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index1",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index3",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerPlayerIndex/index4"
              ],
              "title": "Player indices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GCControllerPlayerIndexUnset"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index2/title",
          "value": "GCControllerPlayerIndex2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1indexUnset/title",
          "value": "GCControllerPlayerIndexUnset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1indexUnset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndexUnset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex/title",
          "value": "GCControllerPlayerIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index4/title",
          "value": "GCControllerPlayerIndex4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index3/title",
          "value": "GCControllerPlayerIndex3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index1/title",
          "value": "GCControllerPlayerIndex1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerPlayerIndex~1index1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerPlayerIndex1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gccontrollerplayerindex/indexunset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gccontrollerplayerindex/indexunset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
