{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayReverse"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayReverse"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"abstract":[{"text":"A Boolean value that indicates whether the item can play in reverse.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/canplayreverse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/canplayreverse"]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)AVPlayerItem(py)canPlayReverse","extendedModule":"AVFoundation","symbolKind":"property","title":"canPlayReverse","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayReverse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"canPlayReverse"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"6.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"6.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1","beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.8","beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false},{"name":"watchOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false}],"modules":[{"name":"AVFoundation"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Determining-Playback-Capabilities","title":"Determining Playback Capabilities","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastForward","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastReverse","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowForward","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowReverse"],"generated":true}],"sections":[],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastReverse":{"url":"/documentation/avfoundation/avplayeritem/canplayfastreverse","abstract":[{"text":"A Boolean value that indicates whether the item can be quickly reversed.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayFastReverse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"canPlayFastReverse","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastReverse","type":"topic","navigatorTitle":[{"text":"canPlayFastReverse","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayReverse":{"abstract":[{"text":"A Boolean value that indicates whether the item can play in reverse.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayReverse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayReverse","type":"topic","title":"canPlayReverse","url":"/documentation/avfoundation/avplayeritem/canplayreverse","role":"symbol","navigatorTitle":[{"text":"canPlayReverse","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowReverse":{"title":"canPlaySlowReverse","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowReverse","kind":"symbol","navigatorTitle":[{"text":"canPlaySlowReverse","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlaySlowReverse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/canplayslowreverse","abstract":[{"text":"A Boolean value that indicates whether the item can play slowly backward.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastForward":{"abstract":[{"text":"A Boolean value that indicates whether the item can be fast forwarded.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayFastForward","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastForward","type":"topic","title":"canPlayFastForward","url":"/documentation/avfoundation/avplayeritem/canplayfastforward","role":"symbol","navigatorTitle":[{"text":"canPlayFastForward","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowForward":{"title":"canPlaySlowForward","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowForward","kind":"symbol","navigatorTitle":[{"text":"canPlaySlowForward","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlaySlowForward","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/canplayslowforward","abstract":[{"type":"text","text":"A Boolean value that indicates whether the item can play slower than normal."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"6.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"6.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1","beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.8","beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false},{"name":"watchOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"canPlayReverse"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"canPlayReverse","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Determining Playback Capabilities","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastForward","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlayFastReverse","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowForward","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/canPlaySlowReverse"],"anchor":"Determining-Playback-Capabilities"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayReverse"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"canPlayFastReverse","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayFastReverse/title","op":"replace"},{"value":[{"kind":"identifier","text":"canPlayFastReverse"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayFastReverse/fragments","op":"replace"},{"value":"canPlayReverse","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayReverse/title","op":"replace"},{"value":[{"text":"canPlayReverse","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayReverse/fragments","op":"replace"},{"value":"canPlaySlowReverse","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlaySlowReverse/title","op":"replace"},{"value":[{"text":"canPlaySlowReverse","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlaySlowReverse/fragments","op":"replace"},{"value":"AVPlayerItem","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVPlayerItem"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVPlayerItem"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","op":"replace"},{"value":"canPlayFastForward","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayFastForward/title","op":"replace"},{"value":[{"text":"canPlayFastForward","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlayFastForward/fragments","op":"replace"},{"value":"canPlaySlowForward","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlaySlowForward/title","op":"replace"},{"value":[{"text":"canPlaySlowForward","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1canPlaySlowForward/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}