{"seeAlsoSections":[{"title":"Managing Time Offsets","generated":true,"anchor":"Managing-Time-Offsets","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/automaticallyPreservesTimeOffsetFromLive","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/recommendedTimeOffsetFromLive"]}],"metadata":{"externalID":"c:objc(cs)AVPlayerItem(py)configuredTimeOffsetFromLive","navigatorTitle":[{"text":"configuredTimeOffsetFromLive","kind":"identifier"}],"symbolKind":"property","platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"unavailable":false,"name":"macOS","introducedAt":"10.15","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","introducedAt":"13.0","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","introducedAt":"6.0","deprecated":false,"beta":false}],"modules":[{"name":"AVFoundation"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuredTimeOffsetFromLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"}],"extendedModule":"AVFoundation","title":"configuredTimeOffsetFromLive","roleHeading":"Instance Property","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuredTimeOffsetFromLive"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"For nonlive stream content, the value is ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/configuredTimeOffsetFromLive","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A time value that indicates the offset from the live time to start playback, or resume playback after a seek to positive infinity."}],"variants":[{"paths":["/documentation/avfoundation/avplayeritem/configuredtimeoffsetfromlive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avplayeritem/configuredtimeoffsetfromlive"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/configuredTimeOffsetFromLive":{"title":"configuredTimeOffsetFromLive","navigatorTitle":[{"kind":"identifier","text":"configuredTimeOffsetFromLive"}],"abstract":[{"type":"text","text":"A time value that indicates the offset from the live time to start playback, or resume playback after a seek to positive infinity."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuredTimeOffsetFromLive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"}],"role":"symbol","kind":"symbol","type":"topic","url":"/documentation/avfoundation/avplayeritem/configuredtimeoffsetfromlive","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/configuredTimeOffsetFromLive"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"}],"abstract":[{"type":"text","text":"A value that represents an invalid time."}],"type":"topic","title":"invalid","url":"/documentation/CoreMedia/CMTime/invalid","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/automaticallyPreservesTimeOffsetFromLive":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/automaticallyPreservesTimeOffsetFromLive","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticallyPreservesTimeOffsetFromLive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/avfoundation/avplayeritem/automaticallypreservestimeoffsetfromlive","type":"topic","abstract":[{"text":"A Boolean value that indicates whether the player preserves its time offset from the live time after a buffering operation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"automaticallyPreservesTimeOffsetFromLive","kind":"identifier"}],"title":"automaticallyPreservesTimeOffsetFromLive"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@SA@CMTime":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTime","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that represents time."}],"type":"topic","title":"CMTime","url":"/documentation/CoreMedia/CMTime","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/recommendedTimeOffsetFromLive":{"url":"/documentation/avfoundation/avplayeritem/recommendedtimeoffsetfromlive","abstract":[{"text":"A recommended time offset from the live time based on observed network conditions.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/recommendedTimeOffsetFromLive","title":"recommendedTimeOffsetFromLive","navigatorTitle":[{"kind":"identifier","text":"recommendedTimeOffsetFromLive"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommendedTimeOffsetFromLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.15"},{"name":"tvOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"6.0","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"path":"/metadata/title","op":"replace","value":"configuredTimeOffsetFromLive"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"configuredTimeOffsetFromLive"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Managing Time Offsets","generated":true,"anchor":"Managing-Time-Offsets","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/automaticallyPreservesTimeOffsetFromLive","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/recommendedTimeOffsetFromLive"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"text":" ","kind":"text"},{"text":"configuredTimeOffsetFromLive","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1configuredTimeOffsetFromLive/title","value":"configuredTimeOffsetFromLive","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1configuredTimeOffsetFromLive/fragments","value":[{"text":"configuredTimeOffsetFromLive","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","value":"AVPlayerItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","value":[{"kind":"identifier","text":"AVPlayerItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","value":[{"kind":"identifier","text":"AVPlayerItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1invalid/title","value":"kCMTimeInvalid","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1invalid/fragments","value":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"kCMTimeInvalid"},{"kind":"text","text":";"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1automaticallyPreservesTimeOffsetFromLive/title","value":"automaticallyPreservesTimeOffsetFromLive","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1automaticallyPreservesTimeOffsetFromLive/fragments","value":[{"kind":"identifier","text":"automaticallyPreservesTimeOffsetFromLive"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"CMTime","kind":"identifier"},{"text":";","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1recommendedTimeOffsetFromLive/title","value":"recommendedTimeOffsetFromLive","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1recommendedTimeOffsetFromLive/fragments","value":[{"kind":"identifier","text":"recommendedTimeOffsetFromLive"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}