{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAuthorizationRequestStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVContentAuthorizationStatus","kind":"typeIdentifier","text":"AVContentAuthorizationStatus","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property reports the authorization status as determined by the most recent call to "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value will be "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown"},{"type":"text","text":" before the first call and between the time a request call is made and just prior to the completion handler being executed (thus it is safe to query this property from the completion handler)."}]},{"type":"paragraph","inlineContent":[{"text":"This value is not key-value observable.","type":"text"}]}]}],"metadata":{"symbolKind":"property","extendedModule":"AVFoundation","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAuthorizationRequestStatus"},{"kind":"text","text":": "},{"text":"AVContentAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVContentAuthorizationStatus"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)AVPlayerItem(py)contentAuthorizationRequestStatus","platforms":[{"introducedAt":"10.7","beta":false,"unavailable":false,"name":"macOS","deprecated":false}],"title":"contentAuthorizationRequestStatus","navigatorTitle":[{"text":"contentAuthorizationRequestStatus","kind":"identifier"}],"modules":[{"name":"AVFoundation"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/contentauthorizationrequeststatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/contentauthorizationrequeststatus"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"abstract":[{"type":"text","text":"The status of the most recent content authorization request."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"],"generated":true,"anchor":"Managing-Playback-Authorization-in-macOS","title":"Managing Playback Authorization in macOS"}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus","interfaceLanguage":"swift"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)":{"url":"/documentation/avfoundation/avplayeritem/requestcontentauthorizationasynchronously(withtimeoutinterval:completionhandler:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestContentAuthorizationAsynchronously","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTimeoutInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Presents the user the opportunity to authorize the content for playback."}],"title":"requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback":{"title":"isContentAuthorizedForPlayback","abstract":[{"type":"text","text":"A Boolean value that indicates whether the content has been authorized by the user."}],"role":"symbol","navigatorTitle":[{"text":"contentAuthorizedForPlayback","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContentAuthorizedForPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/iscontentauthorizedforplayback","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback":{"type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isApplicationAuthorizedForPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isApplicationAuthorizedForPlayback","navigatorTitle":[{"text":"applicationAuthorizedForPlayback","kind":"identifier"}],"url":"/documentation/avfoundation/avplayeritem/isapplicationauthorizedforplayback","kind":"symbol","abstract":[{"text":"A Boolean value that indicates whether the application can be used to play the content.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus":{"title":"contentAuthorizationRequestStatus","abstract":[{"type":"text","text":"The status of the most recent content authorization request."}],"role":"symbol","navigatorTitle":[{"text":"contentAuthorizationRequestStatus","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAuthorizationRequestStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVContentAuthorizationStatus","preciseIdentifier":"c:@E@AVContentAuthorizationStatus","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/contentauthorizationrequeststatus","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback":{"abstract":[{"text":"A Boolean value that indicates whether authorization is required to play the content.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuthorizationRequiredForPlayback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isAuthorizationRequiredForPlayback","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","type":"topic","url":"/documentation/avfoundation/avplayeritem/isauthorizationrequiredforplayback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"authorizationRequiredForPlayback"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown":{"url":"/documentation/avfoundation/avcontentauthorizationstatus/unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"AVContentAuthorizationUnknown","kind":"identifier"}],"title":"AVContentAuthorizationStatus.unknown","type":"topic","abstract":[{"text":"The content authorization content request hasn’t completed.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus":{"abstract":[{"text":"A value representing the status of a content authorization request.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVContentAuthorizationStatus","kind":"identifier"}],"title":"AVContentAuthorizationStatus","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","type":"topic","url":"/documentation/avfoundation/avcontentauthorizationstatus","role":"symbol","navigatorTitle":[{"text":"AVContentAuthorizationStatus","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:ScM","fragments":[{"kind":"attribute","text":"@globalActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainActor"}],"abstract":[{"type":"text","text":"A singleton actor whose executor is equivalent to the main dispatch queue."}],"type":"topic","title":"MainActor","url":"/documentation/Swift/MainActor","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()":{"abstract":[{"text":"Cancels the currently outstanding content authorization request.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelContentAuthorizationRequest"},{"kind":"text","text":"()"}],"title":"cancelContentAuthorizationRequest()","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()","type":"topic","url":"/documentation/avfoundation/avplayeritem/cancelcontentauthorizationrequest()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelContentAuthorizationRequest"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.7","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"contentAuthorizationRequestStatus","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"contentAuthorizationRequestStatus"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"],"title":"Managing Playback Authorization in macOS","anchor":"Managing-Playback-Authorization-in-macOS"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@AVContentAuthorizationStatus","kind":"typeIdentifier","text":"AVContentAuthorizationStatus","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentAuthorizationRequestStatus"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/title","value":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/title","value":"contentAuthorizedForPlayback"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/fragments","value":[{"text":"contentAuthorizedForPlayback","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/title","value":"applicationAuthorizedForPlayback","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/fragments","value":[{"kind":"identifier","text":"applicationAuthorizedForPlayback"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","value":"AVPlayerItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","value":[{"kind":"identifier","text":"AVPlayerItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/title","value":"contentAuthorizationRequestStatus","op":"replace"},{"value":[{"kind":"identifier","text":"contentAuthorizationRequestStatus"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/fragments"},{"value":"authorizationRequiredForPlayback","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/title"},{"value":[{"text":"authorizationRequiredForPlayback","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/fragments"},{"value":"AVContentAuthorizationUnknown","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/title"},{"value":[{"kind":"identifier","text":"AVContentAuthorizationUnknown"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/fragments"},{"value":"AVContentAuthorizationStatus","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/title"},{"value":[{"kind":"identifier","text":"AVContentAuthorizationStatus"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/fragments"},{"value":[{"text":"AVContentAuthorizationStatus","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/navigatorTitle"},{"value":"cancelContentAuthorizationRequest","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cancelContentAuthorizationRequest","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}