{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"abstract":[{"type":"text","text":"Creates a copy of the object with the specified zone."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy()"],"title":"Copying an Player Item","generated":true,"anchor":"Copying-an-Player-Item"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)AVPlayerItem(im)copyWithZone:","role":"symbol","title":"copy(with:)","modules":[{"name":"AVFoundation"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"4.0"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"4.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.7"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"},{"deprecated":false,"name":"watchOS","beta":false,"unavailable":false,"introducedAt":"1.0"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"? = nil) -> "},{"kind":"keyword","text":"Any"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The system ignores this parameter."}],"type":"paragraph"}],"name":"zone"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A copy of the original asset instance.","type":"text"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/copy(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/copy(with:)"]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy(with:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy(with:)":{"url":"/documentation/avfoundation/avplayeritem/copy(with:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy(with:)","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"text":"Creates a copy of the object with the specified zone.","type":"text"}],"kind":"symbol","type":"topic","title":"copy(with:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy()":{"abstract":[{"text":"Creates a copy of the object.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy()","type":"topic","title":"copy()","url":"/documentation/avfoundation/avplayeritem/copy()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"navigatorTitle":[{"text":"copy","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/s:10ObjectiveC6NSZoneV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"NSZone","kind":"identifier"}],"kind":"symbol","title":"NSZone","abstract":[{"text":"","type":"text"}],"url":"/documentation/objectivec/nszone","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC6NSZoneV"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"4.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"4.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.7","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"watchOS","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"copyWithZone:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]}},{"op":"add","path":"/topicSections","value":null},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"title":"Copying an Player Item","anchor":"Copying-an-Player-Item","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/copy()"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The system ignores this parameter."}]}],"name":"zone"}]},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A copy of the original asset instance."}]}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"value":"copyWithZone:","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1copy(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1copy(with:)/fragments","op":"replace"},{"value":"AVPlayerItem","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","op":"replace"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","op":"replace"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","op":"replace"},{"value":"copy","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1copy()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"copy","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1copy()/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}