{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"abstract":[{"type":"text","text":"A Boolean value that indicates whether the application can be used to play the content."}],"sections":[],"metadata":{"roleHeading":"Instance Property","extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"4.2","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"4.2","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.7","beta":false}],"title":"isApplicationAuthorizedForPlayback","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"applicationAuthorizedForPlayback"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isApplicationAuthorizedForPlayback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:objc(cs)AVPlayerItem(py)applicationAuthorizedForPlayback"},"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/isapplicationauthorizedforplayback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/isapplicationauthorizedforplayback"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isApplicationAuthorizedForPlayback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property reports whether or not the calling application is authorized to play the content associated with the item."}]},{"type":"paragraph","inlineContent":[{"text":"Application authorization is independent of content authorization (see ","type":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","isActive":true,"type":"reference"},{"text":") and that both must be granted in order for an application to be allowed to play protected content. Also, unlike content authorization, application authorization is not dependent on user credentials (that is, if ","type":"text"},{"code":"applicationAuthorizedForPlayback","type":"codeVoice"},{"text":" is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":", there are no means to obtain authorization).","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This property is not key-value observable.","type":"text"}]}]}],"seeAlsoSections":[{"generated":true,"title":"Managing Playback Authorization in macOS","anchor":"Managing-Playback-Authorization-in-macOS","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus":{"title":"contentAuthorizationRequestStatus","abstract":[{"type":"text","text":"The status of the most recent content authorization request."}],"role":"symbol","navigatorTitle":[{"text":"contentAuthorizationRequestStatus","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAuthorizationRequestStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVContentAuthorizationStatus","preciseIdentifier":"c:@E@AVContentAuthorizationStatus","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/contentauthorizationrequeststatus","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback":{"title":"isContentAuthorizedForPlayback","abstract":[{"type":"text","text":"A Boolean value that indicates whether the content has been authorized by the user."}],"role":"symbol","navigatorTitle":[{"text":"contentAuthorizedForPlayback","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContentAuthorizedForPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritem/iscontentauthorizedforplayback","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback":{"type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isApplicationAuthorizedForPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isApplicationAuthorizedForPlayback","navigatorTitle":[{"text":"applicationAuthorizedForPlayback","kind":"identifier"}],"url":"/documentation/avfoundation/avplayeritem/isapplicationauthorizedforplayback","kind":"symbol","abstract":[{"text":"A Boolean value that indicates whether the application can be used to play the content.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)":{"url":"/documentation/avfoundation/avplayeritem/requestcontentauthorizationasynchronously(withtimeoutinterval:completionhandler:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestContentAuthorizationAsynchronously","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTimeoutInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Presents the user the opportunity to authorize the content for playback."}],"title":"requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus":{"abstract":[{"text":"A value representing the status of a content authorization request.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVContentAuthorizationStatus","kind":"identifier"}],"title":"AVContentAuthorizationStatus","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","type":"topic","url":"/documentation/avfoundation/avcontentauthorizationstatus","role":"symbol","navigatorTitle":[{"text":"AVContentAuthorizationStatus","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()":{"abstract":[{"text":"Cancels the currently outstanding content authorization request.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelContentAuthorizationRequest"},{"kind":"text","text":"()"}],"title":"cancelContentAuthorizationRequest()","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()","type":"topic","url":"/documentation/avfoundation/avplayeritem/cancelcontentauthorizationrequest()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelContentAuthorizationRequest"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback":{"abstract":[{"text":"A Boolean value that indicates whether authorization is required to play the content.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuthorizationRequiredForPlayback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isAuthorizationRequiredForPlayback","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","type":"topic","url":"/documentation/avfoundation/avplayeritem/isauthorizationrequiredforplayback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"authorizationRequiredForPlayback"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.externally.resolved.symbol/s:ScM":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:ScM","fragments":[{"kind":"attribute","text":"@globalActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainActor"}],"abstract":[{"type":"text","text":"A singleton actor whose executor is equivalent to the main dispatch queue."}],"type":"topic","title":"MainActor","url":"/documentation/Swift/MainActor","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","kind":"symbol","url":"/documentation/swift/false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"type":"text","text":"A false value."}],"role":"symbol","title":"false"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false},{"unavailable":false,"name":"macOS","introducedAt":"10.7","beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"applicationAuthorizedForPlayback","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"applicationAuthorizedForPlayback"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"],"title":"Managing Playback Authorization in macOS","anchor":"Managing-Playback-Authorization-in-macOS","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isApplicationAuthorizedForPlayback"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationAuthorizedForPlayback"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"contentAuthorizationRequestStatus","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/title"},{"op":"replace","value":[{"text":"contentAuthorizationRequestStatus","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/fragments"},{"op":"replace","value":"contentAuthorizedForPlayback","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/title"},{"op":"replace","value":[{"text":"contentAuthorizedForPlayback","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/fragments"},{"op":"replace","value":"applicationAuthorizedForPlayback","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/title"},{"op":"replace","value":[{"kind":"identifier","text":"applicationAuthorizedForPlayback"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/fragments"},{"op":"replace","value":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/fragments"},{"op":"replace","value":"AVContentAuthorizationStatus","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVContentAuthorizationStatus"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/fragments"},{"value":[{"text":"AVContentAuthorizationStatus","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/navigatorTitle"},{"value":"cancelContentAuthorizationRequest","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cancelContentAuthorizationRequest","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/fragments"},{"value":"authorizationRequiredForPlayback","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/title"},{"value":[{"kind":"identifier","text":"authorizationRequiredForPlayback"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/fragments"},{"value":"AVPlayerItem","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}