{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackBufferEmpty","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether playback has consumed all buffered media and that playback will stall or end."}],"seeAlsoSections":[{"anchor":"Determining-Buffering-Status","title":"Determining Buffering Status","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)AVPlayerItem(py)playbackBufferEmpty","platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false}],"title":"isPlaybackBufferEmpty","symbolKind":"property","navigatorTitle":[{"text":"playbackBufferEmpty","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackBufferEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}],"role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/isplaybackbufferempty"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/isplaybackbufferempty"]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp":{"url":"/documentation/avfoundation/avplayeritem/isplaybacklikelytokeepup","abstract":[{"text":"A Boolean value that indicates whether the item will likely play through without stalling.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp","title":"isPlaybackLikelyToKeepUp","navigatorTitle":[{"kind":"identifier","text":"playbackLikelyToKeepUp"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackLikelyToKeepUp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty":{"url":"/documentation/avfoundation/avplayeritem/isplaybackbufferempty","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackBufferEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","title":"isPlaybackBufferEmpty","abstract":[{"type":"text","text":"A Boolean value that indicates whether playback has consumed all buffered media and that playback will stall or end."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty","navigatorTitle":[{"kind":"identifier","text":"playbackBufferEmpty"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull":{"title":"isPlaybackBufferFull","type":"topic","navigatorTitle":[{"text":"playbackBufferFull","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackBufferFull","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the internal media buffer is full and that further I/O is suspended."}],"kind":"symbol","url":"/documentation/avfoundation/avplayeritem/isplaybackbufferfull"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"playbackBufferEmpty"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"playbackBufferEmpty"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"path":"/hierarchy","op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull"],"generated":true,"title":"Determining Buffering Status","anchor":"Determining-Buffering-Status"}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isPlaybackBufferEmpty"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackBufferEmpty"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackLikelyToKeepUp/title","op":"replace","value":"playbackLikelyToKeepUp"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackLikelyToKeepUp/fragments","op":"replace","value":[{"text":"playbackLikelyToKeepUp","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferEmpty/title","op":"replace","value":"playbackBufferEmpty"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferEmpty/fragments","op":"replace","value":[{"kind":"identifier","text":"playbackBufferEmpty"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","op":"replace","value":"AVPlayerItem"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","op":"replace","value":[{"kind":"identifier","text":"AVPlayerItem"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVPlayerItem"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferFull/title","op":"replace","value":"playbackBufferFull"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferFull/fragments","op":"replace","value":[{"text":"playbackBufferFull","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}