{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackLikelyToKeepUp","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"This property communicates a prediction of playability. Factors considered in this prediction include I/O throughput and media decode performance. It is possible for ","type":"text"},{"type":"codeVoice","code":"playbackLikelyToKeepUp"},{"text":" to indicate ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"text":" while the property ","type":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull","type":"reference","isActive":true},{"text":" indicates ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":". In this event the playback buffer has reached capacity but there isn’t the statistical data to support a prediction that playback is likely to keep up in the future. It is up to you to decide whether to continue media playback.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty"],"generated":true,"anchor":"Determining-Buffering-Status","title":"Determining Buffering Status"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the item will likely play through without stalling."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp"},"variants":[{"paths":["/documentation/avfoundation/avplayeritem/isplaybacklikelytokeepup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avplayeritem/isplaybacklikelytokeepup"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"metadata":{"navigatorTitle":[{"text":"playbackLikelyToKeepUp","kind":"identifier"}],"extendedModule":"AVFoundation","externalID":"c:objc(cs)AVPlayerItem(py)playbackLikelyToKeepUp","title":"isPlaybackLikelyToKeepUp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackLikelyToKeepUp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"AVFoundation"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp":{"url":"/documentation/avfoundation/avplayeritem/isplaybacklikelytokeepup","abstract":[{"text":"A Boolean value that indicates whether the item will likely play through without stalling.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackLikelyToKeepUp","title":"isPlaybackLikelyToKeepUp","navigatorTitle":[{"kind":"identifier","text":"playbackLikelyToKeepUp"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackLikelyToKeepUp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/true","abstract":[{"text":"A true value.","type":"text"}],"type":"topic","title":"true","url":"/documentation/swift/true","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","kind":"symbol","url":"/documentation/swift/false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"type":"text","text":"A false value."}],"role":"symbol","title":"false"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty":{"url":"/documentation/avfoundation/avplayeritem/isplaybackbufferempty","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackBufferEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","title":"isPlaybackBufferEmpty","abstract":[{"type":"text","text":"A Boolean value that indicates whether playback has consumed all buffered media and that playback will stall or end."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty","navigatorTitle":[{"kind":"identifier","text":"playbackBufferEmpty"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull":{"title":"isPlaybackBufferFull","type":"topic","navigatorTitle":[{"text":"playbackBufferFull","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaybackBufferFull","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the internal media buffer is full and that further I/O is suspended."}],"kind":"symbol","url":"/documentation/avfoundation/avplayeritem/isplaybackbufferfull"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"playbackLikelyToKeepUp","path":"/metadata/title"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"playbackLikelyToKeepUp","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferFull","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isPlaybackBufferEmpty"],"generated":true,"title":"Determining Buffering Status","anchor":"Determining-Buffering-Status"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isPlaybackLikelyToKeepUp","kind":"identifier"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"playbackLikelyToKeepUp","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace"},{"value":"playbackLikelyToKeepUp","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackLikelyToKeepUp/title"},{"value":[{"kind":"identifier","text":"playbackLikelyToKeepUp"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackLikelyToKeepUp/fragments"},{"value":"playbackBufferEmpty","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferEmpty/title"},{"value":[{"kind":"identifier","text":"playbackBufferEmpty"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferEmpty/fragments"},{"value":"playbackBufferFull","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferFull/title"},{"value":[{"kind":"identifier","text":"playbackBufferFull"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isPlaybackBufferFull/fragments"},{"value":"AVPlayerItem","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}