{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithURL:","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/playeritemwithurl:"]}],"seeAlsoSections":[{"anchor":"Creating-a-Player-Item","generated":true,"title":"Creating a Player Item","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(url:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:)-87rjl","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:automaticallyLoadedAssetKeys:","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:automaticallyLoadedAssetKeys:)-8x4"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerItemWithURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"URL"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"URL","content":[{"inlineContent":[{"type":"text","text":"A URL identifying the media resource to be played."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"A new player item, prepared to use "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method immediately returns the item, but with the status "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/unknown"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Associating the player item with an "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer","isActive":true,"type":"reference"},{"type":"text","text":" immediately begins enqueuing its media and preparing it for playback. If the URL contains valid data that can be used by the player item, its status later changes to "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/readyToPlay","isActive":true,"type":"reference"},{"type":"text","text":". If the URL contains no valid data or otherwise can’t be used by the player item, its status later changes to "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/failed","isActive":true,"type":"reference"},{"type":"text","text":". You can determine the nature of the failure by querying the player item’s "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/error","isActive":true,"type":"reference"},{"type":"text","text":" property."}]}],"kind":"content"}],"abstract":[{"text":"Returns a new player item with a specified URL.","type":"text"}],"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"playerItemWithURL:"}],"navigatorTitle":[{"kind":"identifier","text":"playerItemWithURL:"}],"platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"4.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"4.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.7","unavailable":false},{"introducedAt":"9.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"watchOS","beta":false}],"title":"playerItemWithURL:","role":"symbol","symbolKind":"method","modules":[{"name":"AVFoundation"}],"externalID":"c:objc(cs)AVPlayerItem(cm)playerItemWithURL:"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/readyToPlay":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readyToPlay","kind":"identifier"}],"url":"/documentation/avfoundation/avplayeritem/status-swift.enum/readytoplay","kind":"symbol","type":"topic","abstract":[{"text":"The item is ready to play.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/readyToPlay","title":"AVPlayerItem.Status.readyToPlay","navigatorTitle":[{"text":"AVPlayerItemStatusReadyToPlay","kind":"identifier"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/unknown":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"url":"/documentation/avfoundation/avplayeritem/status-swift.enum/unknown","kind":"symbol","type":"topic","abstract":[{"text":"The item’s status is unknown.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/unknown","title":"AVPlayerItem.Status.unknown","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemStatusUnknown"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:)-87rjl":{"type":"topic","abstract":[{"type":"text","text":"Creates a player item for a specified asset."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:)-87rjl","navigatorTitle":[{"kind":"identifier","text":"initWithAsset:"}],"url":"/documentation/avfoundation/avplayeritem/init(asset:)-87rjl","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAsset","text":"AVAsset"},{"kind":"text","text":")"}],"role":"symbol","title":"init(asset:)","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/failed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"url":"/documentation/avfoundation/avplayeritem/status-swift.enum/failed","kind":"symbol","type":"topic","abstract":[{"text":"The item no longer plays due to an error.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/Status-swift.enum/failed","title":"AVPlayerItem.Status.failed","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemStatusFailed"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSURL"}],"abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","title":"NSURL","url":"/documentation/foundation/nsurl","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayer","kind":"identifier"}],"navigatorTitle":[{"text":"AVPlayer","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}],"type":"topic","title":"AVPlayer","url":"/documentation/avfoundation/avplayer","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithURL:":{"abstract":[{"type":"text","text":"Returns a new player item with a specified URL."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithURL:","type":"topic","title":"playerItemWithURL:","url":"/documentation/avfoundation/avplayeritem/playeritemwithurl:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"playerItemWithURL:"}],"navigatorTitle":[{"kind":"identifier","text":"playerItemWithURL:"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:automaticallyLoadedAssetKeys:":{"url":"/documentation/avfoundation/avplayeritem/playeritemwithasset:automaticallyloadedassetkeys:","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:automaticallyLoadedAssetKeys:","navigatorTitle":[{"kind":"identifier","text":"playerItemWithAsset:automaticallyLoadedAssetKeys:"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"playerItemWithAsset:automaticallyLoadedAssetKeys:"}],"abstract":[{"type":"text","text":"Creates a player item with the specified asset and the asset keys to automatically load."}],"kind":"symbol","type":"topic","title":"playerItemWithAsset:automaticallyLoadedAssetKeys:","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/playerItemWithAsset:","kind":"symbol","title":"playerItemWithAsset:","type":"topic","navigatorTitle":[{"text":"playerItemWithAsset:","kind":"identifier"}],"abstract":[{"text":"Returns a new player item for a specified asset.","type":"text"}],"url":"/documentation/avfoundation/avplayeritem/playeritemwithasset:","fragments":[{"text":"+ ","kind":"text"},{"text":"playerItemWithAsset:","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:automaticallyLoadedAssetKeys:)-8x4":{"title":"init(asset:automaticallyLoadedAssetKeys:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAsset","kind":"typeIdentifier","text":"AVAsset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automaticallyLoadedAssetKeys"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?)"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(asset:automaticallyLoadedAssetKeys:)-8x4","abstract":[{"type":"text","text":"Creates a player item with the specified asset and the asset keys to automatically load."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAsset:automaticallyLoadedAssetKeys:"}],"url":"/documentation/avfoundation/avplayeritem/init(asset:automaticallyloadedassetkeys:)-8x4"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(url:)":{"title":"init(url:)","role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/init(url:)","abstract":[{"type":"text","text":"Creates a player item with a specified URL."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithURL:"}],"url":"/documentation/avfoundation/avplayeritem/init(url:)"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/error":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/error","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","url":"/documentation/avfoundation/avplayeritem/error","kind":"symbol","role":"symbol","title":"error","navigatorTitle":[{"text":"error","kind":"identifier"}],"abstract":[{"text":"The error that caused the player item to fail.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AVPlayerItemStatusReadyToPlay","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1readyToPlay/title"},{"value":[{"text":"AVPlayerItemStatusReadyToPlay","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1readyToPlay/fragments"},{"value":"AVPlayerItemStatusUnknown","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1unknown/title"},{"value":[{"text":"AVPlayerItemStatusUnknown","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1unknown/fragments"},{"value":"initWithAsset:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(asset:)-87rjl/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAsset:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(asset:)-87rjl/fragments"},{"value":"AVPlayerItemStatusFailed","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1failed/title"},{"value":[{"text":"AVPlayerItemStatusFailed","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1Status-swift.enum~1failed/fragments"},{"value":[{"text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract"},{"value":"AVPlayer","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/title"},{"value":[{"text":"AVPlayer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/fragments"},{"value":[{"kind":"identifier","text":"AVPlayer"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/navigatorTitle"},{"value":"initWithAsset:automaticallyLoadedAssetKeys:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(asset:automaticallyLoadedAssetKeys:)-8x4/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(asset:automaticallyLoadedAssetKeys:)-8x4/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAsset:automaticallyLoadedAssetKeys:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(url:)/title","value":"initWithURL:"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1init(url:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURL:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","value":"AVPlayerItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","value":[{"text":"AVPlayerItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","value":[{"text":"AVPlayerItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1error/title","value":"error"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1error/fragments","value":[{"text":"error","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}