{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"requestPlaybackRestrictionsAuthorization:"}],"platforms":[{"name":"tvOS","beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false}],"symbolKind":"method","extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}],"title":"requestPlaybackRestrictionsAuthorization(_:)","role":"symbol","externalID":"c:objc(cs)AVPlayerItem(im)requestPlaybackRestrictionsAuthorization:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPlaybackRestrictionsAuthorization"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestPlaybackRestrictionsAuthorization(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/requestplaybackrestrictionsauthorization(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/requestplaybackrestrictionsauthorization(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestPlaybackRestrictionsAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]},{"platforms":["tvOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPlaybackRestrictionsAuthorization"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback the system invokes after it makes a determination of parental restrictions."}]},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"A Boolean value that indicates whether the system authorizes the app to play an item.","type":"text"}]}]},"term":{"inlineContent":[{"code":"isAuthorized","type":"codeVoice"}]}},{"definition":{"content":[{"inlineContent":[{"type":"text","text":"An optional error that contains error details if the system encountered an error."}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"codeVoice","code":"error"}]}}]}]}]}],"seeAlsoSections":[{"anchor":"Requesting-Playback-Authorization-in-tvOS","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelPlaybackRestrictionsAuthorizationRequest()"],"title":"Requesting Playback Authorization in tvOS"}],"abstract":[{"type":"text","text":"Determines whether this item is subject to parental restrictions, and, if so, prompts the user to enter the restrictions passcode."}],"kind":"symbol","sections":[],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s8SendableP","text":"Sendable"}],"type":"topic","url":"/documentation/Swift/Error","title":"Error","abstract":[{"text":"A type representing an error value that can be thrown.","type":"text"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"role":"symbol","title":"NSError","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","type":"topic","kind":"symbol","url":"/documentation/foundation/nserror"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.externally.resolved.symbol/s:s4Voida":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","type":"topic","title":"Void","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}],"abstract":[{"text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.","type":"text"}],"url":"/documentation/Swift/Void"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelPlaybackRestrictionsAuthorizationRequest()":{"abstract":[{"type":"text","text":"Cancels a pending authorization request and dismisses the passcode entry, if displayed."}],"title":"cancelPlaybackRestrictionsAuthorizationRequest()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelPlaybackRestrictionsAuthorizationRequest","kind":"identifier"},{"text":"()","kind":"text"}],"url":"/documentation/avfoundation/avplayeritem/cancelplaybackrestrictionsauthorizationrequest()","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelPlaybackRestrictionsAuthorizationRequest()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"cancelPlaybackRestrictionsAuthorizationRequest","kind":"identifier"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:ScM","fragments":[{"kind":"attribute","text":"@globalActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainActor"}],"abstract":[{"type":"text","text":"A singleton actor whose executor is equivalent to the main dispatch queue."}],"type":"topic","title":"MainActor","url":"/documentation/Swift/MainActor","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestPlaybackRestrictionsAuthorization(_:)":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestPlaybackRestrictionsAuthorization(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestPlaybackRestrictionsAuthorization","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"requestPlaybackRestrictionsAuthorization:","kind":"identifier"}],"title":"requestPlaybackRestrictionsAuthorization(_:)","abstract":[{"text":"Determines whether this item is subject to parental restrictions, and, if so, prompts the user to enter the restrictions passcode.","type":"text"}],"url":"/documentation/avfoundation/avplayeritem/requestplaybackrestrictionsauthorization(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"introducedAt":"13.0","name":"tvOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"requestPlaybackRestrictionsAuthorization:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestPlaybackRestrictionsAuthorization:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelPlaybackRestrictionsAuthorizationRequest()"],"generated":true,"anchor":"Requesting-Playback-Authorization-in-tvOS","title":"Requesting Playback Authorization in tvOS"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"requestPlaybackRestrictionsAuthorization:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isAuthorized","kind":"internalParam"},{"text":", ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback the system invokes after it makes a determination of parental restrictions."}]},{"type":"termList","items":[{"term":{"inlineContent":[{"type":"codeVoice","code":"isAuthorized"}]},"definition":{"content":[{"inlineContent":[{"text":"A Boolean value that indicates whether the system authorizes the app to play an item.","type":"text"}],"type":"paragraph"}]}},{"term":{"inlineContent":[{"type":"codeVoice","code":"error"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional error that contains error details if the system encountered an error.","type":"text"}]}]}}]}]}],"kind":"parameters"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title","value":"AVPlayerItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments","value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle","value":[{"kind":"identifier","text":"AVPlayerItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelPlaybackRestrictionsAuthorizationRequest()/title","value":"cancelPlaybackRestrictionsAuthorizationRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelPlaybackRestrictionsAuthorizationRequest()/fragments","value":[{"text":"- ","kind":"text"},{"text":"cancelPlaybackRestrictionsAuthorizationRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestPlaybackRestrictionsAuthorization(_:)/title","value":"requestPlaybackRestrictionsAuthorization:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestPlaybackRestrictionsAuthorization(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestPlaybackRestrictionsAuthorization:","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}