{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoComposition","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/customVideoCompositor"],"title":"Configuring Video Compositing","anchor":"Configuring-Video-Compositing","generated":true}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/seekingWaitsForVideoCompositionRendering","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"By default, item timing is updated as quickly as possible during seeking. Specifically, the item does not wait for new frames to be rendered when seeking during normal playback. In most situations, the latency between the completion of a seek operation and the display of a video frame at the new time is negligible. However, when video compositions are in use, the processing of video may introduce noticeable latency. Setting the value of this property to "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"type":"text","text":" causes the item’s timing to be updated only after the corresponding video frame has been displayed. For example, this allows an AVSynchronizedLayer object associated with the item to remain in sync with the displayed video."}],"type":"paragraph"},{"inlineContent":[{"text":"This property has no effect on items whose ","type":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoComposition","isActive":true,"type":"reference"},{"text":" property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A Boolean value that indicates whether the item’s timing follows the displayed video frame when seeking with a video composition."}],"metadata":{"platforms":[{"name":"iOS","introducedAt":"6.0","deprecated":false,"beta":false,"unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"6.0","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.9","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0","unavailable":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false}],"title":"seekingWaitsForVideoCompositionRendering","modules":[{"name":"AVFoundation"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"}],"extendedModule":"AVFoundation","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:objc(cs)AVPlayerItem(py)seekingWaitsForVideoCompositionRendering"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/seekingwaitsforvideocompositionrendering"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/seekingwaitsforvideocompositionrendering"]}],"kind":"symbol","references":{"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/seekingWaitsForVideoCompositionRendering":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekingWaitsForVideoCompositionRendering","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"A Boolean value that indicates whether the item’s timing follows the displayed video frame when seeking with a video composition.","type":"text"}],"type":"topic","title":"seekingWaitsForVideoCompositionRendering","url":"/documentation/avfoundation/avplayeritem/seekingwaitsforvideocompositionrendering","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/seekingWaitsForVideoCompositionRendering","navigatorTitle":[{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/true","abstract":[{"text":"A true value.","type":"text"}],"type":"topic","title":"true","url":"/documentation/swift/true","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoComposition":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoComposition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVVideoComposition","text":"AVVideoComposition"},{"kind":"text","text":"?"}],"abstract":[{"text":"The video composition settings to be applied during playback.","type":"text"}],"type":"topic","title":"videoComposition","url":"/documentation/avfoundation/avplayeritem/videocomposition","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoComposition","navigatorTitle":[{"kind":"identifier","text":"videoComposition"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/customVideoCompositor":{"title":"customVideoCompositor","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/customVideoCompositor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customVideoCompositor"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)AVVideoCompositing","kind":"typeIdentifier","text":"AVVideoCompositing"},{"kind":"text","text":")?"}],"url":"/documentation/avfoundation/avplayeritem/customvideocompositor","type":"topic","abstract":[{"type":"text","text":"The custom video compositor."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customVideoCompositor"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"6.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"6.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.9","name":"macOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0","name":"tvOS"},{"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"seekingWaitsForVideoCompositionRendering","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Configuring Video Compositing","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoComposition","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/customVideoCompositor"],"anchor":"Configuring-Video-Compositing"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"seekingWaitsForVideoCompositionRendering","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"seekingWaitsForVideoCompositionRendering","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1seekingWaitsForVideoCompositionRendering/title"},{"value":[{"kind":"identifier","text":"seekingWaitsForVideoCompositionRendering"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1seekingWaitsForVideoCompositionRendering/fragments"},{"value":"videoComposition","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1videoComposition/title"},{"value":[{"kind":"identifier","text":"videoComposition"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1videoComposition/fragments"},{"value":"AVPlayerItem","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments"},{"value":[{"text":"AVPlayerItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle"},{"value":"customVideoCompositor","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1customVideoCompositor/title"},{"value":[{"kind":"identifier","text":"customVideoCompositor"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1customVideoCompositor/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}