{"metadata":{"role":"symbol","navigatorTitle":[{"text":"textStyleRules","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"6.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"6.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.9","name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"9.0","name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}],"title":"textStyleRules","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textStyleRules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AVTextStyleRule","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVTextStyleRule"},{"text":"]?","kind":"text"}],"externalID":"c:objc(cs)AVPlayerItem(py)textStyleRules","extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritem/textstylerules"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritem/textstylerules"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/textStyleRules"},"kind":"symbol","abstract":[{"type":"text","text":"An array of text style rules that specify the formatting and presentation of Web Video Text Tracks (WebVTT) subtitles."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textStyleRules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AVTextStyleRule","kind":"typeIdentifier","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVTextStyleRule","preciseIdentifier":"c:objc(cs)AVTextStyleRule"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Text style rules apply only to WebVTT subtitles. They don’t apply to other subtitle formats and legible text.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVTextStyleRule"],"title":"Accessing Text Style Rules","generated":true,"anchor":"Accessing-Text-Style-Rules"}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/textStyleRules":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/textStyleRules","abstract":[{"type":"text","text":"An array of text style rules that specify the formatting and presentation of Web Video Text Tracks (WebVTT) subtitles."}],"title":"textStyleRules","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textStyleRules","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVTextStyleRule","text":"AVTextStyleRule","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","role":"symbol","url":"/documentation/avfoundation/avplayeritem/textstylerules","navigatorTitle":[{"text":"textStyleRules","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVTextStyleRule":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVTextStyleRule"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An object that represents the text styling rules to apply to a media item’s textual content."}],"title":"AVTextStyleRule","type":"topic","url":"/documentation/avfoundation/avtextstylerule","navigatorTitle":[{"kind":"identifier","text":"AVTextStyleRule"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVTextStyleRule"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"6.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"6.0"},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"introducedAt":"10.9","beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"textStyleRules","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"textStyleRules"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Accessing-Text-Style-Rules","title":"Accessing Text Style Rules","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVTextStyleRule"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<AVTextStyleRule *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"textStyleRules","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"textStyleRules","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1textStyleRules/title"},{"value":[{"text":"textStyleRules","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1textStyleRules/fragments"},{"value":"AVPlayerItem","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVPlayerItem"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVPlayerItem"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle"},{"op":"replace","value":"AVTextStyleRule","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVTextStyleRule/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVTextStyleRule"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVTextStyleRule/fragments"},{"op":"replace","value":[{"text":"AVTextStyleRule","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVTextStyleRule/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}