{
  "abstract": [
    {
      "text": "A relative fan speed setting.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/relativeFanSpeedSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSetClimateSettingsInCarIntent(py)relativeFanSpeedSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "relativeFanSpeedSetting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INRelativeSetting",
        "text": "INRelativeSetting"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "relativeFanSpeedSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetClimateSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetClimateSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetClimateSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetClimateSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "relativeFanSpeedSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "relativeFanSpeedSetting"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INRelativeSetting",
              "text": "INRelativeSetting"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to adjust the fan speed to the next or previous setting. The value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the user modified a different climate control setting.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting": {
      "abstract": [
        {
          "text": "Constants indicating relative settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelativeSetting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeSetting"
        }
      ],
      "role": "symbol",
      "title": "INRelativeSetting",
      "type": "topic",
      "url": "/documentation/intents/inrelativesetting"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown": {
      "abstract": [
        {
          "text": "An unknown setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeSettingUnknown"
        }
      ],
      "role": "symbol",
      "title": "INRelativeSetting.unknown",
      "type": "topic",
      "url": "/documentation/intents/inrelativesetting/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the climate settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-3bu9e": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to turn on the cabin fan system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableFan"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-3bu9e",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableFan",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/enablefan-3bu9e"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-5srs9": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to turn on the cabin fan system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableFan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-5srs9",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableFan",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/enablefan-5srs9"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-4c1rr": {
      "abstract": [
        {
          "text": "An integer value indicating the desired fan speed position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "fanSpeedIndex"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-4c1rr",
      "kind": "symbol",
      "role": "symbol",
      "title": "fanSpeedIndex",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/fanspeedindex-4c1rr"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-wz49": {
      "abstract": [
        {
          "text": "An integer value indicating the desired fan speed position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fanSpeedIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-wz49",
      "kind": "symbol",
      "role": "symbol",
      "title": "fanSpeedIndex",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/fanspeedindex-wz49"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-7i2hq": {
      "abstract": [
        {
          "text": "A floating-point value indicating the requested fan speed specified as a percentage of the maximum speed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fanSpeedPercentage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-7i2hq",
      "kind": "symbol",
      "role": "symbol",
      "title": "fanSpeedPercentage",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/fanspeedpercentage-7i2hq"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-ep0u": {
      "abstract": [
        {
          "text": "A floating-point value indicating the requested fan speed specified as a percentage of the maximum speed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "fanSpeedPercentage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-ep0u",
      "kind": "symbol",
      "role": "symbol",
      "title": "fanSpeedPercentage",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/fanspeedpercentage-ep0u"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/relativeFanSpeedSetting": {
      "abstract": [
        {
          "text": "A relative fan speed setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeFanSpeedSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRelativeSetting",
          "text": "INRelativeSetting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/relativeFanSpeedSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relativeFanSpeedSetting"
        }
      ],
      "role": "symbol",
      "title": "relativeFanSpeedSetting",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent/relativefanspeedsetting"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Fan-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-5srs9",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-wz49",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-7i2hq"
      ],
      "title": "Getting the Fan Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "relativeFanSpeedSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeFanSpeedSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Fan-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/enableFan-3bu9e",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedIndex-4c1rr",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent/fanSpeedPercentage-ep0u"
              ],
              "title": "Getting the Fan Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INRelativeSetting",
                    "text": "INRelativeSetting"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "relativeFanSpeedSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INRelativeSetting",
                    "text": "INRelativeSetting"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "relativeFanSpeedSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting~1unknown/title",
          "value": "INRelativeSettingUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSettingUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/title",
          "value": "INSetClimateSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent~1relativeFanSpeedSetting/title",
          "value": "relativeFanSpeedSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent~1relativeFanSpeedSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeFanSpeedSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/title",
          "value": "INRelativeSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetclimatesettingsincarintent/relativefanspeedsetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetclimatesettingsincarintent/relativefanspeedsetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
