{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute/mAttributeID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothSDPServiceAttribute@mAttributeID",
    "fragments": [
      {
        "kind": "identifier",
        "text": "mAttributeID"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mAttributeID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Variable",
    "symbolKind": "ivar",
    "title": "mAttributeID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothSDPServiceAttributeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothSDPServiceAttributeID",
              "text": "BluetoothSDPServiceAttributeID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mAttributeID"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothSDPServiceAttributeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothSDPServiceAttributeID"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothSDPServiceAttributeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothSDPServiceAttributeID"
        }
      ],
      "role": "symbol",
      "title": "BluetoothSDPServiceAttributeID",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothsdpserviceattributeid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute": {
      "abstract": [
        {
          "text": "IOBluetoothSDPServiceAttribute represents a single SDP service attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPServiceAttribute"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPServiceAttribute"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothSDPServiceAttribute",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothsdpserviceattribute"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute/mAttributeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mAttributeID"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPServiceAttribute/mAttributeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "mAttributeID",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothsdpserviceattribute/mattributeid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothSDPServiceAttributeID/title",
          "value": "BluetoothSDPServiceAttributeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothSDPServiceAttributeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothSDPServiceAttributeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothSDPServiceAttributeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothSDPServiceAttributeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPServiceAttribute/title",
          "value": "IOBluetoothSDPServiceAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPServiceAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPServiceAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPServiceAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPServiceAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothsdpserviceattribute/mattributeid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
