{
  "abstract": [
    {
      "text": "A category sample type for recording a mindful session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKCategoryTypeIdentifierMindfulSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mindfulSession"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
        "text": "HKCategoryTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryTypeIdentifierMindfulSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "mindfulSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mindfulSession"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue/notApplicable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value with these samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAppleSleepingBreathingDisturbancesClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleSleepingBreathingDisturbancesClassification"
        }
      ],
      "role": "symbol",
      "title": "HKAppleSleepingBreathingDisturbancesClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplesleepingbreathingdisturbancesclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassificationForQuantity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleSleepingBreathingDisturbancesClassificationForQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassificationForQuantity",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleSleepingBreathingDisturbancesClassificationForQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplesleepingbreathingdisturbancesclassificationforquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample": {
      "abstract": [
        {
          "text": "A sample with values from a short list of possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategorySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategorySample"
        }
      ],
      "role": "symbol",
      "title": "HKCategorySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain a value from a small set of possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for creating category types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession": {
      "abstract": [
        {
          "text": "A category sample type for recording a mindful session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mindfulSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierMindfulSession"
        }
      ],
      "role": "symbol",
      "title": "mindfulSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/mindfulsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis": {
      "abstract": [
        {
          "text": "A category sample type for sleep analysis information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepAnalysis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierSleepAnalysis"
        }
      ],
      "role": "symbol",
      "title": "sleepAnalysis",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/sleepanalysis"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue": {
      "abstract": [
        {
          "text": "Categories that are undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValue"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValue"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValue",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalue"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue/notApplicable": {
      "abstract": [
        {
          "text": "A category value for types that don’t have a defined value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApplicable"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue/notApplicable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueNotApplicable"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValue.notApplicable",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalue/notapplicable"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysisAsleepValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAsleepValues"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysisAsleepValues",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysisAsleepValues",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysisasleepvalues"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingWristTemperature": {
      "abstract": [
        {
          "text": "A quantity sample type that records the wrist temperature during sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleSleepingWristTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingWristTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierAppleSleepingWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "appleSleepingWristTemperature",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/applesleepingwristtemperature"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Mindfulness-and-sleep",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingWristTemperature",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassification"
      ],
      "title": "Mindfulness and sleep"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryTypeIdentifierMindfulSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierMindfulSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Mindfulness-and-sleep",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysisAsleepValues",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingWristTemperature",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassificationForQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleSleepingBreathingDisturbancesClassification"
              ],
              "title": "Mindfulness and sleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
                    "text": "HKCategoryTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKCategoryTypeIdentifierMindfulSession"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleSleepingBreathingDisturbancesClassification/title",
          "value": "HKAppleSleepingBreathingDisturbancesClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleSleepingBreathingDisturbancesClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleSleepingBreathingDisturbancesClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleSleepingBreathingDisturbancesClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleSleepingBreathingDisturbancesClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/title",
          "value": "HKCategoryValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepAnalysis/title",
          "value": "HKCategoryTypeIdentifierSleepAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1appleSleepingWristTemperature/title",
          "value": "HKQuantityTypeIdentifierAppleSleepingWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1appleSleepingWristTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierAppleSleepingWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/title",
          "value": "HKCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue~1notApplicable/title",
          "value": "HKCategoryValueNotApplicable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue~1notApplicable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueNotApplicable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1mindfulSession/title",
          "value": "HKCategoryTypeIdentifierMindfulSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1mindfulSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierMindfulSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/title",
          "value": "HKCategoryTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategorySample/title",
          "value": "HKCategorySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategorySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategorySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategorySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategorySample"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategorytypeidentifier/mindfulsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategorytypeidentifier/mindfulsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
