{
  "abstract": [
    {
      "text": "A string constant that serves as a dictionary key identifying an element’s horizontal size class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/horizontalSizeClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:@XCUIElementAttributeNameHorizontalSizeClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "horizontalSizeClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUIElement",
        "text": "XCUIElement"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@XCUIElementAttributeName",
        "text": "AttributeName"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIElementAttributeNameHorizontalSizeClass"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "horizontalSizeClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "horizontalSizeClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElement",
              "text": "XCUIElement"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@XCUIElementAttributeName",
              "text": "AttributeName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName": {
      "abstract": [
        {
          "text": "A set of string constants that serves as keys for storing element attributes in a dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.AttributeName",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/children": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameChildren"
        }
      ],
      "role": "symbol",
      "title": "children",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/children"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/elementType": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/elementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameElementType"
        }
      ],
      "role": "symbol",
      "title": "elementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/enabled": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying whether an element is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameEnabled"
        }
      ],
      "role": "symbol",
      "title": "enabled",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/enabled"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/frame": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameFrame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/frame"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/hasFocus": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying whether an element has focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasFocus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/hasFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameHasFocus"
        }
      ],
      "role": "symbol",
      "title": "hasFocus",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/hasfocus"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/horizontalSizeClass": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s horizontal size class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalSizeClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/horizontalSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameHorizontalSizeClass"
        }
      ],
      "role": "symbol",
      "title": "horizontalSizeClass",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/horizontalsizeclass"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/identifier": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameIdentifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/identifier"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/label": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameLabel"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/label"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/placeholderValue": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s placeholder value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/placeholderValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNamePlaceholderValue"
        }
      ],
      "role": "symbol",
      "title": "placeholderValue",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/placeholdervalue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/selected": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying whether an element is selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/selected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameSelected"
        }
      ],
      "role": "symbol",
      "title": "selected",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/selected"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/title": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameTitle"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/title"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/value": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameValue"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/value"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/verticalSizeClass": {
      "abstract": [
        {
          "text": "A string constant that serves as a dictionary key identifying an element’s vertical size class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalSizeClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIElementAttributeName",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/verticalSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributeNameVerticalSizeClass"
        }
      ],
      "role": "symbol",
      "title": "verticalSizeClass",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/attributename/verticalsizeclass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/children",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/elementType",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/enabled",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/frame",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/hasFocus",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/identifier",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/label",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/placeholderValue",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/selected",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/title",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/value",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/verticalSizeClass"
      ],
      "title": "Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIElementAttributeNameHorizontalSizeClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameHorizontalSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/children",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/elementType",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/enabled",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/frame",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/hasFocus",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/identifier",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/label",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/placeholderValue",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/selected",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/title",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/value",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName/verticalSizeClass"
              ],
              "title": "Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/AttributeName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@XCUIElementAttributeName",
                    "text": "XCUIElementAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIElementAttributeNameHorizontalSizeClass"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1frame/title",
          "value": "XCUIElementAttributeNameFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1identifier/title",
          "value": "XCUIElementAttributeNameIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1horizontalSizeClass/title",
          "value": "XCUIElementAttributeNameHorizontalSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1horizontalSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameHorizontalSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1enabled/title",
          "value": "XCUIElementAttributeNameEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1verticalSizeClass/title",
          "value": "XCUIElementAttributeNameVerticalSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1verticalSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameVerticalSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName/title",
          "value": "XCUIElementAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1value/title",
          "value": "XCUIElementAttributeNameValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1elementType/title",
          "value": "XCUIElementAttributeNameElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1elementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1children/title",
          "value": "XCUIElementAttributeNameChildren"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameChildren"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1selected/title",
          "value": "XCUIElementAttributeNameSelected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1selected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameSelected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1hasFocus/title",
          "value": "XCUIElementAttributeNameHasFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1hasFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameHasFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1label/title",
          "value": "XCUIElementAttributeNameLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1placeholderValue/title",
          "value": "XCUIElementAttributeNamePlaceholderValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1placeholderValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNamePlaceholderValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1title/title",
          "value": "XCUIElementAttributeNameTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1AttributeName~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributeNameTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielement/attributename/horizontalsizeclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielement/attributename/horizontalsizeclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
