{
  "abstract": [
    {
      "text": "A request to submit a form.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formSubmitted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKNavigationType@WKNavigationTypeFormSubmitted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "formSubmitted"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKNavigationTypeFormSubmitted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKNavigationType.formSubmitted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "formSubmitted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType": {
      "abstract": [
        {
          "text": "The type of action that triggered the navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKNavigationType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationType"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/backForward": {
      "abstract": [
        {
          "text": "A request for the frame’s next or previous item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backForward"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/backForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeBackForward"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.backForward",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/backforward"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formResubmitted": {
      "abstract": [
        {
          "text": "A request to resubmit a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formResubmitted"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formResubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeFormResubmitted"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.formResubmitted",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/formresubmitted"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formSubmitted": {
      "abstract": [
        {
          "text": "A request to submit a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSubmitted"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formSubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeFormSubmitted"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.formSubmitted",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/formsubmitted"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/linkActivated": {
      "abstract": [
        {
          "text": "A link activation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkActivated"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/linkActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeLinkActivated"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.linkActivated",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/linkactivated"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/other": {
      "abstract": [
        {
          "text": "A navigation request that originates for some other reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeOther"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.other",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/other"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/reload": {
      "abstract": [
        {
          "text": "A request to reload the webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationTypeReload"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationType.reload",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationtype/reload"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Navigation-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/linkActivated",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/backForward",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/reload",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formResubmitted",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/other"
      ],
      "title": "Getting the Navigation Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKNavigationTypeFormSubmitted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeFormSubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Navigation-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/linkActivated",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/backForward",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/reload",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/formResubmitted",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationType/other"
              ],
              "title": "Getting the Navigation Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKNavigationTypeFormSubmitted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1other/title",
          "value": "WKNavigationTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1linkActivated/title",
          "value": "WKNavigationTypeLinkActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1linkActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeLinkActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType/title",
          "value": "WKNavigationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1formSubmitted/title",
          "value": "WKNavigationTypeFormSubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1formSubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeFormSubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1backForward/title",
          "value": "WKNavigationTypeBackForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1backForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeBackForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1formResubmitted/title",
          "value": "WKNavigationTypeFormResubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1formResubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeFormResubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1reload/title",
          "value": "WKNavigationTypeReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationType~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationTypeReload"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wknavigationtype/formsubmitted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wknavigationtype/formsubmitted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
