{
  "abstract": [
    {
      "text": "An undefined constellation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNRequestFaceLandmarksConstellation@VNRequestFaceLandmarksConstellationNotDefined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "constellationNotDefined"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNRequestFaceLandmarksConstellationNotDefined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNRequestFaceLandmarksConstellation.constellationNotDefined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "constellationNotDefined"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation": {
      "abstract": [
        {
          "text": "An enumeration of face landmarks in a constellation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points": {
      "abstract": [
        {
          "text": "A constellation with 65 points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation65Points"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation65Points"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellation65Points",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellation65points"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points": {
      "abstract": [
        {
          "text": "A constellation with 76 points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation76Points"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation76Points"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellation76Points",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellation76points"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined": {
      "abstract": [
        {
          "text": "An undefined constellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellationNotDefined"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellationNotDefined"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellationNotDefined",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellationnotdefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types-of-Constellations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points"
      ],
      "title": "Types of Constellations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNRequestFaceLandmarksConstellationNotDefined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellationNotDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types-of-Constellations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation65Points",
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points"
              ],
              "title": "Types of Constellations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNRequestFaceLandmarksConstellationNotDefined"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation65Points/title",
          "value": "VNRequestFaceLandmarksConstellation65Points"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation65Points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation65Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/title",
          "value": "VNRequestFaceLandmarksConstellation76Points"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation76Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/title",
          "value": "VNRequestFaceLandmarksConstellationNotDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellationNotDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/title",
          "value": "VNRequestFaceLandmarksConstellation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnrequestfacelandmarksconstellation/constellationnotdefined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnrequestfacelandmarksconstellation/constellationnotdefined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
