{
  "abstract": [
    {
      "text": "Uniform Type Identifiers for file formats supported by the Model I/O framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLAsset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/asset-file-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Asset File Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAsset": {
      "abstract": [
        {
          "text": "An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAsset"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAsset"
        }
      ],
      "role": "symbol",
      "title": "MDLAsset",
      "type": "topic",
      "url": "/documentation/modelio/mdlasset"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject": {
      "abstract": [
        {
          "text": "The Object file format (common extension ",
          "type": "text"
        },
        {
          "code": ".obj",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTType3dObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTType3dObject"
        }
      ],
      "role": "symbol",
      "title": "kUTType3dObject",
      "type": "topic",
      "url": "/documentation/modelio/kuttype3dobject"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic": {
      "abstract": [
        {
          "text": "The Alembic file format (common extension ",
          "type": "text"
        },
        {
          "code": ".abc",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeAlembic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeAlembic"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeAlembic",
      "type": "topic",
      "url": "/documentation/modelio/kuttypealembic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon": {
      "abstract": [
        {
          "text": "The Polygon file format (common extension ",
          "type": "text"
        },
        {
          "code": ".ply",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypePolygon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypePolygon"
        }
      ],
      "role": "symbol",
      "title": "kUTTypePolygon",
      "type": "topic",
      "url": "/documentation/modelio/kuttypepolygon"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography": {
      "abstract": [
        {
          "text": "The Stereolithography file format (common extension ",
          "type": "text"
        },
        {
          "code": ".stl",
          "type": "codeVoice"
        },
        {
          "text": "), also known as the Standard Tessellated Geometry format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeStereolithography"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeStereolithography"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeStereolithography",
      "type": "topic",
      "url": "/documentation/modelio/kuttypestereolithography"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription": {
      "abstract": [
        {
          "text": "The Universal Scene Description file format (common extension ",
          "type": "text"
        },
        {
          "code": ".usd",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescription"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeUniversalSceneDescription",
      "type": "topic",
      "url": "/documentation/modelio/kuttypeuniversalscenedescription"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
        "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
                "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTType3dObject/title",
          "value": "kUTType3dObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTType3dObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTType3dObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeStereolithography/title",
          "value": "kUTTypeStereolithography"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeStereolithography/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeStereolithography"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title",
          "value": "MDLAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypePolygon/title",
          "value": "kUTTypePolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypePolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypePolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescription/title",
          "value": "kUTTypeUniversalSceneDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeUniversalSceneDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeAlembic/title",
          "value": "kUTTypeAlembic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeAlembic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeAlembic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/asset-file-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/asset-file-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
