{"metadata":{"platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"9.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"9.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","deprecated":false},{"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.11","deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"9.0","deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false}],"role":"symbol","navigatorTitle":[{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"title":"MDLAxisAlignedBoundingBox","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"modules":[{"name":"Model I/O"}],"symbolKind":"struct","roleHeading":"Structure","externalID":"c:@SA@MDLAxisAlignedBoundingBox"},"topicSections":[{"generated":true,"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init()","doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/maxBounds","doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/minBounds"],"anchor":"Instance-Properties","title":"Instance Properties"}],"abstract":[{"text":"The minimal volume containing an object, used by the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)"},{"text":" method.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlaxisalignedboundingbox"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlaxisalignedboundingbox"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLAxisAlignedBoundingBox"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox"},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)":{"title":"boundingBox(atTime:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingBox","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MDLAxisAlignedBoundingBox"}],"url":"/documentation/modelio/mdlobject/boundingbox(attime:)","abstract":[{"text":"Returns the minimum region entirely enclosing the object’s contents at the specified time sample.","type":"text"}],"navigatorTitle":[{"text":"boundingBoxAtTime:","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)"},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)","url":"/documentation/modelio/mdlaxisalignedboundingbox/init(maxbounds:minbounds:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(maxBounds:minBounds:)","type":"topic","abstract":[]},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init()":{"type":"topic","title":"init()","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"/documentation/modelio/mdlaxisalignedboundingbox/init()","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init()","role":"symbol","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","kind":"symbol","role":"symbol","title":"Sendable","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/minBounds":{"title":"minBounds","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minBounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"url":"/documentation/modelio/mdlaxisalignedboundingbox/minbounds","abstract":[{"text":"The corner of the bounding box with the lowest x-, y-, and z-coordinate values.","type":"text"}],"navigatorTitle":[{"text":"minBounds","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/minBounds"},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/maxBounds":{"abstract":[{"text":"The corner of the bounding box with the highest x-, y-, and z-coordinate values.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/maxBounds","title":"maxBounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxBounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"role":"symbol","navigatorTitle":[{"text":"maxBounds","kind":"identifier"}],"url":"/documentation/modelio/mdlaxisalignedboundingbox/maxbounds"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"abstract":[{"type":"text","text":""}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"url":"/documentation/Swift/BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","kind":"symbol","role":"symbol","title":"BitwiseCopyable","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox":{"title":"MDLAxisAlignedBoundingBox","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox","type":"topic","navigatorTitle":[{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"url":"/documentation/modelio/mdlaxisalignedboundingbox","abstract":[{"type":"text","text":"The minimal volume containing an object, used by the "},{"isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)","type":"reference"},{"text":" method.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"iOS","introducedAt":"9.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"9.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","introducedAt":"10.11","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","introducedAt":"9.0","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Structure","path":"/metadata/roleHeading"},{"op":"replace","value":"MDLAxisAlignedBoundingBox","path":"/metadata/title"},{"op":"replace","value":"struct","path":"/metadata/symbolKind"},{"value":[{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO"]]},"path":"/hierarchy","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/maxBounds","doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/minBounds"]}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"boundingBoxAtTime:","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/title"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"boundingBoxAtTime:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox~1minBounds/title","value":"minBounds","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox~1minBounds/fragments","value":[{"kind":"identifier","text":"minBounds"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox~1maxBounds/title","value":"maxBounds","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox~1maxBounds/fragments","value":[{"kind":"identifier","text":"maxBounds"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/title","value":"MDLAxisAlignedBoundingBox","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/fragments","value":[{"kind":"identifier","text":"MDLAxisAlignedBoundingBox"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/navigatorTitle","value":[{"kind":"identifier","text":"MDLAxisAlignedBoundingBox"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}