{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLAnimatedValueInterpolation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLAnimatedValueInterpolation"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLAnimatedValueInterpolation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MDLAnimatedValueInterpolation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAnimatedValueInterpolation"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAnimatedValueInterpolation"
        }
      ],
      "role": "symbol",
      "title": "MDLAnimatedValueInterpolation",
      "type": "topic",
      "url": "/documentation/modelio/mdlanimatedvalueinterpolation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/constant": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constant"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAnimatedValueInterpolationConstant"
        }
      ],
      "role": "symbol",
      "title": "MDLAnimatedValueInterpolation.constant",
      "type": "topic",
      "url": "/documentation/modelio/mdlanimatedvalueinterpolation/constant"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlanimatedvalueinterpolation/init(rawvalue:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/linear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAnimatedValueInterpolationLinear"
        }
      ],
      "role": "symbol",
      "title": "MDLAnimatedValueInterpolation.linear",
      "type": "topic",
      "url": "/documentation/modelio/mdlanimatedvalueinterpolation/linear"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAsset/placeLightProbes(withDensity:heuristic:using:)": {
      "abstract": [
        {
          "text": "Automatically creates and places light probes for use in illuminating a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeLightProbes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "heuristic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLProbePlacement",
          "text": "MDLProbePlacement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLLightProbeIrradianceDataSource",
          "text": "MDLLightProbeIrradianceDataSource"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLLightProbe",
          "text": "MDLLightProbe"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAsset/placeLightProbes(withDensity:heuristic:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeLightProbesWithDensity:heuristic:usingIrradianceDataSource:"
        }
      ],
      "role": "symbol",
      "title": "placeLightProbes(withDensity:heuristic:using:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlasset/placelightprobes(withdensity:heuristic:using:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection": {
      "abstract": [
        {
          "text": "The style of projection transform used by the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLCameraProjection",
          "text": "MDLCameraProjection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projection"
        }
      ],
      "role": "symbol",
      "title": "projection",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/projection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection": {
      "abstract": [
        {
          "text": "Options for camera projection styles, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCameraProjection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCameraProjection"
        }
      ],
      "role": "symbol",
      "title": "MDLCameraProjection",
      "type": "topic",
      "url": "/documentation/modelio/mdlcameraprojection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLDataPrecision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLDataPrecision"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLDataPrecision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLDataPrecision"
        }
      ],
      "role": "symbol",
      "title": "MDLDataPrecision",
      "type": "topic",
      "url": "/documentation/modelio/mdldataprecision"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType": {
      "abstract": [
        {
          "text": "Types of geometric primitives for rendering a submesh, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth": {
      "abstract": [
        {
          "text": "Options for the size of integer data in a submesh’s index buffer, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "role": "symbol",
      "title": "MDLIndexBitDepth",
      "type": "topic",
      "url": "/documentation/modelio/mdlindexbitdepth"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType": {
      "abstract": [
        {
          "text": "The type of the light.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLLightType",
          "text": "MDLLightType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightType"
        }
      ],
      "role": "symbol",
      "title": "lightType",
      "type": "topic",
      "url": "/documentation/modelio/mdllight/lighttype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType": {
      "abstract": [
        {
          "text": "Options for the shape and style of illumination provided by a light, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLightType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightType"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialFace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialFace"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialFace"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialFace",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialface"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at sizes between mipmap levels, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialMipMapFilterMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialmipmapfiltermode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic": {
      "abstract": [
        {
          "text": "The semantic meaning for the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semantic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialSemantic",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "semantic"
        }
      ],
      "role": "symbol",
      "title": "semantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/semantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type": {
      "abstract": [
        {
          "text": "The data type stored in the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialPropertyType",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/type"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType": {
      "abstract": [
        {
          "text": "Options for the data type of a material property, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic": {
      "abstract": [
        {
          "text": "Options for the semantic use of a material property’s value in rendering a particular surface appearance; used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at coordinates between texels, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureFilterMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturefiltermode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at coordinates outside the texture bounds, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type": {
      "abstract": [
        {
          "text": "The type of data contained in a buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMeshBufferType",
          "text": "MDLMeshBufferType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffer/type"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator": {
      "abstract": [
        {
          "text": "The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferallocator"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType": {
      "abstract": [
        {
          "text": "Options for the content of a mesh buffer, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods for creating buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferType"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferType",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLProbePlacement": {
      "abstract": [
        {
          "text": "Options affecting automatic placement of light probes in a scene, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAsset/placeLightProbes(withDensity:heuristic:using:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLProbePlacement"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLProbePlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLProbePlacement"
        }
      ],
      "role": "symbol",
      "title": "MDLProbePlacement",
      "type": "topic",
      "url": "/documentation/modelio/mdlprobeplacement"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType": {
      "abstract": [
        {
          "text": "The type of geometric primitives described by the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometryType"
        }
      ],
      "role": "symbol",
      "title": "geometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/geometrytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType": {
      "abstract": [
        {
          "text": "The data type for each element in the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexType"
        }
      ],
      "role": "symbol",
      "title": "indexType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/indextype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTexture/channelEncoding": {
      "abstract": [
        {
          "text": "The data format for each channel value per texel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelEncoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLTextureChannelEncoding",
          "text": "MDLTextureChannelEncoding"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTexture/channelEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelEncoding"
        }
      ],
      "role": "symbol",
      "title": "channelEncoding",
      "type": "topic",
      "url": "/documentation/modelio/mdltexture/channelencoding"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureChannelEncoding": {
      "abstract": [
        {
          "text": "Options for the data size and type of texel channel values, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTexture/channelEncoding",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTextureChannelEncoding"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureChannelEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTextureChannelEncoding"
        }
      ],
      "role": "symbol",
      "title": "MDLTextureChannelEncoding",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturechannelencoding"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures at sizes larger than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureFilterMode",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magFilter"
        }
      ],
      "role": "symbol",
      "title": "magFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/magfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures at sizes smaller than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureFilterMode",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minFilter"
        }
      ],
      "role": "symbol",
      "title": "minFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/minfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures using mipmapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialMipMapFilterMode",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mipFilter"
        }
      ],
      "role": "symbol",
      "title": "mipFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/mipfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture r-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rWrapMode"
        }
      ],
      "role": "symbol",
      "title": "rWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/rwrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sWrapMode"
        }
      ],
      "role": "symbol",
      "title": "sWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/swrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tWrapMode"
        }
      ],
      "role": "symbol",
      "title": "tWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/twrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format": {
      "abstract": [
        {
          "text": "The format of per-vertex data for the attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "format"
        }
      ],
      "role": "symbol",
      "title": "format",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/format"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat": {
      "abstract": [
        {
          "text": "Descriptions of the data size and layout for a vertex attribute, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
        "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialFace",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType",
        "doc://com.apple.modelio/documentation/ModelIO/MDLProbePlacement",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureChannelEncoding",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat",
        "doc://com.apple.modelio/documentation/ModelIO/MDLDataPrecision"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/constant",
        "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/linear"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLAnimatedValueInterpolation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/constant",
                "doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedValueInterpolation/linear"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
                "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialFace",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType",
                "doc://com.apple.modelio/documentation/ModelIO/MDLProbePlacement",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureChannelEncoding",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat",
                "doc://com.apple.modelio/documentation/ModelIO/MDLDataPrecision"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLAnimatedValueInterpolation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/title",
          "value": "rWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/title",
          "value": "MDLCameraProjection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCameraProjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCameraProjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/title",
          "value": "MDLLightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1mipFilter/title",
          "value": "mipFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1mipFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/title",
          "value": "MDLMaterialTextureFilterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/title",
          "value": "MDLMaterialPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/title",
          "value": "indexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/title",
          "value": "format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/title",
          "value": "MDLMaterialMipMapFilterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialMipMapFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialMipMapFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/title",
          "value": "MDLGeometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation/title",
          "value": "MDLAnimatedValueInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/title",
          "value": "geometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLDataPrecision/title",
          "value": "MDLDataPrecision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLDataPrecision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLDataPrecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLDataPrecision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLDataPrecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/title",
          "value": "MDLMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/title",
          "value": "MDLMaterialTextureWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projection/title",
          "value": "projection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1magFilter/title",
          "value": "magFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1magFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/title",
          "value": "semantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "semantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/title",
          "value": "lightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/title",
          "value": "MDLMaterialSemantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1placeLightProbes(withDensity:heuristic:using:)/title",
          "value": "placeLightProbesWithDensity:heuristic:usingIrradianceDataSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1placeLightProbes(withDensity:heuristic:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "placeLightProbesWithDensity:heuristic:usingIrradianceDataSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureChannelEncoding/title",
          "value": "MDLTextureChannelEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureChannelEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureChannelEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureChannelEncoding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureChannelEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/title",
          "value": "MDLIndexBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture~1channelEncoding/title",
          "value": "channelEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture~1channelEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/title",
          "value": "tWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation~1constant/title",
          "value": "MDLAnimatedValueInterpolationConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation~1constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolationConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialFace/title",
          "value": "MDLMaterialFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialFace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLProbePlacement/title",
          "value": "MDLProbePlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLProbePlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLProbePlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLProbePlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLProbePlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/title",
          "value": "MDLMeshBufferType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/title",
          "value": "sWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1minFilter/title",
          "value": "minFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1minFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation~1linear/title",
          "value": "MDLAnimatedValueInterpolationLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedValueInterpolation~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAnimatedValueInterpolationLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/title",
          "value": "MDLVertexFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlanimatedvalueinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlanimatedvalueinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
