{
  "abstract": [
    {
      "text": "A point of view for rendering a 3D scene, along with a set of parameters describing an intended appearance for rendering.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLCamera",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLCamera"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLCamera"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MDLCamera"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Camera parameters include basic information—such as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fieldOfView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties—for use with any renderer, as well as attributes that model real-world cameras—such as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposure",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties—for use in a renderer based on realistic optical physics.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a 3D scene, along with a set of parameters describing an intended appearance for rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount": {
      "abstract": [
        {
          "text": "The number of blades in the camera’s simulated aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apertureBladeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "apertureBladeCount"
        }
      ],
      "role": "symbol",
      "title": "apertureBladeCount",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/aperturebladecount"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion": {
      "abstract": [
        {
          "text": "The first coefficient for determining the radial distortion applied to pixels rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barrelDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barrelDistortion"
        }
      ],
      "role": "symbol",
      "title": "barrelDistortion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/barreldistortion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)": {
      "abstract": [
        {
          "text": "Creates and returns a texture, based on the camera’s aperture blade count, to be used in rendering out-of-focus highlights in a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bokehKernel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLTexture",
          "text": "MDLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bokehKernelWithSize:"
        }
      ],
      "role": "symbol",
      "title": "bokehKernel(withSize:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/bokehkernel(withsize:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/cameraWithSCNCamera:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "cameraWithSCNCamera:"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/cameraWithSCNCamera:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraWithSCNCamera:"
        }
      ],
      "role": "symbol",
      "title": "cameraWithSCNCamera:",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/camerawithscncamera:"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration": {
      "abstract": [
        {
          "text": "The amount of radial color shift around the edges of an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaticAberration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chromaticAberration"
        }
      ],
      "role": "symbol",
      "title": "chromaticAberration",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/chromaticaberration"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposure": {
      "abstract": [
        {
          "text": "Red, green, and blue factors that scale each color channel in the camera’s image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposure"
        }
      ],
      "role": "symbol",
      "title": "exposure",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/exposure"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposureCompression": {
      "abstract": [
        {
          "text": "Two parameters that determine the brightness compression curve for colors in the camera’s image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposureCompression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposureCompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposureCompression"
        }
      ],
      "role": "symbol",
      "title": "exposureCompression",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/exposurecompression"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop": {
      "abstract": [
        {
          "text": "The relative aperture ratio of the camera’s simulated lens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fStop"
        }
      ],
      "role": "symbol",
      "title": "fStop",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/fstop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/farVisibilityDistance": {
      "abstract": [
        {
          "text": "The camera’s far depth limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "farVisibilityDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/farVisibilityDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "farVisibilityDistance"
        }
      ],
      "role": "symbol",
      "title": "farVisibilityDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/farvisibilitydistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fieldOfView": {
      "abstract": [
        {
          "text": "The camera’s field of view, in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fieldOfView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fieldOfView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fieldOfView"
        }
      ],
      "role": "symbol",
      "title": "fieldOfView",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/fieldofview"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion": {
      "abstract": [
        {
          "text": "The second coefficient for determining the radial distortion applied to pixels rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fisheyeDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fisheyeDistortion"
        }
      ],
      "role": "symbol",
      "title": "fisheyeDistortion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/fisheyedistortion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/flash": {
      "abstract": [
        {
          "text": "Red, green, and blue factors to be used in brightening darker areas of the camera’s image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/flash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flash"
        }
      ],
      "role": "symbol",
      "title": "flash",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/flash"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength": {
      "abstract": [
        {
          "text": "The focal length, in millimeters, of the camera’s simulated lens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focalLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focalLength"
        }
      ],
      "role": "symbol",
      "title": "focalLength",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/focallength"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance": {
      "abstract": [
        {
          "text": "The distance, in meters, at which the lens is focused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusDistance"
        }
      ],
      "role": "symbol",
      "title": "focusDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/focusdistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/frameBoundingBox(_:setNearAndFar:)": {
      "abstract": [
        {
          "text": "Moves the camera such that the specified bounding box lies entirely within the camera’s field of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameBoundingBox"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
          "text": "MDLAxisAlignedBoundingBox"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "setNearAndFar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/frameBoundingBox(_:setNearAndFar:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameBoundingBox:setNearAndFar:"
        }
      ],
      "role": "symbol",
      "title": "frameBoundingBox(_:setNearAndFar:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/frameboundingbox(_:setnearandfar:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:)": {
      "abstract": [
        {
          "text": "Orients the camera to face toward the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "look"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAt:"
        }
      ],
      "role": "symbol",
      "title": "look(at:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/look(at:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:from:)": {
      "abstract": [
        {
          "text": "Sets the camera’s position and orients the camera to face toward the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "look"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAt:from:"
        }
      ],
      "role": "symbol",
      "title": "look(at:from:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/look(at:from:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion": {
      "abstract": [
        {
          "text": "The maximum diameter, in millimeters on the imaging plane, at which light from a point source should appear in an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCircleOfConfusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumCircleOfConfusion"
        }
      ],
      "role": "symbol",
      "title": "maximumCircleOfConfusion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/maximumcircleofconfusion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/nearVisibilityDistance": {
      "abstract": [
        {
          "text": "The camera’s near depth limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nearVisibilityDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/nearVisibilityDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nearVisibilityDistance"
        }
      ],
      "role": "symbol",
      "title": "nearVisibilityDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/nearvisibilitydistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting": {
      "abstract": [
        {
          "text": "The amount of radial light attenuation around the edges of an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opticalVignetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opticalVignetting"
        }
      ],
      "role": "symbol",
      "title": "opticalVignetting",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/opticalvignetting"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection": {
      "abstract": [
        {
          "text": "The style of projection transform used by the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLCameraProjection",
          "text": "MDLCameraProjection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projection"
        }
      ],
      "role": "symbol",
      "title": "projection",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/projection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix": {
      "abstract": [
        {
          "text": "A transformation matrix that determines the extent of a scene visible to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        }
      ],
      "role": "symbol",
      "title": "projectionMatrix",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/projectionmatrix"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/ray(to:forViewPort:)": {
      "abstract": [
        {
          "text": "Returns a point, in 3D world coordinates, corresponding to the specified 2D view coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forViewPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float3",
          "text": "vector_float3"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/ray(to:forViewPort:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rayTo:forViewPort:"
        }
      ],
      "role": "symbol",
      "title": "ray(to:forViewPort:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/ray(to:forviewport:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorAspect": {
      "abstract": [
        {
          "text": "The ratio of width to height for the camera’s simulated imaging surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorAspect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorAspect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorAspect"
        }
      ],
      "role": "symbol",
      "title": "sensorAspect",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/sensoraspect"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorEnlargement": {
      "abstract": [
        {
          "text": "The horizontal and vertical scale factors that determine the active region of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorEnlargement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorEnlargement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorEnlargement"
        }
      ],
      "role": "symbol",
      "title": "sensorEnlargement",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/sensorenlargement"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorShift": {
      "abstract": [
        {
          "text": "The horizontal and vertical offsets, in millimeters, of the center of the camera image relative to the center of the simulated lens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorShift"
        }
      ],
      "role": "symbol",
      "title": "sensorShift",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/sensorshift"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorVerticalAperture": {
      "abstract": [
        {
          "text": "The height, in millimeters, of the camera’s simulated imaging surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorVerticalAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorVerticalAperture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorVerticalAperture"
        }
      ],
      "role": "symbol",
      "title": "sensorVerticalAperture",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/sensorverticalaperture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval": {
      "abstract": [
        {
          "text": "The duration, in seconds, for which the camera’s simulated shutter is open during each frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shutterOpenInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shutterOpenInterval"
        }
      ],
      "role": "symbol",
      "title": "shutterOpenInterval",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/shutteropeninterval"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/worldToMetersConversionScale": {
      "abstract": [
        {
          "text": "The scale factor to meters from the world coordinate system containing the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldToMetersConversionScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/worldToMetersConversionScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "worldToMetersConversionScale"
        }
      ],
      "role": "symbol",
      "title": "worldToMetersConversionScale",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/worldtometersconversionscale"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection": {
      "abstract": [
        {
          "text": "Options for camera projection styles, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCameraProjection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCameraProjection"
        }
      ],
      "role": "symbol",
      "title": "MDLCameraProjection",
      "type": "topic",
      "url": "/documentation/modelio/mdlcameraprojection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNamed": {
      "abstract": [
        {
          "text": "The common interface for Model I/O objects that expose a human-readable name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "role": "symbol",
      "title": "MDLNamed",
      "type": "topic",
      "url": "/documentation/modelio/mdlnamed"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLObject": {
      "abstract": [
        {
          "text": "The base class for objects that are part of a 3D asset, including meshes, cameras, and lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLObject"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLObject"
        }
      ],
      "role": "symbol",
      "title": "MDLObject",
      "type": "topic",
      "url": "/documentation/modelio/mdlobject"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a stereoscopic display of a 3D scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLStereoscopicCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Cameras",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
      ],
      "title": "Cameras"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Camera-Position-and-Orientation",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/frameBoundingBox(_:setNearAndFar:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:from:)"
      ],
      "title": "Managing Camera Position and Orientation"
    },
    {
      "anchor": "Managing-Camera-Perspective",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/nearVisibilityDistance",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/farVisibilityDistance",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fieldOfView",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/ray(to:forViewPort:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/worldToMetersConversionScale"
      ],
      "title": "Managing Camera Perspective"
    },
    {
      "anchor": "Modeling-a-Physical-Lens",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval"
      ],
      "title": "Modeling a Physical Lens"
    },
    {
      "anchor": "Modeling-a-Physical-Imaging-Surface",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorVerticalAperture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorAspect",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorEnlargement",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorShift",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/flash",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposure",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposureCompression"
      ],
      "title": "Modeling a Physical Imaging Surface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLCamera"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Camera-Position-and-Orientation",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/frameBoundingBox(_:setNearAndFar:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/look(at:from:)"
              ],
              "title": "Managing Camera Position and Orientation"
            },
            {
              "anchor": "Managing-Camera-Perspective",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projectionMatrix",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/projection",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCameraProjection",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/nearVisibilityDistance",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/farVisibilityDistance",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fieldOfView",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/ray(to:forViewPort:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/worldToMetersConversionScale"
              ],
              "title": "Managing Camera Perspective"
            },
            {
              "anchor": "Modeling-a-Physical-Lens",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval"
              ],
              "title": "Modeling a Physical Lens"
            },
            {
              "anchor": "Modeling-a-Physical-Imaging-Surface",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorVerticalAperture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorAspect",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorEnlargement",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/sensorShift",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/flash",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposure",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/exposureCompression"
              ],
              "title": "Modeling a Physical Imaging Surface"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/cameraWithSCNCamera:"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Cameras",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera"
              ],
              "title": "Cameras"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLCamera"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MDLObject",
                    "text": "MDLObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fieldOfView/title",
          "value": "fieldOfView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fieldOfView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fieldOfView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1worldToMetersConversionScale/title",
          "value": "worldToMetersConversionScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1worldToMetersConversionScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "worldToMetersConversionScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1farVisibilityDistance/title",
          "value": "farVisibilityDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1farVisibilityDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "farVisibilityDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1chromaticAberration/title",
          "value": "chromaticAberration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1chromaticAberration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticAberration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1opticalVignetting/title",
          "value": "opticalVignetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1opticalVignetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opticalVignetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focalLength/title",
          "value": "focalLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focalLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focalLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1bokehKernel(withSize:)/title",
          "value": "bokehKernelWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1bokehKernel(withSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bokehKernelWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/title",
          "value": "MDLCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fStop/title",
          "value": "fStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1nearVisibilityDistance/title",
          "value": "nearVisibilityDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1nearVisibilityDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nearVisibilityDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1look(at:from:)/title",
          "value": "lookAt:from:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1look(at:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAt:from:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projection/title",
          "value": "projection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1maximumCircleOfConfusion/title",
          "value": "maximumCircleOfConfusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1maximumCircleOfConfusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumCircleOfConfusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1apertureBladeCount/title",
          "value": "apertureBladeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1apertureBladeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "apertureBladeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1frameBoundingBox(_:setNearAndFar:)/title",
          "value": "frameBoundingBox:setNearAndFar:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1frameBoundingBox(_:setNearAndFar:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "frameBoundingBox:setNearAndFar:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorAspect/title",
          "value": "sensorAspect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorAspect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorAspect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorEnlargement/title",
          "value": "sensorEnlargement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorEnlargement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorEnlargement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/title",
          "value": "MDLCameraProjection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCameraProjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCameraProjection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCameraProjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fisheyeDistortion/title",
          "value": "fisheyeDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fisheyeDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fisheyeDistortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1flash/title",
          "value": "flash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1flash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/title",
          "value": "MDLNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1exposureCompression/title",
          "value": "exposureCompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1exposureCompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposureCompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1barrelDistortion/title",
          "value": "barrelDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1barrelDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barrelDistortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projectionMatrix/title",
          "value": "projectionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1projectionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorShift/title",
          "value": "sensorShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/title",
          "value": "MDLStereoscopicCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1look(at:)/title",
          "value": "lookAt:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1look(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAt:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorVerticalAperture/title",
          "value": "sensorVerticalAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1sensorVerticalAperture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorVerticalAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1shutterOpenInterval/title",
          "value": "shutterOpenInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1shutterOpenInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shutterOpenInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1ray(to:forViewPort:)/title",
          "value": "rayTo:forViewPort:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1ray(to:forViewPort:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rayTo:forViewPort:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/title",
          "value": "MDLObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focusDistance/title",
          "value": "focusDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focusDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1exposure/title",
          "value": "exposure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1exposure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlcamera"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlcamera"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
