{
  "abstract": [
    {
      "text": "Options for the semantic use of a material property’s value in rendering a particular surface appearance; used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLMaterialSemantic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLMaterialSemantic"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLMaterialSemantic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MDLMaterialSemantic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic": {
      "abstract": [
        {
          "text": "The semantic meaning for the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semantic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialSemantic",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "semantic"
        }
      ],
      "role": "symbol",
      "title": "semantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/semantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type": {
      "abstract": [
        {
          "text": "The data type stored in the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialPropertyType",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/type"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType": {
      "abstract": [
        {
          "text": "Options for the data type of a material property, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic": {
      "abstract": [
        {
          "text": "Options for the semantic use of a material property’s value in rendering a particular surface appearance; used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusion": {
      "abstract": [
        {
          "text": "The attenuation of ambient light due to local geometry variations on a surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientOcclusion"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAmbientOcclusion"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.ambientOcclusion",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/ambientocclusion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusionScale": {
      "abstract": [
        {
          "text": "The scaling factor for ambient occlusion shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientOcclusionScale"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusionScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAmbientOcclusionScale"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.ambientOcclusionScale",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/ambientocclusionscale"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic": {
      "abstract": [
        {
          "text": "The degree to which specular highlights elongate in the direction of the local tangent basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anisotropic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAnisotropic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.anisotropic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/anisotropic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation": {
      "abstract": [
        {
          "text": "The angle at which anisotropic effects are rotated relative to the local tangent basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anisotropicRotation"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAnisotropicRotation"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.anisotropicRotation",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/anisotropicrotation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor": {
      "abstract": [
        {
          "text": "The inherent color of a surface, to be used as a modulator during shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseColor"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticBaseColor"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.baseColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/basecolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump": {
      "abstract": [
        {
          "text": "The degree of perturbation in a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bump"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticBump"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.bump",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/bump"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat": {
      "abstract": [
        {
          "text": "The intensity of a second specular highlight, similar to the gloss that results from a clear coat on an automotive finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearcoat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticClearcoat"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.clearcoat",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/clearcoat"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss": {
      "abstract": [
        {
          "text": "The spread of a second specular highlight, similar to the gloss that results from a clear coat on an automotive finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearcoatGloss"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticClearcoatGloss"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.clearcoatGloss",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/clearcoatgloss"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacement": {
      "abstract": [
        {
          "text": "The displacement of a material’s surface relative to the surface normal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displacement"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticDisplacement"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.displacement",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/displacement"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacementScale": {
      "abstract": [
        {
          "text": "The scaling factor for displacement of a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displacementScale"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacementScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticDisplacementScale"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.displacementScale",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/displacementscale"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission": {
      "abstract": [
        {
          "text": "The color emitted as radiance from a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emission"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticEmission"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.emission",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/emission"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/init(rawvalue:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/interfaceIndexOfRefraction": {
      "abstract": [
        {
          "text": "The index of refraction for the medium surrounding a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceIndexOfRefraction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/interfaceIndexOfRefraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticInterfaceIndexOfRefraction"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.interfaceIndexOfRefraction",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/interfaceindexofrefraction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/materialIndexOfRefraction": {
      "abstract": [
        {
          "text": "The index of refraction for a material itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "materialIndexOfRefraction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/materialIndexOfRefraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticMaterialIndexOfRefraction"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.materialIndexOfRefraction",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/materialindexofrefraction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic": {
      "abstract": [
        {
          "text": "The degree to which a material appears as a dielectric surface (lower values) or as a metal (higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metallic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticMetallic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.metallic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/metallic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/none": {
      "abstract": [
        {
          "text": "The material property’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property has not been initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticNone"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.none",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/none"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/objectSpaceNormal": {
      "abstract": [
        {
          "text": "The variation in the surface normal vectors in a material, relative to model coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectSpaceNormal"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/objectSpaceNormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticObjectSpaceNormal"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.objectSpaceNormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/objectspacenormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity": {
      "abstract": [
        {
          "text": "The opacity of a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticOpacity"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.opacity",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/opacity"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness": {
      "abstract": [
        {
          "text": "The degree to which a material appears smooth, affecting both diffuse and specular response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roughness"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticRoughness"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.roughness",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/roughness"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen": {
      "abstract": [
        {
          "text": "The intensity of highlights that appear only at glancing angles on a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheen"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSheen"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.sheen",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/sheen"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint": {
      "abstract": [
        {
          "text": "The balance of color for highlights that appear only at glancing angles, between the light color (lower values) and the material’s base color (at higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheenTint"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSheenTint"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.sheenTint",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/sheentint"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular": {
      "abstract": [
        {
          "text": "The intensity of specular highlights that appear on the material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specular"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecular"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specular",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/specular"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent": {
      "abstract": [
        {
          "text": "The exponent to be used in Blinn-Phong approximation of the material’s specular response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specularExponent"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecularExponent"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specularExponent",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/specularexponent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint": {
      "abstract": [
        {
          "text": "The balance of color for specular highlights, between the light color (lower values) and the material’s base color (at higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specularTint"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecularTint"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specularTint",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/speculartint"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface": {
      "abstract": [
        {
          "text": "The degree to which light scatters under the surface of a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsurface"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSubsurface"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.subsurface",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/subsurface"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/tangentSpaceNormal": {
      "abstract": [
        {
          "text": "The variation in the surface normal vectors in a material, relative to surface tangent coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tangentSpaceNormal"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/tangentSpaceNormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticTangentSpaceNormal"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.tangentSpaceNormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/tangentspacenormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/userDefined": {
      "abstract": [
        {
          "text": "The meaning of the material property’s value is not one of the standard semantic uses recognized by Model I/O.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDefined"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/userDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticUserDefined"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.userDefined",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/userdefined"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/interfaceIndexOfRefraction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/materialIndexOfRefraction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/objectSpaceNormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/tangentSpaceNormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacement",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacementScale",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusionScale",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/none",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/userDefined"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLMaterialSemantic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/interfaceIndexOfRefraction",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/materialIndexOfRefraction",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/objectSpaceNormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/tangentSpaceNormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacement",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/displacementScale",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/ambientOcclusionScale",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/none",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/userDefined"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLMaterialSemantic"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1displacement/title",
          "value": "MDLMaterialSemanticDisplacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1displacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticDisplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specular/title",
          "value": "MDLMaterialSemanticSpecular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/title",
          "value": "MDLMaterialPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularTint/title",
          "value": "MDLMaterialSemanticSpecularTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecularTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1opacity/title",
          "value": "MDLMaterialSemanticOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1ambientOcclusion/title",
          "value": "MDLMaterialSemanticAmbientOcclusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1ambientOcclusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAmbientOcclusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1userDefined/title",
          "value": "MDLMaterialSemanticUserDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1userDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticUserDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1displacementScale/title",
          "value": "MDLMaterialSemanticDisplacementScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1displacementScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticDisplacementScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularExponent/title",
          "value": "MDLMaterialSemanticSpecularExponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularExponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecularExponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/title",
          "value": "MDLMaterialSemantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1tangentSpaceNormal/title",
          "value": "MDLMaterialSemanticTangentSpaceNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1tangentSpaceNormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticTangentSpaceNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1bump/title",
          "value": "MDLMaterialSemanticBump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1bump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticBump"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheenTint/title",
          "value": "MDLMaterialSemanticSheenTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheenTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSheenTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1metallic/title",
          "value": "MDLMaterialSemanticMetallic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1metallic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticMetallic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1none/title",
          "value": "MDLMaterialSemanticNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1materialIndexOfRefraction/title",
          "value": "MDLMaterialSemanticMaterialIndexOfRefraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1materialIndexOfRefraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticMaterialIndexOfRefraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1emission/title",
          "value": "MDLMaterialSemanticEmission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1emission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticEmission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropicRotation/title",
          "value": "MDLMaterialSemanticAnisotropicRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropicRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAnisotropicRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1roughness/title",
          "value": "MDLMaterialSemanticRoughness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1roughness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticRoughness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheen/title",
          "value": "MDLMaterialSemanticSheen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSheen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1baseColor/title",
          "value": "MDLMaterialSemanticBaseColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1baseColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticBaseColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoatGloss/title",
          "value": "MDLMaterialSemanticClearcoatGloss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoatGloss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticClearcoatGloss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoat/title",
          "value": "MDLMaterialSemanticClearcoat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticClearcoat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1ambientOcclusionScale/title",
          "value": "MDLMaterialSemanticAmbientOcclusionScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1ambientOcclusionScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAmbientOcclusionScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1objectSpaceNormal/title",
          "value": "MDLMaterialSemanticObjectSpaceNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1objectSpaceNormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticObjectSpaceNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1interfaceIndexOfRefraction/title",
          "value": "MDLMaterialSemanticInterfaceIndexOfRefraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1interfaceIndexOfRefraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticInterfaceIndexOfRefraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/title",
          "value": "semantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "semantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1subsurface/title",
          "value": "MDLMaterialSemanticSubsurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1subsurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSubsurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropic/title",
          "value": "MDLMaterialSemanticAnisotropic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAnisotropic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmaterialsemantic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmaterialsemantic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
