{
  "abstract": [
    {
      "text": "Options for the content of a mesh buffer, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property and by ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " methods for creating buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLMeshBufferType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLMeshBufferType"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLMeshBufferType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MDLMeshBufferType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type": {
      "abstract": [
        {
          "text": "The type of data contained in a buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMeshBufferType",
          "text": "MDLMeshBufferType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffer/type"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator": {
      "abstract": [
        {
          "text": "The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferallocator"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType": {
      "abstract": [
        {
          "text": "Options for the content of a mesh buffer, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods for creating buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferType"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferType",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/custom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferTypeCustom"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferType.custom",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype/custom"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index": {
      "abstract": [
        {
          "text": "The buffer contains index data for a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferTypeIndex"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferType.index",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype/index"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype/init(rawvalue:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex": {
      "abstract": [
        {
          "text": "The buffer contains per-vertex data for one or more vertex attributes of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertex"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferTypeVertex"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferType.vertex",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffertype/vertex"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh": {
      "abstract": [
        {
          "text": "A container for index buffer data and material information to be used in rendering all or part of a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MDLSubmesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/custom"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLMeshBufferType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/custom"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLMeshBufferType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/title",
          "value": "MDLMeshBufferTypeVertex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferTypeVertex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1custom/title",
          "value": "MDLMeshBufferTypeCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferTypeCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/title",
          "value": "MDLMeshBufferTypeIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferTypeIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/title",
          "value": "MDLMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/title",
          "value": "MDLMeshBufferType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/title",
          "value": "MDLSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmeshbuffertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmeshbuffertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
