{
  "abstract": [
    {
      "text": "The common interface for Model I/O objects that expose a human-readable name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MDLNamed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLNamed"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLNamed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MDLNamed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed/name",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property defined by this protocol is adopted by many classes in Model I/O. You can use this property to assign descriptive names to objects such as meshes, materials, cameras, and scattering functions to better keep track of the objects in your app. When you load objects from or export objects to a file using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, this property corresponds to the names and labels for objects that appear in popular 3D authoring tools.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight": {
      "abstract": [
        {
          "text": "A light source that illuminates a 3D scene from an area with a specific shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "role": "symbol",
      "title": "MDLAreaLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAsset": {
      "abstract": [
        {
          "text": "An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAsset"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAsset"
        }
      ],
      "role": "symbol",
      "title": "MDLAsset",
      "type": "topic",
      "url": "/documentation/modelio/mdlasset"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a 3D scene, along with a set of parameters describing an intended appearance for rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a checkerboard pattern with two specified colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCheckerboardTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCheckerboardTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLCheckerboardTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlcheckerboardtexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a gradient between two specified colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLColorSwatchTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLColorSwatchTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLColorSwatchTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlcolorswatchtexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLight": {
      "abstract": [
        {
          "text": "The abstract superclass for objects that describe light sources in a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLight"
        }
      ],
      "role": "symbol",
      "title": "MDLLight",
      "type": "topic",
      "url": "/documentation/modelio/mdllight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe": {
      "abstract": [
        {
          "text": "A light source described in terms of the variations in color and intensity of its illumination in all directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLightProbe"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightProbe"
        }
      ],
      "role": "symbol",
      "title": "MDLLightProbe",
      "type": "topic",
      "url": "/documentation/modelio/mdllightprobe"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial": {
      "abstract": [
        {
          "text": "A collection of material properties that together describe the intended surface appearance for rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterial",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterial"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty": {
      "abstract": [
        {
          "text": "A definition for one specific aspect of the rendering parameters for a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialProperty"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialProperty",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyConnection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyConnection"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyConnection",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertyconnection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyGraph"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyGraph"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyGraph",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertygraph"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyNode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyNode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyNode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertynode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNamed": {
      "abstract": [
        {
          "text": "The common interface for Model I/O objects that expose a human-readable name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "role": "symbol",
      "title": "MDLNamed",
      "type": "topic",
      "url": "/documentation/modelio/mdlnamed"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNamed/name": {
      "abstract": [
        {
          "text": "A descriptive name for the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/modelio/mdlnamed/name"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a field of random noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNoiseTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNoiseTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLNoiseTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlnoisetexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that computes a normal map from a supplied texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNormalMapTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNormalMapTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLNormalMapTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlnormalmaptexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLObject": {
      "abstract": [
        {
          "text": "The base class for objects that are part of a 3D asset, including meshes, cameras, and lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLObject"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLObject"
        }
      ],
      "role": "symbol",
      "title": "MDLObject",
      "type": "topic",
      "url": "/documentation/modelio/mdlobject"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPackedJointAnimation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPackedJointAnimation"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPackedJointAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPackedJointAnimation"
        }
      ],
      "role": "symbol",
      "title": "MDLPackedJointAnimation",
      "type": "topic",
      "url": "/documentation/modelio/mdlpackedjointanimation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight": {
      "abstract": [
        {
          "text": "A light source whose shape, direction, and intensity of illumination are determined by a photometric profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhotometricLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhotometricLight"
        }
      ],
      "role": "symbol",
      "title": "MDLPhotometricLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlphotometriclight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight": {
      "abstract": [
        {
          "text": "A light source for use in shading models based on real-world physics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleLight"
        }
      ],
      "role": "symbol",
      "title": "MDLPhysicallyPlausibleLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction": {
      "abstract": [
        {
          "text": "A set of material properties that describes a physically realistic shading model for materials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleScatteringFunction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleScatteringFunction"
        }
      ],
      "role": "symbol",
      "title": "MDLPhysicallyPlausibleScatteringFunction",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblescatteringfunction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction": {
      "abstract": [
        {
          "text": "A set of material properties that describes a basic shading model for materials, and the superclass for more complex shading models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLScatteringFunction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLScatteringFunction"
        }
      ],
      "role": "symbol",
      "title": "MDLScatteringFunction",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkeleton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSkeleton"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSkeleton"
        }
      ],
      "role": "symbol",
      "title": "MDLSkeleton",
      "type": "topic",
      "url": "/documentation/modelio/mdlskeleton"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates cube textures using a physically realistic simulation of the sunlit sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLSkyCubeTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a stereoscopic display of a 3D scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLStereoscopicCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLStereoscopicCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlstereoscopiccamera"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh": {
      "abstract": [
        {
          "text": "A container for index buffer data and material information to be used in rendering all or part of a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MDLSubmesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmeshTopology": {
      "abstract": [
        {
          "text": "A description of how a submesh’s index buffer data is arranged and how that arrangement should be used to produce the submesh’s intended 3D shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSubmeshTopology"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmeshTopology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSubmeshTopology"
        }
      ],
      "role": "symbol",
      "title": "MDLSubmeshTopology",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmeshtopology"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTexture": {
      "abstract": [
        {
          "text": "A source of texel data to be used in rendering material surface appearances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdltexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransform": {
      "abstract": [
        {
          "text": "A description of the local coordinate space transformations for a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransform"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransform"
        }
      ],
      "role": "symbol",
      "title": "MDLTransform",
      "type": "topic",
      "url": "/documentation/modelio/mdltransform"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture": {
      "abstract": [
        {
          "text": "A lightweight reference to a URL from which to load texture data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLURLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLURLTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLURLTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlurltexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray": {
      "abstract": [
        {
          "text": "A model of a 3D object’s solid volume as a collection of ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "voxels",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", or cubic units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVoxelArray"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVoxelArray"
        }
      ],
      "role": "symbol",
      "title": "MDLVoxelArray",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPackedJointAnimation",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkeleton",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLStereoscopicCamera",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "3D-Asset-Basics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAsset",
        "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransform",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmeshTopology"
      ],
      "title": "3D Asset Basics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Naming-an-Object",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLNamed/name"
      ],
      "title": "Naming an Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLNamed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Naming-an-Object",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLNamed/name"
              ],
              "title": "Naming an Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTexture"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "3D-Asset-Basics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLAsset",
                "doc://com.apple.modelio/documentation/ModelIO/MDLObject",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransform",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmeshTopology"
              ],
              "title": "3D Asset Basics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLNamed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/title",
          "value": "MDLSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/title",
          "value": "MDLMaterialPropertyConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/title",
          "value": "MDLPhysicallyPlausibleLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/title",
          "value": "MDLMaterialPropertyGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPackedJointAnimation/title",
          "value": "MDLPackedJointAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPackedJointAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPackedJointAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPackedJointAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPackedJointAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/title",
          "value": "MDLScatteringFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmeshTopology/title",
          "value": "MDLSubmeshTopology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmeshTopology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmeshTopology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmeshTopology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmeshTopology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/title",
          "value": "MDLLightProbe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/title",
          "value": "MDLTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkeleton/title",
          "value": "MDLSkeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/title",
          "value": "MDLSkyCubeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/title",
          "value": "MDLPhysicallyPlausibleScatteringFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/title",
          "value": "MDLColorSwatchTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLColorSwatchTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLColorSwatchTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/title",
          "value": "MDLMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title",
          "value": "MDLAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/title",
          "value": "MDLMaterialPropertyNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/title",
          "value": "MDLVoxelArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/title",
          "value": "MDLMaterialProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/title",
          "value": "MDLCheckerboardTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCheckerboardTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCheckerboardTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/title",
          "value": "MDLStereoscopicCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLStereoscopicCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLStereoscopicCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/title",
          "value": "MDLNoiseTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNoiseTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNoiseTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransform/title",
          "value": "MDLTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/title",
          "value": "MDLURLTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLURLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLURLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/title",
          "value": "MDLNormalMapTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNormalMapTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNormalMapTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/title",
          "value": "MDLAreaLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/title",
          "value": "MDLCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/title",
          "value": "MDLLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/title",
          "value": "MDLObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/title",
          "value": "MDLPhotometricLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhotometricLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhotometricLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/title",
          "value": "MDLNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlnamed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlnamed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
