{
  "abstract": [
    {
      "text": "A light source for use in shading models based on real-world physics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLPhysicallyPlausibleLight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLPhysicallyPlausibleLight"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLPhysicallyPlausibleLight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MDLPhysicallyPlausibleLight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight": {
      "abstract": [
        {
          "text": "A light source that illuminates a 3D scene from an area with a specific shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "role": "symbol",
      "title": "MDLAreaLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLight": {
      "abstract": [
        {
          "text": "The abstract superclass for objects that describe light sources in a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLight"
        }
      ],
      "role": "symbol",
      "title": "MDLLight",
      "type": "topic",
      "url": "/documentation/modelio/mdllight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe": {
      "abstract": [
        {
          "text": "A light source described in terms of the variations in color and intensity of its illumination in all directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLightProbe"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightProbe"
        }
      ],
      "role": "symbol",
      "title": "MDLLightProbe",
      "type": "topic",
      "url": "/documentation/modelio/mdllightprobe"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbeIrradianceDataSource": {
      "abstract": [
        {
          "text": "Adopt this protocol to provide information for use in automatic placement of light probes around a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLightProbeIrradianceDataSource"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbeIrradianceDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightProbeIrradianceDataSource"
        }
      ],
      "role": "symbol",
      "title": "MDLLightProbeIrradianceDataSource",
      "type": "topic",
      "url": "/documentation/modelio/mdllightprobeirradiancedatasource"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNamed": {
      "abstract": [
        {
          "text": "The common interface for Model I/O objects that expose a human-readable name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "role": "symbol",
      "title": "MDLNamed",
      "type": "topic",
      "url": "/documentation/modelio/mdlnamed"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight": {
      "abstract": [
        {
          "text": "A light source whose shape, direction, and intensity of illumination are determined by a photometric profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhotometricLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhotometricLight"
        }
      ],
      "role": "symbol",
      "title": "MDLPhotometricLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlphotometriclight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight": {
      "abstract": [
        {
          "text": "A light source for use in shading models based on real-world physics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleLight"
        }
      ],
      "role": "symbol",
      "title": "MDLPhysicallyPlausibleLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationEndDistance": {
      "abstract": [
        {
          "text": "The distance from the light source, in units of local coordinate space, at which its illumination becomes zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationEndDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationEndDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationEndDistance"
        }
      ],
      "role": "symbol",
      "title": "attenuationEndDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/attenuationenddistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationStartDistance": {
      "abstract": [
        {
          "text": "The distance from the light source, in units of local coordinate space, at which its illumination begins to diminish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationStartDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationStartDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationStartDistance"
        }
      ],
      "role": "symbol",
      "title": "attenuationStartDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/attenuationstartdistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/color": {
      "abstract": [
        {
          "text": "The color of the light source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/color"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/innerConeAngle": {
      "abstract": [
        {
          "text": "The radial angle, in degrees, of the area fully illuminated by the light.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "innerConeAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/innerConeAngle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "innerConeAngle"
        }
      ],
      "role": "symbol",
      "title": "innerConeAngle",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/innerconeangle"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/lumens": {
      "abstract": [
        {
          "text": "The total visible intensity of the light source, in lumens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lumens"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/lumens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lumens"
        }
      ],
      "role": "symbol",
      "title": "lumens",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/lumens"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/outerConeAngle": {
      "abstract": [
        {
          "text": "The radial angle, in degrees, at which the illumination from a spotlight becomes zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outerConeAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/outerConeAngle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outerConeAngle"
        }
      ],
      "role": "symbol",
      "title": "outerConeAngle",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/outerconeangle"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/setColorByTemperature(_:)": {
      "abstract": [
        {
          "text": "Sets the light’s color based on a black-body temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setColorByTemperature"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/setColorByTemperature(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setColorByTemperature:"
        }
      ],
      "role": "symbol",
      "title": "setColorByTemperature(_:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblelight/setcolorbytemperature(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLLight"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Lights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbeIrradianceDataSource",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight"
      ],
      "title": "Lights"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Light-Color-and-Intensity",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/color",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/lumens",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/setColorByTemperature(_:)"
      ],
      "title": "Managing Light Color and Intensity"
    },
    {
      "anchor": "Managing-Light-Geometry",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/innerConeAngle",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/outerConeAngle"
      ],
      "title": "Managing Light Geometry"
    },
    {
      "anchor": "Managing-Attenuation",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationStartDistance",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationEndDistance"
      ],
      "title": "Managing Attenuation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLPhysicallyPlausibleLight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Light-Color-and-Intensity",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/color",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/lumens",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/setColorByTemperature(_:)"
              ],
              "title": "Managing Light Color and Intensity"
            },
            {
              "anchor": "Managing-Light-Geometry",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/innerConeAngle",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/outerConeAngle"
              ],
              "title": "Managing Light Geometry"
            },
            {
              "anchor": "Managing-Attenuation",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationStartDistance",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleLight/attenuationEndDistance"
              ],
              "title": "Managing Attenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLLight"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Lights",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
                "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbe",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightProbeIrradianceDataSource",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhotometricLight"
              ],
              "title": "Lights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLPhysicallyPlausibleLight"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MDLLight",
                    "text": "MDLLight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/title",
          "value": "MDLLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1setColorByTemperature(_:)/title",
          "value": "setColorByTemperature:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1setColorByTemperature(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setColorByTemperature:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1attenuationStartDistance/title",
          "value": "attenuationStartDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1attenuationStartDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationStartDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/title",
          "value": "MDLPhysicallyPlausibleLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/title",
          "value": "MDLLightProbe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbe/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbeIrradianceDataSource/title",
          "value": "MDLLightProbeIrradianceDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbeIrradianceDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbeIrradianceDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightProbeIrradianceDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightProbeIrradianceDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1outerConeAngle/title",
          "value": "outerConeAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1outerConeAngle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outerConeAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1innerConeAngle/title",
          "value": "innerConeAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1innerConeAngle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "innerConeAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/title",
          "value": "MDLPhotometricLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhotometricLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhotometricLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhotometricLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/title",
          "value": "MDLAreaLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/title",
          "value": "MDLNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1lumens/title",
          "value": "lumens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1lumens/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lumens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1attenuationEndDistance/title",
          "value": "attenuationEndDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleLight~1attenuationEndDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationEndDistance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlphysicallyplausiblelight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlphysicallyplausiblelight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
