{
  "abstract": [
    {
      "text": "A set of material properties that describes a basic shading model for materials, and the superclass for more complex shading models.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLScatteringFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLScatteringFunction"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLScatteringFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MDLScatteringFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The set of material properties that define a material’s response to lighting is also called the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Bidirectional Reflectance Distribution Function",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", or BRDF, for surfaces shaded using that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The set of properties defined by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class itself describes a Lambertian shading model with Blinn-Phong specular response; subclasses can define a set of properties for other shading models.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Creating a new scattering function object with the inherited ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method creates a set of material properties with useful default values for this shading model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init": {
      "abstract": [
        {
          "text": "Implemented by subclasses to initialize a new object (the receiver) immediately after memory for it has been allocated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1418641-init"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial": {
      "abstract": [
        {
          "text": "A collection of material properties that together describe the intended surface appearance for rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterial",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterial"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty": {
      "abstract": [
        {
          "text": "A definition for one specific aspect of the rendering parameters for a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialProperty"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialProperty",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyConnection"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyConnection"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyConnection",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertyconnection"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyGraph"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyGraph"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyGraph",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertygraph"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyNode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyNode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyNode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertynode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNamed": {
      "abstract": [
        {
          "text": "The common interface for Model I/O objects that expose a human-readable name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNamed"
        }
      ],
      "role": "symbol",
      "title": "MDLNamed",
      "type": "topic",
      "url": "/documentation/modelio/mdlnamed"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction": {
      "abstract": [
        {
          "text": "A set of material properties that describes a physically realistic shading model for materials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleScatteringFunction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLPhysicallyPlausibleScatteringFunction"
        }
      ],
      "role": "symbol",
      "title": "MDLPhysicallyPlausibleScatteringFunction",
      "type": "topic",
      "url": "/documentation/modelio/mdlphysicallyplausiblescatteringfunction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction": {
      "abstract": [
        {
          "text": "A set of material properties that describes a basic shading model for materials, and the superclass for more complex shading models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLScatteringFunction"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLScatteringFunction"
        }
      ],
      "role": "symbol",
      "title": "MDLScatteringFunction",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusion": {
      "abstract": [
        {
          "text": "The attenuation of ambient light due to local geometry variations on a surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientOcclusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ambientOcclusion"
        }
      ],
      "role": "symbol",
      "title": "ambientOcclusion",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/ambientocclusion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusionScale": {
      "abstract": [
        {
          "text": "The scaling factor for ambient occlusion shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientOcclusionScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusionScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ambientOcclusionScale"
        }
      ],
      "role": "symbol",
      "title": "ambientOcclusionScale",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/ambientocclusionscale"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/baseColor": {
      "abstract": [
        {
          "text": "The inherent color of the material, to be used as a modulator during shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/baseColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseColor"
        }
      ],
      "role": "symbol",
      "title": "baseColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/basecolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/emission": {
      "abstract": [
        {
          "text": "The color emitted as radiance from a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emission"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/emission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emission"
        }
      ],
      "role": "symbol",
      "title": "emission",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/emission"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/interfaceIndexOfRefraction": {
      "abstract": [
        {
          "text": "The index of refraction for a material itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceIndexOfRefraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/interfaceIndexOfRefraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceIndexOfRefraction"
        }
      ],
      "role": "symbol",
      "title": "interfaceIndexOfRefraction",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/interfaceindexofrefraction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/materialIndexOfRefraction": {
      "abstract": [
        {
          "text": "The index of refraction for the medium surrounding a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "materialIndexOfRefraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/materialIndexOfRefraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "materialIndexOfRefraction"
        }
      ],
      "role": "symbol",
      "title": "materialIndexOfRefraction",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/materialindexofrefraction"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/name": {
      "abstract": [
        {
          "text": "A descriptive name for the scattering function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/name"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/normal": {
      "abstract": [
        {
          "text": "The variation in the surface normal vectors in a material, relative to model coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "role": "symbol",
      "title": "normal",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/normal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/specular": {
      "abstract": [
        {
          "text": "The intensity of specular highlights on the material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterialProperty",
          "text": "MDLMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/specular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "specular"
        }
      ],
      "role": "symbol",
      "title": "specular",
      "type": "topic",
      "url": "/documentation/modelio/mdlscatteringfunction/specular"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNamed",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Materials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction"
      ],
      "title": "Materials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Naming-a-Scattering-Function",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/name"
      ],
      "title": "Naming a Scattering Function"
    },
    {
      "anchor": "Working-with-Shading-Properties",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/baseColor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/emission",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/specular",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/materialIndexOfRefraction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/interfaceIndexOfRefraction",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/normal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusionScale"
      ],
      "title": "Working with Shading Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLScatteringFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Naming-a-Scattering-Function",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/name"
              ],
              "title": "Naming a Scattering Function"
            },
            {
              "anchor": "Working-with-Shading-Properties",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/baseColor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/emission",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/specular",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/materialIndexOfRefraction",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/interfaceIndexOfRefraction",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/normal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLScatteringFunction/ambientOcclusionScale"
              ],
              "title": "Working with Shading Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLNamed"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Materials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLPhysicallyPlausibleScatteringFunction"
              ],
              "title": "Materials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLScatteringFunction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/title",
          "value": "MDLPhysicallyPlausibleScatteringFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLPhysicallyPlausibleScatteringFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLPhysicallyPlausibleScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1normal/title",
          "value": "normal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1ambientOcclusion/title",
          "value": "ambientOcclusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1ambientOcclusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ambientOcclusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/title",
          "value": "MDLMaterialPropertyNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1baseColor/title",
          "value": "baseColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1baseColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "baseColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/title",
          "value": "MDLScatteringFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLScatteringFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/title",
          "value": "MDLMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11418641-init/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/title",
          "value": "MDLMaterialProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/title",
          "value": "MDLMaterialPropertyGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1ambientOcclusionScale/title",
          "value": "ambientOcclusionScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1ambientOcclusionScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ambientOcclusionScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1interfaceIndexOfRefraction/title",
          "value": "interfaceIndexOfRefraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1interfaceIndexOfRefraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interfaceIndexOfRefraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/title",
          "value": "MDLNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1emission/title",
          "value": "emission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1emission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1specular/title",
          "value": "specular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1specular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "specular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/title",
          "value": "MDLMaterialPropertyConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1materialIndexOfRefraction/title",
          "value": "materialIndexOfRefraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLScatteringFunction~1materialIndexOfRefraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "materialIndexOfRefraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlscatteringfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlscatteringfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
