{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MDLTransformOp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLTransformOp"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLTransformOp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MDLTransformOp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLTransformOp"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformMatrixOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformMatrixOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformMatrixOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformMatrixOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformMatrixOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformmatrixop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/double4x4(atTime:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_double4x4",
          "text": "matrix_double4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/double4x4(atTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double4x4AtTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "double4x4(atTime:)",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformop/double4x4(attime:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/float4x4(atTime:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float4x4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/float4x4(atTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "float4x4AtTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "float4x4(atTime:)",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformop/float4x4(attime:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/isInverseOp()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInverseOp"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/isInverseOp()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IsInverseOp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isInverseOp()",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformop/isinverseop()"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformop/name"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOrientOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformOrientOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOrientOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformOrientOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformOrientOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformorientop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformRotateOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformRotateOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformRotateOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformrotateop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateXOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformRotateXOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateXOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformRotateXOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformRotateXOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformrotatexop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateYOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformRotateYOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateYOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformRotateYOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformRotateYOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformrotateyop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateZOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformRotateZOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateZOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformRotateZOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformRotateZOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformrotatezop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformScaleOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformScaleOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformScaleOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformScaleOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformScaleOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformscaleop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTransformTranslateOp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTransformTranslateOp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTransformTranslateOp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTransformTranslateOp"
        }
      ],
      "role": "symbol",
      "title": "MDLTransformTranslateOp",
      "type": "topic",
      "url": "/documentation/modelio/mdltransformtranslateop"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformMatrixOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOrientOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateXOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateYOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateZOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformScaleOp",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformTranslateOp"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/name"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/double4x4(atTime:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/float4x4(atTime:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/isInverseOp()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLTransformOp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/name"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/double4x4(atTime:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/float4x4(atTime:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOp/isInverseOp()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformMatrixOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformOrientOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateXOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateYOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformRotateZOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformScaleOp",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTransformTranslateOp"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLTransformOp"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp/title",
          "value": "MDLTransformOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1isInverseOp()/title",
          "value": "IsInverseOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1isInverseOp()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "IsInverseOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateZOp/title",
          "value": "MDLTransformRotateZOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateZOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateZOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateZOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateZOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformTranslateOp/title",
          "value": "MDLTransformTranslateOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformTranslateOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformTranslateOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformTranslateOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformTranslateOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1float4x4(atTime:)/title",
          "value": "float4x4AtTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1float4x4(atTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "float4x4AtTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformScaleOp/title",
          "value": "MDLTransformScaleOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformScaleOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformScaleOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformScaleOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformScaleOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateOp/title",
          "value": "MDLTransformRotateOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateXOp/title",
          "value": "MDLTransformRotateXOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateXOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateXOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateXOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateXOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateYOp/title",
          "value": "MDLTransformRotateYOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateYOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateYOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformRotateYOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformRotateYOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOrientOp/title",
          "value": "MDLTransformOrientOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOrientOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOrientOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOrientOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformOrientOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1double4x4(atTime:)/title",
          "value": "double4x4AtTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformOp~1double4x4(atTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "double4x4AtTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformMatrixOp/title",
          "value": "MDLTransformMatrixOp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformMatrixOp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformMatrixOp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTransformMatrixOp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTransformMatrixOp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdltransformop"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdltransformop"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
