{
  "abstract": [
    {
      "text": "A description of filtering modes for a renderer to use when sampling from a texture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLTextureFilter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLTextureFilter"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLTextureFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MDLTextureFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLTextureFilter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A texture filter, together with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and transform information, form a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which describes a texture and its rendering parameters for use in rendering one aspect of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s surface appearance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a checkerboard pattern with two specified colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCheckerboardTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCheckerboardTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLCheckerboardTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlcheckerboardtexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a gradient between two specified colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLColorSwatchTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLColorSwatchTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLColorSwatchTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlcolorswatchtexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial": {
      "abstract": [
        {
          "text": "A collection of material properties that together describe the intended surface appearance for rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterial",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterial"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at sizes between mipmap levels, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialMipMapFilterMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialmipmapfiltermode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at coordinates between texels, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureFilterMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturefiltermode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at coordinates outside the texture bounds, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates a field of random noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNoiseTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNoiseTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLNoiseTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlnoisetexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that computes a normal map from a supplied texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLNormalMapTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLNormalMapTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLNormalMapTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlnormalmaptexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates cube textures using a physically realistic simulation of the sunlit sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLSkyCubeTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTexture": {
      "abstract": [
        {
          "text": "A source of texel data to be used in rendering material surface appearances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdltexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter": {
      "abstract": [
        {
          "text": "A description of filtering modes for a renderer to use when sampling from a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTextureFilter"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTextureFilter"
        }
      ],
      "role": "symbol",
      "title": "MDLTextureFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures at sizes larger than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureFilterMode",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magFilter"
        }
      ],
      "role": "symbol",
      "title": "magFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/magfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures at sizes smaller than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureFilterMode",
          "text": "MDLMaterialTextureFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minFilter"
        }
      ],
      "role": "symbol",
      "title": "minFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/minfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter": {
      "abstract": [
        {
          "text": "The filter mode for rendering textures using mipmapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialMipMapFilterMode",
          "text": "MDLMaterialMipMapFilterMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mipFilter"
        }
      ],
      "role": "symbol",
      "title": "mipFilter",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/mipfilter"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture r-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rWrapMode"
        }
      ],
      "role": "symbol",
      "title": "rWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/rwrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sWrapMode"
        }
      ],
      "role": "symbol",
      "title": "sWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/swrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tWrapMode"
        }
      ],
      "role": "symbol",
      "title": "tWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/twrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler": {
      "abstract": [
        {
          "text": "An object that pairs a source of texture data with sampling parameters to be used in rendering the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTextureSampler"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTextureSampler"
        }
      ],
      "role": "symbol",
      "title": "MDLTextureSampler",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturesampler"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture": {
      "abstract": [
        {
          "text": "A lightweight reference to a URL from which to load texture data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLURLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLURLTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLURLTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlurltexture"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Textures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler"
      ],
      "title": "Textures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Texture-Coordinate-Wrap-Modes",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode"
      ],
      "title": "Managing Texture Coordinate Wrap Modes"
    },
    {
      "anchor": "Managing-Texture-Filter-Modes",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
        "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter"
      ],
      "title": "Managing Texture Filter Modes"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLTextureFilter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Texture-Coordinate-Wrap-Modes",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode"
              ],
              "title": "Managing Texture Coordinate Wrap Modes"
            },
            {
              "anchor": "Managing-Texture-Filter-Modes",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/minFilter",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/magFilter",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/mipFilter"
              ],
              "title": "Managing Texture Filter Modes"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureFilterMode",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialMipMapFilterMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Textures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLColorSwatchTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLNoiseTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLNormalMapTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLURLTexture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler"
              ],
              "title": "Textures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLTextureFilter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/title",
          "value": "MDLMaterialTextureFilterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureFilterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/title",
          "value": "MDLNormalMapTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNormalMapTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNormalMapTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNormalMapTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1mipFilter/title",
          "value": "mipFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1mipFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/title",
          "value": "MDLMaterialTextureWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/title",
          "value": "MDLNoiseTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNoiseTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLNoiseTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLNoiseTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/title",
          "value": "MDLSkyCubeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/title",
          "value": "rWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1minFilter/title",
          "value": "minFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1minFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/title",
          "value": "MDLTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/title",
          "value": "tWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/title",
          "value": "MDLURLTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLURLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLURLTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLURLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/title",
          "value": "MDLMaterialMipMapFilterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialMipMapFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialMipMapFilterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialMipMapFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/title",
          "value": "MDLCheckerboardTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCheckerboardTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCheckerboardTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/title",
          "value": "MDLMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/title",
          "value": "sWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/title",
          "value": "MDLTextureSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/title",
          "value": "MDLColorSwatchTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLColorSwatchTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLColorSwatchTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLColorSwatchTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter/title",
          "value": "MDLTextureFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1magFilter/title",
          "value": "magFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1magFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdltexturefilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdltexturefilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
