{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object describes layout information for a vertex buffer in a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object. A collection of vertex layer objects, vertex attribute objects, and additional information forms a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object, which completely describes the layout of vertex buffers for a mesh.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLVertexBufferLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MDLVertexBufferLayout"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLVertexBufferLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MDLVertexBufferLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLVertexBufferLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A collection of vertex layout objects, vertex attribute objects, and additional information forms a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which completely describes the layout of vertex buffers for a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A mesh may store vertex data in either a structure of arrays model, where data for each vertex attribute (such as vertex position or surface normal) lies in a separate vertex buffer, or in an array of structures model, where multiple vertex attributes share the same buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In a structure of arrays, the mesh’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " array contains several ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects, and the mesh’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object contains a separate ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object for each buffer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In an array of structures, the mesh contains a single vertex buffer, and its descriptor contains a single vertex buffer layout object. To identify which bytes in the buffer refer to which vertices and vertex attributes, use the layout’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/stride",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " together with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties of the descriptor’s vertex attributes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Because there is only one stride per buffer:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If a buffer uses interleaved layout, it can contain attributes of different sizes, and the stride is the sum of their sizes (plus padding).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If a buffer uses non-interleaved layout (that is, it stores all the data for one attribute, then all the data for another, and so on), each attribute in the buffer must have the same size as the others.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers": {
      "abstract": [
        {
          "text": "The array of buffers that provide vertex data for the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexBuffers"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
          "text": "MDLMeshBuffer"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexBuffers"
        }
      ],
      "role": "symbol",
      "title": "vertexBuffers",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexbuffers"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor": {
      "abstract": [
        {
          "text": "A description of the format and layout of the mesh’s vertex buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexDescriptor"
        }
      ],
      "role": "symbol",
      "title": "vertexDescriptor",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexdescriptor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer": {
      "abstract": [
        {
          "text": "The general interface for managing storage of vertex and index data used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBuffer",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffer"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator": {
      "abstract": [
        {
          "text": "The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferallocator"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferData": {
      "abstract": [
        {
          "text": "A memory buffer that stores vertex or index data for a Model I/O mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferData"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferData"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferData",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferdata"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferDataAllocator": {
      "abstract": [
        {
          "text": "A basic allocator implementation that allocates from main memory using data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferDataAllocator"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferDataAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferDataAllocator"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferDataAllocator",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferdataallocator"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferMap": {
      "abstract": [
        {
          "text": "An object that manages access to a memory buffer used for the data storage of a Model I/O mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferMap"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferMap"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferMap",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffermap"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone": {
      "abstract": [
        {
          "text": "The general interface for logical pools of memory used in allocation of related mesh data buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferZone"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferZone"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferZone",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferzone"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZoneDefault": {
      "abstract": [
        {
          "text": "A standard implementation of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferZoneDefault"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZoneDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBufferZoneDefault"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBufferZoneDefault",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbufferzonedefault"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute": {
      "abstract": [
        {
          "text": "A description of the format of per-vertex data for a single vertex attribute in a mesh object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttribute"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttribute"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttribute",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format": {
      "abstract": [
        {
          "text": "The format of per-vertex data for the attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "format"
        }
      ],
      "role": "symbol",
      "title": "format",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/format"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset": {
      "abstract": [
        {
          "text": "The offset, in bytes, of vertex data for the attribute in a vertex buffer, relative to the start of data for each vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/offset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offset"
        }
      ],
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/offset"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeData": {
      "abstract": [
        {
          "text": "An object that provides convenience access to vertex data for a specific vertex attribute of a mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeData"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeData"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeData",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributedata"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object describes layout information for a vertex buffer in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. A collection of vertex layer objects, vertex attribute objects, and additional information forms a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object, which completely describes the layout of vertex buffers for a mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexBufferLayout"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexBufferLayout"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexBufferLayout",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexbufferlayout"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/init(stride:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/init(stride:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStride:"
        }
      ],
      "role": "symbol",
      "title": "init(stride:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexbufferlayout/init(stride:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/stride": {
      "abstract": [
        {
          "text": "The stride, in bytes, between data for separate vertices in a vertex buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stride"
        }
      ],
      "role": "symbol",
      "title": "stride",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexbufferlayout/stride"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor": {
      "abstract": [
        {
          "text": "A description of the structure, format, and layout for vertex data buffers associated with a mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexDescriptor",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexdescriptor"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Mesh-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferData",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferDataAllocator",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferMap",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZoneDefault",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeData",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor"
      ],
      "title": "Managing Mesh Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Working-with-Layout-Information",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/stride"
      ],
      "title": "Working with Layout Information"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/init(stride:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLVertexBufferLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexBufferLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexBufferLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Working-with-Layout-Information",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/stride"
              ],
              "title": "Working with Layout Information"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexBufferLayout/init(stride:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Mesh-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferData",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferDataAllocator",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferMap",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZoneDefault",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeData",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexDescriptor"
              ],
              "title": "Managing Mesh Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MDLVertexBufferLayout"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/title",
          "value": "MDLMeshBufferZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZoneDefault/title",
          "value": "MDLMeshBufferZoneDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZoneDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferZoneDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZoneDefault/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferZoneDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferMap/title",
          "value": "MDLMeshBufferMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/title",
          "value": "MDLMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout~1stride/title",
          "value": "stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout~1stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferData/title",
          "value": "MDLMeshBufferData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeData/title",
          "value": "MDLVertexAttributeData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexDescriptor/title",
          "value": "vertexDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1offset/title",
          "value": "offset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1offset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/title",
          "value": "vertexBuffers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexBuffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/title",
          "value": "MDLVertexAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/title",
          "value": "MDLMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/title",
          "value": "format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferDataAllocator/title",
          "value": "MDLMeshBufferDataAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferDataAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferDataAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferDataAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBufferDataAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout/title",
          "value": "MDLVertexBufferLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexBufferLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexBufferLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexDescriptor/title",
          "value": "MDLVertexDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout~1init(stride:)/title",
          "value": "initWithStride:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexBufferLayout~1init(stride:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStride:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlvertexbufferlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlvertexbufferlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
