{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Model I/O Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy": {
      "abstract": [
        {
          "text": "The attribute data describes the degree to which a surface’s appearance changes in appearance when rotated about its normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeAnisotropy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeAnisotropy"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeAnisotropy",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeanisotropy"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal": {
      "abstract": [
        {
          "text": "The attribute data describes surface binormal vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBinormal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBinormal"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeBinormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributebinormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent": {
      "abstract": [
        {
          "text": "The attribute data describes surface bitangent vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBitangent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBitangent"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeBitangent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributebitangent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor": {
      "abstract": [
        {
          "text": "The attribute data describes vertex colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeColor"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributecolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease": {
      "abstract": [
        {
          "text": "The attribute data describes edges that should be left unmodified by surface subdivision operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeEdgeCrease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeEdgeCrease"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeEdgeCrease",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeedgecrease"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices": {
      "abstract": [
        {
          "text": "The attribute data describes the indices of bones or joints in a skeletal animation rig.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointIndices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointIndices"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeJointIndices",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributejointindices"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights": {
      "abstract": [
        {
          "text": "The attribute data describes the influence factors of bones or joints on a vertex’s position for use in skeletal animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointWeights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointWeights"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeJointWeights",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributejointweights"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal": {
      "abstract": [
        {
          "text": "The attribute data describes surface normal vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeNormal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeNormal"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeNormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributenormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue": {
      "abstract": [
        {
          "text": "The attribute data describes per-vertex ambient occlusion values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeOcclusionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeOcclusionValue"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeOcclusionValue",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeocclusionvalue"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition": {
      "abstract": [
        {
          "text": "The attribute data describes vertex positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributePosition",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeposition"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU": {
      "abstract": [
        {
          "text": "The attribute data describes the U component of a vector basis for use in shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisU"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeShadingBasisU",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeshadingbasisu"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV": {
      "abstract": [
        {
          "text": "The attribute data describes the V component of a vector basis for use in shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisV"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeShadingBasisV",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeshadingbasisv"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil": {
      "abstract": [
        {
          "text": "The attribute data describes which neighboring vertices influence the effect of surface subdivision on the area around a vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeSubdivisionStencil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeSubdivisionStencil"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeSubdivisionStencil",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributesubdivisionstencil"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent": {
      "abstract": [
        {
          "text": "The attribute data describes surface tangent vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTangent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTangent"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeTangent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributetangent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate": {
      "abstract": [
        {
          "text": "The attribute data describes texture coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTextureCoordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTextureCoordinate"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeTextureCoordinate",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributetexturecoordinate"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject": {
      "abstract": [
        {
          "text": "The Object file format (common extension ",
          "type": "text"
        },
        {
          "code": ".obj",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTType3dObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTType3dObject"
        }
      ],
      "role": "symbol",
      "title": "kUTType3dObject",
      "type": "topic",
      "url": "/documentation/modelio/kuttype3dobject"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic": {
      "abstract": [
        {
          "text": "The Alembic file format (common extension ",
          "type": "text"
        },
        {
          "code": ".abc",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeAlembic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeAlembic"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeAlembic",
      "type": "topic",
      "url": "/documentation/modelio/kuttypealembic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon": {
      "abstract": [
        {
          "text": "The Polygon file format (common extension ",
          "type": "text"
        },
        {
          "code": ".ply",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypePolygon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypePolygon"
        }
      ],
      "role": "symbol",
      "title": "kUTTypePolygon",
      "type": "topic",
      "url": "/documentation/modelio/kuttypepolygon"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography": {
      "abstract": [
        {
          "text": "The Stereolithography file format (common extension ",
          "type": "text"
        },
        {
          "code": ".stl",
          "type": "codeVoice"
        },
        {
          "text": "), also known as the Standard Tessellated Geometry format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeStereolithography"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeStereolithography"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeStereolithography",
      "type": "topic",
      "url": "/documentation/modelio/kuttypestereolithography"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription": {
      "abstract": [
        {
          "text": "The Universal Scene Description file format (common extension ",
          "type": "text"
        },
        {
          "code": ".usd",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescription"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeUniversalSceneDescription",
      "type": "topic",
      "url": "/documentation/modelio/kuttypeuniversalscenedescription"
    },
    "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescriptionMobile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescriptionMobile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescriptionMobile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUTTypeUniversalSceneDescriptionMobile"
        }
      ],
      "role": "symbol",
      "title": "kUTTypeUniversalSceneDescriptionMobile",
      "type": "topic",
      "url": "/documentation/modelio/kuttypeuniversalscenedescriptionmobile"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Data Types",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-data-types"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Enumerations",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-enumerations"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Structures",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-structures",
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate",
        "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription",
        "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescriptionMobile"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate",
                "doc://com.apple.modelio/documentation/ModelIO/kUTType3dObject",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeAlembic",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypePolygon",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeStereolithography",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescription",
                "doc://com.apple.modelio/documentation/ModelIO/kUTTypeUniversalSceneDescriptionMobile"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-structures",
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeAlembic/title",
          "value": "kUTTypeAlembic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeAlembic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeAlembic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescriptionMobile/title",
          "value": "kUTTypeUniversalSceneDescriptionMobile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescriptionMobile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeUniversalSceneDescriptionMobile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBitangent/title",
          "value": "MDLVertexAttributeBitangent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBitangent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeBitangent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeNormal/title",
          "value": "MDLVertexAttributeNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeNormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTType3dObject/title",
          "value": "kUTType3dObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTType3dObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTType3dObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeEdgeCrease/title",
          "value": "MDLVertexAttributeEdgeCrease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeEdgeCrease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeEdgeCrease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeOcclusionValue/title",
          "value": "MDLVertexAttributeOcclusionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeOcclusionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeOcclusionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeSubdivisionStencil/title",
          "value": "MDLVertexAttributeSubdivisionStencil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeSubdivisionStencil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeSubdivisionStencil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBinormal/title",
          "value": "MDLVertexAttributeBinormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBinormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeBinormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTangent/title",
          "value": "MDLVertexAttributeTangent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTangent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeTangent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypePolygon/title",
          "value": "kUTTypePolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypePolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypePolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeAnisotropy/title",
          "value": "MDLVertexAttributeAnisotropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeAnisotropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeAnisotropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescription/title",
          "value": "kUTTypeUniversalSceneDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeUniversalSceneDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeUniversalSceneDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointIndices/title",
          "value": "MDLVertexAttributeJointIndices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointIndices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeJointIndices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeColor/title",
          "value": "MDLVertexAttributeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeStereolithography/title",
          "value": "kUTTypeStereolithography"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1kUTTypeStereolithography/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUTTypeStereolithography"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointWeights/title",
          "value": "MDLVertexAttributeJointWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeJointWeights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTextureCoordinate/title",
          "value": "MDLVertexAttributeTextureCoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTextureCoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeTextureCoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/title",
          "value": "MDLVertexAttributePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisV/title",
          "value": "MDLVertexAttributeShadingBasisV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeShadingBasisV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisU/title",
          "value": "MDLVertexAttributeShadingBasisU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeShadingBasisU"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/model-i-o-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/model-i-o-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
