{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Model I/O Structures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent": {
      "abstract": [
        {
          "text": "The indexes that define the corners of the three-dimensional voxel grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxelIndexExtent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLVoxelIndexExtent",
          "text": "MDLVoxelIndexExtent"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelIndexExtent"
        }
      ],
      "role": "symbol",
      "title": "voxelIndexExtent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxelindexextent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)": {
      "abstract": [
        {
          "text": "Returns a data object containing all voxels within the specified volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "within"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLVoxelIndexExtent",
          "text": "MDLVoxelIndexExtent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelsWithinExtent:"
        }
      ],
      "role": "symbol",
      "title": "voxels(within:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxels(within:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndexExtent": {
      "abstract": [
        {
          "text": "The corner voxel indices defining a solid rectangular volume of voxels. Used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVoxelIndexExtent"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndexExtent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVoxelIndexExtent"
        }
      ],
      "role": "symbol",
      "title": "MDLVoxelIndexExtent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelindexextent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Constants",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-constants"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Data Types",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-data-types"
    },
    "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model I/O Enumerations",
      "type": "topic",
      "url": "/documentation/modelio/model-i-o-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations",
        "doc://com.apple.modelio/documentation/ModelIO/model-i-o-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndexExtent"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndexExtent"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-data-types",
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-enumerations",
                "doc://com.apple.modelio/documentation/ModelIO/model-i-o-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxels(within:)/title",
          "value": "voxelsWithinExtent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxels(within:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "voxelsWithinExtent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndexExtent/title",
          "value": "voxelIndexExtent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndexExtent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voxelIndexExtent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndexExtent/title",
          "value": "MDLVoxelIndexExtent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndexExtent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelIndexExtent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndexExtent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelIndexExtent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/model-i-o-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/model-i-o-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
