{
  "abstract": [
    {
      "text": "Names that identify semantic uses for vertex attribute data, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/vertex-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Vertex Attributes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Model I/O  automatically uses these names to identify vertex attribute data loaded from an asset when the asset does not already use its own custom names for vertex attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some mesh operations require that an attribute with a specific name be present in the mesh. For example, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addNormals(withAttributeNamed:creaseThreshold:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method requires an attribute with the name ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addNormals(withAttributeNamed:creaseThreshold:)": {
      "abstract": [
        {
          "text": "Generates surface normal data for the mesh based on its vertex position data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addNormals"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "creaseThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addNormals(withAttributeNamed:creaseThreshold:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addNormalsWithAttributeNamed:creaseThreshold:"
        }
      ],
      "role": "symbol",
      "title": "addNormals(withAttributeNamed:creaseThreshold:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/addnormals(withattributenamed:creasethreshold:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute": {
      "abstract": [
        {
          "text": "A description of the format of per-vertex data for a single vertex attribute in a mesh object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttribute"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttribute"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttribute",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format": {
      "abstract": [
        {
          "text": "The format of per-vertex data for the attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "format"
        }
      ],
      "role": "symbol",
      "title": "format",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/format"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name": {
      "abstract": [
        {
          "text": "An identifier for the semantic use of the vertex attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/name"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy": {
      "abstract": [
        {
          "text": "The attribute data describes the degree to which a surface’s appearance changes in appearance when rotated about its normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeAnisotropy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeAnisotropy"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeAnisotropy",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeanisotropy"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal": {
      "abstract": [
        {
          "text": "The attribute data describes surface binormal vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBinormal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBinormal"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeBinormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributebinormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent": {
      "abstract": [
        {
          "text": "The attribute data describes surface bitangent vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBitangent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeBitangent"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeBitangent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributebitangent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor": {
      "abstract": [
        {
          "text": "The attribute data describes vertex colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeColor"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributecolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease": {
      "abstract": [
        {
          "text": "The attribute data describes edges that should be left unmodified by surface subdivision operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeEdgeCrease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeEdgeCrease"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeEdgeCrease",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeedgecrease"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices": {
      "abstract": [
        {
          "text": "The attribute data describes the indices of bones or joints in a skeletal animation rig.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointIndices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointIndices"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeJointIndices",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributejointindices"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights": {
      "abstract": [
        {
          "text": "The attribute data describes the influence factors of bones or joints on a vertex’s position for use in skeletal animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointWeights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeJointWeights"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeJointWeights",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributejointweights"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal": {
      "abstract": [
        {
          "text": "The attribute data describes surface normal vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeNormal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeNormal"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeNormal",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributenormal"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue": {
      "abstract": [
        {
          "text": "The attribute data describes per-vertex ambient occlusion values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeOcclusionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeOcclusionValue"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeOcclusionValue",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeocclusionvalue"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition": {
      "abstract": [
        {
          "text": "The attribute data describes vertex positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributePosition",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeposition"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU": {
      "abstract": [
        {
          "text": "The attribute data describes the U component of a vector basis for use in shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisU"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeShadingBasisU",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeshadingbasisu"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV": {
      "abstract": [
        {
          "text": "The attribute data describes the V component of a vector basis for use in shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeShadingBasisV"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeShadingBasisV",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeshadingbasisv"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil": {
      "abstract": [
        {
          "text": "The attribute data describes which neighboring vertices influence the effect of surface subdivision on the area around a vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeSubdivisionStencil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeSubdivisionStencil"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeSubdivisionStencil",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributesubdivisionstencil"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent": {
      "abstract": [
        {
          "text": "The attribute data describes surface tangent vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTangent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTangent"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeTangent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributetangent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate": {
      "abstract": [
        {
          "text": "The attribute data describes texture coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTextureCoordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributeTextureCoordinate"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributeTextureCoordinate",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributetexturecoordinate"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat": {
      "abstract": [
        {
          "text": "Descriptions of the data size and layout for a vertex attribute, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeAnisotropy",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBinormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeBitangent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeColor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeEdgeCrease",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointIndices",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeJointWeights",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeNormal",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeOcclusionValue",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisU",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeShadingBasisV",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeSubdivisionStencil",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTangent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributeTextureCoordinate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeOcclusionValue/title",
          "value": "MDLVertexAttributeOcclusionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeOcclusionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeOcclusionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTextureCoordinate/title",
          "value": "MDLVertexAttributeTextureCoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTextureCoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeTextureCoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBitangent/title",
          "value": "MDLVertexAttributeBitangent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBitangent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeBitangent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeNormal/title",
          "value": "MDLVertexAttributeNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeNormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeAnisotropy/title",
          "value": "MDLVertexAttributeAnisotropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeAnisotropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeAnisotropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/title",
          "value": "MDLVertexAttributePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addNormals(withAttributeNamed:creaseThreshold:)/title",
          "value": "addNormalsWithAttributeNamed:creaseThreshold:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addNormals(withAttributeNamed:creaseThreshold:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addNormalsWithAttributeNamed:creaseThreshold:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/title",
          "value": "format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeEdgeCrease/title",
          "value": "MDLVertexAttributeEdgeCrease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeEdgeCrease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeEdgeCrease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisV/title",
          "value": "MDLVertexAttributeShadingBasisV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeShadingBasisV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBinormal/title",
          "value": "MDLVertexAttributeBinormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeBinormal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeBinormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisU/title",
          "value": "MDLVertexAttributeShadingBasisU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeShadingBasisU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeShadingBasisU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointIndices/title",
          "value": "MDLVertexAttributeJointIndices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointIndices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeJointIndices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeSubdivisionStencil/title",
          "value": "MDLVertexAttributeSubdivisionStencil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeSubdivisionStencil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeSubdivisionStencil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointWeights/title",
          "value": "MDLVertexAttributeJointWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeJointWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeJointWeights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeColor/title",
          "value": "MDLVertexAttributeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/title",
          "value": "MDLVertexAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/title",
          "value": "MDLVertexFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTangent/title",
          "value": "MDLVertexAttributeTangent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributeTangent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributeTangent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/vertex-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/vertex-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
