{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/common-security-services-manager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/1434848-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_INTEGRITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_ACL_AUTHORIZATION_INTEGRITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_INTEGRITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_ACL_AUTHORIZATION_INTEGRITY"
        }
      ],
      "role": "symbol",
      "title": "CSSM_ACL_AUTHORIZATION_INTEGRITY",
      "type": "topic",
      "url": "/documentation/security/cssm_acl_authorization_integrity"
    },
    "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_PARTITION_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_ACL_AUTHORIZATION_PARTITION_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_PARTITION_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_ACL_AUTHORIZATION_PARTITION_ID"
        }
      ],
      "role": "symbol",
      "title": "CSSM_ACL_AUTHORIZATION_PARTITION_ID",
      "type": "topic",
      "url": "/documentation/security/cssm_acl_authorization_partition_id"
    },
    "doc://com.apple.security/documentation/Security/common-security-services-manager": {
      "abstract": [
        {
          "text": "A set of open source modules underpinning the legacy implementation of the Security framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/common-security-services-manager",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Security Services Manager",
      "type": "topic",
      "url": "/documentation/security/common-security-services-manager"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_INTEGRITY",
        "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_PARTITION_ID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_INTEGRITY",
                "doc://com.apple.security/documentation/Security/CSSM_ACL_AUTHORIZATION_PARTITION_ID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ACL_AUTHORIZATION_PARTITION_ID/title",
          "value": "CSSM_ACL_AUTHORIZATION_PARTITION_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ACL_AUTHORIZATION_PARTITION_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ACL_AUTHORIZATION_PARTITION_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ACL_AUTHORIZATION_INTEGRITY/title",
          "value": "CSSM_ACL_AUTHORIZATION_INTEGRITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ACL_AUTHORIZATION_INTEGRITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ACL_AUTHORIZATION_INTEGRITY"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/1434848-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/1434848-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
