{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/common-security-services-manager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/1434766-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_19": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_19"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_19",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_19"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_19",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_19"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_20": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_20"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_20",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_20"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_20",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_20"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_21": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_21"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_21",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_21"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_21",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_21"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_22": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_22"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_22",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_22"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_22",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_22"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_23": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_23"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_23",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_23"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_23",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_23"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_24"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_24",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_24"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_25"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_25",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_25"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_26": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_26"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_26",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_26"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_26",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_26"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_27": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_27",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_PRIVATE_CSPDL_CODE_27",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_private_cspdl_code_27"
    },
    "doc://com.apple.security/documentation/Security/common-security-services-manager": {
      "abstract": [
        {
          "text": "A set of open source modules underpinning the legacy implementation of the Security framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/common-security-services-manager",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Security Services Manager",
      "type": "topic",
      "url": "/documentation/security/common-security-services-manager"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_19",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_20",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_21",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_22",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_23",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_24",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_25",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_26",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_19",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_20",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_21",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_22",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_23",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_24",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_25",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_26",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_21/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_21"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_21/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_21"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_24/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_26/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_26"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_26/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_26"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_22/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_22"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_22/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_22"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_25/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_23/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_23"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_23/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_23"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_27/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_27/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_27"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_19/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_19"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_19/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_19"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_20/title",
          "value": "CSSM_APPLE_PRIVATE_CSPDL_CODE_20"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_PRIVATE_CSPDL_CODE_20/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_PRIVATE_CSPDL_CODE_20"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/1434766-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/1434766-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
