{
  "abstract": [
    {
      "text": "The operations an access control list entry applies to.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/access-control-lists"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/acl-authorization-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ACL Authorization Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/access-control-lists": {
      "abstract": [
        {
          "text": "Control which apps have access to keychain items in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/access-control-lists",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Access Control Lists",
      "type": "topic",
      "url": "/documentation/security/access-control-lists"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationAny": {
      "abstract": [
        {
          "text": "No restrictions. This ACL entry applies to all operations available to the caller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationAny"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationAny",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationany"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeACL": {
      "abstract": [
        {
          "text": "Change an access control list entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationChangeACL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeACL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationChangeACL"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationChangeACL",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationchangeacl"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeOwner": {
      "abstract": [
        {
          "text": "For internal system use only. Use the ",
          "type": "text"
        },
        {
          "code": "CSSM_ACL_AUTHORIZATION_CHANGE_ACL",
          "type": "codeVoice"
        },
        {
          "text": " tag for changes to owner ACL entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationChangeOwner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeOwner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationChangeOwner"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationChangeOwner",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationchangeowner"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDecrypt": {
      "abstract": [
        {
          "text": "Decrypt data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDecrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDecrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDecrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationDecrypt",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationdecrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDelete": {
      "abstract": [
        {
          "text": "Delete this item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDelete"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationDelete",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationdelete"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDerive": {
      "abstract": [
        {
          "text": "Derive a new key from another key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDerive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDerive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationDerive"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationDerive",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationderive"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationEncrypt": {
      "abstract": [
        {
          "text": "Encrypt data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationEncrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationEncrypt",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationencrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportClear": {
      "abstract": [
        {
          "text": "Export an unencrypted key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationExportClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationExportClear"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationExportClear",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationexportclear"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportWrapped": {
      "abstract": [
        {
          "text": "Export a wrapped (that is, encrypted) key. This tag is checked on the key being exported; in addition, the ",
          "type": "text"
        },
        {
          "code": "CSSM_ACL_AUTHORIZATION_ENCRYPT",
          "type": "codeVoice"
        },
        {
          "text": " tag is checked for any key used in the wrapping operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationExportWrapped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportWrapped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationExportWrapped"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationExportWrapped",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationexportwrapped"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationGenKey": {
      "abstract": [
        {
          "text": "Generate a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationGenKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationGenKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationGenKey"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationGenKey",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationgenkey"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportClear": {
      "abstract": [
        {
          "text": "Import an unencrypted key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationImportClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationImportClear"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationImportClear",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationimportclear"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportWrapped": {
      "abstract": [
        {
          "text": "Import an encrypted key. This tag is checked on the key being imported; in addition, the ",
          "type": "text"
        },
        {
          "code": "CSSM_ACL_AUTHORIZATION_DECRYPT",
          "type": "codeVoice"
        },
        {
          "text": " tag is checked for any key used in the unwrapping operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationImportWrapped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportWrapped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationImportWrapped"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationImportWrapped",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationimportwrapped"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationIntegrity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationIntegrity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationIntegrity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationIntegrity"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationIntegrity",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationintegrity"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainCreate": {
      "abstract": [
        {
          "text": "Create a new keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainCreate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainCreate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainCreate"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainCreate",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychaincreate"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainDelete": {
      "abstract": [
        {
          "text": "Delete a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainDelete"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainDelete",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychaindelete"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemDelete": {
      "abstract": [
        {
          "text": "Delete an item from a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemDelete"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainItemDelete",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychainitemdelete"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemInsert": {
      "abstract": [
        {
          "text": "Insert an item into a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemInsert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemInsert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemInsert"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainItemInsert",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychainiteminsert"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemModify": {
      "abstract": [
        {
          "text": "Modify an item in a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemModify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemModify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemModify"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainItemModify",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychainitemmodify"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemRead": {
      "abstract": [
        {
          "text": "Read an item from a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationKeychainItemRead"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationKeychainItemRead",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationkeychainitemread"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationLogin": {
      "abstract": [
        {
          "text": "Use for a CSP (smart card) login.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationLogin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationLogin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationLogin"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationLogin",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationlogin"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationMAC": {
      "abstract": [
        {
          "text": "Create or verify a message authentication code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationMAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationMAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationMAC"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationMAC",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationmac"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationPartitionID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationPartitionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationPartitionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationPartitionID"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationPartitionID",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationpartitionid"
    },
    "doc://com.apple.security/documentation/Security/kSecACLAuthorizationSign": {
      "abstract": [
        {
          "text": "Digitally sign data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecACLAuthorizationSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecACLAuthorizationSign"
        }
      ],
      "role": "symbol",
      "title": "kSecACLAuthorizationSign",
      "type": "topic",
      "url": "/documentation/security/ksecaclauthorizationsign"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationAny",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationLogin",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationGenKey",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDelete",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportWrapped",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportClear",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportWrapped",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportClear",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationSign",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationEncrypt",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDecrypt",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationMAC",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDerive",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainCreate",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainDelete",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemRead",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemInsert",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemModify",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemDelete",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeACL",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeOwner",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationIntegrity",
        "doc://com.apple.security/documentation/Security/kSecACLAuthorizationPartitionID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationAny",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationLogin",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationGenKey",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDelete",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportWrapped",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationExportClear",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportWrapped",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationImportClear",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationSign",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationEncrypt",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDecrypt",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationMAC",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationDerive",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainCreate",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainDelete",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemRead",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemInsert",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemModify",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationKeychainItemDelete",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeACL",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationChangeOwner",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationIntegrity",
                "doc://com.apple.security/documentation/Security/kSecACLAuthorizationPartitionID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainDelete/title",
          "value": "kSecACLAuthorizationKeychainDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationChangeOwner/title",
          "value": "kSecACLAuthorizationChangeOwner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationChangeOwner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationChangeOwner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationExportWrapped/title",
          "value": "kSecACLAuthorizationExportWrapped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationExportWrapped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationExportWrapped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemDelete/title",
          "value": "kSecACLAuthorizationKeychainItemDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainItemDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemRead/title",
          "value": "kSecACLAuthorizationKeychainItemRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainItemRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDerive/title",
          "value": "kSecACLAuthorizationDerive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDerive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationDerive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationChangeACL/title",
          "value": "kSecACLAuthorizationChangeACL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationChangeACL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationChangeACL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationExportClear/title",
          "value": "kSecACLAuthorizationExportClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationExportClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationExportClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationAny/title",
          "value": "kSecACLAuthorizationAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationPartitionID/title",
          "value": "kSecACLAuthorizationPartitionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationPartitionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationPartitionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemModify/title",
          "value": "kSecACLAuthorizationKeychainItemModify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemModify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainItemModify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationImportClear/title",
          "value": "kSecACLAuthorizationImportClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationImportClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationImportClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationMAC/title",
          "value": "kSecACLAuthorizationMAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationMAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationMAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationGenKey/title",
          "value": "kSecACLAuthorizationGenKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationGenKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationGenKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationImportWrapped/title",
          "value": "kSecACLAuthorizationImportWrapped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationImportWrapped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationImportWrapped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationEncrypt/title",
          "value": "kSecACLAuthorizationEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationSign/title",
          "value": "kSecACLAuthorizationSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationLogin/title",
          "value": "kSecACLAuthorizationLogin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationLogin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationLogin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDecrypt/title",
          "value": "kSecACLAuthorizationDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDecrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainCreate/title",
          "value": "kSecACLAuthorizationKeychainCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainCreate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationIntegrity/title",
          "value": "kSecACLAuthorizationIntegrity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationIntegrity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationIntegrity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDelete/title",
          "value": "kSecACLAuthorizationDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemInsert/title",
          "value": "kSecACLAuthorizationKeychainItemInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecACLAuthorizationKeychainItemInsert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecACLAuthorizationKeychainItemInsert"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/acl-authorization-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/acl-authorization-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
