{
  "abstract": [
    {
      "text": "Use actions to trigger particular behaviors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/security-transforms"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/actions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Actions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeNotification": {
      "abstract": [
        {
          "text": "An action that triggers when an attribute is set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionAttributeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionAttributeNotification"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionAttributeNotification",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionattributenotification"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeValidation": {
      "abstract": [
        {
          "text": "An action that triggers to perform validation of an attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionAttributeValidation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionAttributeValidation"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionAttributeValidation",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionattributevalidation"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionCanExecute": {
      "abstract": [
        {
          "text": "An action that triggers to verify that all required attributes are either set or connected to another transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionCanExecute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionCanExecute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionCanExecute"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionCanExecute",
      "type": "topic",
      "url": "/documentation/security/ksectransformactioncanexecute"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionExternalizeExtraData": {
      "abstract": [
        {
          "text": "An action that triggers after data is stored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionExternalizeExtraData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionExternalizeExtraData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionExternalizeExtraData"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionExternalizeExtraData",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionexternalizeextradata"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionFinalize": {
      "abstract": [
        {
          "text": "An action that triggers just before deleting a custom transform to enable custom cleanup operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionFinalize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionFinalize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionFinalize"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionFinalize",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionfinalize"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionInternalizeExtraData": {
      "abstract": [
        {
          "text": "An action that triggers after attributes are read into a transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionInternalizeExtraData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionInternalizeExtraData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionInternalizeExtraData"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionInternalizeExtraData",
      "type": "topic",
      "url": "/documentation/security/ksectransformactioninternalizeextradata"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionProcessData": {
      "abstract": [
        {
          "text": "An action that triggers to process the data of an attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionProcessData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionProcessData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionProcessData"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionProcessData",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionprocessdata"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformActionStartingExecution": {
      "abstract": [
        {
          "text": "An action that triggers just before starting execution of a custom transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformActionStartingExecution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformActionStartingExecution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformActionStartingExecution"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformActionStartingExecution",
      "type": "topic",
      "url": "/documentation/security/ksectransformactionstartingexecution"
    },
    "doc://com.apple.security/documentation/Security/security-transforms": {
      "abstract": [
        {
          "text": "Perform cryptographic functions like encoding, encryption, signing, and signature verification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Transforms",
      "type": "topic",
      "url": "/documentation/security/security-transforms"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeNotification",
        "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeValidation",
        "doc://com.apple.security/documentation/Security/kSecTransformActionCanExecute",
        "doc://com.apple.security/documentation/Security/kSecTransformActionExternalizeExtraData",
        "doc://com.apple.security/documentation/Security/kSecTransformActionFinalize",
        "doc://com.apple.security/documentation/Security/kSecTransformActionInternalizeExtraData",
        "doc://com.apple.security/documentation/Security/kSecTransformActionProcessData",
        "doc://com.apple.security/documentation/Security/kSecTransformActionStartingExecution"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeNotification",
                "doc://com.apple.security/documentation/Security/kSecTransformActionAttributeValidation",
                "doc://com.apple.security/documentation/Security/kSecTransformActionCanExecute",
                "doc://com.apple.security/documentation/Security/kSecTransformActionExternalizeExtraData",
                "doc://com.apple.security/documentation/Security/kSecTransformActionFinalize",
                "doc://com.apple.security/documentation/Security/kSecTransformActionInternalizeExtraData",
                "doc://com.apple.security/documentation/Security/kSecTransformActionProcessData",
                "doc://com.apple.security/documentation/Security/kSecTransformActionStartingExecution"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionProcessData/title",
          "value": "kSecTransformActionProcessData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionProcessData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionProcessData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionCanExecute/title",
          "value": "kSecTransformActionCanExecute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionCanExecute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionCanExecute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionExternalizeExtraData/title",
          "value": "kSecTransformActionExternalizeExtraData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionExternalizeExtraData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionExternalizeExtraData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionAttributeValidation/title",
          "value": "kSecTransformActionAttributeValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionAttributeValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionAttributeValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionFinalize/title",
          "value": "kSecTransformActionFinalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionFinalize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionFinalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionAttributeNotification/title",
          "value": "kSecTransformActionAttributeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionAttributeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionAttributeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionInternalizeExtraData/title",
          "value": "kSecTransformActionInternalizeExtraData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionInternalizeExtraData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionInternalizeExtraData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionStartingExecution/title",
          "value": "kSecTransformActionStartingExecution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformActionStartingExecution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformActionStartingExecution"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/actions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/actions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
