{
  "abstract": [
    {
      "text": "Add network credentials to the keychain on behalf of the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/keychain-items"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/keychain-items",
        "doc://com.apple.security/documentation/Security/using-the-keychain-to-manage-user-secrets"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adding a password to the keychain"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use keychain services to enable simple, secure storage for users’ passwords. In this way you avoid repeatedly asking the user for a password, and you don’t have to implement your own encryption, which can be error prone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Get-Set-Up",
          "level": 3,
          "text": "Get Set Up",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To get started, define a structure to hold the credentials as they move around your app in memory:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct Credentials {",
            "    var username: String",
            "    var password: String",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, define an error enumeration that you can use to communicate keychain access outcomes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "enum KeychainError: Error {",
            "    case noPassword",
            "    case unexpectedPasswordData",
            "    case unhandledError(status: OSStatus)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, identify the server that your app is working with:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "static let server = \"www.example.com\""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Create-an-add-query",
          "level": 3,
          "text": "Create an add query",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Using an instance of the credentials structure and the server constant, you can create an add query:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let account = credentials.username",
            "let password = credentials.password.data(using: String.Encoding.utf8)!",
            "var query: [String: Any] = [kSecClass as String: kSecClassInternetPassword,",
            "                            kSecAttrAccount as String: account,",
            "                            kSecAttrServer as String: server,",
            "                            kSecValueData as String: password]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The query dictionary’s first key-value pair indicates that the item is an Internet password, from which keychain services infers that the data is secret and requires encryption. This also ensures that the item has attributes that distinguish it from other Internet passwords, such as the server and account to which it applies. Indeed, the next two key-value pairs in the query provide this information, attaching the user name acquired from the user as the account, along with a domain name appropriate to this password as the server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Keychain services also offers the related ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " item class. Generic passwords are similar in most respects to Internet passwords, but they lack certain attributes specific to remote access (for example, they don’t have a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrServer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " attribute). When you don’t need these extra attributes, use a generic password instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Although not necessary in this case, you might further characterize the password by specifying additional attributes, such as the port number or the network protocol. For example, if you need to store distinct FTP and HTTP credentials for the same user working on the same server, you might add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrProtocol",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute to distinguish between them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, the query contains the password from the user, encoded as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-the-item",
          "level": 3,
          "text": "Add the item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the query complete, you simply feed it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let status = SecItemAdd(query as CFDictionary, nil)",
            "guard status == errSecSuccess else { throw KeychainError.unhandledError(status: status) }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Although you typically ignore the return data supplied by reference in the second argument on an add operation (as demonstrated here), always check the function’s return status to ensure that the operation succeeds. The operation might fail, for example, if an item with the given attributes already exists.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you do want the return data, keep in mind that the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function behaves much like the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function in this regard. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/searching-for-keychain-items",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for details.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Ensure-searchability",
          "level": 3,
          "text": "Ensure searchability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To find the item later, use your knowledge of its attributes. In this example, the server and the account are the item’s distinguishing characteristics. For constant attributes (here, the server), use the same value during lookup. In contrast, the account attribute is dynamic, because it holds a value provided by the user at runtime. As long as your app never adds similar items with varying attributes (such as passwords for different accounts on the same server), you can omit these dynamic attributes as search parameters and instead retrieve them along with the item. As a result, when you look up the password, you also get the corresponding username. For more information on finding keychain items, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/searching-for-keychain-items",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app does add items with varying dynamic attributes, you need a way to choose among them during retrieval. One option is to record information about the items in another way. For example, if you keep records of users in a Core Data model, you store the username there after using keychain services to store the password field. Later, you use the user name pulled from your data model to condition the search for the password.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In other cases, it might make sense to further characterize the item by adding more attributes. For example, you might include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute in the original add query, providing a string that marks the item for the particular purpose. Then you can use this attribute to narrow your search later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/data": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        }
      ],
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemadd(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)": {
      "abstract": [
        {
          "text": "Returns one or more keychain items that match a search query, or copies attributes of specific keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        }
      ],
      "role": "symbol",
      "title": "SecItemCopyMatching(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemcopymatching(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrLabel": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the item’s label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrLabel",
      "type": "topic",
      "url": "/documentation/security/ksecattrlabel"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrProtocol": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrProtocol"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrProtocol",
      "type": "topic",
      "url": "/documentation/security/ksecattrprotocol"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrServer": {
      "abstract": [
        {
          "text": "A key whose value is a string indicating the item’s server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrServer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrServer"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrServer",
      "type": "topic",
      "url": "/documentation/security/ksecattrserver"
    },
    "doc://com.apple.security/documentation/Security/kSecClassGenericPassword": {
      "abstract": [
        {
          "text": "The value that indicates a generic password item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        }
      ],
      "role": "symbol",
      "title": "kSecClassGenericPassword",
      "type": "topic",
      "url": "/documentation/security/ksecclassgenericpassword"
    },
    "doc://com.apple.security/documentation/Security/keychain-items": {
      "abstract": [
        {
          "text": "Embed confidential information in items that you store in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-items",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain items",
      "type": "topic",
      "url": "/documentation/security/keychain-items"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    },
    "doc://com.apple.security/documentation/Security/searching-for-keychain-items": {
      "abstract": [
        {
          "text": "Find keychain items based on search criteria that you specify.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/searching-for-keychain-items",
      "kind": "article",
      "role": "article",
      "title": "Searching for keychain items",
      "type": "topic",
      "url": "/documentation/security/searching-for-keychain-items"
    },
    "doc://com.apple.security/documentation/Security/using-the-keychain-to-manage-user-secrets": {
      "abstract": [
        {
          "text": "Relieve the user of remembering small secrets by storing them in the keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/using-the-keychain-to-manage-user-secrets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Using the keychain to manage user secrets",
      "type": "topic",
      "url": "/documentation/security/using-the-keychain-to-manage-user-secrets"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/title",
          "value": "kSecAttrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrProtocol/title",
          "value": "kSecAttrProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/title",
          "value": "SecItemCopyMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemCopyMatching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrServer/title",
          "value": "kSecAttrServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/title",
          "value": "kSecClassGenericPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassGenericPassword"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/adding-a-password-to-the-keychain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/adding-a-password-to-the-keychain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
