{
  "abstract": [
    {
      "text": "Use name tags to define authorization security items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/authorization-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/authorization-name-tags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Authorization Name Tags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These tags are possible values for the ",
              "type": "text"
            },
            {
              "code": "name",
              "type": "codeVoice"
            },
            {
              "text": " field of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure. This is not an all-inclusive set. You determine the name of the right to request. These environment tags are for future use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationItem": {
      "abstract": [
        {
          "text": "A structure containing information about an authorization right or the authorization environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationItem"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationItem"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationItem",
      "type": "topic",
      "url": "/documentation/security/authorizationitem"
    },
    "doc://com.apple.security/documentation/Security/authorization-services": {
      "abstract": [
        {
          "text": "Access restricted areas of the operating system, and control access to particular features of your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Services",
      "type": "topic",
      "url": "/documentation/security/authorization-services"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentIcon": {
      "abstract": [
        {
          "text": "The type for an authorization item containing the name of the item that should be passed into the environment when specifying an alternate icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentIcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentIcon"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationEnvironmentIcon",
      "type": "topic",
      "url": "/documentation/security/kauthorizationenvironmenticon"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPassword": {
      "abstract": [
        {
          "text": "The type for an authorization item containing a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentPassword"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationEnvironmentPassword",
      "type": "topic",
      "url": "/documentation/security/kauthorizationenvironmentpassword"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPrompt": {
      "abstract": [
        {
          "text": "The type for an authorization item containing the name of the item that should be passed into the environment when specifying invocation-specific additional text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentPrompt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPrompt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentPrompt"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationEnvironmentPrompt",
      "type": "topic",
      "url": "/documentation/security/kauthorizationenvironmentprompt"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentShared": {
      "abstract": [
        {
          "text": "The type for an authorization item containing a shared right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentShared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentShared"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationEnvironmentShared",
      "type": "topic",
      "url": "/documentation/security/kauthorizationenvironmentshared"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentUsername": {
      "abstract": [
        {
          "text": "The type for an authorization item containing a user name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentUsername"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentUsername",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEnvironmentUsername"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationEnvironmentUsername",
      "type": "topic",
      "url": "/documentation/security/kauthorizationenvironmentusername"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationPamResult": {
      "abstract": [
        {
          "text": "The type for an authorization item containing a return code from a Pluggable Authentication Module (PAM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationPamResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationPamResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationPamResult"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationPamResult",
      "type": "topic",
      "url": "/documentation/security/kauthorizationpamresult"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRightExecute": {
      "abstract": [
        {
          "text": "The type for an authorization item requesting the right to execute with privileges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRightExecute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRightExecute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRightExecute"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRightExecute",
      "type": "topic",
      "url": "/documentation/security/kauthorizationrightexecute"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentUsername",
        "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPassword",
        "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentShared",
        "doc://com.apple.security/documentation/Security/kAuthorizationRightExecute",
        "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPrompt",
        "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentIcon",
        "doc://com.apple.security/documentation/Security/kAuthorizationPamResult"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentUsername",
                "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPassword",
                "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentShared",
                "doc://com.apple.security/documentation/Security/kAuthorizationRightExecute",
                "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentPrompt",
                "doc://com.apple.security/documentation/Security/kAuthorizationEnvironmentIcon",
                "doc://com.apple.security/documentation/Security/kAuthorizationPamResult"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentIcon/title",
          "value": "kAuthorizationEnvironmentIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationEnvironmentIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentPassword/title",
          "value": "kAuthorizationEnvironmentPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationEnvironmentPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationPamResult/title",
          "value": "kAuthorizationPamResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationPamResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationPamResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItem/title",
          "value": "AuthorizationItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentShared/title",
          "value": "kAuthorizationEnvironmentShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationEnvironmentShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentUsername/title",
          "value": "kAuthorizationEnvironmentUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentUsername/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationEnvironmentUsername"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentPrompt/title",
          "value": "kAuthorizationEnvironmentPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationEnvironmentPrompt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationEnvironmentPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRightExecute/title",
          "value": "kAuthorizationRightExecute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRightExecute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRightExecute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorization-name-tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/authorization-name-tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
