{
  "abstract": [
    {
      "text": "Initializes the plug-in and exchanges interfaces with the authorization engine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AuthorizationPluginCreate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AuthorizationPluginCreate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AuthorizationPluginCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AuthorizationPluginCreate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationPluginCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AuthorizationCallbacks",
              "text": "AuthorizationCallbacks"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "callbacks"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationPluginRef",
              "text": "AuthorizationPluginRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outPlugin"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AuthorizationPluginInterface",
              "text": "AuthorizationPluginInterface"
            },
            {
              "kind": "text",
              "text": " * * "
            },
            {
              "kind": "internalParam",
              "text": "outPluginInterface"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure containing entry points to the Security Server.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callbacks"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On input, a pointer that you can assign, on output, to a reference value that you define. The authorization engine passes this reference back to you in any subsequent calls to your functions ",
                  "type": "text"
                },
                {
                  "code": "outPluginInterface->MechanismCreate",
                  "type": "codeVoice"
                },
                {
                  "text": " (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") and ",
                  "type": "text"
                },
                {
                  "code": "outPluginInterface->PluginDestroy",
                  "type": "codeVoice"
                },
                {
                  "text": " (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") so that you can identify the instance of the plug-in affected.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outPlugin"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On input, a pointer that you assign, on output, to a structure containing entry points in the plug-in. This structure remains valid until the authorization engine calls ",
                  "type": "text"
                },
                {
                  "code": "outPluginInterface->PluginDestroy",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outPluginInterface"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. Returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (no error) if the function completes successfully and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Security Server internal error) if any error occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/extending-authorization-services-with-plug-ins"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is the main entry point to the plug-in. The authorization engine calls this function only once. The plug-in receives an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure containing the entry points to the Security Server’s functions and returns an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure containing the entry points to all of the plug-in’s routines. Both of these structures contain version numbers. The authorization engine matches the version of its interface to the version in your plug-in’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure in order to ensure that older plug-ins will continue to function correctly after the Security Server is updated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your plug-in is running in macOS 10.5 or later and displays a window before the user has logged in, ensure you set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Authorization plug-ins that put up a GUI or otherwise connect to the window server cannot run as privileged. Note that running GUI code as root is a bad idea in general, because GUI code links in many libraries, any of which could contain security vulnerabilities.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/AppKit/NSWindow"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window can be displayed at the login window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canBecomeVisibleWithoutLogin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin",
      "kind": "symbol",
      "role": "symbol",
      "title": "canBecomeVisibleWithoutLogin",
      "type": "topic",
      "url": "/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCallbacks": {
      "abstract": [
        {
          "text": "The interface implemented by the Security Server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationCallbacks"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationCallbacks",
      "type": "topic",
      "url": "/documentation/security/authorizationcallbacks"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate": {
      "abstract": [
        {
          "text": "Initializes the plug-in and exchanges interfaces with the authorization engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationPluginCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationPluginCreate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugincreate"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface": {
      "abstract": [
        {
          "text": "The interface that must be implemented by your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationPluginInterface"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationPluginInterface",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate": {
      "abstract": [
        {
          "text": "Creates an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismCreate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismcreate"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy": {
      "abstract": [
        {
          "text": "Destroys an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismDestroy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismDestroy",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismdestroy"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginRef": {
      "abstract": [
        {
          "text": "A handle passed by the plug-in to the authorization engine when the plug-in is initiated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationPluginRef"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationPluginRef",
      "type": "topic",
      "url": "/documentation/security/authorizationpluginref"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInternal": {
      "abstract": [
        {
          "text": "An unrecognized internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInternal",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinternal"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationSuccess": {
      "abstract": [
        {
          "text": "The operation completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationSuccess",
      "type": "topic",
      "url": "/documentation/security/errauthorizationsuccess"
    },
    "doc://com.apple.security/documentation/Security/extending-authorization-services-with-plug-ins": {
      "abstract": [
        {
          "text": "Modify the system’s authorization policy with custom code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/extending-authorization-services-with-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Extending authorization services with plug-ins",
      "type": "topic",
      "url": "/documentation/security/extending-authorization-services-with-plug-ins"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/title",
          "value": "errAuthorizationSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/title",
          "value": "errAuthorizationInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWindow~1canBecomeVisibleWithoutLogin/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "canBecomeVisibleWithoutLogin"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationplugincreate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
