{
  "abstract": [
    {
      "text": "Authorizes and preauthorizes rights asynchronously.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationCopyRightsAsync(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AuthorizationCopyRightsAsync",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AuthorizationCopyRightsAsync"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationRef",
        "text": "AuthorizationRef"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationRights",
        "text": "AuthorizationRights"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationEnvironment",
        "text": "AuthorizationEnvironment"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AuthorizationFlags",
        "text": "AuthorizationFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationAsyncCallback",
        "text": "AuthorizationAsyncCallback"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AuthorizationCopyRightsAsync"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AuthorizationCopyRightsAsync(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationCopyRightsAsync"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "authorization"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRef",
              "text": "AuthorizationRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRights",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "environment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationEnvironment",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AuthorizationFlags",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "callbackBlock"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationAsyncCallback",
              "text": "AuthorizationAsyncCallback"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An authorization reference referring to the authorization session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "authorization"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a set of authorization rights you create. Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if the application requires no rights at this time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Data used when authorizing or preauthorizing rights. Not used in OS X v10.2 and earlier. In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box. In macOS 10.4 and later, you can also pass a user name and password in order to authorize a user without displaying the authentication dialog box. Possible values for this parameter are listed in ",
                  "type": "text"
                },
                {
                  "code": "Security.framework/Headers/AuthorizationTags.h",
                  "type": "codeVoice"
                },
                {
                  "text": ". The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "environment"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask for specifying authorization options. Use one of the options sets defined for the flags parameter in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCopyRights(_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A callback that you provide for the function to call when it finishes asynchronously. Use a function with the signature defined by ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callbackBlock"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See the discussion for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCopyRights(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This function behaves similarly, except that it performs its operations asynchronously and calls back to you upon completion.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback": {
      "abstract": [
        {
          "text": "A block used as a callback for the asynchronous version of copying authorization rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationAsyncCallback"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationAsyncCallback"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationAsyncCallback",
      "type": "topic",
      "url": "/documentation/security/authorizationasynccallback"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCopyRights(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights synchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationCopyRights"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCopyRights(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationCopyRights"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationCopyRights(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/authorizationcopyrights(_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCopyRightsAsync(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationCopyRightsAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationAsyncCallback",
          "text": "AuthorizationAsyncCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCopyRightsAsync(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationCopyRightsAsync"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationCopyRightsAsync(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/authorizationcopyrightsasync(_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationEnvironment": {
      "abstract": [
        {
          "text": "An authorization item set designated to hold environment information relevant to authorization decisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationEnvironment",
      "type": "topic",
      "url": "/documentation/security/authorizationenvironment"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/security/authorizationflags"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationRef": {
      "abstract": [
        {
          "text": "A pointer to an opaque authorization reference structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRef"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationRef"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationRef",
      "type": "topic",
      "url": "/documentation/security/authorizationref"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationRights": {
      "abstract": [
        {
          "text": "An authorization item set designated to represent a set of rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationRights",
      "type": "topic",
      "url": "/documentation/security/authorizationrights"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment": {
      "abstract": [
        {
          "text": "A constant you use in functions with an environment parameter if you have no environment data to provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEmptyEnvironment"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationEmptyEnvironment",
      "type": "topic",
      "url": "/documentation/security/kauthorizationemptyenvironment"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AuthorizationCopyRightsAsync"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationCopyRightsAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AuthorizationCopyRightsAsync"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationRef",
                    "text": "AuthorizationRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "authorization"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationRights",
                    "text": "AuthorizationRights"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rights"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationEnvironment",
                    "text": "AuthorizationEnvironment"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "environment"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AuthorizationFlags",
                    "text": "AuthorizationFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationAsyncCallback",
                    "text": "AuthorizationAsyncCallback"
                  },
                  {
                    "kind": "internalParam",
                    "text": "callbackBlock"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An authorization reference referring to the authorization session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "authorization"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a set of authorization rights you create. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the application requires no rights at this time.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rights"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Data used when authorizing or preauthorizing rights. Not used in OS X v10.2 and earlier. In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box. In macOS 10.4 and later, you can also pass a user name and password in order to authorize a user without displaying the authentication dialog box. Possible values for this parameter are listed in ",
                        "type": "text"
                      },
                      {
                        "code": "Security.framework/Headers/AuthorizationTags.h",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "environment"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A bit mask for specifying authorization options. Use one of the options sets defined for the flags parameter in the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCopyRights(_:_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A callback that you provide for the function to call when it finishes asynchronously. Use a function with the signature defined by ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/AuthorizationAsyncCallback",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callbackBlock"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/title",
          "value": "AuthorizationEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/title",
          "value": "AuthorizationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCopyRightsAsync(_:_:_:_:_:)/title",
          "value": "AuthorizationCopyRightsAsync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCopyRightsAsync(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationCopyRightsAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/title",
          "value": "AuthorizationRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationAsyncCallback/title",
          "value": "AuthorizationAsyncCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationAsyncCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationAsyncCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationAsyncCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationAsyncCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/title",
          "value": "AuthorizationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCopyRights(_:_:_:_:_:)/title",
          "value": "AuthorizationCopyRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCopyRights(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationCopyRights"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationcopyrightsasync(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/authorizationcopyrightsasync(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
