{
  "abstract": [
    {
      "text": "The mechanism ID specified in the authorization policy database is passed to the plug-in to create the appropriate mechanism.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationMechanismId"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AuthorizationMechanismId",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AuthorizationMechanismId"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AuthorizationMechanismId"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AuthorizationMechanismId"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationString",
              "text": "AuthorizationString"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationMechanismId"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationMechanismId": {
      "abstract": [
        {
          "text": "The mechanism ID specified in the authorization policy database is passed to the plug-in to create the appropriate mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationMechanismId"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationMechanismId",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationMechanismId",
      "type": "topic",
      "url": "/documentation/security/authorizationmechanismid"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationString": {
      "abstract": [
        {
          "text": "A zero-terminated string in UTF-8 encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationString"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationString",
      "type": "topic",
      "url": "/documentation/security/authorizationstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationString/title",
          "value": "AuthorizationString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationmechanismid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
