{
  "abstract": [
    {
      "text": "Creates a new authorization reference and provides an option to authorize or preauthorize rights.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationCreate(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AuthorizationCreate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AuthorizationCreate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationRights",
        "text": "AuthorizationRights"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationEnvironment",
        "text": "AuthorizationEnvironment"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AuthorizationFlags",
        "text": "AuthorizationFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationRef",
        "text": "AuthorizationRef"
      },
      {
        "kind": "text",
        "text": "?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AuthorizationCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AuthorizationCreate(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRights",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "environment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationEnvironment",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AuthorizationFlags",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "authorization"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRef",
              "text": "AuthorizationRef"
            },
            {
              "kind": "text",
              "text": "?>?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a set of authorization rights you create. Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if the application requires no rights at this time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItemSet",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure used when authorizing or preauthorizing rights.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Not used in OS X v10.2 and earlier.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In macOS 10.4 and later, you can also pass a user name and password in order to authorize a user without user interaction. Possible values for this parameter are listed in ",
                  "type": "text"
                },
                {
                  "code": "Security.framework/Headers/AuthorizationTags.h",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For a list of possible keys in the authorization set, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/authorization-name-tags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". For the data structure itself, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItemSet",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "environment"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask constructed at the bitwise ",
                  "type": "text"
                },
                {
                  "code": "OR",
                  "type": "codeVoice"
                },
                {
                  "text": " of one or more ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for specifying authorization options. Use one of the following option sets:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Use the constant ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " if no options are necessary.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Use the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flag to request rights. You can also add the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flag to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/partialRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flags to request partial rights. You can also add the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flag to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/preAuthorize",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flags to preauthorize rights.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/destroyRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " flag to prevent the Security Server from preserving the rights obtained during this call.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an authorization reference. On return, this parameter refers to the authorization session the Security Server creates. Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if you require a function result but no authorization reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "authorization"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/authorization-services-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The primary purpose of this function is to create the opaque authorization reference structure associated with the authorization reference. You use the authorization reference in other authorization functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use this function to authorize all or partial rights. Authorizing rights with this function is most useful for applications that require a one-time authorization. By passing ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " to the ",
              "type": "text"
            },
            {
              "code": "authorization",
              "type": "codeVoice"
            },
            {
              "text": " parameter, the Security Server attempts to authorize the requested rights and returns the appropriate result code without actually granting the rights. If you are not going to call any other authorization functions, use this method to determine if a user has authorization without granting any rights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use this function to preauthorize rights by specifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/preAuthorize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask. Preauthorization is most useful when a right has a zero timeout. For example, you can preauthorize in the application and if it succeeds, call the helper tool and request authorization. This eliminates calling the helper tool if the user cannot later authorize the specified rights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/partialRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the Security Server denies at least one right, then the status of this function on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationDenied",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the Security Server requires user interaction, then the status of this function on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the user cancels the authentication process, then the status of this function on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationCanceled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When your application no longer needs the authorization reference, use the function ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFree(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to free the memory associated with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new authorization reference and provides an option to authorize or preauthorize rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationCreate"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/authorizationcreate(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationEnvironment": {
      "abstract": [
        {
          "text": "An authorization item set designated to hold environment information relevant to authorization decisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationEnvironment",
      "type": "topic",
      "url": "/documentation/security/authorizationenvironment"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/security/authorizationflags"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/destroyRights": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to revoke authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/destroyRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagDestroyRights"
        }
      ],
      "role": "symbol",
      "title": "destroyRights",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/destroyrights"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to attempt to grant the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagExtendRights"
        }
      ],
      "role": "symbol",
      "title": "extendRights",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/extendrights"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed": {
      "abstract": [
        {
          "text": "A flag that permits user interaction as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagInteractionAllowed"
        }
      ],
      "role": "symbol",
      "title": "interactionAllowed",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/interactionallowed"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults": {
      "abstract": [
        {
          "text": "An empty flag set that you use as a placeholder when you don’t want any of the other flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagDefaults"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationFlagDefaults",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/kauthorizationflagdefaults"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/partialRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to grant rights on an individual basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/partialRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagPartialRights"
        }
      ],
      "role": "symbol",
      "title": "partialRights",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/partialrights"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/preAuthorize": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to preauthorize the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preAuthorize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/preAuthorize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagPreAuthorize"
        }
      ],
      "role": "symbol",
      "title": "preAuthorize",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/preauthorize"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFree(_:_:)": {
      "abstract": [
        {
          "text": "Frees the memory associated with an authorization reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFree(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationFree"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationFree(_:_:)",
      "type": "topic",
      "url": "/documentation/security/authorizationfree(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationItemSet": {
      "abstract": [
        {
          "text": "A structure containing a set of authorization items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItemSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationItemSet"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationItemSet",
      "type": "topic",
      "url": "/documentation/security/authorizationitemset"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationRef": {
      "abstract": [
        {
          "text": "A pointer to an opaque authorization reference structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRef"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationRef"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationRef",
      "type": "topic",
      "url": "/documentation/security/authorizationref"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationRights": {
      "abstract": [
        {
          "text": "An authorization item set designated to represent a set of rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationRights",
      "type": "topic",
      "url": "/documentation/security/authorizationrights"
    },
    "doc://com.apple.security/documentation/Security/authorization-name-tags": {
      "abstract": [
        {
          "text": "Use name tags to define authorization security items.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-name-tags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Name Tags",
      "type": "topic",
      "url": "/documentation/security/authorization-name-tags"
    },
    "doc://com.apple.security/documentation/Security/authorization-services-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the authorization services API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-services-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Services Result Codes",
      "type": "topic",
      "url": "/documentation/security/authorization-services-result-codes"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationCanceled"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationCanceled",
      "type": "topic",
      "url": "/documentation/security/errauthorizationcanceled"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationDenied": {
      "abstract": [
        {
          "text": "The Security Server denied authorization for one or more requested rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/security/errauthorizationdenied"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed": {
      "abstract": [
        {
          "text": "The Security Server denied authorization because no user interaction is allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInteractionNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInteractionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInteractionNotAllowed",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinteractionnotallowed"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment": {
      "abstract": [
        {
          "text": "A constant you use in functions with an environment parameter if you have no environment data to provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationEmptyEnvironment"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationEmptyEnvironment",
      "type": "topic",
      "url": "/documentation/security/kauthorizationemptyenvironment"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AuthorizationCreate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AuthorizationCreate"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRights",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationRights",
                    "text": "AuthorizationRights"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rights"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationEnvironment",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationEnvironment",
                    "text": "AuthorizationEnvironment"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "environment"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AuthorizationFlags",
                    "text": "AuthorizationFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationRef",
                    "text": "AuthorizationRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "authorization"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a set of authorization rights you create. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the application requires no rights at this time.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rights"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItemSet",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure used when authorizing or preauthorizing rights.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "Not used in OS X v10.2 and earlier.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "In macOS 10.4 and later, you can also pass a user name and password in order to authorize a user without user interaction. Possible values for this parameter are listed in ",
                        "type": "text"
                      },
                      {
                        "code": "Security.framework/Headers/AuthorizationTags.h",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationEmptyEnvironment",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "For a list of possible keys in the authorization set, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/authorization-name-tags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". For the data structure itself, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/AuthorizationItemSet",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "environment"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A bit mask constructed at the bitwise ",
                        "type": "text"
                      },
                      {
                        "code": "OR",
                        "type": "codeVoice"
                      },
                      {
                        "text": " of one or more ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for specifying authorization options. Use one of the following option sets:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Use the constant ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " if no options are necessary.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Use the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flag to request rights. You can also add the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flag to allow user interaction.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/partialRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " and ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flags to request partial rights. You can also add the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/interactionAllowed",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flag to allow user interaction.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/preAuthorize",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " and ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flags to preauthorize rights.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/destroyRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " flag to prevent the Security Server from preserving the rights obtained during this call.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an authorization reference. On return, this parameter refers to the authorization session the Security Server creates. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you require a function result but no authorization reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "authorization"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/authorization-services-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/title",
          "value": "AuthorizationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/title",
          "value": "kAuthorizationFlagInteractionAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagInteractionAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCreate(_:_:_:_:)/title",
          "value": "AuthorizationCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1partialRights/title",
          "value": "kAuthorizationFlagPartialRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1partialRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPartialRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1extendRights/title",
          "value": "kAuthorizationFlagExtendRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1extendRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagExtendRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationDenied/title",
          "value": "errAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFree(_:_:)/title",
          "value": "AuthorizationFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFree(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/title",
          "value": "AuthorizationRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRights/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/title",
          "value": "AuthorizationEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1preAuthorize/title",
          "value": "kAuthorizationFlagPreAuthorize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1preAuthorize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPreAuthorize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/title",
          "value": "AuthorizationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItemSet/title",
          "value": "AuthorizationItemSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItemSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationItemSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationItemSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationItemSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1destroyRights/title",
          "value": "kAuthorizationFlagDestroyRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags~1destroyRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagDestroyRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationCanceled/title",
          "value": "errAuthorizationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInteractionNotAllowed/title",
          "value": "errAuthorizationInteractionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInteractionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInteractionNotAllowed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationcreate(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/authorizationcreate(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
