{
  "abstract": [
    {
      "text": "Recognize result codes specific to the authorization services API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/authorization-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/authorization-services-result-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Authorization Services Result Codes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to obtain a human readable string corresponding to these status codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/authorization-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API may also return the general codes listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)": {
      "abstract": [
        {
          "text": "Returns a string explaining the meaning of a security result code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCopyErrorMessageString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCopyErrorMessageString"
        }
      ],
      "role": "symbol",
      "title": "SecCopyErrorMessageString(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccopyerrormessagestring(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/authorization-services": {
      "abstract": [
        {
          "text": "Access restricted areas of the operating system, and control access to particular features of your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Services",
      "type": "topic",
      "url": "/documentation/security/authorization-services"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationBadAddress": {
      "abstract": [
        {
          "text": "The requested socket address is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationBadAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationBadAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationBadAddress"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationBadAddress",
      "type": "topic",
      "url": "/documentation/security/errauthorizationbadaddress"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationCanceled"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationCanceled",
      "type": "topic",
      "url": "/documentation/security/errauthorizationcanceled"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationDenied": {
      "abstract": [
        {
          "text": "The Security Server denied authorization for one or more requested rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/security/errauthorizationdenied"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationExternalizeNotAllowed": {
      "abstract": [
        {
          "text": "The Security Server denied externalization of the authorization reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationExternalizeNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationExternalizeNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationExternalizeNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationExternalizeNotAllowed",
      "type": "topic",
      "url": "/documentation/security/errauthorizationexternalizenotallowed"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed": {
      "abstract": [
        {
          "text": "The Security Server denied authorization because no user interaction is allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInteractionNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInteractionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInteractionNotAllowed",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinteractionnotallowed"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInternal": {
      "abstract": [
        {
          "text": "An unrecognized internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInternal",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinternal"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInternalizeNotAllowed": {
      "abstract": [
        {
          "text": "The Security Server denied internalization of the authorization reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInternalizeNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternalizeNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInternalizeNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInternalizeNotAllowed",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinternalizenotallowed"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInvalidFlags": {
      "abstract": [
        {
          "text": "The flags parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInvalidFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidFlags"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInvalidFlags",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinvalidflags"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInvalidPointer": {
      "abstract": [
        {
          "text": "The authorizedRights parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidPointer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInvalidPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidPointer"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInvalidPointer",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinvalidpointer"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInvalidRef": {
      "abstract": [
        {
          "text": "The authorization parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInvalidRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidRef"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInvalidRef",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinvalidref"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInvalidSet": {
      "abstract": [
        {
          "text": "The set parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInvalidSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidSet"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInvalidSet",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinvalidset"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInvalidTag": {
      "abstract": [
        {
          "text": "The tag parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInvalidTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInvalidTag"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInvalidTag",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinvalidtag"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationSuccess": {
      "abstract": [
        {
          "text": "The operation completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationSuccess",
      "type": "topic",
      "url": "/documentation/security/errauthorizationsuccess"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationToolEnvironmentError": {
      "abstract": [
        {
          "text": "The attempt to execute the tool failed to return a success or an error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationToolEnvironmentError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationToolEnvironmentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationToolEnvironmentError"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationToolEnvironmentError",
      "type": "topic",
      "url": "/documentation/security/errauthorizationtoolenvironmenterror"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationToolExecuteFailure": {
      "abstract": [
        {
          "text": "The tool failed to execute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationToolExecuteFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationToolExecuteFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationToolExecuteFailure"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationToolExecuteFailure",
      "type": "topic",
      "url": "/documentation/security/errauthorizationtoolexecutefailure"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Codes",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
        "doc://com.apple.security/documentation/Security/errAuthorizationInvalidSet",
        "doc://com.apple.security/documentation/Security/errAuthorizationInvalidRef",
        "doc://com.apple.security/documentation/Security/errAuthorizationInvalidTag",
        "doc://com.apple.security/documentation/Security/errAuthorizationInvalidPointer",
        "doc://com.apple.security/documentation/Security/errAuthorizationDenied",
        "doc://com.apple.security/documentation/Security/errAuthorizationCanceled",
        "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed",
        "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
        "doc://com.apple.security/documentation/Security/errAuthorizationExternalizeNotAllowed",
        "doc://com.apple.security/documentation/Security/errAuthorizationInternalizeNotAllowed",
        "doc://com.apple.security/documentation/Security/errAuthorizationInvalidFlags",
        "doc://com.apple.security/documentation/Security/errAuthorizationToolExecuteFailure",
        "doc://com.apple.security/documentation/Security/errAuthorizationToolEnvironmentError",
        "doc://com.apple.security/documentation/Security/errAuthorizationBadAddress"
      ],
      "title": "Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Codes",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
                "doc://com.apple.security/documentation/Security/errAuthorizationInvalidSet",
                "doc://com.apple.security/documentation/Security/errAuthorizationInvalidRef",
                "doc://com.apple.security/documentation/Security/errAuthorizationInvalidTag",
                "doc://com.apple.security/documentation/Security/errAuthorizationInvalidPointer",
                "doc://com.apple.security/documentation/Security/errAuthorizationDenied",
                "doc://com.apple.security/documentation/Security/errAuthorizationCanceled",
                "doc://com.apple.security/documentation/Security/errAuthorizationInteractionNotAllowed",
                "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
                "doc://com.apple.security/documentation/Security/errAuthorizationExternalizeNotAllowed",
                "doc://com.apple.security/documentation/Security/errAuthorizationInternalizeNotAllowed",
                "doc://com.apple.security/documentation/Security/errAuthorizationInvalidFlags",
                "doc://com.apple.security/documentation/Security/errAuthorizationToolExecuteFailure",
                "doc://com.apple.security/documentation/Security/errAuthorizationToolEnvironmentError",
                "doc://com.apple.security/documentation/Security/errAuthorizationBadAddress"
              ],
              "title": "Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationToolEnvironmentError/title",
          "value": "errAuthorizationToolEnvironmentError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationToolEnvironmentError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationToolEnvironmentError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCopyErrorMessageString(_:_:)/title",
          "value": "SecCopyErrorMessageString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCopyErrorMessageString(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCopyErrorMessageString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationCanceled/title",
          "value": "errAuthorizationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/title",
          "value": "errAuthorizationInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationBadAddress/title",
          "value": "errAuthorizationBadAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationBadAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationBadAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidFlags/title",
          "value": "errAuthorizationInvalidFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInvalidFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidSet/title",
          "value": "errAuthorizationInvalidSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInvalidSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInteractionNotAllowed/title",
          "value": "errAuthorizationInteractionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInteractionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInteractionNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationToolExecuteFailure/title",
          "value": "errAuthorizationToolExecuteFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationToolExecuteFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationToolExecuteFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationDenied/title",
          "value": "errAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidRef/title",
          "value": "errAuthorizationInvalidRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInvalidRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidTag/title",
          "value": "errAuthorizationInvalidTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInvalidTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidPointer/title",
          "value": "errAuthorizationInvalidPointer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInvalidPointer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInvalidPointer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternalizeNotAllowed/title",
          "value": "errAuthorizationInternalizeNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternalizeNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInternalizeNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationExternalizeNotAllowed/title",
          "value": "errAuthorizationExternalizeNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationExternalizeNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationExternalizeNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/title",
          "value": "errAuthorizationSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorization-services-result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/authorization-services-result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
