{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CE_DataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CE_DataType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CE_DataType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CE_DataType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CE_DataType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CE_DataType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "text": "__CE_DataType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CE_DataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CE_DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CE_DataType"
        }
      ],
      "role": "symbol",
      "title": "CE_DataType",
      "type": "topic",
      "url": "/documentation/security/ce_datatype"
    },
    "doc://com.apple.security/documentation/Security/DT_AuthorityInfoAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_AuthorityInfoAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_AuthorityInfoAccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_AuthorityInfoAccess",
      "type": "topic",
      "url": "/documentation/security/dt_authorityinfoaccess"
    },
    "doc://com.apple.security/documentation/Security/DT_AuthorityKeyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_AuthorityKeyID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_AuthorityKeyID",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_AuthorityKeyID",
      "type": "topic",
      "url": "/documentation/security/dt_authoritykeyid"
    },
    "doc://com.apple.security/documentation/Security/DT_BasicConstraints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_BasicConstraints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_BasicConstraints",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_BasicConstraints",
      "type": "topic",
      "url": "/documentation/security/dt_basicconstraints"
    },
    "doc://com.apple.security/documentation/Security/DT_CertPolicies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_CertPolicies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_CertPolicies",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_CertPolicies",
      "type": "topic",
      "url": "/documentation/security/dt_certpolicies"
    },
    "doc://com.apple.security/documentation/Security/DT_CrlDistributionPoints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_CrlDistributionPoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_CrlDistributionPoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_CrlDistributionPoints",
      "type": "topic",
      "url": "/documentation/security/dt_crldistributionpoints"
    },
    "doc://com.apple.security/documentation/Security/DT_CrlNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_CrlNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_CrlNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_CrlNumber",
      "type": "topic",
      "url": "/documentation/security/dt_crlnumber"
    },
    "doc://com.apple.security/documentation/Security/DT_CrlReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_CrlReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_CrlReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_CrlReason",
      "type": "topic",
      "url": "/documentation/security/dt_crlreason"
    },
    "doc://com.apple.security/documentation/Security/DT_DeltaCrl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_DeltaCrl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_DeltaCrl",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_DeltaCrl",
      "type": "topic",
      "url": "/documentation/security/dt_deltacrl"
    },
    "doc://com.apple.security/documentation/Security/DT_ExtendedKeyUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_ExtendedKeyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_ExtendedKeyUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_ExtendedKeyUsage",
      "type": "topic",
      "url": "/documentation/security/dt_extendedkeyusage"
    },
    "doc://com.apple.security/documentation/Security/DT_InhibitAnyPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_InhibitAnyPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_InhibitAnyPolicy",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_InhibitAnyPolicy",
      "type": "topic",
      "url": "/documentation/security/dt_inhibitanypolicy"
    },
    "doc://com.apple.security/documentation/Security/DT_IssuerAltName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_IssuerAltName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_IssuerAltName",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_IssuerAltName",
      "type": "topic",
      "url": "/documentation/security/dt_issueraltname"
    },
    "doc://com.apple.security/documentation/Security/DT_IssuingDistributionPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_IssuingDistributionPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_IssuingDistributionPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_IssuingDistributionPoint",
      "type": "topic",
      "url": "/documentation/security/dt_issuingdistributionpoint"
    },
    "doc://com.apple.security/documentation/Security/DT_KeyUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_KeyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_KeyUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_KeyUsage",
      "type": "topic",
      "url": "/documentation/security/dt_keyusage"
    },
    "doc://com.apple.security/documentation/Security/DT_NameConstraints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_NameConstraints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_NameConstraints",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_NameConstraints",
      "type": "topic",
      "url": "/documentation/security/dt_nameconstraints"
    },
    "doc://com.apple.security/documentation/Security/DT_NetscapeCertType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_NetscapeCertType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_NetscapeCertType",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_NetscapeCertType",
      "type": "topic",
      "url": "/documentation/security/dt_netscapecerttype"
    },
    "doc://com.apple.security/documentation/Security/DT_Other": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_Other"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_Other",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_Other",
      "type": "topic",
      "url": "/documentation/security/dt_other"
    },
    "doc://com.apple.security/documentation/Security/DT_PolicyConstraints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_PolicyConstraints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_PolicyConstraints",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_PolicyConstraints",
      "type": "topic",
      "url": "/documentation/security/dt_policyconstraints"
    },
    "doc://com.apple.security/documentation/Security/DT_PolicyMappings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_PolicyMappings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_PolicyMappings",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_PolicyMappings",
      "type": "topic",
      "url": "/documentation/security/dt_policymappings"
    },
    "doc://com.apple.security/documentation/Security/DT_QC_Statements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_QC_Statements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_QC_Statements",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_QC_Statements",
      "type": "topic",
      "url": "/documentation/security/dt_qc_statements"
    },
    "doc://com.apple.security/documentation/Security/DT_SubjectAltName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_SubjectAltName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_SubjectAltName",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_SubjectAltName",
      "type": "topic",
      "url": "/documentation/security/dt_subjectaltname"
    },
    "doc://com.apple.security/documentation/Security/DT_SubjectKeyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DT_SubjectKeyID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/DT_SubjectKeyID",
      "kind": "symbol",
      "role": "symbol",
      "title": "DT_SubjectKeyID",
      "type": "topic",
      "url": "/documentation/security/dt_subjectkeyid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/DT_AuthorityInfoAccess",
        "doc://com.apple.security/documentation/Security/DT_AuthorityKeyID",
        "doc://com.apple.security/documentation/Security/DT_BasicConstraints",
        "doc://com.apple.security/documentation/Security/DT_CertPolicies",
        "doc://com.apple.security/documentation/Security/DT_CrlDistributionPoints",
        "doc://com.apple.security/documentation/Security/DT_CrlNumber",
        "doc://com.apple.security/documentation/Security/DT_CrlReason",
        "doc://com.apple.security/documentation/Security/DT_DeltaCrl",
        "doc://com.apple.security/documentation/Security/DT_ExtendedKeyUsage",
        "doc://com.apple.security/documentation/Security/DT_InhibitAnyPolicy",
        "doc://com.apple.security/documentation/Security/DT_IssuerAltName",
        "doc://com.apple.security/documentation/Security/DT_IssuingDistributionPoint",
        "doc://com.apple.security/documentation/Security/DT_KeyUsage",
        "doc://com.apple.security/documentation/Security/DT_NameConstraints",
        "doc://com.apple.security/documentation/Security/DT_NetscapeCertType",
        "doc://com.apple.security/documentation/Security/DT_Other",
        "doc://com.apple.security/documentation/Security/DT_PolicyConstraints",
        "doc://com.apple.security/documentation/Security/DT_PolicyMappings",
        "doc://com.apple.security/documentation/Security/DT_QC_Statements",
        "doc://com.apple.security/documentation/Security/DT_SubjectAltName",
        "doc://com.apple.security/documentation/Security/DT_SubjectKeyID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CE_DataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@__CE_DataType",
                    "text": "__CE_DataType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CE_DataType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_DataType/title",
          "value": "CE_DataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_DataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_DataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/ce_datatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/ce_datatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
