{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CE_GeneralNameType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CE_GeneralNameType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CE_GeneralNameType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CE_GeneralNameType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CE_GeneralNameType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CE_GeneralNameType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "text": "__CE_GeneralNameType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CE_GeneralNameType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CE_GeneralNameType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CE_GeneralNameType"
        }
      ],
      "role": "symbol",
      "title": "CE_GeneralNameType",
      "type": "topic",
      "url": "/documentation/security/ce_generalnametype"
    },
    "doc://com.apple.security/documentation/Security/GNT_DNSName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_DNSName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_DNSName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_DNSName",
      "type": "topic",
      "url": "/documentation/security/gnt_dnsname"
    },
    "doc://com.apple.security/documentation/Security/GNT_DirectoryName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_DirectoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_DirectoryName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_DirectoryName",
      "type": "topic",
      "url": "/documentation/security/gnt_directoryname"
    },
    "doc://com.apple.security/documentation/Security/GNT_EdiPartyName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_EdiPartyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_EdiPartyName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_EdiPartyName",
      "type": "topic",
      "url": "/documentation/security/gnt_edipartyname"
    },
    "doc://com.apple.security/documentation/Security/GNT_IPAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_IPAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_IPAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_IPAddress",
      "type": "topic",
      "url": "/documentation/security/gnt_ipaddress"
    },
    "doc://com.apple.security/documentation/Security/GNT_OtherName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_OtherName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_OtherName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_OtherName",
      "type": "topic",
      "url": "/documentation/security/gnt_othername"
    },
    "doc://com.apple.security/documentation/Security/GNT_RFC822Name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_RFC822Name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_RFC822Name",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_RFC822Name",
      "type": "topic",
      "url": "/documentation/security/gnt_rfc822name"
    },
    "doc://com.apple.security/documentation/Security/GNT_RegisteredID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_RegisteredID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_RegisteredID",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_RegisteredID",
      "type": "topic",
      "url": "/documentation/security/gnt_registeredid"
    },
    "doc://com.apple.security/documentation/Security/GNT_URI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_URI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_URI",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_URI",
      "type": "topic",
      "url": "/documentation/security/gnt_uri"
    },
    "doc://com.apple.security/documentation/Security/GNT_X400Address": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GNT_X400Address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_GeneralNameType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/GNT_X400Address",
      "kind": "symbol",
      "role": "symbol",
      "title": "GNT_X400Address",
      "type": "topic",
      "url": "/documentation/security/gnt_x400address"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/GNT_DNSName",
        "doc://com.apple.security/documentation/Security/GNT_DirectoryName",
        "doc://com.apple.security/documentation/Security/GNT_EdiPartyName",
        "doc://com.apple.security/documentation/Security/GNT_IPAddress",
        "doc://com.apple.security/documentation/Security/GNT_OtherName",
        "doc://com.apple.security/documentation/Security/GNT_RFC822Name",
        "doc://com.apple.security/documentation/Security/GNT_RegisteredID",
        "doc://com.apple.security/documentation/Security/GNT_URI",
        "doc://com.apple.security/documentation/Security/GNT_X400Address"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CE_GeneralNameType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_GeneralNameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_GeneralNameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@__CE_GeneralNameType",
                    "text": "__CE_GeneralNameType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CE_GeneralNameType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_GeneralNameType/title",
          "value": "CE_GeneralNameType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_GeneralNameType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_GeneralNameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_GeneralNameType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_GeneralNameType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/ce_generalnametype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/ce_generalnametype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
