{
  "abstract": [
    {
      "text": "Use these four character values to indicate certificate item attributes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/certificates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/certificate-item-attribute-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Certificate Item Attribute Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/certificates": {
      "abstract": [
        {
          "text": "Manage digital certificates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificates",
      "type": "topic",
      "url": "/documentation/security/certificates"
    },
    "doc://com.apple.security/documentation/Security/kSecCertEncodingItemAttr": {
      "abstract": [
        {
          "text": "Certificate encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCertEncodingItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCertEncodingItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCertEncodingItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecCertEncodingItemAttr",
      "type": "topic",
      "url": "/documentation/security/kseccertencodingitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecCertTypeItemAttr": {
      "abstract": [
        {
          "text": "Certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCertTypeItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCertTypeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCertTypeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecCertTypeItemAttr",
      "type": "topic",
      "url": "/documentation/security/kseccerttypeitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecIssuerItemAttr": {
      "abstract": [
        {
          "text": "DER-encoded issuer distinguished name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecIssuerItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecIssuerItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecIssuerItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecIssuerItemAttr",
      "type": "topic",
      "url": "/documentation/security/ksecissueritemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecPublicKeyHashItemAttr": {
      "abstract": [
        {
          "text": "Public key hash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPublicKeyHashItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPublicKeyHashItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPublicKeyHashItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecPublicKeyHashItemAttr",
      "type": "topic",
      "url": "/documentation/security/ksecpublickeyhashitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecSerialNumberItemAttr": {
      "abstract": [
        {
          "text": "DER-encoded certificate serial number (without the tag and length).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecSerialNumberItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecSerialNumberItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSerialNumberItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecSerialNumberItemAttr",
      "type": "topic",
      "url": "/documentation/security/ksecserialnumberitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecSubjectItemAttr": {
      "abstract": [
        {
          "text": "DER-encoded subject distinguished name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecSubjectItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecSubjectItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSubjectItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecSubjectItemAttr",
      "type": "topic",
      "url": "/documentation/security/ksecsubjectitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecSubjectKeyIdentifierItemAttr": {
      "abstract": [
        {
          "text": "Subject key identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecSubjectKeyIdentifierItemAttr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecSubjectKeyIdentifierItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSubjectKeyIdentifierItemAttr"
        }
      ],
      "role": "symbol",
      "title": "kSecSubjectKeyIdentifierItemAttr",
      "type": "topic",
      "url": "/documentation/security/ksecsubjectkeyidentifieritemattr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecSubjectItemAttr",
        "doc://com.apple.security/documentation/Security/kSecIssuerItemAttr",
        "doc://com.apple.security/documentation/Security/kSecSerialNumberItemAttr",
        "doc://com.apple.security/documentation/Security/kSecPublicKeyHashItemAttr",
        "doc://com.apple.security/documentation/Security/kSecSubjectKeyIdentifierItemAttr",
        "doc://com.apple.security/documentation/Security/kSecCertTypeItemAttr",
        "doc://com.apple.security/documentation/Security/kSecCertEncodingItemAttr"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecSubjectItemAttr",
                "doc://com.apple.security/documentation/Security/kSecIssuerItemAttr",
                "doc://com.apple.security/documentation/Security/kSecSerialNumberItemAttr",
                "doc://com.apple.security/documentation/Security/kSecPublicKeyHashItemAttr",
                "doc://com.apple.security/documentation/Security/kSecSubjectKeyIdentifierItemAttr",
                "doc://com.apple.security/documentation/Security/kSecCertTypeItemAttr",
                "doc://com.apple.security/documentation/Security/kSecCertEncodingItemAttr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSubjectKeyIdentifierItemAttr/title",
          "value": "kSecSubjectKeyIdentifierItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSubjectKeyIdentifierItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSubjectKeyIdentifierItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPublicKeyHashItemAttr/title",
          "value": "kSecPublicKeyHashItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPublicKeyHashItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPublicKeyHashItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCertTypeItemAttr/title",
          "value": "kSecCertTypeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCertTypeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCertTypeItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIssuerItemAttr/title",
          "value": "kSecIssuerItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIssuerItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecIssuerItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSerialNumberItemAttr/title",
          "value": "kSecSerialNumberItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSerialNumberItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSerialNumberItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCertEncodingItemAttr/title",
          "value": "kSecCertEncodingItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCertEncodingItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCertEncodingItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSubjectItemAttr/title",
          "value": "kSecSubjectItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSubjectItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSubjectItemAttr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/certificate-item-attribute-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/certificate-item-attribute-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
