{
  "abstract": [
    {
      "text": "Recognize the possible certificate property types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/certificates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/certificate-property-type-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Certificate Property Type Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These are the possible values that may be assigned to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyKeyType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in each of the property dictionaries returned by a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyValues(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCertificateCopyValues(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a dictionary that represents a certificate’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificateCopyValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyValues(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificateCopyValues"
        }
      ],
      "role": "symbol",
      "title": "SecCertificateCopyValues(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccertificatecopyvalues(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/certificates": {
      "abstract": [
        {
          "text": "Manage digital certificates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificates",
      "type": "topic",
      "url": "/documentation/security/certificates"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyKeyType": {
      "abstract": [
        {
          "text": "A key whose value indicates the type of certificate property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyKeyType"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyKeyType",
      "type": "topic",
      "url": "/documentation/security/ksecpropertykeytype"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeArray": {
      "abstract": [
        {
          "text": "Specifies a key whose value is an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeArray"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeArray",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypearray"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeData": {
      "abstract": [
        {
          "text": "A key whose value is a data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeData"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeData",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypedata"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeDate": {
      "abstract": [
        {
          "text": "Specifies a key whose value is a string containing a date (or a string listing the bytes of an invalid date).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeDate"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeDate",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypedate"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeError": {
      "abstract": [
        {
          "text": "Specifies a key whose value is a string containing the reason for a trust evaluation failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeError"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeError",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypeerror"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeNumber": {
      "abstract": [
        {
          "text": "Specifies a key whose value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeNumber"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeNumber",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypenumber"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeSection": {
      "abstract": [
        {
          "text": "A key whose value is a string describing the name of a field in the certificate (",
          "type": "text"
        },
        {
          "code": "CFSTR(\"Subject Name\")",
          "type": "codeVoice"
        },
        {
          "text": ", for example).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeSection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeSection"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeSection",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypesection"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeString": {
      "abstract": [
        {
          "text": "A key whose value is a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeString"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeString",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypestring"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeSuccess": {
      "abstract": [
        {
          "text": "A key whose value is a string describing a trust evaluation success.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeSuccess"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeSuccess",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypesuccess"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeTitle": {
      "abstract": [
        {
          "text": "Specifies a key whose value is a string containing the title (display name) of the certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeTitle"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeTitle",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypetitle"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeURL": {
      "abstract": [
        {
          "text": "Specifies a key whose value is a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeURL"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeURL",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypeurl"
    },
    "doc://com.apple.security/documentation/Security/kSecPropertyTypeWarning": {
      "abstract": [
        {
          "text": "A key whose value is a string describing a trust evaluation warning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeWarning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPropertyTypeWarning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPropertyTypeWarning"
        }
      ],
      "role": "symbol",
      "title": "kSecPropertyTypeWarning",
      "type": "topic",
      "url": "/documentation/security/ksecpropertytypewarning"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeWarning",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeSuccess",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeSection",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeData",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeString",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeURL",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeDate",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeArray",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeNumber",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeTitle",
        "doc://com.apple.security/documentation/Security/kSecPropertyTypeError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeWarning",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeSuccess",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeSection",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeData",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeString",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeURL",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeDate",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeArray",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeNumber",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeTitle",
                "doc://com.apple.security/documentation/Security/kSecPropertyTypeError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeArray/title",
          "value": "kSecPropertyTypeArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeSection/title",
          "value": "kSecPropertyTypeSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeSection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeNumber/title",
          "value": "kSecPropertyTypeNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeString/title",
          "value": "kSecPropertyTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeTitle/title",
          "value": "kSecPropertyTypeTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeDate/title",
          "value": "kSecPropertyTypeDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeWarning/title",
          "value": "kSecPropertyTypeWarning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeWarning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeWarning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeError/title",
          "value": "kSecPropertyTypeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyValues(_:_:_:)/title",
          "value": "SecCertificateCopyValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyValues(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeSuccess/title",
          "value": "kSecPropertyTypeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeData/title",
          "value": "kSecPropertyTypeData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeURL/title",
          "value": "kSecPropertyTypeURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyTypeURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyTypeURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyKeyType/title",
          "value": "kSecPropertyKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPropertyKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPropertyKeyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/certificate-property-type-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/certificate-property-type-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
