{
  "abstract": [
    {
      "text": "Obtains an array of all of the certificates in a message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CMSDecoderCopyAllCerts(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSDecoderCopyAllCerts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSDecoderCopyAllCerts"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSDecoderRef",
        "text": "CMSDecoder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSDecoderCopyAllCerts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSDecoderCopyAllCerts(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSDecoderCopyAllCerts"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cmsDecoder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSDecoder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSDecoderRef",
              "text": "CMSDecoder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "certsOut"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The CMSDecoder reference returned by the ",
                  "type": "text"
                },
                {
                  "code": "CMSDecoderCreate",
                  "type": "codeVoice"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cmsDecoder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to an array of ",
                  "type": "text"
                },
                {
                  "code": "SecCertificateRef",
                  "type": "codeVoice"
                },
                {
                  "text": " objects. Returns ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if the message does not contain any certificates (the message was encrypted but not signed); this is not considered an error. You must use the ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": " function to free this reference when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "certsOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A CMS message can contain arbitrary sets of certificates other than or in addition to those indicating the identity of signers. You can use this function to retrieve such certificates from a message. If the message was signed, it contains signer certificates. You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderCopySignerCert(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions to retrieve the certificates for a specific signer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You cannot call this function until after you have called the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderFinalizeMessage(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoder": {
      "abstract": [
        {
          "text": "An opaque reference to a CMS decoder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoder"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoder"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoder",
      "type": "topic",
      "url": "/documentation/security/cmsdecoder"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderCopyAllCerts(_:_:)": {
      "abstract": [
        {
          "text": "Obtains an array of all of the certificates in a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderCopyAllCerts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderCopyAllCerts(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderCopyAllCerts"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderCopyAllCerts(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecodercopyallcerts(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderCopySignerCert(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the certificate of the specified signer of a CMS message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderCopySignerCert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderCopySignerCert(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderCopySignerCert"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderCopySignerCert(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecodercopysignercert(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a CMSDecoder reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderCreate"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderCreate(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecodercreate(_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderFinalizeMessage(_:)": {
      "abstract": [
        {
          "text": "Indicates that there is no more data to decode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderFinalizeMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderFinalizeMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderFinalizeMessage"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderFinalizeMessage(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecoderfinalizemessage(_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of signers of a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderGetNumSigners"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderGetNumSigners"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderGetNumSigners(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecodergetnumsigners(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)": {
      "abstract": [
        {
          "text": "Adds certificates to a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSupportingCerts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSupportingCerts"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderAddSupportingCerts(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencoderaddsupportingcerts(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSDecoderCopySignerCert(_:_:_:)",
        "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)",
        "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
        "doc://com.apple.security/documentation/Security/CMSDecoderCreate(_:)",
        "doc://com.apple.security/documentation/Security/CMSDecoderFinalizeMessage(_:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSDecoderCopyAllCerts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderCopyAllCerts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CMSDecoderCopySignerCert(_:_:_:)",
                "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)",
                "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
                "doc://com.apple.security/documentation/Security/CMSDecoderCreate(_:)",
                "doc://com.apple.security/documentation/Security/CMSDecoderFinalizeMessage(_:)"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSDecoderCopyAllCerts"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CMSDecoder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSDecoderRef",
                    "text": "CMSDecoderRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cmsDecoder"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "certsOut"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The CMSDecoder reference returned by the ",
                        "type": "text"
                      },
                      {
                        "code": "CMSDecoderCreate",
                        "type": "codeVoice"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cmsDecoder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, points to an array of ",
                        "type": "text"
                      },
                      {
                        "code": "SecCertificateRef",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects. Returns ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the message does not contain any certificates (the message was encrypted but not signed); this is not considered an error. You must use the ",
                        "type": "text"
                      },
                      {
                        "code": "CFRelease",
                        "type": "codeVoice"
                      },
                      {
                        "text": " function to free this reference when you are finished using it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "certsOut"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSupportingCerts(_:_:)/title",
          "value": "CMSEncoderAddSupportingCerts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSupportingCerts(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderAddSupportingCerts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoder/title",
          "value": "CMSDecoderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCopyAllCerts(_:_:)/title",
          "value": "CMSDecoderCopyAllCerts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCopyAllCerts(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderCopyAllCerts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCopySignerCert(_:_:_:)/title",
          "value": "CMSDecoderCopySignerCert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCopySignerCert(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderCopySignerCert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCreate(_:)/title",
          "value": "CMSDecoderCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderFinalizeMessage(_:)/title",
          "value": "CMSDecoderFinalizeMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderFinalizeMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderFinalizeMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderGetNumSigners(_:_:)/title",
          "value": "CMSDecoderGetNumSigners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderGetNumSigners(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderGetNumSigners"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmsdecodercopyallcerts(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cmsdecodercopyallcerts(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
