{
  "abstract": [
    {
      "text": "Encodes a message and obtains the result in one high-level function call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CMSEncode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSEncode",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMSEncode"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSEncode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSEncode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSEncode"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "signers"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recipients"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_data",
              "text": "SecAsn1Oid"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "eContentType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Boolean",
              "text": "Boolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "detachedContent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMSSignedAttributes",
              "text": "CMSSignedAttributes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "signedAttributes"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "content"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@size_t",
              "text": "size_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "contentLen"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDataRef",
              "text": "CFDataRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "encodedContentOut"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identity object for the identity of one signer, specified as type ",
                  "type": "text"
                },
                {
                  "code": "SecIdentityRef",
                  "type": "codeVoice"
                },
                {
                  "text": ", or a ",
                  "type": "text"
                },
                {
                  "code": "CFArray",
                  "type": "codeVoice"
                },
                {
                  "text": " of identity objects of type",
                  "type": "text"
                },
                {
                  "code": "SecIdentityRef",
                  "type": "codeVoice"
                },
                {
                  "text": ". Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for this parameter if you do not want to sign the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "signers"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A certificate containing a public encryption key for one message recipient, specified as a certificate object (type ",
                  "type": "text"
                },
                {
                  "code": "SecCertificateRef",
                  "type": "codeVoice"
                },
                {
                  "text": "), or a ",
                  "type": "text"
                },
                {
                  "code": "CFArray",
                  "type": "codeVoice"
                },
                {
                  "text": " of certificate objects. Pass NULL for this parameter if you do not want to encrypt the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recipients"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object identifier for the encapsulated data in a signed message. This parameter is optional. If you pass ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ", the value ",
                  "type": "text"
                },
                {
                  "code": "id-data",
                  "type": "codeVoice"
                },
                {
                  "text": " is used. (This is the normal encapsulated content type for applications such as S/MIME, which uses it to indicate MIME-encoded content.) You can pass any value that is meaningful to your application.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eContentType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specify ",
                  "type": "text"
                },
                {
                  "code": "TRUE",
                  "type": "codeVoice"
                },
                {
                  "text": " if the signed data is to be separate from the message; that is, if the message is_not_ to include the data to be signed. You cannot specify ",
                  "type": "text"
                },
                {
                  "code": "TRUE",
                  "type": "codeVoice"
                },
                {
                  "text": " for this parameter for an encrypted message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "detachedContent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Attribute flags as defined in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Attributes are optional for signed messages and are not used in other types of CMS messages. The use of attributes is described in section 2.5 of the S/MIME 3.1 specification.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "signedAttributes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content that you want to add to the message. The content must conform to the type set in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderSetEncapsulatedContentType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " parameter (or type ",
                  "type": "text"
                },
                {
                  "code": "id-data",
                  "type": "codeVoice"
                },
                {
                  "text": " if that function has not been called).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "content"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The length of the content being added, in bytes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contentLen"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the encoded message. You must use the ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": " function to free this reference when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "encodedContentOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use this function, you must include content and you must provide valid non-",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " input for at least one of the ",
              "type": "text"
            },
            {
              "code": "signers",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "recipients",
              "type": "codeVoice"
            },
            {
              "text": " parameters. You can both encrypt and sign a message; however, you cannot use detached content with an encrypted message. If you want to create a message that contains certificates and no other content, you must use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function instead of this one. To gain more control over the process of encoding a message, call the sequence of functions beginning with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function instead of this one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncodeContent(_:_:_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for new development.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSEncode": {
      "abstract": [
        {
          "text": "Encodes a message and obtains the result in one high-level function call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMSEncode"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncode",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSEncode",
      "type": "topic",
      "url": "/documentation/security/cmsencode"
    },
    "doc://com.apple.security/documentation/Security/CMSEncodeContent(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Encodes a message and obtains the result in one high-level function call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncodeContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncodeContent(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncodeContent"
        }
      ],
      "role": "symbol",
      "title": "CMSEncodeContent(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodecontent(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)": {
      "abstract": [
        {
          "text": "Adds certificates to a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSupportingCerts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSupportingCerts"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderAddSupportingCerts(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencoderaddsupportingcerts(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a CMSEncoder reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCreate(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercreate(_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderSetEncapsulatedContentType": {
      "abstract": [
        {
          "text": "Specifies an object identifier for the encapsulated data of a signed message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMSEncoderSetEncapsulatedContentType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderSetEncapsulatedContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSEncoderSetEncapsulatedContentType",
      "type": "topic",
      "url": "/documentation/security/cmsencodersetencapsulatedcontenttype"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes": {
      "abstract": [
        {
          "text": "Optional attributes you can add to a signed message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSSignedAttributes"
        }
      ],
      "role": "symbol",
      "title": "CMSSignedAttributes",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes"
    },
    "doc://com.apple.security/documentation/Security/cssm_data-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "role": "symbol",
      "title": "cssm_data",
      "type": "topic",
      "url": "/documentation/security/cssm_data-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDataRef": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
        "doc://com.apple.security/documentation/Security/CMSEncoderAddSupportingCerts(_:_:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncodeContent(_:_:_:_:_:_:_:_:)/title",
          "value": "CMSEncodeContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncodeContent(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncodeContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/title",
          "value": "CMSSignedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/title",
          "value": "CMSEncoderCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/title",
          "value": "cssm_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSupportingCerts(_:_:)/title",
          "value": "CMSEncoderAddSupportingCerts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSupportingCerts(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderAddSupportingCerts"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmsencode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
