{
  "abstract": [
    {
      "text": "Obtains the array of recipients specified with the ",
      "type": "text"
    },
    {
      "code": "CMSEncoderAddRecipients",
      "type": "codeVoice"
    },
    {
      "text": " function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CMSEncoderCopyRecipients(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSEncoderCopyRecipients",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSEncoderCopyRecipients"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSEncoderRef",
        "text": "CMSEncoder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSEncoderCopyRecipients"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSEncoderCopyRecipients(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSEncoderCopyRecipients"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cmsEncoder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSEncoderRef",
              "text": "CMSEncoder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recipientsOut"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The CMSEncoder reference returned by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cmsEncoder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to an array of certificate objects of type ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " of the recipients of the message. If the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function has not been called for this message, this function returns a ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " array. You must use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to free this reference when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recipientsOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoder": {
      "abstract": [
        {
          "text": "Opaque reference to a CMS encoder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoder",
      "type": "topic",
      "url": "/documentation/security/cmsencoder"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)": {
      "abstract": [
        {
          "text": "Specifies a message is to be encrypted and specifies the recipients of the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderAddRecipients"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderAddRecipients"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderAddRecipients(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencoderaddrecipients(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCopyRecipients(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the array of recipients specified with the ",
          "type": "text"
        },
        {
          "code": "CMSEncoderAddRecipients",
          "type": "codeVoice"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCopyRecipients"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCopyRecipients(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCopyRecipients"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCopyRecipients(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercopyrecipients(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a CMSEncoder reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCreate(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercreate(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecCertificate": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an X.509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "role": "symbol",
      "title": "SecCertificate",
      "type": "topic",
      "url": "/documentation/security/seccertificate"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
        "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSEncoderCopyRecipients"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCopyRecipients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
                "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSEncoderCopyRecipients"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSEncoderRef",
                    "text": "CMSEncoderRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cmsEncoder"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "recipientsOut"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The CMSEncoder reference returned by the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cmsEncoder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, points to an array of certificate objects of type ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " of the recipients of the message. If the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddRecipients(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function has not been called for this message, this function returns a ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array. You must use the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function to free this reference when you are finished using it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "recipientsOut"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/title",
          "value": "SecCertificateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddRecipients(_:_:)/title",
          "value": "CMSEncoderAddRecipients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddRecipients(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderAddRecipients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/title",
          "value": "CMSEncoderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/title",
          "value": "CMSEncoderCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopyRecipients(_:_:)/title",
          "value": "CMSEncoderCopyRecipients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopyRecipients(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCopyRecipients"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmsencodercopyrecipients(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cmsencodercopyrecipients(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
