{
  "abstract": [
    {
      "text": "Returns the timestamp of a signer of a CMS message using a particular policy, if present.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSEncoderCopySignerTimestampWithPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSEncoderCopySignerTimestampWithPolicy"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSEncoderRef",
        "text": "CMSEncoder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeRef",
        "text": "CFTypeRef"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAbsoluteTime",
        "text": "CFAbsoluteTime"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSEncoderCopySignerTimestampWithPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSEncoderCopySignerTimestampWithPolicy"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cmsEncoder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSEncoderRef",
              "text": "CMSEncoder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "timeStampPolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "signerIndex"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "timestamp"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAbsoluteTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAbsoluteTime",
              "text": "CFAbsoluteTime"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A CMSEncoder reference returned by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cmsEncoder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A timestamp policy. Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " (or use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestamp(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function instead) to get the default, which is a policy using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/policies",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more about policies.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "timeStampPolicy"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A number indicating which signer to examine. Signer index numbers start with 0. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to determine the total number of signers for a message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "signerIndex"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The address of an absolute time value where the result should be stored.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "timestamp"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of signers of a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSDecoderGetNumSigners"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSDecoderRef",
          "text": "CMSDecoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSDecoderGetNumSigners"
        }
      ],
      "role": "symbol",
      "title": "CMSDecoderGetNumSigners(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsdecodergetnumsigners(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoder": {
      "abstract": [
        {
          "text": "Opaque reference to a CMS encoder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoder",
      "type": "topic",
      "url": "/documentation/security/cmsencoder"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestamp(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the timestamp of a signer of a CMS message, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCopySignerTimestamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestamp(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCopySignerTimestamp"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCopySignerTimestamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercopysignertimestamp(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the timestamp of a signer of a CMS message using a particular policy, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCopySignerTimestampWithPolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCopySignerTimestampWithPolicy"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercopysignertimestampwithpolicy(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a CMSEncoder reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCreate(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercreate(_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping": {
      "abstract": [
        {
          "text": "Policy that causes evaluation of the validity of the time stamp on a signature. This can be used to allow verification that a certificate was valid at the time that something was signed with that certificate even if the certificate is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleTimeStamping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleTimeStamping"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleTimeStamping",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappletimestamping"
    },
    "doc://com.apple.security/documentation/Security/policies": {
      "abstract": [
        {
          "text": "Obtain policies for establishing trust.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/policies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Policies",
      "type": "topic",
      "url": "/documentation/security/policies"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAbsoluteTime": {
      "abstract": [
        {
          "text": "Type used to represent a specific point in time relative to the absolute reference date of 1 Jan 2001 00:00:00 GMT.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAbsoluteTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAbsoluteTime",
      "type": "topic",
      "url": "/documentation/corefoundation/cfabsolutetime"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSEncoderCopySignerTimestampWithPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCopySignerTimestampWithPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSEncoderCopySignerTimestampWithPolicy"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSEncoderRef",
                    "text": "CMSEncoderRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cmsEncoder"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeRef",
                    "text": "CFTypeRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timeStampPolicy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "signerIndex"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAbsoluteTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAbsoluteTime",
                    "text": "CFAbsoluteTime"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timestamp"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A CMSEncoder reference returned by the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cmsEncoder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A timestamp policy. Specify ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " (or use the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCopySignerTimestamp(_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function instead) to get the default, which is a policy using ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/policies",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for more about policies.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "timeStampPolicy"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A number indicating which signer to examine. Signer index numbers start with 0. Use the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSDecoderGetNumSigners(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function to determine the total number of signers for a message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "signerIndex"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The address of an absolute time value where the result should be stored.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "timestamp"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopySignerTimestamp(_:_:_:)/title",
          "value": "CMSEncoderCopySignerTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopySignerTimestamp(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCopySignerTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)/title",
          "value": "CMSEncoderCopySignerTimestampWithPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCopySignerTimestampWithPolicy(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCopySignerTimestampWithPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderGetNumSigners(_:_:)/title",
          "value": "CMSDecoderGetNumSigners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSDecoderGetNumSigners(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSDecoderGetNumSigners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleTimeStamping/title",
          "value": "kSecPolicyAppleTimeStamping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleTimeStamping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleTimeStamping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/title",
          "value": "CMSEncoderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/title",
          "value": "CMSEncoderCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCreate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmsencodercopysignertimestampwithpolicy(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cmsencodercopysignertimestampwithpolicy(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
