{
  "abstract": [
    {
      "text": "Specifies which certificates to include in a signed CMS message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CMSEncoderSetCertificateChainMode(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSEncoderSetCertificateChainMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSEncoderSetCertificateChainMode"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSEncoderRef",
        "text": "CMSEncoder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMSCertificateChainMode",
        "text": "CMSCertificateChainMode"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSEncoderSetCertificateChainMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSEncoderSetCertificateChainMode(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSEncoderSetCertificateChainMode"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cmsEncoder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSEncoderRef",
              "text": "CMSEncoder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "chainMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSCertificateChainMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMSCertificateChainMode",
              "text": "CMSCertificateChainMode"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The CMSEncoder reference returned by the ",
                  "type": "text"
                },
                {
                  "code": "CMSEncoderCreate",
                  "type": "codeVoice"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cmsEncoder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A constant that indicates which certificate or certificates to include in the message. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/CMSCertificateChainMode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "chainMode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is used only for signed messages and is optional. If you don’t call this function, the default, ",
              "type": "text"
            },
            {
              "code": "kCMSCertificateChain",
              "type": "codeVoice"
            },
            {
              "text": ", is used. In this case the message includes the signer certificate plus all certificates needed to verify the signer certificate, up to but not including the root  certificate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do call this function, you must call it before the first call to the ",
              "type": "text"
            },
            {
              "code": "CMSEncoderUpdateContent",
              "type": "codeVoice"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSCertificateChainMode": {
      "abstract": [
        {
          "text": "Constants that can be set to specify what certificates to include in a signed message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSCertificateChainMode"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSCertificateChainMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSCertificateChainMode"
        }
      ],
      "role": "symbol",
      "title": "CMSCertificateChainMode",
      "type": "topic",
      "url": "/documentation/security/cmscertificatechainmode"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoder": {
      "abstract": [
        {
          "text": "Opaque reference to a CMS encoder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoder"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoder",
      "type": "topic",
      "url": "/documentation/security/cmsencoder"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a CMSEncoder reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderCreate"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderCreate(_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodercreate(_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderGetCertificateChainMode(_:_:)": {
      "abstract": [
        {
          "text": "Obtains a constant that indicates which certificates are to be included in a signed CMS message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderGetCertificateChainMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSCertificateChainMode",
          "text": "CMSCertificateChainMode"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderGetCertificateChainMode(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderGetCertificateChainMode"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderGetCertificateChainMode(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodergetcertificatechainmode(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderSetCertificateChainMode(_:_:)": {
      "abstract": [
        {
          "text": "Specifies which certificates to include in a signed CMS message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderSetCertificateChainMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSCertificateChainMode",
          "text": "CMSCertificateChainMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderSetCertificateChainMode(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderSetCertificateChainMode"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderSetCertificateChainMode(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencodersetcertificatechainmode(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderUpdateContent(_:_:_:)": {
      "abstract": [
        {
          "text": "Feeds content bytes into the encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderUpdateContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderUpdateContent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderUpdateContent"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderUpdateContent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencoderupdatecontent(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSEncoderUpdateContent(_:_:_:)",
        "doc://com.apple.security/documentation/Security/CMSEncoderGetCertificateChainMode(_:_:)",
        "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSEncoderSetCertificateChainMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderSetCertificateChainMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CMSEncoderUpdateContent(_:_:_:)",
                "doc://com.apple.security/documentation/Security/CMSEncoderGetCertificateChainMode(_:_:)",
                "doc://com.apple.security/documentation/Security/CMSEncoderCreate(_:)"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSEncoderSetCertificateChainMode"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CMSEncoder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSEncoderRef",
                    "text": "CMSEncoderRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cmsEncoder"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CMSCertificateChainMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CMSCertificateChainMode",
                    "text": "CMSCertificateChainMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "chainMode"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The CMSEncoder reference returned by the ",
                        "type": "text"
                      },
                      {
                        "code": "CMSEncoderCreate",
                        "type": "codeVoice"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cmsEncoder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A constant that indicates which certificate or certificates to include in the message. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/CMSCertificateChainMode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "chainMode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSCertificateChainMode/title",
          "value": "CMSCertificateChainMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSCertificateChainMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSCertificateChainMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSCertificateChainMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSCertificateChainMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderSetCertificateChainMode(_:_:)/title",
          "value": "CMSEncoderSetCertificateChainMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderSetCertificateChainMode(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderSetCertificateChainMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderUpdateContent(_:_:_:)/title",
          "value": "CMSEncoderUpdateContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderUpdateContent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderUpdateContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/title",
          "value": "CMSEncoderCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderGetCertificateChainMode(_:_:)/title",
          "value": "CMSEncoderGetCertificateChainMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderGetCertificateChainMode(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderGetCertificateChainMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/title",
          "value": "CMSEncoderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmsencodersetcertificatechainmode(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cmsencodersetcertificatechainmode(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
