{
  "abstract": [
    {
      "text": "Optional attributes you can add to a signed message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CMSSignedAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMSSignedAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSSignedAttributes"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSSignedAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CMSSignedAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these flags with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddSignedAttributes(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to cause the encoder to add attributes to a signed message that can be interpreted by the recipient. These attributes are not used for unsigned messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CMSEncoderAddSignedAttributes(_:_:)": {
      "abstract": [
        {
          "text": "Specifies attributes for a signed message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSignedAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSEncoderRef",
          "text": "CMSEncoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSEncoderAddSignedAttributes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSEncoderAddSignedAttributes"
        }
      ],
      "role": "symbol",
      "title": "CMSEncoderAddSignedAttributes(_:_:)",
      "type": "topic",
      "url": "/documentation/security/cmsencoderaddsignedattributes(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes": {
      "abstract": [
        {
          "text": "Optional attributes you can add to a signed message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSSignedAttributes"
        }
      ],
      "role": "symbol",
      "title": "CMSSignedAttributes",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgility": {
      "abstract": [
        {
          "text": "Include Apple codesigning hash agility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrAppleCodesigningHashAgility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrAppleCodesigningHashAgility"
        }
      ],
      "role": "symbol",
      "title": "attrAppleCodesigningHashAgility",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrapplecodesigninghashagility"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgilityV2": {
      "abstract": [
        {
          "text": "Include Apple codesigning hash agility, version 2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrAppleCodesigningHashAgilityV2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgilityV2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrAppleCodesigningHashAgilityV2"
        }
      ],
      "role": "symbol",
      "title": "attrAppleCodesigningHashAgilityV2",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrapplecodesigninghashagilityv2"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleExpirationTime": {
      "abstract": [
        {
          "text": "Include the expiration time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrAppleExpirationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleExpirationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrAppleExpirationTime"
        }
      ],
      "role": "symbol",
      "title": "attrAppleExpirationTime",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrappleexpirationtime"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSigningTime": {
      "abstract": [
        {
          "text": "Include the signing time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrSigningTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSigningTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrSigningTime"
        }
      ],
      "role": "symbol",
      "title": "attrSigningTime",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrsigningtime"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeCapabilities": {
      "abstract": [
        {
          "text": "Identify signature, encryption, and digest algorithms supported by the encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrSmimeCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrSmimeCapabilities"
        }
      ],
      "role": "symbol",
      "title": "attrSmimeCapabilities",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrsmimecapabilities"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeEncryptionKeyPrefs": {
      "abstract": [
        {
          "text": "Indicate that the signing certificate included with the message is the preferred one for S/MIME encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrSmimeEncryptionKeyPrefs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeEncryptionKeyPrefs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrSmimeEncryptionKeyPrefs"
        }
      ],
      "role": "symbol",
      "title": "attrSmimeEncryptionKeyPrefs",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrsmimeencryptionkeyprefs"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeMSEncryptionKeyPrefs": {
      "abstract": [
        {
          "text": "Indicate that the signing certificate included with the message is the preferred one for S/MIME encryption, but using an attribute object identifier (OID) preferred by Microsoft.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attrSmimeMSEncryptionKeyPrefs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMSSignedAttributes",
          "text": "CMSSignedAttributes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeMSEncryptionKeyPrefs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSAttrSmimeMSEncryptionKeyPrefs"
        }
      ],
      "role": "symbol",
      "title": "attrSmimeMSEncryptionKeyPrefs",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/attrsmimemsencryptionkeyprefs"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a new attributes structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/CMSSignedAttributes/kCMSAttrNone": {
      "abstract": [
        {
          "text": "No attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMSAttrNone"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CMSSignedAttributes/kCMSAttrNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMSAttrNone",
      "type": "topic",
      "url": "/documentation/security/cmssignedattributes/kcmsattrnone"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Attributes",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeCapabilities",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeEncryptionKeyPrefs",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeMSEncryptionKeyPrefs",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSigningTime",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgility",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgilityV2",
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleExpirationTime"
      ],
      "title": "Attributes"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CMSSignedAttributes/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSSignedAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Attributes",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/kCMSAttrNone",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeCapabilities",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeEncryptionKeyPrefs",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSmimeMSEncryptionKeyPrefs",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrSigningTime",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgility",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleCodesigningHashAgilityV2",
                "doc://com.apple.security/documentation/Security/CMSSignedAttributes/attrAppleExpirationTime"
              ],
              "title": "Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSSignedAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleExpirationTime/title",
          "value": "kCMSAttrAppleExpirationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleExpirationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrAppleExpirationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleCodesigningHashAgility/title",
          "value": "kCMSAttrAppleCodesigningHashAgility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleCodesigningHashAgility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrAppleCodesigningHashAgility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeCapabilities/title",
          "value": "kCMSAttrSmimeCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrSmimeCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/title",
          "value": "CMSSignedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleCodesigningHashAgilityV2/title",
          "value": "kCMSAttrAppleCodesigningHashAgilityV2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrAppleCodesigningHashAgilityV2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrAppleCodesigningHashAgilityV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSignedAttributes(_:_:)/title",
          "value": "CMSEncoderAddSignedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSEncoderAddSignedAttributes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSEncoderAddSignedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeEncryptionKeyPrefs/title",
          "value": "kCMSAttrSmimeEncryptionKeyPrefs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeEncryptionKeyPrefs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrSmimeEncryptionKeyPrefs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeMSEncryptionKeyPrefs/title",
          "value": "kCMSAttrSmimeMSEncryptionKeyPrefs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSmimeMSEncryptionKeyPrefs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrSmimeMSEncryptionKeyPrefs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSigningTime/title",
          "value": "kCMSAttrSigningTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CMSSignedAttributes~1attrSigningTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSAttrSigningTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cmssignedattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cmssignedattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
