{
  "abstract": [
    {
      "text": "Use these supplemental flags to retrieve signing information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/code-signing-information-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Code Signing Information Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to specify what type of information to return. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information about the information returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves various pieces of information from a code signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopySigningInformation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopysigninginformation(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecCSCalculateCMSDigest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSCalculateCMSDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSCalculateCMSDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSCalculateCMSDigest"
        }
      ],
      "role": "symbol",
      "title": "kSecCSCalculateCMSDigest",
      "type": "topic",
      "url": "/documentation/security/kseccscalculatecmsdigest"
    },
    "doc://com.apple.security/documentation/Security/kSecCSContentInformation": {
      "abstract": [
        {
          "text": "More information about the file system contents making up the signed code on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSContentInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSContentInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSContentInformation"
        }
      ],
      "role": "symbol",
      "title": "kSecCSContentInformation",
      "type": "topic",
      "url": "/documentation/security/kseccscontentinformation"
    },
    "doc://com.apple.security/documentation/Security/kSecCSDynamicInformation": {
      "abstract": [
        {
          "text": "Dynamic validity information about running code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSDynamicInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSDynamicInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSDynamicInformation"
        }
      ],
      "role": "symbol",
      "title": "kSecCSDynamicInformation",
      "type": "topic",
      "url": "/documentation/security/kseccsdynamicinformation"
    },
    "doc://com.apple.security/documentation/Security/kSecCSInternalInformation": {
      "abstract": [
        {
          "text": "Internal code signing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSInternalInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSInternalInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSInternalInformation"
        }
      ],
      "role": "symbol",
      "title": "kSecCSInternalInformation",
      "type": "topic",
      "url": "/documentation/security/kseccsinternalinformation"
    },
    "doc://com.apple.security/documentation/Security/kSecCSRequirementInformation": {
      "abstract": [
        {
          "text": "Code requirements—including the designated requirement—embedded in the code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSRequirementInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSRequirementInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSRequirementInformation"
        }
      ],
      "role": "symbol",
      "title": "kSecCSRequirementInformation",
      "type": "topic",
      "url": "/documentation/security/kseccsrequirementinformation"
    },
    "doc://com.apple.security/documentation/Security/kSecCSSigningInformation": {
      "abstract": [
        {
          "text": "Cryptographic signing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSSigningInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSSigningInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSSigningInformation"
        }
      ],
      "role": "symbol",
      "title": "kSecCSSigningInformation",
      "type": "topic",
      "url": "/documentation/security/kseccssigninginformation"
    },
    "doc://com.apple.security/documentation/Security/kSecCSSkipResourceDirectory": {
      "abstract": [
        {
          "text": "Suppress validating the resource directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSSkipResourceDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSSkipResourceDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSSkipResourceDirectory"
        }
      ],
      "role": "symbol",
      "title": "kSecCSSkipResourceDirectory",
      "type": "topic",
      "url": "/documentation/security/kseccsskipresourcedirectory"
    },
    "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys": {
      "abstract": [
        {
          "text": "Use these keys from the information dictionary when you retrieve information from a code signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Signing Information Dictionary Keys",
      "type": "topic",
      "url": "/documentation/security/signing-information-dictionary-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecCSInternalInformation",
        "doc://com.apple.security/documentation/Security/kSecCSSigningInformation",
        "doc://com.apple.security/documentation/Security/kSecCSRequirementInformation",
        "doc://com.apple.security/documentation/Security/kSecCSDynamicInformation",
        "doc://com.apple.security/documentation/Security/kSecCSContentInformation",
        "doc://com.apple.security/documentation/Security/kSecCSSkipResourceDirectory",
        "doc://com.apple.security/documentation/Security/kSecCSCalculateCMSDigest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecCSInternalInformation",
                "doc://com.apple.security/documentation/Security/kSecCSSigningInformation",
                "doc://com.apple.security/documentation/Security/kSecCSRequirementInformation",
                "doc://com.apple.security/documentation/Security/kSecCSDynamicInformation",
                "doc://com.apple.security/documentation/Security/kSecCSContentInformation",
                "doc://com.apple.security/documentation/Security/kSecCSSkipResourceDirectory",
                "doc://com.apple.security/documentation/Security/kSecCSCalculateCMSDigest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCalculateCMSDigest/title",
          "value": "kSecCSCalculateCMSDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCalculateCMSDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSCalculateCMSDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/title",
          "value": "SecCodeCopySigningInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopySigningInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSigningInformation/title",
          "value": "kSecCSSigningInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSigningInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSSigningInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDynamicInformation/title",
          "value": "kSecCSDynamicInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDynamicInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSDynamicInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSContentInformation/title",
          "value": "kSecCSContentInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSContentInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSContentInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSInternalInformation/title",
          "value": "kSecCSInternalInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSInternalInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSInternalInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSkipResourceDirectory/title",
          "value": "kSecCSSkipResourceDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSkipResourceDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSSkipResourceDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRequirementInformation/title",
          "value": "kSecCSRequirementInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRequirementInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSRequirementInformation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/code-signing-information-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/code-signing-information-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
