{
  "abstract": [
    {
      "text": "Use these supplemental flags to get static code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/code-signing-architecture-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Code Signing Architecture Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These flags supplement the flags described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use these additional constants with the ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the ",
          "type": "text"
        },
        {
          "code": "flags",
          "type": "codeVoice"
        },
        {
          "text": " parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a static code object representing the on-disk version of the given running code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopyStaticCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopyStaticCode"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopyStaticCode(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopystaticcode(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecCSUseAllArchitectures": {
      "abstract": [
        {
          "text": "Flag for requesting all architectures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSUseAllArchitectures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSUseAllArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSUseAllArchitectures"
        }
      ],
      "role": "symbol",
      "title": "kSecCSUseAllArchitectures",
      "type": "topic",
      "url": "/documentation/security/kseccsuseallarchitectures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecCSUseAllArchitectures"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecCSUseAllArchitectures"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSUseAllArchitectures/title",
          "value": "kSecCSUseAllArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSUseAllArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSUseAllArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyStaticCode(_:_:_:)/title",
          "value": "SecCodeCopyStaticCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyStaticCode(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopyStaticCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/title",
          "value": "SecCSFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/code-signing-architecture-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/code-signing-architecture-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
