{
  "abstract": [
    {
      "text": "Specify these keys from the attribute dictionary when you create a static code instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/code-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Code Attributes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys in the attribute dictionary when calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a static code object representing the code at a specified file system path using an attributes dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCodeCreateWithPathAndAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecStaticCodeCreateWithPathAndAttributes"
        }
      ],
      "role": "symbol",
      "title": "SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secstaticcodecreatewithpathandattributes(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeAttributeArchitecture": {
      "abstract": [
        {
          "text": "A key whose value is a string that indicates an architecture, such as ",
          "type": "text"
        },
        {
          "code": "i386",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "x86_64",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeArchitecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeAttributeArchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeArchitecture"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeAttributeArchitecture",
      "type": "topic",
      "url": "/documentation/security/kseccodeattributearchitecture"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeAttributeBundleVersion": {
      "abstract": [
        {
          "text": "A key whose value indicates the bundle version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeBundleVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeAttributeBundleVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeBundleVersion"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeAttributeBundleVersion",
      "type": "topic",
      "url": "/documentation/security/kseccodeattributebundleversion"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeAttributeSubarchitecture": {
      "abstract": [
        {
          "text": "A key whose value is a string indicating a specific processor type, such as ",
          "type": "text"
        },
        {
          "code": "i686",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "core2",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeSubarchitecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeAttributeSubarchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeSubarchitecture"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeAttributeSubarchitecture",
      "type": "topic",
      "url": "/documentation/security/kseccodeattributesubarchitecture"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeAttributeUniversalFileOffset": {
      "abstract": [
        {
          "text": "A key whose value indicates the offset of a Mach-O specific slice of a universal Mach-O file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeUniversalFileOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeAttributeUniversalFileOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeAttributeUniversalFileOffset"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeAttributeUniversalFileOffset",
      "type": "topic",
      "url": "/documentation/security/kseccodeattributeuniversalfileoffset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecCodeAttributeArchitecture",
        "doc://com.apple.security/documentation/Security/kSecCodeAttributeSubarchitecture",
        "doc://com.apple.security/documentation/Security/kSecCodeAttributeBundleVersion",
        "doc://com.apple.security/documentation/Security/kSecCodeAttributeUniversalFileOffset"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecCodeAttributeArchitecture",
                "doc://com.apple.security/documentation/Security/kSecCodeAttributeSubarchitecture",
                "doc://com.apple.security/documentation/Security/kSecCodeAttributeBundleVersion",
                "doc://com.apple.security/documentation/Security/kSecCodeAttributeUniversalFileOffset"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeBundleVersion/title",
          "value": "kSecCodeAttributeBundleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeBundleVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeAttributeBundleVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeUniversalFileOffset/title",
          "value": "kSecCodeAttributeUniversalFileOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeUniversalFileOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeAttributeUniversalFileOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeArchitecture/title",
          "value": "kSecCodeAttributeArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeArchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeAttributeArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeSubarchitecture/title",
          "value": "kSecCodeAttributeSubarchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeAttributeSubarchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeAttributeSubarchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)/title",
          "value": "SecStaticCodeCreateWithPathAndAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCreateWithPathAndAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecStaticCodeCreateWithPathAndAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/code-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/code-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
