{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.security/documentation/Security"]]},"variants":[{"paths":["/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo"}],"metadata":{"roleHeading":"Structure","externalID":"c:@S@cssm_acl_keychain_prompt_selector","symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"title":"cssm_acl_keychain_prompt_selector","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"role":"symbol","platforms":[{"introducedAt":"10.0","deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"modules":[{"name":"Security"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cssm_acl_keychain_prompt_selector","kind":"identifier"}]}]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init()","doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init(version:flags:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/flags","doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/version"]}],"references":{"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"abstract":[],"role":"symbol","title":"cssm_acl_keychain_prompt_selector","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"identifier":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct","url":"/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct"},"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init(version:flags:)":{"abstract":[],"title":"init(version:flags:)","identifier":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init(version:flags:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint16","kind":"typeIdentifier","text":"uint16"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flags"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint16","kind":"typeIdentifier","text":"uint16"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct/init(version:flags:)"},"doc://com.apple.security/documentation/Security":{"title":"Security","abstract":[{"text":"Secure the data your app manages, and control access to your app.","type":"text"}],"identifier":"doc://com.apple.security/documentation/Security","kind":"symbol","url":"/documentation/security","type":"topic","role":"collection"},"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/version":{"abstract":[],"title":"version","identifier":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/version","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint16","kind":"typeIdentifier","text":"uint16"}],"type":"topic","url":"/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct/version","navigatorTitle":[{"kind":"identifier","text":"version"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","url":"/documentation/Swift/BitwiseCopyable","abstract":[{"text":"","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"kind":"symbol","role":"symbol","title":"BitwiseCopyable"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","kind":"symbol","type":"topic","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sendable"}],"title":"Sendable"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init()":{"abstract":[],"title":"init()","identifier":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/init()","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","url":"/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct/init()"},"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/flags":{"abstract":[],"title":"flags","identifier":"doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/flags","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flags"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint16","kind":"typeIdentifier","text":"uint16"}],"type":"topic","url":"/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct/flags","navigatorTitle":[{"kind":"identifier","text":"flags"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"introducedAt":"10.0","unavailable":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"op":"replace","value":"Structure","path":"/metadata/roleHeading"},{"op":"replace","value":"cssm_acl_keychain_prompt_selector","path":"/metadata/title"},{"op":"replace","value":"struct","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"cssm_acl_keychain_prompt_selector","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.security/documentation/Security"]]},"path":"/hierarchy"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/flags","doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct/version"],"title":"Instance Properties"}],"path":"/topicSections"},{"op":"replace","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/title","value":"cssm_acl_keychain_prompt_selector","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/fragments","value":[{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/navigatorTitle","value":[{"kind":"identifier","text":"cssm_acl_keychain_prompt_selector"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct~1version/title","value":"version","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct~1version/fragments","value":[{"kind":"identifier","text":"version"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct~1flags/title","value":"flags","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct~1flags/fragments","value":[{"kind":"identifier","text":"flags"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}