{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CSSM_APPLE_TP_CRL_OPTIONS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_CRL_OPTIONS"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_CRL_OPTIONS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CSSM_APPLE_TP_CRL_OPTIONS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPTIONS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CRL_OPTIONS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_TP_CRL_OPTIONS",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/CrlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CrlFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_APPLE_TP_CRL_OPT_FLAGS",
          "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/CrlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CrlFlags"
        }
      ],
      "role": "symbol",
      "title": "CrlFlags",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/crlflags"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/Version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/Version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Version"
        }
      ],
      "role": "symbol",
      "title": "Version",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/version"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/crlStore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crlStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_dl_db_handle",
          "text": "cssm_dl_db_handle"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/crlStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "crlStore"
        }
      ],
      "role": "symbol",
      "title": "crlStore",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/crlstore"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/init()"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "CrlFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_APPLE_TP_CRL_OPT_FLAGS",
          "text": "CSSM_APPLE_TP_CRL_OPT_FLAGS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "crlStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_dl_db_handle",
          "text": "cssm_dl_db_handle"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(Version:CrlFlags:crlStore:)",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_crl_options/init(version:crlflags:crlstore:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init()",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/init(Version:CrlFlags:crlStore:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/CrlFlags",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/Version",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/crlStore"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSSM_APPLE_TP_CRL_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/CrlFlags",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/Version",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CRL_OPTIONS/crlStore"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSSM_APPLE_TP_CRL_OPTIONS"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1Version/title",
          "value": "Version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1Version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1CrlFlags/title",
          "value": "CrlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1CrlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CrlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/title",
          "value": "CSSM_APPLE_TP_CRL_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CRL_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1crlStore/title",
          "value": "crlStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CRL_OPTIONS~1crlStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "crlStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_crl_options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_crl_options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
