{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_DL_DbCreate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_DL_DbCreate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_DL_DbCreate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_DL_DbCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_DL_DbCreate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_DL_DbCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DL_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DL_HANDLE",
              "text": "CSSM_DL_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "DLHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "DbName"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_net_address-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_net_address",
              "text": "CSSM_NET_ADDRESS"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "DbLocation"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_dbinfo-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_dbinfo",
              "text": "CSSM_DBINFO"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "DBInfo"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_ACCESS_TYPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_ACCESS_TYPE",
              "text": "CSSM_DB_ACCESS_TYPE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "AccessRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_resource_control_context-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_resource_control_context",
              "text": "CSSM_RESOURCE_CONTROL_CONTEXT"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "CredAndAclEntry"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "OpenParameters"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_HANDLE",
              "text": "CSSM_DB_HANDLE"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "DbHandle"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_ACCESS_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_DB_ACCESS_TYPE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_ACCESS_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_ACCESS_TYPE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_DB_ACCESS_TYPE",
      "type": "topic",
      "url": "/documentation/security/cssm_db_access_type"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_DB_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_DB_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_db_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DL_DbCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_DL_DbCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DL_DbCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_DL_DbCreate",
      "type": "topic",
      "url": "/documentation/security/cssm_dl_dbcreate"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DL_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_DL_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DL_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_DL_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_DL_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_dl_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/cssm_dbinfo-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_dbinfo"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_dbinfo-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_dbinfo",
      "type": "topic",
      "url": "/documentation/security/cssm_dbinfo-c.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_net_address-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_net_address"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_net_address-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_net_address",
      "type": "topic",
      "url": "/documentation/security/cssm_net_address-c.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_resource_control_context-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_resource_control_context"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_resource_control_context-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_resource_control_context",
      "type": "topic",
      "url": "/documentation/security/cssm_resource_control_context-c.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_ACCESS_TYPE/title",
          "value": "CSSM_DB_ACCESS_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_ACCESS_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_ACCESS_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_ACCESS_TYPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_ACCESS_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_HANDLE/title",
          "value": "CSSM_DB_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DL_HANDLE/title",
          "value": "CSSM_DL_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DL_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DL_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DL_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DL_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_dl_dbcreate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
