{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_DL_DataGetNext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_DL_DataGetNext",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_DL_DataGetNext"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_DL_DataGetNext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_DL_DataGetNext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_DL_DataGetNext"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_dl_db_handle",
              "text": "CSSM_DL_DB_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "DLDBHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_HANDLE",
              "text": "CSSM_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ResultsHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR",
              "text": "CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Attributes"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DATA_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DATA_PTR",
              "text": "CSSM_DATA_PTR"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_UNIQUE_RECORD_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_UNIQUE_RECORD_PTR",
              "text": "CSSM_DB_UNIQUE_RECORD_PTR"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "UniqueId"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DATA_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_DATA_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DATA_PTR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_DATA_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_data_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_DB_RECORD_ATTRIBUTE_DATA_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_db_record_attribute_data_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_UNIQUE_RECORD_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_UNIQUE_RECORD_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_UNIQUE_RECORD_PTR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_DB_UNIQUE_RECORD_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_db_unique_record_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DL_DataGetNext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_DL_DataGetNext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DL_DataGetNext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_DL_DataGetNext",
      "type": "topic",
      "url": "/documentation/security/cssm_dl_datagetnext"
    },
    "doc://com.apple.security/documentation/Security/CSSM_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_dl_db_handle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_dl_db_handle-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_dl_db_handle"
        }
      ],
      "role": "symbol",
      "title": "cssm_dl_db_handle",
      "type": "topic",
      "url": "/documentation/security/cssm_dl_db_handle-swift.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_HANDLE/title",
          "value": "CSSM_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/title",
          "value": "cssm_dl_db_handle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_dl_db_handle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_dl_db_handle-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_dl_db_handle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_dl_datagetnext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
