{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_CL_CertGroupFromVerifiedBundle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_CL_CertGroupFromVerifiedBundle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_CL_CertGroupFromVerifiedBundle"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_CL_CertGroupFromVerifiedBundle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_CL_CertGroupFromVerifiedBundle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_CL_CertGroupFromVerifiedBundle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CL_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CL_HANDLE",
              "text": "CSSM_CL_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "CLHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CC_HANDLE",
              "text": "CSSM_CC_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "CCHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_cert_bundle-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_cert_bundle",
              "text": "CSSM_CERT_BUNDLE"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "CertBundle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_data",
              "text": "SecAsn1Item"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "SignerCert"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CERTGROUP_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CERTGROUP_PTR",
              "text": "CSSM_CERTGROUP_PTR"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "CertGroup"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CC_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CC_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CC_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_cc_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CERTGROUP_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_CERTGROUP_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CERTGROUP_PTR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_CERTGROUP_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_certgroup_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CL_CertGroupFromVerifiedBundle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_CL_CertGroupFromVerifiedBundle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CL_CertGroupFromVerifiedBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_CL_CertGroupFromVerifiedBundle",
      "type": "topic",
      "url": "/documentation/security/cssm_cl_certgroupfromverifiedbundle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CL_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CL_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CL_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CL_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CL_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_cl_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/cssm_cert_bundle-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_cert_bundle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_cert_bundle-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_cert_bundle",
      "type": "topic",
      "url": "/documentation/security/cssm_cert_bundle-c.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_data-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "role": "symbol",
      "title": "cssm_data",
      "type": "topic",
      "url": "/documentation/security/cssm_data-swift.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/title",
          "value": "cssm_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CL_HANDLE/title",
          "value": "CSSM_CL_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CL_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CL_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CL_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CL_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/title",
          "value": "CSSM_CC_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CC_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CC_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_cl_certgroupfromverifiedbundle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
