{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CSSM_APPLE_TP_CERT_REQUEST",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_CERT_REQUEST"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_CERT_REQUEST"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CSSM_APPLE_TP_CERT_REQUEST"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CERT_REQUEST"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CERT_REQUEST"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_CERT_REQUEST"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_TP_CERT_REQUEST",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/certPublicKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/certPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "certPublicKey"
        }
      ],
      "role": "symbol",
      "title": "certPublicKey",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/certpublickey"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/challengeString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challengeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/challengeString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "challengeString"
        }
      ],
      "role": "symbol",
      "title": "challengeString",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/challengestring"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/clHand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CL_HANDLE",
          "text": "CSSM_CL_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/clHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clHand"
        }
      ],
      "role": "symbol",
      "title": "clHand",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/clhand"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/cspHand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cspHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/cspHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cspHand"
        }
      ],
      "role": "symbol",
      "title": "cspHand",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/csphand"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/extensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataAndType"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/extensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensions"
        }
      ],
      "role": "symbol",
      "title": "extensions",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/extensions"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/init()"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init(cspHand:clHand:serialNumber:numSubjectNames:subjectNames:numIssuerNames:issuerNames:issuerNameX509:certPublicKey:issuerPrivateKey:signatureAlg:signatureOid:notBefore:notAfter:numExtensions:extensions:challengeString:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cspHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
          "text": "CSSM_CSP_HANDLE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CL_HANDLE",
          "text": "CSSM_CL_HANDLE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numSubjectNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subjectNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CSSM_APPLE_TP_NAME_OID",
          "text": "CSSM_APPLE_TP_NAME_OID"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "numIssuerNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "issuerNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CSSM_APPLE_TP_NAME_OID",
          "text": "CSSM_APPLE_TP_NAME_OID"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "issuerNameX509"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_x509_name",
          "text": "cssm_x509_name"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "certPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "issuerPrivateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "signatureAlg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_ALGORITHMS",
          "text": "CSSM_ALGORITHMS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signatureOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAsn1Oid",
          "text": "SecAsn1Oid"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "notBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "notAfter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numExtensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "__CE_DataAndType"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "challengeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init(cspHand:clHand:serialNumber:numSubjectNames:subjectNames:numIssuerNames:issuerNames:issuerNameX509:certPublicKey:issuerPrivateKey:signatureAlg:signatureOid:notBefore:notAfter:numExtensions:extensions:challengeString:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(cspHand:clHand:serialNumber:numSubjectNames:subjectNames:numIssuerNames:issuerNames:issuerNameX509:certPublicKey:issuerPrivateKey:signatureAlg:signatureOid:notBefore:notAfter:numExtensions:extensions:challengeString:)",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/init(csphand:clhand:serialnumber:numsubjectnames:subjectnames:numissuernames:issuernames:issuernamex509:certpublickey:issuerprivatekey:signaturealg:signatureoid:notbefore:notafter:numextensions:extensions:challengestring:)"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNameX509": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "issuerNameX509"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_x509_name",
          "text": "cssm_x509_name"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNameX509",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "issuerNameX509"
        }
      ],
      "role": "symbol",
      "title": "issuerNameX509",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/issuernamex509"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNames": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "issuerNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CSSM_APPLE_TP_NAME_OID",
          "text": "CSSM_APPLE_TP_NAME_OID"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "issuerNames"
        }
      ],
      "role": "symbol",
      "title": "issuerNames",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/issuernames"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerPrivateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "issuerPrivateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerPrivateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "issuerPrivateKey"
        }
      ],
      "role": "symbol",
      "title": "issuerPrivateKey",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/issuerprivatekey"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notAfter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAfter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notAfter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notAfter"
        }
      ],
      "role": "symbol",
      "title": "notAfter",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/notafter"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notBefore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notBefore"
        }
      ],
      "role": "symbol",
      "title": "notBefore",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/notbefore"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numExtensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numExtensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numExtensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numExtensions"
        }
      ],
      "role": "symbol",
      "title": "numExtensions",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/numextensions"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numIssuerNames": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numIssuerNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numIssuerNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numIssuerNames"
        }
      ],
      "role": "symbol",
      "title": "numIssuerNames",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/numissuernames"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numSubjectNames": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numSubjectNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numSubjectNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numSubjectNames"
        }
      ],
      "role": "symbol",
      "title": "numSubjectNames",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/numsubjectnames"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/serialNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/serialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serialNumber"
        }
      ],
      "role": "symbol",
      "title": "serialNumber",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/serialnumber"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureAlg": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureAlg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_ALGORITHMS",
          "text": "CSSM_ALGORITHMS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureAlg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signatureAlg"
        }
      ],
      "role": "symbol",
      "title": "signatureAlg",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/signaturealg"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureOid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAsn1Oid",
          "text": "SecAsn1Oid"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureOid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signatureOid"
        }
      ],
      "role": "symbol",
      "title": "signatureOid",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/signatureoid"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/subjectNames": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CSSM_APPLE_TP_NAME_OID",
          "text": "CSSM_APPLE_TP_NAME_OID"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/subjectNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subjectNames"
        }
      ],
      "role": "symbol",
      "title": "subjectNames",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_cert_request/subjectnames"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init()",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/init(cspHand:clHand:serialNumber:numSubjectNames:subjectNames:numIssuerNames:issuerNames:issuerNameX509:certPublicKey:issuerPrivateKey:signatureAlg:signatureOid:notBefore:notAfter:numExtensions:extensions:challengeString:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/certPublicKey",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/challengeString",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/clHand",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/cspHand",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/extensions",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNameX509",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNames",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerPrivateKey",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notAfter",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notBefore",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numExtensions",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numIssuerNames",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numSubjectNames",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/serialNumber",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureAlg",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureOid",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/subjectNames"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSSM_APPLE_TP_CERT_REQUEST"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CERT_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CERT_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/certPublicKey",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/challengeString",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/clHand",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/cspHand",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/extensions",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNameX509",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerNames",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/issuerPrivateKey",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notAfter",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/notBefore",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numExtensions",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numIssuerNames",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/numSubjectNames",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/serialNumber",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureAlg",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/signatureOid",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_CERT_REQUEST/subjectNames"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSSM_APPLE_TP_CERT_REQUEST"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerNameX509/title",
          "value": "issuerNameX509"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerNameX509/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "issuerNameX509"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1clHand/title",
          "value": "clHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1clHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1certPublicKey/title",
          "value": "certPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1certPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "certPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1challengeString/title",
          "value": "challengeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1challengeString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "challengeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numSubjectNames/title",
          "value": "numSubjectNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numSubjectNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numSubjectNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numIssuerNames/title",
          "value": "numIssuerNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numIssuerNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numIssuerNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1serialNumber/title",
          "value": "serialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1serialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numExtensions/title",
          "value": "numExtensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1numExtensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numExtensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1subjectNames/title",
          "value": "subjectNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1subjectNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subjectNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1signatureOid/title",
          "value": "signatureOid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1signatureOid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signatureOid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1notBefore/title",
          "value": "notBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1notBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1notAfter/title",
          "value": "notAfter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1notAfter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notAfter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1cspHand/title",
          "value": "cspHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1cspHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cspHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerPrivateKey/title",
          "value": "issuerPrivateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerPrivateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "issuerPrivateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1extensions/title",
          "value": "extensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1extensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST/title",
          "value": "CSSM_APPLE_TP_CERT_REQUEST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CERT_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_CERT_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerNames/title",
          "value": "issuerNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1issuerNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "issuerNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1signatureAlg/title",
          "value": "signatureAlg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_CERT_REQUEST~1signatureAlg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signatureAlg"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_cert_request"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_cert_request"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
