{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@cssm_csp_operational_statistics",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cssm_csp_operational_statistics"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cssm_csp_operational_statistics"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "cssm_csp_operational_statistics"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cssm_csp_operational_statistics"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_csp_operational_statistics"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_csp_operational_statistics"
        }
      ],
      "role": "symbol",
      "title": "cssm_csp_operational_statistics",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/DeviceFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DeviceFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_FLAGS",
          "text": "CSSM_CSP_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/DeviceFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DeviceFlags"
        }
      ],
      "role": "symbol",
      "title": "DeviceFlags",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/deviceflags"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePrivateMem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenFreePrivateMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePrivateMem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenFreePrivateMem"
        }
      ],
      "role": "symbol",
      "title": "TokenFreePrivateMem",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenfreeprivatemem"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePublicMem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenFreePublicMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePublicMem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenFreePublicMem"
        }
      ],
      "role": "symbol",
      "title": "TokenFreePublicMem",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenfreepublicmem"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxRWSessionCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenMaxRWSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxRWSessionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenMaxRWSessionCount"
        }
      ],
      "role": "symbol",
      "title": "TokenMaxRWSessionCount",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenmaxrwsessioncount"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxSessionCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenMaxSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxSessionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenMaxSessionCount"
        }
      ],
      "role": "symbol",
      "title": "TokenMaxSessionCount",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenmaxsessioncount"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedRWSessionCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenOpenedRWSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedRWSessionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenOpenedRWSessionCount"
        }
      ],
      "role": "symbol",
      "title": "TokenOpenedRWSessionCount",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenopenedrwsessioncount"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedSessionCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenOpenedSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedSessionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenOpenedSessionCount"
        }
      ],
      "role": "symbol",
      "title": "TokenOpenedSessionCount",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokenopenedsessioncount"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPrivateMem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenTotalPrivateMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPrivateMem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenTotalPrivateMem"
        }
      ],
      "role": "symbol",
      "title": "TokenTotalPrivateMem",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokentotalprivatemem"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPublicMem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenTotalPublicMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPublicMem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenTotalPublicMem"
        }
      ],
      "role": "symbol",
      "title": "TokenTotalPublicMem",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/tokentotalpublicmem"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/UserAuthenticated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_BOOL",
          "text": "CSSM_BOOL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/UserAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "UserAuthenticated",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/userauthenticated"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/init()"
    },
    "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init(UserAuthenticated:DeviceFlags:TokenMaxSessionCount:TokenOpenedSessionCount:TokenMaxRWSessionCount:TokenOpenedRWSessionCount:TokenTotalPublicMem:TokenFreePublicMem:TokenTotalPrivateMem:TokenFreePrivateMem:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "UserAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_BOOL",
          "text": "CSSM_BOOL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "DeviceFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_FLAGS",
          "text": "CSSM_CSP_FLAGS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenMaxSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenOpenedSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenMaxRWSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenOpenedRWSessionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenTotalPublicMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenFreePublicMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenTotalPrivateMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "TokenFreePrivateMem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init(UserAuthenticated:DeviceFlags:TokenMaxSessionCount:TokenOpenedSessionCount:TokenMaxRWSessionCount:TokenOpenedRWSessionCount:TokenTotalPublicMem:TokenFreePublicMem:TokenTotalPrivateMem:TokenFreePrivateMem:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(UserAuthenticated:DeviceFlags:TokenMaxSessionCount:TokenOpenedSessionCount:TokenMaxRWSessionCount:TokenOpenedRWSessionCount:TokenTotalPublicMem:TokenFreePublicMem:TokenTotalPrivateMem:TokenFreePrivateMem:)",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_operational_statistics-swift.struct/init(userauthenticated:deviceflags:tokenmaxsessioncount:tokenopenedsessioncount:tokenmaxrwsessioncount:tokenopenedrwsessioncount:tokentotalpublicmem:tokenfreepublicmem:tokentotalprivatemem:tokenfreeprivatemem:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init()",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/init(UserAuthenticated:DeviceFlags:TokenMaxSessionCount:TokenOpenedSessionCount:TokenMaxRWSessionCount:TokenOpenedRWSessionCount:TokenTotalPublicMem:TokenFreePublicMem:TokenTotalPrivateMem:TokenFreePrivateMem:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/DeviceFlags",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePrivateMem",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePublicMem",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxRWSessionCount",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxSessionCount",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedRWSessionCount",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedSessionCount",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPrivateMem",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPublicMem",
        "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/UserAuthenticated"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cssm_csp_operational_statistics"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_csp_operational_statistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_csp_operational_statistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/DeviceFlags",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePrivateMem",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenFreePublicMem",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxRWSessionCount",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenMaxSessionCount",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedRWSessionCount",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenOpenedSessionCount",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPrivateMem",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/TokenTotalPublicMem",
                "doc://com.apple.security/documentation/Security/cssm_csp_operational_statistics-swift.struct/UserAuthenticated"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cssm_csp_operational_statistics"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenOpenedRWSessionCount/title",
          "value": "TokenOpenedRWSessionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenOpenedRWSessionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenOpenedRWSessionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1UserAuthenticated/title",
          "value": "UserAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1UserAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UserAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenMaxSessionCount/title",
          "value": "TokenMaxSessionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenMaxSessionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenMaxSessionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenFreePublicMem/title",
          "value": "TokenFreePublicMem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenFreePublicMem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenFreePublicMem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct/title",
          "value": "cssm_csp_operational_statistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_csp_operational_statistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_csp_operational_statistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenFreePrivateMem/title",
          "value": "TokenFreePrivateMem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenFreePrivateMem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenFreePrivateMem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1DeviceFlags/title",
          "value": "DeviceFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1DeviceFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DeviceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenTotalPublicMem/title",
          "value": "TokenTotalPublicMem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenTotalPublicMem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenTotalPublicMem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenOpenedSessionCount/title",
          "value": "TokenOpenedSessionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenOpenedSessionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenOpenedSessionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenMaxRWSessionCount/title",
          "value": "TokenMaxRWSessionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenMaxRWSessionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenMaxRWSessionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenTotalPrivateMem/title",
          "value": "TokenTotalPrivateMem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_csp_operational_statistics-swift.struct~1TokenTotalPrivateMem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TokenTotalPrivateMem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_csp_operational_statistics-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_csp_operational_statistics-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
