{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CSSM_APPLE_CL_CSR_REQUEST",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_CL_CSR_REQUEST"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_CL_CSR_REQUEST"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CSSM_APPLE_CL_CSR_REQUEST"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_CL_CSR_REQUEST"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_CL_CSR_REQUEST"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_CL_CSR_REQUEST",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/challengeString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challengeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/challengeString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "challengeString"
        }
      ],
      "role": "symbol",
      "title": "challengeString",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/challengestring"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cspHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cspHand"
        }
      ],
      "role": "symbol",
      "title": "cspHand",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/csphand"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/init()"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init(subjectNameX509:signatureAlg:signatureOid:cspHand:subjectPublicKey:subjectPrivateKey:challengeString:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "subjectNameX509"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_x509_name",
          "text": "cssm_x509_name"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "signatureAlg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_ALGORITHMS",
          "text": "CSSM_ALGORITHMS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signatureOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAsn1Oid",
          "text": "SecAsn1Oid"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cspHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
          "text": "CSSM_CSP_HANDLE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subjectPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "subjectPrivateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "challengeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init(subjectNameX509:signatureAlg:signatureOid:cspHand:subjectPublicKey:subjectPrivateKey:challengeString:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(subjectNameX509:signatureAlg:signatureOid:cspHand:subjectPublicKey:subjectPrivateKey:challengeString:)",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/init(subjectnamex509:signaturealg:signatureoid:csphand:subjectpublickey:subjectprivatekey:challengestring:)"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureAlg": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureAlg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_ALGORITHMS",
          "text": "CSSM_ALGORITHMS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureAlg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signatureAlg"
        }
      ],
      "role": "symbol",
      "title": "signatureAlg",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/signaturealg"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureOid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAsn1Oid",
          "text": "SecAsn1Oid"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureOid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signatureOid"
        }
      ],
      "role": "symbol",
      "title": "signatureOid",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/signatureoid"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectNameX509": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectNameX509"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_x509_name",
          "text": "cssm_x509_name"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectNameX509",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subjectNameX509"
        }
      ],
      "role": "symbol",
      "title": "subjectNameX509",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/subjectnamex509"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPrivateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectPrivateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPrivateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subjectPrivateKey"
        }
      ],
      "role": "symbol",
      "title": "subjectPrivateKey",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/subjectprivatekey"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPublicKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cssm_key",
          "text": "cssm_key"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subjectPublicKey"
        }
      ],
      "role": "symbol",
      "title": "subjectPublicKey",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/subjectpublickey"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init()",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/init(subjectNameX509:signatureAlg:signatureOid:cspHand:subjectPublicKey:subjectPrivateKey:challengeString:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/challengeString",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureAlg",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureOid",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectNameX509",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPrivateKey",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPublicKey"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSSM_APPLE_CL_CSR_REQUEST"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/challengeString",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureAlg",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/signatureOid",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectNameX509",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPrivateKey",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/subjectPublicKey"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSSM_APPLE_CL_CSR_REQUEST"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1challengeString/title",
          "value": "challengeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1challengeString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "challengeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1signatureAlg/title",
          "value": "signatureAlg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1signatureAlg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signatureAlg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/title",
          "value": "CSSM_APPLE_CL_CSR_REQUEST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectPublicKey/title",
          "value": "subjectPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subjectPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectPrivateKey/title",
          "value": "subjectPrivateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectPrivateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subjectPrivateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectNameX509/title",
          "value": "subjectNameX509"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1subjectNameX509/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subjectNameX509"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1signatureOid/title",
          "value": "signatureOid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1signatureOid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signatureOid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1cspHand/title",
          "value": "cspHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1cspHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cspHand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_cl_csr_request"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_apple_cl_csr_request"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
