{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_FreeKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_FreeKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_FreeKey"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_FreeKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_FreeKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_FreeKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
              "text": "CSSM_CSP_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "CSPHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_access_credentials-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_access_credentials",
              "text": "CSSM_ACCESS_CREDENTIALS"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "AccessCred"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_KEY_PTR",
              "text": "CSSM_KEY_PTR"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "KeyPtr"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_BOOL",
              "text": "CSSM_BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Delete"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_BOOL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_BOOL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_BOOL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_BOOL"
        }
      ],
      "role": "symbol",
      "title": "CSSM_BOOL",
      "type": "topic",
      "url": "/documentation/security/cssm_bool"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CSP_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_FreeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_FreeKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_FreeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_FreeKey",
      "type": "topic",
      "url": "/documentation/security/cssm_freekey"
    },
    "doc://com.apple.security/documentation/Security/CSSM_KEY_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_KEY_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_PTR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_KEY_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_key_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/cssm_access_credentials-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_access_credentials"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_access_credentials-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_access_credentials",
      "type": "topic",
      "url": "/documentation/security/cssm_access_credentials-c.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/title",
          "value": "CSSM_BOOL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_BOOL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_BOOL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_BOOL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/title",
          "value": "CSSM_CSP_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_freekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
