{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_Init"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_Init",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_Init"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_Init"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_Init"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_Init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_version-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_version",
              "text": "CSSM_VERSION"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "Version"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_PRIVILEGE_SCOPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_PRIVILEGE_SCOPE",
              "text": "CSSM_PRIVILEGE_SCOPE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Scope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_guid",
              "text": "CSSM_GUID"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "CallerGuid"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_KEY_HIERARCHY",
              "text": "CSSM_KEY_HIERARCHY"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "KeyHierarchy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_PVC_MODE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_PVC_MODE",
              "text": "CSSM_PVC_MODE"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "PvcPolicy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "Reserved"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_Init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_Init"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_Init",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_Init",
      "type": "topic",
      "url": "/documentation/security/cssm_init"
    },
    "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_KEY_HIERARCHY"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_KEY_HIERARCHY"
        }
      ],
      "role": "symbol",
      "title": "CSSM_KEY_HIERARCHY",
      "type": "topic",
      "url": "/documentation/security/cssm_key_hierarchy"
    },
    "doc://com.apple.security/documentation/Security/CSSM_PRIVILEGE_SCOPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_PRIVILEGE_SCOPE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_PRIVILEGE_SCOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_PRIVILEGE_SCOPE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_PRIVILEGE_SCOPE",
      "type": "topic",
      "url": "/documentation/security/cssm_privilege_scope"
    },
    "doc://com.apple.security/documentation/Security/CSSM_PVC_MODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_PVC_MODE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_PVC_MODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_PVC_MODE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_PVC_MODE",
      "type": "topic",
      "url": "/documentation/security/cssm_pvc_mode"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_guid"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_guid"
        }
      ],
      "role": "symbol",
      "title": "cssm_guid",
      "type": "topic",
      "url": "/documentation/security/cssm_guid-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_version-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_version"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_version-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_version"
        }
      ],
      "role": "symbol",
      "title": "cssm_version",
      "type": "topic",
      "url": "/documentation/security/cssm_version-swift.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/title",
          "value": "CSSM_KEY_HIERARCHY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEY_HIERARCHY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEY_HIERARCHY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/title",
          "value": "cssm_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PRIVILEGE_SCOPE/title",
          "value": "CSSM_PRIVILEGE_SCOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PRIVILEGE_SCOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_PRIVILEGE_SCOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PRIVILEGE_SCOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_PRIVILEGE_SCOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/title",
          "value": "cssm_guid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_guid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_guid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PVC_MODE/title",
          "value": "CSSM_PVC_MODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PVC_MODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_PVC_MODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_PVC_MODE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_PVC_MODE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_init"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
