{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CSSM_ModuleAttach"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CSSM_ModuleAttach",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSM_ModuleAttach"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_ModuleAttach"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CSSM_ModuleAttach"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_RETURN",
              "text": "CSSM_RETURN"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_ModuleAttach"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_guid",
              "text": "CSSM_GUID"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "ModuleGuid"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_version-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_version",
              "text": "CSSM_VERSION"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "Version"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_API_MEMORY_FUNCS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_API_MEMORY_FUNCS",
              "text": "CSSM_API_MEMORY_FUNCS"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "MemoryFuncs"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "SubserviceID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_SERVICE_TYPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_SERVICE_TYPE",
              "text": "CSSM_SERVICE_TYPE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "SubServiceType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_ATTACH_FLAGS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_ATTACH_FLAGS",
              "text": "CSSM_ATTACH_FLAGS"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "AttachFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_KEY_HIERARCHY",
              "text": "CSSM_KEY_HIERARCHY"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "KeyHierarchy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_func_name_addr-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_func_name_addr",
              "text": "CSSM_FUNC_NAME_ADDR"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "FunctionTable"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "NumFunctionTable"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "Reserved"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_MODULE_HANDLE_PTR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_MODULE_HANDLE_PTR",
              "text": "CSSM_MODULE_HANDLE_PTR"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "NewModuleHandle"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_API_MEMORY_FUNCS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_API_MEMORY_FUNCS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_API_MEMORY_FUNCS",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_API_MEMORY_FUNCS",
      "type": "topic",
      "url": "/documentation/security/cssm_api_memory_funcs"
    },
    "doc://com.apple.security/documentation/Security/CSSM_ATTACH_FLAGS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_ATTACH_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_ATTACH_FLAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_ATTACH_FLAGS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_ATTACH_FLAGS",
      "type": "topic",
      "url": "/documentation/security/cssm_attach_flags"
    },
    "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_KEY_HIERARCHY"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEY_HIERARCHY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_KEY_HIERARCHY"
        }
      ],
      "role": "symbol",
      "title": "CSSM_KEY_HIERARCHY",
      "type": "topic",
      "url": "/documentation/security/cssm_key_hierarchy"
    },
    "doc://com.apple.security/documentation/Security/CSSM_MODULE_HANDLE_PTR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_MODULE_HANDLE_PTR"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_MODULE_HANDLE_PTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_MODULE_HANDLE_PTR"
        }
      ],
      "role": "symbol",
      "title": "CSSM_MODULE_HANDLE_PTR",
      "type": "topic",
      "url": "/documentation/security/cssm_module_handle_ptr"
    },
    "doc://com.apple.security/documentation/Security/CSSM_ModuleAttach": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSM_ModuleAttach"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_ModuleAttach",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSM_ModuleAttach",
      "type": "topic",
      "url": "/documentation/security/cssm_moduleattach"
    },
    "doc://com.apple.security/documentation/Security/CSSM_RETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_RETURN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_RETURN"
        }
      ],
      "role": "symbol",
      "title": "CSSM_RETURN",
      "type": "topic",
      "url": "/documentation/security/cssm_return"
    },
    "doc://com.apple.security/documentation/Security/CSSM_SERVICE_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_SERVICE_TYPE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_SERVICE_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_SERVICE_TYPE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_SERVICE_TYPE",
      "type": "topic",
      "url": "/documentation/security/cssm_service_type"
    },
    "doc://com.apple.security/documentation/Security/cssm_func_name_addr-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_func_name_addr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_func_name_addr-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_func_name_addr"
        }
      ],
      "role": "symbol",
      "title": "cssm_func_name_addr",
      "type": "topic",
      "url": "/documentation/security/cssm_func_name_addr-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_guid"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_guid-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_guid"
        }
      ],
      "role": "symbol",
      "title": "cssm_guid",
      "type": "topic",
      "url": "/documentation/security/cssm_guid-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_version-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_version"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_version-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_version"
        }
      ],
      "role": "symbol",
      "title": "cssm_version",
      "type": "topic",
      "url": "/documentation/security/cssm_version-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/security/uint32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/title",
          "value": "cssm_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_version-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_func_name_addr-swift.struct/title",
          "value": "cssm_func_name_addr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_func_name_addr-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_func_name_addr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_func_name_addr-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_func_name_addr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/title",
          "value": "CSSM_RETURN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_RETURN/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_RETURN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ATTACH_FLAGS/title",
          "value": "CSSM_ATTACH_FLAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ATTACH_FLAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ATTACH_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ATTACH_FLAGS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ATTACH_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/title",
          "value": "cssm_guid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_guid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_guid-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_guid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/title",
          "value": "CSSM_KEY_HIERARCHY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEY_HIERARCHY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEY_HIERARCHY/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEY_HIERARCHY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MODULE_HANDLE_PTR/title",
          "value": "CSSM_MODULE_HANDLE_PTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MODULE_HANDLE_PTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_MODULE_HANDLE_PTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MODULE_HANDLE_PTR/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_MODULE_HANDLE_PTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_SERVICE_TYPE/title",
          "value": "CSSM_SERVICE_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_SERVICE_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_SERVICE_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_SERVICE_TYPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_SERVICE_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/title",
          "value": "uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_moduleattach"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
