{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CSSM_APPLE_TP_SMIME_OPTIONS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CSSM_APPLE_TP_SMIME_OPTIONS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_TP_SMIME_OPTIONS",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/IntendedUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IntendedUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint16",
          "text": "uint16"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/IntendedUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntendedUsage"
        }
      ],
      "role": "symbol",
      "title": "IntendedUsage",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/intendedusage"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmail": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SenderEmail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SenderEmail"
        }
      ],
      "role": "symbol",
      "title": "SenderEmail",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/senderemail"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmailLen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SenderEmailLen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmailLen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SenderEmailLen"
        }
      ],
      "role": "symbol",
      "title": "SenderEmailLen",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/senderemaillen"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/Version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/Version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Version"
        }
      ],
      "role": "symbol",
      "title": "Version",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/version"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/init()"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init(Version:IntendedUsage:SenderEmailLen:SenderEmail:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "IntendedUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint16",
          "text": "uint16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "SenderEmailLen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "SenderEmail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init(Version:IntendedUsage:SenderEmailLen:SenderEmail:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(Version:IntendedUsage:SenderEmailLen:SenderEmail:)",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_tp_smime_options/init(version:intendedusage:senderemaillen:senderemail:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init()",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/init(Version:IntendedUsage:SenderEmailLen:SenderEmail:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/IntendedUsage",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmail",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmailLen",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/Version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSSM_APPLE_TP_SMIME_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/IntendedUsage",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmail",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/SenderEmailLen",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_TP_SMIME_OPTIONS/Version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS/title",
          "value": "CSSM_APPLE_TP_SMIME_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_TP_SMIME_OPTIONS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1IntendedUsage/title",
          "value": "IntendedUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1IntendedUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IntendedUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1SenderEmailLen/title",
          "value": "SenderEmailLen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1SenderEmailLen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SenderEmailLen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1Version/title",
          "value": "Version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1Version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1SenderEmail/title",
          "value": "SenderEmail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_TP_SMIME_OPTIONS~1SenderEmail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SenderEmail"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_smime_options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_apple_tp_smime_options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
