{
  "abstract": [
    {
      "text": "Modify the strong password rules for your app by adding your own restrictions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/password-autofill"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/customizing-password-autofill-rules"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Customizing Password AutoFill rules"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While automatic strong passwords generated by Password AutoFill are designed to be robust, your app may require its own restrictions in order to remain compatible with other technologies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To customize password rules for an automatically generated password, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or the ",
              "type": "text"
            },
            {
              "code": "passwordrules",
              "type": "codeVoice"
            },
            {
              "text": " attribute in the HTML input element in your webpage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value for these both of these properties must follow the same set of restrictions in the following form:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "required: (<identifier> | <character-class>), ..., (<identifier> | <character-class>); allowed: (<identifier> | <character-class>), ..., (<identifier> | <character-class>); max-consecutive: <non-negative-integer>"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use a combination of keywords to specify your rules:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Required or Allowed Keys:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use ",
                      "type": "text"
                    },
                    {
                      "code": "required",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the restrictions must be followed by all passwords; use ",
                      "type": "text"
                    },
                    {
                      "code": "allowed",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the restrictions specify a subset of allowed characters. If you don’t include the allowed property, all the required characters are permitted. If you include both properties, all the allowed and required characters are permitted. If neither are specified, then all ASCII printable characters are permitted",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Character Classes:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use a combination of ",
                      "type": "text"
                    },
                    {
                      "code": "upper",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (A-Z), ",
                      "type": "text"
                    },
                    {
                      "code": "lower",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (a-z), ",
                      "type": "text"
                    },
                    {
                      "code": "digits",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (0-9), ",
                      "type": "text"
                    },
                    {
                      "code": "special",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (-~!@#$%^&*_+=`|(){}[:;”’<>,.? ] and space), ",
                      "type": "text"
                    },
                    {
                      "code": "ascii-printable",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (all ASCII printable characters), or ",
                      "type": "text"
                    },
                    {
                      "code": "unicode",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (all unicode characters).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Maximum Length Key:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use ",
                      "type": "text"
                    },
                    {
                      "code": "max-consecutive",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to specify the maximum length of consecutive characters in your password. If you have multiple ",
                      "type": "text"
                    },
                    {
                      "code": "max-consecutive",
                      "type": "codeVoice"
                    },
                    {
                      "text": " properties in your rule, the minimum value of the properties will be applied. Without this property, the password can be of any length.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Custom Character Class:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " A ",
                      "type": "text"
                    },
                    {
                      "code": "<character-class>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is a custom characters class. This property consists of a list of ASCII characters surrounded by square brackets. For example, ",
                      "type": "text"
                    },
                    {
                      "code": "[abc]",
                      "type": "codeVoice"
                    },
                    {
                      "text": " only allows characters “a”, “b”, and “c”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Non-negative Integer Class:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " A ",
                      "type": "text"
                    },
                    {
                      "code": "<non-negative-integer>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is a valid non-negative integer. This property is used to specify the ",
                      "type": "text"
                    },
                    {
                      "code": "max-consecutive",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property, since the maximum length can’t be negative.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The default password rule is applied without any definition for the password rules property. It allows all ASCII printable characters, written as ",
              "type": "text"
            },
            {
              "code": "allowed: ascii-printable",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can combine these keywords to form your rule. Duplicate property values, empty character classes, and properties without a value are ignored. Don’t specify the ",
              "type": "text"
            },
            {
              "code": "pattern",
              "type": "codeVoice"
            },
            {
              "text": " property if using password rules. If you have two password fields (one for the password, one for confirmation), you don’t need to specify password rules for both fields when the user enters a new password.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The more restrictions you have on a password, the higher the likelihood that it can be guessed. The hardest-to-guess password rule is ",
                  "type": "text"
                },
                {
                  "code": "allowed: unicode",
                  "type": "codeVoice"
                },
                {
                  "text": ". No password rule at all creates the second most-difficult-to-guess passwords.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The specified password length can’t be less than 12, and the allowed characters must consist of at least 2 of the following classes: ASCII uppercase letters, ASCII lowercase letters, and digits. If your password restrictions don’t meet these guidelines after all the properties for your text field have been combined, they will be ignored by the user agent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Construct-a-password-rule",
          "level": 3,
          "text": "Construct a password rule",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, say you want to require a password with at least eight characters consisting of a mix of uppercase and lowercase letters, at least one number, and at most two consecutive characters. You’d add this markup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let newPasswordTextField = UITextField()",
                    "newPasswordTextField.passwordRules = UITextInputPasswordRules(descriptor: \"required: upper; required: lower; required: digit; max-consecutive: 2; minlength: 8;\")",
                    ""
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "<input type=\"password\" minlength=\"8\" passwordrules=\"required: upper; required: lower; required: digit; max-consecutive: 2\">",
                    ""
                  ],
                  "syntax": "html",
                  "type": "codeListing"
                }
              ],
              "title": "HTML"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "To require at least one digit or one special character, but not both, add this to your markup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let newPasswordTextField = UITextField()",
                    "newPasswordTextField.passwordRules = UITextInputPasswordRules(descriptor: \"required: upper; required: lower; required: digit, [-().&@?'#,/&quot;+]; max-consecutive: 2; minlength: 8;\") "
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "<input type=\"password\" minlength=\"8\" passwordrules=\"required: upper; required: lower; required: digit, [-().&@?'#,/&quot;+]; max-consecutive: 2\">",
                    ""
                  ],
                  "syntax": "html",
                  "type": "codeListing"
                }
              ],
              "title": "HTML"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Or, you could require at least one of a set of special characters ( ",
              "type": "text"
            },
            {
              "code": "-().&@?’#,/“+",
              "type": "codeVoice"
            },
            {
              "text": ") by adding this to your markup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let newPasswordTextField = UITextField()",
                    "newPasswordTextField.passwordRules = UITextInputPasswordRules(descriptor: \"required: upper; required: lower; required: digit; required: [-().&@?'#,/&quot;+]; max-consecutive: 2; minlength: 8;\")"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "<input type=\"password\" minlength=\"8\" passwordrules=\"required: upper; required: lower; required: digit; required: [-().&@?'#,/&quot;+]; max-consecutive: 2\">",
                    ""
                  ],
                  "syntax": "html",
                  "type": "codeListing"
                }
              ],
              "title": "HTML"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, to optionally allow one special character, add this to your markup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let newPasswordTextField = UITextField()",
                    "newPasswordTextField.passwordRules = UITextInputPasswordRules(descriptor: \"required: upper; required: lower; required: digit; allowed: [-().&@?'#,/&quot;+]; max-consecutive: 2; minlength: 8;\")"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "<input type=\"password\" minlength=\"8\" passwordrules=\"required: upper; required: lower; required: digit; allowed: [-().&@?'#,/&quot;+]; max-consecutive: 2\">"
                  ],
                  "syntax": "html",
                  "type": "codeListing"
                }
              ],
              "title": "HTML"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "As another example, to allow a password to contain an arbitrary mix of letters, numbers, and special characters, add this to your markup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let newPasswordTextField = UITextField()",
            "newPasswordTextField.passwordRules = UITextInputPasswordRules(descriptor: \"allowed: upper, lower, digit, [-().&@?__'__#,/&quot;+]; minlength: 8;\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Specifying multiple character classes is equivalent to specifying one character class that represents the union of the characters in all character classes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The exception to this equivalency is ",
              "type": "text"
            },
            {
              "code": "required",
              "type": "codeVoice"
            },
            {
              "text": ". A password must contain at least one character in every specified ",
              "type": "text"
            },
            {
              "code": "required",
              "type": "codeVoice"
            },
            {
              "text": " property. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "allowed: upper; allowed: lower <=> allowed: upper, lower",
            "required: upper; required: lower <=> required: upper; required: lower"
          ],
          "syntax": "console",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits": {
      "abstract": [
        {
          "text": "A set of methods that defines features for keyboard input to a text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInputTraits"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextInputTraits",
      "type": "topic",
      "url": "/documentation/UIKit/UITextInputTraits"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@NSCopying"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passwordRules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextInputPasswordRules",
          "text": "UITextInputPasswordRules"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules",
      "kind": "symbol",
      "role": "symbol",
      "title": "passwordRules",
      "type": "topic",
      "url": "/documentation/UIKit/UITextInputTraits/passwordRules"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/password-autofill": {
      "abstract": [
        {
          "text": "Streamline your app’s login and onboarding procedures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/password-autofill",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Password AutoFill",
      "type": "topic",
      "url": "/documentation/security/password-autofill"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextInputTraits~1passwordRules/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextInputPasswordRules",
              "text": "UITextInputPasswordRules"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "passwordRules"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextInputTraits/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextInputTraits"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/customizing-password-autofill-rules"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/customizing-password-autofill-rules"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
