{
  "abstract": [
    {
      "text": "Determine when your macOS app behaves incorrectly because of a sandbox violation, and fix sandbox-related issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/app-sandbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/discovering-and-diagnosing-app-sandbox-violations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Discovering and diagnosing App Sandbox violations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "App Sandbox protects documents and system resources from malicious abuse by limiting your macOS app’s access to only capabilities you request in its entitlements file. If your app attempts to use capabilities that you didn’t request, it’ll fail to complete those operations even if you use the APIs correctly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you discover that your app’s failure to complete a task is due to a violation of its App Sandbox limitations, you can choose one of three approaches to resolve the issue:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Extend the app’s capabilities to cover the attempted task, by adding a capability to the App Sandbox entitlement for the app executable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Distribute a separate helper tool with your app that uses the additional capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Remove the code that accesses the additional capability if it’s not necessary for implementing your app’s feature set.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Examine-error-output-to-identify-where-your-app-exceeds-its-privileges",
          "level": 3,
          "text": "Examine error output to identify where your app exceeds its privileges",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If an App Sandbox constraint stops a system library from performing a task, that library may log a message to your app’s standard error stream to report the problem. To examine your app’s output, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Xcode, run your app. Xcode automatically displays the Debug pane, shown in the figure below.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reproduce the problem in your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Switch back to Xcode and check for output from your app in the Debug pane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4116319",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Output such as the following indicates that the process encountered an App Sandbox violation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "2022-10-25 14:14:45.543941+0100 SampleApp[12447:550451] dnssd_clientstub ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:22 Err:-1 Errno:1 Operation not permitted",
            "2022-10-25 14:14:45.453414+0100 SampleApp[12447:550126] [] networkd_settings_read_from_file Sandbox is preventing this process from reading networkd settings file at \"/Library/Preferences/com.apple.networkd.plist\", please add an exception.",
            "2022-10-25 14:14:45.542962+0100 SampleApp[12447:550451] [] nw_resolver_can_use_dns_xpc_block_invoke Sandbox does not allow access to com.apple.dnssd.service"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "anchor": "Use-Console-to-identify-violations",
          "level": 3,
          "text": "Use Console to identify violations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the Console app to discover whether a problem is due to an App Sandbox violation by following these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open Console.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Copy each of the lines below, one at a time, into the search field in the Console window.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "code": [
            "type:error",
            "subsystem:com.apple.sandbox.reporting",
            "category:violation"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Save, and enter a name for the saved search.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Start Streaming.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reproduce the problem in your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Switch to Console.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Look for a message relating to your app in the messages view, shown below.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 3,
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4116320",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The message names the process that violated the App Sandbox restrictions, the violating action, and provides additional information about the violation where possible. In the example below, the app’s attempt to make an outgoing network connection violates its App Sandbox restrictions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Sandbox: SampleApp(12447) deny(1) network-outbound /private/var/run/mDNSResponder",
            "Violation: deny(1) network-outbound /private/var/run/mDNSResponder",
            "Process: SampleApp [12447]",
            "Path: /Users/meichen/Library/Developer/Xcode/DerivedData/SampleApp-ejawvdggzjjsyxcmimtdyrrwepff/Build/Products/Release/SampleApp.app/Contents/MacOS/SampleApp",
            "Load Address: 0x1008f4000",
            "Identifier: com.example.SampleApp",
            "Version: 1 (1.0)",
            "Code Type: arm64 (Native)",
            "Parent Process: SampleApp [1]",
            "Responsible: /Users/meichen/Library/Developer/Xcode/DerivedData/SampleApp-ejawvdggzjjsyxcmimtdyrrwepff/Build/Products/Release/SampleApp.app/Contents/MacOS/SampleApp",
            "User ID: 501",
            "[…]",
            "",
            "Thread 0 (id: 551548):",
            "0 libsystem_kernel.dylib 0x0000000180bfb188 __connect_nocancel + 20864 ",
            "1 libsystem_dnssd.dylib 0x000000018c242e7c DNSServiceCreateConnection + 3628 ",
            "2 Network 0x00000001871c8d8c nw_resolver_instantiate_dns_connection_for_parameters + 1203340 ",
            "3 Network 0x00000001871c6340 nw_resolver_create_dns_service_locked + 1192492 ",
            "4 Network 0x00000001871c1db0 __nw_resolver_set_update_handler_block_invoke + 1172360 ",
            "5 Network 0x00000001879479d0 nw_queue_context_async_if_needed + 9062772 ",
            "6 Network 0x00000001871c0eb0 nw_resolver_set_update_handler + 1170824 ",
            "7 Network 0x0000000187533260 -[NWConcrete_nw_endpoint_resolver startWithHandler:] + 4782368 ",
            "8 Network 0x0000000187548180 nw_endpoint_handler_path_change + 4855592 ",
            "9 Network 0x0000000187550100 nw_endpoint_handler_start + 4902092 ",
            "10 Network 0x0000000187b18758 nw_endpoint_flow_setup_protocols + 10961348 ",
            "11 Network 0x0000000187b38f1c -[NWConcrete_nw_endpoint_flow startWithHandler:] + 11096344 ",
            "12 Network 0x0000000187548180 nw_endpoint_handler_path_change + 4855592 ",
            "13 Network 0x0000000187550100 nw_endpoint_handler_start + 4902092 ",
            "14 Network 0x000000018748fb28 __nw_connection_start_block_invoke + 4113712 ",
            "15 Network 0x000000018748f1bc nw_connection_start + 4112176 ",
            "16 CFNetwork 0x00000001855d4670 ??? + 1348664 ",
            "17 CFNetwork 0x00000001855cc9a8 ??? + 1316952 ",
            "18 CFNetwork 0x00000001855cd8b4 ??? + 1319360 ",
            "19 CFNetwork 0x000000018561a5b0 ??? + 1634820 ",
            "20 CFNetwork 0x00000001855cc5f4 ??? + 1312804 ",
            "21 CFNetwork 0x00000001854b2194 ??? + 159676 ",
            "22 CFNetwork 0x0000000185619aac ??? + 1631212 ",
            "23 CFNetwork 0x0000000185619c48 ??? + 1633316 ",
            "24 libdispatch.dylib 0x0000000180aad9dc _dispatch_call_block_and_release + 10684 ",
            "25 libdispatch.dylib 0x0000000180aaf504 _dispatch_client_callout + 17648 ",
            "26 libdispatch.dylib 0x0000000180ab6bbc _dispatch_lane_serial_drain + 47388 ",
            "27 libdispatch.dylib 0x0000000180ab773c _dispatch_lane_invoke + 50568 ",
            "28 libdispatch.dylib 0x0000000180ab8a20 _dispatch_workloop_invoke + 54060 ",
            "29 libdispatch.dylib 0x0000000180ac234c _dispatch_workloop_worker_thread + 94400 ",
            "30 libsystem_pthread.dylib 0x0000000180c32100 _pthread_wqthread + 12256 ",
            "31 libsystem_pthread.dylib 0x0000000180c30e20 start_wqthread + 7704"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The line in the Console message that starts with “Violation:” describes the app’s behavior that violated its App Sandbox restrictions. Use the backtrace to identify which thread in your app violated the App Sandbox restrictions, and locate the violating code. The backtrace is similar to a crash report, even though the system doesn’t terminate apps that violate App Sandbox restrictions. For more information on interpreting a backtrace, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/examining-the-fields-in-a-crash-report",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Extend-your-apps-sandbox-to-accommodate-new-features",
          "level": 3,
          "text": "Extend your app’s sandbox to accommodate new features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you’ve determined that your app needs to perform the task that leads to an App Sandbox violation, add the appropriate capability to the App Sandbox entitlement for your app in the Xcode entitlements editor. To review the available App Sandbox capabilities, see ",
              "type": "text"
            },
            {
              "code": "Entitlements",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Move-potentially-vulnerable-operations-to-a-separate-helper-tool",
          "level": 3,
          "text": "Move potentially vulnerable operations to a separate helper tool",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By separating your app into different components that have access to distinct subsets of the required capabilities, you can balance access to operating system resources with the good practice of protecting people’s devices from malicious attacks. As an example, if your app takes camera images, processes them using unsafe memory operations, and communicates with a network service, create separate components for these three features. Separating the features makes it harder for an attacker who compromises the app through the network to gain access to someone’s camera, or to exploit the potentially unsafe processing code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an app that uses App Sandbox launches a helper tool directly using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/process",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or fork and exec, the helper tool inherits the same sandbox capabilities as the launching app. To enable different capabilities in the app and the helper, use one of these designs:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " service",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A login item",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A helper app, which you can configure to run in the background by setting the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSBackgroundOnly",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSBackgroundOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app runs only in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSBackgroundOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSBackgroundOnly",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/LSBackgroundOnly"
    },
    "doc://com.apple.documentation/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/XPC"
    },
    "doc://com.apple.documentation/documentation/Xcode/examining-the-fields-in-a-crash-report": {
      "abstract": [
        {
          "text": "Understand the structure of a crash report and the information each field contains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/examining-the-fields-in-a-crash-report",
      "kind": "article",
      "role": "article",
      "title": "Examining the fields in a crash report",
      "type": "topic",
      "url": "/documentation/Xcode/examining-the-fields-in-a-crash-report"
    },
    "doc://com.apple.documentation/documentation/foundation/process": {
      "abstract": [
        {
          "text": "An object that represents a subprocess of the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Process"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/process",
      "kind": "symbol",
      "role": "symbol",
      "title": "Process",
      "type": "topic",
      "url": "/documentation/foundation/process"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/app-sandbox": {
      "abstract": [
        {
          "text": "Restrict access to system resources and user data in macOS apps to contain damage if an app becomes compromised.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/app-sandbox",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App Sandbox",
      "type": "topic",
      "url": "/documentation/security/app-sandbox"
    },
    "media-4116319": {
      "alt": "A screenshot of the Debug pane in Xcode, showing log messages from an app that has violated its sandbox.",
      "identifier": "media-4116319",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/262cc1853ef6f800ff78d37765b88d06/media-4116319@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1076a42b2363d9eed668cfa32ca6105d/media-4116319~dark@2x.png"
        }
      ]
    },
    "media-4116320": {
      "alt": "A screenshot of Console, showing App Sandbox violation messages.",
      "identifier": "media-4116320",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c90d7bf761e60fc5986d9ba133755b21/media-4116320@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ba9d0e76782be87152ac3a66ecc4ed5d/media-4116320~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1process/title",
          "value": "NSTask"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/discovering-and-diagnosing-app-sandbox-violations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/discovering-and-diagnosing-app-sandbox-violations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
