{
  "abstract": [
    {
      "text": "Learn what to expect when evaluating a trust object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/trust"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/evaluating-a-trust-and-parsing-the-result"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Evaluating a Trust and Parsing the Result"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Using the trust object that you obtained in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/creating-a-trust-object",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you evaluate it with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsyncWithError(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "DispatchQueue.global().async {",
                    "    SecTrustEvaluateAsyncWithError(trust, DispatchQueue.global()) {",
                    "        trust, result, error in",
                    "",
                    "        if result {",
                    "            let publicKey = SecTrustCopyPublicKey(trust)",
                    "            ",
                    "            // Use key . . .",
                    "        } else {",
                    "            print(\"Trust failed: \\(error!.localizedDescription)\")",
                    "        }",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{",
                    "    SecTrustEvaluateAsyncWithError(",
                    "        trust,",
                    "        dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0),",
                    "        ^(SecTrustRef evaluatedTrust, bool trustResult, CFErrorRef error) {",
                    "            if (trustResult == YES) {",
                    "                // Evaluation succeeded!",
                    "                SecKeyRef publicKey = SecTrustCopyPublicKey(evaluatedTrust);",
                    " ",
                    "                // Use and release key . . .",
                    " ",
                    "            } else {",
                    "                // Evaluation failed: Check the error",
                    "            }",
                    " ",
                    "            // Finally, release the trust and error.",
                    "            if (evaluatedTrust) { CFRelease(evaluatedTrust); }",
                    "            if (error)          { CFRelease(error); }",
                    "        }",
                    "    );",
                    "});"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "If the trust object already has a result, the evaluation might invoke the callback synchronously, before the method returns. In other cases, like when the evaluation needs to fetch intermediate certificates or perform revocation checking, it might instead return immediately, perform the evaluation asynchronously, and call the closure later with a result. Either way, you must call the evaluation method on the same thread that you specify for the closure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the evaluation finishes and the method invokes the callback, examine the ",
              "type": "text"
            },
            {
              "code": "result",
              "type": "codeVoice"
            },
            {
              "text": " parameter. If the trust result is ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", the evaluation succeeded. At this point, you can get the public key from the leaf certificate with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyPublicKey(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as explained in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/getting-an-existing-key",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and begin to use it. If the result is ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ", you might be able to recover from the failure, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/discovering-why-a-trust-evaluation-failed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If you can’t recover—for example, because the certificate is revoked—handle the failure gracefully.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecTrustCopyPublicKey(_:)": {
      "abstract": [
        {
          "text": "Returns the public key for a leaf certificate after it has been evaluated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustCopyPublicKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyPublicKey(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustCopyPublicKey"
        }
      ],
      "role": "symbol",
      "title": "SecTrustCopyPublicKey(_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustcopypublickey(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsyncWithError(_:_:_:)": {
      "abstract": [
        {
          "text": "Evaluates a trust object asynchronously on the specified dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateAsyncWithError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustWithErrorCallback",
          "text": "SecTrustWithErrorCallback"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsyncWithError(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateAsyncWithError"
        }
      ],
      "role": "symbol",
      "title": "SecTrustEvaluateAsyncWithError(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustevaluateasyncwitherror(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/creating-a-trust-object": {
      "abstract": [
        {
          "text": "Construct a trust object from a certificate and a policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/creating-a-trust-object",
      "kind": "article",
      "role": "article",
      "title": "Creating a Trust Object",
      "type": "topic",
      "url": "/documentation/security/creating-a-trust-object"
    },
    "doc://com.apple.security/documentation/Security/discovering-why-a-trust-evaluation-failed": {
      "abstract": [
        {
          "text": "Determine whether you can recover from a failed trust evaluation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/discovering-why-a-trust-evaluation-failed",
      "kind": "article",
      "role": "article",
      "title": "Discovering Why a Trust Evaluation Failed",
      "type": "topic",
      "url": "/documentation/security/discovering-why-a-trust-evaluation-failed"
    },
    "doc://com.apple.security/documentation/Security/getting-an-existing-key": {
      "abstract": [
        {
          "text": "Learn how to obtain an existing cryptographic key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/getting-an-existing-key",
      "kind": "article",
      "role": "article",
      "title": "Getting an Existing Key",
      "type": "topic",
      "url": "/documentation/security/getting-an-existing-key"
    },
    "doc://com.apple.security/documentation/Security/trust": {
      "abstract": [
        {
          "text": "Evaluate trust based on a given policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/trust",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Trust",
      "type": "topic",
      "url": "/documentation/security/trust"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyPublicKey(_:)/title",
          "value": "SecTrustCopyPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyPublicKey(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustCopyPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateAsyncWithError(_:_:_:)/title",
          "value": "SecTrustEvaluateAsyncWithError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateAsyncWithError(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustEvaluateAsyncWithError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/evaluating-a-trust-and-parsing-the-result"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/evaluating-a-trust-and-parsing-the-result"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
