{
  "abstract": [
    {
      "text": "Use templates for each of the simple types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/asn-1"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/generic-templates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Generic Templates"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/asn-1": {
      "abstract": [
        {
          "text": "Encode and decode Distinguished Encoding Rules (DER) and Basic Encoding Rules (BER) data streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/asn-1",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ASN.1",
      "type": "topic",
      "url": "/documentation/security/asn-1"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1AnyTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1AnyTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1AnyTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1AnyTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1anytemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1BMPStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1BMPStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1BMPStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1BMPStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1bmpstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1BitStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1BitStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1BitStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1BitStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1bitstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1BooleanTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1BooleanTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1BooleanTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1BooleanTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1booleantemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1EnumeratedTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1EnumeratedTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1EnumeratedTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1EnumeratedTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1enumeratedtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1GeneralizedTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1GeneralizedTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1GeneralizedTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1GeneralizedTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1generalizedtimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1IA5StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1IA5StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1IA5StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1IA5StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1ia5stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1IntegerTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1IntegerTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1IntegerTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1IntegerTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1integertemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1NullTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1NullTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1NullTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1NullTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1nulltemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1ObjectIDTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1ObjectIDTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1ObjectIDTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1ObjectIDTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1objectidtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1OctetStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1OctetStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1OctetStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1OctetStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1octetstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToAnyTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToAnyTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToAnyTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToAnyTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoanytemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBMPStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToBMPStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBMPStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToBMPStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertobmpstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBitStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToBitStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBitStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToBitStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertobitstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBooleanTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToBooleanTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBooleanTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToBooleanTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertobooleantemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToEnumeratedTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToEnumeratedTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToEnumeratedTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToEnumeratedTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoenumeratedtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToGeneralizedTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToGeneralizedTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToGeneralizedTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToGeneralizedTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertogeneralizedtimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIA5StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToIA5StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIA5StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToIA5StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoia5stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIntegerTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToIntegerTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIntegerTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToIntegerTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertointegertemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToNullTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToNullTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToNullTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToNullTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertonulltemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToObjectIDTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToObjectIDTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToObjectIDTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToObjectIDTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoobjectidtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToOctetStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToOctetStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToOctetStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToOctetStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertooctetstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToPrintableStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToPrintableStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToPrintableStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToPrintableStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoprintablestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToT61StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToT61StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToT61StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToT61StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertot61stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToTeletexStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToTeletexStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToTeletexStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToTeletexStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoteletexstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTCTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToUTCTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTCTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToUTCTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoutctimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTF8StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToUTF8StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTF8StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToUTF8StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertoutf8stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUniversalStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToUniversalStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUniversalStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToUniversalStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertouniversalstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PointerToVisibleStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PointerToVisibleStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PointerToVisibleStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PointerToVisibleStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1pointertovisiblestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1PrintableStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1PrintableStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1PrintableStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1PrintableStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1printablestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfAnyTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfAnyTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfAnyTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfAnyTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofanytemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBMPStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfBMPStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBMPStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfBMPStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofbmpstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBitStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfBitStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBitStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfBitStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofbitstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBooleanTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfBooleanTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBooleanTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfBooleanTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofbooleantemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfEnumeratedTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfEnumeratedTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfEnumeratedTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfEnumeratedTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofenumeratedtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfGeneralizedTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfGeneralizedTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfGeneralizedTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfGeneralizedTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofgeneralizedtimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIA5StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfIA5StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIA5StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfIA5StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofia5stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIntegerTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfIntegerTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIntegerTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfIntegerTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofintegertemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfNullTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfNullTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfNullTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfNullTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofnulltemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfObjectIDTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfObjectIDTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfObjectIDTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfObjectIDTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofobjectidtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfOctetStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfOctetStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfOctetStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfOctetStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofoctetstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfPrintableStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfPrintableStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfPrintableStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfPrintableStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofprintablestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfT61StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfT61StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfT61StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfT61StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceoft61stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfTeletexStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfTeletexStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfTeletexStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfTeletexStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofteletexstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTCTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfUTCTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTCTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfUTCTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofutctimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTF8StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfUTF8StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTF8StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfUTF8StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofutf8stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUniversalStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfUniversalStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUniversalStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfUniversalStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofuniversalstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfVisibleStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SequenceOfVisibleStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfVisibleStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SequenceOfVisibleStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1sequenceofvisiblestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfAnyTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfAnyTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfAnyTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfAnyTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofanytemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBMPStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfBMPStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBMPStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfBMPStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofbmpstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBitStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfBitStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBitStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfBitStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofbitstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBooleanTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfBooleanTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBooleanTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfBooleanTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofbooleantemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfEnumeratedTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfEnumeratedTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfEnumeratedTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfEnumeratedTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofenumeratedtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfGeneralizedTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfGeneralizedTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfGeneralizedTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfGeneralizedTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofgeneralizedtimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIA5StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfIA5StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIA5StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfIA5StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofia5stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIntegerTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfIntegerTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIntegerTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfIntegerTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofintegertemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfNullTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfNullTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfNullTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfNullTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofnulltemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfObjectIDTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfObjectIDTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfObjectIDTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfObjectIDTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofobjectidtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfOctetStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfOctetStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfOctetStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfOctetStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofoctetstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfPrintableStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfPrintableStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfPrintableStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfPrintableStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofprintablestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfT61StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfT61StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfT61StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfT61StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setoft61stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfTeletexStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfTeletexStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfTeletexStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfTeletexStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofteletexstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTCTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfUTCTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTCTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfUTCTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofutctimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTF8StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfUTF8StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTF8StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfUTF8StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofutf8stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUniversalStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfUniversalStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUniversalStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfUniversalStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofuniversalstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SetOfVisibleStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SetOfVisibleStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SetOfVisibleStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SetOfVisibleStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1setofvisiblestringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1SkipTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1SkipTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1SkipTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1SkipTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1skiptemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1T61StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1T61StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1T61StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1T61StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1t61stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1TeletexStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1TeletexStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1TeletexStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1TeletexStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1teletexstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1UTCTimeTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1UTCTimeTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1UTCTimeTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1UTCTimeTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1utctimetemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1UTF8StringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1UTF8StringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1UTF8StringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1UTF8StringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1utf8stringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1UniversalStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1UniversalStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1UniversalStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1UniversalStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1universalstringtemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1UnsignedIntegerTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1UnsignedIntegerTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1UnsignedIntegerTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1UnsignedIntegerTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1unsignedintegertemplate"
    },
    "doc://com.apple.security/documentation/Security/kSecAsn1VisibleStringTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAsn1VisibleStringTemplate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAsn1VisibleStringTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAsn1VisibleStringTemplate",
      "type": "topic",
      "url": "/documentation/security/ksecasn1visiblestringtemplate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Templates",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecAsn1AnyTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1BMPStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1BitStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1BooleanTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1EnumeratedTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1GeneralizedTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1IA5StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1IntegerTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1NullTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1ObjectIDTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1OctetStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PrintableStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SkipTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1T61StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1TeletexStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1UTCTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1UTF8StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1UniversalStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1UnsignedIntegerTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1VisibleStringTemplate"
              ],
              "title": "Templates"
            },
            {
              "anchor": "Template-Pointers",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToAnyTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBMPStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBitStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToBooleanTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToEnumeratedTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToGeneralizedTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIA5StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToIntegerTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToNullTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToObjectIDTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToOctetStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToPrintableStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToT61StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToTeletexStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTCTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUTF8StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToUniversalStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1PointerToVisibleStringTemplate"
              ],
              "title": "Template Pointers"
            },
            {
              "anchor": "Template-Sets",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfAnyTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBMPStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBitStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfBooleanTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfEnumeratedTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfGeneralizedTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIA5StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfIntegerTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfNullTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfObjectIDTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfOctetStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfPrintableStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfT61StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfTeletexStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTCTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUTF8StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfUniversalStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SetOfVisibleStringTemplate"
              ],
              "title": "Template Sets"
            },
            {
              "anchor": "Template-Sequences",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfAnyTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBMPStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBitStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfBooleanTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfEnumeratedTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfGeneralizedTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIA5StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfIntegerTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfNullTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfObjectIDTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfOctetStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfPrintableStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfT61StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfTeletexStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTCTimeTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUTF8StringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfUniversalStringTemplate",
                "doc://com.apple.security/documentation/Security/kSecAsn1SequenceOfVisibleStringTemplate"
              ],
              "title": "Template Sequences"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/generic-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/generic-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
