{
  "abstract": [
    {
      "text": "Specify attributes of guest code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/guest-attribute-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Guest Attribute Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys in the dictionary you supply as the ",
              "type": "text"
            },
            {
              "code": "attributes",
              "type": "codeVoice"
            },
            {
              "text": " parameter to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecHostCreateGuest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecHostSetGuestStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyGuestWithAttributes(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopyGuestWithAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Asks a code host to identify one of its guests given the type and value of specific attributes of the guest code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopyGuestWithAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyGuestWithAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopyGuestWithAttributes"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopyGuestWithAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopyguestwithattributes(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecHostCreateGuest": {
      "abstract": [
        {
          "text": "Creates a new guest and describes its initial properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecHostCreateGuest"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecHostCreateGuest",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecHostCreateGuest",
      "type": "topic",
      "url": "/documentation/security/sechostcreateguest"
    },
    "doc://com.apple.security/documentation/Security/SecHostSetGuestStatus": {
      "abstract": [
        {
          "text": "Updates the status and attributes of a particular guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecHostSetGuestStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecHostSetGuestStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecHostSetGuestStatus",
      "type": "topic",
      "url": "/documentation/security/sechostsetgueststatus"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeArchitecture": {
      "abstract": [
        {
          "text": "A key whose value is a number representing the CPU type under which the guest code is designed to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeArchitecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeArchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeArchitecture"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeArchitecture",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributearchitecture"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeAudit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeAudit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeAudit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeAudit"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeAudit",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributeaudit"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeCanonical": {
      "abstract": [
        {
          "text": "A key whose value is the guest code object for that guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeCanonical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeCanonical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeCanonical"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeCanonical",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributecanonical"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeDynamicCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeDynamicCode"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeDynamicCode",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributedynamiccode"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCodeInfoPlist": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeDynamicCodeInfoPlist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCodeInfoPlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeDynamicCodeInfoPlist"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeDynamicCodeInfoPlist",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributedynamiccodeinfoplist"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeHash": {
      "abstract": [
        {
          "text": "A key whose value is a data object containing the SHA-1 hash of the code directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeHash"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeHash",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributehash"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeMachPort": {
      "abstract": [
        {
          "text": "Not implemented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeMachPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeMachPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeMachPort"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeMachPort",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributemachport"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributePid": {
      "abstract": [
        {
          "text": "A key whose value is an integer of type ",
          "type": "text"
        },
        {
          "code": "pid_t",
          "type": "codeVoice"
        },
        {
          "text": " representing a process ID (PID), usually of the kernel’s guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributePid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributePid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributePid"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributePid",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributepid"
    },
    "doc://com.apple.security/documentation/Security/kSecGuestAttributeSubarchitecture": {
      "abstract": [
        {
          "text": "A key whose value is a number representing the CPU subtype under which the guest code is designed to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeSubarchitecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecGuestAttributeSubarchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestAttributeSubarchitecture"
        }
      ],
      "role": "symbol",
      "title": "kSecGuestAttributeSubarchitecture",
      "type": "topic",
      "url": "/documentation/security/ksecguestattributesubarchitecture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeArchitecture",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeAudit",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeCanonical",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCode",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCodeInfoPlist",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeHash",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeMachPort",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributePid",
        "doc://com.apple.security/documentation/Security/kSecGuestAttributeSubarchitecture"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeArchitecture",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeAudit",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeCanonical",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCode",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeDynamicCodeInfoPlist",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeHash",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeMachPort",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributePid",
                "doc://com.apple.security/documentation/Security/kSecGuestAttributeSubarchitecture"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeArchitecture/title",
          "value": "kSecGuestAttributeArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeArchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeMachPort/title",
          "value": "kSecGuestAttributeMachPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeMachPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeMachPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeDynamicCodeInfoPlist/title",
          "value": "kSecGuestAttributeDynamicCodeInfoPlist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeDynamicCodeInfoPlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeDynamicCodeInfoPlist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeSubarchitecture/title",
          "value": "kSecGuestAttributeSubarchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeSubarchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeSubarchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeCanonical/title",
          "value": "kSecGuestAttributeCanonical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeCanonical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeCanonical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeAudit/title",
          "value": "kSecGuestAttributeAudit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeAudit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeAudit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeHash/title",
          "value": "kSecGuestAttributeHash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeHash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeHash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyGuestWithAttributes(_:_:_:_:)/title",
          "value": "SecCodeCopyGuestWithAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyGuestWithAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopyGuestWithAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeDynamicCode/title",
          "value": "kSecGuestAttributeDynamicCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributeDynamicCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributeDynamicCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributePid/title",
          "value": "kSecGuestAttributePid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecGuestAttributePid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestAttributePid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/guest-attribute-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/guest-attribute-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
