{
  "abstract": [
    {
      "text": "Manage security protections and resource access for your macOS apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/hardened-runtime"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "title": "Hardened Runtime"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Hardened Runtime, along with System Integrity Protection (SIP), protects the runtime integrity of your software by preventing certain classes of exploits, like code injection, dynamically linked library (DLL) hijacking, and process memory space tampering. To enable the Hardened Runtime for your app, navigate in Xcode to your target’s Signing & Capabilities information and click the + button. In the window that appears, choose Hardened Runtime.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3330446",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Hardened Runtime doesn’t affect the operation of most apps, but it does disallow certain less common capabilities, like just-in-time (JIT) compilation. If your app relies on a capability that the Hardened Runtime restricts, add an entitlement to disable an individual protection. You add an entitlement by enabling one of the runtime exceptions or access permissions listed in Xcode. Make sure to use only the entitlements that are absolutely necessary for your app’s functionality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3330445",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You add entitlements only to executables. Shared libraries, frameworks, and in-process plug-ins inherit the entitlements of their host executable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of these Boolean entitlements is false. When Xcode signs your code, it includes an entitlement only if the value is true. If you’re manually signing code, follow this convention to ensure maximum compatibility. Don’t include an entitlement if the value is false.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To upload a macOS app to be notarized, you must enable the Hardened Runtime capability. For more information about notarization, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/notarizing-macos-software-before-distribution",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.automation.apple-events": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may prompt the user for permission to send Apple events to other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.automation.apple-events",
      "kind": "symbol",
      "role": "symbol",
      "title": "Apple Events Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.automation.apple-events"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-dyld-environment-variables": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may be affected by dynamic linker environment variables, which you can use to inject code into your app’s process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-dyld-environment-variables",
      "kind": "symbol",
      "role": "symbol",
      "title": "Allow DYLD environment variables entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-dyld-environment-variables"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may create writable and executable memory using the `MAP_JIT` flag.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit",
      "kind": "symbol",
      "role": "symbol",
      "title": "Allow execution of JIT-compiled code entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-unsigned-executable-memory": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may create writable and executable memory without the restrictions imposed by using the `MAP_JIT` flag.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-unsigned-executable-memory",
      "kind": "symbol",
      "role": "symbol",
      "title": "Allow Unsigned Executable Memory Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-unsigned-executable-memory"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.debugger": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app is a debugger and may attach to other processes or get task ports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.debugger",
      "kind": "symbol",
      "role": "symbol",
      "title": "Debugging tool entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.debugger"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-executable-page-protection": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to disable all code signing protections while launching an app, and during its execution.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-executable-page-protection",
      "kind": "symbol",
      "role": "symbol",
      "title": "Disable Executable Memory Protection Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-executable-page-protection"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-library-validation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app loads arbitrary plug-ins or frameworks, without requiring code signing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-library-validation",
      "kind": "symbol",
      "role": "symbol",
      "title": "Disable Library Validation Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-library-validation"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.audio-input": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may record audio using the built-in microphone and access audio input using Core Audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.audio-input",
      "kind": "symbol",
      "role": "symbol",
      "title": "Audio Input Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.device.audio-input"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.camera": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may interact with the built-in and external cameras, and capture movies and still images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
      "kind": "symbol",
      "role": "symbol",
      "title": "Camera entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.device.camera"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to contacts in the user’s address book.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
      "kind": "symbol",
      "role": "symbol",
      "title": "Address book entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to the user’s calendar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
      "kind": "symbol",
      "role": "symbol",
      "title": "Calendars entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may access location information from Location Services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
      "kind": "symbol",
      "role": "symbol",
      "title": "Location entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.photos-library": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app has read-write access to the user’s Photos library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.photos-library",
      "kind": "symbol",
      "role": "symbol",
      "title": "Photos Library Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.personal-information.photos-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/notarizing-macos-software-before-distribution": {
      "abstract": [
        {
          "text": "Give users even more confidence in your macOS software by submitting it to Apple for notarization.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/notarizing-macos-software-before-distribution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notarizing macOS software before distribution",
      "type": "topic",
      "url": "/documentation/security/notarizing-macos-software-before-distribution"
    },
    "media-3330445": {
      "alt": "Screenshot of Xcode showing some of the entitlements used for exceptions to the Hardened Runtime.",
      "identifier": "media-3330445",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e34650edf88337ff29b74fc8176cfc74/media-3330445@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5fbee560bf1b1cc71b9ac1b57d7013b7/media-3330445~dark@2x.png"
        }
      ]
    },
    "media-3330446": {
      "alt": "Screenshot highlighting where to click to add a new capability in Xcode’s Signing & Capabilities tab.",
      "identifier": "media-3330446",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/56cfc71df9e6bfd2a682fdd556780e09/media-3330446@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5973ade3f4df40d484b2159392cb5a11/media-3330446~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Runtime-Exceptions",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-unsigned-executable-memory",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-dyld-environment-variables",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-library-validation",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-executable-page-protection",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.debugger"
      ],
      "title": "Runtime Exceptions"
    },
    {
      "anchor": "Resource-Access",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.audio-input",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.photos-library",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.automation.apple-events"
      ],
      "title": "Resource Access"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Runtime-Exceptions",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-jit",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-unsigned-executable-memory",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.allow-dyld-environment-variables",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-library-validation",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.disable-executable-page-protection",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.cs.debugger"
              ],
              "title": "Runtime Exceptions"
            },
            {
              "anchor": "Resource-Access",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.audio-input",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.personal-information.photos-library",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.automation.apple-events"
              ],
              "title": "Resource Access"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/hardened-runtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/hardened-runtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
