{
  "abstract": [
    {
      "text": "Specify the class of a keychain item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/keychain-items"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/item-class-keys-and-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Item class keys and values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Keychain items come in a variety of classes according to the kind of data they hold, such as passwords, cryptographic keys, and certificates. The item’s class dictates which attributes apply and enables the system to decide whether to encrypt the data. For example, the system encrypts passwords, but not certificates because they aren’t secret.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the key and one of the corresponding values listed here to specify the class for a new item you create with a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function by placing the key/value pair in the ",
              "type": "text"
            },
            {
              "code": "attributes",
              "type": "codeVoice"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Later, use this same pair in the ",
              "type": "text"
            },
            {
              "code": "query",
              "type": "codeVoice"
            },
            {
              "text": " dictionary when searching for an item with one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemUpdate(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemDelete(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        }
      ],
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemadd(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)": {
      "abstract": [
        {
          "text": "Returns one or more keychain items that match a search query, or copies attributes of specific keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        }
      ],
      "role": "symbol",
      "title": "SecItemCopyMatching(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemcopymatching(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemDelete(_:)": {
      "abstract": [
        {
          "text": "Deletes items that match a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemDelete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemDelete(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemDelete"
        }
      ],
      "role": "symbol",
      "title": "SecItemDelete(_:)",
      "type": "topic",
      "url": "/documentation/security/secitemdelete(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemUpdate(_:_:)": {
      "abstract": [
        {
          "text": "Modifies items that match a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemUpdate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemUpdate"
        }
      ],
      "role": "symbol",
      "title": "SecItemUpdate(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemupdate(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/kSecClass": {
      "abstract": [
        {
          "text": "A dictionary key whose value is the item’s class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClass"
        }
      ],
      "role": "symbol",
      "title": "kSecClass",
      "type": "topic",
      "url": "/documentation/security/ksecclass"
    },
    "doc://com.apple.security/documentation/Security/kSecClassCertificate": {
      "abstract": [
        {
          "text": "The value that indicates a certificate item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassCertificate"
        }
      ],
      "role": "symbol",
      "title": "kSecClassCertificate",
      "type": "topic",
      "url": "/documentation/security/ksecclasscertificate"
    },
    "doc://com.apple.security/documentation/Security/kSecClassGenericPassword": {
      "abstract": [
        {
          "text": "The value that indicates a generic password item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        }
      ],
      "role": "symbol",
      "title": "kSecClassGenericPassword",
      "type": "topic",
      "url": "/documentation/security/ksecclassgenericpassword"
    },
    "doc://com.apple.security/documentation/Security/kSecClassIdentity": {
      "abstract": [
        {
          "text": "The value that indicates an identity item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassIdentity"
        }
      ],
      "role": "symbol",
      "title": "kSecClassIdentity",
      "type": "topic",
      "url": "/documentation/security/ksecclassidentity"
    },
    "doc://com.apple.security/documentation/Security/kSecClassInternetPassword": {
      "abstract": [
        {
          "text": "The value that indicates an Internet password item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassInternetPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassInternetPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassInternetPassword"
        }
      ],
      "role": "symbol",
      "title": "kSecClassInternetPassword",
      "type": "topic",
      "url": "/documentation/security/ksecclassinternetpassword"
    },
    "doc://com.apple.security/documentation/Security/kSecClassKey": {
      "abstract": [
        {
          "text": "The value that indicates a cryptographic key item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassKey"
        }
      ],
      "role": "symbol",
      "title": "kSecClassKey",
      "type": "topic",
      "url": "/documentation/security/ksecclasskey"
    },
    "doc://com.apple.security/documentation/Security/keychain-items": {
      "abstract": [
        {
          "text": "Embed confidential information in items that you store in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-items",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain items",
      "type": "topic",
      "url": "/documentation/security/keychain-items"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Item-class-keys",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecClass"
      ],
      "title": "Item class keys"
    },
    {
      "abstract": [
        {
          "text": "Values you use with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "anchor": "Item-class-values",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
        "doc://com.apple.security/documentation/Security/kSecClassInternetPassword",
        "doc://com.apple.security/documentation/Security/kSecClassCertificate",
        "doc://com.apple.security/documentation/Security/kSecClassKey",
        "doc://com.apple.security/documentation/Security/kSecClassIdentity"
      ],
      "title": "Item class values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Item-class-keys",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecClass"
              ],
              "title": "Item class keys"
            },
            {
              "abstract": [
                {
                  "text": "Values you use with the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key.",
                  "type": "text"
                }
              ],
              "anchor": "Item-class-values",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
                "doc://com.apple.security/documentation/Security/kSecClassInternetPassword",
                "doc://com.apple.security/documentation/Security/kSecClassCertificate",
                "doc://com.apple.security/documentation/Security/kSecClassKey",
                "doc://com.apple.security/documentation/Security/kSecClassIdentity"
              ],
              "title": "Item class values"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/title",
          "value": "SecItemCopyMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemCopyMatching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassKey/title",
          "value": "kSecClassKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemUpdate(_:_:)/title",
          "value": "SecItemUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemUpdate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClass/title",
          "value": "kSecClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassIdentity/title",
          "value": "kSecClassIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassInternetPassword/title",
          "value": "kSecClassInternetPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassInternetPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassInternetPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemDelete(_:)/title",
          "value": "SecItemDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemDelete(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassCertificate/title",
          "value": "kSecClassCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/title",
          "value": "kSecClassGenericPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassGenericPassword"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/item-class-keys-and-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/item-class-keys-and-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
