{
  "abstract": [
    {
      "text": "Specify how you want returned keychain item data formatted.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/keychain-items"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/item-return-result-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Item return result keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you use one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions to add or search for keychain items, these functions return the item’s data and attributes through the ",
              "type": "text"
            },
            {
              "code": "result",
              "type": "codeVoice"
            },
            {
              "text": " parameter to which you provide a pointer. Use the item result keys described below in the corresponding query dictionary to indicate how those results should be formatted:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you request a data reference with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnRef",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the search returns a reference of type ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItem",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata-rv9",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", depending on the class of the item.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you request a persistent data reference using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnPersistentRef",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the search returns an item reference of type ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata-rv9",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " that you can store on disk or pass between processes. You later convert persistent references to regular references with another call to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function, using an array of persistent references (of the same item class) as the value for the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecMatchItemList",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you ask for the data itself with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the search returns a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata-rv9",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance that holds the actual data. This is typically what you want for password items. To undo the encryption it added prior to storing the item, keychain services decrypts the data before returning it to you. Don’t use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for cryptographic key or identity items, as the key material may not be extractable. Instead, call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecKeyCopyExternalRepresentation(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and check the ",
                      "type": "text"
                    },
                    {
                      "code": "error",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter if it returns ",
                      "type": "text"
                    },
                    {
                      "code": "nil",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you request the item’s attributes using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnAttributes",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or more than one return type, the search returns a dictionary. Item attributes are represented directly as key-value pairs in this dictionary, while the item’s data appears in one or more of the previously mentioned forms, and is associated with the appropriate item value type key from ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When you specify a match limit greater than one, the search produces an array. Each element of the array is itself a search result formatted according to the previous rules.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfdata-rv9": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata-rv9",
      "kind": "article",
      "role": "article",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata-rv9"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCertificate": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an X.509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "role": "symbol",
      "title": "SecCertificate",
      "type": "topic",
      "url": "/documentation/security/seccertificate"
    },
    "doc://com.apple.security/documentation/Security/SecIdentity": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "role": "symbol",
      "title": "SecIdentity",
      "type": "topic",
      "url": "/documentation/security/secidentity"
    },
    "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        }
      ],
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemadd(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)": {
      "abstract": [
        {
          "text": "Returns one or more keychain items that match a search query, or copies attributes of specific keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        }
      ],
      "role": "symbol",
      "title": "SecItemCopyMatching(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemcopymatching(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKey": {
      "abstract": [
        {
          "text": "An object that represents a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "role": "symbol",
      "title": "SecKey",
      "type": "topic",
      "url": "/documentation/security/seckey"
    },
    "doc://com.apple.security/documentation/Security/SecKeyCopyExternalRepresentation(_:_:)": {
      "abstract": [
        {
          "text": "Returns an external representation of the given key suitable for the key’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyCopyExternalRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyCopyExternalRepresentation(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyCopyExternalRepresentation"
        }
      ],
      "role": "symbol",
      "title": "SecKeyCopyExternalRepresentation(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeycopyexternalrepresentation(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItem": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychainItem"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychainItem"
        }
      ],
      "role": "symbol",
      "title": "SecKeychainItem",
      "type": "topic",
      "url": "/documentation/security/seckeychainitem"
    },
    "doc://com.apple.security/documentation/Security/item-return-result-keys": {
      "abstract": [
        {
          "text": "Specify how you want returned keychain item data formatted.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Item return result keys",
      "type": "topic",
      "url": "/documentation/security/item-return-result-keys"
    },
    "doc://com.apple.security/documentation/Security/kSecMatchItemList": {
      "abstract": [
        {
          "text": "A key whose value indicates a list of items to search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecMatchItemList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecMatchItemList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecMatchItemList"
        }
      ],
      "role": "symbol",
      "title": "kSecMatchItemList",
      "type": "topic",
      "url": "/documentation/security/ksecmatchitemlist"
    },
    "doc://com.apple.security/documentation/Security/kSecReturnAttributes": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean indicating whether or not to return item attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecReturnAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecReturnAttributes"
        }
      ],
      "role": "symbol",
      "title": "kSecReturnAttributes",
      "type": "topic",
      "url": "/documentation/security/ksecreturnattributes"
    },
    "doc://com.apple.security/documentation/Security/kSecReturnData": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether or not to return item data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecReturnData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecReturnData"
        }
      ],
      "role": "symbol",
      "title": "kSecReturnData",
      "type": "topic",
      "url": "/documentation/security/ksecreturndata"
    },
    "doc://com.apple.security/documentation/Security/kSecReturnPersistentRef": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean indicating whether or not to return a persistent reference to an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecReturnPersistentRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnPersistentRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecReturnPersistentRef"
        }
      ],
      "role": "symbol",
      "title": "kSecReturnPersistentRef",
      "type": "topic",
      "url": "/documentation/security/ksecreturnpersistentref"
    },
    "doc://com.apple.security/documentation/Security/kSecReturnRef": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean indicating whether or not to return a reference to an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecReturnRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecReturnRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecReturnRef"
        }
      ],
      "role": "symbol",
      "title": "kSecReturnRef",
      "type": "topic",
      "url": "/documentation/security/ksecreturnref"
    },
    "doc://com.apple.security/documentation/Security/kSecValueData": {
      "abstract": [
        {
          "text": "A key whose value is the item’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecValueData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecValueData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecValueData"
        }
      ],
      "role": "symbol",
      "title": "kSecValueData",
      "type": "topic",
      "url": "/documentation/security/ksecvaluedata"
    },
    "doc://com.apple.security/documentation/Security/kSecValuePersistentRef": {
      "abstract": [
        {
          "text": "A key whose value is a persistent reference to the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecValuePersistentRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecValuePersistentRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecValuePersistentRef"
        }
      ],
      "role": "symbol",
      "title": "kSecValuePersistentRef",
      "type": "topic",
      "url": "/documentation/security/ksecvaluepersistentref"
    },
    "doc://com.apple.security/documentation/Security/kSecValueRef": {
      "abstract": [
        {
          "text": "A key whose value is a reference to the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecValueRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecValueRef"
        }
      ],
      "role": "symbol",
      "title": "kSecValueRef",
      "type": "topic",
      "url": "/documentation/security/ksecvalueref"
    },
    "doc://com.apple.security/documentation/Security/keychain-items": {
      "abstract": [
        {
          "text": "Embed confidential information in items that you store in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-items",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain items",
      "type": "topic",
      "url": "/documentation/security/keychain-items"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Keys you use to specify the type of results to return from a keychain item search or add operation.",
          "type": "text"
        }
      ],
      "anchor": "Item-result-keys",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecReturnData",
        "doc://com.apple.security/documentation/Security/kSecReturnAttributes",
        "doc://com.apple.security/documentation/Security/kSecReturnRef",
        "doc://com.apple.security/documentation/Security/kSecReturnPersistentRef"
      ],
      "title": "Item result keys"
    },
    {
      "abstract": [
        {
          "text": "Keys that appear in the result dictionary when you specify more than one search result key.",
          "type": "text"
        }
      ],
      "anchor": "Item-value-type-keys",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecValueData",
        "doc://com.apple.security/documentation/Security/kSecValueRef",
        "doc://com.apple.security/documentation/Security/kSecValuePersistentRef"
      ],
      "title": "Item value type keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Keys you use to specify the type of results to return from a keychain item search or add operation.",
                  "type": "text"
                }
              ],
              "anchor": "Item-result-keys",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecReturnData",
                "doc://com.apple.security/documentation/Security/kSecReturnAttributes",
                "doc://com.apple.security/documentation/Security/kSecReturnRef",
                "doc://com.apple.security/documentation/Security/kSecReturnPersistentRef"
              ],
              "title": "Item result keys"
            },
            {
              "abstract": [
                {
                  "text": "Keys that appear in the result dictionary when you specify more than one search result key.",
                  "type": "text"
                }
              ],
              "anchor": "Item-value-type-keys",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecValueData",
                "doc://com.apple.security/documentation/Security/kSecValueRef",
                "doc://com.apple.security/documentation/Security/kSecValuePersistentRef"
              ],
              "title": "Item value type keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCopyExternalRepresentation(_:_:)/title",
          "value": "SecKeyCopyExternalRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCopyExternalRepresentation(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyCopyExternalRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecMatchItemList/title",
          "value": "kSecMatchItemList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecMatchItemList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecMatchItemList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/title",
          "value": "SecIdentityRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/title",
          "value": "SecKeyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnRef/title",
          "value": "kSecReturnRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecReturnRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueRef/title",
          "value": "kSecValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValuePersistentRef/title",
          "value": "kSecValuePersistentRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValuePersistentRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecValuePersistentRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnPersistentRef/title",
          "value": "kSecReturnPersistentRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnPersistentRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecReturnPersistentRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnAttributes/title",
          "value": "kSecReturnAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecReturnAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/title",
          "value": "SecItemCopyMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemCopyMatching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/title",
          "value": "SecCertificateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/title",
          "value": "SecKeychainItemRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainItemRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainItemRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnData/title",
          "value": "kSecReturnData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecReturnData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecReturnData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueData/title",
          "value": "kSecValueData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecValueData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/item-return-result-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/item-return-result-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
