{
  "abstract": [
    {
      "text": "Specifies the attributes for a key item in a keychain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/keychain-services",
        "doc://com.apple.security/documentation/Security/keychain-items"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/keychain-item-attribute-constants-for-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Keychain Item Attribute Constants For Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For attributes for items other than keys, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr": {
      "abstract": [
        {
          "text": "Specifies a keychain item’s attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyAlias": {
      "abstract": [
        {
          "text": "Type blob; currently unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyAlias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyAlias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyAlias"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyAlias",
      "type": "topic",
      "url": "/documentation/security/kseckeyalias"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyAlwaysSensitive": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key has always been marked sensitive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyAlwaysSensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyAlwaysSensitive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyAlwaysSensitive"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyAlwaysSensitive",
      "type": "topic",
      "url": "/documentation/security/kseckeyalwayssensitive"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyApplicationTag": {
      "abstract": [
        {
          "text": "Type blob; currently unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyApplicationTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyApplicationTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyApplicationTag"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyApplicationTag",
      "type": "topic",
      "url": "/documentation/security/kseckeyapplicationtag"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyDecrypt": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can be used in a decrypt operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyDecrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyDecrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyDecrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyDecrypt",
      "type": "topic",
      "url": "/documentation/security/kseckeydecrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyDerive": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can be used in a key derivation operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyDerive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyDerive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyDerive"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyDerive",
      "type": "topic",
      "url": "/documentation/security/kseckeyderive"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyEffectiveKeySize": {
      "abstract": [
        {
          "text": "Type uint32; value is the effective number of bits in this key.  For example, a DES key has a key size in bits (",
          "type": "text"
        },
        {
          "code": "kSecKeyKeySizeInBits",
          "type": "codeVoice"
        },
        {
          "text": ") of 64 but a value for ",
          "type": "text"
        },
        {
          "code": "kSecKeyEffectiveKeySize",
          "type": "codeVoice"
        },
        {
          "text": " of 56.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyEffectiveKeySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyEffectiveKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyEffectiveKeySize"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyEffectiveKeySize",
      "type": "topic",
      "url": "/documentation/security/kseckeyeffectivekeysize"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyEncrypt": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can be used in an encrypt operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyEncrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyEncrypt",
      "type": "topic",
      "url": "/documentation/security/kseckeyencrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyEndDate": {
      "abstract": [
        {
          "text": "Type ",
          "type": "text"
        },
        {
          "code": "CSSM_DATE",
          "type": "codeVoice"
        },
        {
          "text": ".  Latest date at which this key may be used.  If the value is all zeros or not present, no restriction applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyEndDate"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyEndDate",
      "type": "topic",
      "url": "/documentation/security/kseckeyenddate"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyExtractable": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can be wrapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyExtractable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyExtractable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyExtractable"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyExtractable",
      "type": "topic",
      "url": "/documentation/security/kseckeyextractable"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyKeyClass": {
      "abstract": [
        {
          "text": "Type uint32 (",
          "type": "text"
        },
        {
          "code": "CSSM_KEYCLASS",
          "type": "codeVoice"
        },
        {
          "text": "); value is one of ",
          "type": "text"
        },
        {
          "code": "CSSM_KEYCLASS_PUBLIC_KEY",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "CSSM_KEYCLASS_PRIVATE_KEY",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "CSSM_KEYCLASS_SESSION_KEY",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyKeyClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyKeyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyKeyClass"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyKeyClass",
      "type": "topic",
      "url": "/documentation/security/kseckeykeyclass"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyKeyCreator": {
      "abstract": [
        {
          "text": "Type data. The data points to a ",
          "type": "text"
        },
        {
          "code": "CSSM_GUID",
          "type": "codeVoice"
        },
        {
          "text": " structure representing the module ID of the CSP owning this key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyKeyCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyKeyCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyKeyCreator"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyKeyCreator",
      "type": "topic",
      "url": "/documentation/security/kseckeykeycreator"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyKeySizeInBits": {
      "abstract": [
        {
          "text": "Type uint32; value is the number of bits in this key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyKeySizeInBits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyKeySizeInBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyKeySizeInBits"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyKeySizeInBits",
      "type": "topic",
      "url": "/documentation/security/kseckeykeysizeinbits"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyKeyType": {
      "abstract": [
        {
          "text": "Type uint32; value is a CSSM algorithm (",
          "type": "text"
        },
        {
          "code": "CSSM_ALGORITHMS",
          "type": "codeVoice"
        },
        {
          "text": ") representing the algorithm associated with this key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyKeyType"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyKeyType",
      "type": "topic",
      "url": "/documentation/security/kseckeykeytype"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyLabel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyLabel",
      "type": "topic",
      "url": "/documentation/security/kseckeylabel"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyModifiable": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. Attributes of this key can be modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyModifiable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyModifiable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyModifiable"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyModifiable",
      "type": "topic",
      "url": "/documentation/security/kseckeymodifiable"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyNeverExtractable": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key was never marked extractable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyNeverExtractable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyNeverExtractable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyNeverExtractable"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyNeverExtractable",
      "type": "topic",
      "url": "/documentation/security/kseckeyneverextractable"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyPermanent": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key is permanent (stored in some keychain) and is always ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyPermanent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyPermanent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyPermanent"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyPermanent",
      "type": "topic",
      "url": "/documentation/security/kseckeypermanent"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyPrintName": {
      "abstract": [
        {
          "text": "Type blob; human readable name of the key. Same as ",
          "type": "text"
        },
        {
          "code": "kSecLabelItemAttr",
          "type": "codeVoice"
        },
        {
          "text": " for typical keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyPrintName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyPrintName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyPrintName"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyPrintName",
      "type": "topic",
      "url": "/documentation/security/kseckeyprintname"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyPrivate": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key is protected by a user login, a password, or both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyPrivate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyPrivate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyPrivate"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyPrivate",
      "type": "topic",
      "url": "/documentation/security/kseckeyprivate"
    },
    "doc://com.apple.security/documentation/Security/kSecKeySensitive": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key cannot be wrapped with ",
          "type": "text"
        },
        {
          "code": "CSSM_ALGID_NONE",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeySensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeySensitive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeySensitive"
        }
      ],
      "role": "symbol",
      "title": "kSecKeySensitive",
      "type": "topic",
      "url": "/documentation/security/kseckeysensitive"
    },
    "doc://com.apple.security/documentation/Security/kSecKeySign": {
      "abstract": [
        {
          "text": "Type uint32, value is nonzero. This key can be used in a sign operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeySign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeySign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeySign"
        }
      ],
      "role": "symbol",
      "title": "kSecKeySign",
      "type": "topic",
      "url": "/documentation/security/kseckeysign"
    },
    "doc://com.apple.security/documentation/Security/kSecKeySignRecover": {
      "abstract": [
        {
          "text": "Type uint32.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeySignRecover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeySignRecover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeySignRecover"
        }
      ],
      "role": "symbol",
      "title": "kSecKeySignRecover",
      "type": "topic",
      "url": "/documentation/security/kseckeysignrecover"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyStartDate": {
      "abstract": [
        {
          "text": "Type ",
          "type": "text"
        },
        {
          "code": "CSSM_DATE",
          "type": "codeVoice"
        },
        {
          "text": ".  Earliest date at which this key may be used.  If the value is all zeros or not present, no restriction applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyStartDate"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyStartDate",
      "type": "topic",
      "url": "/documentation/security/kseckeystartdate"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyUnwrap": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can unwrap other keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyUnwrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyUnwrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUnwrap"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyUnwrap",
      "type": "topic",
      "url": "/documentation/security/kseckeyunwrap"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyVerify": {
      "abstract": [
        {
          "text": "Type uint32, value is nonzero. This key can be used in a verify operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyVerify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyVerify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyVerify"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyVerify",
      "type": "topic",
      "url": "/documentation/security/kseckeyverify"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyVerifyRecover": {
      "abstract": [
        {
          "text": "Type uint32. This key can unwrap other keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyVerifyRecover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyVerifyRecover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyVerifyRecover"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyVerifyRecover",
      "type": "topic",
      "url": "/documentation/security/kseckeyverifyrecover"
    },
    "doc://com.apple.security/documentation/Security/kSecKeyWrap": {
      "abstract": [
        {
          "text": "Type uint32; value is nonzero. This key can wrap other keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecKeyWrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecKeyWrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyWrap"
        }
      ],
      "role": "symbol",
      "title": "kSecKeyWrap",
      "type": "topic",
      "url": "/documentation/security/kseckeywrap"
    },
    "doc://com.apple.security/documentation/Security/keychain-items": {
      "abstract": [
        {
          "text": "Embed confidential information in items that you store in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-items",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain items",
      "type": "topic",
      "url": "/documentation/security/keychain-items"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecKeyKeyClass",
        "doc://com.apple.security/documentation/Security/kSecKeyPrintName",
        "doc://com.apple.security/documentation/Security/kSecKeyAlias",
        "doc://com.apple.security/documentation/Security/kSecKeyPermanent",
        "doc://com.apple.security/documentation/Security/kSecKeyPrivate",
        "doc://com.apple.security/documentation/Security/kSecKeyModifiable",
        "doc://com.apple.security/documentation/Security/kSecKeyLabel",
        "doc://com.apple.security/documentation/Security/kSecKeyApplicationTag",
        "doc://com.apple.security/documentation/Security/kSecKeyKeyCreator",
        "doc://com.apple.security/documentation/Security/kSecKeyKeyType",
        "doc://com.apple.security/documentation/Security/kSecKeyKeySizeInBits",
        "doc://com.apple.security/documentation/Security/kSecKeyEffectiveKeySize",
        "doc://com.apple.security/documentation/Security/kSecKeyStartDate",
        "doc://com.apple.security/documentation/Security/kSecKeyEndDate",
        "doc://com.apple.security/documentation/Security/kSecKeySensitive",
        "doc://com.apple.security/documentation/Security/kSecKeyAlwaysSensitive",
        "doc://com.apple.security/documentation/Security/kSecKeyExtractable",
        "doc://com.apple.security/documentation/Security/kSecKeyNeverExtractable",
        "doc://com.apple.security/documentation/Security/kSecKeyEncrypt",
        "doc://com.apple.security/documentation/Security/kSecKeyDecrypt",
        "doc://com.apple.security/documentation/Security/kSecKeyDerive",
        "doc://com.apple.security/documentation/Security/kSecKeySign",
        "doc://com.apple.security/documentation/Security/kSecKeyVerify",
        "doc://com.apple.security/documentation/Security/kSecKeySignRecover",
        "doc://com.apple.security/documentation/Security/kSecKeyVerifyRecover",
        "doc://com.apple.security/documentation/Security/kSecKeyWrap",
        "doc://com.apple.security/documentation/Security/kSecKeyUnwrap"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecKeyKeyClass",
                "doc://com.apple.security/documentation/Security/kSecKeyPrintName",
                "doc://com.apple.security/documentation/Security/kSecKeyAlias",
                "doc://com.apple.security/documentation/Security/kSecKeyPermanent",
                "doc://com.apple.security/documentation/Security/kSecKeyPrivate",
                "doc://com.apple.security/documentation/Security/kSecKeyModifiable",
                "doc://com.apple.security/documentation/Security/kSecKeyLabel",
                "doc://com.apple.security/documentation/Security/kSecKeyApplicationTag",
                "doc://com.apple.security/documentation/Security/kSecKeyKeyCreator",
                "doc://com.apple.security/documentation/Security/kSecKeyKeyType",
                "doc://com.apple.security/documentation/Security/kSecKeyKeySizeInBits",
                "doc://com.apple.security/documentation/Security/kSecKeyEffectiveKeySize",
                "doc://com.apple.security/documentation/Security/kSecKeyStartDate",
                "doc://com.apple.security/documentation/Security/kSecKeyEndDate",
                "doc://com.apple.security/documentation/Security/kSecKeySensitive",
                "doc://com.apple.security/documentation/Security/kSecKeyAlwaysSensitive",
                "doc://com.apple.security/documentation/Security/kSecKeyExtractable",
                "doc://com.apple.security/documentation/Security/kSecKeyNeverExtractable",
                "doc://com.apple.security/documentation/Security/kSecKeyEncrypt",
                "doc://com.apple.security/documentation/Security/kSecKeyDecrypt",
                "doc://com.apple.security/documentation/Security/kSecKeyDerive",
                "doc://com.apple.security/documentation/Security/kSecKeySign",
                "doc://com.apple.security/documentation/Security/kSecKeyVerify",
                "doc://com.apple.security/documentation/Security/kSecKeySignRecover",
                "doc://com.apple.security/documentation/Security/kSecKeyVerifyRecover",
                "doc://com.apple.security/documentation/Security/kSecKeyWrap",
                "doc://com.apple.security/documentation/Security/kSecKeyUnwrap"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyDecrypt/title",
          "value": "kSecKeyDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyDecrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyUnwrap/title",
          "value": "kSecKeyUnwrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyUnwrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUnwrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPermanent/title",
          "value": "kSecKeyPermanent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPermanent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyPermanent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEncrypt/title",
          "value": "kSecKeyEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEffectiveKeySize/title",
          "value": "kSecKeyEffectiveKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEffectiveKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyEffectiveKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyType/title",
          "value": "kSecKeyKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyModifiable/title",
          "value": "kSecKeyModifiable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyModifiable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyModifiable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyStartDate/title",
          "value": "kSecKeyStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeySizeInBits/title",
          "value": "kSecKeyKeySizeInBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeySizeInBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyKeySizeInBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySensitive/title",
          "value": "kSecKeySensitive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySensitive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeySensitive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEndDate/title",
          "value": "kSecKeyEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/title",
          "value": "SecItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyCreator/title",
          "value": "kSecKeyKeyCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyKeyCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyWrap/title",
          "value": "kSecKeyWrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyWrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyWrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyAlwaysSensitive/title",
          "value": "kSecKeyAlwaysSensitive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyAlwaysSensitive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyAlwaysSensitive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySignRecover/title",
          "value": "kSecKeySignRecover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySignRecover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeySignRecover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyAlias/title",
          "value": "kSecKeyAlias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyAlias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyAlias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySign/title",
          "value": "kSecKeySign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeySign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeySign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyApplicationTag/title",
          "value": "kSecKeyApplicationTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyApplicationTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyApplicationTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPrintName/title",
          "value": "kSecKeyPrintName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPrintName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyPrintName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyVerify/title",
          "value": "kSecKeyVerify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyVerify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyVerify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyClass/title",
          "value": "kSecKeyKeyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyKeyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyKeyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyVerifyRecover/title",
          "value": "kSecKeyVerifyRecover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyVerifyRecover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyVerifyRecover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyLabel/title",
          "value": "kSecKeyLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyDerive/title",
          "value": "kSecKeyDerive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyDerive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyDerive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyNeverExtractable/title",
          "value": "kSecKeyNeverExtractable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyNeverExtractable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyNeverExtractable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPrivate/title",
          "value": "kSecKeyPrivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyPrivate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyPrivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyExtractable/title",
          "value": "kSecKeyExtractable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecKeyExtractable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyExtractable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/keychain-item-attribute-constants-for-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/keychain-item-attribute-constants-for-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
