{
  "abstract": [
    {
      "text": "Use these constants when you pass dictionary-based arguments to import and export functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/identities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/keychain-import-and-export-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Keychain Import and Export Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAccess": {
      "abstract": [
        {
          "text": "An opaque type that identifies a keychain item’s access information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "role": "symbol",
      "title": "SecAccess",
      "type": "topic",
      "url": "/documentation/security/secaccess"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/identities": {
      "abstract": [
        {
          "text": "Combine certificates and cryptographic keys into identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/identities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Identities",
      "type": "topic",
      "url": "/documentation/security/identities"
    },
    "doc://com.apple.security/documentation/Security/kSecImportExportAccess": {
      "abstract": [
        {
          "text": "An initial access control list represented by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecImportExportAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecImportExportAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecImportExportAccess"
        }
      ],
      "role": "symbol",
      "title": "kSecImportExportAccess",
      "type": "topic",
      "url": "/documentation/security/ksecimportexportaccess"
    },
    "doc://com.apple.security/documentation/Security/kSecImportExportKeychain": {
      "abstract": [
        {
          "text": "A keychain represented by a SecKeychainRef to be used as the target when importing or exporting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecImportExportKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecImportExportKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecImportExportKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSecImportExportKeychain",
      "type": "topic",
      "url": "/documentation/security/ksecimportexportkeychain"
    },
    "doc://com.apple.security/documentation/Security/kSecImportExportPassphrase": {
      "abstract": [
        {
          "text": "A passphrase (represented by a ",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": " object) to be used when exporting to or importing from PKCS#12 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecImportExportPassphrase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecImportExportPassphrase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecImportExportPassphrase"
        }
      ],
      "role": "symbol",
      "title": "kSecImportExportPassphrase",
      "type": "topic",
      "url": "/documentation/security/ksecimportexportpassphrase"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecImportExportPassphrase",
        "doc://com.apple.security/documentation/Security/kSecImportExportKeychain",
        "doc://com.apple.security/documentation/Security/kSecImportExportAccess"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecImportExportPassphrase",
                "doc://com.apple.security/documentation/Security/kSecImportExportKeychain",
                "doc://com.apple.security/documentation/Security/kSecImportExportAccess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportAccess/title",
          "value": "kSecImportExportAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecImportExportAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportPassphrase/title",
          "value": "kSecImportExportPassphrase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportPassphrase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecImportExportPassphrase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportKeychain/title",
          "value": "kSecImportExportKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportExportKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecImportExportKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/title",
          "value": "SecAccessRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/keychain-import-and-export-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/keychain-import-and-export-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
