{
  "abstract": [
    {
      "text": "Securely store small chunks of data on behalf of the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/keychain-services"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "title": "Keychain services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Computer users often have small secrets that they need to store securely. For example, most people manage numerous online accounts. Remembering a complex, unique password for each is impossible, but writing them down is both insecure and tedious. Users typically respond to this situation by recycling simple passwords across many accounts, which is also insecure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The keychain services API helps you solve this problem by giving your app a mechanism to store small bits of user data in an encrypted database called a keychain. When you securely remember the password for them, you free the user to choose a complicated one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The keychain is not limited to passwords, as shown in Figure 1. You can store other secrets that the user explicitly cares about, such as credit card information or even short notes. You can also store items that the user needs but may not be aware of. For example, the cryptographic keys and certificates that you manage with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enable the user to engage in secure communications and to establish trust with other users and devices. You use the keychain to store these items as well.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2891902",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/access-control-lists": {
      "abstract": [
        {
          "text": "Control which apps have access to keychain items in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/access-control-lists",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Access Control Lists",
      "type": "topic",
      "url": "/documentation/security/access-control-lists"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/keychain-items": {
      "abstract": [
        {
          "text": "Embed confidential information in items that you store in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-items",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain items",
      "type": "topic",
      "url": "/documentation/security/keychain-items"
    },
    "doc://com.apple.security/documentation/Security/keychains": {
      "abstract": [
        {
          "text": "Create and manage entire keychains in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychains",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychains",
      "type": "topic",
      "url": "/documentation/security/keychains"
    },
    "media-2891902": {
      "alt": "Diagram showing passwords, keys, certificates, and identities all passing through the Keychain Services API to be stored securely in a keychain.",
      "identifier": "media-2891902",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ad0bbbff6a49d15c0da8e31ef76adb08/media-2891902@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "API-components",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/keychain-items",
        "doc://com.apple.security/documentation/Security/keychains",
        "doc://com.apple.security/documentation/Security/access-control-lists"
      ],
      "title": "API components"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "API-components",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/keychain-items",
                "doc://com.apple.security/documentation/Security/keychains",
                "doc://com.apple.security/documentation/Security/access-control-lists"
              ],
              "title": "API components"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/keychain-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/keychain-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
