{
  "abstract": [
    {
      "text": "The value that indicates a generic password item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/kSecClassGenericPassword"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSecClassGenericPassword",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSecClassGenericPassword"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSecClassGenericPassword"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSecClassGenericPassword"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecClassGenericPassword"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following keychain item attributes form the composite primary key of a generic password item:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " (on macOS, this key only applies if you set ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecUseDataProtectionKeychain",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrSynchronizable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/true",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccount",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrService",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrSynchronizable",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Calls to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that add a generic password item with the same values for all of these attributes as an existing item result in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errSecDuplicateItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following keychain item attributes apply to a generic password item, and don’t form part of its composite primary key:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccess",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " (macOS only)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessControl",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessible",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " (on macOS, this key only applies if you set ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecUseDataProtectionKeychain",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrSynchronizable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/true",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCreationDate",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrModificationDate",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrDescription",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrComment",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCreator",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrType",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsInvisible",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsNegative",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrGeneric",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        }
      ],
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemadd(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain": {
      "abstract": [
        {
          "text": "Add network credentials to the keychain on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain",
      "kind": "article",
      "role": "article",
      "title": "Adding a password to the keychain",
      "type": "topic",
      "url": "/documentation/security/adding-a-password-to-the-keychain"
    },
    "doc://com.apple.security/documentation/Security/errSecDuplicateItem": {
      "abstract": [
        {
          "text": "The item already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSecDuplicateItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSecDuplicateItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSecDuplicateItem"
        }
      ],
      "role": "symbol",
      "title": "errSecDuplicateItem",
      "type": "topic",
      "url": "/documentation/security/errsecduplicateitem"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccess": {
      "abstract": [
        {
          "text": "A key with a value that indicates access control list settings for the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccess"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccess",
      "type": "topic",
      "url": "/documentation/security/ksecattraccess"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccessControl": {
      "abstract": [
        {
          "text": "A key with a value that’s an access control instance indicating access control settings for the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccessControl"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccessControl",
      "type": "topic",
      "url": "/documentation/security/ksecattraccesscontrol"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the access group the item is in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccessGroup"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccessGroup",
      "type": "topic",
      "url": "/documentation/security/ksecattraccessgroup"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccessible": {
      "abstract": [
        {
          "text": "A key with a value that indicates when the keychain item is accessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccessible"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccessible",
      "type": "topic",
      "url": "/documentation/security/ksecattraccessible"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccount": {
      "abstract": [
        {
          "text": "A key whose value is a string indicating the item’s account name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccount"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccount",
      "type": "topic",
      "url": "/documentation/security/ksecattraccount"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrComment": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating a comment associated with the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrComment"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrComment",
      "type": "topic",
      "url": "/documentation/security/ksecattrcomment"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCreationDate": {
      "abstract": [
        {
          "text": "A key with a value that indicates the item’s creation date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCreationDate"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCreationDate",
      "type": "topic",
      "url": "/documentation/security/ksecattrcreationdate"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCreator": {
      "abstract": [
        {
          "text": "A key with a value that indicates the item’s creator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCreator"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCreator",
      "type": "topic",
      "url": "/documentation/security/ksecattrcreator"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrDescription": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the item’s description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrDescription"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrDescription",
      "type": "topic",
      "url": "/documentation/security/ksecattrdescription"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrGeneric": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s user-defined attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrGeneric"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrGeneric",
      "type": "topic",
      "url": "/documentation/security/ksecattrgeneric"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrIsInvisible": {
      "abstract": [
        {
          "text": "A key with a value that’s a Boolean indicating the item’s visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrIsInvisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsInvisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrIsInvisible"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrIsInvisible",
      "type": "topic",
      "url": "/documentation/security/ksecattrisinvisible"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrIsNegative": {
      "abstract": [
        {
          "text": "A key with a value that’s a Boolean indicating whether the item has a valid password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrIsNegative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsNegative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrIsNegative"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrIsNegative",
      "type": "topic",
      "url": "/documentation/security/ksecattrisnegative"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrLabel": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the item’s label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrLabel",
      "type": "topic",
      "url": "/documentation/security/ksecattrlabel"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrModificationDate": {
      "abstract": [
        {
          "text": "A key with a value that indicates the item’s most recent modification date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrModificationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrModificationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrModificationDate"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrModificationDate",
      "type": "topic",
      "url": "/documentation/security/ksecattrmodificationdate"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrService": {
      "abstract": [
        {
          "text": "A key whose value is a string indicating the item’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrService"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrService",
      "type": "topic",
      "url": "/documentation/security/ksecattrservice"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrSynchronizable": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating whether the item synchronizes through iCloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrSynchronizable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrSynchronizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrSynchronizable"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrSynchronizable",
      "type": "topic",
      "url": "/documentation/security/ksecattrsynchronizable"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrType": {
      "abstract": [
        {
          "text": "A key with a value that indicates the item’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrType"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrType",
      "type": "topic",
      "url": "/documentation/security/ksecattrtype"
    },
    "doc://com.apple.security/documentation/Security/kSecClassGenericPassword": {
      "abstract": [
        {
          "text": "The value that indicates a generic password item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClassGenericPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClassGenericPassword"
        }
      ],
      "role": "symbol",
      "title": "kSecClassGenericPassword",
      "type": "topic",
      "url": "/documentation/security/ksecclassgenericpassword"
    },
    "doc://com.apple.security/documentation/Security/kSecUseDataProtectionKeychain": {
      "abstract": [
        {
          "text": "A key whose value indicates whether to treat macOS keychain items like iOS keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecUseDataProtectionKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecUseDataProtectionKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecUseDataProtectionKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSecUseDataProtectionKeychain",
      "type": "topic",
      "url": "/documentation/security/ksecusedataprotectionkeychain"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSecClassGenericPassword"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassGenericPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSecClassGenericPassword"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessible/title",
          "value": "kSecAttrAccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccount/title",
          "value": "kSecAttrAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessGroup/title",
          "value": "kSecAttrAccessGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccessGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCreationDate/title",
          "value": "kSecAttrCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrService/title",
          "value": "kSecAttrService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessControl/title",
          "value": "kSecAttrAccessControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccessControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsNegative/title",
          "value": "kSecAttrIsNegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsNegative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrIsNegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseDataProtectionKeychain/title",
          "value": "kSecUseDataProtectionKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseDataProtectionKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecUseDataProtectionKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsInvisible/title",
          "value": "kSecAttrIsInvisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsInvisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrIsInvisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrGeneric/title",
          "value": "kSecAttrGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCreator/title",
          "value": "kSecAttrCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/title",
          "value": "kSecAttrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/title",
          "value": "kSecClassGenericPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClassGenericPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClassGenericPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrType/title",
          "value": "kSecAttrType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccess/title",
          "value": "kSecAttrAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrModificationDate/title",
          "value": "kSecAttrModificationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrModificationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrModificationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSecDuplicateItem/title",
          "value": "errSecDuplicateItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSecDuplicateItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSecDuplicateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrDescription/title",
          "value": "kSecAttrDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrSynchronizable/title",
          "value": "kSecAttrSynchronizable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrSynchronizable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrSynchronizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrComment/title",
          "value": "kSecAttrComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrComment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/ksecclassgenericpassword"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/ksecclassgenericpassword"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
