{
  "abstract": [
    {
      "text": "Use shared web credentials to create a seamless experience for the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/shared-web-credentials"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/managing-shared-credentials"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Managing Shared Credentials"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are a wide range of common situations where you may want to use shared web credentials. This article covers four:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Logging in to a remote server",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Creating a user account in the app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Changing a user’s password",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Deleting a user’s account",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Logging-In-to-a-Remote-Server",
          "level": 3,
          "text": "Logging In to a Remote Server",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, when an app needs to log in to a remote service, you start by checking for the user’s credentials in the iOS keychain. If you have current credentials for the user, you can log them in directly. If not, prompt the users for their user name and password, and then try to log them in. You will also want to save their credentials after the login is successful. This workflow is shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965823",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-1965823",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When using shared web credentials, you add two steps to this procedure. As before, you start by checking if the user’s credentials are stored in the keychain. If you cannot find the user’s credentials, you check for shared web credentials. If you still cannot find any credentials, or if the user declines to use the shared credentials, you must prompt the user for her name and password. Try to log the user in, and if the login is successful, save the credentials to both the keychain and the shared web credentials. This ensures that the user has access to the credentials in Safari as well as within your app. This workflow is shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965824",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-1965824",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Even if the system finds a match in the shared web credentials, the user can still decline to use those credentials. This will cause the check for shared web credentials to fail. Therefore, you must always have a fallback that prompts the user for their name and password.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Remember",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Do not use the shared web credentials as your primary storage for secure user credentials. Instead, save the user’s credentials in the keychain, and only use the shared web credentials when you can’t find the login credentials in the keychain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To read the user’s credentials from the shared web credentials, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Accessing shared web credentials",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "SecRequestSharedWebCredential(NULL, NULL, ^(CFArrayRef credentials, CFErrorRef error) {",
            " ",
            "    if (error != NULL) {",
            "        // If an error occurs, handle the error here.",
            "        [self handleError:error];",
            "        return;",
            "    }",
            " ",
            "    BOOL success = NO;",
            "    CFStringRef server = NULL;",
            "    CFStringRef userName = NULL;",
            "    CFStringRef password = NULL;",
            " ",
            "    // If credentials are found, use them.",
            "    if (CFArrayGetCount(credentials) > 0) {",
            " ",
            "        // There will only ever be one credential dictionary",
            "        CFDictionaryRef credentialDict =",
            "        CFArrayGetValueAtIndex(credentials, 0);",
            " ",
            "        server = CFDictionaryGetValue(credentialDict, kSecAttrServer);",
            "        userName = CFDictionaryGetValue(credentialDict, kSecAttrAccount);",
            "        password = CFDictionaryGetValue(credentialDict, kSecSharedPassword);",
            " ",
            "        // Attempt to log in",
            "        success = [self logIntoServer:server user:userName password:password];",
            "    }",
            " ",
            "    if (!success) {",
            "        [self promptForUserNameAndPassword];",
            "    } else {",
            "        [self saveCredentialsToKeychainForServer: server user:userName password:password];",
            "    }",
            "});"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The keychain supports saving and loading a wide range of possible credential types. These types can be user name and password pairs, authentication tokens or cookies. Shared web credentials, however, are much more restrictive. You can save only user name and password pairs to the shared web credentials.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Creating-a-User-Account-in-the-App",
          "level": 3,
          "text": "Creating a User Account in the App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user can create new accounts in your app, you should save the user name and password to the shared web credentials. In this way, the user can easily access the account from Safari, as well as from within your app. You can save the user’s name and password to the shared web credentials using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function as shown.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 2. Creating a user account",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "SecAddSharedWebCredential(domain, name, password, ^(CFErrorRef error) {",
            " ",
            "    if (error != NULL) {",
            "        // Handle the error here...",
            "        return;",
            "    }",
            " ",
            "    // The credentials have been successfully saved.",
            " ",
            "});"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If there are no existing credentials for this user name and domain, this method completes without prompting the user for permission.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Changing-a-Users-Password",
          "level": 3,
          "text": "Changing a User’s Password",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user changes her password in the app, you must update both the credentials stored in the keychain and in the shared web credentials. You can change a password using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. This is exactly the same procedure used when creating a new user account (see Creating a User Account in the App, above). However, if credentials already exist for the given user name and domain, this method prompts the user for permission before making the change. The user can cancel this change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Deleting-a-Users-Account",
          "level": 3,
          "text": "Deleting a User’s Account",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user deletes her account, you should remove the credentials from both the keychain and the shared web credentials. You can remove the credentials for a given domain and user name by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function and passing ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " for the password.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 3. Deleting a user account",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "SecAddSharedWebCredential(domain, name, NULL, ^(CFErrorRef error) {",
            " ",
            "    if (error != NULL) {",
            "        // Handle the error here...",
            "        return;",
            "    }",
            " ",
            "    // The account information has been successfully deleted.",
            " ",
            "});"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The system prompts the user for permission before deleting their user name and password from the shared web credentials. Users can cancel this change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to remove a user’s credentials only when the user deletes her account. Do not use this method when the user simply logs out. Passing a ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " password to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " removes the user’s credentials and prevents Safari from autocompleting her login information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/security/shared_web_credentials/managing_shared_credentials#1965823": {
      "identifier": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965823",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965823"
    },
    "/documentation/security/shared_web_credentials/managing_shared_credentials#1965824": {
      "identifier": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965824",
      "title": "Figure 2",
      "titleInlineContent": [
        {
          "text": "Figure 2",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/security/shared_web_credentials/managing_shared_credentials#1965824"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Asynchronously stores (or updates) a shared password for a website.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAddSharedWebCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAddSharedWebCredential"
        }
      ],
      "role": "symbol",
      "title": "SecAddSharedWebCredential(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secaddsharedwebcredential(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)": {
      "abstract": [
        {
          "text": "Asynchronously obtains one or more shared passwords for a website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequestSharedWebCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequestSharedWebCredential"
        }
      ],
      "role": "symbol",
      "title": "SecRequestSharedWebCredential(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secrequestsharedwebcredential(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/shared-web-credentials": {
      "abstract": [
        {
          "text": "Share credentials between iOS apps and their website counterparts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/shared-web-credentials",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared Web Credentials",
      "type": "topic",
      "url": "/documentation/security/shared-web-credentials"
    },
    "media-1965823": {
      "alt": null,
      "identifier": "media-1965823",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/98e039bdd2ff903d76dfa39a97206085/media-1965823@2x.png"
        }
      ]
    },
    "media-1965824": {
      "alt": null,
      "identifier": "media-1965824",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7f06e56b3e179a5878e829b668edf416/media-1965824@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequestSharedWebCredential(_:_:_:)/title",
          "value": "SecRequestSharedWebCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequestSharedWebCredential(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequestSharedWebCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAddSharedWebCredential(_:_:_:_:)/title",
          "value": "SecAddSharedWebCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAddSharedWebCredential(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAddSharedWebCredential"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/managing-shared-credentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/managing-shared-credentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
