{
  "abstract": [
    {
      "text": "Streamline your app’s login and onboarding procedures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/password-autofill"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "title": "Password AutoFill"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Password AutoFill simplifies login and account creation tasks for iOS apps and webpages. With just a few taps, your users can create and save new passwords or log in to an existing account. Users don’t even need to know their password; the system handles everything. This convenience increases the likelihood that users will complete your app’s onboarding process and start using your app more quickly. Additionally, by encouraging users to select unique, strong passwords, you increase the security of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, Password AutoFill saves the user’s login credentials on their current iOS device. iOS can sync these credentials securely across the user’s devices using iCloud Keychain. Password AutoFill recommends credentials only for your app’s associated domain, and the user must authenticate using Face ID or Touch ID before accessing these credentials. For more information on privacy and security, see ",
              "type": "text"
            },
            {
              "identifier": "https://www.apple.com/privacy/approach-to-privacy/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://images.apple.com/business/docs/iOS_Security_Guide.pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Password AutoFill also provides credentials from third-party password managers that implement a credential provider extension. For more information on the credential provider extension, see the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-Password-AutoFill",
          "level": 3,
          "text": "Enable Password AutoFill",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Password AutoFill uses heuristics to determine when the user logs in or creates new passwords, and automatically provides the password QuickType bar. These heuristics give users some Password AutoFill support in most apps, even if those apps haven’t been updated to support AutoFill. However, to provide the best user experience and ensure your app fully supports Password AutoFill, perform the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set up your app’s associated domains. To learn how to set up your app’s associated domains, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the correct AutoFill type on relevant text fields. For an iOS app, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-a-text-input-view",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For a web app, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-an-html-input-element",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Support-third-party-web-services",
          "level": 3,
          "text": "Support third-party web services",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Password AutoFill streamlines logging into web services at your domain; however, if you need to log into a third-party service, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead, which supports Password AutoFill when your user hasn’t already logged in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Integrate-a-password-management-app-with-Password-AutoFill",
          "level": 3,
          "text": "Integrate a password management app with Password AutoFill",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re developing a password management app, create AutoFill Credential Provider Extensions to surface credentials from your app in Password AutoFill and pull your app’s password data into the Password AutoFill workflow. When your app integrates with Password AutoFill, users don’t have to copy and paste credentials. Instead, they can use password data stored in your app easily because the data will be offered to the user to fill in compatible user name and password fields. To integrate a password app with Password AutoFill, use in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/AuthenticationServices"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession": {
      "abstract": [
        {
          "text": "A session that an app uses to authenticate a user through a web service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASWebAuthenticationSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASWebAuthenticationSession",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASWebAuthenticationSession"
    },
    "doc://com.apple.documentation/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/applinks",
      "kind": "symbol",
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/BundleResources/applinks"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextContentType/newPassword": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a new password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextContentType/newPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "newPassword",
      "type": "topic",
      "url": "/documentation/UIKit/UITextContentType/newPassword"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextContentType/oneTimeCode": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a one-time code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextContentType/oneTimeCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "oneTimeCode",
      "type": "topic",
      "url": "/documentation/UIKit/UITextContentType/oneTimeCode"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextContentType/password": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextContentType/password",
      "kind": "symbol",
      "role": "symbol",
      "title": "password",
      "type": "topic",
      "url": "/documentation/UIKit/UITextContentType/password"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextContentType/username": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as an account or login name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextContentType/username",
      "kind": "symbol",
      "role": "symbol",
      "title": "username",
      "type": "topic",
      "url": "/documentation/UIKit/UITextContentType/username"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextInputPasswordRules": {
      "abstract": [
        {
          "text": "A class that represents password rules for a text input field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInputPasswordRules"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputPasswordRules",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextInputPasswordRules",
      "type": "topic",
      "url": "/documentation/UIKit/UITextInputPasswordRules"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@NSCopying"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passwordRules"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextInputPasswordRules",
          "text": "UITextInputPasswordRules"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules",
      "kind": "symbol",
      "role": "symbol",
      "title": "passwordRules",
      "type": "topic",
      "url": "/documentation/UIKit/UITextInputTraits/passwordRules"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/textContentType": {
      "abstract": [
        {
          "text": "The semantic meaning for a text input area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        },
        {
          "kind": "text",
          "text": "! { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/textContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType",
      "type": "topic",
      "url": "/documentation/UIKit/UITextInputTraits/textContentType"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/about-the-password-autofill-workflow": {
      "abstract": [
        {
          "text": "Learn how Password AutoFill interacts with both iOS and web apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/about-the-password-autofill-workflow",
      "kind": "article",
      "role": "article",
      "title": "About the Password AutoFill workflow",
      "type": "topic",
      "url": "/documentation/security/about-the-password-autofill-workflow"
    },
    "doc://com.apple.security/documentation/Security/customizing-password-autofill-rules": {
      "abstract": [
        {
          "text": "Modify the strong password rules for your app by adding your own restrictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/customizing-password-autofill-rules",
      "kind": "article",
      "role": "article",
      "title": "Customizing Password AutoFill rules",
      "type": "topic",
      "url": "/documentation/security/customizing-password-autofill-rules"
    },
    "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-a-text-input-view": {
      "abstract": [
        {
          "text": "Make sure a text input view displays the correct AutoFill suggestions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-a-text-input-view",
      "kind": "article",
      "role": "article",
      "title": "Enabling Password AutoFill on a text input view",
      "type": "topic",
      "url": "/documentation/security/enabling-password-autofill-on-a-text-input-view"
    },
    "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-an-html-input-element": {
      "abstract": [
        {
          "text": "Make sure a web view or webpage provides the correct AutoFill suggestions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-an-html-input-element",
      "kind": "article",
      "role": "article",
      "title": "Enabling Password AutoFill on an HTML input element",
      "type": "topic",
      "url": "/documentation/security/enabling-password-autofill-on-an-html-input-element"
    },
    "https://images.apple.com/business/docs/iOS_Security_Guide.pdf": {
      "identifier": "https://images.apple.com/business/docs/iOS_Security_Guide.pdf",
      "title": "iOS Security Guide",
      "titleInlineContent": [
        {
          "text": "iOS Security Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://images.apple.com/business/docs/iOS_Security_Guide.pdf"
    },
    "https://www.apple.com/privacy/approach-to-privacy/": {
      "identifier": "https://www.apple.com/privacy/approach-to-privacy/",
      "title": "Approach to Privacy",
      "titleInlineContent": [
        {
          "text": "Approach to Privacy",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.apple.com/privacy/approach-to-privacy/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/about-the-password-autofill-workflow",
        "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
        "doc://com.apple.documentation/documentation/BundleResources/applinks"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Text-input-views",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-a-text-input-view",
        "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/textContentType",
        "doc://com.apple.documentation/documentation/UIKit/UITextContentType/username",
        "doc://com.apple.documentation/documentation/UIKit/UITextContentType/password",
        "doc://com.apple.documentation/documentation/UIKit/UITextContentType/newPassword",
        "doc://com.apple.documentation/documentation/UIKit/UITextContentType/oneTimeCode"
      ],
      "title": "Text input views"
    },
    {
      "anchor": "Text-input-elements",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-an-html-input-element"
      ],
      "title": "Text input elements"
    },
    {
      "anchor": "Password-rules",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/customizing-password-autofill-rules",
        "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules",
        "doc://com.apple.documentation/documentation/UIKit/UITextInputPasswordRules"
      ],
      "title": "Password rules"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/about-the-password-autofill-workflow",
                "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                "doc://com.apple.documentation/documentation/BundleResources/applinks"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Text-input-views",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-a-text-input-view",
                "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/textContentType",
                "doc://com.apple.documentation/documentation/UIKit/UITextContentType/username",
                "doc://com.apple.documentation/documentation/UIKit/UITextContentType/password",
                "doc://com.apple.documentation/documentation/UIKit/UITextContentType/newPassword",
                "doc://com.apple.documentation/documentation/UIKit/UITextContentType/oneTimeCode"
              ],
              "title": "Text input views"
            },
            {
              "anchor": "Text-input-elements",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/enabling-password-autofill-on-an-html-input-element"
              ],
              "title": "Text input elements"
            },
            {
              "anchor": "Password-rules",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/customizing-password-autofill-rules",
                "doc://com.apple.documentation/documentation/UIKit/UITextInputTraits/passwordRules",
                "doc://com.apple.documentation/documentation/UIKit/UITextInputPasswordRules"
              ],
              "title": "Password rules"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASWebAuthenticationSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASWebAuthenticationSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextInputTraits~1passwordRules/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextInputPasswordRules",
              "text": "UITextInputPasswordRules"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "passwordRules"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1username/title",
          "value": "UITextContentTypeUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1username/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextContentType",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextContentTypeUsername"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1newPassword/title",
          "value": "UITextContentTypeNewPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1newPassword/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextContentType",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextContentTypeNewPassword"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextInputTraits~1textContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextContentType",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1password/title",
          "value": "UITextContentTypePassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1password/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextContentType",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextContentTypePassword"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextInputPasswordRules/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextInputPasswordRules"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1oneTimeCode/title",
          "value": "UITextContentTypeOneTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextContentType~1oneTimeCode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextContentType",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextContentTypeOneTimeCode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/password-autofill"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/password-autofill"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
