{
  "abstract": [
    {
      "text": "Use these constants to set rights and rules in the policy database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/authorization-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/policy-database-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Policy Database Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants when creating or modifying a rule in the policy database using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRightSet(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationRightSet(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates or updates a right entry in the policy database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRightSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFBundleRef",
          "text": "CFBundle"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationRightSet(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationRightSet"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationRightSet(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/authorizationrightset(_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/authorization-services": {
      "abstract": [
        {
          "text": "Access restricted areas of the operating system, and control access to particular features of your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Services",
      "type": "topic",
      "url": "/documentation/security/authorization-services"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationComment": {
      "abstract": [
        {
          "text": "Indicates comments for a rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationComment"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationComment",
      "type": "topic",
      "url": "/documentation/security/kauthorizationcomment"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRightRule": {
      "abstract": [
        {
          "text": "Indicates a rule delegation key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRightRule"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRightRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRightRule"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRightRule",
      "type": "topic",
      "url": "/documentation/security/kauthorizationrightrule"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsAdmin": {
      "abstract": [
        {
          "text": "Indicates a delegate rule definition constant specifying that the user must authenticate as an administrator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleAuthenticateAsAdmin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsAdmin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleAuthenticateAsAdmin"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRuleAuthenticateAsAdmin",
      "type": "topic",
      "url": "/documentation/security/kauthorizationruleauthenticateasadmin"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsSessionUser": {
      "abstract": [
        {
          "text": "Indicates a delegate rule definition constant specifying that the user must authenticate as the session owner (logged-in user).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleAuthenticateAsSessionUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsSessionUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleAuthenticateAsSessionUser"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRuleAuthenticateAsSessionUser",
      "type": "topic",
      "url": "/documentation/security/kauthorizationruleauthenticateassessionuser"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassAllow": {
      "abstract": [
        {
          "text": "Indicates a delegate rule definition constant that always allows the specified right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleClassAllow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassAllow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleClassAllow"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRuleClassAllow",
      "type": "topic",
      "url": "/documentation/security/kauthorizationruleclassallow"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassDeny": {
      "abstract": [
        {
          "text": "Indicates a delegate rule definition constant that always denies the specified right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleClassDeny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassDeny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleClassDeny"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRuleClassDeny",
      "type": "topic",
      "url": "/documentation/security/kauthorizationruleclassdeny"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationRuleIsAdmin": {
      "abstract": [
        {
          "text": "Indicates a delegate rule definition constant specifying that the user must be an administrator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleIsAdmin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationRuleIsAdmin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationRuleIsAdmin"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationRuleIsAdmin",
      "type": "topic",
      "url": "/documentation/security/kauthorizationruleisadmin"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kAuthorizationRightRule",
        "doc://com.apple.security/documentation/Security/kAuthorizationRuleIsAdmin",
        "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsAdmin",
        "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsSessionUser",
        "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassAllow",
        "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassDeny",
        "doc://com.apple.security/documentation/Security/kAuthorizationComment"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kAuthorizationRightRule",
                "doc://com.apple.security/documentation/Security/kAuthorizationRuleIsAdmin",
                "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsAdmin",
                "doc://com.apple.security/documentation/Security/kAuthorizationRuleAuthenticateAsSessionUser",
                "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassAllow",
                "doc://com.apple.security/documentation/Security/kAuthorizationRuleClassDeny",
                "doc://com.apple.security/documentation/Security/kAuthorizationComment"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRightSet(_:_:_:_:_:_:)/title",
          "value": "AuthorizationRightSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationRightSet(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationRightSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleClassDeny/title",
          "value": "kAuthorizationRuleClassDeny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleClassDeny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRuleClassDeny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleClassAllow/title",
          "value": "kAuthorizationRuleClassAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleClassAllow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRuleClassAllow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleIsAdmin/title",
          "value": "kAuthorizationRuleIsAdmin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleIsAdmin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRuleIsAdmin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleAuthenticateAsAdmin/title",
          "value": "kAuthorizationRuleAuthenticateAsAdmin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleAuthenticateAsAdmin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRuleAuthenticateAsAdmin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRightRule/title",
          "value": "kAuthorizationRightRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRightRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRightRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleAuthenticateAsSessionUser/title",
          "value": "kAuthorizationRuleAuthenticateAsSessionUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationRuleAuthenticateAsSessionUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationRuleAuthenticateAsSessionUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationComment/title",
          "value": "kAuthorizationComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationComment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/policy-database-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/policy-database-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
