{
  "abstract": [
    {
      "text": "Enforce secure network links in your app by relying on App Transport Security.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/preventing-insecure-network-connections"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "title": "Preventing Insecure Network Connections"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On Apple platforms, a networking security feature called App Transport Security (ATS) improves privacy and data integrity for all apps and app extensions. It does this by requiring that network connections made by your app are secured by the Transport Layer Security (TLS) protocol using reliable certificates and ciphers. ATS blocks connections that don’t meet minimum security requirements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3162039",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "ATS operates by default for apps linked against the iOS 9.0 or macOS 10.11 SDKs or later. In cases where you need to connect to a server that isn’t fully secure—and that you can’t reconfigure to make more secure—you can add exceptions to loosen some of the ATS requirements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you link your app against an SDK older than iOS 9.0 or macOS 10.11, ATS is disabled no matter which version of the operating system your app runs on.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Prefer-High-Level-Frameworks-in-Your-App",
          "level": 3,
          "text": "Prefer High-Level Frameworks in Your App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system enforces ATS when you use the standard ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " automatically negotiate the most secure connection available from the server. The only action your app must take is to use secure URLs, like those beginning with ",
              "type": "text"
            },
            {
              "code": "https",
              "type": "codeVoice"
            },
            {
              "text": ". Otherwise, ATS denies the connection and prints a console message:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "App Transport Security has blocked a cleartext HTTP (http://) resource",
            "load since it is insecure. Temporary exceptions can be configured via",
            "your app's Info.plist file."
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "ATS doesn’t apply to calls your app makes to lower-level networking interfaces like the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Network",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CFNetwork",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In these cases, you take responsibility for ensuring the security of the connection. You can construct a secure connection this way, but mistakes are both easy to make and costly. It’s typically safest to rely on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Ensure-the-Network-Server-Meets-Minimum-Requirements",
          "level": 3,
          "text": "Ensure the Network Server Meets Minimum Requirements",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A secure server establishes its identity using an X.509 digital certificate. A connecting client examines this certificate to perform default server trust evaluation, which includes checking that the certificate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Has an intact digital signature, showing that the certificate hasn’t been tampered with.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Isn’t expired.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Has a name that matches the server’s DNS name.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Is signed by another valid certificate, which is in turned signed by another, and so on back to a trusted anchor certificate, which must be issued by a Certificate Authority (CA). The anchor certificate must be part of the client operating system, as indicated in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/en-us/HT204132",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or be installed on the client by the user or a system administrator.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "ATS requires all of these things, and then provides extended security checks:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The server certificate must be signed with either a Rivest-Shamir-Adleman (RSA) key of at least 2048 bits, or an Elliptic-Curve Cryptography (ECC) key of at least 256 bits.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The certificate must use the Secure Hash Algorithm 2 (SHA-2) with a digest length, sometimes called a ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "fingerprint",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", of at least 256 bits (that is, SHA-256 or greater).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The connection must use Transport Layer Security (TLS) protocol version 1.2 or later.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Data must be exchanged using either the AES-128 or the AES-256 symmetric cipher.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The link must support perfect forward secrecy (PFS) through Elliptic Curve Diffie-Hellman Ephemeral (ECDHE) key exchange.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " automatically handles server trust evaluation for you, but enables you to customize the process, for example to extend trust to a self-signed certificate embedded in your app, or to bypass certificate expiry. When ATS is enabled, you can no longer loosen trust evaluation requirements that way, but you can still tighten them—for example, to implement certificate pinning. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-Exceptions-Only-When-Needed-Prefer-Server-Fixes",
          "level": 3,
          "text": "Configure Exceptions Only When Needed; Prefer Server Fixes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ATS disallows a connection if the server fails to meet one of the security checks discussed in the previous section. Your best response is to update the server. If you can’t do that for some reason, you can specify exceptions in your app to disable one or more aspects of ATS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "It’s always better to fix the server when faced with an ATS failure. Exceptions reduce the security of your app. Some also require justification when submitting an app to the App Store, as described in the next section.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "You configure ATS exceptions by providing a dictionary as the value for the optional ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file. The dictionary has the following structure, where all keys are optional:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "NSAppTransportSecurity : Dictionary {",
            "    NSAllowsArbitraryLoads : Boolean",
            "    NSAllowsArbitraryLoadsForMedia : Boolean",
            "    NSAllowsArbitraryLoadsInWebContent : Boolean",
            "    NSAllowsLocalNetworking : Boolean",
            "    NSExceptionDomains : Dictionary {",
            "        <domain-name-string> : Dictionary {",
            "            NSIncludesSubdomains : Boolean",
            "            NSExceptionAllowsInsecureHTTPLoads : Boolean",
            "            NSExceptionMinimumTLSVersion : String",
            "            NSExceptionRequiresForwardSecrecy : Boolean",
            "            NSRequiresCertificateTransparency : Boolean",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Keys at the first level of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary apply to connections made to any domain not specifically called out in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sub-dictionary. For example, by setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", you completely disable ATS for all network connections:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3138689",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Depending on your use case, you can provide narrower exceptions. For example, by setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", you can disable ATS restrictions on calls made from within web views, like instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3138691",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You might only need to limit your ATS exception to a single domain. For example, if you need to access the insecure server ",
              "type": "text"
            },
            {
              "code": "http://example.com",
              "type": "codeVoice"
            },
            {
              "text": ", you can still maintain all the benefits of ATS for other domains by setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": " in the domain-specific sub-dictionary:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3138690",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Global exceptions don’t apply to any domains that you add to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " dictionary. So you can invert the previous example—allowing insecure traffic on all domains ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "except",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "example.com",
                  "type": "codeVoice"
                },
                {
                  "text": "—by placing ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " at the top level, and including an empty ",
                  "type": "text"
                },
                {
                  "code": "example.com",
                  "type": "codeVoice"
                },
                {
                  "text": " dictionary as an exception domain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the ",
              "type": "text"
            },
            {
              "code": "nscurl",
              "type": "codeVoice"
            },
            {
              "text": " command line tool to connect to a server using different combinations of ATS exceptions. This helps you quickly narrow down the source of any ATS failures you have and figure out what exceptions you need. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/identifying-the-source-of-blocked-connections",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-Justification-for-Exceptions",
          "level": 3,
          "text": "Provide Justification for Exceptions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Adding certain ATS exceptions to your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file requires you to provide justification, and might trigger additional App Store review for your app. Exceptions that require justification are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Arbitrary connection exceptions (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Media streaming exceptions (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Web content loads (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Per-domain nonsecure connections (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Per-domain minimum TLS version (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Some examples of justifications eligible for consideration are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app must connect to a server managed by another entity that doesn’t support secure connections.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app must support connecting to devices that cannot be upgraded to use secure connections, and that must be accessed using public host names.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app must display embedded web content from a variety of sources, but can’t use a class supported by the web content exception.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app loads media content that is encrypted and that contains no personalized information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When submitting your app to the App Store, provide sufficient information for the App Store to determine why your app cannot make secure connections by default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Always look for a way to avoid using exceptions as a first recourse. If you must use an exception, make it as limited in scope as possible.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "role": "symbol",
      "title": "Information Property List",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity": {
      "abstract": [
        {
          "text": "A description of changes made to the default security for HTTP connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppTransportSecurity",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether App Transport Security restrictions are disabled for all network connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAllowsArbitraryLoads",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether all App Transport Security restrictions are disabled for requests made using the AV Foundation framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAllowsArbitraryLoadsForMedia",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether all App Transport Security restrictions are disabled for requests made from web views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAllowsArbitraryLoadsInWebContent",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains": {
      "abstract": [
        {
          "text": "Custom App Transport Security (ATS) configurations for named domains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExceptionDomains",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to allow insecure HTTP loads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExceptionAllowsInsecureHTTPLoads",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion": {
      "abstract": [
        {
          "text": "The minimum Transport Layer Security (TLS) version for network connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExceptionMinimumTLSVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion"
    },
    "doc://com.apple.documentation/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/CFNetwork"
    },
    "doc://com.apple.documentation/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/Network"
    },
    "doc://com.apple.documentation/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/WebKit/WKWebView"
    },
    "doc://com.apple.documentation/documentation/foundation/url_loading_system": {
      "abstract": [
        {
          "text": "Interact with URLs and communicate with servers using standard Internet protocols. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system",
      "kind": "article",
      "role": "article",
      "title": "URL Loading System",
      "type": "topic",
      "url": "/documentation/foundation/url_loading_system"
    },
    "doc://com.apple.documentation/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication": {
      "abstract": [
        {
          "text": "Evaluate the server’s security credentials in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication",
      "kind": "article",
      "role": "article",
      "title": "Performing manual server trust authentication",
      "type": "topic",
      "url": "/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsession": {
      "abstract": [
        {
          "text": "An object that coordinates a group of related, network data transfer tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLSession",
      "type": "topic",
      "url": "/documentation/foundation/urlsession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/identifying-the-source-of-blocked-connections": {
      "abstract": [
        {
          "text": "Figure out why App Transport Security denies a network connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/identifying-the-source-of-blocked-connections",
      "kind": "article",
      "role": "article",
      "title": "Identifying the Source of Blocked Connections",
      "type": "topic",
      "url": "/documentation/security/identifying-the-source-of-blocked-connections"
    },
    "https://support.apple.com/en-us/HT204132": {
      "identifier": "https://support.apple.com/en-us/HT204132",
      "title": "Lists of available trusted root certificates in iOS",
      "titleInlineContent": [
        {
          "text": "Lists of available trusted root certificates in iOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT204132"
    },
    "media-3138689": {
      "alt": null,
      "identifier": "media-3138689",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c980f5c9c7c8e8e985bd11f2066aa51b/media-3138689@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fe61f9fff064d6e4b04e6afc05319783/media-3138689~dark@2x.png"
        }
      ]
    },
    "media-3138690": {
      "alt": null,
      "identifier": "media-3138690",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/15237498eed9ac779b0b43b1bc161735/media-3138690@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/eea384dd50f805f66c3baf8e34a0be64/media-3138690~dark@2x.png"
        }
      ]
    },
    "media-3138691": {
      "alt": null,
      "identifier": "media-3138691",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/525ffcae55afd38ad9626f2b15594542/media-3138691@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/42e45ccab449196c19ad08010fe10b4e/media-3138691~dark@2x.png"
        }
      ]
    },
    "media-3162039": {
      "alt": "Diagram showing how ATS blocks insecure connections, but lets secure traffic flow between your app and the network.",
      "identifier": "media-3162039",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fe39fdee2649e965806cb8b8b4aa45f4/media-3162039@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/01694cd2b712f4b4b3768b1ac4ca3cc9/media-3162039~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Evaluation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/identifying-the-source-of-blocked-connections"
      ],
      "title": "Evaluation"
    },
    {
      "anchor": "Exceptions",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity"
      ],
      "title": "Exceptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Evaluation",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/identifying-the-source-of-blocked-connections"
              ],
              "title": "Evaluation"
            },
            {
              "anchor": "Exceptions",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity"
              ],
              "title": "Exceptions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession/title",
          "value": "NSURLSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKWebView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/preventing-insecure-network-connections"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/preventing-insecure-network-connections"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
