{
  "abstract": [
    {
      "text": "Use these flags to create a revocation policy object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/policies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/revocation-policy-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Revocation Policy Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these flags with a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicyCreateRevocation(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to characterize the constructed policy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecPolicyCreateRevocation(_:)": {
      "abstract": [
        {
          "text": "Returns a policy object for checking revocation of certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecPolicyCreateRevocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecPolicyRef",
          "text": "SecPolicy"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicyCreateRevocation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecPolicyCreateRevocation"
        }
      ],
      "role": "symbol",
      "title": "SecPolicyCreateRevocation(_:)",
      "type": "topic",
      "url": "/documentation/security/secpolicycreaterevocation(_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationCRLMethod": {
      "abstract": [
        {
          "text": "Perform revocation checking using the CRL (Certification Revocation List) method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationCRLMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationCRLMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationCRLMethod"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationCRLMethod",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationcrlmethod"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationNetworkAccessDisabled": {
      "abstract": [
        {
          "text": "Consult only locally cached replies; do not use network access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationNetworkAccessDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationNetworkAccessDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationNetworkAccessDisabled"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationNetworkAccessDisabled",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationnetworkaccessdisabled"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationOCSPMethod": {
      "abstract": [
        {
          "text": "Perform revocation     checking using OCSP (Online Certificate Status Protocol).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationOCSPMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationOCSPMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationOCSPMethod"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationOCSPMethod",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationocspmethod"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationPreferCRL": {
      "abstract": [
        {
          "text": "Prefer CRL revocation checking over OCSP; by default, OCSP is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationPreferCRL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationPreferCRL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationPreferCRL"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationPreferCRL",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationprefercrl"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationRequirePositiveResponse": {
      "abstract": [
        {
          "text": "Require a positive response to pass the policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationRequirePositiveResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationRequirePositiveResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationRequirePositiveResponse"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationRequirePositiveResponse",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationrequirepositiveresponse"
    },
    "doc://com.apple.security/documentation/Security/kSecRevocationUseAnyAvailableMethod": {
      "abstract": [
        {
          "text": "Perform either OCSP or CRL checking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecRevocationUseAnyAvailableMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecRevocationUseAnyAvailableMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRevocationUseAnyAvailableMethod"
        }
      ],
      "role": "symbol",
      "title": "kSecRevocationUseAnyAvailableMethod",
      "type": "topic",
      "url": "/documentation/security/ksecrevocationuseanyavailablemethod"
    },
    "doc://com.apple.security/documentation/Security/policies": {
      "abstract": [
        {
          "text": "Obtain policies for establishing trust.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/policies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Policies",
      "type": "topic",
      "url": "/documentation/security/policies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecRevocationCRLMethod",
        "doc://com.apple.security/documentation/Security/kSecRevocationNetworkAccessDisabled",
        "doc://com.apple.security/documentation/Security/kSecRevocationOCSPMethod",
        "doc://com.apple.security/documentation/Security/kSecRevocationPreferCRL",
        "doc://com.apple.security/documentation/Security/kSecRevocationRequirePositiveResponse",
        "doc://com.apple.security/documentation/Security/kSecRevocationUseAnyAvailableMethod"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecRevocationCRLMethod",
                "doc://com.apple.security/documentation/Security/kSecRevocationNetworkAccessDisabled",
                "doc://com.apple.security/documentation/Security/kSecRevocationOCSPMethod",
                "doc://com.apple.security/documentation/Security/kSecRevocationPreferCRL",
                "doc://com.apple.security/documentation/Security/kSecRevocationRequirePositiveResponse",
                "doc://com.apple.security/documentation/Security/kSecRevocationUseAnyAvailableMethod"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationCRLMethod/title",
          "value": "kSecRevocationCRLMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationCRLMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationCRLMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationRequirePositiveResponse/title",
          "value": "kSecRevocationRequirePositiveResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationRequirePositiveResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationRequirePositiveResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationOCSPMethod/title",
          "value": "kSecRevocationOCSPMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationOCSPMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationOCSPMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationNetworkAccessDisabled/title",
          "value": "kSecRevocationNetworkAccessDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationNetworkAccessDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationNetworkAccessDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationUseAnyAvailableMethod/title",
          "value": "kSecRevocationUseAnyAvailableMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationUseAnyAvailableMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationUseAnyAvailableMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationPreferCRL/title",
          "value": "kSecRevocationPreferCRL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecRevocationPreferCRL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRevocationPreferCRL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicyCreateRevocation(_:)/title",
          "value": "SecPolicyCreateRevocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicyCreateRevocation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyCreateRevocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/revocation-policy-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/revocation-policy-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
