{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/sec_protocol_options_set_enable_encrypted_client_hello"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@sec_protocol_options_set_enable_encrypted_client_hello",
    "fragments": [
      {
        "kind": "identifier",
        "text": "sec_protocol_options_set_enable_encrypted_client_hello"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sec_protocol_options_set_enable_encrypted_client_hello"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "sec_protocol_options_set_enable_encrypted_client_hello"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sec_protocol_options_set_enable_encrypted_client_hello"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_options_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sec_protocol_options_t",
              "text": "sec_protocol_options_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:b",
              "text": "bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "enable_encrypted_client_hello"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "sec_protocol_options_t",
                  "type": "codeVoice"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "code": [
            "  For experimental use only. When this is enabled, the Encrypted Client Hello extension will be sent on the Client",
            "  Hello if TLS 1.3 is among the supported TLS versions. Default false."
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/sec_protocol_options_set_enable_encrypted_client_hello": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sec_protocol_options_set_enable_encrypted_client_hello"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_options_set_enable_encrypted_client_hello",
      "kind": "symbol",
      "role": "symbol",
      "title": "sec_protocol_options_set_enable_encrypted_client_hello",
      "type": "topic",
      "url": "/documentation/security/sec_protocol_options_set_enable_encrypted_client_hello"
    },
    "doc://com.apple.security/documentation/Security/sec_protocol_options_t": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "sec_protocol_options",
          "type": "codeVoice"
        },
        {
          "text": " instance is a container of options for security protocol instances,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "such as TLS. Protocol options are used to configure security protocols in the network stack.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "For example, clients may set the maximum and minimum allowed TLS versions through protocol",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sec_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sec_protocol_options_t"
        }
      ],
      "role": "symbol",
      "title": "sec_protocol_options_t",
      "type": "topic",
      "url": "/documentation/security/sec_protocol_options_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_options_t/title",
          "value": "sec_protocol_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_options_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sec_protocol_options_set_enable_encrypted_client_hello"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
