{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@sec_protocol_pre_shared_key_selection_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sec_protocol_pre_shared_key_selection_t"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sec_protocol_pre_shared_key_selection_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "sec_protocol_pre_shared_key_selection_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_t"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_metadata_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sec_protocol_metadata_t",
              "text": "sec_protocol_metadata_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "dispatch_data_t"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_complete_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sec_protocol_pre_shared_key_selection_complete_t",
              "text": "sec_protocol_pre_shared_key_selection_complete_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "sec_protocol_metadata_t",
                  "type": "codeVoice"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "metadata"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "dispatch_data_t",
                  "type": "codeVoice"
                },
                {
                  "text": " object carrying the peer’s (optional) PSK identity hint.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "psk_identity_hint"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "sec_protocol_pre_shared_key_selection_complete_t",
                  "type": "codeVoice"
                },
                {
                  "text": " block to be invoked when PSK selection is complete.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "complete"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "code": [
            "  Block to be invoked when the client must choose a PSK identity given a hint from its peer."
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/sec_protocol_metadata_t": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "sec_protocol_metadata",
          "type": "codeVoice"
        },
        {
          "text": " instance conatins read-only properties of a connected and configured",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "security protocol. Clients use this object to read information about a protocol instance. Properties",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "include, for example, the negotiated TLS version, ciphersuite, and peer certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sec_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_metadata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sec_protocol_metadata_t"
        }
      ],
      "role": "symbol",
      "title": "sec_protocol_metadata_t",
      "type": "topic",
      "url": "/documentation/security/sec_protocol_metadata_t"
    },
    "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_complete_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sec_protocol_pre_shared_key_selection_complete_t"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_complete_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sec_protocol_pre_shared_key_selection_complete_t"
        }
      ],
      "role": "symbol",
      "title": "sec_protocol_pre_shared_key_selection_complete_t",
      "type": "topic",
      "url": "/documentation/security/sec_protocol_pre_shared_key_selection_complete_t"
    },
    "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sec_protocol_pre_shared_key_selection_t"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sec_protocol_pre_shared_key_selection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sec_protocol_pre_shared_key_selection_t"
        }
      ],
      "role": "symbol",
      "title": "sec_protocol_pre_shared_key_selection_t",
      "type": "topic",
      "url": "/documentation/security/sec_protocol_pre_shared_key_selection_t"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sec_protocol_pre_shared_key_selection_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_sec_protocol_metadata#*QS4_objc(pl)OS_dispatch_data#BFv(#S5_))",
                    "text": "void (^)(NSObject<OS_sec_protocol_metadata> *, NSObject<OS_dispatch_data> *, void (^)(NSObject<OS_dispatch_data> *))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sec_protocol_pre_shared_key_selection_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_t/title",
          "value": "sec_protocol_pre_shared_key_selection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_metadata_t/title",
          "value": "sec_protocol_metadata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_metadata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_metadata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_metadata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_metadata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_complete_t/title",
          "value": "sec_protocol_pre_shared_key_selection_complete_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_complete_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_complete_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1sec_protocol_pre_shared_key_selection_complete_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sec_protocol_pre_shared_key_selection_complete_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sec_protocol_pre_shared_key_selection_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sec_protocol_pre_shared_key_selection_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
