{
  "abstract": [
    {
      "text": "Access control constants that dictate how a keychain item may be used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecAccessControlCreateFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecAccessControlCreateFlags"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecAccessControlCreateFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SecAccessControlCreateFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/restricting-keychain-item-accessibility",
        "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these flags with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateWithFlags(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, or as the value associated with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessControl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in a keychain item’s attribute dictionary, to control keychain item accessibility.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags": {
      "abstract": [
        {
          "text": "Access control constants that dictate how a keychain item may be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "role": "symbol",
      "title": "SecAccessControlCreateFlags",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/and": {
      "abstract": [
        {
          "text": "Indicates that all constraints must be satisfied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "and"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/and",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlAnd"
        }
      ],
      "role": "symbol",
      "title": "and",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/and"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/applicationPassword": {
      "abstract": [
        {
          "text": "Option to use an application-provided password for data encryption key generation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/applicationPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlApplicationPassword"
        }
      ],
      "role": "symbol",
      "title": "applicationPassword",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/applicationpassword"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryAny": {
      "abstract": [
        {
          "text": "Constraint to access an item with Touch ID for any enrolled fingers, or Face ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlBiometryAny"
        }
      ],
      "role": "symbol",
      "title": "biometryAny",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/biometryany"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryCurrentSet": {
      "abstract": [
        {
          "text": "Constraint to access an item with Touch ID for currently enrolled fingers, or from Face ID with the currently enrolled user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryCurrentSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryCurrentSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlBiometryCurrentSet"
        }
      ],
      "role": "symbol",
      "title": "biometryCurrentSet",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/biometrycurrentset"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/companion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "companion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/companion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlCompanion"
        }
      ],
      "role": "symbol",
      "title": "companion",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/companion"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/devicePasscode": {
      "abstract": [
        {
          "text": "Constraint to access an item with a passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePasscode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/devicePasscode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlDevicePasscode"
        }
      ],
      "role": "symbol",
      "title": "devicePasscode",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/devicepasscode"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initialize an access control creation flags object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/or": {
      "abstract": [
        {
          "text": "Indicates that at least one constraint must be satisfied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "or"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/or",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlOr"
        }
      ],
      "role": "symbol",
      "title": "or",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/or"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage": {
      "abstract": [
        {
          "text": "Enable a private key to be used in signing a block of data or verifying a signed block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privateKeyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlPrivateKeyUsage"
        }
      ],
      "role": "symbol",
      "title": "privateKeyUsage",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/privatekeyusage"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDAny": {
      "abstract": [
        {
          "text": "Constraint to access an item with Touch ID for any enrolled fingers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlTouchIDAny"
        }
      ],
      "role": "symbol",
      "title": "touchIDAny",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/touchidany"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDCurrentSet": {
      "abstract": [
        {
          "text": "Constraint to access an item with Touch ID for currently enrolled fingers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDCurrentSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDCurrentSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlTouchIDCurrentSet"
        }
      ],
      "role": "symbol",
      "title": "touchIDCurrentSet",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/touchidcurrentset"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/userPresence": {
      "abstract": [
        {
          "text": "Constraint to access an item with either biometry or passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userPresence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/userPresence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlUserPresence"
        }
      ],
      "role": "symbol",
      "title": "userPresence",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/userpresence"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/watch": {
      "abstract": [
        {
          "text": "Constraint to access an item with a watch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/watch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccessControlWatch"
        }
      ],
      "role": "symbol",
      "title": "watch",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreateflags/watch"
    },
    "doc://com.apple.security/documentation/Security/SecAccessControlCreateWithFlags(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new access control object with the specified protection type and flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateWithFlags"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecAccessControlCreateFlags",
          "text": "SecAccessControlCreateFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAccessControlRef",
          "text": "SecAccessControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccessControlCreateWithFlags(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccessControlCreateWithFlags"
        }
      ],
      "role": "symbol",
      "title": "SecAccessControlCreateWithFlags(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secaccesscontrolcreatewithflags(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccessControl": {
      "abstract": [
        {
          "text": "A key with a value that’s an access control instance indicating access control settings for the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccessControl"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccessControl",
      "type": "topic",
      "url": "/documentation/security/ksecattraccesscontrol"
    },
    "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave": {
      "abstract": [
        {
          "text": "Create an extra layer of security for your private keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/protecting-keys-with-the-secure-enclave",
      "kind": "article",
      "role": "article",
      "title": "Protecting keys with the Secure Enclave",
      "type": "topic",
      "url": "/documentation/security/protecting-keys-with-the-secure-enclave"
    },
    "doc://com.apple.security/documentation/Security/restricting-keychain-item-accessibility": {
      "abstract": [
        {
          "text": "Set the conditions under which an app can access a keychain item such as a password.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/restricting-keychain-item-accessibility",
      "kind": "article",
      "role": "article",
      "title": "Restricting keychain item accessibility",
      "type": "topic",
      "url": "/documentation/security/restricting-keychain-item-accessibility"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags": {
      "abstract": [
        {
          "text": "A bitfield used for passing special allocation and other requests into Core Foundation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFOptionFlags",
      "type": "topic",
      "url": "/documentation/corefoundation/cfoptionflags"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constraints",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/devicePasscode",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryAny",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryCurrentSet",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/userPresence",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/watch"
      ],
      "title": "Constraints"
    },
    {
      "anchor": "Conjunctions",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/and",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/or"
      ],
      "title": "Conjunctions"
    },
    {
      "anchor": "Additional-Options",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/applicationPassword",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage"
      ],
      "title": "Additional Options"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Legacy-Constraints",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDAny",
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDCurrentSet"
      ],
      "title": "Legacy Constraints"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/companion"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecAccessControlCreateFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constraints",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/devicePasscode",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryAny",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/biometryCurrentSet",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/userPresence",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/watch"
              ],
              "title": "Constraints"
            },
            {
              "anchor": "Conjunctions",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/and",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/or"
              ],
              "title": "Conjunctions"
            },
            {
              "anchor": "Additional-Options",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/applicationPassword",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/privateKeyUsage"
              ],
              "title": "Additional Options"
            },
            {
              "anchor": "Legacy-Constraints",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDAny",
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/touchIDCurrentSet"
              ],
              "title": "Legacy Constraints"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAccessControlCreateFlags/companion"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecAccessControlCreateFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFOptionFlags",
                    "text": "CFOptionFlags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1privateKeyUsage/title",
          "value": "kSecAccessControlPrivateKeyUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1privateKeyUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlPrivateKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1companion/title",
          "value": "kSecAccessControlCompanion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1companion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlCompanion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1biometryCurrentSet/title",
          "value": "kSecAccessControlBiometryCurrentSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1biometryCurrentSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlBiometryCurrentSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1watch/title",
          "value": "kSecAccessControlWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1watch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/title",
          "value": "SecAccessControlCreateFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1devicePasscode/title",
          "value": "kSecAccessControlDevicePasscode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1devicePasscode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlDevicePasscode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1touchIDCurrentSet/title",
          "value": "kSecAccessControlTouchIDCurrentSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1touchIDCurrentSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlTouchIDCurrentSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessControl/title",
          "value": "kSecAttrAccessControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccessControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1applicationPassword/title",
          "value": "kSecAccessControlApplicationPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1applicationPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlApplicationPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1and/title",
          "value": "kSecAccessControlAnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1and/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlAnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1userPresence/title",
          "value": "kSecAccessControlUserPresence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1userPresence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlUserPresence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1touchIDAny/title",
          "value": "kSecAccessControlTouchIDAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1touchIDAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlTouchIDAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1biometryAny/title",
          "value": "kSecAccessControlBiometryAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1biometryAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlBiometryAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1or/title",
          "value": "kSecAccessControlOr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateFlags~1or/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccessControlOr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateWithFlags(_:_:_:_:)/title",
          "value": "SecAccessControlCreateWithFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccessControlCreateWithFlags(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessControlCreateWithFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secaccesscontrolcreateflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secaccesscontrolcreateflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
