{
  "abstract": [
    {
      "text": "The authentication type to use for an Internet password.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecAuthenticationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecAuthenticationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecAuthenticationType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecAuthenticationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecAuthenticationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecAuthenticationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType": {
      "abstract": [
        {
          "text": "The authentication type to use for an Internet password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAuthenticationType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAuthenticationType"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/DPA": {
      "abstract": [
        {
          "text": "Specifies Distributed Password authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DPA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/DPA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeDPA"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.DPA",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/dpa"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/MSN": {
      "abstract": [
        {
          "text": "Specifies Microsoft Network default authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/MSN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeMSN"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.MSN",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/msn"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/NTLM": {
      "abstract": [
        {
          "text": "Specifies Windows NT LAN Manager authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NTLM"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/NTLM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeNTLM"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.NTLM",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/ntlm"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/RPA": {
      "abstract": [
        {
          "text": "Specifies Remote Password authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/RPA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeRPA"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.RPA",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/rpa"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/any": {
      "abstract": [
        {
          "text": "Specifies that any authentication type is acceptable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeAny"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.any",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/any"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/default": {
      "abstract": [
        {
          "text": "Specifies the default authentication type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.default",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/default"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/htmlForm": {
      "abstract": [
        {
          "text": "Specifies HTML form based authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "htmlForm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/htmlForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeHTMLForm"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.htmlForm",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/htmlform"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpBasic": {
      "abstract": [
        {
          "text": "Specifies HTTP Basic authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpBasic"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeHTTPBasic"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.httpBasic",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/httpbasic"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpDigest": {
      "abstract": [
        {
          "text": "Specifies HTTP Digest Access authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpDigest"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeHTTPDigest"
        }
      ],
      "role": "symbol",
      "title": "SecAuthenticationType.httpDigest",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/httpdigest"
    },
    "doc://com.apple.security/documentation/Security/SecAuthenticationType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FourCharCode",
          "text": "FourCharCode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAuthenticationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secauthenticationtype/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/NTLM",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/MSN",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/DPA",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/RPA",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpBasic",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpDigest",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/htmlForm",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/default",
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/any"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAuthenticationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/NTLM",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/MSN",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/DPA",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/RPA",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpBasic",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/httpDigest",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/htmlForm",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/default",
                "doc://com.apple.security/documentation/Security/SecAuthenticationType/any"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecAuthenticationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1htmlForm/title",
          "value": "kSecAuthenticationTypeHTMLForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1htmlForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeHTMLForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType/title",
          "value": "SecAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1httpBasic/title",
          "value": "kSecAuthenticationTypeHTTPBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1httpBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeHTTPBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1any/title",
          "value": "kSecAuthenticationTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1httpDigest/title",
          "value": "kSecAuthenticationTypeHTTPDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1httpDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeHTTPDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1default/title",
          "value": "kSecAuthenticationTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1DPA/title",
          "value": "kSecAuthenticationTypeDPA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1DPA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeDPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1NTLM/title",
          "value": "kSecAuthenticationTypeNTLM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1NTLM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeNTLM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1RPA/title",
          "value": "kSecAuthenticationTypeRPA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1RPA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeRPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1MSN/title",
          "value": "kSecAuthenticationTypeMSN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAuthenticationType~1MSN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeMSN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secauthenticationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secauthenticationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
