{
  "abstract": [
    {
      "text": "Returns the application list, description, and CSSM prompt selector for a given access control list entry.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecACLCopyContents(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecACLCopySimpleContents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecACLCopySimpleContents",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecACLCopySimpleContents"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecACLCopySimpleContents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecACLCopySimpleContents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecACLCopySimpleContents"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecACL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecACLRef",
              "text": "SecACLRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "acl"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArrayRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "applicationList"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "description"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_acl_keychain_prompt_selector",
              "text": "CSSM_ACL_KEYCHAIN_PROMPT_SELECTOR"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "promptSelector"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ACL object that identifies the access control list entry from which you want information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "acl"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to an array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecTrustedApplication",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instances identifying applications that are allowed access to the keychain item without user confirmation. If this parameter returns ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", then any application can use this item. If this parameter returns a valid pointer but the array is empty, then there are no trusted applications. In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "applicationList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, the name of the keychain item that appears in the dialog box when the user is prompted for permission to use the item. Note that this name is not necessarily the same as the one displayed for the item by the Keychain Access application. In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "description"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the prompt selector flag for the given access control list entry. If the ",
                  "type": "text"
                },
                {
                  "code": "CSSM_ACL_KEYCHAIN_PROMPT_REQUIRE_PASSPHRASE",
                  "type": "codeVoice"
                },
                {
                  "text": " bit is set, the user is prompted for the keychain password each time a non-trusted application attempts to access this item, even if the keychain is already unlocked.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "promptSelector"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This function is deprecated.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecACLCopyContents(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "An access control list entry applies to a specific use or set of uses for a specific keychain item. The ACL object includes a list of trusted applications (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustedApplicationCreateFromPath(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), the name of the keychain item as it appears in user prompts, the prompt selector flag, and a list of one or more operations to which this ACL object applies. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecACLGetAuthorizations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to get the list of operations for an ACL object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is deprecated in macOS 10.7 and later; use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecACLCopyContents(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecACL": {
      "abstract": [
        {
          "text": "An opaque type that represents information about an ACL entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecACL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecACL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecACL"
        }
      ],
      "role": "symbol",
      "title": "SecACL",
      "type": "topic",
      "url": "/documentation/security/secacl"
    },
    "doc://com.apple.security/documentation/Security/SecACLCopyContents(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the application list, description, and prompt selector for a given ACL entry.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecACLCopyContents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecACLRef",
          "text": "SecACL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainPromptSelector",
          "text": "SecKeychainPromptSelector"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecACLCopyContents(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecACLCopyContents"
        }
      ],
      "role": "symbol",
      "title": "SecACLCopyContents(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secaclcopycontents(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecACLCopySimpleContents": {
      "abstract": [
        {
          "text": "Returns the application list, description, and CSSM prompt selector for a given access control list entry.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecACLCopySimpleContents"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecACLCopySimpleContents",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecACLCopySimpleContents",
      "type": "topic",
      "url": "/documentation/security/secaclcopysimplecontents"
    },
    "doc://com.apple.security/documentation/Security/SecACLGetAuthorizations": {
      "abstract": [
        {
          "text": "Retrieves the CSSM authorization tags of a given access control list entry.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecACLGetAuthorizations"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecACLGetAuthorizations",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecACLGetAuthorizations",
      "type": "topic",
      "url": "/documentation/security/secaclgetauthorizations"
    },
    "doc://com.apple.security/documentation/Security/SecTrustedApplication": {
      "abstract": [
        {
          "text": "An opaque type that contains information about a trusted app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustedApplication"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustedApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustedApplication"
        }
      ],
      "role": "symbol",
      "title": "SecTrustedApplication",
      "type": "topic",
      "url": "/documentation/security/sectrustedapplication"
    },
    "doc://com.apple.security/documentation/Security/SecTrustedApplicationCreateFromPath(_:_:)": {
      "abstract": [
        {
          "text": "Creates a trusted app instance based on the app at the given path in the file system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustedApplicationCreateFromPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustedApplicationRef",
          "text": "SecTrustedApplication"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustedApplicationCreateFromPath(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustedApplicationCreateFromPath"
        }
      ],
      "role": "symbol",
      "title": "SecTrustedApplicationCreateFromPath(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustedapplicationcreatefrompath(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_acl_keychain_prompt_selector"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_acl_keychain_prompt_selector-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_acl_keychain_prompt_selector"
        }
      ],
      "role": "symbol",
      "title": "cssm_acl_keychain_prompt_selector",
      "type": "topic",
      "url": "/documentation/security/cssm_acl_keychain_prompt_selector-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationCreateFromPath(_:_:)/title",
          "value": "SecTrustedApplicationCreateFromPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationCreateFromPath(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustedApplicationCreateFromPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecACLCopyContents(_:_:_:_:)/title",
          "value": "SecACLCopyContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecACLCopyContents(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecACLCopyContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecACL/title",
          "value": "SecACLRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecACL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecACLRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecACL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecACLRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/title",
          "value": "SecTrustedApplicationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustedApplicationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustedApplicationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/title",
          "value": "cssm_acl_keychain_prompt_selector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_acl_keychain_prompt_selector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_acl_keychain_prompt_selector-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_acl_keychain_prompt_selector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secaclcopysimplecontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
