{
  "abstract": [
    {
      "text": "Specify option flags that can be embedded in a code signature during signing and that govern the use of the signature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecCodeSignatureFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCodeSignatureFlags"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecCodeSignatureFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SecCodeSignatureFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCodeSignatureFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some of these flags can be set through the ",
              "type": "text"
            },
            {
              "code": "codesign(1)",
              "type": "codeVoice"
            },
            {
              "text": " command’s ",
              "type": "text"
            },
            {
              "code": "--options",
              "type": "codeVoice"
            },
            {
              "text": " argument and some are set implicitly based on signing circumstances. The flags here appear as the value associated with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the signing information dictionary. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags/considerExpiration": {
      "abstract": [
        {
          "text": "Consider expired certificates invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "considerExpiration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/considerExpiration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSConsiderExpiration"
        }
      ],
      "role": "symbol",
      "title": "considerExpiration",
      "type": "topic",
      "url": "/documentation/security/seccsflags/considerexpiration"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags": {
      "abstract": [
        {
          "text": "Specify option flags that can be embedded in a code signature during signing and that govern the use of the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "role": "symbol",
      "title": "SecCodeSignatureFlags",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/adhoc": {
      "abstract": [
        {
          "text": "Must be used without a signing identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adhoc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/adhoc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureAdhoc"
        }
      ],
      "role": "symbol",
      "title": "adhoc",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/adhoc"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/enforcement": {
      "abstract": [
        {
          "text": "Enforce code signing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enforcement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/enforcement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureEnforcement"
        }
      ],
      "role": "symbol",
      "title": "enforcement",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/enforcement"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceExpiration": {
      "abstract": [
        {
          "text": "Always set the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/considerExpiration",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " flag when validating the code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceExpiration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceExpiration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureForceExpiration"
        }
      ],
      "role": "symbol",
      "title": "forceExpiration",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/forceexpiration"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceHard": {
      "abstract": [
        {
          "text": "Always set the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecCodeStatus/hard",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " status flag on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceHard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceHard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureForceHard"
        }
      ],
      "role": "symbol",
      "title": "forceHard",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/forcehard"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceKill": {
      "abstract": [
        {
          "text": "Always set the termination status flag on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceKill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceKill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureForceKill"
        }
      ],
      "role": "symbol",
      "title": "forceKill",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/forcekill"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/host": {
      "abstract": [
        {
          "text": "May host guest code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "host"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/host",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHost"
        }
      ],
      "role": "symbol",
      "title": "host",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/host"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/libraryValidation": {
      "abstract": [
        {
          "text": "Require library validation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryValidation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/libraryValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureLibraryValidation"
        }
      ],
      "role": "symbol",
      "title": "libraryValidation",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/libraryvalidation"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/linkerSigned": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkerSigned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/linkerSigned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureLinkerSigned"
        }
      ],
      "role": "symbol",
      "title": "linkerSigned",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/linkersigned"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/restrict": {
      "abstract": [
        {
          "text": "Restrict dyld loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/restrict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureRestrict"
        }
      ],
      "role": "symbol",
      "title": "restrict",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/restrict"
    },
    "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/runtime": {
      "abstract": [
        {
          "text": "Apply runtime hardening policies as required by the hardened runtime version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runtime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeSignatureFlags",
          "text": "SecCodeSignatureFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/runtime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureRuntime"
        }
      ],
      "role": "symbol",
      "title": "runtime",
      "type": "topic",
      "url": "/documentation/security/seccodesignatureflags/runtime"
    },
    "doc://com.apple.security/documentation/Security/SecCodeStatus/hard": {
      "abstract": [
        {
          "text": "The code prefers to be denied access to resources if gaining access would invalidate it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCodeStatus",
          "text": "SecCodeStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeStatus/hard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeStatusHard"
        }
      ],
      "role": "symbol",
      "title": "hard",
      "type": "topic",
      "url": "/documentation/security/seccodestatus/hard"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags": {
      "abstract": [
        {
          "text": "A key whose value indicates the static (on-disk) state of the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFlags"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoFlags",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoflags"
    },
    "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys": {
      "abstract": [
        {
          "text": "Use these keys from the information dictionary when you retrieve information from a code signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Signing Information Dictionary Keys",
      "type": "topic",
      "url": "/documentation/security/signing-information-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/host",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/adhoc",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceHard",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceKill",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceExpiration",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/enforcement",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/libraryValidation",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/restrict",
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/runtime"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/linkerSigned"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecCodeSignatureFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeSignatureFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeSignatureFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/host",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/adhoc",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceHard",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceKill",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/forceExpiration",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/enforcement",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/libraryValidation",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/restrict",
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/runtime"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecCodeSignatureFlags/linkerSigned"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCodeSignatureFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1host/title",
          "value": "kSecCodeSignatureHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1host/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1runtime/title",
          "value": "kSecCodeSignatureRuntime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1runtime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureRuntime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeStatus~1hard/title",
          "value": "kSecCodeStatusHard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeStatus~1hard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeStatusHard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceHard/title",
          "value": "kSecCodeSignatureForceHard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceHard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureForceHard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceExpiration/title",
          "value": "kSecCodeSignatureForceExpiration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceExpiration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureForceExpiration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags/title",
          "value": "SecCodeSignatureFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeSignatureFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeSignatureFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1libraryValidation/title",
          "value": "kSecCodeSignatureLibraryValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1libraryValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureLibraryValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1adhoc/title",
          "value": "kSecCodeSignatureAdhoc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1adhoc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureAdhoc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1enforcement/title",
          "value": "kSecCodeSignatureEnforcement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1enforcement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureEnforcement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1restrict/title",
          "value": "kSecCodeSignatureRestrict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1restrict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureRestrict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFlags/title",
          "value": "kSecCodeInfoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags~1considerExpiration/title",
          "value": "kSecCSConsiderExpiration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags~1considerExpiration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSConsiderExpiration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1linkerSigned/title",
          "value": "kSecCodeSignatureLinkerSigned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1linkerSigned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureLinkerSigned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceKill/title",
          "value": "kSecCodeSignatureForceKill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeSignatureFlags~1forceKill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureForceKill"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seccodesignatureflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seccodesignatureflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
