{
  "abstract": [
    {
      "text": "Retrieves the public key from a certificate.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyKey(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecCertificateCopyPublicKey(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecCertificateCopyPublicKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCertificateCopyPublicKey"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecCertificateRef",
        "text": "SecCertificate"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecKeyRef",
        "text": "SecKey"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecCertificateCopyPublicKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.3",
        "name": "iOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.3",
        "name": "iPadOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.2",
        "name": "tvOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "5.0",
        "introducedAt": "3.2",
        "name": "watchOS",
        "renamed": "SecCertificateCopyKey(_:)",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecCertificateCopyPublicKey(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCertificateCopyPublicKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "certificate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecCertificateRef",
              "text": "SecCertificate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyRef",
              "text": "SecKey"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCertificateCopyPublicKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "certificate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecCertificateRef",
              "text": "SecCertificate"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyRef",
              "text": "SecKey"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The certificate object from which to retrieve the public key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "certificate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "In macOS, points to the public key for the specified certificate. In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when you are finished with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS, the certificate’s public key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/examining-a-certificate"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, a result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCertificate": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an X.509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "role": "symbol",
      "title": "SecCertificate",
      "type": "topic",
      "url": "/documentation/security/seccertificate"
    },
    "doc://com.apple.security/documentation/Security/SecCertificateCopyKey(_:)": {
      "abstract": [
        {
          "text": "Retrieves the public key for a given certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificateCopyKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyKey(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificateCopyKey"
        }
      ],
      "role": "symbol",
      "title": "SecCertificateCopyKey(_:)",
      "type": "topic",
      "url": "/documentation/security/seccertificatecopykey(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecCertificateCopyPublicKey(_:)": {
      "abstract": [
        {
          "text": "Retrieves the public key from a certificate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificateCopyPublicKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyPublicKey(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificateCopyPublicKey"
        }
      ],
      "role": "symbol",
      "title": "SecCertificateCopyPublicKey(_:)",
      "type": "topic",
      "url": "/documentation/security/seccertificatecopypublickey(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKey": {
      "abstract": [
        {
          "text": "An object that represents a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "role": "symbol",
      "title": "SecKey",
      "type": "topic",
      "url": "/documentation/security/seckey"
    },
    "doc://com.apple.security/documentation/Security/examining-a-certificate": {
      "abstract": [
        {
          "text": "Learn how to retrieve properties from a certificate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/examining-a-certificate",
      "kind": "article",
      "role": "article",
      "title": "Examining a Certificate",
      "type": "topic",
      "url": "/documentation/security/examining-a-certificate"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "5.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecCertificateCopyPublicKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecKeyRef",
                    "text": "SecKeyRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCertificateCopyPublicKey"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecCertificateRef",
                    "text": "SecCertificateRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "certificate"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCertificateCopyPublicKey"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecCertificateRef",
                    "text": "SecCertificateRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "certificate"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecKeyRef",
                    "text": "SecKeyRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The certificate object from which to retrieve the public key.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "certificate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "In macOS, points to the public key for the specified certificate. In Objective-C, call the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function to release this object when you are finished with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "key"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "In iOS, the certificate’s public key.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyKey(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/title",
          "value": "SecKeyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyKey(_:)/title",
          "value": "SecCertificateCopyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyKey(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/title",
          "value": "SecCertificateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyPublicKey(_:)/title",
          "value": "SecCertificateCopyPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyPublicKey(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyPublicKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seccertificatecopypublickey(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seccertificatecopypublickey(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
