{
  "abstract": [
    {
      "text": "Returns a copy of the long description of a certificate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecCertificateCopyLongDescription(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecCertificateCopyLongDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCertificateCopyLongDescription"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecCertificateRef",
        "text": "SecCertificate"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFErrorRef",
        "text": "CFError"
      },
      {
        "kind": "text",
        "text": ">?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecCertificateCopyLongDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecCertificateCopyLongDescription(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCertificateCopyLongDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "alloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "certificate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecCertificateRef",
              "text": "SecCertificate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFErrorRef",
              "text": "CFError"
            },
            {
              "kind": "text",
              "text": ">?>?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator that should be used. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to use the default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "alloc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The certificate from which the long description should be copied.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "certificate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " variable where an error object is stored upon failure. If not ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the caller is responsible for checking this variable and releasing the resulting object if it exists.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A string object containing the long description, or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if an error occurred. In Objective-C, free this object with a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function when you are done with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The format of this string is not guaranteed to be consistent across different operating systems or versions. Do not attempt to parse it programmatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
      "kind": "article",
      "role": "article",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror-ru8"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault": {
      "abstract": [
        {
          "text": "This is a synonym for `NULL`. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFAllocatorDefault"
        },
        {
          "kind": "text",
          "text": ": CFAllocator!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFAllocatorDefault",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfallocatordefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCertificate": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an X.509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificate"
        }
      ],
      "role": "symbol",
      "title": "SecCertificate",
      "type": "topic",
      "url": "/documentation/security/seccertificate"
    },
    "doc://com.apple.security/documentation/Security/SecCertificateCopyLongDescription(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of the long description of a certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCertificateCopyLongDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCertificateCopyLongDescription(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCertificateCopyLongDescription"
        }
      ],
      "role": "symbol",
      "title": "SecCertificateCopyLongDescription(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccertificatecopylongdescription(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFErrorRef": {
      "abstract": [
        {
          "text": "A reference to a CFError object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecCertificateCopyLongDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyLongDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCertificateCopyLongDescription"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alloc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecCertificate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecCertificateRef",
                    "text": "SecCertificateRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "certificate"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFErrorRef",
                    "text": "CFErrorRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator that should be used. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to use the default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "alloc"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The certificate from which the long description should be copied.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "certificate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " variable where an error object is stored upon failure. If not ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the caller is responsible for checking this variable and releasing the resulting object if it exists.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A string object containing the long description, or ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if an error occurred. In Objective-C, free this object with a call to the ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " function when you are done with it.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyLongDescription(_:_:_:)/title",
          "value": "SecCertificateCopyLongDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificateCopyLongDescription(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateCopyLongDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/title",
          "value": "SecCertificateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCertificate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCertificateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title",
          "value": "CFErrorRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seccertificatecopylongdescription(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seccertificatecopylongdescription(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
