{
  "abstract": [
    {
      "text": "Asks the kernel to accept the signing information currently attached to a code object and uses it to validate memory page-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecCodeMapMemory(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecCodeMapMemory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCodeMapMemory"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecStaticCodeRef",
        "text": "SecStaticCode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SecCSFlags",
        "text": "SecCSFlags"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecCodeMapMemory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecCodeMapMemory(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCodeMapMemory"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "code"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecStaticCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecStaticCodeRef",
              "text": "SecStaticCode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecCSFlags",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A code or static code object representing the signed code whose main executable should be subject to page-in validation. If you provide a code object, the function processes it in the same manner as the  ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function—that is, whether you provide a code object or a static code object, the function actually takes the signature from the code on disk.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "code"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Optional flags; see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values. Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for standard behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/code-signing-services-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is for the use of code hosts that use memory mapping to manage their own code. The kernel takes the signing information attached to the code on disk specified by the ",
              "type": "text"
            },
            {
              "code": "code",
              "type": "codeVoice"
            },
            {
              "text": " parameter and attaches it to the memory object. After that, it uses the signature to validate memory page-ins, updating the dynamic validity status accordingly. You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to check the code’s dynamic validity status. The attachment of the signature to the memory object affects all processes that have the main executable of this code mapped.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the ",
          "type": "text"
        },
        {
          "code": "flags",
          "type": "codeVoice"
        },
        {
          "text": " parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags": {
      "abstract": [
        {
          "text": "No flags (use the default behavior).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecCSDefaultFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecCSDefaultFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags/kseccsdefaultflags"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves various pieces of information from a code signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopySigningInformation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopysigninginformation(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a static code object representing the on-disk version of the given running code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopyStaticCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopyStaticCode"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopyStaticCode(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopystaticcode(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecCodeMapMemory(_:_:)": {
      "abstract": [
        {
          "text": "Asks the kernel to accept the signing information currently attached to a code object and uses it to validate memory page-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeMapMemory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeMapMemory(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeMapMemory"
        }
      ],
      "role": "symbol",
      "title": "SecCodeMapMemory(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodemapmemory(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecStaticCode": {
      "abstract": [
        {
          "text": "A static code object representing signed code on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCode"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecStaticCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecStaticCode"
        }
      ],
      "role": "symbol",
      "title": "SecStaticCode",
      "type": "topic",
      "url": "/documentation/security/secstaticcode"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the code signing services API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services Result Codes",
      "type": "topic",
      "url": "/documentation/security/code-signing-services-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecCodeMapMemory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeMapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCodeMapMemory"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecStaticCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecStaticCodeRef",
                    "text": "SecStaticCodeRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "code"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SecCSFlags",
                    "text": "SecCSFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A code or static code object representing the signed code whose main executable should be subject to page-in validation. If you provide a code object, the function processes it in the same manner as the  ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopyStaticCode(_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function—that is, whether you provide a code object or a static code object, the function actually takes the signature from the code on disk.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "code"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Optional flags; see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for possible values. Pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for standard behavior.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/code-signing-services-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyStaticCode(_:_:_:)/title",
          "value": "SecCodeCopyStaticCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopyStaticCode(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopyStaticCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeMapMemory(_:_:)/title",
          "value": "SecCodeMapMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeMapMemory(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeMapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/title",
          "value": "SecCodeCopySigningInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopySigningInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/title",
          "value": "SecCSFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCode/title",
          "value": "SecStaticCodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecStaticCodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecStaticCodeRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seccodemapmemory(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seccodemapmemory(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
