{
  "abstract": [
    {
      "text": "The list of digest algorithms available for code signatures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecCSDigestAlgorithm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCSDigestAlgorithm"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecCSDigestAlgorithm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecCSDigestAlgorithm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCSDigestAlgorithm"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these values with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm": {
      "abstract": [
        {
          "text": "The list of digest algorithms available for code signatures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSDigestAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCSDigestAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureHashSHA1"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHashSHA1"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureHashSHA1",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturehashsha1"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureHashSHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHashSHA256"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureHashSHA256",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturehashsha256"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256Truncated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureHashSHA256Truncated"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256Truncated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHashSHA256Truncated"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureHashSHA256Truncated",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturehashsha256truncated"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureHashSHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHashSHA384"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureHashSHA384",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturehashsha384"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA512": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureHashSHA512"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureHashSHA512"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureHashSHA512",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturehashsha512"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureNoHash": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureNoHash"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureNoHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeSignatureNoHash"
        }
      ],
      "role": "symbol",
      "title": "SecCSDigestAlgorithm.codeSignatureNoHash",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/codesignaturenohash"
    },
    "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/seccsdigestalgorithm/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm": {
      "abstract": [
        {
          "text": "A key whose value is a number indicating the cryptographic hash function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDigestAlgorithm",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodigestalgorithm"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms": {
      "abstract": [
        {
          "text": "A key whose value is a list of the kinds of cryptographic hash functions available within the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithms"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDigestAlgorithms",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodigestalgorithms"
    },
    "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys": {
      "abstract": [
        {
          "text": "Use these keys from the information dictionary when you retrieve information from a code signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Signing Information Dictionary Keys",
      "type": "topic",
      "url": "/documentation/security/signing-information-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA1",
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256",
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256Truncated",
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA384",
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA512",
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureNoHash"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecCSDigestAlgorithm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA1",
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256",
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA256Truncated",
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA384",
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureHashSHA512",
                "doc://com.apple.security/documentation/Security/SecCSDigestAlgorithm/codeSignatureNoHash"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecCSDigestAlgorithm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithm/title",
          "value": "kSecCodeInfoDigestAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithms/title",
          "value": "kSecCodeInfoDigestAlgorithms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDigestAlgorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA512/title",
          "value": "kSecCodeSignatureHashSHA512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHashSHA512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA256Truncated/title",
          "value": "kSecCodeSignatureHashSHA256Truncated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA256Truncated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHashSHA256Truncated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA256/title",
          "value": "kSecCodeSignatureHashSHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHashSHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA384/title",
          "value": "kSecCodeSignatureHashSHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHashSHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureNoHash/title",
          "value": "kSecCodeSignatureNoHash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureNoHash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureNoHash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm/title",
          "value": "SecCSDigestAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA1/title",
          "value": "kSecCodeSignatureHashSHA1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSDigestAlgorithm~1codeSignatureHashSHA1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeSignatureHashSHA1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seccsdigestalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seccsdigestalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
