{
  "abstract": [
    {
      "text": "The external format of a keychain item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecExternalFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecExternalFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecExternalFormat"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecExternalFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecExternalFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat": {
      "abstract": [
        {
          "text": "The external format of a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat",
      "type": "topic",
      "url": "/documentation/security/secexternalformat"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatBSAFE": {
      "abstract": [
        {
          "text": "Format for asymmetric keys. BSAFE is a standard from RSA Security for encryption, digital signatures, and privacy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatBSAFE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatBSAFE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatBSAFE"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatBSAFE",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatbsafe"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatNetscapeCertSequence": {
      "abstract": [
        {
          "text": "Set of certificates in the Netscape Certificate Sequence format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatNetscapeCertSequence"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatNetscapeCertSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatNetscapeCertSequence"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatNetscapeCertSequence",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatnetscapecertsequence"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatOpenSSL": {
      "abstract": [
        {
          "text": "Format for asymmetric (public/private) keys. OpenSSL is an open source toolkit for Secure Sockets Layer (SSL) and Transport Layer Security (TLS). Also known as X.509 for public keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatOpenSSL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatOpenSSL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatOpenSSL"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatOpenSSL",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatopenssl"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence": {
      "abstract": [
        {
          "text": "Sequence of certificates and keys with PEM armor. PEM armor refers to a way of expressing binary data as an ASCII string so that it can be transferred over text-only channels such as email. This is the default format for multiple items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPEMSequence"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPEMSequence"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPEMSequence",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpemsequence"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12": {
      "abstract": [
        {
          "text": "Set of certificates and private keys. PKCS12 is the Personal Information Exchange Syntax from RSA Security, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPKCS12"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPKCS12"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPKCS12",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpkcs12"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7": {
      "abstract": [
        {
          "text": "Sequence of certificates, no PEM armor. PKCS7 is the Cryptographic Message Syntax Standard from RSA Security, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatPKCS7"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatPKCS7"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatPKCS7",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatpkcs7"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatRawKey": {
      "abstract": [
        {
          "text": "Format for symmetric keys. Raw, unformatted key bits. This is the default for symmetric keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatRawKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatRawKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatRawKey"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatRawKey",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatrawkey"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSH": {
      "abstract": [
        {
          "text": "OpenSSH 1 format for asymmetric (public/private) keys. OpenSSH is an OpenBSD implementation of the Secure Shell (SSH) protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatSSH"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatSSH"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatSSH",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatssh"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSHv2": {
      "abstract": [
        {
          "text": "OpenSSH 2 format for public keys. OpenSSH version 2 private keys are in format ",
          "type": "text"
        },
        {
          "code": "kSecFormatOpenSSL",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "kSecFormatWrappedOpenSSL",
          "type": "codeVoice"
        },
        {
          "text": ". OpenSSH is an OpenBSD implementation of the Secure Shell (SSH) protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatSSHv2"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSHv2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatSSHv2"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatSSHv2",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatsshv2"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatUnknown"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatUnknown"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatUnknown",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatunknown"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedLSH": {
      "abstract": [
        {
          "text": "Not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatWrappedLSH"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedLSH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatWrappedLSH"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatWrappedLSH",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatwrappedlsh"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedOpenSSL": {
      "abstract": [
        {
          "text": "Format for wrapped symmetric and private keys. OpenSSL is an open-source toolkit for Secure Sockets Layer (SSL) and Transport Layer Security (TLS).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatWrappedOpenSSL"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedOpenSSL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatWrappedOpenSSL"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatWrappedOpenSSL",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatwrappedopenssl"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedPKCS8": {
      "abstract": [
        {
          "text": "Format for wrapped symmetric and private keys. PKCS8 is the Private-Key Information Syntax Standard from RSA Security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatWrappedPKCS8"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedPKCS8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatWrappedPKCS8"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatWrappedPKCS8",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatwrappedpkcs8"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedSSH": {
      "abstract": [
        {
          "text": "OpenSSH 1 format for wrapped symmetric and private keys.  OpenSSH is an OpenBSD implementation of the Secure Shell (SSH) protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatWrappedSSH"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedSSH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatWrappedSSH"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatWrappedSSH",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatwrappedssh"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/formatX509Cert": {
      "abstract": [
        {
          "text": "Format for certificates. DER (distinguished encoding rules) encoded. X.509 is a standard for digital certificates from the International Telecommunication Union (ITU). This is the default for certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatX509Cert"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/formatX509Cert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecFormatX509Cert"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat.formatX509Cert",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/formatx509cert"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secexternalformat/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatUnknown",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatOpenSSL",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSH",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatBSAFE",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSHv2",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatRawKey",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedPKCS8",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedOpenSSL",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedSSH",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedLSH",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatX509Cert",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12",
        "doc://com.apple.security/documentation/Security/SecExternalFormat/formatNetscapeCertSequence"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecExternalFormat/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecExternalFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatUnknown",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatOpenSSL",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSH",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatBSAFE",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatSSHv2",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatRawKey",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedPKCS8",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedOpenSSL",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedSSH",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatWrappedLSH",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatX509Cert",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPEMSequence",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS7",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatPKCS12",
                "doc://com.apple.security/documentation/Security/SecExternalFormat/formatNetscapeCertSequence"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecExternalFormat"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/title",
          "value": "SecExternalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatOpenSSL/title",
          "value": "kSecFormatOpenSSL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatOpenSSL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatOpenSSL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedOpenSSL/title",
          "value": "kSecFormatWrappedOpenSSL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedOpenSSL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatWrappedOpenSSL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatSSH/title",
          "value": "kSecFormatSSH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatSSH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatSSH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedLSH/title",
          "value": "kSecFormatWrappedLSH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedLSH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatWrappedLSH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatNetscapeCertSequence/title",
          "value": "kSecFormatNetscapeCertSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatNetscapeCertSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatNetscapeCertSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatSSHv2/title",
          "value": "kSecFormatSSHv2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatSSHv2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatSSHv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatUnknown/title",
          "value": "kSecFormatUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatX509Cert/title",
          "value": "kSecFormatX509Cert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatX509Cert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatX509Cert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatRawKey/title",
          "value": "kSecFormatRawKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatRawKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatRawKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatBSAFE/title",
          "value": "kSecFormatBSAFE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatBSAFE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatBSAFE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedPKCS8/title",
          "value": "kSecFormatWrappedPKCS8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedPKCS8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatWrappedPKCS8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedSSH/title",
          "value": "kSecFormatWrappedSSH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatWrappedSSH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatWrappedSSH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS12/title",
          "value": "kSecFormatPKCS12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPKCS12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPEMSequence/title",
          "value": "kSecFormatPEMSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPEMSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPEMSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS7/title",
          "value": "kSecFormatPKCS7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat~1formatPKCS7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecFormatPKCS7"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secexternalformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secexternalformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
