{
  "abstract": [
    {
      "text": "Removes a guest from a host.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecHostRemoveGuest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecHostRemoveGuest",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecHostRemoveGuest"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecHostRemoveGuest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecHostRemoveGuest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecHostRemoveGuest"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecGuestRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecGuestRef",
              "text": "SecGuestRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "host"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecGuestRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecGuestRef",
              "text": "SecGuestRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "guest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecCSFlags",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The guest code object of the host of the guest. You cannot specify a host of a host here except in the case of a dedicated host. For a dedicated host, the dedicated host is automatically substituted for its guest. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecCSDedicatedHost",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a discussion of dedicated hosts.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "host"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The guest code object for the guest whose guest relationship you wish to terminate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "guest"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Optional flags; see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values. Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for standard behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/code-signing-services-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function removes all memory of the guest-host relationship from the Code Signing Services hosting system. You cannot remove a dedicated guest. The specified guest must have been created using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecHostCreateGuest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. If you remove a guest that is also a host, all of the guest’s guests are removed, recursively, as well, even if one or more of those guests are dedicated hosts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the ",
          "type": "text"
        },
        {
          "code": "flags",
          "type": "codeVoice"
        },
        {
          "text": " parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags": {
      "abstract": [
        {
          "text": "No flags (use the default behavior).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecCSDefaultFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags/kSecCSDefaultFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecCSDefaultFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags/kseccsdefaultflags"
    },
    "doc://com.apple.security/documentation/Security/SecGuestRef": {
      "abstract": [
        {
          "text": "A reference to a guest object, which identifies a particular block of guest code in the context of its code signing host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecGuestRef"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecGuestRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecGuestRef"
        }
      ],
      "role": "symbol",
      "title": "SecGuestRef",
      "type": "topic",
      "url": "/documentation/security/secguestref"
    },
    "doc://com.apple.security/documentation/Security/SecHostCreateGuest": {
      "abstract": [
        {
          "text": "Creates a new guest and describes its initial properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecHostCreateGuest"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecHostCreateGuest",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecHostCreateGuest",
      "type": "topic",
      "url": "/documentation/security/sechostcreateguest"
    },
    "doc://com.apple.security/documentation/Security/SecHostRemoveGuest": {
      "abstract": [
        {
          "text": "Removes a guest from a host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecHostRemoveGuest"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecHostRemoveGuest",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecHostRemoveGuest",
      "type": "topic",
      "url": "/documentation/security/sechostremoveguest"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the code signing services API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services Result Codes",
      "type": "topic",
      "url": "/documentation/security/code-signing-services-result-codes"
    },
    "doc://com.apple.security/documentation/Security/kSecCSDedicatedHost": {
      "abstract": [
        {
          "text": "Declares dedicated hosting for the given host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSDedicatedHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSDedicatedHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSDedicatedHost"
        }
      ],
      "role": "symbol",
      "title": "kSecCSDedicatedHost",
      "type": "topic",
      "url": "/documentation/security/kseccsdedicatedhost"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecHostCreateGuest"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGuestRef/title",
          "value": "SecGuestRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGuestRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecGuestRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGuestRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecGuestRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDedicatedHost/title",
          "value": "kSecCSDedicatedHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDedicatedHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSDedicatedHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/title",
          "value": "SecCSFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sechostremoveguest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
