{
  "abstract": [
    {
      "text": "Adds one or more items to a keychain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecItemAdd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecItemAdd"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeRef",
        "text": "CFTypeRef"
      },
      {
        "kind": "text",
        "text": "?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecItemAdd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecItemAdd(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": "?>?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that describes the item to add. A typical ",
                  "type": "text"
                },
                {
                  "code": "attributes",
                  "type": "codeVoice"
                },
                {
                  "text": " dictionary consists of:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "inlineContent": [
                            {
                              "text": "The item’s class.",
                              "type": "text"
                            }
                          ],
                          "type": "strong"
                        },
                        {
                          "text": " Different attributes and behaviors apply to different classes of items. You use the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " key with a suitable value to tell keychain services whether the data you want to store represents a password, a certificate, a cryptographic key, or something else. See ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "inlineContent": [
                            {
                              "text": "The data.",
                              "type": "text"
                            }
                          ],
                          "type": "strong"
                        },
                        {
                          "text": " Use the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecValueData",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " key to indicate the data you want to store. Keychain services takes care of encrypting this data if the item is secret, namely when it’s one of the password types or involves a private key.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "inlineContent": [
                            {
                              "text": "Optional attributes.",
                              "type": "text"
                            }
                          ],
                          "type": "strong"
                        },
                        {
                          "text": " Include attribute keys that help you find the item later, indicate how your app uses the data, and how the system shares the data. You can add any number of attributes, although many are specific to a particular class of item. For the attributes applicable to the keychain item you add, see the entry for the item’s class in ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values#Item-class-values",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "inlineContent": [
                            {
                              "text": "Optional return types.",
                              "type": "text"
                            }
                          ],
                          "type": "strong"
                        },
                        {
                          "text": " Include return type keys to indicate what data, if any, you want returned upon successful completion. You often ignore the return data from a ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " call, in which case you don’t need to include any return result key. See ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for more information.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "attributes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, a reference to the newly added items. The exact type of the result is based on the values supplied in ",
                  "type": "text"
                },
                {
                  "code": "attributes",
                  "type": "codeVoice"
                },
                {
                  "text": ", as discussed in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if you don’t need the result. Otherwise, your app becomes responsible for releasing the referenced object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "result"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain",
        "doc://com.apple.security/documentation/Security/updating-and-deleting-keychain-items",
        "doc://com.apple.security/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps",
        "doc://com.apple.security/documentation/Security/storing-keys-in-the-keychain",
        "doc://com.apple.security/documentation/Security/storing-a-certificate-in-the-keychain"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add multiple items to a keychain at once use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecUseItemList",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the ",
              "type": "text"
            },
            {
              "code": "attributes",
              "type": "codeVoice"
            },
            {
              "text": " dictionary with an array of dictionaries (each corresponding to one of the items) as its value. This is only supported for non-password items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you use Xcode to create an application, Xcode adds an ",
              "type": "text"
            },
            {
              "code": "application-identifier",
              "type": "codeVoice"
            },
            {
              "text": " entitlement to the application bundle. Keychain Services uses this entitlement to grant the application access to its own keychain items. To share the new keychain item to among multiple apps, include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the ",
              "type": "text"
            },
            {
              "code": "attributes",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. The value of this key must be the name of a keychain access group to which all the programs that share this item belong.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Performance-considerations",
          "level": 3,
          "text": "Performance considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "SecItemAdd",
              "type": "codeVoice"
            },
            {
              "text": " blocks the calling thread, so it can cause your app’s UI to hang if called from the main thread. Instead, call ",
              "type": "text"
            },
            {
              "code": "SecItemAdd",
              "type": "codeVoice"
            },
            {
              "text": " from a background dispatch queue or ",
              "type": "text"
            },
            {
              "code": "async",
              "type": "codeVoice"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func addKeychainItem(attributes attrs: CFDictionary, _ completion: @escaping (OSStatus, CFTypeRef?) -> Void) {",
                    "    queue.async {",
                    "        var item: CFTypeRef?",
                    "        let result = SecItemAdd(attrs, &item)",
                    "        completion(result, item)",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)addKeychainItemWithAttributes:(CFDictionaryRef)attrs completion:(void(^)(OSStatus status, CFTypeRef item))completion {",
                    "    dispatch_async(backgroundQueue, ^{",
                    "        CFTypeRef item = NULL;",
                    "        OSStatus addResult = SecItemAdd(attrs, &item);",
                    "        completion(addResult, item);",
                    "        if (item) {",
                    "            CFRelease(item);",
                    "        }",
                    "    });",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        }
      ],
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemadd(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain": {
      "abstract": [
        {
          "text": "Add network credentials to the keychain on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/adding-a-password-to-the-keychain",
      "kind": "article",
      "role": "article",
      "title": "Adding a password to the keychain",
      "type": "topic",
      "url": "/documentation/security/adding-a-password-to-the-keychain"
    },
    "doc://com.apple.security/documentation/Security/item-class-keys-and-values": {
      "abstract": [
        {
          "text": "Specify the class of a keychain item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Item class keys and values",
      "type": "topic",
      "url": "/documentation/security/item-class-keys-and-values"
    },
    "doc://com.apple.security/documentation/Security/item-class-keys-and-values#Item-class-values": {
      "abstract": [],
      "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values#Item-class-values",
      "kind": "section",
      "title": "Item class values",
      "type": "topic",
      "url": "/documentation/security/item-class-keys-and-values#Item-class-values"
    },
    "doc://com.apple.security/documentation/Security/item-return-result-keys": {
      "abstract": [
        {
          "text": "Specify how you want returned keychain item data formatted.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Item return result keys",
      "type": "topic",
      "url": "/documentation/security/item-return-result-keys"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the access group the item is in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccessGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccessGroup"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccessGroup",
      "type": "topic",
      "url": "/documentation/security/ksecattraccessgroup"
    },
    "doc://com.apple.security/documentation/Security/kSecClass": {
      "abstract": [
        {
          "text": "A dictionary key whose value is the item’s class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecClass"
        }
      ],
      "role": "symbol",
      "title": "kSecClass",
      "type": "topic",
      "url": "/documentation/security/ksecclass"
    },
    "doc://com.apple.security/documentation/Security/kSecUseItemList": {
      "abstract": [
        {
          "text": "A key whose value is an array of items to search.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecUseItemList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecUseItemList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecUseItemList"
        }
      ],
      "role": "symbol",
      "title": "kSecUseItemList",
      "type": "topic",
      "url": "/documentation/security/ksecuseitemlist"
    },
    "doc://com.apple.security/documentation/Security/kSecValueData": {
      "abstract": [
        {
          "text": "A key whose value is the item’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecValueData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecValueData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecValueData"
        }
      ],
      "role": "symbol",
      "title": "kSecValueData",
      "type": "topic",
      "url": "/documentation/security/ksecvaluedata"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.apple.security/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps": {
      "abstract": [
        {
          "text": "Enable apps to share keychain items with each other by adding the apps to an access group.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps",
      "kind": "article",
      "role": "article",
      "title": "Sharing access to keychain items among a collection of apps",
      "type": "topic",
      "url": "/documentation/security/sharing-access-to-keychain-items-among-a-collection-of-apps"
    },
    "doc://com.apple.security/documentation/Security/storing-a-certificate-in-the-keychain": {
      "abstract": [
        {
          "text": "Store a certificate in the keychain for safekeeping.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/storing-a-certificate-in-the-keychain",
      "kind": "article",
      "role": "article",
      "title": "Storing a Certificate in the Keychain",
      "type": "topic",
      "url": "/documentation/security/storing-a-certificate-in-the-keychain"
    },
    "doc://com.apple.security/documentation/Security/storing-keys-in-the-keychain": {
      "abstract": [
        {
          "text": "Store and access cryptographic keys in the keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/storing-keys-in-the-keychain",
      "kind": "article",
      "role": "article",
      "title": "Storing Keys in the Keychain",
      "type": "topic",
      "url": "/documentation/security/storing-keys-in-the-keychain"
    },
    "doc://com.apple.security/documentation/Security/updating-and-deleting-keychain-items": {
      "abstract": [
        {
          "text": "Modify items in the keychain when the user’s data changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/updating-and-deleting-keychain-items",
      "kind": "article",
      "role": "article",
      "title": "Updating and deleting keychain items",
      "type": "topic",
      "url": "/documentation/security/updating-and-deleting-keychain-items"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecItemAdd"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attributes"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeRef",
                    "text": "CFTypeRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that describes the item to add. A typical ",
                        "type": "text"
                      },
                      {
                        "code": "attributes",
                        "type": "codeVoice"
                      },
                      {
                        "text": " dictionary consists of:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "inlineContent": [
                                  {
                                    "text": "The item’s class.",
                                    "type": "text"
                                  }
                                ],
                                "type": "strong"
                              },
                              {
                                "text": " Different attributes and behaviors apply to different classes of items. You use the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecClass",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " key with a suitable value to tell keychain services whether the data you want to store represents a password, a certificate, a cryptographic key, or something else. See ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "inlineContent": [
                                  {
                                    "text": "The data.",
                                    "type": "text"
                                  }
                                ],
                                "type": "strong"
                              },
                              {
                                "text": " Use the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecValueData",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " key to indicate the data you want to store. Keychain services takes care of encrypting this data if the item is secret, namely when it’s one of the password types or involves a private key.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "inlineContent": [
                                  {
                                    "text": "Optional attributes.",
                                    "type": "text"
                                  }
                                ],
                                "type": "strong"
                              },
                              {
                                "text": " Include attribute keys that help you find the item later, indicate how your app uses the data, and how the system shares the data. You can add any number of attributes, although many are specific to a particular class of item. For the attributes applicable to the keychain item you add, see the entry for the item’s class in ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/item-class-keys-and-values#Item-class-values",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "inlineContent": [
                                  {
                                    "text": "Optional return types.",
                                    "type": "text"
                                  }
                                ],
                                "type": "strong"
                              },
                              {
                                "text": " Include return type keys to indicate what data, if any, you want returned upon successful completion. You often ignore the return data from a ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/SecItemAdd(_:_:)",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " call, in which case you don’t need to include any return result key. See ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for more information.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "attributes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, a reference to the newly added items. The exact type of the result is based on the values supplied in ",
                        "type": "text"
                      },
                      {
                        "code": "attributes",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", as discussed in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/item-return-result-keys",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you don’t need the result. Otherwise, your app becomes responsible for releasing the referenced object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "result"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClass/title",
          "value": "kSecClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueData/title",
          "value": "kSecValueData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecValueData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecValueData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseItemList/title",
          "value": "kSecUseItemList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseItemList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecUseItemList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessGroup/title",
          "value": "kSecAttrAccessGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccessGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccessGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secitemadd(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secitemadd(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
