{
  "abstract": [
    {
      "text": "Specifies a keychain item’s attributes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecItemAttr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecItemAttr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecItemAttr"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecItemAttr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecItemAttr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Not all of these attributes are used for all types of items. Which set of attributes exist for each type of item is documented in the “Data Storage Library Services” chapter of ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Common Security: CDSA and CSSM, version 2 (with corrigenda)",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " from The Open Group (",
              "type": "text"
            },
            {
              "identifier": "http://www.opengroup.org/security/cdsa.htm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") for standard items and in the DL section of the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Security Release Notes",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " for Apple-defined item types (if any).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To obtain information about a certificate, use the CDSA Certificate Library (CL) API. To obtain information about a key, use the ",
              "type": "text"
            },
            {
              "code": "SecKeyGetCSSMKey",
              "type": "codeVoice"
            },
            {
              "text": " function and the CDSA Cryptographic Service Provider (CSP) API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For attributes for keys, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/keychain-item-attribute-constants-for-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr": {
      "abstract": [
        {
          "text": "Specifies a keychain item’s attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/accountItemAttr": {
      "abstract": [
        {
          "text": "Identifies the account attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/accountItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAccountItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.accountItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/accountitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/addressItemAttr": {
      "abstract": [
        {
          "text": "Identifies the address attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/addressItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAddressItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.addressItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/addressitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/alias": {
      "abstract": [
        {
          "text": "Indicates an alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alias"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/alias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAlias"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.alias",
      "type": "topic",
      "url": "/documentation/security/secitemattr/alias"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/authenticationTypeItemAttr": {
      "abstract": [
        {
          "text": "Identifies the authentication type attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationTypeItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/authenticationTypeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAuthenticationTypeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.authenticationTypeItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/authenticationtypeitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/certificateEncoding": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "CSSM_CERT_ENCODING",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificateEncoding"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/certificateEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCertificateEncoding"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.certificateEncoding",
      "type": "topic",
      "url": "/documentation/security/secitemattr/certificateencoding"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/certificateType": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "CSSM_CERT_TYPE",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificateType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/certificateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCertificateType"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.certificateType",
      "type": "topic",
      "url": "/documentation/security/secitemattr/certificatetype"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/commentItemAttr": {
      "abstract": [
        {
          "text": "Identifies the comment attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commentItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/commentItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCommentItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.commentItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/commentitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/creationDateItemAttr": {
      "abstract": [
        {
          "text": "Identifies the creation date attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDateItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/creationDateItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCreationDateItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.creationDateItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/creationdateitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/creatorItemAttr": {
      "abstract": [
        {
          "text": "Identifies the creator attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creatorItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/creatorItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCreatorItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.creatorItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/creatoritemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/crlEncoding": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "CSSM_CRL_ENCODING",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crlEncoding"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/crlEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCrlEncoding"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.crlEncoding",
      "type": "topic",
      "url": "/documentation/security/secitemattr/crlencoding"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/crlType": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "CSSM_CRL_TYPE",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crlType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/crlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCrlType"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.crlType",
      "type": "topic",
      "url": "/documentation/security/secitemattr/crltype"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/customIconItemAttr": {
      "abstract": [
        {
          "text": "Identifies the custom icon attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customIconItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/customIconItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCustomIconItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.customIconItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/customiconitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/descriptionItemAttr": {
      "abstract": [
        {
          "text": "Identifies the description attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/descriptionItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDescriptionItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.descriptionItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/descriptionitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/genericItemAttr": {
      "abstract": [
        {
          "text": "Identifies the generic attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/genericItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGenericItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.genericItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/genericitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FourCharCode",
          "text": "FourCharCode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secitemattr/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/invisibleItemAttr": {
      "abstract": [
        {
          "text": "Identifies the invisible attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invisibleItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/invisibleItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecInvisibleItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.invisibleItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/invisibleitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/labelItemAttr": {
      "abstract": [
        {
          "text": "Identifies the label attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labelItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/labelItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecLabelItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.labelItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/labelitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/modDateItemAttr": {
      "abstract": [
        {
          "text": "Identifies the modification date attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modDateItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/modDateItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecModDateItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.modDateItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/moddateitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/negativeItemAttr": {
      "abstract": [
        {
          "text": "Identifies the negative attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negativeItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/negativeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecNegativeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.negativeItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/negativeitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/pathItemAttr": {
      "abstract": [
        {
          "text": "Identifies the path attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/pathItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPathItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.pathItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/pathitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/portItemAttr": {
      "abstract": [
        {
          "text": "Identifies the port attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/portItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPortItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.portItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/portitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/protocolItemAttr": {
      "abstract": [
        {
          "text": "Identifies the protocol attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "protocolItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/protocolItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.protocolItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/protocolitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/scriptCodeItemAttr": {
      "abstract": [
        {
          "text": "Identifies the script code attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scriptCodeItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/scriptCodeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecScriptCodeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.scriptCodeItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/scriptcodeitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/securityDomainItemAttr": {
      "abstract": [
        {
          "text": "Identifies the security domain attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityDomainItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/securityDomainItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSecurityDomainItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.securityDomainItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/securitydomainitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/serverItemAttr": {
      "abstract": [
        {
          "text": "Identifies the server attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/serverItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecServerItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.serverItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/serveritemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/serviceItemAttr": {
      "abstract": [
        {
          "text": "Identifies the service attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/serviceItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecServiceItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.serviceItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/serviceitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/signatureItemAttr": {
      "abstract": [
        {
          "text": "Identifies the server signature attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/signatureItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSignatureItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.signatureItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/signatureitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/typeItemAttr": {
      "abstract": [
        {
          "text": "Identifies the type attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/typeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTypeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.typeItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/typeitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr/volumeItemAttr": {
      "abstract": [
        {
          "text": "Identifies the volume attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volumeItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr/volumeItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecVolumeItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr.volumeItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr/volumeitemattr"
    },
    "doc://com.apple.security/documentation/Security/keychain-item-attribute-constants-for-keys": {
      "abstract": [
        {
          "text": "Specifies the attributes for a key item in a keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-item-attribute-constants-for-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain Item Attribute Constants For Keys",
      "type": "topic",
      "url": "/documentation/security/keychain-item-attribute-constants-for-keys"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "http://www.opengroup.org/security/cdsa.htm": {
      "identifier": "http://www.opengroup.org/security/cdsa.htm",
      "title": "http://www.opengroup.org/security/cdsa.htm",
      "titleInlineContent": [
        {
          "text": "http://www.opengroup.org/security/cdsa.htm",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.opengroup.org/security/cdsa.htm"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecItemAttr/creationDateItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/modDateItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/descriptionItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/commentItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/creatorItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/typeItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/scriptCodeItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/labelItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/invisibleItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/negativeItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/customIconItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/accountItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/serviceItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/genericItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/securityDomainItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/serverItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/authenticationTypeItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/portItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/pathItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/volumeItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/addressItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/signatureItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/protocolItemAttr",
        "doc://com.apple.security/documentation/Security/SecItemAttr/certificateType",
        "doc://com.apple.security/documentation/Security/SecItemAttr/certificateEncoding",
        "doc://com.apple.security/documentation/Security/SecItemAttr/crlType",
        "doc://com.apple.security/documentation/Security/SecItemAttr/crlEncoding",
        "doc://com.apple.security/documentation/Security/SecItemAttr/alias"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecItemAttr/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecItemAttr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecItemAttr/creationDateItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/modDateItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/descriptionItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/commentItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/creatorItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/typeItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/scriptCodeItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/labelItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/invisibleItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/negativeItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/customIconItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/accountItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/serviceItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/genericItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/securityDomainItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/serverItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/authenticationTypeItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/portItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/pathItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/volumeItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/addressItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/signatureItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/protocolItemAttr",
                "doc://com.apple.security/documentation/Security/SecItemAttr/certificateType",
                "doc://com.apple.security/documentation/Security/SecItemAttr/certificateEncoding",
                "doc://com.apple.security/documentation/Security/SecItemAttr/crlType",
                "doc://com.apple.security/documentation/Security/SecItemAttr/crlEncoding",
                "doc://com.apple.security/documentation/Security/SecItemAttr/alias"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecItemAttr"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1addressItemAttr/title",
          "value": "kSecAddressItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1addressItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAddressItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1certificateType/title",
          "value": "kSecCertificateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1certificateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCertificateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1certificateEncoding/title",
          "value": "kSecCertificateEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1certificateEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCertificateEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1portItemAttr/title",
          "value": "kSecPortItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1portItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPortItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1securityDomainItemAttr/title",
          "value": "kSecSecurityDomainItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1securityDomainItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSecurityDomainItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1signatureItemAttr/title",
          "value": "kSecSignatureItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1signatureItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSignatureItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1crlType/title",
          "value": "kSecCrlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1crlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCrlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1scriptCodeItemAttr/title",
          "value": "kSecScriptCodeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1scriptCodeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecScriptCodeItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1typeItemAttr/title",
          "value": "kSecTypeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1typeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTypeItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1labelItemAttr/title",
          "value": "kSecLabelItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1labelItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecLabelItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1alias/title",
          "value": "kSecAlias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1alias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAlias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1customIconItemAttr/title",
          "value": "kSecCustomIconItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1customIconItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCustomIconItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1protocolItemAttr/title",
          "value": "kSecProtocolItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1protocolItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1descriptionItemAttr/title",
          "value": "kSecDescriptionItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1descriptionItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDescriptionItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1authenticationTypeItemAttr/title",
          "value": "kSecAuthenticationTypeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1authenticationTypeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAuthenticationTypeItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1pathItemAttr/title",
          "value": "kSecPathItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1pathItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPathItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1modDateItemAttr/title",
          "value": "kSecModDateItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1modDateItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecModDateItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1crlEncoding/title",
          "value": "kSecCrlEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1crlEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCrlEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1creatorItemAttr/title",
          "value": "kSecCreatorItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1creatorItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCreatorItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1negativeItemAttr/title",
          "value": "kSecNegativeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1negativeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecNegativeItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1genericItemAttr/title",
          "value": "kSecGenericItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1genericItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGenericItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/title",
          "value": "SecItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1serverItemAttr/title",
          "value": "kSecServerItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1serverItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecServerItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1serviceItemAttr/title",
          "value": "kSecServiceItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1serviceItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecServiceItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1accountItemAttr/title",
          "value": "kSecAccountItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1accountItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAccountItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1creationDateItemAttr/title",
          "value": "kSecCreationDateItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1creationDateItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCreationDateItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1commentItemAttr/title",
          "value": "kSecCommentItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1commentItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCommentItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1invisibleItemAttr/title",
          "value": "kSecInvisibleItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1invisibleItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecInvisibleItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1volumeItemAttr/title",
          "value": "kSecVolumeItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr~1volumeItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecVolumeItemAttr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secitemattr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secitemattr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
