{
  "abstract": [
    {
      "text": "Finds the next identity matching specified search criteria",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecIdentitySearchCopyNext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecIdentitySearchCopyNext",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecIdentitySearchCopyNext"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecIdentitySearchCopyNext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecIdentitySearchCopyNext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecIdentitySearchCopyNext"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecIdentitySearchRef",
              "text": "SecIdentitySearchRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "searchRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecIdentityRef",
              "text": "SecIdentityRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "identity"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An identity search object specifying the search criteria for this search. You create the identity search object by calling the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearchCreate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "searchRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the identity object of the next matching identity (if any). In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when finished with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "identity"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When there are no more identities that match the parameters specified to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearchCreate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errSecItemNotFound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecIdentity": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "role": "symbol",
      "title": "SecIdentity",
      "type": "topic",
      "url": "/documentation/security/secidentity"
    },
    "doc://com.apple.security/documentation/Security/SecIdentitySearch": {
      "abstract": [
        {
          "text": "Contains information about an identity search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentitySearch"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentitySearch"
        }
      ],
      "role": "symbol",
      "title": "SecIdentitySearch",
      "type": "topic",
      "url": "/documentation/security/secidentitysearch"
    },
    "doc://com.apple.security/documentation/Security/SecIdentitySearchCopyNext": {
      "abstract": [
        {
          "text": "Finds the next identity matching specified search criteria",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecIdentitySearchCopyNext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearchCopyNext",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecIdentitySearchCopyNext",
      "type": "topic",
      "url": "/documentation/security/secidentitysearchcopynext"
    },
    "doc://com.apple.security/documentation/Security/SecIdentitySearchCreate": {
      "abstract": [
        {
          "text": "Creates a search object for finding identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecIdentitySearchCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySearchCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecIdentitySearchCreate",
      "type": "topic",
      "url": "/documentation/security/secidentitysearchcreate"
    },
    "doc://com.apple.security/documentation/Security/errSecItemNotFound": {
      "abstract": [
        {
          "text": "The item cannot be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSecItemNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSecItemNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSecItemNotFound"
        }
      ],
      "role": "symbol",
      "title": "errSecItemNotFound",
      "type": "topic",
      "url": "/documentation/security/errsecitemnotfound"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentitySearch/title",
          "value": "SecIdentitySearchRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentitySearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentitySearchRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentitySearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentitySearchRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/title",
          "value": "SecIdentityRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSecItemNotFound/title",
          "value": "errSecItemNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSecItemNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSecItemNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secidentitysearchcopynext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
