{
  "abstract": [
    {
      "text": "Specifies a keychain item’s class code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecItemClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecItemClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecItemClass"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecItemClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecItemClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecItemClass"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These enumerations define constants your application can use to specify the type of the keychain item you wish to create, dispose, add, delete, update, copy, or locate. You can also use these constants with the tag constant ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemAttr": {
      "abstract": [
        {
          "text": "Specifies a keychain item’s attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemAttr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemAttr"
        }
      ],
      "role": "symbol",
      "title": "SecItemAttr",
      "type": "topic",
      "url": "/documentation/security/secitemattr"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass": {
      "abstract": [
        {
          "text": "Specifies a keychain item’s class code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/certificateItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is an X509 certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "certificateItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/certificateItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCertificateItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.certificateItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/certificateitemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/genericPasswordItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is a generic password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericPasswordItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/genericPasswordItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGenericPasswordItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.genericPasswordItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/genericpassworditemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FourCharCode",
          "text": "FourCharCode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secitemclass/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/internetPasswordItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is an Internet password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internetPasswordItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/internetPasswordItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecInternetPasswordItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.internetPasswordItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/internetpassworditemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/kSecAppleSharePasswordItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is an AppleShare password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecAppleSharePasswordItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/kSecAppleSharePasswordItemClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAppleSharePasswordItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/ksecapplesharepassworditemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/privateKeyItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is a private key of a public-private pair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privateKeyItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/privateKeyItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPrivateKeyItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.privateKeyItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/privatekeyitemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/publicKeyItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is a public key of a public-private pair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicKeyItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/publicKeyItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPublicKeyItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.publicKeyItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/publickeyitemclass"
    },
    "doc://com.apple.security/documentation/Security/SecItemClass/symmetricKeyItemClass": {
      "abstract": [
        {
          "text": "Indicates that the item is a private key used for symmetric-key encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symmetricKeyItemClass"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemClass/symmetricKeyItemClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSymmetricKeyItemClass"
        }
      ],
      "role": "symbol",
      "title": "SecItemClass.symmetricKeyItemClass",
      "type": "topic",
      "url": "/documentation/security/secitemclass/symmetrickeyitemclass"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecItemClass/internetPasswordItemClass",
        "doc://com.apple.security/documentation/Security/SecItemClass/genericPasswordItemClass",
        "doc://com.apple.security/documentation/Security/SecItemClass/certificateItemClass",
        "doc://com.apple.security/documentation/Security/SecItemClass/publicKeyItemClass",
        "doc://com.apple.security/documentation/Security/SecItemClass/privateKeyItemClass",
        "doc://com.apple.security/documentation/Security/SecItemClass/symmetricKeyItemClass"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecItemClass/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecItemClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecItemClass/internetPasswordItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/genericPasswordItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/kSecAppleSharePasswordItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/certificateItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/publicKeyItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/privateKeyItemClass",
                "doc://com.apple.security/documentation/Security/SecItemClass/symmetricKeyItemClass"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecItemClass"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1symmetricKeyItemClass/title",
          "value": "kSecSymmetricKeyItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1symmetricKeyItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSymmetricKeyItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/title",
          "value": "SecItemAttr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemAttr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemAttr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1publicKeyItemClass/title",
          "value": "kSecPublicKeyItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1publicKeyItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPublicKeyItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1privateKeyItemClass/title",
          "value": "kSecPrivateKeyItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1privateKeyItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPrivateKeyItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass/title",
          "value": "SecItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1certificateItemClass/title",
          "value": "kSecCertificateItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1certificateItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCertificateItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1genericPasswordItemClass/title",
          "value": "kSecGenericPasswordItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1genericPasswordItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGenericPasswordItemClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1internetPasswordItemClass/title",
          "value": "kSecInternetPasswordItemClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemClass~1internetPasswordItemClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecInternetPasswordItemClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secitemclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secitemclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
