{
  "abstract": [
    {
      "text": "Generates a random symmetric key.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeyGenerateSymmetric",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeyGenerateSymmetric"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFErrorRef",
        "text": "CFError"
      },
      {
        "kind": "text",
        "text": ">?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecKeyRef",
        "text": "SecKey"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeyGenerateSymmetric"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.7",
        "message": "No longer supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeyGenerateSymmetric(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeyGenerateSymmetric"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFErrorRef",
              "text": "CFError"
            },
            {
              "kind": "text",
              "text": ">?>?) -> "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyRef",
              "text": "SecKey"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A key generation parameter dictionary. At minimum, this must contain ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". In addition, this function assumes default values for the following keys:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " if this key is present and has a value of ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ", the key or key pair will be added to the default keychain.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ", which means the effective key size is the same as the key size (",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ").",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            },
            {
              "inlineContent": [
                {
                  "text": "These default values can be overridden by adding a value for the associated key in the parameter dictionary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "When used as a replacement for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", set the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecUseKeychain",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key to the keychain (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") into which the key should be stored, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to a user-visible label for the key, and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationLabel",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to an identifier defined by your application, for subsequent use in calls to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Additionally, you can specify keychain access controls for the key by setting ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccess",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parameters"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " variable where an error object is stored upon failure. If not ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the caller is responsible for checking this variable and releasing the resulting object if it exists.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A newly generated symmetric key, or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " on failure. In Objective-C, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to free the key’s memory when you are done with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
      "kind": "article",
      "role": "article",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror-ru8"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAccess": {
      "abstract": [
        {
          "text": "An opaque type that identifies a keychain item’s access information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "role": "symbol",
      "title": "SecAccess",
      "type": "topic",
      "url": "/documentation/security/secaccess"
    },
    "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)": {
      "abstract": [
        {
          "text": "Returns one or more keychain items that match a search query, or copies attributes of specific keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        }
      ],
      "role": "symbol",
      "title": "SecItemCopyMatching(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemcopymatching(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKey": {
      "abstract": [
        {
          "text": "An object that represents a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "role": "symbol",
      "title": "SecKey",
      "type": "topic",
      "url": "/documentation/security/seckey"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGenerate": {
      "abstract": [
        {
          "text": "Creates a symmetric key and optionally stores it in a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeyGenerate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerate",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeyGenerate",
      "type": "topic",
      "url": "/documentation/security/seckeygenerate"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)": {
      "abstract": [
        {
          "text": "Generates a random symmetric key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyGenerateSymmetric"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyGenerateSymmetric"
        }
      ],
      "role": "symbol",
      "title": "SecKeyGenerateSymmetric(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeygeneratesymmetric(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeychain": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "role": "symbol",
      "title": "SecKeychain",
      "type": "topic",
      "url": "/documentation/security/seckeychain"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrAccess": {
      "abstract": [
        {
          "text": "A key with a value that indicates access control list settings for the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrAccess"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrAccess",
      "type": "topic",
      "url": "/documentation/security/ksecattraccess"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrApplicationLabel": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s application label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrApplicationLabel",
      "type": "topic",
      "url": "/documentation/security/ksecattrapplicationlabel"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s private tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationTag"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrApplicationTag",
      "type": "topic",
      "url": "/documentation/security/ksecattrapplicationtag"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for decryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanDecrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanDecrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanDecrypt",
      "type": "topic",
      "url": "/documentation/security/ksecattrcandecrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanDerive": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for derivation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanDerive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanDerive"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanDerive",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanderive"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanEncrypt",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanencrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanSign": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for digital signing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanSign"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanSign",
      "type": "topic",
      "url": "/documentation/security/ksecattrcansign"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for unwrapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanUnwrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanUnwrap"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanUnwrap",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanunwrap"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanVerify": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for signature verification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanVerify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanVerify"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanVerify",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanverify"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanWrap": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for wrapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanWrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanWrap"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanWrap",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanwrap"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize": {
      "abstract": [
        {
          "text": "A key whose value indicates the effective number of bits in a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrEffectiveKeySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrEffectiveKeySize"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrEffectiveKeySize",
      "type": "topic",
      "url": "/documentation/security/ksecattreffectivekeysize"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s permanence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrIsPermanent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrIsPermanent"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrIsPermanent",
      "type": "topic",
      "url": "/documentation/security/ksecattrispermanent"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits": {
      "abstract": [
        {
          "text": "A key whose value indicates the number of bits in a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeySizeInBits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrKeySizeInBits"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrKeySizeInBits",
      "type": "topic",
      "url": "/documentation/security/ksecattrkeysizeinbits"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrKeyType": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrKeyType"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrKeyType",
      "type": "topic",
      "url": "/documentation/security/ksecattrkeytype"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrLabel": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the item’s label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrLabel",
      "type": "topic",
      "url": "/documentation/security/ksecattrlabel"
    },
    "doc://com.apple.security/documentation/Security/kSecUseKeychain": {
      "abstract": [
        {
          "text": "A key whose value is a keychain to operate on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecUseKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecUseKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecUseKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSecUseKeychain",
      "type": "topic",
      "url": "/documentation/security/ksecusekeychain"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFErrorRef": {
      "abstract": [
        {
          "text": "A reference to a CFError object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeyGenerateSymmetric"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGenerateSymmetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecKeyRef",
                    "text": "SecKeyRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeyGenerateSymmetric"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFErrorRef",
                    "text": "CFErrorRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key generation parameter dictionary. At minimum, this must contain ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". In addition, this function assumes default values for the following keys:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " if this key is present and has a value of ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ", the key or key pair will be added to the default keychain.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ", which means the effective key size is the same as the key size (",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ").",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "These default values can be overridden by adding a value for the associated key in the parameter dictionary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "When used as a replacement for ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", set the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecUseKeychain",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " key to the keychain (",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ") into which the key should be stored, ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to a user-visible label for the key, and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationLabel",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to an identifier defined by your application, for subsequent use in calls to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecItemCopyMatching(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Additionally, you can specify keychain access controls for the key by setting ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrAccess",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "parameters"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " variable where an error object is stored upon failure. If not ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the caller is responsible for checking this variable and releasing the resulting object if it exists.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A newly generated symmetric key, or ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": " on failure. In Objective-C, call the ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " function to free the key’s memory when you are done with it.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeyType/title",
          "value": "kSecAttrKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanSign/title",
          "value": "kSecAttrCanSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/title",
          "value": "SecKeychainRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsPermanent/title",
          "value": "kSecAttrIsPermanent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsPermanent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrIsPermanent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanWrap/title",
          "value": "kSecAttrCanWrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanWrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanWrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrEffectiveKeySize/title",
          "value": "kSecAttrEffectiveKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrEffectiveKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrEffectiveKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeySizeInBits/title",
          "value": "kSecAttrKeySizeInBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeySizeInBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrKeySizeInBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/title",
          "value": "kSecAttrCanEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDerive/title",
          "value": "kSecAttrCanDerive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDerive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanDerive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationLabel/title",
          "value": "kSecAttrApplicationLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrApplicationLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/title",
          "value": "kSecAttrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseKeychain/title",
          "value": "kSecUseKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecUseKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecUseKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationTag/title",
          "value": "kSecAttrApplicationTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrApplicationTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/title",
          "value": "SecKeyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/title",
          "value": "SecItemCopyMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemCopyMatching(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemCopyMatching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccess/title",
          "value": "kSecAttrAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanVerify/title",
          "value": "kSecAttrCanVerify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanVerify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanVerify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDecrypt/title",
          "value": "kSecAttrCanDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDecrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanUnwrap/title",
          "value": "kSecAttrCanUnwrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanUnwrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanUnwrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/title",
          "value": "SecAccessRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGenerateSymmetric(_:_:)/title",
          "value": "SecKeyGenerateSymmetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGenerateSymmetric(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGenerateSymmetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title",
          "value": "CFErrorRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeygeneratesymmetric(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeygeneratesymmetric(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
