{
  "abstract": [
    {
      "text": "Generates a public/private key pair.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairAsync(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeyGeneratePairAsync",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeyGeneratePairAsync"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@dispatch_queue_t",
        "text": "dispatch_queue_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecKeyGeneratePairBlock",
        "text": "SecKeyGeneratePairBlock"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeyGeneratePairAsync"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.7",
        "message": "No longer supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeyGeneratePairAsync(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeyGeneratePairAsync"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "deliveryQueue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyGeneratePairBlock",
              "text": "SecKeyGeneratePairBlock"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A key generation parameter dictionary. At minimum, this must contain ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". In addition, this function assumes default values for the following keys:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " if this key is present and has a value of ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ", the key or key pair will be added to the default keychain.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "code": "NULL",
                          "type": "codeVoice"
                        },
                        {
                          "text": ", which means the effective key size is the same as the key size (",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ").",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " defaults to ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for private keys, ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " for public keys.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            },
            {
              "inlineContent": [
                {
                  "text": "These default values can be overridden by adding a value for the associated key in the parameter dictionary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parameters"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The dispatch queue on which the result block should be scheduled.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deliveryQueue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block of type ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that gets called with the result upon completion.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "result"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGeneratePairAsync(_:_:_:)": {
      "abstract": [
        {
          "text": "Generates a public/private key pair.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyGeneratePairAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyGeneratePairBlock",
          "text": "SecKeyGeneratePairBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairAsync(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyGeneratePairAsync"
        }
      ],
      "role": "symbol",
      "title": "SecKeyGeneratePairAsync(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeygeneratepairasync(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock": {
      "abstract": [
        {
          "text": "A block called with the results of a call to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairAsync(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyGeneratePairBlock"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyGeneratePairBlock"
        }
      ],
      "role": "symbol",
      "title": "SecKeyGeneratePairBlock",
      "type": "topic",
      "url": "/documentation/security/seckeygeneratepairblock"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s private tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrApplicationTag"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrApplicationTag",
      "type": "topic",
      "url": "/documentation/security/ksecattrapplicationtag"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for decryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanDecrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanDecrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanDecrypt",
      "type": "topic",
      "url": "/documentation/security/ksecattrcandecrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanDerive": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for derivation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanDerive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanDerive"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanDerive",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanderive"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanEncrypt",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanencrypt"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanSign": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for digital signing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanSign"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanSign",
      "type": "topic",
      "url": "/documentation/security/ksecattrcansign"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for unwrapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanUnwrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanUnwrap"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanUnwrap",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanunwrap"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanVerify": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for signature verification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanVerify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanVerify"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanVerify",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanverify"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanWrap": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for wrapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanWrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanWrap"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanWrap",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanwrap"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize": {
      "abstract": [
        {
          "text": "A key whose value indicates the effective number of bits in a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrEffectiveKeySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrEffectiveKeySize"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrEffectiveKeySize",
      "type": "topic",
      "url": "/documentation/security/ksecattreffectivekeysize"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s permanence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrIsPermanent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrIsPermanent"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrIsPermanent",
      "type": "topic",
      "url": "/documentation/security/ksecattrispermanent"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits": {
      "abstract": [
        {
          "text": "A key whose value indicates the number of bits in a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeySizeInBits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrKeySizeInBits"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrKeySizeInBits",
      "type": "topic",
      "url": "/documentation/security/ksecattrkeysizeinbits"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrKeyType": {
      "abstract": [
        {
          "text": "A key whose value indicates the item’s algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrKeyType"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrKeyType",
      "type": "topic",
      "url": "/documentation/security/ksecattrkeytype"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrLabel": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the item’s label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrLabel"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrLabel",
      "type": "topic",
      "url": "/documentation/security/ksecattrlabel"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeyGeneratePairAsync"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGeneratePairAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeyGeneratePairAsync"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_queue_t",
                    "text": "dispatch_queue_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "deliveryQueue"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecKeyGeneratePairBlock",
                    "text": "SecKeyGeneratePairBlock"
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key generation parameter dictionary. At minimum, this must contain ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeyType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". In addition, this function assumes default values for the following keys:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrLabel",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrIsPermanent",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " if this key is present and has a value of ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ", the key or key pair will be added to the default keychain.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrApplicationTag",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrEffectiveKeySize",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "code": "NULL",
                                "type": "codeVoice"
                              },
                              {
                                "text": ", which means the effective key size is the same as the key size (",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrKeySizeInBits",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ").",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDecrypt",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanDerive",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanSign",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanVerify",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanWrap",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanUnwrap",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " defaults to ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for private keys, ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " for public keys.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "These default values can be overridden by adding a value for the associated key in the parameter dictionary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "parameters"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The dispatch queue on which the result block should be scheduled.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "deliveryQueue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block of type ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecKeyGeneratePairBlock",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that gets called with the result upon completion.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "result"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanSign/title",
          "value": "kSecAttrCanSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDecrypt/title",
          "value": "kSecAttrCanDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDecrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsPermanent/title",
          "value": "kSecAttrIsPermanent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrIsPermanent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrIsPermanent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGeneratePairAsync(_:_:_:)/title",
          "value": "SecKeyGeneratePairAsync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGeneratePairAsync(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGeneratePairAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/title",
          "value": "kSecAttrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanUnwrap/title",
          "value": "kSecAttrCanUnwrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanUnwrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanUnwrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeyType/title",
          "value": "kSecAttrKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrEffectiveKeySize/title",
          "value": "kSecAttrEffectiveKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrEffectiveKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrEffectiveKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanWrap/title",
          "value": "kSecAttrCanWrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanWrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanWrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationTag/title",
          "value": "kSecAttrApplicationTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrApplicationTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrApplicationTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/title",
          "value": "kSecAttrCanEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeySizeInBits/title",
          "value": "kSecAttrKeySizeInBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrKeySizeInBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrKeySizeInBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDerive/title",
          "value": "kSecAttrCanDerive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanDerive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanDerive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanVerify/title",
          "value": "kSecAttrCanVerify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanVerify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanVerify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGeneratePairBlock/title",
          "value": "SecKeyGeneratePairBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGeneratePairBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGeneratePairBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGeneratePairBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGeneratePairBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeygeneratepairasync(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeygeneratepairasync(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
