{
  "abstract": [
    {
      "text": "The legacy import/export parameter structure.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This structure is passed in the ",
          "type": "text"
        },
        {
          "code": "keyParams",
          "type": "codeVoice"
        },
        {
          "text": " parameter as input to the deprecated ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemExport",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecItemExport(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead. The newer functions rely on the similar but distinct ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecItemImportExportKeyParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure as input rather than the structure defined here.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SecKeyImportExportParameters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeyImportExportParameters"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeyImportExportParameters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SecKeyImportExportParameters"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "PKCS12 is an abbreviation for Public-Key Cryptography Standard # 12. This standard, by RSA Security, provides a format for external representation of keys and certificates and is described in ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "PKCS 12 v1.0: Personal Information Exchange Syntax",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecItemExport(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Exports one or more certificates, keys, or identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemExport"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecExternalFormat",
          "text": "SecExternalFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecItemImportExportFlags",
          "text": "SecItemImportExportFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SecItemImportExportKeyParameters",
          "text": "SecItemImportExportKeyParameters"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemExport(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemExport"
        }
      ],
      "role": "symbol",
      "title": "SecItemExport(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemexport(_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Imports one or more certificates, keys, or identities and optionally adds them to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemImport"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecExternalFormat",
          "text": "SecExternalFormat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecExternalItemType",
          "text": "SecExternalItemType"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecItemImportExportFlags",
          "text": "SecItemImportExportFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SecItemImportExportKeyParameters",
          "text": "SecItemImportExportKeyParameters"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeychainRef",
          "text": "SecKeychain"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemImport"
        }
      ],
      "role": "symbol",
      "title": "SecItemImport(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemimport(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemImportExportKeyParameters": {
      "abstract": [
        {
          "text": "The import/export parameter structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemImportExportKeyParameters"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemImportExportKeyParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemImportExportKeyParameters"
        }
      ],
      "role": "symbol",
      "title": "SecItemImportExportKeyParameters",
      "type": "topic",
      "url": "/documentation/security/secitemimportexportkeyparameters"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters": {
      "abstract": [
        {
          "text": "The legacy import/export parameter structure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyImportExportParameters"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyImportExportParameters"
        }
      ],
      "role": "symbol",
      "title": "SecKeyImportExportParameters",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/accessRef": {
      "abstract": [
        {
          "text": "Specifies the initial access controls of imported private keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAccessRef",
          "text": "SecAccess"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/accessRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessRef"
        }
      ],
      "role": "symbol",
      "title": "accessRef",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/accessref"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertPrompt": {
      "abstract": [
        {
          "text": "The prompt to display in the secure passphrase alert panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertPrompt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertPrompt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertPrompt"
        }
      ],
      "role": "symbol",
      "title": "alertPrompt",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/alertprompt"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertTitle": {
      "abstract": [
        {
          "text": "The title to display in the secure passphrase alert panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertTitle"
        }
      ],
      "role": "symbol",
      "title": "alertTitle",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/alerttitle"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/flags": {
      "abstract": [
        {
          "text": "The bitwise ",
          "type": "text"
        },
        {
          "code": "OR",
          "type": "codeVoice"
        },
        {
          "text": " of zero or more key import/export flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyImportExportFlags",
          "text": "SecKeyImportExportFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/flags"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/init(version:flags:passphrase:alertTitle:alertPrompt:accessRef:keyUsage:keyAttributes:)": {
      "abstract": [
        {
          "text": "Creates a new import/export parameter structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyImportExportFlags",
          "text": "SecKeyImportExportFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "passphrase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "alertTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "alertPrompt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "accessRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAccessRef",
          "text": "SecAccess"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "keyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_KEYUSE",
          "text": "CSSM_KEYUSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keyAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_KEYATTR_FLAGS",
          "text": "CSSM_KEYATTR_FLAGS"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/init(version:flags:passphrase:alertTitle:alertPrompt:accessRef:keyUsage:keyAttributes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:flags:passphrase:alertTitle:alertPrompt:accessRef:keyUsage:keyAttributes:)",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/init(version:flags:passphrase:alerttitle:alertprompt:accessref:keyusage:keyattributes:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyAttributes": {
      "abstract": [
        {
          "text": "A word of bits constituting the low-level attribute flags for imported keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_KEYATTR_FLAGS",
          "text": "CSSM_KEYATTR_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyAttributes"
        }
      ],
      "role": "symbol",
      "title": "keyAttributes",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/keyattributes"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyUsage": {
      "abstract": [
        {
          "text": "A word of bits constituting the low-level use flags for imported keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_KEYUSE",
          "text": "CSSM_KEYUSE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyUsage"
        }
      ],
      "role": "symbol",
      "title": "keyUsage",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/keyusage"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/passphrase": {
      "abstract": [
        {
          "text": "The password to use during key import or export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passphrase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/passphrase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passphrase"
        }
      ],
      "role": "symbol",
      "title": "passphrase",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/passphrase"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/version": {
      "abstract": [
        {
          "text": "The version of this structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters/version"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItemExport": {
      "abstract": [
        {
          "text": "Exports one or more certificates, keys, or identities.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainItemExport"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemExport",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainItemExport",
      "type": "topic",
      "url": "/documentation/security/seckeychainitemexport"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItemImport": {
      "abstract": [
        {
          "text": "Imports one or more certificates, keys, or identities and adds them to a keychain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainItemImport"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainItemImport",
      "type": "topic",
      "url": "/documentation/security/seckeychainitemimport"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/accessRef",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertPrompt",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertTitle",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/flags",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyAttributes",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyUsage",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/passphrase",
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/version"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/init(version:flags:passphrase:alertTitle:alertPrompt:accessRef:keyUsage:keyAttributes:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeyImportExportParameters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/accessRef",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertPrompt",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/alertTitle",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/flags",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyAttributes",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/keyUsage",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/passphrase",
                "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeyImportExportParameters"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This structure is passed in the ",
                  "type": "text"
                },
                {
                  "code": "keyParams",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter as input to the deprecated ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemExport",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " functions. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemExport(_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead. The newer functions rely on the similar but distinct ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecItemImportExportKeyParameters",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure as input rather than the structure defined here.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemExport(_:_:_:_:_:)/title",
          "value": "SecItemExport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemExport(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemExport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1alertPrompt/title",
          "value": "alertPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1alertPrompt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1alertTitle/title",
          "value": "alertTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1alertTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1keyUsage/title",
          "value": "keyUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1keyUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1keyAttributes/title",
          "value": "keyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1keyAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImport(_:_:_:_:_:_:_:_:)/title",
          "value": "SecItemImport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImport(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1passphrase/title",
          "value": "passphrase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1passphrase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passphrase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/title",
          "value": "SecKeyImportExportParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportKeyParameters/title",
          "value": "SecItemImportExportKeyParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportKeyParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImportExportKeyParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportKeyParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImportExportKeyParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1accessRef/title",
          "value": "accessRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters~1accessRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeyimportexportparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeyimportexportparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
