{
  "abstract": [
    {
      "text": "Bit masks corresponding to the events that can trigger a keychain callback.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeychainEventMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecKeychainEventMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeychainEventMask"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeychainEventMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SecKeychainEventMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeychainEventMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Bitwise ",
              "type": "text"
            },
            {
              "code": "OR",
              "type": "codeVoice"
            },
            {
              "text": " one or more of these masks together to provide the ",
              "type": "text"
            },
            {
              "code": "eventMask",
              "type": "codeVoice"
            },
            {
              "text": " input to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychainAddCallback(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to indicate what event or events should trigger your callback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainAddCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers your keychain event callback function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychainAddCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeychainCallback",
          "text": "SecKeychainCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainAddCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychainAddCallback"
        }
      ],
      "role": "symbol",
      "title": "SecKeychainAddCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeychainaddcallback(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask": {
      "abstract": [
        {
          "text": "Bit masks corresponding to the events that can trigger a keychain callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychainEventMask"
        }
      ],
      "role": "symbol",
      "title": "SecKeychainEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/addEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when an item is added to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/addEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAddEventMask"
        }
      ],
      "role": "symbol",
      "title": "addEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/addeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/dataAccessEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a process accesses a keychain item’s data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataAccessEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/dataAccessEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDataAccessEventMask"
        }
      ],
      "role": "symbol",
      "title": "dataAccessEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/dataaccesseventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/defaultChangedEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a different keychain is specified as the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultChangedEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/defaultChangedEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDefaultChangedEventMask"
        }
      ],
      "role": "symbol",
      "title": "defaultChangedEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/defaultchangedeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/deleteEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when an item is deleted from a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/deleteEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDeleteEventMask"
        }
      ],
      "role": "symbol",
      "title": "deleteEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/deleteeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/everyEventMask": {
      "abstract": [
        {
          "text": "If all the bits are set, your callback function is invoked whenever any event occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "everyEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/everyEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecEveryEventMask"
        }
      ],
      "role": "symbol",
      "title": "everyEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/everyeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes an event mask value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/keychainListChangedMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a keychain list is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keychainListChangedMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/keychainListChangedMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeychainListChangedMask"
        }
      ],
      "role": "symbol",
      "title": "keychainListChangedMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/keychainlistchangedmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/lockEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a keychain is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/lockEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecLockEventMask"
        }
      ],
      "role": "symbol",
      "title": "lockEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/lockeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/passwordChangedEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when the keychain password is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passwordChangedEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/passwordChangedEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPasswordChangedEventMask"
        }
      ],
      "role": "symbol",
      "title": "passwordChangedEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/passwordchangedeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/trustSettingsChangedEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when there is a change in certificate trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trustSettingsChangedEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/trustSettingsChangedEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsChangedEventMask"
        }
      ],
      "role": "symbol",
      "title": "trustSettingsChangedEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/trustsettingschangedeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/unlockEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a keychain is unlocked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/unlockEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecUnlockEventMask"
        }
      ],
      "role": "symbol",
      "title": "unlockEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/unlockeventmask"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainEventMask/updateEventMask": {
      "abstract": [
        {
          "text": "If the bit specified by this mask is set, your callback function is invoked when a keychain item is updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateEventMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeychainEventMask",
          "text": "SecKeychainEventMask"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainEventMask/updateEventMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecUpdateEventMask"
        }
      ],
      "role": "symbol",
      "title": "updateEventMask",
      "type": "topic",
      "url": "/documentation/security/seckeychaineventmask/updateeventmask"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/lockEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/unlockEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/addEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/deleteEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/updateEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/passwordChangedEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/defaultChangedEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/dataAccessEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/keychainListChangedMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/trustSettingsChangedEventMask",
        "doc://com.apple.security/documentation/Security/SecKeychainEventMask/everyEventMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeychainEventMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/lockEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/unlockEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/addEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/deleteEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/updateEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/passwordChangedEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/defaultChangedEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/dataAccessEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/keychainListChangedMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/trustSettingsChangedEventMask",
                "doc://com.apple.security/documentation/Security/SecKeychainEventMask/everyEventMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeychainEventMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1trustSettingsChangedEventMask/title",
          "value": "kSecTrustSettingsChangedEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1trustSettingsChangedEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsChangedEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainAddCallback(_:_:_:)/title",
          "value": "SecKeychainAddCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainAddCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainAddCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1lockEventMask/title",
          "value": "kSecLockEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1lockEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecLockEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1keychainListChangedMask/title",
          "value": "kSecKeychainListChangedMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1keychainListChangedMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeychainListChangedMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1addEventMask/title",
          "value": "kSecAddEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1addEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAddEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1updateEventMask/title",
          "value": "kSecUpdateEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1updateEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecUpdateEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1unlockEventMask/title",
          "value": "kSecUnlockEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1unlockEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecUnlockEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1dataAccessEventMask/title",
          "value": "kSecDataAccessEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1dataAccessEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDataAccessEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1defaultChangedEventMask/title",
          "value": "kSecDefaultChangedEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1defaultChangedEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDefaultChangedEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1deleteEventMask/title",
          "value": "kSecDeleteEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1deleteEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDeleteEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1passwordChangedEventMask/title",
          "value": "kSecPasswordChangedEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1passwordChangedEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPasswordChangedEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1everyEventMask/title",
          "value": "kSecEveryEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask~1everyEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecEveryEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask/title",
          "value": "SecKeychainEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainEventMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainEventMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeychaineventmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeychaineventmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
