{
  "abstract": [
    {
      "text": "The flags that indicate key usage in the ",
      "type": "text"
    },
    {
      "code": "KeyUsage",
      "type": "codeVoice"
    },
    {
      "text": " extension of a certificate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeyUsage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecKeyUsage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeyUsage"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeyUsage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SecKeyUsage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeyUsage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage": {
      "abstract": [
        {
          "text": "The flags that indicate key usage in the ",
          "type": "text"
        },
        {
          "code": "KeyUsage",
          "type": "codeVoice"
        },
        {
          "text": " extension of a certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyUsage"
        }
      ],
      "role": "symbol",
      "title": "SecKeyUsage",
      "type": "topic",
      "url": "/documentation/security/seckeyusage"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/all": {
      "abstract": [
        {
          "text": "All flags set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/all"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/contentCommitment": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ContentCommitment",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentCommitment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/contentCommitment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageContentCommitment"
        }
      ],
      "role": "symbol",
      "title": "contentCommitment",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/contentcommitment"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/critical": {
      "abstract": [
        {
          "text": "The KeyUsage extension is marked critical.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "critical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/critical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageCritical"
        }
      ],
      "role": "symbol",
      "title": "critical",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/critical"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/crlSign": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "CRLSign",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crlSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/crlSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageCRLSign"
        }
      ],
      "role": "symbol",
      "title": "crlSign",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/crlsign"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/dataEncipherment": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "DataEncipherment",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataEncipherment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/dataEncipherment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageDataEncipherment"
        }
      ],
      "role": "symbol",
      "title": "dataEncipherment",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/dataencipherment"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/decipherOnly": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "DecipherOnly",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decipherOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/decipherOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageDecipherOnly"
        }
      ],
      "role": "symbol",
      "title": "decipherOnly",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/decipheronly"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/digitalSignature": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "DigitalSignature",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "digitalSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/digitalSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageDigitalSignature"
        }
      ],
      "role": "symbol",
      "title": "digitalSignature",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/digitalsignature"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/encipherOnly": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "EncipherOnly",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encipherOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/encipherOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageEncipherOnly"
        }
      ],
      "role": "symbol",
      "title": "encipherOnly",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/encipheronly"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a key usage structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/kSecKeyUsageUnspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageUnspecified"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/kSecKeyUsageUnspecified",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecKeyUsageUnspecified",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/kseckeyusageunspecified"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/keyAgreement": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "KeyAgreement",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyAgreement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/keyAgreement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageKeyAgreement"
        }
      ],
      "role": "symbol",
      "title": "keyAgreement",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/keyagreement"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/keyCertSign": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "KeyCertSign",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyCertSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/keyCertSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageKeyCertSign"
        }
      ],
      "role": "symbol",
      "title": "keyCertSign",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/keycertsign"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/keyEncipherment": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "KeyEncipherment",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEncipherment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/keyEncipherment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageKeyEncipherment"
        }
      ],
      "role": "symbol",
      "title": "keyEncipherment",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/keyencipherment"
    },
    "doc://com.apple.security/documentation/Security/SecKeyUsage/nonRepudiation": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NonRepudiation",
          "type": "codeVoice"
        },
        {
          "text": " bit is set in KeyUsage extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonRepudiation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyUsage",
          "text": "SecKeyUsage"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyUsage/nonRepudiation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyUsageNonRepudiation"
        }
      ],
      "role": "symbol",
      "title": "nonRepudiation",
      "type": "topic",
      "url": "/documentation/security/seckeyusage/nonrepudiation"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeyUsage/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Flags",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeyUsage/crlSign",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/contentCommitment",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/critical",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/dataEncipherment",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/decipherOnly",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/digitalSignature",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/encipherOnly",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/keyAgreement",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/keyCertSign",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/keyEncipherment",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/nonRepudiation",
        "doc://com.apple.security/documentation/Security/SecKeyUsage/all"
      ],
      "title": "Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeyUsage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Flags",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecKeyUsage/kSecKeyUsageUnspecified",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/crlSign",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/contentCommitment",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/critical",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/dataEncipherment",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/decipherOnly",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/digitalSignature",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/encipherOnly",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/keyAgreement",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/keyCertSign",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/keyEncipherment",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/nonRepudiation",
                "doc://com.apple.security/documentation/Security/SecKeyUsage/all"
              ],
              "title": "Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeyUsage"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyCertSign/title",
          "value": "kSecKeyUsageKeyCertSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyCertSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageKeyCertSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1decipherOnly/title",
          "value": "kSecKeyUsageDecipherOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1decipherOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageDecipherOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1crlSign/title",
          "value": "kSecKeyUsageCRLSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1crlSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageCRLSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1all/title",
          "value": "kSecKeyUsageAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1contentCommitment/title",
          "value": "kSecKeyUsageContentCommitment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1contentCommitment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageContentCommitment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1digitalSignature/title",
          "value": "kSecKeyUsageDigitalSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1digitalSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageDigitalSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage/title",
          "value": "SecKeyUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1critical/title",
          "value": "kSecKeyUsageCritical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1critical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageCritical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1nonRepudiation/title",
          "value": "kSecKeyUsageNonRepudiation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1nonRepudiation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageNonRepudiation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1dataEncipherment/title",
          "value": "kSecKeyUsageDataEncipherment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1dataEncipherment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageDataEncipherment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1encipherOnly/title",
          "value": "kSecKeyUsageEncipherOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1encipherOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageEncipherOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyEncipherment/title",
          "value": "kSecKeyUsageKeyEncipherment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyEncipherment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageKeyEncipherment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyAgreement/title",
          "value": "kSecKeyUsageKeyAgreement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyUsage~1keyAgreement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyUsageKeyAgreement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeyusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeyusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
