{
  "abstract": [
    {
      "text": "Returns the CSSM CSP handle for the given keychain object.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "The common security services manager module is no longer used.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeychainGetCSPHandle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecKeychainGetCSPHandle"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeychainGetCSPHandle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeychainGetCSPHandle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeychainGetCSPHandle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeychainRef",
              "text": "SecKeychainRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keychain"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
              "text": "CSSM_CSP_HANDLE"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "cspHandle"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A keychain object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keychain"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, a pointer to the CSSM CSP handle for the given keychain. The handle is valid until the keychain object is released.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cspHandle"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This function is deprecated.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The common security services manager module is no longer used.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CSP_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_handle"
    },
    "doc://com.apple.security/documentation/Security/SecKeychain": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "role": "symbol",
      "title": "SecKeychain",
      "type": "topic",
      "url": "/documentation/security/seckeychain"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle": {
      "abstract": [
        {
          "text": "Returns the CSSM CSP handle for the given keychain object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainGetCSPHandle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainGetCSPHandle",
      "type": "topic",
      "url": "/documentation/security/seckeychaingetcsphandle"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/title",
          "value": "SecKeychainRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/title",
          "value": "CSSM_CSP_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeychaingetcsphandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
