{
  "abstract": [
    {
      "text": "The supported sizes for keys of various common types.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecKeySizes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecKeySizes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecKeySizes"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeySizes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.9",
        "message": "No longer supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecKeySizes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeySizes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes": {
      "abstract": [
        {
          "text": "The supported sizes for keys of various common types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeySizes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeySizes"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes",
      "type": "topic",
      "url": "/documentation/security/seckeysizes"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/sec3DES192": {
      "abstract": [
        {
          "text": "192-bit DES.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sec3DES192"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/sec3DES192",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSec3DES192"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.sec3DES192",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/sec3des192"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secAES128": {
      "abstract": [
        {
          "text": "128-bit AES.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secAES128"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secAES128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAES128"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secAES128",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secaes128"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secAES192": {
      "abstract": [
        {
          "text": "192-bit AES.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secAES192"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeySizes",
          "text": "SecKeySizes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secAES192",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAES192"
        }
      ],
      "role": "symbol",
      "title": "secAES192",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secaes192"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secAES256": {
      "abstract": [
        {
          "text": "256-bit AES.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secAES256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secAES256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAES256"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secAES256",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secaes256"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secDefaultKeySize": {
      "abstract": [
        {
          "text": "The default key size for the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secDefaultKeySize"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secDefaultKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDefaultKeySize"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secDefaultKeySize",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secdefaultkeysize"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMax": {
      "abstract": [
        {
          "text": "4096 bits is the maximum size for an RSA key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secRSAMax"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRSAMax"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secRSAMax",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secrsamax"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMin": {
      "abstract": [
        {
          "text": "1024 bits is the minimum size for an RSA key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secRSAMin"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRSAMin"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secRSAMin",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secrsamin"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secp192r1": {
      "abstract": [
        {
          "text": "192-bit ECC Keys for Suite-B from RFC 4492 section 5.1.1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secp192r1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeySizes",
          "text": "SecKeySizes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secp192r1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecp192r1"
        }
      ],
      "role": "symbol",
      "title": "secp192r1",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secp192r1"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secp256r1": {
      "abstract": [
        {
          "text": "256-bit ECC Keys for Suite-B from RFC 4492 section 5.1.1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secp256r1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeySizes",
          "text": "SecKeySizes"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secp256r1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecp256r1"
        }
      ],
      "role": "symbol",
      "title": "secp256r1",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secp256r1"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secp384r1": {
      "abstract": [
        {
          "text": "384-bit ECC Keys for Suite-B from RFC 4492 section 5.1.1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secp384r1"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secp384r1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecp384r1"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secp384r1",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secp384r1"
    },
    "doc://com.apple.security/documentation/Security/SecKeySizes/secp521r1": {
      "abstract": [
        {
          "text": "521-bit ECC Keys for Suite-B from RFC 4492 section 5.1.1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secp521r1"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeySizes/secp521r1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecp521r1"
        }
      ],
      "role": "symbol",
      "title": "SecKeySizes.secp521r1",
      "type": "topic",
      "url": "/documentation/security/seckeysizes/secp521r1"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeySizes/secDefaultKeySize",
        "doc://com.apple.security/documentation/Security/SecKeySizes/sec3DES192",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secAES128",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secAES192",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secAES256",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secp192r1",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secp256r1",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secp384r1",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secp521r1",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMin",
        "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMax"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecKeySizes/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecKeySizes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeySizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeySizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecKeySizes/secDefaultKeySize",
                "doc://com.apple.security/documentation/Security/SecKeySizes/sec3DES192",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secAES128",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secAES192",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secAES256",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secp192r1",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secp256r1",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secp384r1",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secp521r1",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMin",
                "doc://com.apple.security/documentation/Security/SecKeySizes/secRSAMax"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecKeySizes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes/title",
          "value": "SecKeySizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeySizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeySizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secRSAMin/title",
          "value": "kSecRSAMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secRSAMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRSAMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp384r1/title",
          "value": "kSecp384r1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp384r1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecp384r1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp256r1/title",
          "value": "kSecp256r1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp256r1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecp256r1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp192r1/title",
          "value": "kSecp192r1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp192r1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecp192r1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES192/title",
          "value": "kSecAES192"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES192/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAES192"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secDefaultKeySize/title",
          "value": "kSecDefaultKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secDefaultKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDefaultKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES256/title",
          "value": "kSecAES256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAES256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES128/title",
          "value": "kSecAES128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secAES128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAES128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1sec3DES192/title",
          "value": "kSec3DES192"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1sec3DES192/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSec3DES192"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp521r1/title",
          "value": "kSecp521r1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secp521r1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecp521r1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secRSAMax/title",
          "value": "kSecRSAMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeySizes~1secRSAMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRSAMax"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeysizes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/seckeysizes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
