{
  "abstract": [
    {
      "text": "Creates a symmetric key and optionally stores it in a keychain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecKeyGenerate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeyGenerate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecKeyGenerate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeyGenerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeyGenerate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeyGenerate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeychainRef",
              "text": "SecKeychainRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keychainRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_ALGORITHMS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_ALGORITHMS",
              "text": "CSSM_ALGORITHMS"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "algorithm"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keySizeInBits"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CC_HANDLE",
              "text": "CSSM_CC_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "contextHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEYUSE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_KEYUSE",
              "text": "CSSM_KEYUSE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keyUsage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keyAttr"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecAccessRef",
              "text": "SecAccessRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "initialAccess"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyRef",
              "text": "SecKeyRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "keyRef"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The keychain in which to store the generated key. Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to generate a transient key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keychainRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The algorithm to use in generating the symmetric key. Possible values are defined in ",
                  "type": "text"
                },
                {
                  "code": "cssmtype.h",
                  "type": "codeVoice"
                },
                {
                  "text": ". Algorithms supported by the AppleCSP module are listed in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/Security/Reference/SecAppleCryptoSpec/Apple_Cryptographic_Service_Provider_Functional_Specification.pdf",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". This parameter is ignored if the ",
                  "type": "text"
                },
                {
                  "code": "contextHandle",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter is not ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "algorithm"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A key size for the key pair. This parameter is ignored if the ",
                  "type": "text"
                },
                {
                  "code": "contextHandle",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter is not ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keySizeInBits"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A CSSM CSP handle, or ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ". If this argument is not ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ", the ",
                  "type": "text"
                },
                {
                  "code": "algorithm",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "keySizeInBits",
                  "type": "codeVoice"
                },
                {
                  "text": " parameters are ignored.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contextHandle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask indicating all permitted uses for the new key. The possible values for the ",
                  "type": "text"
                },
                {
                  "code": "CSSM_KEYUSE",
                  "type": "codeVoice"
                },
                {
                  "text": " data type are defined in ",
                  "type": "text"
                },
                {
                  "code": "cssmtype.h",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyUsage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask defining attribute values for the new key. The bit mask values are defined in ",
                  "type": "text"
                },
                {
                  "code": "CSSM_KEYATTR_FLAGS",
                  "type": "codeVoice"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "cssmtype.h",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyAttr"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An access object that sets the initial access control list for the key returned. See Creating an Access Object in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for functions that create an access object. This parameter is ignored if you specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for the ",
                  "type": "text"
                },
                {
                  "code": "keychainRef",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "initialAccess"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the keychain item object of the new public key. Use this object as input to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeyGetCSSMKey",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to obtain the ",
                  "type": "text"
                },
                {
                  "code": "CSSM_KEY",
                  "type": "codeVoice"
                },
                {
                  "text": " structure containing the key. In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when you are finished with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyRef"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Key-generation algorithms supported by the AppleCSP module are listed in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Security/Reference/SecAppleCryptoSpec/Apple_Cryptographic_Service_Provider_Functional_Specification.pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For details about algorithms and default values for key-generation parameters, download the CDSA security framework from Apple’s Open Source website at ",
              "type": "text"
            },
            {
              "identifier": "https://opensource.apple.com/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and read the file ",
              "type": "text"
            },
            {
              "code": "Supported_CSP_Algorithms.doc",
              "type": "codeVoice"
            },
            {
              "text": " in the Documentation folder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you need extra parameters to generate a key—as required by some algorithms—call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to obtain a CSSM CSP handle and then call ",
              "type": "text"
            },
            {
              "code": "CSSM_CSP_CreateKeyGenContext",
              "type": "codeVoice"
            },
            {
              "text": " to create a context. With this context, use ",
              "type": "text"
            },
            {
              "code": "CSSM_UpdateContextAttributes",
              "type": "codeVoice"
            },
            {
              "text": " to add additional parameters. Finally, call ",
              "type": "text"
            },
            {
              "code": "CSSM_DeleteContext",
              "type": "codeVoice"
            },
            {
              "text": " to dispose of the context after calling this function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_ALGORITHMS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_ALGORITHMS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_ALGORITHMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_ALGORITHMS"
        }
      ],
      "role": "symbol",
      "title": "CSSM_ALGORITHMS",
      "type": "topic",
      "url": "/documentation/security/cssm_algorithms"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CC_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CC_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CC_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CC_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_cc_handle"
    },
    "doc://com.apple.security/documentation/Security/CSSM_KEYUSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_KEYUSE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_KEYUSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_KEYUSE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_KEYUSE",
      "type": "topic",
      "url": "/documentation/security/cssm_keyuse"
    },
    "doc://com.apple.security/documentation/Security/SecAccess": {
      "abstract": [
        {
          "text": "An opaque type that identifies a keychain item’s access information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAccess"
        }
      ],
      "role": "symbol",
      "title": "SecAccess",
      "type": "topic",
      "url": "/documentation/security/secaccess"
    },
    "doc://com.apple.security/documentation/Security/SecKey": {
      "abstract": [
        {
          "text": "An object that represents a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKey"
        }
      ],
      "role": "symbol",
      "title": "SecKey",
      "type": "topic",
      "url": "/documentation/security/seckey"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGenerate": {
      "abstract": [
        {
          "text": "Creates a symmetric key and optionally stores it in a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeyGenerate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerate",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeyGenerate",
      "type": "topic",
      "url": "/documentation/security/seckeygenerate"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)": {
      "abstract": [
        {
          "text": "Generates a random symmetric key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyGenerateSymmetric"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGenerateSymmetric(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyGenerateSymmetric"
        }
      ],
      "role": "symbol",
      "title": "SecKeyGenerateSymmetric(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeygeneratesymmetric(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGetCSSMKey": {
      "abstract": [
        {
          "text": "Retrieves a pointer to the ",
          "type": "text"
        },
        {
          "code": "CSSM_KEY",
          "type": "codeVoice"
        },
        {
          "text": " structure containing the key stored in a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeyGetCSSMKey"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGetCSSMKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeyGetCSSMKey",
      "type": "topic",
      "url": "/documentation/security/seckeygetcssmkey"
    },
    "doc://com.apple.security/documentation/Security/SecKeychain": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "role": "symbol",
      "title": "SecKeychain",
      "type": "topic",
      "url": "/documentation/security/seckeychain"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle": {
      "abstract": [
        {
          "text": "Returns the CSSM CSP handle for the given keychain object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainGetCSPHandle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainGetCSPHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainGetCSPHandle",
      "type": "topic",
      "url": "/documentation/security/seckeychaingetcsphandle"
    },
    "doc://com.apple.security/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keychain-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/security/keychain-services"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.apple.security/documentation/Security/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/security/uint32"
    },
    "https://developer.apple.com/library/archive/documentation/Security/Reference/SecAppleCryptoSpec/Apple_Cryptographic_Service_Provider_Functional_Specification.pdf": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Security/Reference/SecAppleCryptoSpec/Apple_Cryptographic_Service_Provider_Functional_Specification.pdf",
      "title": "Apple Cryptographic Service Provider Functional Specification",
      "titleInlineContent": [
        {
          "text": "Apple Cryptographic Service Provider Functional Specification",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Security/Reference/SecAppleCryptoSpec/Apple_Cryptographic_Service_Provider_Functional_Specification.pdf"
    },
    "https://opensource.apple.com/": {
      "identifier": "https://opensource.apple.com/",
      "title": "https://opensource.apple.com/",
      "titleInlineContent": [
        {
          "text": "https://opensource.apple.com/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://opensource.apple.com/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/title",
          "value": "SecAccessRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAccessRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGenerateSymmetric(_:_:)/title",
          "value": "SecKeyGenerateSymmetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGenerateSymmetric(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGenerateSymmetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/title",
          "value": "uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/title",
          "value": "CSSM_CC_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CC_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CC_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CC_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/title",
          "value": "SecKeychainRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEYUSE/title",
          "value": "CSSM_KEYUSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEYUSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEYUSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_KEYUSE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_KEYUSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ALGORITHMS/title",
          "value": "CSSM_ALGORITHMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ALGORITHMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ALGORITHMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_ALGORITHMS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_ALGORITHMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/title",
          "value": "SecKeyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeygenerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
