{
  "abstract": [
    {
      "text": "Returns a CSSM unique record for the given keychain item object.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "The common security services manager module is no longer used.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecKeychainItemGetUniqueRecordID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeychainItemGetUniqueRecordID",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecKeychainItemGetUniqueRecordID"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeychainItemGetUniqueRecordID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeychainItemGetUniqueRecordID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeychainItemGetUniqueRecordID"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeychainItemRef",
              "text": "SecKeychainItemRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "itemRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_db_unique_record-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_db_unique_record",
              "text": "CSSM_DB_UNIQUE_RECORD"
            },
            {
              "kind": "text",
              "text": " * * "
            },
            {
              "kind": "internalParam",
              "text": "uniqueRecordID"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A keychain item object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "itemRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, a pointer to a CSSM unique record for the given item. The unique record is valid until the item object is released.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "uniqueRecordID"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This function is deprecated.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The common security services manager module is no longer used.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItem": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychainItem"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychainItem"
        }
      ],
      "role": "symbol",
      "title": "SecKeychainItem",
      "type": "topic",
      "url": "/documentation/security/seckeychainitem"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItemGetUniqueRecordID": {
      "abstract": [
        {
          "text": "Returns a CSSM unique record for the given keychain item object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainItemGetUniqueRecordID"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemGetUniqueRecordID",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainItemGetUniqueRecordID",
      "type": "topic",
      "url": "/documentation/security/seckeychainitemgetuniquerecordid"
    },
    "doc://com.apple.security/documentation/Security/cssm_db_unique_record-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_db_unique_record"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_db_unique_record-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_db_unique_record",
      "type": "topic",
      "url": "/documentation/security/cssm_db_unique_record-c.struct"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/title",
          "value": "SecKeychainItemRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainItemRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainItemRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeychainitemgetuniquerecordid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
