{
  "abstract": [
    {
      "text": "Imports one or more certificates, keys, or identities and adds them to a keychain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecKeychainItemImport"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecKeychainItemImport",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecKeychainItemImport"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecKeychainItemImport"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecKeychainItemImport"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecKeychainItemImport"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDataRef",
              "text": "CFDataRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "importedData"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "fileNameOrExtension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecExternalFormat",
              "text": "SecExternalFormat"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inputFormat"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecExternalItemType",
              "text": "SecExternalItemType"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "itemType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemImportExportFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecItemImportExportFlags",
              "text": "SecItemImportExportFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SecKeyImportExportParameters",
              "text": "SecKeyImportExportParameters"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "keyParams"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeychainRef",
              "text": "SecKeychainRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "importKeychain"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArrayRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outItems"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The external representation of the items to import.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importedData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name or extension of the file from which the external representation was obtained. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you don’t know the name or extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fileNameOrExtension"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On entry, points to the format of the external representation. Pass ",
                  "type": "text"
                },
                {
                  "code": "kSecFormatUnknown",
                  "type": "codeVoice"
                },
                {
                  "text": " if you do not know the exact format. On return, points to the format that the function has determined the external representation to be in. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you don’t know the format and don’t want the format returned to you. For a list of formats, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inputFormat"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On entry, points to the item type of the item or items contained in the external representation. Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeUnknown",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " if you do not know the item type. On return, points to the item type that the function has determined the external representation to contain. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you don’t know the item type and don’t want the type returned to you.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "itemType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Unused; pass in ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a structure containing a set of input parameters for the function. If no key items are being imported, these parameters are optional and you can set the ",
                  "type": "text"
                },
                {
                  "code": "keyParams",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter to ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for the ",
                  "type": "text"
                },
                {
                  "code": "importKeychain",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter, the ",
                  "type": "text"
                },
                {
                  "code": "kSecKeyImportOnlyOne",
                  "type": "codeVoice"
                },
                {
                  "text": " bit in the ",
                  "type": "text"
                },
                {
                  "code": "flags",
                  "type": "codeVoice"
                },
                {
                  "text": " field of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure is ignored. Otherwise, if the ",
                  "type": "text"
                },
                {
                  "code": "kSecKeyImportOnlyOne",
                  "type": "codeVoice"
                },
                {
                  "text": " bit is set and there is more than one private key in the incoming external representation, no items are imported to the specified keychain and the error ",
                  "type": "text"
                },
                {
                  "code": "errSecMultiplePrivKeys",
                  "type": "codeVoice"
                },
                {
                  "text": " is returned. The possible values for the ",
                  "type": "text"
                },
                {
                  "code": "flags",
                  "type": "codeVoice"
                },
                {
                  "text": " field are described in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyParams"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A keychain object indicating the keychain to which the key or certificate should be imported. If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the item is not imported. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecKeychainCopyDefault(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to get a reference to the default keychain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importKeychain"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to an array of ",
                  "type": "text"
                },
                {
                  "code": "SecKeychainItemRef",
                  "type": "codeVoice"
                },
                {
                  "text": " objects for the imported items. You must provide a valid pointer to a ",
                  "type": "text"
                },
                {
                  "code": "CFArrayRef",
                  "type": "codeVoice"
                },
                {
                  "text": " object to receive this information. If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for this parameter, the function does not return the imported items. You must call the ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": " function to release this object when you are finished using it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outItems"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you pass this function a ",
              "type": "text"
            },
            {
              "code": "CFDataRef",
              "type": "codeVoice"
            },
            {
              "text": " object containing the external representation of one or more keys, certificates, or identities, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attempts to determine the format and contents of the data. To ensure that this process is successful, you should specify values for one or more of the parameters ",
              "type": "text"
            },
            {
              "code": "fileNameOrExtension",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "inputFormat",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "itemType",
              "type": "codeVoice"
            },
            {
              "text": ". To have the function add the imported items to a keychain, specify a non-",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " value for the ",
              "type": "text"
            },
            {
              "code": "importKeychain",
              "type": "codeVoice"
            },
            {
              "text": " parameter. To have the function return ",
              "type": "text"
            },
            {
              "code": "SecKeychainItemRef",
              "type": "codeVoice"
            },
            {
              "text": " objects for the imported items, specify a non-",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " value for the ",
              "type": "text"
            },
            {
              "code": "outItems",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function determines whether the item is PEM armored by inspecting the data, the ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter is not used in calling this function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After the function returns, you can determine the nature of the keychain items from the values returned in the ",
              "type": "text"
            },
            {
              "code": "inputFormat",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "itemType",
              "type": "codeVoice"
            },
            {
              "text": " parameters. Depending on the nature of each item, once it is imported to a keychain you can safely cast the ",
              "type": "text"
            },
            {
              "code": "SecKeychainItemRef",
              "type": "codeVoice"
            },
            {
              "text": " object to a ",
              "type": "text"
            },
            {
              "code": "SecKeyRef",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "SecCertificateRef",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "SecIdentityRef",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that when you import data in PKCS12 format, typically one ",
              "type": "text"
            },
            {
              "code": "SecIdentityRef",
              "type": "codeVoice"
            },
            {
              "text": " object is returned in the ",
              "type": "text"
            },
            {
              "code": "outItems",
              "type": "codeVoice"
            },
            {
              "text": " parameter. The data might also include one or more ",
              "type": "text"
            },
            {
              "code": "SecCertificateRef",
              "type": "codeVoice"
            },
            {
              "text": " objects. The output data will not include any ",
              "type": "text"
            },
            {
              "code": "SecKeyRef",
              "type": "codeVoice"
            },
            {
              "text": " objects unless the incoming data includes a key with no matching certificate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the output item type is ",
              "type": "text"
            },
            {
              "code": "kSecItemTypeAggregate",
              "type": "codeVoice"
            },
            {
              "text": ", you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to determine the Core Foundation type of each item and the functions in ",
              "type": "text"
            },
            {
              "code": "Getting Information About Keychain Services and Types",
              "type": "codeVoice"
            },
            {
              "text": " to determine the keychain item type of each item. For example, the following code determines whether the item is a certificate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CFTypeID theID = CFGetTypeID(theItem);",
            "if (SecCertificateGetTypeID() == theID)"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can pass in ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " for both ",
              "type": "text"
            },
            {
              "code": "outItems",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "importKeychain",
              "type": "codeVoice"
            },
            {
              "text": " to determine what is inside a given external data representation. When you do, the function returns the input format and the item type without modifying the data in any way.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is deprecated in macOS 10.7 and later; use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid": {
      "abstract": [
        {
          "text": "Returns the unique identifier of an opaque type to which a Core Foundation object belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFGetTypeID"
        },
        {
          "kind": "text",
          "text": "(CFTypeRef!) -> CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFGetTypeID(_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1521218-cfgettypeid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecExternalFormat": {
      "abstract": [
        {
          "text": "The external format of a keychain item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecExternalFormat"
        }
      ],
      "role": "symbol",
      "title": "SecExternalFormat",
      "type": "topic",
      "url": "/documentation/security/secexternalformat"
    },
    "doc://com.apple.security/documentation/Security/SecExternalItemType": {
      "abstract": [
        {
          "text": "The import item type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecExternalItemType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecExternalItemType"
        }
      ],
      "role": "symbol",
      "title": "SecExternalItemType",
      "type": "topic",
      "url": "/documentation/security/secexternalitemtype"
    },
    "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeUnknown": {
      "abstract": [
        {
          "text": "Indicates that the caller does not know the type of information being imported or exported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemTypeUnknown"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecExternalItemType/itemTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecItemTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "SecExternalItemType.itemTypeUnknown",
      "type": "topic",
      "url": "/documentation/security/secexternalitemtype/itemtypeunknown"
    },
    "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Imports one or more certificates, keys, or identities and optionally adds them to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemImport"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecExternalFormat",
          "text": "SecExternalFormat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecExternalItemType",
          "text": "SecExternalItemType"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecItemImportExportFlags",
          "text": "SecItemImportExportFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SecItemImportExportKeyParameters",
          "text": "SecItemImportExportKeyParameters"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeychainRef",
          "text": "SecKeychain"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemImport(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemImport"
        }
      ],
      "role": "symbol",
      "title": "SecItemImport(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secitemimport(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecItemImportExportFlags": {
      "abstract": [
        {
          "text": "The import and export function flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemImportExportFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecItemImportExportFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecItemImportExportFlags"
        }
      ],
      "role": "symbol",
      "title": "SecItemImportExportFlags",
      "type": "topic",
      "url": "/documentation/security/secitemimportexportflags"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportFlags": {
      "abstract": [
        {
          "text": "The import/export parameter structure flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyImportExportFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyImportExportFlags"
        }
      ],
      "role": "symbol",
      "title": "SecKeyImportExportFlags",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportflags"
    },
    "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters": {
      "abstract": [
        {
          "text": "The legacy import/export parameter structure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyImportExportParameters"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyImportExportParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyImportExportParameters"
        }
      ],
      "role": "symbol",
      "title": "SecKeyImportExportParameters",
      "type": "topic",
      "url": "/documentation/security/seckeyimportexportparameters"
    },
    "doc://com.apple.security/documentation/Security/SecKeychain": {
      "abstract": [
        {
          "text": "An opaque type that represents a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychain"
        }
      ],
      "role": "symbol",
      "title": "SecKeychain",
      "type": "topic",
      "url": "/documentation/security/seckeychain"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainCopyDefault(_:)": {
      "abstract": [
        {
          "text": "Retrieves a pointer to the default keychain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeychainCopyDefault"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeychainRef",
          "text": "SecKeychain"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainCopyDefault(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeychainCopyDefault"
        }
      ],
      "role": "symbol",
      "title": "SecKeychainCopyDefault(_:)",
      "type": "topic",
      "url": "/documentation/security/seckeychaincopydefault(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeychainItemImport": {
      "abstract": [
        {
          "text": "Imports one or more certificates, keys, or identities and adds them to a keychain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecKeychainItemImport"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeychainItemImport",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecKeychainItemImport",
      "type": "topic",
      "url": "/documentation/security/seckeychainitemimport"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDataRef": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/title",
          "value": "SecKeychainRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainCopyDefault(_:)/title",
          "value": "SecKeychainCopyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeychainCopyDefault(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeychainCopyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/title",
          "value": "SecKeyImportExportParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/title",
          "value": "SecExternalItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportFlags/title",
          "value": "SecItemImportExportFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImportExportFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImportExportFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImportExportFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportFlags/title",
          "value": "SecKeyImportExportFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyImportExportFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyImportExportFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/title",
          "value": "SecExternalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecExternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType~1itemTypeUnknown/title",
          "value": "kSecItemTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecExternalItemType~1itemTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecItemTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImport(_:_:_:_:_:_:_:_:)/title",
          "value": "SecItemImport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecItemImport(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecItemImport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11521218-cfgettypeid/title",
          "value": "CFGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/seckeychainitemimport"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
