{
  "abstract": [
    {
      "text": "The protocol type associated with an Internet password.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecProtocolType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecProtocolType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecProtocolType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecProtocolType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecProtocolType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecProtocolType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType": {
      "abstract": [
        {
          "text": "The protocol type associated with an Internet password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecProtocolType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecProtocolType"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/AFP": {
      "abstract": [
        {
          "text": "Indicates AFP over TCP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AFP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/AFP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeAFP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.AFP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/afp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/CIFS": {
      "abstract": [
        {
          "text": "Indicates CIFS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CIFS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/CIFS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeCIFS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.CIFS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/cifs"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/DAAP": {
      "abstract": [
        {
          "text": "Indicates DAAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DAAP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/DAAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeDAAP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.DAAP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/daap"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/EPPC": {
      "abstract": [
        {
          "text": "Indicates Remote Apple Events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPPC"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/EPPC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeEPPC"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.EPPC",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/eppc"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/FTP": {
      "abstract": [
        {
          "text": "Indicates FTP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FTP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/FTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeFTP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.FTP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ftp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/FTPS": {
      "abstract": [
        {
          "text": "Indicates FTP over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FTPS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/FTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeFTPS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.FTPS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ftps"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/HTTP": {
      "abstract": [
        {
          "text": "Indicates HTTP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HTTP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/HTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeHTTP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.HTTP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/http"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/HTTPS": {
      "abstract": [
        {
          "text": "Indicates HTTP over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HTTPS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/HTTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeHTTPS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.HTTPS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/https"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/IMAP": {
      "abstract": [
        {
          "text": "Indicates IMAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/IMAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeIMAP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.IMAP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/imap"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/IMAPS": {
      "abstract": [
        {
          "text": "Indicates IMAP4 over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAPS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/IMAPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeIMAPS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.IMAPS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/imaps"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/IPP": {
      "abstract": [
        {
          "text": "Indicates IPP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IPP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/IPP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeIPP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.IPP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ipp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/IRC": {
      "abstract": [
        {
          "text": "Indicates IRC.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IRC"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/IRC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeIRC"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.IRC",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/irc"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/IRCS": {
      "abstract": [
        {
          "text": "Indicates IRC over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IRCS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/IRCS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeIRCS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.IRCS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ircs"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/LDAP": {
      "abstract": [
        {
          "text": "Indicates LDAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LDAP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/LDAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeLDAP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.LDAP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ldap"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/LDAPS": {
      "abstract": [
        {
          "text": "Indicates LDAP over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LDAPS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/LDAPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeLDAPS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.LDAPS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ldaps"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/NNTP": {
      "abstract": [
        {
          "text": "Indicates NNTP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NNTP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/NNTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeNNTP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.NNTP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/nntp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/NNTPS": {
      "abstract": [
        {
          "text": "Indicates NNTP over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NNTPS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/NNTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeNNTPS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.NNTPS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/nntps"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/POP3": {
      "abstract": [
        {
          "text": "Indicates POP3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "POP3"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/POP3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypePOP3"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.POP3",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/pop3"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/POP3S": {
      "abstract": [
        {
          "text": "Indicates POP3 over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "POP3S"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/POP3S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypePOP3S"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.POP3S",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/pop3s"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/RTSP": {
      "abstract": [
        {
          "text": "Indicates RTSP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RTSP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/RTSP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeRTSP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.RTSP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/rtsp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/SMB": {
      "abstract": [
        {
          "text": "Indicates SMB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMB"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/SMB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeSMB"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.SMB",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/smb"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/SMTP": {
      "abstract": [
        {
          "text": "Indicates SMTP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMTP"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/SMTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeSMTP"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.SMTP",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/smtp"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/SOCKS": {
      "abstract": [
        {
          "text": "Indicates SOCKS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SOCKS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/SOCKS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeSOCKS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.SOCKS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/socks"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/SSH": {
      "abstract": [
        {
          "text": "Indicates SSH.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSH"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/SSH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeSSH"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.SSH",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ssh"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/SVN": {
      "abstract": [
        {
          "text": "Indicates Subversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SVN"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/SVN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeSVN"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.SVN",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/svn"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/any": {
      "abstract": [
        {
          "text": "Indicates that any protocol is acceptable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeAny"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.any",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/any"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/appleTalk": {
      "abstract": [
        {
          "text": "Indicates AFP over AppleTalk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleTalk"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/appleTalk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeAppleTalk"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.appleTalk",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/appletalk"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/cvSpserver": {
      "abstract": [
        {
          "text": "Indicates CVS pserver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cvSpserver"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/cvSpserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeCVSpserver"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.cvSpserver",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/cvspserver"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/ftpAccount": {
      "abstract": [
        {
          "text": "Indicates a client side FTP account. The usage of this constant is deprecated as of macOS 10.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ftpAccount"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/ftpAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeFTPAccount"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.ftpAccount",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ftpaccount"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/ftpProxy": {
      "abstract": [
        {
          "text": "Indicates FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ftpProxy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/ftpProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeFTPProxy"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.ftpProxy",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/ftpproxy"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/httpProxy": {
      "abstract": [
        {
          "text": "Indicates HTTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpProxy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/httpProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.httpProxy",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/httpproxy"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/httpsProxy": {
      "abstract": [
        {
          "text": "Indicates HTTPS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpsProxy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/httpsProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeHTTPSProxy"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.httpsProxy",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/httpsproxy"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FourCharCode",
          "text": "FourCharCode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/rtspProxy": {
      "abstract": [
        {
          "text": "Indicates RTSP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rtspProxy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/rtspProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeRTSPProxy"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.rtspProxy",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/rtspproxy"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/telnet": {
      "abstract": [
        {
          "text": "Indicates Telnet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telnet"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/telnet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeTelnet"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.telnet",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/telnet"
    },
    "doc://com.apple.security/documentation/Security/SecProtocolType/telnetS": {
      "abstract": [
        {
          "text": "Indicates Telnet over TLS/SSL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telnetS"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecProtocolType/telnetS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecProtocolTypeTelnetS"
        }
      ],
      "role": "symbol",
      "title": "SecProtocolType.telnetS",
      "type": "topic",
      "url": "/documentation/security/secprotocoltype/telnets"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecProtocolType/FTP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/ftpAccount",
        "doc://com.apple.security/documentation/Security/SecProtocolType/HTTP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/IRC",
        "doc://com.apple.security/documentation/Security/SecProtocolType/NNTP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/POP3",
        "doc://com.apple.security/documentation/Security/SecProtocolType/SMTP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/SOCKS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/IMAP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/LDAP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/appleTalk",
        "doc://com.apple.security/documentation/Security/SecProtocolType/AFP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/telnet",
        "doc://com.apple.security/documentation/Security/SecProtocolType/SSH",
        "doc://com.apple.security/documentation/Security/SecProtocolType/FTPS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/HTTPS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/httpProxy",
        "doc://com.apple.security/documentation/Security/SecProtocolType/httpsProxy",
        "doc://com.apple.security/documentation/Security/SecProtocolType/ftpProxy",
        "doc://com.apple.security/documentation/Security/SecProtocolType/CIFS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/SMB",
        "doc://com.apple.security/documentation/Security/SecProtocolType/RTSP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/rtspProxy",
        "doc://com.apple.security/documentation/Security/SecProtocolType/DAAP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/EPPC",
        "doc://com.apple.security/documentation/Security/SecProtocolType/IPP",
        "doc://com.apple.security/documentation/Security/SecProtocolType/NNTPS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/LDAPS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/telnetS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/IMAPS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/IRCS",
        "doc://com.apple.security/documentation/Security/SecProtocolType/POP3S",
        "doc://com.apple.security/documentation/Security/SecProtocolType/cvSpserver",
        "doc://com.apple.security/documentation/Security/SecProtocolType/SVN",
        "doc://com.apple.security/documentation/Security/SecProtocolType/any"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecProtocolType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecProtocolType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecProtocolType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecProtocolType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecProtocolType/FTP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/ftpAccount",
                "doc://com.apple.security/documentation/Security/SecProtocolType/HTTP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/IRC",
                "doc://com.apple.security/documentation/Security/SecProtocolType/NNTP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/POP3",
                "doc://com.apple.security/documentation/Security/SecProtocolType/SMTP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/SOCKS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/IMAP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/LDAP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/appleTalk",
                "doc://com.apple.security/documentation/Security/SecProtocolType/AFP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/telnet",
                "doc://com.apple.security/documentation/Security/SecProtocolType/SSH",
                "doc://com.apple.security/documentation/Security/SecProtocolType/FTPS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/HTTPS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/httpProxy",
                "doc://com.apple.security/documentation/Security/SecProtocolType/httpsProxy",
                "doc://com.apple.security/documentation/Security/SecProtocolType/ftpProxy",
                "doc://com.apple.security/documentation/Security/SecProtocolType/CIFS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/SMB",
                "doc://com.apple.security/documentation/Security/SecProtocolType/RTSP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/rtspProxy",
                "doc://com.apple.security/documentation/Security/SecProtocolType/DAAP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/EPPC",
                "doc://com.apple.security/documentation/Security/SecProtocolType/IPP",
                "doc://com.apple.security/documentation/Security/SecProtocolType/NNTPS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/LDAPS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/telnetS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/IMAPS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/IRCS",
                "doc://com.apple.security/documentation/Security/SecProtocolType/POP3S",
                "doc://com.apple.security/documentation/Security/SecProtocolType/cvSpserver",
                "doc://com.apple.security/documentation/Security/SecProtocolType/SVN",
                "doc://com.apple.security/documentation/Security/SecProtocolType/any"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecProtocolType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1HTTP/title",
          "value": "kSecProtocolTypeHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1HTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IRCS/title",
          "value": "kSecProtocolTypeIRCS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IRCS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeIRCS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1httpsProxy/title",
          "value": "kSecProtocolTypeHTTPSProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1httpsProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeHTTPSProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1telnetS/title",
          "value": "kSecProtocolTypeTelnetS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1telnetS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeTelnetS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SMTP/title",
          "value": "kSecProtocolTypeSMTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SMTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeSMTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IMAP/title",
          "value": "kSecProtocolTypeIMAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IMAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeIMAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1appleTalk/title",
          "value": "kSecProtocolTypeAppleTalk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1appleTalk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeAppleTalk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1ftpAccount/title",
          "value": "kSecProtocolTypeFTPAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1ftpAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeFTPAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1rtspProxy/title",
          "value": "kSecProtocolTypeRTSPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1rtspProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeRTSPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1NNTP/title",
          "value": "kSecProtocolTypeNNTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1NNTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeNNTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IMAPS/title",
          "value": "kSecProtocolTypeIMAPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IMAPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeIMAPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SSH/title",
          "value": "kSecProtocolTypeSSH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SSH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeSSH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1httpProxy/title",
          "value": "kSecProtocolTypeHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1httpProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1POP3/title",
          "value": "kSecProtocolTypePOP3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1POP3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypePOP3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1FTP/title",
          "value": "kSecProtocolTypeFTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1FTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeFTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SVN/title",
          "value": "kSecProtocolTypeSVN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SVN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeSVN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1LDAP/title",
          "value": "kSecProtocolTypeLDAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1LDAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeLDAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1FTPS/title",
          "value": "kSecProtocolTypeFTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1FTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeFTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1telnet/title",
          "value": "kSecProtocolTypeTelnet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1telnet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeTelnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1cvSpserver/title",
          "value": "kSecProtocolTypeCVSpserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1cvSpserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeCVSpserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IRC/title",
          "value": "kSecProtocolTypeIRC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IRC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeIRC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType/title",
          "value": "SecProtocolType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecProtocolType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecProtocolType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1AFP/title",
          "value": "kSecProtocolTypeAFP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1AFP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeAFP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1RTSP/title",
          "value": "kSecProtocolTypeRTSP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1RTSP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeRTSP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1HTTPS/title",
          "value": "kSecProtocolTypeHTTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1HTTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeHTTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SMB/title",
          "value": "kSecProtocolTypeSMB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SMB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeSMB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1POP3S/title",
          "value": "kSecProtocolTypePOP3S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1POP3S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypePOP3S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1CIFS/title",
          "value": "kSecProtocolTypeCIFS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1CIFS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeCIFS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1any/title",
          "value": "kSecProtocolTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1NNTPS/title",
          "value": "kSecProtocolTypeNNTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1NNTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeNNTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1ftpProxy/title",
          "value": "kSecProtocolTypeFTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1ftpProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeFTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1EPPC/title",
          "value": "kSecProtocolTypeEPPC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1EPPC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeEPPC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SOCKS/title",
          "value": "kSecProtocolTypeSOCKS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1SOCKS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeSOCKS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1DAAP/title",
          "value": "kSecProtocolTypeDAAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1DAAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeDAAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1LDAPS/title",
          "value": "kSecProtocolTypeLDAPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1LDAPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeLDAPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IPP/title",
          "value": "kSecProtocolTypeIPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecProtocolType~1IPP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecProtocolTypeIPP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secprotocoltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secprotocoltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
