{
  "abstract": [
    {
      "text": "Creates a search object for finding policies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecPolicySearchCreate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecPolicySearchCreate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecPolicySearchCreate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecPolicySearchCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecPolicySearchCreate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecPolicySearchCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CERT_TYPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CERT_TYPE",
              "text": "CSSM_CERT_TYPE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "certType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_data",
              "text": "SecAsn1Oid"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "policyOID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cssm_data",
              "text": "SecAsn1Item"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicySearch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecPolicySearchRef",
              "text": "SecPolicySearchRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "searchRef"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of certificates a policy uses, as defined in ",
                  "type": "text"
                },
                {
                  "code": "Security.framework/cssmtype.h",
                  "type": "codeVoice"
                },
                {
                  "text": ". Permissible values are ",
                  "type": "text"
                },
                {
                  "code": "CSSM_CERT_X_509v1",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "CSSM_CERT_X_509v2",
                  "type": "codeVoice"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "code": "CSSM_CERT_X_509v3",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you are unsure of the certificate type, use ",
                  "type": "text"
                },
                {
                  "code": "CSSM_CERT_X_509v3",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "certType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a BER-encoded policy object identifier that uniquely specifies the policy. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a list of policies and object identifiers provided by the AppleX509TP module.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "policyOID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an optional, policy-defined value. The contents of this value depend on the policy object identifier specified. (Note that this parameter refers to the value stored in MDS and is not related to the ",
                  "type": "text"
                },
                {
                  "code": "value",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecPolicyGetValue",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.) Currently the function does not use this parameter; pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for this pointer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the newly created policy search object. In Objective-C, call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to release this object when you are finished with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "searchRef"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use the search object created by this function in subsequent calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicySearchCopyNext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to obtain trust policy objects. Policies are stored in the Module Directory Services (MDS) database. MDS is described in detail in “Part 8: Module Directory Service (MDS)” of ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Common Security: CDSA and CSSM, version 2 (with corrigenda)",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " from The Open Group (",
              "type": "text"
            },
            {
              "identifier": "http://www.opengroup.org/security/cdsa.htm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CERT_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CERT_TYPE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CERT_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CERT_TYPE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CERT_TYPE",
      "type": "topic",
      "url": "/documentation/security/cssm_cert_type"
    },
    "doc://com.apple.security/documentation/Security/SecPolicyGetValue": {
      "abstract": [
        {
          "text": "Retrieves a policy’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicyGetValue"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicyGetValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicyGetValue",
      "type": "topic",
      "url": "/documentation/security/secpolicygetvalue"
    },
    "doc://com.apple.security/documentation/Security/SecPolicySearch": {
      "abstract": [
        {
          "text": "An object that contains information about a policy search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecPolicySearch"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicySearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecPolicySearch"
        }
      ],
      "role": "symbol",
      "title": "SecPolicySearch",
      "type": "topic",
      "url": "/documentation/security/secpolicysearch"
    },
    "doc://com.apple.security/documentation/Security/SecPolicySearchCopyNext": {
      "abstract": [
        {
          "text": "Retrieves a policy object for the next policy matching specified search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicySearchCopyNext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicySearchCopyNext",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicySearchCopyNext",
      "type": "topic",
      "url": "/documentation/security/secpolicysearchcopynext"
    },
    "doc://com.apple.security/documentation/Security/SecPolicySearchCreate": {
      "abstract": [
        {
          "text": "Creates a search object for finding policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicySearchCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicySearchCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicySearchCreate",
      "type": "topic",
      "url": "/documentation/security/secpolicysearchcreate"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/cssm_data-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_data-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_data"
        }
      ],
      "role": "symbol",
      "title": "cssm_data",
      "type": "topic",
      "url": "/documentation/security/cssm_data-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "http://www.opengroup.org/security/cdsa.htm": {
      "identifier": "http://www.opengroup.org/security/cdsa.htm",
      "title": "http://www.opengroup.org/security/cdsa.htm",
      "titleInlineContent": [
        {
          "text": "http://www.opengroup.org/security/cdsa.htm",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.opengroup.org/security/cdsa.htm"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CERT_TYPE/title",
          "value": "CSSM_CERT_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CERT_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CERT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CERT_TYPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CERT_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/title",
          "value": "cssm_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_data-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicySearch/title",
          "value": "SecPolicySearchRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicySearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicySearchRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicySearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicySearchRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secpolicysearchcreate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
