{
  "abstract": [
    {
      "text": "Retrieves the trust policy handle for a policy object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecPolicyGetTPHandle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecPolicyGetTPHandle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecPolicyGetTPHandle"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecPolicyGetTPHandle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecPolicyGetTPHandle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecPolicyGetTPHandle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecPolicyRef",
              "text": "SecPolicyRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "policyRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_TP_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_TP_HANDLE",
              "text": "CSSM_TP_HANDLE"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "tpHandle"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The policy object from which to obtain the trust policy handle.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "policyRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to the policy object’s trust policy handle. The handle remains valid until the policy object is released.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tpHandle"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The trust policy handle is the CSSM identifier of the trust policy module that is managing the certificate. The trust policy handle is uses as an input to a number of CSSM functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_TP_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_TP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_TP_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_TP_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_TP_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_tp_handle"
    },
    "doc://com.apple.security/documentation/Security/SecPolicy": {
      "abstract": [
        {
          "text": "An object that represents a trust policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecPolicy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecPolicy"
        }
      ],
      "role": "symbol",
      "title": "SecPolicy",
      "type": "topic",
      "url": "/documentation/security/secpolicy"
    },
    "doc://com.apple.security/documentation/Security/SecPolicyGetTPHandle": {
      "abstract": [
        {
          "text": "Retrieves the trust policy handle for a policy object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicyGetTPHandle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicyGetTPHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicyGetTPHandle",
      "type": "topic",
      "url": "/documentation/security/secpolicygettphandle"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/title",
          "value": "SecPolicyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_TP_HANDLE/title",
          "value": "CSSM_TP_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_TP_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_TP_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_TP_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_TP_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secpolicygettphandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
