{
  "abstract": [
    {
      "text": "Sets properties for a policy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SecPolicySetProperties"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecPolicySetProperties",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SecPolicySetProperties"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecPolicySetProperties"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecPolicySetProperties"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecPolicySetProperties"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecPolicyRef",
              "text": "SecPolicyRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "policyRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionaryRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "properties"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The policy to alter",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "policyRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "CFDictionaryRef",
                  "type": "codeVoice"
                },
                {
                  "text": " object containing the new set of properties. For a list of valid property keys, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/security-policy-keys",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The property ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyOid",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is read-only and thus cannot be changed by this function.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "name": "Note",
              "style": "note",
              "type": "aside"
            }
          ],
          "name": "properties"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecPolicy": {
      "abstract": [
        {
          "text": "An object that represents a trust policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecPolicy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecPolicy"
        }
      ],
      "role": "symbol",
      "title": "SecPolicy",
      "type": "topic",
      "url": "/documentation/security/secpolicy"
    },
    "doc://com.apple.security/documentation/Security/SecPolicySetProperties": {
      "abstract": [
        {
          "text": "Sets properties for a policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicySetProperties"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicySetProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicySetProperties",
      "type": "topic",
      "url": "/documentation/security/secpolicysetproperties"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyOid": {
      "abstract": [
        {
          "text": "The object identifier that defines the policy type (",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": "). All policies have a value for this key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyOid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyOid"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyOid",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyoid"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.apple.security/documentation/Security/security-policy-keys": {
      "abstract": [
        {
          "text": "Use these dictionary keys to get and set policy properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-policy-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Policy Keys",
      "type": "topic",
      "url": "/documentation/security/security-policy-keys"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/title",
          "value": "SecPolicyRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyOid/title",
          "value": "kSecPolicyOid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyOid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyOid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secpolicysetproperties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
