{
  "abstract": [
    {
      "text": "An enumeration indicating different types of internal requirements for code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecRequirementType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecRequirementType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecRequirementType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecRequirementType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecRequirementType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecRequirementType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are indexes into requirement sets and are not currently used in any public API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType": {
      "abstract": [
        {
          "text": "An enumeration indicating different types of internal requirements for code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/designatedRequirementType": {
      "abstract": [
        {
          "text": "A designated requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "designatedRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/designatedRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecDesignatedRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.designatedRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/designatedrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/guestRequirementType": {
      "abstract": [
        {
          "text": "What guests this code may run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guestRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/guestRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecGuestRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.guestRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/guestrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/hostRequirementType": {
      "abstract": [
        {
          "text": "What hosts may run this code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/hostRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecHostRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.hostRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/hostrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/invalidRequirementType": {
      "abstract": [
        {
          "text": "Invalid type of requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/invalidRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecInvalidRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.invalidRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/invalidrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/libraryRequirementType": {
      "abstract": [
        {
          "text": "What libraries this code may link against.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/libraryRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecLibraryRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.libraryRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/libraryrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/pluginRequirementType": {
      "abstract": [
        {
          "text": "What plug-ins this code may load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pluginRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/pluginRequirementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPluginRequirementType"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementType.pluginRequirementType",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/pluginrequirementtype"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementType/requirementTypeCount": {
      "abstract": [
        {
          "text": "The number of valid requirement types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requirementTypeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecRequirementType",
          "text": "SecRequirementType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementType/requirementTypeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecRequirementTypeCount"
        }
      ],
      "role": "symbol",
      "title": "requirementTypeCount",
      "type": "topic",
      "url": "/documentation/security/secrequirementtype/requirementtypecount"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecRequirementType/hostRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/guestRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/designatedRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/libraryRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/pluginRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/invalidRequirementType",
        "doc://com.apple.security/documentation/Security/SecRequirementType/requirementTypeCount"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecRequirementType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecRequirementType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecRequirementType/hostRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/guestRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/designatedRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/libraryRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/pluginRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/invalidRequirementType",
                "doc://com.apple.security/documentation/Security/SecRequirementType/requirementTypeCount"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecRequirementType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1invalidRequirementType/title",
          "value": "kSecInvalidRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1invalidRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecInvalidRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1requirementTypeCount/title",
          "value": "kSecRequirementTypeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1requirementTypeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecRequirementTypeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1libraryRequirementType/title",
          "value": "kSecLibraryRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1libraryRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecLibraryRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType/title",
          "value": "SecRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1hostRequirementType/title",
          "value": "kSecHostRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1hostRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecHostRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1designatedRequirementType/title",
          "value": "kSecDesignatedRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1designatedRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecDesignatedRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1guestRequirementType/title",
          "value": "kSecGuestRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1guestRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecGuestRequirementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1pluginRequirementType/title",
          "value": "kSecPluginRequirementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementType~1pluginRequirementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPluginRequirementType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secrequirementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secrequirementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
