{
  "abstract": [
    {
      "text": "Returns the unique identifier of the opaque type to which a code requirement object belongs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecRequirementGetTypeID()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecRequirementGetTypeID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecRequirementGetTypeID"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeID",
        "text": "CFTypeID"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecRequirementGetTypeID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecRequirementGetTypeID()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecRequirementGetTypeID"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeID",
              "text": "CFTypeID"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A value that identifies the opaque type of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecRequirement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can compare the value returned by this function to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cftypeid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " identifier obtained by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function on a specific object. These values might change from release to release or platform to platform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid": {
      "abstract": [
        {
          "text": "Returns the unique identifier of an opaque type to which a Core Foundation object belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFGetTypeID"
        },
        {
          "kind": "text",
          "text": "(CFTypeRef!) -> CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521218-cfgettypeid",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFGetTypeID(_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1521218-cfgettypeid"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cftypeid": {
      "abstract": [
        {
          "text": "A type for unique, constant integer values that identify particular Core Foundation opaque types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cftypeid",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeID",
      "type": "topic",
      "url": "/documentation/corefoundation/cftypeid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecRequirement": {
      "abstract": [
        {
          "text": "A code requirement object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequirement"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequirement"
        }
      ],
      "role": "symbol",
      "title": "SecRequirement",
      "type": "topic",
      "url": "/documentation/security/secrequirement"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementCreateWithString(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a code requirement object by compiling a valid text representation of a code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequirementCreateWithString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecRequirementRef",
          "text": "SecRequirement"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementCreateWithString(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequirementCreateWithString"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementCreateWithString(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secrequirementcreatewithstring(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementCreateWithStringAndErrors(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a code requirement object by compiling a valid text representation of a code requirement and returns detailed error information in the case of failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequirementCreateWithStringAndErrors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecRequirementRef",
          "text": "SecRequirement"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementCreateWithStringAndErrors(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequirementCreateWithStringAndErrors"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementCreateWithStringAndErrors(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secrequirementcreatewithstringanderrors(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecRequirementGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the unique identifier of the opaque type to which a code requirement object belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequirementGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequirementGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequirementGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "SecRequirementGetTypeID()",
      "type": "topic",
      "url": "/documentation/security/secrequirementgettypeid()"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeID": {
      "abstract": [
        {
          "text": "A type for unique, constant integer values that identify particular Core Foundation opaque types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeID",
      "type": "topic",
      "url": "/documentation/corefoundation/cftypeid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecRequirementCreateWithString(_:_:_:)",
        "doc://com.apple.security/documentation/Security/SecRequirementCreateWithStringAndErrors(_:_:_:_:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecRequirementGetTypeID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecRequirementCreateWithString(_:_:_:)",
                "doc://com.apple.security/documentation/Security/SecRequirementCreateWithStringAndErrors(_:_:_:_:)"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeID",
                    "text": "CFTypeID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecRequirementGetTypeID"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A value that identifies the opaque type of a ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecRequirement",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementCreateWithString(_:_:_:)/title",
          "value": "SecRequirementCreateWithString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementCreateWithString(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementCreateWithString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11521218-cfgettypeid/title",
          "value": "CFGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementCreateWithStringAndErrors(_:_:_:_:)/title",
          "value": "SecRequirementCreateWithStringAndErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementCreateWithStringAndErrors(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementCreateWithStringAndErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementGetTypeID()/title",
          "value": "SecRequirementGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirementGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirement/title",
          "value": "SecRequirementRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequirement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequirementRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secrequirementgettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/secrequirementgettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
