{
  "abstract": [
    {
      "text": "Evaluates trust for the specified certificate and policies.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateWithError(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecTrustEvaluate(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecTrustEvaluate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecTrustEvaluate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecTrustRef",
        "text": "SecTrust"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SecTrustResultType",
        "text": "SecTrustResultType"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecTrustEvaluate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.3",
        "name": "macOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "2.0",
        "name": "tvOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "1.0",
        "name": "watchOS",
        "renamed": "SecTrustEvaluateWithError(_:_:)",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecTrustEvaluate(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecTrustEvaluate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "trust"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecTrustRef",
              "text": "SecTrust"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecTrustResultType",
              "text": "SecTrustResultType"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The trust management object to evaluate. A trust management object includes the certificate to be verified plus the policy or policies to be used in evaluating trust. It can optionally also include other certificates to be used in verifying the first certificate. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecTrustCreateWithCertificates(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function to create a trust management object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "trust"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, points to a result type reflecting the result of this evaluation. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for descriptions of possible values. See the discussion below for an explanation of how to handle specific values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "result"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function evaluates a certificate’s validity to establish trust for a particular use—for example, in creating a digital signature or to establish a Secure Sockets Layer connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you call this function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetVerifyDate(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function before calling ",
                      "type": "text"
                    },
                    {
                      "code": "SecTrustEvaluate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to set the date and time to use when verifying the certificate. By default, ",
                      "type": "text"
                    },
                    {
                      "code": "SecTrustEvaluate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " uses the current date and time. (Note that some APIs such as CMS may set the verification date for you based on a trusted time stamp.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In macOS, you can optionally call any of the ",
                      "type": "text"
                    },
                    {
                      "code": "SecTrustSet...",
                      "type": "codeVoice"
                    },
                    {
                      "text": " functions (such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetParameters",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetVerifyDate(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ") to set values for parameters and options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "SecTrustEvaluate",
              "type": "codeVoice"
            },
            {
              "text": " function validates a certificate by verifying its signature plus the signatures of the certificates in its certificate chain, up to the anchor certificate, according to the policy or policies included in the trust management object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For each policy, the function usually evaluates trust according to the user-specified trust setting (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustSettingsSetTrustSettings(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustSettingsCopyTrustSettings(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). For an example of user-specified trust settings, use the Keychain Access utility and look at any certificate. As an exception, if your app has previously called ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetAnchorCertificates(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the user-specified trust settings are ignored, and the certificate’s chain must contain one of the specified anchor certificates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For each policy, ",
              "type": "text"
            },
            {
              "code": "SecTrustEvaluate",
              "type": "codeVoice"
            },
            {
              "text": " constructs a certificate chain based on the policies requested. It then starts with the leaf certificate and checks each certificate in the chain in turn until it either reaches a defective certificate, runs out of certificates, or reaches a certificate with a non-default trust setting—usually an anchor certificate or a certificate that the user has explicitly chosen to trust or distrust—and stores the result of this trust evaluation in the trust management object. This design means that an explicit user-trust setting for a certificate at or near the leaf can override the behavior of a certificate closer to the root, but otherwise a failure at any point in the chain results in a failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If some of the certificates needed to verify the leaf certificate are missing from the trust management object, then ",
              "type": "text"
            },
            {
              "code": "SecTrustEvaluate",
              "type": "codeVoice"
            },
            {
              "text": " searches for certificates in the following locations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In any keychains currently on the caller’s keychain search list (see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetKeychains(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ").",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Any certificates previously provided by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetAnchorCertificates(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In a system-provided set of keychains provided for this purpose.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Over the network if certain extensions are present in the certificate used to build the chain.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Although this function searches the user’s keychain (or the application keychain in iOS) for intermediate certificates, it does not search those keychains for anchor (root) certificates. To add an anchor certificate, you must call ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetAnchorCertificates(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "As a rule, you should handle the various return values as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/unspecified",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—Evaluation successfully reached an (implicitly trusted) anchor certificate without any evaluation failures, but never encountered any explicitly stated user-trust preference. This is the most common return value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Most apps should, by default, trust the chain. If you ask the user what to do, in macOS, you should use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface/SFCertificateTrustPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/proceed",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—The user explicitly chose to trust a certificate in the chain (usually by clicking a button in a certificate trust panel).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your app should trust the chain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/deny",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—The user explicitly chose to ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "not",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " trust a certificate in the chain (usually by clicking the appropriate button in a certificate trust panel).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your app should ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "not",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " trust the chain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/confirm",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—The user previously chose to always ask for permission before accepting one of the certificates in the chain. This return value is no longer used, but may occur in older versions of macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Either ask the user what to do or reject the certificate. If you ask the user what to do, in macOS, you should use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface/SFCertificateTrustPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/recoverableTrustFailure",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—This means that you should not trust the chain as-is, but that the chain could be trusted with some minor change to the evaluation context, such as ignoring expired certificates or adding an additional anchor to the set of trusted anchors.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The way you handle this depends on the OS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS, you should typically refuse the certificate. However, if you are performing signature validation and you know when the message was originally received, you should check again using that date to see if the message was valid when you originally received it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, you can call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to get more information about the results of the trust evaluation, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustGetCssmResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to get information about the evaluation in a form that can be passed to CSSM functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Then, as appropriate, you can call one or more of the ",
              "type": "text"
            },
            {
              "code": "SecTrustSet...",
              "type": "codeVoice"
            },
            {
              "text": " functions to correct or bypass the problem, or you can inform the user of the problem and call the ",
              "type": "text"
            },
            {
              "code": "SFCertificateTrustPanel",
              "type": "codeVoice"
            },
            {
              "text": " class to let the user change the trust setting for the certificate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you think you have corrected the problem, call ",
              "type": "text"
            },
            {
              "code": "SecTrustEvaluate",
              "type": "codeVoice"
            },
            {
              "text": " again. Each time you call ",
              "type": "text"
            },
            {
              "code": "SecTrustEvaluate",
              "type": "codeVoice"
            },
            {
              "text": ", it discards the results of any previous evaluation and replaces them with the new results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the trust failure was caused by an untrusted root certificate and your app asks the user what to do, you should use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface/SFCertificateTrustPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/fatalTrustFailure",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—Evaluation failed because a certificate in the chain is defective. This usually represents a fundamental defect in the certificate data, such as an invalid encoding for a critical ",
                      "type": "text"
                    },
                    {
                      "code": "subjectAltName",
                      "type": "codeVoice"
                    },
                    {
                      "text": " extension, an unsupported critical extension, or some other critical portion of the certificate that could not be successfully interpreted. Changing parameter values and calling ",
                      "type": "text"
                    },
                    {
                      "code": "SecTrustEvaluate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " again is unlikely to result in a successful reevaluation unless you provide different certificates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/otherError",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "—Evaluation failed for some other reason. This can be caused by either a revoked certificate or by OS-level errors that are unrelated to the certificates themselves.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It is not safe to call this function concurrently with any other function that uses the same trust management object, or to re-enter this function for the same trust management object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because this function might look on the network for certificates in the certificate chain, the function might block while attempting network access. You should never call it from your main thread; call it only from within a function running on a dispatch queue or on a separate thread. Alternatively, in macOS, you can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsync(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from your main thread. In iOS, you can do the same thing using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/dispatch/1447169-dispatch_once",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/SecurityInterface"
    },
    "doc://com.apple.documentation/documentation/SecurityInterface/SFCertificateTrustPanel": {
      "abstract": [
        {
          "text": "A panel or sheet that lets the user edit the trust settings in any of the certificates in a certificate chain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificateTrustPanel"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SecurityInterface/SFCertificateTrustPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFCertificateTrustPanel",
      "type": "topic",
      "url": "/documentation/SecurityInterface/SFCertificateTrustPanel"
    },
    "doc://com.apple.documentation/documentation/dispatch/1447169-dispatch_once": {
      "abstract": [
        {
          "text": "Executes a block object only once for the lifetime of an application.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/dispatch/1447169-dispatch_once",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_once",
      "type": "topic",
      "url": "/documentation/dispatch/1447169-dispatch_once"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecTrust": {
      "abstract": [
        {
          "text": "An object used to evaluate trust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "role": "symbol",
      "title": "SecTrust",
      "type": "topic",
      "url": "/documentation/security/sectrust"
    },
    "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing information about an evaluated trust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustCopyResult"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustCopyResult"
        }
      ],
      "role": "symbol",
      "title": "SecTrustCopyResult(_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustcopyresult(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustCreateWithCertificates(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a trust management object based on certificates and policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustCreateWithCertificates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustCreateWithCertificates(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustCreateWithCertificates"
        }
      ],
      "role": "symbol",
      "title": "SecTrustCreateWithCertificates(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustcreatewithcertificates(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustEvaluate(_:_:)": {
      "abstract": [
        {
          "text": "Evaluates trust for the specified certificate and policies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustEvaluate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTrustResultType",
          "text": "SecTrustResultType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustEvaluate"
        }
      ],
      "role": "symbol",
      "title": "SecTrustEvaluate(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustevaluate(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsync(_:_:_:)": {
      "abstract": [
        {
          "text": "Evaluates a trust object asynchronously on the specified dispatch queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustCallback",
          "text": "SecTrustCallback"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateAsync(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateAsync"
        }
      ],
      "role": "symbol",
      "title": "SecTrustEvaluateAsync(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustevaluateasync(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustEvaluateWithError(_:_:)": {
      "abstract": [
        {
          "text": "Evaluates trust for the specified certificate and policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateWithError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateWithError(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustEvaluateWithError"
        }
      ],
      "role": "symbol",
      "title": "SecTrustEvaluateWithError(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustevaluatewitherror(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustGetCssmResult": {
      "abstract": [
        {
          "text": "Retrieves the CSSM trust result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecTrustGetCssmResult"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustGetCssmResult",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecTrustGetCssmResult",
      "type": "topic",
      "url": "/documentation/security/sectrustgetcssmresult"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType": {
      "abstract": [
        {
          "text": "Trust evaluation result codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustResultType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustResultType"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/confirm": {
      "abstract": [
        {
          "text": "User confirmation is required before proceeding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/confirm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultConfirm"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.confirm",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/confirm"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/deny": {
      "abstract": [
        {
          "text": "The user specified that the certificate should not be trusted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deny"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/deny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultDeny"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.deny",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/deny"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/fatalTrustFailure": {
      "abstract": [
        {
          "text": "Trust is denied and no simple fix is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalTrustFailure"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/fatalTrustFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultFatalTrustFailure"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.fatalTrustFailure",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/fataltrustfailure"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/otherError": {
      "abstract": [
        {
          "text": "A value that indicates a failure other than trust evaluation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherError"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/otherError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultOtherError"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.otherError",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/othererror"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/proceed": {
      "abstract": [
        {
          "text": "The user granted permission to trust the certificate for the purposes designated in the specified policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proceed"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/proceed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultProceed"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.proceed",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/proceed"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/recoverableTrustFailure": {
      "abstract": [
        {
          "text": "Trust is denied, but recovery may be possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recoverableTrustFailure"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/recoverableTrustFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultRecoverableTrustFailure"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.recoverableTrustFailure",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/recoverabletrustfailure"
    },
    "doc://com.apple.security/documentation/Security/SecTrustResultType/unspecified": {
      "abstract": [
        {
          "text": "The user did not specify a trust setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultUnspecified"
        }
      ],
      "role": "symbol",
      "title": "SecTrustResultType.unspecified",
      "type": "topic",
      "url": "/documentation/security/sectrustresulttype/unspecified"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSetAnchorCertificates(_:_:)": {
      "abstract": [
        {
          "text": "Sets the anchor certificates used when evaluating a trust management object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSetAnchorCertificates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetAnchorCertificates(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSetAnchorCertificates"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSetAnchorCertificates(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsetanchorcertificates(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSetKeychains(_:_:)": {
      "abstract": [
        {
          "text": "Sets the keychains searched for intermediate certificates when evaluating a trust management object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSetKeychains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetKeychains(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSetKeychains"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSetKeychains(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsetkeychains(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSetParameters": {
      "abstract": [
        {
          "text": "Sets the action and action data for a trust management object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecTrustSetParameters"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecTrustSetParameters",
      "type": "topic",
      "url": "/documentation/security/sectrustsetparameters"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSetVerifyDate(_:_:)": {
      "abstract": [
        {
          "text": "Sets the date and time against which the certificates in a trust management object are verified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSetVerifyDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDateRef",
          "text": "CFDate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetVerifyDate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSetVerifyDate"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSetVerifyDate(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsetverifydate(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSettingsCopyTrustSettings(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the trust settings for a certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSettingsCopyTrustSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTrustSettingsDomain",
          "text": "SecTrustSettingsDomain"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSettingsCopyTrustSettings(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSettingsCopyTrustSettings"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSettingsCopyTrustSettings(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsettingscopytrustsettings(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSettingsSetTrustSettings(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies trust settings for a certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSettingsSetTrustSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCertificateRef",
          "text": "SecCertificate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTrustSettingsDomain",
          "text": "SecTrustSettingsDomain"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSettingsSetTrustSettings(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSettingsSetTrustSettings"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSettingsSetTrustSettings(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsettingssettrustsettings(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "2.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecTrustEvaluate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustEvaluate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecTrustEvaluate"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecTrustRef",
                    "text": "SecTrustRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "trust"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SecTrustResultType",
                    "text": "SecTrustResultType"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The trust management object to evaluate. A trust management object includes the certificate to be verified plus the policy or policies to be used in evaluating trust. It can optionally also include other certificates to be used in verifying the first certificate. Use the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecTrustCreateWithCertificates(_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function to create a trust management object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "trust"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, points to a result type reflecting the result of this evaluation. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/SecTrustResultType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for descriptions of possible values. See the discussion below for an explanation of how to handle specific values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "result"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecTrustEvaluateWithError(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCreateWithCertificates(_:_:_:)/title",
          "value": "SecTrustCreateWithCertificates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCreateWithCertificates(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustCreateWithCertificates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType/title",
          "value": "SecTrustResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetVerifyDate(_:_:)/title",
          "value": "SecTrustSetVerifyDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetVerifyDate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSetVerifyDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1confirm/title",
          "value": "kSecTrustResultConfirm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1confirm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultConfirm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/title",
          "value": "SecTrustRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetAnchorCertificates(_:_:)/title",
          "value": "SecTrustSetAnchorCertificates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetAnchorCertificates(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSetAnchorCertificates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1otherError/title",
          "value": "kSecTrustResultOtherError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1otherError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultOtherError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyResult(_:)/title",
          "value": "SecTrustCopyResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyResult(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustCopyResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetKeychains(_:_:)/title",
          "value": "SecTrustSetKeychains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetKeychains(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSetKeychains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluate(_:_:)/title",
          "value": "SecTrustEvaluate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustEvaluate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1deny/title",
          "value": "kSecTrustResultDeny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1deny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultDeny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateAsync(_:_:_:)/title",
          "value": "SecTrustEvaluateAsync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateAsync(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustEvaluateAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateWithError(_:_:)/title",
          "value": "SecTrustEvaluateWithError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustEvaluateWithError(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustEvaluateWithError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SecurityInterface~1SFCertificateTrustPanel/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFCertificateTrustPanel"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFCertificatePanel",
              "text": "SFCertificatePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1recoverableTrustFailure/title",
          "value": "kSecTrustResultRecoverableTrustFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1recoverableTrustFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultRecoverableTrustFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1fatalTrustFailure/title",
          "value": "kSecTrustResultFatalTrustFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1fatalTrustFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultFatalTrustFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1proceed/title",
          "value": "kSecTrustResultProceed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1proceed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultProceed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1unspecified/title",
          "value": "kSecTrustResultUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustResultType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSettingsCopyTrustSettings(_:_:_:)/title",
          "value": "SecTrustSettingsCopyTrustSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSettingsCopyTrustSettings(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSettingsCopyTrustSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSettingsSetTrustSettings(_:_:_:)/title",
          "value": "SecTrustSettingsSetTrustSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSettingsSetTrustSettings(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSettingsSetTrustSettings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sectrustevaluate(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sectrustevaluate(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
