{
  "abstract": [
    {
      "text": "Chains transforms together.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "SecTransform is no longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecTransformConnectTransforms(_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SecTransformConnectTransforms",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecTransformConnectTransforms"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecTransformRef",
        "text": "SecTransform"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecTransformRef",
        "text": "SecTransform"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecGroupTransformRef",
        "text": "SecGroupTransform"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFErrorRef",
        "text": "CFError"
      },
      {
        "kind": "text",
        "text": ">?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecGroupTransformRef",
        "text": "SecGroupTransform"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecTransformConnectTransforms"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.7",
        "message": "SecTransform is no longer supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecTransformConnectTransforms(_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecTransformConnectTransforms"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sourceTransformRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecTransformRef",
              "text": "SecTransform"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sourceAttributeName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "destinationTransformRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecTransformRef",
              "text": "SecTransform"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "destinationAttributeName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "group"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecGroupTransformRef",
              "text": "SecGroupTransform"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFErrorRef",
              "text": "CFError"
            },
            {
              "kind": "text",
              "text": ">?>?) -> "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecGroupTransformRef",
              "text": "SecGroupTransform"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The transform that sends the data to the destinationTransformRef.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sourceTransformRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the attribute in the sourceTransformRef that supplies the data to the destinationTransformRef. Any attribute of the transform may be used as a source.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sourceAttributeName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The transform that has one of its attributes be set with the data from the sourceTransformRef parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "destinationTransformRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the attribute within the destinationTransformRef whose data is set with the data from the sourceTransformRef sourceAttributeName attribute. Any attribute of the transform may be set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "destinationAttributeName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "In order to ensure referential integrity, transforms are chained together into a directed graph and placed into a group. Each transform that makes up the graph must be placed into the same group. After a SecTransformRef has been placed into a group by calling the SecTransformConnectTransforms it may be released as the group will retain the transform. CFRelease the group after you execute it, or when you determine you will never execute it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "In the example below, the output of trans1 is set to be the input of trans2. The output of trans2 is set to be the input of trans3. Since the same group was used for the connections, the three transforms are in the same group.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                " ",
                " ",
                "   \t\t\t\t\tSecGroupTransformRef group =SecTransformCreateGroupTransform();",
                "   \t\t\t\t\tCFErrorRef error = NULL;",
                " ",
                "   \t\t\t\t\tSecTransformRef trans1; // previously created using a",
                "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                " ",
                "   \t\t\t\t\tSecTransformRef trans2;\t// previously created using a",
                "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                " ",
                "   \t\t\t\t\tSecTransformRef trans3; // previously created using a",
                "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                " ",
                " ",
                "   \t\t\t\t\tSecTransformConnectTransforms(trans1, kSecTransformOutputAttributeName,",
                "   \t\t\t\t\t\t\t\t\t\t\t\t  trans2, kSecTransformInputAttributeName,",
                "   \t\t\t\t\t\t\t\t\t\t\t\t  group, &error);",
                " ",
                "   \t\t\t\t\tSecTransformConnectTransforms(trans2, kSecTransformOutputAttributeName,",
                "   \t\t\t\t\t\t\t\t\t\t\t\t  trans3, kSecTransformInputAttributeName.",
                "   \t\t\t\t\t\t\t\t\t\t\t\t  group, &error);",
                "   \t\t\t\t\tCFRelease(trans1);",
                "   \t\t\t\t\tCFRelease(trans2);",
                "   \t\t\t\t\tCFRelease(trans3);",
                " ",
                "   \t\t\t\t\tCFDataRef = (CFDataRef)SecTransformExecute(group, &error, NULL, NULL);",
                "   \t\t\t\t\tCFRelease(group);"
              ],
              "syntax": "objc",
              "type": "codeListing"
            }
          ],
          "name": "group"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional pointer to a CFErrorRef. This value is set if an error occurred. If not NULL, the caller is responsible for releasing the CFErrorRef.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that you can use for chaining calls to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformConnectTransforms(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function places transforms into a group by attaching the value of an attribute of one transform to the attribute of another transform. Typically the attribute supplying the data is the kSecTransformAttrOutput attribute but that is not a requirement. It can be used to set an attribute like Salt with the output attribute of a random number transform. This function returns an error and the named attribute will not be changed if ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformExecute(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " had previously been called on the transform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecGroupTransform": {
      "abstract": [
        {
          "text": "A Core Foundation type that represents a container holding a group of transforms.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecGroupTransform"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecGroupTransform"
        }
      ],
      "role": "symbol",
      "title": "SecGroupTransform",
      "type": "topic",
      "url": "/documentation/security/secgrouptransform"
    },
    "doc://com.apple.security/documentation/Security/SecTransform": {
      "abstract": [
        {
          "text": "A Core Foundation type that represents a security transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransform"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransform"
        }
      ],
      "role": "symbol",
      "title": "SecTransform",
      "type": "topic",
      "url": "/documentation/security/sectransform"
    },
    "doc://com.apple.security/documentation/Security/SecTransformConnectTransforms(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Chains transforms together.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformConnectTransforms"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformRef",
          "text": "SecTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformRef",
          "text": "SecTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecGroupTransformRef",
          "text": "SecGroupTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecGroupTransformRef",
          "text": "SecGroupTransform"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformConnectTransforms(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformConnectTransforms"
        }
      ],
      "role": "symbol",
      "title": "SecTransformConnectTransforms(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformconnecttransforms(_:_:_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTransformExecute(_:_:)": {
      "abstract": [
        {
          "text": "Executes a transform or transform group synchronously.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformExecute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformRef",
          "text": "SecTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformExecute(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformExecute"
        }
      ],
      "role": "symbol",
      "title": "SecTransformExecute(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformexecute(_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFErrorRef": {
      "abstract": [
        {
          "text": "A reference to a CFError object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecTransformConnectTransforms"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformConnectTransforms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecGroupTransformRef",
                    "text": "SecGroupTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecTransformConnectTransforms"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTransform",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecTransformRef",
                    "text": "SecTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sourceTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sourceAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTransform",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecTransformRef",
                    "text": "SecTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "destinationTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "destinationAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecGroupTransformRef",
                    "text": "SecGroupTransformRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "group"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFErrorRef",
                    "text": "CFErrorRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The transform that sends the data to the destinationTransformRef.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sourceTransformRef"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the attribute in the sourceTransformRef that supplies the data to the destinationTransformRef. Any attribute of the transform may be used as a source.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sourceAttributeName"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The transform that has one of its attributes be set with the data from the sourceTransformRef parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "destinationTransformRef"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the attribute within the destinationTransformRef whose data is set with the data from the sourceTransformRef sourceAttributeName attribute. Any attribute of the transform may be set.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "destinationAttributeName"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "In order to ensure referential integrity, transforms are chained together into a directed graph and placed into a group. Each transform that makes up the graph must be placed into the same group. After a SecTransformRef has been placed into a group by calling the SecTransformConnectTransforms it may be released as the group will retain the transform. CFRelease the group after you execute it, or when you determine you will never execute it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "In the example below, the output of trans1 is set to be the input of trans2. The output of trans2 is set to be the input of trans3. Since the same group was used for the connections, the three transforms are in the same group.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "code": [
                      " ",
                      " ",
                      "   \t\t\t\t\tSecGroupTransformRef group =SecTransformCreateGroupTransform();",
                      "   \t\t\t\t\tCFErrorRef error = NULL;",
                      " ",
                      "   \t\t\t\t\tSecTransformRef trans1; // previously created using a",
                      "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                      "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                      " ",
                      "   \t\t\t\t\tSecTransformRef trans2;\t// previously created using a",
                      "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                      "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                      " ",
                      "   \t\t\t\t\tSecTransformRef trans3; // previously created using a",
                      "   \t\t\t\t\t\t\t\t\t\t\t// Transform construction API",
                      "   \t\t\t\t\t\t\t\t\t\t\t// like SecEncryptTransformCreate",
                      " ",
                      " ",
                      "   \t\t\t\t\tSecTransformConnectTransforms(trans1, kSecTransformOutputAttributeName,",
                      "   \t\t\t\t\t\t\t\t\t\t\t\t  trans2, kSecTransformInputAttributeName,",
                      "   \t\t\t\t\t\t\t\t\t\t\t\t  group, &error);",
                      " ",
                      "   \t\t\t\t\tSecTransformConnectTransforms(trans2, kSecTransformOutputAttributeName,",
                      "   \t\t\t\t\t\t\t\t\t\t\t\t  trans3, kSecTransformInputAttributeName.",
                      "   \t\t\t\t\t\t\t\t\t\t\t\t  group, &error);",
                      "   \t\t\t\t\tCFRelease(trans1);",
                      "   \t\t\t\t\tCFRelease(trans2);",
                      "   \t\t\t\t\tCFRelease(trans3);",
                      " ",
                      "   \t\t\t\t\tCFDataRef = (CFDataRef)SecTransformExecute(group, &error, NULL, NULL);",
                      "   \t\t\t\t\tCFRelease(group);"
                    ],
                    "syntax": "objc",
                    "type": "codeListing"
                  }
                ],
                "name": "group"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional pointer to a CFErrorRef. This value is set if an error occurred. If not NULL, the caller is responsible for releasing the CFErrorRef.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecGroupTransform",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object that you can use for chaining calls to ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTransformConnectTransforms(_:_:_:_:_:_:)",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "SecTransform is no longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGroupTransform/title",
          "value": "SecGroupTransformRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGroupTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecGroupTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecGroupTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecGroupTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransform/title",
          "value": "SecTransformRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformConnectTransforms(_:_:_:_:_:_:)/title",
          "value": "SecTransformConnectTransforms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformConnectTransforms(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformConnectTransforms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title",
          "value": "CFErrorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformExecute(_:_:)/title",
          "value": "SecTransformExecute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformExecute(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformExecute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sectransformconnecttransforms(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sectransformconnecttransforms(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
