{
  "abstract": [
    {
      "text": "The keys that describe the metadata attributes of transform attributes.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "SecTransform is no longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SecTransformMetaAttributeType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecTransformMetaAttributeType"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SecTransformMetaAttributeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.7",
        "message": "SecTransform is no longer supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SecTransformMetaAttributeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecTransformMetaAttributeType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use one of these values as the ",
              "type": "text"
            },
            {
              "code": "type",
              "type": "codeVoice"
            },
            {
              "text": " parameter in a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformCustomSetAttribute(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformCustomGetAttribute(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. These values allow you to access not only the value of an attribute, as you would do directly with calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformSetAttribute(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTransformGetAttribute(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, but also the metadata associated with that attribute, such as the name of an attribute, or whether it is required to have a value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecTransformCustomGetAttribute(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets an attribute value from a custom transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformCustomGetAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformImplementationRef",
          "text": "SecTransformImplementationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformStringOrAttributeRef",
          "text": "SecTransformStringOrAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTransformMetaAttributeType",
          "text": "SecTransformMetaAttributeType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformCustomGetAttribute(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformCustomGetAttribute"
        }
      ],
      "role": "symbol",
      "title": "SecTransformCustomGetAttribute(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformcustomgetattribute(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTransformCustomSetAttribute(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets an attribute value on a custom transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformCustomSetAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformImplementationRef",
          "text": "SecTransformImplementationRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformStringOrAttributeRef",
          "text": "SecTransformStringOrAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTransformMetaAttributeType",
          "text": "SecTransformMetaAttributeType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformCustomSetAttribute(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformCustomSetAttribute"
        }
      ],
      "role": "symbol",
      "title": "SecTransformCustomSetAttribute(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformcustomsetattribute(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTransformGetAttribute(_:_:)": {
      "abstract": [
        {
          "text": "Gets the current value of a transform attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformGetAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformRef",
          "text": "SecTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformGetAttribute(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformGetAttribute"
        }
      ],
      "role": "symbol",
      "title": "SecTransformGetAttribute(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformgetattribute(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType": {
      "abstract": [
        {
          "text": "The keys that describe the metadata attributes of transform attributes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformMetaAttributeType"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformMetaAttributeType"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/canCycle": {
      "abstract": [
        {
          "text": "The transform allows cyclic behavior.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canCycle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/canCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeCanCycle"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.canCycle",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/cancycle"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/deferred": {
      "abstract": [
        {
          "text": "The attribute defers notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferred"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/deferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeDeferred"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.deferred",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/deferred"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/externalize": {
      "abstract": [
        {
          "text": "The attribute is exportable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalize"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/externalize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeExternalize"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.externalize",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/externalize"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasInboundConnection": {
      "abstract": [
        {
          "text": "The attribute has an inbound connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasInboundConnection"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasInboundConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeHasInboundConnection"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.hasInboundConnection",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/hasinboundconnection"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasOutboundConnections": {
      "abstract": [
        {
          "text": "The attribute has an outbound connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasOutboundConnections"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasOutboundConnections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeHasOutboundConnections"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.hasOutboundConnections",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/hasoutboundconnections"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/name": {
      "abstract": [
        {
          "text": "The name of the attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeName"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.name",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/name"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/ref": {
      "abstract": [
        {
          "text": "A direct reference to an attribute’s value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ref"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/ref",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeRef"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.ref",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/ref"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/required": {
      "abstract": [
        {
          "text": "Indicates whether the attribute value is optional.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "required"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/required",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeRequired"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.required",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/required"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/requiresOutboundConnection": {
      "abstract": [
        {
          "text": "The attribute requires an outbound connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresOutboundConnection"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/requiresOutboundConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeRequiresOutboundConnection"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.requiresOutboundConnection",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/requiresoutboundconnection"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/stream": {
      "abstract": [
        {
          "text": "The attribute expects stream operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stream"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/stream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeStream"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.stream",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/stream"
    },
    "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/value": {
      "abstract": [
        {
          "text": "The actual value of the attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformMetaAttributeValue"
        }
      ],
      "role": "symbol",
      "title": "SecTransformMetaAttributeType.value",
      "type": "topic",
      "url": "/documentation/security/sectransformmetaattributetype/value"
    },
    "doc://com.apple.security/documentation/Security/SecTransformSetAttribute(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a static value for an attribute in a transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTransformSetAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTransformRef",
          "text": "SecTransform"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTransformSetAttribute(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTransformSetAttribute"
        }
      ],
      "role": "symbol",
      "title": "SecTransformSetAttribute(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectransformsetattribute(_:_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/canCycle",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/deferred",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/externalize",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasInboundConnection",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasOutboundConnections",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/name",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/ref",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/required",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/requiresOutboundConnection",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/stream",
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/value"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SecTransformMetaAttributeType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformMetaAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformMetaAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/canCycle",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/deferred",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/externalize",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasInboundConnection",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/hasOutboundConnections",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/name",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/ref",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/required",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/requiresOutboundConnection",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/stream",
                "doc://com.apple.security/documentation/Security/SecTransformMetaAttributeType/value"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SecTransformMetaAttributeType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "SecTransform is no longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1value/title",
          "value": "kSecTransformMetaAttributeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformCustomGetAttribute(_:_:_:)/title",
          "value": "SecTransformCustomGetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformCustomGetAttribute(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformCustomGetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1name/title",
          "value": "kSecTransformMetaAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1deferred/title",
          "value": "kSecTransformMetaAttributeDeferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1deferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeDeferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1required/title",
          "value": "kSecTransformMetaAttributeRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1required/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformSetAttribute(_:_:_:_:)/title",
          "value": "SecTransformSetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformSetAttribute(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1canCycle/title",
          "value": "kSecTransformMetaAttributeCanCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1canCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeCanCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1stream/title",
          "value": "kSecTransformMetaAttributeStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1stream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1requiresOutboundConnection/title",
          "value": "kSecTransformMetaAttributeRequiresOutboundConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1requiresOutboundConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeRequiresOutboundConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1ref/title",
          "value": "kSecTransformMetaAttributeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1ref/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformGetAttribute(_:_:)/title",
          "value": "SecTransformGetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformGetAttribute(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformGetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformCustomSetAttribute(_:_:_:_:)/title",
          "value": "SecTransformCustomSetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformCustomSetAttribute(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformCustomSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1hasInboundConnection/title",
          "value": "kSecTransformMetaAttributeHasInboundConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1hasInboundConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeHasInboundConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1hasOutboundConnections/title",
          "value": "kSecTransformMetaAttributeHasOutboundConnections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1hasOutboundConnections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeHasOutboundConnections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1externalize/title",
          "value": "kSecTransformMetaAttributeExternalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType~1externalize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformMetaAttributeExternalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType/title",
          "value": "SecTransformMetaAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformMetaAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTransformMetaAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTransformMetaAttributeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sectransformmetaattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sectransformmetaattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
