{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/security/sectrustedapplicationsetdata(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/security/sectrustedapplicationsetdata(_:_:)"]}],"metadata":{"symbolKind":"func","platforms":[{"message":"SecKeychain is deprecated","deprecated":false,"introducedAt":"10.0","unavailable":false,"deprecatedAt":"10.10","name":"macOS","beta":false}],"roleHeading":"Function","externalID":"c:@F@SecTrustedApplicationSetData","navigatorTitle":[{"text":"SecTrustedApplicationSetData","kind":"identifier"}],"title":"SecTrustedApplicationSetData(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecTrustedApplicationSetData"},{"kind":"text","text":"("},{"text":"SecTrustedApplication","kind":"typeIdentifier","preciseIdentifier":"c:@T@SecTrustedApplicationRef"},{"text":", ","kind":"text"},{"text":"CFData","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFDataRef"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"role":"symbol","modules":[{"name":"Security"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SecTrustedApplicationSetData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appRef","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SecTrustedApplicationRef","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplication","text":"SecTrustedApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CFDataRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFDataRef","text":"CFData","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A trusted application object.","type":"text"}]}],"name":"appRef"},{"content":[{"inlineContent":[{"type":"text","text":"A reference to the data to set in the trusted application."}],"type":"paragraph"}],"name":"data"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"A result code. See ","type":"text"},{"identifier":"doc://com.apple.security/documentation/Security/security-framework-result-codes","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplicationCopyData(_:_:)"},{"type":"text","text":" method to extract the data from a trusted app instance for storage or transmission, you can use the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplicationSetData(_:_:)"},{"type":"text","text":" method to insert that data into a new trusted app. Doing so creates an object that identifies the same app as the original trusted app instance."}]}]}],"identifier":{"url":"doc://com.apple.security/documentation/Security/SecTrustedApplicationSetData(_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Sets the data of a given trusted app instance.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"SecKeychain is deprecated","type":"text"}],"type":"paragraph"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.security/documentation/Security"]]},"references":{"doc://com.apple.security/documentation/Security/SecTrustedApplicationCopyData(_:_:)":{"role":"symbol","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplicationCopyData(_:_:)","deprecated":true,"abstract":[{"type":"text","text":"Retrieves the data of a trusted app instance."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecTrustedApplicationCopyData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SecTrustedApplicationRef","text":"SecTrustedApplication"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFDataRef","text":"CFData"},{"kind":"text","text":"?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SecTrustedApplicationCopyData"}],"title":"SecTrustedApplicationCopyData(_:_:)","url":"/documentation/security/sectrustedapplicationcopydata(_:_:)"},"doc://com.externally.resolved.symbol/c:@T@CFDataRef":{"fragments":[{"text":"class ","kind":"text"},{"text":"CFData","kind":"identifier"}],"url":"/documentation/corefoundation/cfdata","identifier":"doc://com.externally.resolved.symbol/c:@T@CFDataRef","title":"CFData","type":"topic","abstract":[{"text":"A reference to an immutable CFData object.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.security/documentation/Security":{"title":"Security","abstract":[{"text":"Secure the data your app manages, and control access to your app.","type":"text"}],"identifier":"doc://com.apple.security/documentation/Security","kind":"symbol","url":"/documentation/security","type":"topic","role":"collection"},"doc://com.apple.security/documentation/Security/SecTrustedApplication":{"identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplication","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An opaque type that contains information about a trusted app."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecTrustedApplication"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SecTrustedApplication"}],"title":"SecTrustedApplication","url":"/documentation/security/sectrustedapplication"},"doc://com.apple.security/documentation/Security/security-framework-result-codes":{"url":"/documentation/security/security-framework-result-codes","title":"Security Framework Result Codes","kind":"article","role":"collectionGroup","abstract":[{"text":"Evaluate result codes common to many Security framework functions.","type":"text"}],"type":"topic","identifier":"doc://com.apple.security/documentation/Security/security-framework-result-codes"},"doc://com.apple.security/documentation/Security/SecTrustedApplicationSetData(_:_:)":{"kind":"symbol","type":"topic","url":"/documentation/security/sectrustedapplicationsetdata(_:_:)","navigatorTitle":[{"text":"SecTrustedApplicationSetData","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SecTrustedApplicationSetData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@SecTrustedApplicationRef","text":"SecTrustedApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@CFDataRef","text":"CFData","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Sets the data of a given trusted app instance."}],"title":"SecTrustedApplicationSetData(_:_:)","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplicationSetData(_:_:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","url":"/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"deprecatedAt":"10.10","deprecated":false,"introducedAt":"10.0","unavailable":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"op":"replace","value":"SecTrustedApplicationSetData","path":"/metadata/title"},{"op":"replace","value":"func","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"SecTrustedApplicationSetData","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.security/documentation/Security"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecTrustedApplicationSetData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SecTrustedApplicationRef","text":"SecTrustedApplicationRef","identifier":"doc://com.apple.security/documentation/Security/SecTrustedApplication"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFDataRef","text":"CFDataRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFDataRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":");"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A trusted application object."}],"type":"paragraph"}],"name":"appRef"},{"content":[{"inlineContent":[{"type":"text","text":"A reference to the data to set in the trusted application."}],"type":"paragraph"}],"name":"data"}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A result code. See "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.security/documentation/Security/security-framework-result-codes"},{"type":"text","text":"."}]}],"kind":"content"},"path":"/primaryContentSections/2"},{"path":"/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SecKeychain is deprecated"}]}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationCopyData(_:_:)/title","value":"SecTrustedApplicationCopyData","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationCopyData(_:_:)/fragments","value":[{"text":"SecTrustedApplicationCopyData","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title","value":"CFDataRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/title","value":"SecTrustedApplicationRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/fragments","value":[{"text":"SecTrustedApplicationRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplication/navigatorTitle","value":[{"text":"SecTrustedApplicationRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationSetData(_:_:)/title","value":"SecTrustedApplicationSetData","op":"replace"},{"op":"replace","value":[{"text":"SecTrustedApplicationSetData","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustedApplicationSetData(_:_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}