{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/security-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Security Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationExternalFormLength": {
      "abstract": [
        {
          "text": "The number of bytes in an external form structure’s array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationExternalFormLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationExternalFormLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationExternalFormLength"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationExternalFormLength",
      "type": "topic",
      "url": "/documentation/security/kauthorizationexternalformlength"
    },
    "doc://com.apple.security/documentation/Security/kAuthorizationFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kAuthorizationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlags"
        }
      ],
      "role": "symbol",
      "title": "kAuthorizationFlags",
      "type": "topic",
      "url": "/documentation/security/kauthorizationflags"
    },
    "doc://com.apple.security/documentation/Security/kSecCFErrorResourceRecursive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCFErrorResourceRecursive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCFErrorResourceRecursive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCFErrorResourceRecursive"
        }
      ],
      "role": "symbol",
      "title": "kSecCFErrorResourceRecursive",
      "type": "topic",
      "url": "/documentation/security/kseccferrorresourcerecursive"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDefaultDesignatedLightweightCodeRequirement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDefaultDesignatedLightweightCodeRequirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDefaultDesignatedLightweightCodeRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDefaultDesignatedLightweightCodeRequirement"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDefaultDesignatedLightweightCodeRequirement",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodefaultdesignatedlightweightcoderequirement"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoStapledNotarizationTicket": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoStapledNotarizationTicket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoStapledNotarizationTicket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoStapledNotarizationTicket"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoStapledNotarizationTicket",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfostaplednotarizationticket"
    },
    "doc://com.apple.security/documentation/Security/kSecImportToMemoryOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecImportToMemoryOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecImportToMemoryOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecImportToMemoryOnly"
        }
      ],
      "role": "symbol",
      "title": "kSecImportToMemoryOnly",
      "type": "topic",
      "url": "/documentation/security/ksecimporttomemoryonly"
    },
    "doc://com.apple.security/documentation/Security/kSecMatchHostOrSubdomainOfHost": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecMatchHostOrSubdomainOfHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecMatchHostOrSubdomainOfHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecMatchHostOrSubdomainOfHost"
        }
      ],
      "role": "symbol",
      "title": "kSecMatchHostOrSubdomainOfHost",
      "type": "topic",
      "url": "/documentation/security/ksecmatchhostorsubdomainofhost"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kAuthorizationExternalFormLength",
        "doc://com.apple.security/documentation/Security/kAuthorizationFlags",
        "doc://com.apple.security/documentation/Security/kSecCFErrorResourceRecursive",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoDefaultDesignatedLightweightCodeRequirement",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoStapledNotarizationTicket",
        "doc://com.apple.security/documentation/Security/kSecImportToMemoryOnly",
        "doc://com.apple.security/documentation/Security/kSecMatchHostOrSubdomainOfHost"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kAuthorizationExternalFormLength",
                "doc://com.apple.security/documentation/Security/kAuthorizationFlags",
                "doc://com.apple.security/documentation/Security/kSecCFErrorResourceRecursive",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoDefaultDesignatedLightweightCodeRequirement",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoStapledNotarizationTicket",
                "doc://com.apple.security/documentation/Security/kSecImportToMemoryOnly",
                "doc://com.apple.security/documentation/Security/kSecMatchHostOrSubdomainOfHost"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationFlags/title",
          "value": "kAuthorizationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoStapledNotarizationTicket/title",
          "value": "kSecCodeInfoStapledNotarizationTicket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoStapledNotarizationTicket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoStapledNotarizationTicket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportToMemoryOnly/title",
          "value": "kSecImportToMemoryOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecImportToMemoryOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecImportToMemoryOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecMatchHostOrSubdomainOfHost/title",
          "value": "kSecMatchHostOrSubdomainOfHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecMatchHostOrSubdomainOfHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecMatchHostOrSubdomainOfHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationExternalFormLength/title",
          "value": "kAuthorizationExternalFormLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kAuthorizationExternalFormLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationExternalFormLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDefaultDesignatedLightweightCodeRequirement/title",
          "value": "kSecCodeInfoDefaultDesignatedLightweightCodeRequirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDefaultDesignatedLightweightCodeRequirement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDefaultDesignatedLightweightCodeRequirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCFErrorResourceRecursive/title",
          "value": "kSecCFErrorResourceRecursive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCFErrorResourceRecursive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCFErrorResourceRecursive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/security-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/security-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
