{
  "abstract": [
    {
      "text": "Use these dictionary keys to get and set policy properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/policies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/security-policy-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Security Policy Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys with calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicyCopyProperties(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecPolicySetProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecPolicyCopyProperties(_:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing a policy’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecPolicyCopyProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecPolicyRef",
          "text": "SecPolicy"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicyCopyProperties(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecPolicyCopyProperties"
        }
      ],
      "role": "symbol",
      "title": "SecPolicyCopyProperties(_:)",
      "type": "topic",
      "url": "/documentation/security/secpolicycopyproperties(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecPolicySetProperties": {
      "abstract": [
        {
          "text": "Sets properties for a policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SecPolicySetProperties"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecPolicySetProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecPolicySetProperties",
      "type": "topic",
      "url": "/documentation/security/secpolicysetproperties"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyClient": {
      "abstract": [
        {
          "text": "If true, indicates this policy should be evaluated against the client certificate. If false, the policy is evaluated against the certificate for the server. Default is false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyClient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyClient"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyClient",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyclient"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_CRLSign": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for signing certificate revocation lists (CRLs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_CRLSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_CRLSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_CRLSign"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_CRLSign",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_crlsign"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_DataEncipherment": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for data encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DataEncipherment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_DataEncipherment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DataEncipherment"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_DataEncipherment",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_dataencipherment"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_DecipherOnly": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "only",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for decryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DecipherOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_DecipherOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DecipherOnly"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_DecipherOnly",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_decipheronly"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_DigitalSignature": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for signing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DigitalSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_DigitalSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_DigitalSignature"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_DigitalSignature",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_digitalsignature"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_EncipherOnly": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "only",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_EncipherOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_EncipherOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_EncipherOnly"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_EncipherOnly",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_encipheronly"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyAgreement": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for key agreement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyAgreement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyAgreement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyAgreement"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_KeyAgreement",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_keyagreement"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyCertSign": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for signing certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyCertSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyCertSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyCertSign"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_KeyCertSign",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_keycertsign"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyEncipherment": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for key encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyEncipherment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyEncipherment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_KeyEncipherment"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_KeyEncipherment",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_keyencipherment"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyKU_NonRepudiation": {
      "abstract": [
        {
          "text": "If true, the certificate’s key usage must allow it to be used for non-repudiation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_NonRepudiation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyKU_NonRepudiation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyKU_NonRepudiation"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyKU_NonRepudiation",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyku_nonrepudiation"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyName": {
      "abstract": [
        {
          "text": "A name (",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": ") that the certificate must match to satisfy this policy. For SSL/TLS, this specifies the server name which must match the common name of the certificate. For S/MIME, this specifies the RFC 822 email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyName"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyName",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyname"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyOid": {
      "abstract": [
        {
          "text": "The object identifier that defines the policy type (",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": "). All policies have a value for this key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyOid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyOid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyOid"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyOid",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyoid"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyRevocationFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyRevocationFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyRevocationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyRevocationFlags"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyRevocationFlags",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyrevocationflags"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyTeamIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyTeamIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyTeamIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyTeamIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyTeamIdentifier",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyteamidentifier"
    },
    "doc://com.apple.security/documentation/Security/policies": {
      "abstract": [
        {
          "text": "Obtain policies for establishing trust.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/policies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Policies",
      "type": "topic",
      "url": "/documentation/security/policies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecPolicyOid",
        "doc://com.apple.security/documentation/Security/kSecPolicyName",
        "doc://com.apple.security/documentation/Security/kSecPolicyClient",
        "doc://com.apple.security/documentation/Security/kSecPolicyRevocationFlags",
        "doc://com.apple.security/documentation/Security/kSecPolicyTeamIdentifier",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_DigitalSignature",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_NonRepudiation",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyEncipherment",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_DataEncipherment",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyAgreement",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyCertSign",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_CRLSign",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_EncipherOnly",
        "doc://com.apple.security/documentation/Security/kSecPolicyKU_DecipherOnly"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecPolicyOid",
                "doc://com.apple.security/documentation/Security/kSecPolicyName",
                "doc://com.apple.security/documentation/Security/kSecPolicyClient",
                "doc://com.apple.security/documentation/Security/kSecPolicyRevocationFlags",
                "doc://com.apple.security/documentation/Security/kSecPolicyTeamIdentifier",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_DigitalSignature",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_NonRepudiation",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyEncipherment",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_DataEncipherment",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyAgreement",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_KeyCertSign",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_CRLSign",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_EncipherOnly",
                "doc://com.apple.security/documentation/Security/kSecPolicyKU_DecipherOnly"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DigitalSignature/title",
          "value": "kSecPolicyKU_DigitalSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DigitalSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_DigitalSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyEncipherment/title",
          "value": "kSecPolicyKU_KeyEncipherment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyEncipherment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_KeyEncipherment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyCertSign/title",
          "value": "kSecPolicyKU_KeyCertSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyCertSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_KeyCertSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicyCopyProperties(_:)/title",
          "value": "SecPolicyCopyProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecPolicyCopyProperties(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecPolicyCopyProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyTeamIdentifier/title",
          "value": "kSecPolicyTeamIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyTeamIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyTeamIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_CRLSign/title",
          "value": "kSecPolicyKU_CRLSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_CRLSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_CRLSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_NonRepudiation/title",
          "value": "kSecPolicyKU_NonRepudiation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_NonRepudiation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_NonRepudiation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyName/title",
          "value": "kSecPolicyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyRevocationFlags/title",
          "value": "kSecPolicyRevocationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyRevocationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyRevocationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DataEncipherment/title",
          "value": "kSecPolicyKU_DataEncipherment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DataEncipherment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_DataEncipherment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyOid/title",
          "value": "kSecPolicyOid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyOid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyOid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_EncipherOnly/title",
          "value": "kSecPolicyKU_EncipherOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_EncipherOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_EncipherOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyAgreement/title",
          "value": "kSecPolicyKU_KeyAgreement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_KeyAgreement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_KeyAgreement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DecipherOnly/title",
          "value": "kSecPolicyKU_DecipherOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyKU_DecipherOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyKU_DecipherOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyClient/title",
          "value": "kSecPolicyClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyClient"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/security-policy-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/security-policy-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
