{
  "abstract": [
    {
      "text": "Recognize the error codes used in error objects created by a transform on failure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/security-transforms"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/security-transform-error-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Security Transform Error Codes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorAbortInProgress": {
      "abstract": [
        {
          "text": "The abort attribute has been set and the transform is in the process of shutting down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAbortInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorAbortInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAbortInProgress"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorAbortInProgress",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorabortinprogress"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorAborted": {
      "abstract": [
        {
          "text": "The transform was aborted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAborted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorAborted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAborted"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorAborted",
      "type": "topic",
      "url": "/documentation/security/ksectransformerroraborted"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorAttributeNotFound": {
      "abstract": [
        {
          "text": "The attribute was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAttributeNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorAttributeNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorAttributeNotFound"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorAttributeNotFound",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorattributenotfound"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidAlgorithm": {
      "abstract": [
        {
          "text": "A transform that needs an algorithm as an attribute received an invalid algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidAlgorithm",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidalgorithm"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidConnection": {
      "abstract": [
        {
          "text": "A connection between transforms in different groups was attempted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidConnection"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidConnection",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidconnection"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInput": {
      "abstract": [
        {
          "text": "The input set on a transform is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidInput"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidInput",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidinput"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInputDictionary": {
      "abstract": [
        {
          "text": "A dictionary used to import a transform has invalid data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidInputDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInputDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidInputDictionary"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidInputDictionary",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidinputdictionary"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidLength": {
      "abstract": [
        {
          "text": "A transform that needs a length such as a digest transform has been given an invalid length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidLength"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidLength",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidlength"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidOperation": {
      "abstract": [
        {
          "text": "An invalid operation was attempted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidOperation"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidOperation",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidoperation"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidType": {
      "abstract": [
        {
          "text": "An invalid type has been set on an attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorInvalidType"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorInvalidType",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorinvalidtype"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorMissingParameter": {
      "abstract": [
        {
          "text": "A transform is missing a required attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorMissingParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorMissingParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorMissingParameter"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorMissingParameter",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrormissingparameter"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorMoreThanOneOutput": {
      "abstract": [
        {
          "text": "A transform has an internal routing error that has caused multiple outputs instead of a single discrete output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorMoreThanOneOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorMoreThanOneOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorMoreThanOneOutput"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorMoreThanOneOutput",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrormorethanoneoutput"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorNameAlreadyRegistered": {
      "abstract": [
        {
          "text": "A custom transform of a particular name has already been registered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorNameAlreadyRegistered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorNameAlreadyRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorNameAlreadyRegistered"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorNameAlreadyRegistered",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrornamealreadyregistered"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorNotInitializedCorrectly": {
      "abstract": [
        {
          "text": "A required initialization is missing: It is most likely a missing required attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorNotInitializedCorrectly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorNotInitializedCorrectly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorNotInitializedCorrectly"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorNotInitializedCorrectly",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrornotinitializedcorrectly"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformErrorUnsupportedAttribute": {
      "abstract": [
        {
          "text": "An illegal action such as setting a read-only attribute has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformErrorUnsupportedAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformErrorUnsupportedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformErrorUnsupportedAttribute"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformErrorUnsupportedAttribute",
      "type": "topic",
      "url": "/documentation/security/ksectransformerrorunsupportedattribute"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformInvalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument was given to a Transform API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformInvalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformInvalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformInvalidArgument",
      "type": "topic",
      "url": "/documentation/security/ksectransforminvalidargument"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformInvalidOverride": {
      "abstract": [
        {
          "text": "An illegal override was given to a custom transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformInvalidOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformInvalidOverride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformInvalidOverride"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformInvalidOverride",
      "type": "topic",
      "url": "/documentation/security/ksectransforminvalidoverride"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformOperationNotSupportedOnGroup": {
      "abstract": [
        {
          "text": "An illegal action on a group transform has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformOperationNotSupportedOnGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformOperationNotSupportedOnGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformOperationNotSupportedOnGroup"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformOperationNotSupportedOnGroup",
      "type": "topic",
      "url": "/documentation/security/ksectransformoperationnotsupportedongroup"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformTransformIsExecuting": {
      "abstract": [
        {
          "text": "An illegal operation was called on a Transform while it was executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformTransformIsExecuting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformTransformIsExecuting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformTransformIsExecuting"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformTransformIsExecuting",
      "type": "topic",
      "url": "/documentation/security/ksectransformtransformisexecuting"
    },
    "doc://com.apple.security/documentation/Security/kSecTransformTransformIsNotRegistered": {
      "abstract": [
        {
          "text": "A custom transform was asked to be created but the transform has not been registered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTransformTransformIsNotRegistered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTransformTransformIsNotRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTransformTransformIsNotRegistered"
        }
      ],
      "role": "symbol",
      "title": "kSecTransformTransformIsNotRegistered",
      "type": "topic",
      "url": "/documentation/security/ksectransformtransformisnotregistered"
    },
    "doc://com.apple.security/documentation/Security/security-transforms": {
      "abstract": [
        {
          "text": "Perform cryptographic functions like encoding, encryption, signing, and signature verification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Transforms",
      "type": "topic",
      "url": "/documentation/security/security-transforms"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecTransformErrorAttributeNotFound",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidOperation",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorNotInitializedCorrectly",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorMoreThanOneOutput",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInputDictionary",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidAlgorithm",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidLength",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidType",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInput",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorNameAlreadyRegistered",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorUnsupportedAttribute",
        "doc://com.apple.security/documentation/Security/kSecTransformOperationNotSupportedOnGroup",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorMissingParameter",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidConnection",
        "doc://com.apple.security/documentation/Security/kSecTransformTransformIsExecuting",
        "doc://com.apple.security/documentation/Security/kSecTransformInvalidOverride",
        "doc://com.apple.security/documentation/Security/kSecTransformTransformIsNotRegistered",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorAbortInProgress",
        "doc://com.apple.security/documentation/Security/kSecTransformErrorAborted",
        "doc://com.apple.security/documentation/Security/kSecTransformInvalidArgument"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecTransformErrorAttributeNotFound",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidOperation",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorNotInitializedCorrectly",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorMoreThanOneOutput",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInputDictionary",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidAlgorithm",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidLength",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidType",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidInput",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorNameAlreadyRegistered",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorUnsupportedAttribute",
                "doc://com.apple.security/documentation/Security/kSecTransformOperationNotSupportedOnGroup",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorMissingParameter",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorInvalidConnection",
                "doc://com.apple.security/documentation/Security/kSecTransformTransformIsExecuting",
                "doc://com.apple.security/documentation/Security/kSecTransformInvalidOverride",
                "doc://com.apple.security/documentation/Security/kSecTransformTransformIsNotRegistered",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorAbortInProgress",
                "doc://com.apple.security/documentation/Security/kSecTransformErrorAborted",
                "doc://com.apple.security/documentation/Security/kSecTransformInvalidArgument"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidType/title",
          "value": "kSecTransformErrorInvalidType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformTransformIsNotRegistered/title",
          "value": "kSecTransformTransformIsNotRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformTransformIsNotRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformTransformIsNotRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorMoreThanOneOutput/title",
          "value": "kSecTransformErrorMoreThanOneOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorMoreThanOneOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorMoreThanOneOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidOperation/title",
          "value": "kSecTransformErrorInvalidOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidLength/title",
          "value": "kSecTransformErrorInvalidLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAbortInProgress/title",
          "value": "kSecTransformErrorAbortInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAbortInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorAbortInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAttributeNotFound/title",
          "value": "kSecTransformErrorAttributeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAttributeNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorAttributeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformOperationNotSupportedOnGroup/title",
          "value": "kSecTransformOperationNotSupportedOnGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformOperationNotSupportedOnGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformOperationNotSupportedOnGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformInvalidOverride/title",
          "value": "kSecTransformInvalidOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformInvalidOverride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformInvalidOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAborted/title",
          "value": "kSecTransformErrorAborted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorAborted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorAborted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidAlgorithm/title",
          "value": "kSecTransformErrorInvalidAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidConnection/title",
          "value": "kSecTransformErrorInvalidConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorMissingParameter/title",
          "value": "kSecTransformErrorMissingParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorMissingParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorMissingParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformTransformIsExecuting/title",
          "value": "kSecTransformTransformIsExecuting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformTransformIsExecuting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformTransformIsExecuting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorNameAlreadyRegistered/title",
          "value": "kSecTransformErrorNameAlreadyRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorNameAlreadyRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorNameAlreadyRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidInput/title",
          "value": "kSecTransformErrorInvalidInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorUnsupportedAttribute/title",
          "value": "kSecTransformErrorUnsupportedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorUnsupportedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorUnsupportedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformInvalidArgument/title",
          "value": "kSecTransformInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformInvalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidInputDictionary/title",
          "value": "kSecTransformErrorInvalidInputDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorInvalidInputDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorInvalidInputDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorNotInitializedCorrectly/title",
          "value": "kSecTransformErrorNotInitializedCorrectly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTransformErrorNotInitializedCorrectly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTransformErrorNotInitializedCorrectly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/security-transform-error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/security-transform-error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
