{
  "abstract": [
    {
      "text": "Manage login, authorization, and security sessions in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/sessions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sessions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "Security.AuthSession",
              "type": "codeVoice"
            },
            {
              "text": " API to work with session management and inquiry functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecuritySessionId": {
      "abstract": [
        {
          "text": "A type that contains an authorization session identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecuritySessionId"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecuritySessionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecuritySessionId"
        }
      ],
      "role": "symbol",
      "title": "SecuritySessionId",
      "type": "topic",
      "url": "/documentation/security/securitysessionid"
    },
    "doc://com.apple.security/documentation/Security/SessionAttributeBits": {
      "abstract": [
        {
          "text": "The attributes of a security session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionAttributeBits"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SessionAttributeBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionAttributeBits"
        }
      ],
      "role": "symbol",
      "title": "SessionAttributeBits",
      "type": "topic",
      "url": "/documentation/security/sessionattributebits"
    },
    "doc://com.apple.security/documentation/Security/SessionCreate(_:_:)": {
      "abstract": [
        {
          "text": "Creates a security session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SessionCreationFlags",
          "text": "SessionCreationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SessionAttributeBits",
          "text": "SessionAttributeBits"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SessionCreate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionCreate"
        }
      ],
      "role": "symbol",
      "title": "SessionCreate(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sessioncreate(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SessionCreationFlags": {
      "abstract": [
        {
          "text": "The flags that affect the creation of a security session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionCreationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SessionCreationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionCreationFlags"
        }
      ],
      "role": "symbol",
      "title": "SessionCreationFlags",
      "type": "topic",
      "url": "/documentation/security/sessioncreationflags"
    },
    "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains information about a security session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionGetInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SessionAttributeBits",
          "text": "SessionAttributeBits"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionGetInfo"
        }
      ],
      "role": "symbol",
      "title": "SessionGetInfo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sessiongetinfo(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/session-id-values": {
      "abstract": [
        {
          "text": "Use these values as placeholders for specific sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/session-id-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Session ID Values",
      "type": "topic",
      "url": "/documentation/security/session-id-values"
    },
    "doc://com.apple.security/documentation/Security/sessions-api-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the sessions API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sessions-api-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sessions API Result Codes",
      "type": "topic",
      "url": "/documentation/security/sessions-api-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Session",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SessionCreate(_:_:)",
        "doc://com.apple.security/documentation/Security/SessionCreationFlags",
        "doc://com.apple.security/documentation/Security/SessionAttributeBits"
      ],
      "title": "Creating a Session"
    },
    {
      "anchor": "Session-Information",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)",
        "doc://com.apple.security/documentation/Security/session-id-values",
        "doc://com.apple.security/documentation/Security/SecuritySessionId"
      ],
      "title": "Session Information"
    },
    {
      "anchor": "Result-Codes",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/sessions-api-result-codes"
      ],
      "title": "Result Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Session",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SessionCreate(_:_:)",
                "doc://com.apple.security/documentation/Security/SessionCreationFlags",
                "doc://com.apple.security/documentation/Security/SessionAttributeBits"
              ],
              "title": "Creating a Session"
            },
            {
              "anchor": "Session-Information",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)",
                "doc://com.apple.security/documentation/Security/session-id-values",
                "doc://com.apple.security/documentation/Security/SecuritySessionId"
              ],
              "title": "Session Information"
            },
            {
              "anchor": "Result-Codes",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/sessions-api-result-codes"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionGetInfo(_:_:_:)/title",
          "value": "SessionGetInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionGetInfo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionGetInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionCreate(_:_:)/title",
          "value": "SessionCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionCreate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionAttributeBits/title",
          "value": "SessionAttributeBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionAttributeBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionAttributeBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionAttributeBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionAttributeBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecuritySessionId/title",
          "value": "SecuritySessionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecuritySessionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecuritySessionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecuritySessionId/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecuritySessionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionCreationFlags/title",
          "value": "SessionCreationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionCreationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionCreationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionCreationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionCreationFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sessions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sessions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
