{
  "abstract": [
    {
      "text": "Use these values as placeholders for specific sessions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/sessions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/session-id-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Session ID Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use these values as the ",
              "type": "text"
            },
            {
              "code": "session",
              "type": "codeVoice"
            },
            {
              "text": " input to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function as a stand-in for specific sessions when you don’t already know the ID for that session. They are ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "not",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " returned in the ",
              "type": "text"
            },
            {
              "code": "sessionId",
              "type": "codeVoice"
            },
            {
              "text": " output of that function. Instead, you receive the actual session ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains information about a security session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SessionGetInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SessionAttributeBits",
          "text": "SessionAttributeBits"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SessionGetInfo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SessionGetInfo"
        }
      ],
      "role": "symbol",
      "title": "SessionGetInfo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sessiongetinfo(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/callerSecuritySession": {
      "abstract": [
        {
          "text": "A value that is a placeholder for the caller’s session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callerSecuritySession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/callerSecuritySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callerSecuritySession"
        }
      ],
      "role": "symbol",
      "title": "callerSecuritySession",
      "type": "topic",
      "url": "/documentation/security/callersecuritysession"
    },
    "doc://com.apple.security/documentation/Security/noSecuritySession": {
      "abstract": [
        {
          "text": "Not a valid session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSecuritySession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecuritySessionId",
          "text": "SecuritySessionId"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/noSecuritySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noSecuritySession"
        }
      ],
      "role": "symbol",
      "title": "noSecuritySession",
      "type": "topic",
      "url": "/documentation/security/nosecuritysession"
    },
    "doc://com.apple.security/documentation/Security/sessions": {
      "abstract": [
        {
          "text": "Manage login, authorization, and security sessions in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sessions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sessions",
      "type": "topic",
      "url": "/documentation/security/sessions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/callerSecuritySession",
        "doc://com.apple.security/documentation/Security/noSecuritySession"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/callerSecuritySession",
                "doc://com.apple.security/documentation/Security/noSecuritySession"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionGetInfo(_:_:_:)/title",
          "value": "SessionGetInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SessionGetInfo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SessionGetInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1callerSecuritySession/title",
          "value": "callerSecuritySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1callerSecuritySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callerSecuritySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1noSecuritySession/title",
          "value": "noSecuritySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1noSecuritySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "noSecuritySession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/session-id-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/session-id-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
