{
  "abstract": [
    {
      "text": "Recognize result codes specific to the sessions API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/sessions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/sessions-api-result-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sessions API Result Codes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to obtain a human readable string corresponding to these status codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The functions of the sessions API may also return result codes from the authorization services API listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/authorization-services-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or the general codes listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)": {
      "abstract": [
        {
          "text": "Returns a string explaining the meaning of a security result code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCopyErrorMessageString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCopyErrorMessageString(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCopyErrorMessageString"
        }
      ],
      "role": "symbol",
      "title": "SecCopyErrorMessageString(_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccopyerrormessagestring(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/authorization-services-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the authorization services API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/authorization-services-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authorization Services Result Codes",
      "type": "topic",
      "url": "/documentation/security/authorization-services-result-codes"
    },
    "doc://com.apple.security/documentation/Security/errSessionAuthorizationDenied": {
      "abstract": [
        {
          "text": "Authorization denied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionAuthorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "errSessionAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/security/errsessionauthorizationdenied"
    },
    "doc://com.apple.security/documentation/Security/errSessionInternal": {
      "abstract": [
        {
          "text": "An unrecognized internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionInternal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionInternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionInternal"
        }
      ],
      "role": "symbol",
      "title": "errSessionInternal",
      "type": "topic",
      "url": "/documentation/security/errsessioninternal"
    },
    "doc://com.apple.security/documentation/Security/errSessionInvalidAttributes": {
      "abstract": [
        {
          "text": "Detected an invalid set of request attribute bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionInvalidAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionInvalidAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionInvalidAttributes"
        }
      ],
      "role": "symbol",
      "title": "errSessionInvalidAttributes",
      "type": "topic",
      "url": "/documentation/security/errsessioninvalidattributes"
    },
    "doc://com.apple.security/documentation/Security/errSessionInvalidFlags": {
      "abstract": [
        {
          "text": "Encountered invalid flags or options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionInvalidFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionInvalidFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionInvalidFlags"
        }
      ],
      "role": "symbol",
      "title": "errSessionInvalidFlags",
      "type": "topic",
      "url": "/documentation/security/errsessioninvalidflags"
    },
    "doc://com.apple.security/documentation/Security/errSessionInvalidId": {
      "abstract": [
        {
          "text": "Detected an invalid session ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionInvalidId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionInvalidId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionInvalidId"
        }
      ],
      "role": "symbol",
      "title": "errSessionInvalidId",
      "type": "topic",
      "url": "/documentation/security/errsessioninvalidid"
    },
    "doc://com.apple.security/documentation/Security/errSessionSuccess": {
      "abstract": [
        {
          "text": "The operation completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionSuccess"
        }
      ],
      "role": "symbol",
      "title": "errSessionSuccess",
      "type": "topic",
      "url": "/documentation/security/errsessionsuccess"
    },
    "doc://com.apple.security/documentation/Security/errSessionValueNotSet": {
      "abstract": [
        {
          "text": "The requested session attribute has not been set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errSessionValueNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errSessionValueNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errSessionValueNotSet"
        }
      ],
      "role": "symbol",
      "title": "errSessionValueNotSet",
      "type": "topic",
      "url": "/documentation/security/errsessionvaluenotset"
    },
    "doc://com.apple.security/documentation/Security/security-framework-result-codes": {
      "abstract": [
        {
          "text": "Evaluate result codes common to many Security framework functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/security-framework-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Framework Result Codes",
      "type": "topic",
      "url": "/documentation/security/security-framework-result-codes"
    },
    "doc://com.apple.security/documentation/Security/sessions": {
      "abstract": [
        {
          "text": "Manage login, authorization, and security sessions in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/sessions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sessions",
      "type": "topic",
      "url": "/documentation/security/sessions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Codes",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/errSessionSuccess",
        "doc://com.apple.security/documentation/Security/errSessionInvalidId",
        "doc://com.apple.security/documentation/Security/errSessionInvalidAttributes",
        "doc://com.apple.security/documentation/Security/errSessionAuthorizationDenied",
        "doc://com.apple.security/documentation/Security/errSessionValueNotSet",
        "doc://com.apple.security/documentation/Security/errSessionInternal",
        "doc://com.apple.security/documentation/Security/errSessionInvalidFlags"
      ],
      "title": "Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Codes",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/errSessionSuccess",
                "doc://com.apple.security/documentation/Security/errSessionInvalidId",
                "doc://com.apple.security/documentation/Security/errSessionInvalidAttributes",
                "doc://com.apple.security/documentation/Security/errSessionAuthorizationDenied",
                "doc://com.apple.security/documentation/Security/errSessionValueNotSet",
                "doc://com.apple.security/documentation/Security/errSessionInternal",
                "doc://com.apple.security/documentation/Security/errSessionInvalidFlags"
              ],
              "title": "Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidFlags/title",
          "value": "errSessionInvalidFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionInvalidFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionValueNotSet/title",
          "value": "errSessionValueNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionValueNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionValueNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCopyErrorMessageString(_:_:)/title",
          "value": "SecCopyErrorMessageString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCopyErrorMessageString(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCopyErrorMessageString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidId/title",
          "value": "errSessionInvalidId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionInvalidId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionAuthorizationDenied/title",
          "value": "errSessionAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInternal/title",
          "value": "errSessionInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidAttributes/title",
          "value": "errSessionInvalidAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionInvalidAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionInvalidAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionSuccess/title",
          "value": "errSessionSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errSessionSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errSessionSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sessions-api-result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sessions-api-result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
