{
  "abstract": [
    {
      "text": "Share credentials between iOS apps and their website counterparts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/shared-web-credentials"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Shared Web Credentials"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "Security.SecSharedCredentials",
              "type": "codeVoice"
            },
            {
              "text": " API provides functions for storing and requesting shared password-based credentials. Users often save their username and password in their iCloud keychain when logging into websites in Safari. Later, they may run a native app from the same developer to access the same account. With shared web credentials, the app can access the credentials stored for the website instead of requiring the user to reenter a username and password. Users can also create new accounts, update passwords, or delete their accounts from within the app. These changes are then saved and used by Safari.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2891900",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Accessing shared web credentials requires permission from the app, the website, and the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Asynchronously stores (or updates) a shared password for a website.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAddSharedWebCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAddSharedWebCredential"
        }
      ],
      "role": "symbol",
      "title": "SecAddSharedWebCredential(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secaddsharedwebcredential(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecCreateSharedWebCredentialPassword()": {
      "abstract": [
        {
          "text": "Returns a randomly generated password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCreateSharedWebCredentialPassword"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCreateSharedWebCredentialPassword()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCreateSharedWebCredentialPassword"
        }
      ],
      "role": "symbol",
      "title": "SecCreateSharedWebCredentialPassword()",
      "type": "topic",
      "url": "/documentation/security/seccreatesharedwebcredentialpassword()"
    },
    "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)": {
      "abstract": [
        {
          "text": "Asynchronously obtains one or more shared passwords for a website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecRequestSharedWebCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecRequestSharedWebCredential"
        }
      ],
      "role": "symbol",
      "title": "SecRequestSharedWebCredential(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secrequestsharedwebcredential(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/kSecSharedPassword": {
      "abstract": [
        {
          "text": "A dictionary key whose value is the shared password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecSharedPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecSharedPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecSharedPassword"
        }
      ],
      "role": "symbol",
      "title": "kSecSharedPassword",
      "type": "topic",
      "url": "/documentation/security/ksecsharedpassword"
    },
    "doc://com.apple.security/documentation/Security/managing-shared-credentials": {
      "abstract": [
        {
          "text": "Use shared web credentials to create a seamless experience for the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/managing-shared-credentials",
      "kind": "article",
      "role": "article",
      "title": "Managing Shared Credentials",
      "type": "topic",
      "url": "/documentation/security/managing-shared-credentials"
    },
    "media-2891900": {
      "alt": "Diagram showing a connection between your app and Safari through iCloud keychain.",
      "identifier": "media-2891900",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/16c0e75164ea683d623c490ddc60d300/media-2891900@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "First-Steps",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
        "doc://com.apple.security/documentation/Security/managing-shared-credentials"
      ],
      "title": "First Steps"
    },
    {
      "anchor": "Password-Sharing",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
        "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)",
        "doc://com.apple.security/documentation/Security/SecCreateSharedWebCredentialPassword()",
        "doc://com.apple.security/documentation/Security/kSecSharedPassword"
      ],
      "title": "Password Sharing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "First-Steps",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                "doc://com.apple.security/documentation/Security/managing-shared-credentials"
              ],
              "title": "First Steps"
            },
            {
              "anchor": "Password-Sharing",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SecAddSharedWebCredential(_:_:_:_:)",
                "doc://com.apple.security/documentation/Security/SecRequestSharedWebCredential(_:_:_:)",
                "doc://com.apple.security/documentation/Security/SecCreateSharedWebCredentialPassword()",
                "doc://com.apple.security/documentation/Security/kSecSharedPassword"
              ],
              "title": "Password Sharing"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequestSharedWebCredential(_:_:_:)/title",
          "value": "SecRequestSharedWebCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecRequestSharedWebCredential(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecRequestSharedWebCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSharedPassword/title",
          "value": "kSecSharedPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecSharedPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecSharedPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAddSharedWebCredential(_:_:_:_:)/title",
          "value": "SecAddSharedWebCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAddSharedWebCredential(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAddSharedWebCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCreateSharedWebCredentialPassword()/title",
          "value": "SecCreateSharedWebCredentialPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCreateSharedWebCredentialPassword()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCreateSharedWebCredentialPassword"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/shared-web-credentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/shared-web-credentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
