{
  "abstract": [
    {
      "text": "Use these keys from the information dictionary when you retrieve information from a code signature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/signing-information-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Signing Information Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys when examining the dictionary returned by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to obtain information about the signed code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves various pieces of information from a code signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCodeCopySigningInformation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCodeCopySigningInformation"
        }
      ],
      "role": "symbol",
      "title": "SecCodeCopySigningInformation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seccodecopysigninginformation(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoCMS": {
      "abstract": [
        {
          "text": "A key whose value is the CMS cryptographic object that secures the code signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoCMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCMS"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoCMS",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfocms"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoCdHashes": {
      "abstract": [
        {
          "text": "A key whose value is an array containing the unique binary identifier for every digest algorithm supported in the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCdHashes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoCdHashes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCdHashes"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoCdHashes",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfocdhashes"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoCertificates": {
      "abstract": [
        {
          "text": "A key whose value is an array of certificates representing the certificate chain of the signing certificate as seen by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCertificates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoCertificates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoCertificates"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoCertificates",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfocertificates"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoChangedFiles": {
      "abstract": [
        {
          "text": "A key whose value is a list of all files in the code that may have been modified by the process of signing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoChangedFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoChangedFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoChangedFiles"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoChangedFiles",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfochangedfiles"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDesignatedRequirement": {
      "abstract": [
        {
          "text": "A keys whose value is the designated requirement of the code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDesignatedRequirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDesignatedRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDesignatedRequirement"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDesignatedRequirement",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodesignatedrequirement"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm": {
      "abstract": [
        {
          "text": "A key whose value is a number indicating the cryptographic hash function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDigestAlgorithm",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodigestalgorithm"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms": {
      "abstract": [
        {
          "text": "A key whose value is a list of the kinds of cryptographic hash functions available within the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoDigestAlgorithms"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoDigestAlgorithms",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfodigestalgorithms"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlements": {
      "abstract": [
        {
          "text": "A key whose value represents the embedded entitlement blob of the code, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoEntitlements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoEntitlements"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoEntitlements",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoentitlements"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlementsDict": {
      "abstract": [
        {
          "text": "A key whose value is a dictionary of embedded entitlements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoEntitlementsDict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlementsDict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoEntitlementsDict"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoEntitlementsDict",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoentitlementsdict"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags": {
      "abstract": [
        {
          "text": "A key whose value indicates the static (on-disk) state of the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFlags"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoFlags",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoflags"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoFormat": {
      "abstract": [
        {
          "text": "A key whose value is a string representing the type and format of the code in a form suitable for display to a knowledgeable user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoFormat"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoFormat",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoformat"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoIdentifier": {
      "abstract": [
        {
          "text": "A key whose value is the signing identifier sealed into the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoIdentifier",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoidentifier"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoImplicitDesignatedRequirement": {
      "abstract": [
        {
          "text": "A key whose value is the designated requirement (DR) that the system generated—or would have generated—for the code in the absence of an explicitly-declared DR.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoImplicitDesignatedRequirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoImplicitDesignatedRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoImplicitDesignatedRequirement"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoImplicitDesignatedRequirement",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoimplicitdesignatedrequirement"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoMainExecutable": {
      "abstract": [
        {
          "text": "A key whose value is a URL locating the main executable file of the code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoMainExecutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoMainExecutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoMainExecutable"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoMainExecutable",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfomainexecutable"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoPList": {
      "abstract": [
        {
          "text": "A key whose value is an information dictionary containing the contents of the secured ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file as seen by Code Signing Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoPList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoPList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoPList"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoPList",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoplist"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoPlatformIdentifier": {
      "abstract": [
        {
          "text": "A key whose value identifies the operating system release with which the code is associated, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoPlatformIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoPlatformIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoPlatformIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoPlatformIdentifier",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoplatformidentifier"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirementData": {
      "abstract": [
        {
          "text": "A key whose value is the internal requirements of the code as a binary blob.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRequirementData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirementData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRequirementData"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoRequirementData",
      "type": "topic",
      "url": "/documentation/security/kseccodeinforequirementdata"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirements": {
      "abstract": [
        {
          "text": "A key whose value is the internal requirements of the code as a text string in canonical syntax.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRequirements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRequirements"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoRequirements",
      "type": "topic",
      "url": "/documentation/security/kseccodeinforequirements"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoRuntimeVersion": {
      "abstract": [
        {
          "text": "A key whose value represents the runtime version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRuntimeVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoRuntimeVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoRuntimeVersion"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoRuntimeVersion",
      "type": "topic",
      "url": "/documentation/security/kseccodeinforuntimeversion"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoSource": {
      "abstract": [
        {
          "text": "The source of the code signature used for the code object in a format suitable for display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoSource"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoSource",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfosource"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoStatus": {
      "abstract": [
        {
          "text": "A key whose value is the set of code status flags for the running code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoStatus"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoStatus",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfostatus"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoTeamIdentifier": {
      "abstract": [
        {
          "text": "A key whose value is the team identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTeamIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoTeamIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTeamIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoTeamIdentifier",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfoteamidentifier"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoTime": {
      "abstract": [
        {
          "text": "A key whose value is the signing date embedded in the code signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTime"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoTime",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfotime"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoTimestamp": {
      "abstract": [
        {
          "text": "A key whose value indicates the actual signing date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTimestamp"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoTimestamp",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfotimestamp"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoTrust": {
      "abstract": [
        {
          "text": "A key whose value is the trust object the system uses to evaluate the validity of the code’s signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTrust"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoTrust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoTrust"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoTrust",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfotrust"
    },
    "doc://com.apple.security/documentation/Security/kSecCodeInfoUnique": {
      "abstract": [
        {
          "text": "A key whose value is a binary number that uniquely identifies static code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCodeInfoUnique"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCodeInfoUnique",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCodeInfoUnique"
        }
      ],
      "role": "symbol",
      "title": "kSecCodeInfoUnique",
      "type": "topic",
      "url": "/documentation/security/kseccodeinfounique"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecCodeInfoCdHashes",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoCertificates",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoChangedFiles",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoCMS",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoDesignatedRequirement",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlements",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlementsDict",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoFormat",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoIdentifier",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoImplicitDesignatedRequirement",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoMainExecutable",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoPList",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoPlatformIdentifier",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirements",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirementData",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoRuntimeVersion",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoSource",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoStatus",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoTeamIdentifier",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoTime",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoTimestamp",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoTrust",
        "doc://com.apple.security/documentation/Security/kSecCodeInfoUnique"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecCodeInfoCdHashes",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoCertificates",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoChangedFiles",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoCMS",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoDesignatedRequirement",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithm",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoDigestAlgorithms",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlements",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoEntitlementsDict",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoFormat",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoFlags",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoIdentifier",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoImplicitDesignatedRequirement",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoMainExecutable",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoPList",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoPlatformIdentifier",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirements",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoRequirementData",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoRuntimeVersion",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoSource",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoStatus",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoTeamIdentifier",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoTime",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoTimestamp",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoTrust",
                "doc://com.apple.security/documentation/Security/kSecCodeInfoUnique"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoUnique/title",
          "value": "kSecCodeInfoUnique"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoUnique/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoUnique"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTeamIdentifier/title",
          "value": "kSecCodeInfoTeamIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTeamIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoTeamIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithm/title",
          "value": "kSecCodeInfoDigestAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDigestAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDesignatedRequirement/title",
          "value": "kSecCodeInfoDesignatedRequirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDesignatedRequirement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDesignatedRequirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoEntitlementsDict/title",
          "value": "kSecCodeInfoEntitlementsDict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoEntitlementsDict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoEntitlementsDict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTime/title",
          "value": "kSecCodeInfoTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoPList/title",
          "value": "kSecCodeInfoPList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoPList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoPList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCertificates/title",
          "value": "kSecCodeInfoCertificates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCertificates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoCertificates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoEntitlements/title",
          "value": "kSecCodeInfoEntitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoEntitlements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoEntitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoSource/title",
          "value": "kSecCodeInfoSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCdHashes/title",
          "value": "kSecCodeInfoCdHashes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCdHashes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoCdHashes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoIdentifier/title",
          "value": "kSecCodeInfoIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTimestamp/title",
          "value": "kSecCodeInfoTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRequirementData/title",
          "value": "kSecCodeInfoRequirementData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRequirementData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoRequirementData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoStatus/title",
          "value": "kSecCodeInfoStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTrust/title",
          "value": "kSecCodeInfoTrust"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoTrust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoTrust"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRuntimeVersion/title",
          "value": "kSecCodeInfoRuntimeVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRuntimeVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoRuntimeVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoMainExecutable/title",
          "value": "kSecCodeInfoMainExecutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoMainExecutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoMainExecutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCMS/title",
          "value": "kSecCodeInfoCMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoCMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoCMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/title",
          "value": "SecCodeCopySigningInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCodeCopySigningInformation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCodeCopySigningInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRequirements/title",
          "value": "kSecCodeInfoRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithms/title",
          "value": "kSecCodeInfoDigestAlgorithms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoDigestAlgorithms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoDigestAlgorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoChangedFiles/title",
          "value": "kSecCodeInfoChangedFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoChangedFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoChangedFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFormat/title",
          "value": "kSecCodeInfoFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoImplicitDesignatedRequirement/title",
          "value": "kSecCodeInfoImplicitDesignatedRequirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoImplicitDesignatedRequirement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoImplicitDesignatedRequirement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoPlatformIdentifier/title",
          "value": "kSecCodeInfoPlatformIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoPlatformIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoPlatformIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFlags/title",
          "value": "kSecCodeInfoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCodeInfoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCodeInfoFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/signing-information-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/signing-information-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
