{
  "abstract": [
    {
      "text": "Retrieves a trust management object for the certificate used by a session.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported. Use Network.framework.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SSLCopyPeerTrust(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SSLCopyPeerTrust",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SSLCopyPeerTrust"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SSLContextRef",
        "text": "SSLContext"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecTrustRef",
        "text": "SecTrust"
      },
      {
        "kind": "text",
        "text": "?>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLCopyPeerTrust"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "5.0",
        "message": "No longer supported. Use Network.framework.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "5.0",
        "message": "No longer supported. Use Network.framework.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "No longer supported. Use Network.framework.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.6",
        "message": "No longer supported. Use Network.framework.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SSLCopyPeerTrust(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLCopyPeerTrust"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SSLContextRef",
              "text": "SSLContext"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "trust"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecTrustRef",
              "text": "SecTrust"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An SSL session context reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, a trust management object you can use to evaluate trust for the certificate used by the session. A trust management object includes the certificate to be verified plus the policy or policies to be used in evaluating trust. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for functions to create and evaluate trust management objects. You must call the ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": " function for this object when you are finished with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "trust"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is valid any time after a handshake attempt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLContext": {
      "abstract": [
        {
          "text": "An opaque type that represents an SSL session context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "role": "symbol",
      "title": "SSLContext",
      "type": "topic",
      "url": "/documentation/security/sslcontext"
    },
    "doc://com.apple.security/documentation/Security/SSLCopyPeerTrust(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a trust management object for the certificate used by a session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLCopyPeerTrust"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLCopyPeerTrust(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLCopyPeerTrust"
        }
      ],
      "role": "symbol",
      "title": "SSLCopyPeerTrust(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslcopypeertrust(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrust": {
      "abstract": [
        {
          "text": "An object used to evaluate trust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "role": "symbol",
      "title": "SecTrust",
      "type": "topic",
      "url": "/documentation/security/sectrust"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/secure-transport-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the secure transport API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Secure Transport Result Codes",
      "type": "topic",
      "url": "/documentation/security/secure-transport-result-codes"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SSLCopyPeerTrust"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLCopyPeerTrust"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SSLCopyPeerTrust"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SSLContextRef",
                    "text": "SSLContextRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecTrustRef",
                    "text": "SecTrustRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "trust"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An SSL session context reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, a trust management object you can use to evaluate trust for the certificate used by the session. A trust management object includes the certificate to be verified plus the policy or policies to be used in evaluating trust. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for functions to create and evaluate trust management objects. You must call the ",
                        "type": "text"
                      },
                      {
                        "code": "CFRelease",
                        "type": "codeVoice"
                      },
                      {
                        "text": " function for this object when you are finished with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "trust"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported. Use Network.framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/title",
          "value": "SSLContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCopyPeerTrust(_:_:)/title",
          "value": "SSLCopyPeerTrust"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCopyPeerTrust(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLCopyPeerTrust"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/title",
          "value": "SecTrustRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslcopypeertrust(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sslcopypeertrust(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
