{
  "abstract": [
    {
      "text": "Use these constants to configure Transport Layer Security (TLS) sessions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/secure-transport"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/sslconfig"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SSLConfig"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_3DES_fallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_3DES_fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_3DES_fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_3DES_fallback"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_3DES_fallback",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_3des_fallback"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_ATSv1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_ATSv1"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_ATSv1",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_atsv1"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1_noPFS": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_ATSv1_noPFS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1_noPFS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_ATSv1_noPFS"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_ATSv1_noPFS",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_atsv1_nopfs"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_RC4_fallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_RC4_fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_RC4_fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_RC4_fallback"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_RC4_fallback",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_rc4_fallback"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_3DES_fallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_3DES_fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_3DES_fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_3DES_fallback"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_TLSv1_3DES_fallback",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_tlsv1_3des_fallback"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_RC4_fallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_RC4_fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_RC4_fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_RC4_fallback"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_TLSv1_RC4_fallback",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_tlsv1_rc4_fallback"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_fallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_TLSv1_fallback"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_TLSv1_fallback",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_tlsv1_fallback"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_anonymous": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_anonymous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_anonymous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_anonymous"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_anonymous",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_anonymous"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_default": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_default"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_default"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_default",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_default"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_legacy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_legacy"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_legacy",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_legacy"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy_DHE": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_legacy_DHE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy_DHE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_legacy_DHE"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_legacy_DHE",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_legacy_dhe"
    },
    "doc://com.apple.security/documentation/Security/kSSLSessionConfig_standard": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_standard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSSLSessionConfig_standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionConfig_standard"
        }
      ],
      "role": "symbol",
      "title": "kSSLSessionConfig_standard",
      "type": "topic",
      "url": "/documentation/security/ksslsessionconfig_standard"
    },
    "doc://com.apple.security/documentation/Security/secure-transport": {
      "abstract": [
        {
          "text": "Secure network communication using standardized transport layer security mechanisms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/secure-transport",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Secure Transport",
      "type": "topic",
      "url": "/documentation/security/secure-transport"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_3DES_fallback",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1_noPFS",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_RC4_fallback",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_3DES_fallback",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_RC4_fallback",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_fallback",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_anonymous",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_default",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy_DHE",
        "doc://com.apple.security/documentation/Security/kSSLSessionConfig_standard"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_3DES_fallback",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_ATSv1_noPFS",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_RC4_fallback",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_3DES_fallback",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_RC4_fallback",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_TLSv1_fallback",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_anonymous",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_default",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_legacy_DHE",
                "doc://com.apple.security/documentation/Security/kSSLSessionConfig_standard"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_ATSv1/title",
          "value": "kSSLSessionConfig_ATSv1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_ATSv1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_ATSv1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_3DES_fallback/title",
          "value": "kSSLSessionConfig_TLSv1_3DES_fallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_3DES_fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_TLSv1_3DES_fallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_default/title",
          "value": "kSSLSessionConfig_default"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_default"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_RC4_fallback/title",
          "value": "kSSLSessionConfig_RC4_fallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_RC4_fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_RC4_fallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_3DES_fallback/title",
          "value": "kSSLSessionConfig_3DES_fallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_3DES_fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_3DES_fallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_fallback/title",
          "value": "kSSLSessionConfig_TLSv1_fallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_TLSv1_fallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_anonymous/title",
          "value": "kSSLSessionConfig_anonymous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_anonymous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_anonymous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_legacy_DHE/title",
          "value": "kSSLSessionConfig_legacy_DHE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_legacy_DHE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_legacy_DHE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_standard/title",
          "value": "kSSLSessionConfig_standard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_standard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_legacy/title",
          "value": "kSSLSessionConfig_legacy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_legacy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_legacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_ATSv1_noPFS/title",
          "value": "kSSLSessionConfig_ATSv1_noPFS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_ATSv1_noPFS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_ATSv1_noPFS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_RC4_fallback/title",
          "value": "kSSLSessionConfig_TLSv1_RC4_fallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSSLSessionConfig_TLSv1_RC4_fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionConfig_TLSv1_RC4_fallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslconfig"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sslconfig"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
