{
  "abstract": [
    {
      "text": "Disposes of a Secure Sockets Layer (SSL) session context.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "You use this function to dispose of a context that you create with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLNewContext",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", but that function is deprecated. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLCreateContext(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to create a new context and use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to dispose of that context.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SSLDisposeContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SSLDisposeContext",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SSLDisposeContext"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLDisposeContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SSLDisposeContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLDisposeContext"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SSLContextRef",
              "text": "SSLContextRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A reference to the SSL session context to dispose.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you are completely finished with a secure session, you should dispose of the SSL session context in order to release the memory associated with the session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLContext": {
      "abstract": [
        {
          "text": "An opaque type that represents an SSL session context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "role": "symbol",
      "title": "SSLContext",
      "type": "topic",
      "url": "/documentation/security/sslcontext"
    },
    "doc://com.apple.security/documentation/Security/SSLCreateContext(_:_:_:)": {
      "abstract": [
        {
          "text": "Allocates and returns a new context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLCreateContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SSLProtocolSide",
          "text": "SSLProtocolSide"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SSLConnectionType",
          "text": "SSLConnectionType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLCreateContext(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLCreateContext"
        }
      ],
      "role": "symbol",
      "title": "SSLCreateContext(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslcreatecontext(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLDisposeContext": {
      "abstract": [
        {
          "text": "Disposes of a Secure Sockets Layer (SSL) session context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLDisposeContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLDisposeContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLDisposeContext",
      "type": "topic",
      "url": "/documentation/security/ssldisposecontext"
    },
    "doc://com.apple.security/documentation/Security/SSLNewContext": {
      "abstract": [
        {
          "text": "Creates a new Secure Sockets Layer (SSL) session context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLNewContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLNewContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLNewContext",
      "type": "topic",
      "url": "/documentation/security/sslnewcontext"
    },
    "doc://com.apple.security/documentation/Security/secure-transport-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the secure transport API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Secure Transport Result Codes",
      "type": "topic",
      "url": "/documentation/security/secure-transport-result-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCreateContext(_:_:_:)/title",
          "value": "SSLCreateContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCreateContext(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLCreateContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/title",
          "value": "SSLContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/ssldisposecontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
