{
  "abstract": [
    {
      "text": "Performs the SSL handshake.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported. Use Network.framework.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SSLHandshake",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SSLHandshake"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SSLContextRef",
        "text": "SSLContext"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLHandshake"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "5.0",
        "message": "No longer supported. Use Network.framework.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "5.0",
        "message": "No longer supported. Use Network.framework.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "No longer supported. Use Network.framework.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.2",
        "message": "No longer supported. Use Network.framework.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SSLHandshake(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLHandshake"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SSLContextRef",
              "text": "SSLContext"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An SSL session context reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.security/documentation/Security/using-the-secure-socket-layer-for-network-communication"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On successful return, the session is ready for normal secure communication using the functions ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLRead(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLWrite(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If it finds any problems with the peer’s certificate chain, Secure Transport aborts the handshake. You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLCopyPeerCertificates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to see the peer’s certificate chain. This function can return a wide variety of result codes, including the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLUnknownRootCert",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The peer has a valid certificate chain, but the root of the chain is not a known anchor certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLNoRootCert",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The peer’s certificate chain was not verifiable to a root certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLCertExpired",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The peer’s certificate chain has one or more expired certificates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLXCertChainInvalid",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The peer has an invalid certificate chain; for example, signature verification within the chain failed, or no certificates were found.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLClientCertRequested",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The server has requested a client certificate. This result is returned only if you called the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function to set the ",
                      "type": "text"
                    },
                    {
                      "code": "kSSLSessionOptionBreakOnCertRequested",
                      "type": "codeVoice"
                    },
                    {
                      "text": " option. After receiving this result, you must call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLSetCertificate(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function to return the client certificate, and then call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " again to resume the handshake. Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLCopyDistinguishedNames(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function to obtain a list of certificates acceptable to the server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "errSSLServerAuthCompleted",
                      "type": "codeVoice"
                    },
                    {
                      "text": "—The server authentication portion of the handshake is complete. This result is returned only if you called the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function to set the ",
                      "type": "text"
                    },
                    {
                      "code": "kSSLSessionOptionBreakOnServerAuth",
                      "type": "codeVoice"
                    },
                    {
                      "text": " option, and provides an opportunity to perform application-specific server verification before calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " again to continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Note that in macOS prior to version 10.8, you must also explicitly call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLSetEnableCertVerify",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to disable verification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A return value of ",
              "type": "text"
            },
            {
              "code": "errSSLWouldBlock",
              "type": "codeVoice"
            },
            {
              "text": " indicates that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function must be called again until a different result code is returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLContext": {
      "abstract": [
        {
          "text": "An opaque type that represents an SSL session context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "role": "symbol",
      "title": "SSLContext",
      "type": "topic",
      "url": "/documentation/security/sslcontext"
    },
    "doc://com.apple.security/documentation/Security/SSLCopyDistinguishedNames(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the distinguished names of acceptable certification authorities.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLCopyDistinguishedNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLCopyDistinguishedNames(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLCopyDistinguishedNames"
        }
      ],
      "role": "symbol",
      "title": "SSLCopyDistinguishedNames(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslcopydistinguishednames(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLCopyPeerCertificates": {
      "abstract": [
        {
          "text": "Retrieves a peer certificate and its certificate chain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLCopyPeerCertificates"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLCopyPeerCertificates",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLCopyPeerCertificates",
      "type": "topic",
      "url": "/documentation/security/sslcopypeercertificates"
    },
    "doc://com.apple.security/documentation/Security/SSLHandshake(_:)": {
      "abstract": [
        {
          "text": "Performs the SSL handshake.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        }
      ],
      "role": "symbol",
      "title": "SSLHandshake(_:)",
      "type": "topic",
      "url": "/documentation/security/sslhandshake(_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLRead(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a normal application-level read operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLRead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLRead(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLRead"
        }
      ],
      "role": "symbol",
      "title": "SSLRead(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslread(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLSetCertificate(_:_:)": {
      "abstract": [
        {
          "text": "Specifies this connection’s certificate or certificates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLSetCertificate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetCertificate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLSetCertificate"
        }
      ],
      "role": "symbol",
      "title": "SSLSetCertificate(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslsetcertificate(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLSetEnableCertVerify": {
      "abstract": [
        {
          "text": "Enables or disables peer certificate chain validation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLSetEnableCertVerify"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetEnableCertVerify",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLSetEnableCertVerify",
      "type": "topic",
      "url": "/documentation/security/sslsetenablecertverify"
    },
    "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies options for a specific session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SSLSessionOption",
          "text": "SSLSessionOption"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        }
      ],
      "role": "symbol",
      "title": "SSLSetSessionOption(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslsetsessionoption(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLWrite(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a typical application-level write operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLWrite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLWrite(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLWrite"
        }
      ],
      "role": "symbol",
      "title": "SSLWrite(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslwrite(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/secure-transport-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the secure transport API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Secure Transport Result Codes",
      "type": "topic",
      "url": "/documentation/security/secure-transport-result-codes"
    },
    "doc://com.apple.security/documentation/Security/using-the-secure-socket-layer-for-network-communication": {
      "abstract": [
        {
          "text": "Establish Secure Sockets Layer (SSL) sessions to facilitate secure communication between client and server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/using-the-secure-socket-layer-for-network-communication",
      "kind": "article",
      "role": "article",
      "title": "Using the Secure Socket Layer for Network Communication",
      "type": "topic",
      "url": "/documentation/security/using-the-secure-socket-layer-for-network-communication"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SSLHandshake"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLHandshake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SSLHandshake"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SSLContextRef",
                    "text": "SSLContextRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An SSL session context reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported. Use Network.framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCopyDistinguishedNames(_:_:)/title",
          "value": "SSLCopyDistinguishedNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLCopyDistinguishedNames(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLCopyDistinguishedNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetCertificate(_:_:)/title",
          "value": "SSLSetCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetCertificate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSetCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLRead(_:_:_:_:)/title",
          "value": "SSLRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLRead(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLWrite(_:_:_:_:)/title",
          "value": "SSLWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLWrite(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/title",
          "value": "SSLHandshake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLHandshake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/title",
          "value": "SSLSetSessionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSetSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/title",
          "value": "SSLContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslhandshake(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sslhandshake(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
