{
  "abstract": [
    {
      "text": "An enumeration of valid SSL protocol versions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SSLProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SSLProtocol",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SSLProtocol"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SSLProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The descriptions given here apply to the functions ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLSetProtocolVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLGetProtocolVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For the functions ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLSetProtocolVersionEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLGetProtocolVersionEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", only the following values are used. For these functions, each constant except ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " specifies a single protocol version.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol2",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLGetProtocolVersion": {
      "abstract": [
        {
          "text": "Gets the SSL protocol version.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLGetProtocolVersion"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLGetProtocolVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLGetProtocolVersion",
      "type": "topic",
      "url": "/documentation/security/sslgetprotocolversion"
    },
    "doc://com.apple.security/documentation/Security/SSLGetProtocolVersionEnabled": {
      "abstract": [
        {
          "text": "Retrieves the enabled status of a given protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLGetProtocolVersionEnabled"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLGetProtocolVersionEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLGetProtocolVersionEnabled",
      "type": "topic",
      "url": "/documentation/security/sslgetprotocolversionenabled"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol": {
      "abstract": [
        {
          "text": "An enumeration of valid SSL protocol versions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLProtocol"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLProtocol"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol",
      "type": "topic",
      "url": "/documentation/security/sslprotocol"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol1": {
      "abstract": [
        {
          "text": "Specifies the DTLS 1.0 protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dtlsProtocol1"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDTLSProtocol1"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.dtlsProtocol1",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/dtlsprotocol1"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol12": {
      "abstract": [
        {
          "text": "Specifies the DTLS 1.2 protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dtlsProtocol12"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDTLSProtocol12"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.dtlsProtocol12",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/dtlsprotocol12"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol2": {
      "abstract": [
        {
          "text": "Specifies that only the SSL 2.0 protocol may be negotiated. Deprecated in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sslProtocol2"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLProtocol2"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.sslProtocol2",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/sslprotocol2"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3": {
      "abstract": [
        {
          "text": "Specifies that the SSL 3.0 protocol is preferred; the SSL 2.0 protocol may be negotiated if the peer cannot use the SSL 3.0 protocol.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sslProtocol3"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLProtocol3"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.sslProtocol3",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/sslprotocol3"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3Only": {
      "abstract": [
        {
          "text": "Specifies that only the SSL 3.0 protocol may be negotiated; fails if the peer tries to negotiate the SSL 2.0 protocol. Deprecated in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sslProtocol3Only"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3Only",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLProtocol3Only"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.sslProtocol3Only",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/sslprotocol3only"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll": {
      "abstract": [
        {
          "text": "Specifies all supported versions. Deprecated in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sslProtocolAll"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLProtocolAll"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.sslProtocolAll",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/sslprotocolall"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolUnknown": {
      "abstract": [
        {
          "text": "Specifies that no protocol has been or should be negotiated or specified; use default.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sslProtocolUnknown"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLProtocolUnknown"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.sslProtocolUnknown",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/sslprotocolunknown"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1": {
      "abstract": [
        {
          "text": "Specifies that the TLS 1.0 protocol is preferred but lower versions may be negotiated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocol1"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocol1"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocol1",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocol1"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol11": {
      "abstract": [
        {
          "text": "Specifies that the TLS 1.1 protocol is preferred but lower versions may be negotiated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocol11"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocol11"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocol11",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocol11"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol12": {
      "abstract": [
        {
          "text": "Specifies that the TLS 1.2 protocol is preferred but lower versions may be negotiated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocol12"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocol12"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocol12",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocol12"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol13": {
      "abstract": [
        {
          "text": "Specifies that the TLS 1.3 protocol is preferred but lower versions may be negotiated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocol13"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocol13"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocol13",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocol13"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1Only": {
      "abstract": [
        {
          "text": "Specifies that only the TLS 1.0 protocol may be negotiated. Deprecated in iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocol1Only"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1Only",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocol1Only"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocol1Only",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocol1only"
    },
    "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocolMaxSupported": {
      "abstract": [
        {
          "text": "The maximum system supported version.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlsProtocolMaxSupported"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocolMaxSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kTLSProtocolMaxSupported"
        }
      ],
      "role": "symbol",
      "title": "SSLProtocol.tlsProtocolMaxSupported",
      "type": "topic",
      "url": "/documentation/security/sslprotocol/tlsprotocolmaxsupported"
    },
    "doc://com.apple.security/documentation/Security/SSLSetProtocolVersion": {
      "abstract": [
        {
          "text": "Sets the SSL protocol version.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLSetProtocolVersion"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetProtocolVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLSetProtocolVersion",
      "type": "topic",
      "url": "/documentation/security/sslsetprotocolversion"
    },
    "doc://com.apple.security/documentation/Security/SSLSetProtocolVersionEnabled": {
      "abstract": [
        {
          "text": "Sets the allowed Secure Sockets Layer (SSL) protocol versions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLSetProtocolVersionEnabled"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetProtocolVersionEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLSetProtocolVersionEnabled",
      "type": "topic",
      "url": "/documentation/security/sslsetprotocolversionenabled"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "SSL-Protocols",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolUnknown",
        "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol2",
        "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3",
        "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3Only",
        "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll"
      ],
      "title": "SSL Protocols"
    },
    {
      "anchor": "TLS-Protocols",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1",
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1Only",
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol11",
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol12",
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol13",
        "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocolMaxSupported"
      ],
      "title": "TLS Protocols"
    },
    {
      "anchor": "DTLS-Protocols",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol1",
        "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol12"
      ],
      "title": "DTLS Protocols"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLProtocol/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SSLProtocol"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "SSL-Protocols",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolUnknown",
                "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol2",
                "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3",
                "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocol3Only",
                "doc://com.apple.security/documentation/Security/SSLProtocol/sslProtocolAll"
              ],
              "title": "SSL Protocols"
            },
            {
              "anchor": "TLS-Protocols",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1",
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol1Only",
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol11",
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol12",
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocol13",
                "doc://com.apple.security/documentation/Security/SSLProtocol/tlsProtocolMaxSupported"
              ],
              "title": "TLS Protocols"
            },
            {
              "anchor": "DTLS-Protocols",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol1",
                "doc://com.apple.security/documentation/Security/SSLProtocol/dtlsProtocol12"
              ],
              "title": "DTLS Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SSLProtocol"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol12/title",
          "value": "kTLSProtocol12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocol12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol/title",
          "value": "SSLProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1dtlsProtocol1/title",
          "value": "kDTLSProtocol1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1dtlsProtocol1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDTLSProtocol1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol13/title",
          "value": "kTLSProtocol13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocol13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol2/title",
          "value": "kSSLProtocol2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLProtocol2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1dtlsProtocol12/title",
          "value": "kDTLSProtocol12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1dtlsProtocol12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDTLSProtocol12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol3/title",
          "value": "kSSLProtocol3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLProtocol3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol11/title",
          "value": "kTLSProtocol11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocol11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol3Only/title",
          "value": "kSSLProtocol3Only"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocol3Only/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLProtocol3Only"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocolMaxSupported/title",
          "value": "kTLSProtocolMaxSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocolMaxSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocolMaxSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol1Only/title",
          "value": "kTLSProtocol1Only"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol1Only/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocol1Only"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol1/title",
          "value": "kTLSProtocol1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1tlsProtocol1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kTLSProtocol1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocolUnknown/title",
          "value": "kSSLProtocolUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocolUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLProtocolUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocolAll/title",
          "value": "kSSLProtocolAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLProtocol~1sslProtocolAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLProtocolAll"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sslprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
