{
  "abstract": [
    {
      "text": "The options that can be set for an SSL session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SSLSessionOption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SSLSessionOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SSLSessionOption"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLSessionOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SSLSessionOption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLSessionOption"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these flags with calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLHandshake(_:)": {
      "abstract": [
        {
          "text": "Performs the SSL handshake.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        }
      ],
      "role": "symbol",
      "title": "SSLHandshake(_:)",
      "type": "topic",
      "url": "/documentation/security/sslhandshake(_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption": {
      "abstract": [
        {
          "text": "The options that can be set for an SSL session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLSessionOption"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLSessionOption"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/allowRenegotiation": {
      "abstract": [
        {
          "text": "Allow renegotiation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowRenegotiation"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/allowRenegotiation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionAllowRenegotiation"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.allowRenegotiation",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/allowrenegotiation"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/allowServerIdentityChange": {
      "abstract": [
        {
          "text": "Allow server identity change on renegotiation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowServerIdentityChange"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/allowServerIdentityChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionAllowServerIdentityChange"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.allowServerIdentityChange",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/allowserveridentitychange"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnCertRequested": {
      "abstract": [
        {
          "text": "Enables returning from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " (with a result of ",
          "type": "text"
        },
        {
          "code": "errSSLClientCertRequested",
          "type": "codeVoice"
        },
        {
          "text": ") when the server requests a client certificate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakOnCertRequested"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnCertRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionBreakOnCertRequested"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.breakOnCertRequested",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/breakoncertrequested"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientAuth": {
      "abstract": [
        {
          "text": "Enables returning from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " (with a result of ",
          "type": "text"
        },
        {
          "code": "errSSLClientAuthCompleted",
          "type": "codeVoice"
        },
        {
          "text": ") when the client authentication portion of the handshake is complete to allow your application to perform its own certificate verification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakOnClientAuth"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientAuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionBreakOnClientAuth"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.breakOnClientAuth",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/breakonclientauth"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientHello": {
      "abstract": [
        {
          "text": "Break from a client hello in order to check for SNI.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakOnClientHello"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientHello",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionBreakOnClientHello"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.breakOnClientHello",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/breakonclienthello"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth": {
      "abstract": [
        {
          "text": "Enables returning from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " (with a result of ",
          "type": "text"
        },
        {
          "code": "errSSLServerAuthCompleted",
          "type": "codeVoice"
        },
        {
          "text": ") when the server authentication portion of the handshake is complete to allow your application to perform its own certificate verification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakOnServerAuth"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionBreakOnServerAuth"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.breakOnServerAuth",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/breakonserverauth"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/enableSessionTickets": {
      "abstract": [
        {
          "text": "Enable session tickets.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableSessionTickets"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/enableSessionTickets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionEnableSessionTickets"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.enableSessionTickets",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/enablesessiontickets"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/fallback": {
      "abstract": [
        {
          "text": "Enable fallback countermeasures.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fallback"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/fallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionFallback"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.fallback",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/fallback"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/falseStart": {
      "abstract": [
        {
          "text": "When enabled, TLS False Start is used if an adequate cipher-suite is negotiated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "falseStart"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/falseStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionFalseStart"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.falseStart",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/falsestart"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/init(rawvalue:)"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/sendOneByteRecord": {
      "abstract": [
        {
          "text": "Enables ",
          "type": "text"
        },
        {
          "code": "1/n-1",
          "type": "codeVoice"
        },
        {
          "text": " record splitting for BEAST attack mitigation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendOneByteRecord"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/sendOneByteRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionSendOneByteRecord"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.sendOneByteRecord",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/sendonebyterecord"
    },
    "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies options for a specific session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SSLSessionOption",
          "text": "SSLSessionOption"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        }
      ],
      "role": "symbol",
      "title": "SSLSetSessionOption(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslsetsessionoption(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnCertRequested",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientAuth",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/falseStart",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/sendOneByteRecord",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/allowServerIdentityChange",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/fallback",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientHello",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/allowRenegotiation",
        "doc://com.apple.security/documentation/Security/SSLSessionOption/enableSessionTickets"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SSLSessionOption/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SSLSessionOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnCertRequested",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientAuth",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/falseStart",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/sendOneByteRecord",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/allowServerIdentityChange",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/fallback",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnClientHello",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/allowRenegotiation",
                "doc://com.apple.security/documentation/Security/SSLSessionOption/enableSessionTickets"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SSLSessionOption"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnServerAuth/title",
          "value": "kSSLSessionOptionBreakOnServerAuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnServerAuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionBreakOnServerAuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption/title",
          "value": "SSLSessionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1allowServerIdentityChange/title",
          "value": "kSSLSessionOptionAllowServerIdentityChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1allowServerIdentityChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionAllowServerIdentityChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/title",
          "value": "SSLSetSessionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSetSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1falseStart/title",
          "value": "kSSLSessionOptionFalseStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1falseStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionFalseStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnCertRequested/title",
          "value": "kSSLSessionOptionBreakOnCertRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnCertRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionBreakOnCertRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1allowRenegotiation/title",
          "value": "kSSLSessionOptionAllowRenegotiation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1allowRenegotiation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionAllowRenegotiation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1fallback/title",
          "value": "kSSLSessionOptionFallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1fallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionFallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnClientAuth/title",
          "value": "kSSLSessionOptionBreakOnClientAuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnClientAuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionBreakOnClientAuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/title",
          "value": "SSLHandshake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLHandshake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1enableSessionTickets/title",
          "value": "kSSLSessionOptionEnableSessionTickets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1enableSessionTickets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionEnableSessionTickets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1sendOneByteRecord/title",
          "value": "kSSLSessionOptionSendOneByteRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1sendOneByteRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionSendOneByteRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnClientHello/title",
          "value": "kSSLSessionOptionBreakOnClientHello"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnClientHello/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionBreakOnClientHello"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslsessionoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/sslsessionoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
