{
  "abstract": [
    {
      "text": "Specifies whether certificate expiration times are ignored.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "To ignore expired certificate errors, first disable Secure Transport’s automatic verification of peer certificates by calling ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to set ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to true. When ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subsequently returns an ",
          "type": "text"
        },
        {
          "code": "errSSLServerAuthCompleted",
          "type": "codeVoice"
        },
        {
          "text": " result, obtain the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the peer’s certificates and perform a custom trust evaluation with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " APIs (see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/trust",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " section of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "type": "paragraph"
    },
    {
      "inlineContent": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetOptions(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function allows you to specify that the expiration status of certificates should be ignored for this evaluation.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredCerts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SSLSetAllowsExpiredCerts",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SSLSetAllowsExpiredCerts"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SSLSetAllowsExpiredCerts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SSLSetAllowsExpiredCerts"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SSLSetAllowsExpiredCerts"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SSLContextRef",
              "text": "SSLContextRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Boolean",
              "text": "Boolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allowsExpired"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An SSL session context reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean flag representing whether the certificate expiration times are ignored. The default for this flag is ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ", meaning expired certificates result in an ",
                  "type": "text"
                },
                {
                  "code": "errSSLCertExpired",
                  "type": "codeVoice"
                },
                {
                  "text": " result code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowsExpired"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use this function to allow the handshake to succeed even if one or more certificates in the certificate chain have expired. You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLGetAllowsExpiredCerts",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to determine the current setting of the ",
              "type": "text"
            },
            {
              "code": "allowsExpired",
              "type": "codeVoice"
            },
            {
              "text": " flag.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredRoots",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to set a flag specifying whether expired root certificates are allowed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SSLContext": {
      "abstract": [
        {
          "text": "An opaque type that represents an SSL session context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLContext"
        }
      ],
      "role": "symbol",
      "title": "SSLContext",
      "type": "topic",
      "url": "/documentation/security/sslcontext"
    },
    "doc://com.apple.security/documentation/Security/SSLGetAllowsExpiredCerts": {
      "abstract": [
        {
          "text": "Retrieves the value specifying whether expired certificates are allowed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLGetAllowsExpiredCerts"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLGetAllowsExpiredCerts",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLGetAllowsExpiredCerts",
      "type": "topic",
      "url": "/documentation/security/sslgetallowsexpiredcerts"
    },
    "doc://com.apple.security/documentation/Security/SSLHandshake(_:)": {
      "abstract": [
        {
          "text": "Performs the SSL handshake.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLHandshake"
        }
      ],
      "role": "symbol",
      "title": "SSLHandshake(_:)",
      "type": "topic",
      "url": "/documentation/security/sslhandshake(_:)"
    },
    "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth": {
      "abstract": [
        {
          "text": "Enables returning from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.security/documentation/Security/SSLHandshake(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " (with a result of ",
          "type": "text"
        },
        {
          "code": "errSSLServerAuthCompleted",
          "type": "codeVoice"
        },
        {
          "text": ") when the server authentication portion of the handshake is complete to allow your application to perform its own certificate verification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakOnServerAuth"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSessionOption/breakOnServerAuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSSLSessionOptionBreakOnServerAuth"
        }
      ],
      "role": "symbol",
      "title": "SSLSessionOption.breakOnServerAuth",
      "type": "topic",
      "url": "/documentation/security/sslsessionoption/breakonserverauth"
    },
    "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredCerts": {
      "abstract": [
        {
          "text": "Specifies whether certificate expiration times are ignored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLSetAllowsExpiredCerts"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredCerts",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLSetAllowsExpiredCerts",
      "type": "topic",
      "url": "/documentation/security/sslsetallowsexpiredcerts"
    },
    "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredRoots": {
      "abstract": [
        {
          "text": "Specifies whether expired root certificates are allowed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "SSLSetAllowsExpiredRoots"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetAllowsExpiredRoots",
      "kind": "symbol",
      "role": "symbol",
      "title": "SSLSetAllowsExpiredRoots",
      "type": "topic",
      "url": "/documentation/security/sslsetallowsexpiredroots"
    },
    "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies options for a specific session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SSLContextRef",
          "text": "SSLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SSLSessionOption",
          "text": "SSLSessionOption"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SSLSetSessionOption(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSLSetSessionOption"
        }
      ],
      "role": "symbol",
      "title": "SSLSetSessionOption(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/sslsetsessionoption(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecTrust": {
      "abstract": [
        {
          "text": "An object used to evaluate trust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrust"
        }
      ],
      "role": "symbol",
      "title": "SecTrust",
      "type": "topic",
      "url": "/documentation/security/sectrust"
    },
    "doc://com.apple.security/documentation/Security/SecTrustSetOptions(_:_:)": {
      "abstract": [
        {
          "text": "Sets option flags for customizing evaluation of a trust object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustSetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecTrustOptionFlags",
          "text": "SecTrustOptionFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustSetOptions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustSetOptions"
        }
      ],
      "role": "symbol",
      "title": "SecTrustSetOptions(_:_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustsetoptions(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/secure-transport-result-codes": {
      "abstract": [
        {
          "text": "Recognize result codes specific to the secure transport API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/secure-transport-result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Secure Transport Result Codes",
      "type": "topic",
      "url": "/documentation/security/secure-transport-result-codes"
    },
    "doc://com.apple.security/documentation/Security/trust": {
      "abstract": [
        {
          "text": "Evaluate trust based on a given policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/trust",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Trust",
      "type": "topic",
      "url": "/documentation/security/trust"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/title",
          "value": "SSLSetSessionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSetSessionOption(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLSetSessionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/title",
          "value": "SecTrustRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrust/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/title",
          "value": "SSLContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnServerAuth/title",
          "value": "kSSLSessionOptionBreakOnServerAuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLSessionOption~1breakOnServerAuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSSLSessionOptionBreakOnServerAuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetOptions(_:_:)/title",
          "value": "SecTrustSetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustSetOptions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustSetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/title",
          "value": "SSLHandshake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SSLHandshake(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSLHandshake"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/sslsetallowsexpiredcerts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
