{
  "abstract": [
    {
      "text": "Use special OIDs to cause a certificate to be evaluated based on security policies specific to a given type of certificate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/policies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/standard-policies-for-specific-certificate-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Standard Policies for Specific Certificate Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleCodeSigning": {
      "abstract": [
        {
          "text": "Policy for use in evaluating Apple code signing certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleCodeSigning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleCodeSigning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleCodeSigning"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleCodeSigning",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplecodesigning"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleEAP": {
      "abstract": [
        {
          "text": "Extensible Authentication Protocol. Functionally identical to SSL policy. A separate OID is provided to facilitate per-policy, per-certificate trust settings using the ",
          "type": "text"
        },
        {
          "code": "SecTrust",
          "type": "codeVoice"
        },
        {
          "text": " mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleEAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleEAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleEAP"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleEAP",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappleeap"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleIDValidation": {
      "abstract": [
        {
          "text": "Policy for use in evaluating Apple ID certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleIDValidation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleIDValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleIDValidation"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleIDValidation",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappleidvalidation"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleIPsec": {
      "abstract": [
        {
          "text": "Policy for use in IPsec communication. Functionally identical to SSL policy. A separate OID is provided to facilitate per-policy, per-certificate trust settings using the ",
          "type": "text"
        },
        {
          "code": "SecTrust",
          "type": "codeVoice"
        },
        {
          "text": " mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleIPsec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleIPsec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleIPsec"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleIPsec",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappleipsec"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITClient": {
      "abstract": [
        {
          "text": "Kerberos Pkinit client certificate validation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePKINITClient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePKINITClient"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyApplePKINITClient",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplepkinitclient"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITServer": {
      "abstract": [
        {
          "text": "Kerberos Pkinit server certificate validation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePKINITServer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePKINITServer"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyApplePKINITServer",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplepkinitserver"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyApplePassbookSigning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePassbookSigning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyApplePassbookSigning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePassbookSigning"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyApplePassbookSigning",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplepassbooksigning"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyApplePayIssuerEncryption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePayIssuerEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyApplePayIssuerEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyApplePayIssuerEncryption"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyApplePayIssuerEncryption",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplepayissuerencryption"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleRevocation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleRevocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleRevocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleRevocation"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleRevocation",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplerevocation"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleSMIME": {
      "abstract": [
        {
          "text": "Basic X509 plus email address verification and ",
          "type": "text"
        },
        {
          "code": "KeyUsage",
          "type": "codeVoice"
        },
        {
          "text": " enforcement per RFC 2632.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleSMIME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleSMIME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleSMIME"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleSMIME",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplesmime"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleSSL": {
      "abstract": [
        {
          "text": "Basic X509 plus host name verification per RFC 2818.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleSSL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleSSL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleSSL"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleSSL",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplessl"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping": {
      "abstract": [
        {
          "text": "Policy that causes evaluation of the validity of the time stamp on a signature. This can be used to allow verification that a certificate was valid at the time that something was signed with that certificate even if the certificate is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleTimeStamping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleTimeStamping"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleTimeStamping",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappletimestamping"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleX509Basic": {
      "abstract": [
        {
          "text": "Basic X509-style certificate evaluation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleX509Basic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleX509Basic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleX509Basic"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyAppleX509Basic",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyapplex509basic"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyAppleiChat": {
      "abstract": [
        {
          "text": "Policy for use in iChat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSecPolicyAppleiChat"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyAppleiChat",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecPolicyAppleiChat",
      "type": "topic",
      "url": "/documentation/security/ksecpolicyappleichat"
    },
    "doc://com.apple.security/documentation/Security/kSecPolicyMacAppStoreReceipt": {
      "abstract": [
        {
          "text": "Policy for use in evaluating Mac App Store receipts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecPolicyMacAppStoreReceipt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecPolicyMacAppStoreReceipt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecPolicyMacAppStoreReceipt"
        }
      ],
      "role": "symbol",
      "title": "kSecPolicyMacAppStoreReceipt",
      "type": "topic",
      "url": "/documentation/security/ksecpolicymacappstorereceipt"
    },
    "doc://com.apple.security/documentation/Security/policies": {
      "abstract": [
        {
          "text": "Obtain policies for establishing trust.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/policies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Policies",
      "type": "topic",
      "url": "/documentation/security/policies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleX509Basic",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleSSL",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleSMIME",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleEAP",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleIPsec",
        "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITClient",
        "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITServer",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleCodeSigning",
        "doc://com.apple.security/documentation/Security/kSecPolicyMacAppStoreReceipt",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleIDValidation",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
        "doc://com.apple.security/documentation/Security/kSecPolicyApplePassbookSigning",
        "doc://com.apple.security/documentation/Security/kSecPolicyApplePayIssuerEncryption",
        "doc://com.apple.security/documentation/Security/kSecPolicyAppleRevocation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleX509Basic",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleSSL",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleSMIME",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleEAP",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleIPsec",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleiChat",
                "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITClient",
                "doc://com.apple.security/documentation/Security/kSecPolicyApplePKINITServer",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleCodeSigning",
                "doc://com.apple.security/documentation/Security/kSecPolicyMacAppStoreReceipt",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleIDValidation",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleTimeStamping",
                "doc://com.apple.security/documentation/Security/kSecPolicyApplePassbookSigning",
                "doc://com.apple.security/documentation/Security/kSecPolicyApplePayIssuerEncryption",
                "doc://com.apple.security/documentation/Security/kSecPolicyAppleRevocation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleIDValidation/title",
          "value": "kSecPolicyAppleIDValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleIDValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleIDValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleX509Basic/title",
          "value": "kSecPolicyAppleX509Basic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleX509Basic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleX509Basic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePassbookSigning/title",
          "value": "kSecPolicyApplePassbookSigning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePassbookSigning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyApplePassbookSigning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePayIssuerEncryption/title",
          "value": "kSecPolicyApplePayIssuerEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePayIssuerEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyApplePayIssuerEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleEAP/title",
          "value": "kSecPolicyAppleEAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleEAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleEAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleSSL/title",
          "value": "kSecPolicyAppleSSL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleSSL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleSSL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePKINITClient/title",
          "value": "kSecPolicyApplePKINITClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePKINITClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyApplePKINITClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleTimeStamping/title",
          "value": "kSecPolicyAppleTimeStamping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleTimeStamping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleTimeStamping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleRevocation/title",
          "value": "kSecPolicyAppleRevocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleRevocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleRevocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePKINITServer/title",
          "value": "kSecPolicyApplePKINITServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyApplePKINITServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyApplePKINITServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyMacAppStoreReceipt/title",
          "value": "kSecPolicyMacAppStoreReceipt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyMacAppStoreReceipt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyMacAppStoreReceipt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleCodeSigning/title",
          "value": "kSecPolicyAppleCodeSigning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleCodeSigning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleCodeSigning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleSMIME/title",
          "value": "kSecPolicyAppleSMIME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleSMIME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleSMIME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleIPsec/title",
          "value": "kSecPolicyAppleIPsec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecPolicyAppleIPsec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecPolicyAppleIPsec"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/standard-policies-for-specific-certificate-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/standard-policies-for-specific-certificate-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
