{
  "abstract": [
    {
      "text": "Use these supplemental flags to test the validity of a static code signature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/code-signing-services"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/static-code-validation-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Static Code Validation Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These flags supplement the flags described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use these additional constants with the flags parameter of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidity(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidityWithErrors(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions to control the validation of code in the file system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the ",
          "type": "text"
        },
        {
          "code": "flags",
          "type": "codeVoice"
        },
        {
          "text": " parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecCSFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/security/seccsflags"
    },
    "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidity(_:_:_:)": {
      "abstract": [
        {
          "text": "Validates a static code object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCodeCheckValidity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecRequirementRef",
          "text": "SecRequirement"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidity(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecStaticCodeCheckValidity"
        }
      ],
      "role": "symbol",
      "title": "SecStaticCodeCheckValidity(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secstaticcodecheckvalidity(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidityWithErrors(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs static validation of static signed code and returns detailed error information in the case of failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCodeCheckValidityWithErrors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecRequirementRef",
          "text": "SecRequirement"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecStaticCodeCheckValidityWithErrors(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecStaticCodeCheckValidityWithErrors"
        }
      ],
      "role": "symbol",
      "title": "SecStaticCodeCheckValidityWithErrors(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secstaticcodecheckvaliditywitherrors(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/code-signing-services": {
      "abstract": [
        {
          "text": "Examine and validate signed code running on the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/code-signing-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Code Signing Services",
      "type": "topic",
      "url": "/documentation/security/code-signing-services"
    },
    "doc://com.apple.security/documentation/Security/kSecCSBasicValidateOnly": {
      "abstract": [
        {
          "text": "Do not validate either the main executable or the bundle resources, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSBasicValidateOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSBasicValidateOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSBasicValidateOnly"
        }
      ],
      "role": "symbol",
      "title": "kSecCSBasicValidateOnly",
      "type": "topic",
      "url": "/documentation/security/kseccsbasicvalidateonly"
    },
    "doc://com.apple.security/documentation/Security/kSecCSCheckAllArchitectures": {
      "abstract": [
        {
          "text": "For multi-architecture (universal) Mach-O programs, validate all architectures included.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSCheckAllArchitectures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSCheckAllArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSCheckAllArchitectures"
        }
      ],
      "role": "symbol",
      "title": "kSecCSCheckAllArchitectures",
      "type": "topic",
      "url": "/documentation/security/kseccscheckallarchitectures"
    },
    "doc://com.apple.security/documentation/Security/kSecCSCheckGatekeeperArchitectures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSCheckGatekeeperArchitectures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSCheckGatekeeperArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSCheckGatekeeperArchitectures"
        }
      ],
      "role": "symbol",
      "title": "kSecCSCheckGatekeeperArchitectures",
      "type": "topic",
      "url": "/documentation/security/kseccscheckgatekeeperarchitectures"
    },
    "doc://com.apple.security/documentation/Security/kSecCSCheckNestedCode": {
      "abstract": [
        {
          "text": "For code in bundle form, locate and recursively check embedded code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSCheckNestedCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSCheckNestedCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSCheckNestedCode"
        }
      ],
      "role": "symbol",
      "title": "kSecCSCheckNestedCode",
      "type": "topic",
      "url": "/documentation/security/kseccschecknestedcode"
    },
    "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateExecutable": {
      "abstract": [
        {
          "text": "Do not validate the contents of the main executable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSDoNotValidateExecutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateExecutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSDoNotValidateExecutable"
        }
      ],
      "role": "symbol",
      "title": "kSecCSDoNotValidateExecutable",
      "type": "topic",
      "url": "/documentation/security/kseccsdonotvalidateexecutable"
    },
    "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateResources": {
      "abstract": [
        {
          "text": "Do not validate the presence and contents of all bundle resources (if any).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSDoNotValidateResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSDoNotValidateResources"
        }
      ],
      "role": "symbol",
      "title": "kSecCSDoNotValidateResources",
      "type": "topic",
      "url": "/documentation/security/kseccsdonotvalidateresources"
    },
    "doc://com.apple.security/documentation/Security/kSecCSFullReport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSFullReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSFullReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSFullReport"
        }
      ],
      "role": "symbol",
      "title": "kSecCSFullReport",
      "type": "topic",
      "url": "/documentation/security/kseccsfullreport"
    },
    "doc://com.apple.security/documentation/Security/kSecCSRestrictSidebandData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSRestrictSidebandData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSRestrictSidebandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSRestrictSidebandData"
        }
      ],
      "role": "symbol",
      "title": "kSecCSRestrictSidebandData",
      "type": "topic",
      "url": "/documentation/security/kseccsrestrictsidebanddata"
    },
    "doc://com.apple.security/documentation/Security/kSecCSRestrictSymlinks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSRestrictSymlinks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSRestrictSymlinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSRestrictSymlinks"
        }
      ],
      "role": "symbol",
      "title": "kSecCSRestrictSymlinks",
      "type": "topic",
      "url": "/documentation/security/kseccsrestrictsymlinks"
    },
    "doc://com.apple.security/documentation/Security/kSecCSRestrictToAppLike": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSRestrictToAppLike"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSRestrictToAppLike",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSRestrictToAppLike"
        }
      ],
      "role": "symbol",
      "title": "kSecCSRestrictToAppLike",
      "type": "topic",
      "url": "/documentation/security/kseccsrestricttoapplike"
    },
    "doc://com.apple.security/documentation/Security/kSecCSSingleThreaded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSSingleThreaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSSingleThreaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSSingleThreaded"
        }
      ],
      "role": "symbol",
      "title": "kSecCSSingleThreaded",
      "type": "topic",
      "url": "/documentation/security/kseccssinglethreaded"
    },
    "doc://com.apple.security/documentation/Security/kSecCSStrictValidate": {
      "abstract": [
        {
          "text": "Perform additional checks to ensure the validity of code in bundle form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSStrictValidate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSStrictValidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSStrictValidate"
        }
      ],
      "role": "symbol",
      "title": "kSecCSStrictValidate",
      "type": "topic",
      "url": "/documentation/security/kseccsstrictvalidate"
    },
    "doc://com.apple.security/documentation/Security/kSecCSUseSoftwareSigningCert": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSUseSoftwareSigningCert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSUseSoftwareSigningCert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSUseSoftwareSigningCert"
        }
      ],
      "role": "symbol",
      "title": "kSecCSUseSoftwareSigningCert",
      "type": "topic",
      "url": "/documentation/security/kseccsusesoftwaresigningcert"
    },
    "doc://com.apple.security/documentation/Security/kSecCSValidatePEH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecCSValidatePEH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecCSValidatePEH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecCSValidatePEH"
        }
      ],
      "role": "symbol",
      "title": "kSecCSValidatePEH",
      "type": "topic",
      "url": "/documentation/security/kseccsvalidatepeh"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecCSCheckAllArchitectures",
        "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateExecutable",
        "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateResources",
        "doc://com.apple.security/documentation/Security/kSecCSBasicValidateOnly",
        "doc://com.apple.security/documentation/Security/kSecCSCheckNestedCode",
        "doc://com.apple.security/documentation/Security/kSecCSStrictValidate",
        "doc://com.apple.security/documentation/Security/kSecCSFullReport",
        "doc://com.apple.security/documentation/Security/kSecCSCheckGatekeeperArchitectures",
        "doc://com.apple.security/documentation/Security/kSecCSRestrictSymlinks",
        "doc://com.apple.security/documentation/Security/kSecCSRestrictToAppLike",
        "doc://com.apple.security/documentation/Security/kSecCSRestrictSidebandData",
        "doc://com.apple.security/documentation/Security/kSecCSUseSoftwareSigningCert",
        "doc://com.apple.security/documentation/Security/kSecCSValidatePEH",
        "doc://com.apple.security/documentation/Security/kSecCSSingleThreaded"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecCSCheckAllArchitectures",
                "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateExecutable",
                "doc://com.apple.security/documentation/Security/kSecCSDoNotValidateResources",
                "doc://com.apple.security/documentation/Security/kSecCSBasicValidateOnly",
                "doc://com.apple.security/documentation/Security/kSecCSCheckNestedCode",
                "doc://com.apple.security/documentation/Security/kSecCSStrictValidate",
                "doc://com.apple.security/documentation/Security/kSecCSFullReport",
                "doc://com.apple.security/documentation/Security/kSecCSCheckGatekeeperArchitectures",
                "doc://com.apple.security/documentation/Security/kSecCSRestrictSymlinks",
                "doc://com.apple.security/documentation/Security/kSecCSRestrictToAppLike",
                "doc://com.apple.security/documentation/Security/kSecCSRestrictSidebandData",
                "doc://com.apple.security/documentation/Security/kSecCSUseSoftwareSigningCert",
                "doc://com.apple.security/documentation/Security/kSecCSValidatePEH",
                "doc://com.apple.security/documentation/Security/kSecCSSingleThreaded"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSUseSoftwareSigningCert/title",
          "value": "kSecCSUseSoftwareSigningCert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSUseSoftwareSigningCert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSUseSoftwareSigningCert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCheckValidity(_:_:_:)/title",
          "value": "SecStaticCodeCheckValidity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCheckValidity(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecStaticCodeCheckValidity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSFullReport/title",
          "value": "kSecCSFullReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSFullReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSFullReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckAllArchitectures/title",
          "value": "kSecCSCheckAllArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckAllArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSCheckAllArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictSidebandData/title",
          "value": "kSecCSRestrictSidebandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictSidebandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSRestrictSidebandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSingleThreaded/title",
          "value": "kSecCSSingleThreaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSSingleThreaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSSingleThreaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckGatekeeperArchitectures/title",
          "value": "kSecCSCheckGatekeeperArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckGatekeeperArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSCheckGatekeeperArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDoNotValidateExecutable/title",
          "value": "kSecCSDoNotValidateExecutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDoNotValidateExecutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSDoNotValidateExecutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSValidatePEH/title",
          "value": "kSecCSValidatePEH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSValidatePEH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSValidatePEH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictToAppLike/title",
          "value": "kSecCSRestrictToAppLike"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictToAppLike/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSRestrictToAppLike"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictSymlinks/title",
          "value": "kSecCSRestrictSymlinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSRestrictSymlinks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSRestrictSymlinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckNestedCode/title",
          "value": "kSecCSCheckNestedCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSCheckNestedCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSCheckNestedCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSBasicValidateOnly/title",
          "value": "kSecCSBasicValidateOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSBasicValidateOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSBasicValidateOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/title",
          "value": "SecCSFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecCSFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCheckValidityWithErrors(_:_:_:_:)/title",
          "value": "SecStaticCodeCheckValidityWithErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecStaticCodeCheckValidityWithErrors(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecStaticCodeCheckValidityWithErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDoNotValidateResources/title",
          "value": "kSecCSDoNotValidateResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSDoNotValidateResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSDoNotValidateResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSStrictValidate/title",
          "value": "kSecCSStrictValidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecCSStrictValidate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecCSStrictValidate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/static-code-validation-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/static-code-validation-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
