{
  "abstract": [
    {
      "text": "Set or obtain a system identity for domains.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/identities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/system-identity-domains"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "System Identity Domains"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants can be used with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySetSystemIdentity(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecIdentityCopySystemIdentity(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecIdentityCopySystemIdentity(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the system identity associated with a specified domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentityCopySystemIdentity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecIdentityRef",
          "text": "SecIdentity"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentityCopySystemIdentity(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentityCopySystemIdentity"
        }
      ],
      "role": "symbol",
      "title": "SecIdentityCopySystemIdentity(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/secidentitycopysystemidentity(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecIdentitySetSystemIdentity(_:_:)": {
      "abstract": [
        {
          "text": "Assigns the system identity to be associated with a specified domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentitySetSystemIdentity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecIdentityRef",
          "text": "SecIdentity"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentitySetSystemIdentity(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentitySetSystemIdentity"
        }
      ],
      "role": "symbol",
      "title": "SecIdentitySetSystemIdentity(_:_:)",
      "type": "topic",
      "url": "/documentation/security/secidentitysetsystemidentity(_:_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/identities": {
      "abstract": [
        {
          "text": "Combine certificates and cryptographic keys into identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/identities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Identities",
      "type": "topic",
      "url": "/documentation/security/identities"
    },
    "doc://com.apple.security/documentation/Security/kSecIdentityDomainDefault": {
      "abstract": [
        {
          "text": "The system-wide default identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecIdentityDomainDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecIdentityDomainDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecIdentityDomainDefault"
        }
      ],
      "role": "symbol",
      "title": "kSecIdentityDomainDefault",
      "type": "topic",
      "url": "/documentation/security/ksecidentitydomaindefault"
    },
    "doc://com.apple.security/documentation/Security/kSecIdentityDomainKerberosKDC": {
      "abstract": [
        {
          "text": "Kerberos Key Distribution Center (KDC) identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecIdentityDomainKerberosKDC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecIdentityDomainKerberosKDC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecIdentityDomainKerberosKDC"
        }
      ],
      "role": "symbol",
      "title": "kSecIdentityDomainKerberosKDC",
      "type": "topic",
      "url": "/documentation/security/ksecidentitydomainkerberoskdc"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecIdentityDomainDefault",
        "doc://com.apple.security/documentation/Security/kSecIdentityDomainKerberosKDC"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecIdentityDomainDefault",
                "doc://com.apple.security/documentation/Security/kSecIdentityDomainKerberosKDC"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIdentityDomainKerberosKDC/title",
          "value": "kSecIdentityDomainKerberosKDC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIdentityDomainKerberosKDC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecIdentityDomainKerberosKDC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIdentityDomainDefault/title",
          "value": "kSecIdentityDomainDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecIdentityDomainDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecIdentityDomainDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentitySetSystemIdentity(_:_:)/title",
          "value": "SecIdentitySetSystemIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentitySetSystemIdentity(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentitySetSystemIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentityCopySystemIdentity(_:_:_:)/title",
          "value": "SecIdentityCopySystemIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentityCopySystemIdentity(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityCopySystemIdentity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/system-identity-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/system-identity-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
