{
  "abstract": [
    {
      "text": "The collection of valid ciphersuites.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@tls_ciphersuite_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tls_ciphersuite_t"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tls_ciphersuite_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "tls_ciphersuite_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t": {
      "abstract": [
        {
          "text": "The collection of valid ciphersuites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_t"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_t"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_128_GCM_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AES_128_GCM_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_128_GCM_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_AES_128_GCM_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.AES_128_GCM_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/aes_128_gcm_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_256_GCM_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AES_256_GCM_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_256_GCM_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_AES_256_GCM_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.AES_256_GCM_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/aes_256_gcm_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/CHACHA20_POLY1305_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHACHA20_POLY1305_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/CHACHA20_POLY1305_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_CHACHA20_POLY1305_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.CHACHA20_POLY1305_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/chacha20_poly1305_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_3des_ede_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_128_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_128_cbc_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_GCM_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_128_gcm_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_256_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_256_cbc_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_GCM_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_aes_256_gcm_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_ecdsa_with_chacha20_poly1305_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_3DES_EDE_CBC_SHA": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_3des_ede_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_128_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_128_cbc_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_GCM_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_128_gcm_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_256_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_256_CBC_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_256_CBC_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_256_cbc_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_GCM_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_aes_256_gcm_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/ecdhe_rsa_with_chacha20_poly1305_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_3DES_EDE_CBC_SHA": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_3DES_EDE_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_3DES_EDE_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_3DES_EDE_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_3des_ede_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_128_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_128_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_128_CBC_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_128_cbc_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_GCM_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_GCM_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_128_GCM_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_128_GCM_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_128_gcm_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_256_CBC_SHA",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_256_cbc_sha"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_256_CBC_SHA256"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA256"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_256_CBC_SHA256",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_256_cbc_sha256"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_GCM_SHA384": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_GCM_SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tls_ciphersuite_RSA_WITH_AES_256_GCM_SHA384"
        }
      ],
      "role": "symbol",
      "title": "tls_ciphersuite_t.RSA_WITH_AES_256_GCM_SHA384",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/rsa_with_aes_256_gcm_sha384"
    },
    "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/security/tls_ciphersuite_t/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "AES",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_128_GCM_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_256_GCM_SHA384"
      ],
      "title": "AES"
    },
    {
      "anchor": "Cha-Cha-Poly",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/CHACHA20_POLY1305_SHA256"
      ],
      "title": "Cha Cha Poly"
    },
    {
      "anchor": "Elliptic-Curve",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA384",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
      ],
      "title": "Elliptic Curve"
    },
    {
      "anchor": "RSA",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_3DES_EDE_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_GCM_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA256",
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_GCM_SHA384"
      ],
      "title": "RSA"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tls_ciphersuite_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "AES",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_128_GCM_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/AES_256_GCM_SHA384"
              ],
              "title": "AES"
            },
            {
              "anchor": "Cha-Cha-Poly",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/CHACHA20_POLY1305_SHA256"
              ],
              "title": "Cha Cha Poly"
            },
            {
              "anchor": "Elliptic-Curve",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
              ],
              "title": "Elliptic Curve"
            },
            {
              "anchor": "RSA",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_3DES_EDE_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_CBC_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_128_GCM_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_CBC_SHA256",
                "doc://com.apple.security/documentation/Security/tls_ciphersuite_t/RSA_WITH_AES_256_GCM_SHA384"
              ],
              "title": "RSA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tls_ciphersuite_t"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_CBC_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_CBC_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_GCM_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_GCM_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1AES_256_GCM_SHA384/title",
          "value": "tls_ciphersuite_AES_256_GCM_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1AES_256_GCM_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_AES_256_GCM_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_GCM_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_GCM_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_128_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_128_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_CBC_SHA256/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_CBC_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_GCM_SHA384/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_256_GCM_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_GCM_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_256_GCM_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_CBC_SHA384/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_CBC_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_GCM_SHA384/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_GCM_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_CBC_SHA/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_256_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_256_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_CBC_SHA384/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_CBC_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1AES_128_GCM_SHA256/title",
          "value": "tls_ciphersuite_AES_128_GCM_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1AES_128_GCM_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_AES_128_GCM_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_GCM_SHA256/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_128_GCM_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_GCM_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_128_GCM_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_CBC_SHA256/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_CBC_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_128_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_3DES_EDE_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_3DES_EDE_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1CHACHA20_POLY1305_SHA256/title",
          "value": "tls_ciphersuite_CHACHA20_POLY1305_SHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1CHACHA20_POLY1305_SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_CHACHA20_POLY1305_SHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_CBC_SHA/title",
          "value": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_AES_128_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_AES_128_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_CBC_SHA/title",
          "value": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_RSA_WITH_AES_256_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_RSA_WITH_AES_256_CBC_SHA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t/title",
          "value": "tls_ciphersuite_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_GCM_SHA384/title",
          "value": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1ECDHE_ECDSA_WITH_AES_256_GCM_SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_3DES_EDE_CBC_SHA/title",
          "value": "tls_ciphersuite_RSA_WITH_3DES_EDE_CBC_SHA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1tls_ciphersuite_t~1RSA_WITH_3DES_EDE_CBC_SHA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tls_ciphersuite_RSA_WITH_3DES_EDE_CBC_SHA"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/tls_ciphersuite_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/tls_ciphersuite_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
