{
  "abstract": [
    {
      "text": "Recognize the keys that appear in a dictionary containing information about an evaluated certification chain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/trust"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/trust-result-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Trust Result Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These keys appear in the dictionary returned from a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function and provide information about the evaluated trust.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing information about an evaluated trust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecTrustCopyResult"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecTrustRef",
          "text": "SecTrust"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecTrustCopyResult(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecTrustCopyResult"
        }
      ],
      "role": "symbol",
      "title": "SecTrustCopyResult(_:)",
      "type": "topic",
      "url": "/documentation/security/sectrustcopyresult(_:)"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparency": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean used to indicate Certificate Transparency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustCertificateTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustCertificateTransparency"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustCertificateTransparency",
      "type": "topic",
      "url": "/documentation/security/ksectrustcertificatetransparency"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparencyWhiteList": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean used to indicate the chain satisfies Certificate Transparency by being on the allow list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustCertificateTransparencyWhiteList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparencyWhiteList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustCertificateTransparencyWhiteList"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustCertificateTransparencyWhiteList",
      "type": "topic",
      "url": "/documentation/security/ksectrustcertificatetransparencywhitelist"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustEvaluationDate": {
      "abstract": [
        {
          "text": "A key whose value indicates the time that the trust evaluation took place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustEvaluationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustEvaluationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustEvaluationDate"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustEvaluationDate",
      "type": "topic",
      "url": "/documentation/security/ksectrustevaluationdate"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustExtendedValidation": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean used to indicate Extended Validation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustExtendedValidation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustExtendedValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustExtendedValidation"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustExtendedValidation",
      "type": "topic",
      "url": "/documentation/security/ksectrustextendedvalidation"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustOrganizationName": {
      "abstract": [
        {
          "text": "A key whose value is the organization name field of the subject of the leaf certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustOrganizationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustOrganizationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustOrganizationName"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustOrganizationName",
      "type": "topic",
      "url": "/documentation/security/ksectrustorganizationname"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustResultValue": {
      "abstract": [
        {
          "text": "A key whose value represents the trust evaluation result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustResultValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustResultValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustResultValue"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustResultValue",
      "type": "topic",
      "url": "/documentation/security/ksectrustresultvalue"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustRevocationChecked": {
      "abstract": [
        {
          "text": "A key whose value indicates the outcome of revocation checking during trust evaluation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustRevocationChecked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustRevocationChecked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustRevocationChecked"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustRevocationChecked",
      "type": "topic",
      "url": "/documentation/security/ksectrustrevocationchecked"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustRevocationValidUntilDate": {
      "abstract": [
        {
          "text": "A key whose value indicates the earliest date at which revocation information becomes stale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustRevocationValidUntilDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustRevocationValidUntilDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustRevocationValidUntilDate"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustRevocationValidUntilDate",
      "type": "topic",
      "url": "/documentation/security/ksectrustrevocationvaliduntildate"
    },
    "doc://com.apple.security/documentation/Security/trust": {
      "abstract": [
        {
          "text": "Evaluate trust based on a given policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/trust",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Trust",
      "type": "topic",
      "url": "/documentation/security/trust"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparency",
        "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparencyWhiteList",
        "doc://com.apple.security/documentation/Security/kSecTrustEvaluationDate",
        "doc://com.apple.security/documentation/Security/kSecTrustExtendedValidation",
        "doc://com.apple.security/documentation/Security/kSecTrustOrganizationName",
        "doc://com.apple.security/documentation/Security/kSecTrustResultValue",
        "doc://com.apple.security/documentation/Security/kSecTrustRevocationChecked",
        "doc://com.apple.security/documentation/Security/kSecTrustRevocationValidUntilDate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparency",
                "doc://com.apple.security/documentation/Security/kSecTrustCertificateTransparencyWhiteList",
                "doc://com.apple.security/documentation/Security/kSecTrustEvaluationDate",
                "doc://com.apple.security/documentation/Security/kSecTrustExtendedValidation",
                "doc://com.apple.security/documentation/Security/kSecTrustOrganizationName",
                "doc://com.apple.security/documentation/Security/kSecTrustResultValue",
                "doc://com.apple.security/documentation/Security/kSecTrustRevocationChecked",
                "doc://com.apple.security/documentation/Security/kSecTrustRevocationValidUntilDate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustExtendedValidation/title",
          "value": "kSecTrustExtendedValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustExtendedValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustExtendedValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustEvaluationDate/title",
          "value": "kSecTrustEvaluationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustEvaluationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustEvaluationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustResultValue/title",
          "value": "kSecTrustResultValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustResultValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustResultValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustOrganizationName/title",
          "value": "kSecTrustOrganizationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustOrganizationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustOrganizationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustCertificateTransparency/title",
          "value": "kSecTrustCertificateTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustCertificateTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustCertificateTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustRevocationChecked/title",
          "value": "kSecTrustRevocationChecked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustRevocationChecked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustRevocationChecked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustCertificateTransparencyWhiteList/title",
          "value": "kSecTrustCertificateTransparencyWhiteList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustCertificateTransparencyWhiteList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustCertificateTransparencyWhiteList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyResult(_:)/title",
          "value": "SecTrustCopyResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecTrustCopyResult(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecTrustCopyResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustRevocationValidUntilDate/title",
          "value": "kSecTrustRevocationValidUntilDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustRevocationValidUntilDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustRevocationValidUntilDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/trust-result-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/trust-result-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
