{
  "abstract": [
    {
      "text": "Recognize BER and DER values for ASN.1 identifier octets.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/asn-1"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/type-tags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Type Tags"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ANY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ANY"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_ANY",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_any"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY_CONTENTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ANY_CONTENTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY_CONTENTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ANY_CONTENTS"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_ANY_CONTENTS",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_any_contents"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_APPLICATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_APPLICATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_APPLICATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_APPLICATION"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_APPLICATION",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_application"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_BIT_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BIT_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_BIT_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BIT_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_BIT_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_bit_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_BMP_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BMP_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_BMP_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BMP_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_BMP_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_bmp_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_BOOLEAN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BOOLEAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_BOOLEAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_BOOLEAN"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_BOOLEAN",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_boolean"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_CHOICE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CHOICE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_CHOICE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CHOICE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_CHOICE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_choice"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_CLASS_MASK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CLASS_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_CLASS_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CLASS_MASK"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_CLASS_MASK",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_class_mask"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_CONSTRUCTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CONSTRUCTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_CONSTRUCTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CONSTRUCTED"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_CONSTRUCTED",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_constructed"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_CONTEXT_SPECIFIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CONTEXT_SPECIFIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_CONTEXT_SPECIFIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_CONTEXT_SPECIFIC"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_CONTEXT_SPECIFIC",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_context_specific"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_DYNAMIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_DYNAMIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_DYNAMIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_DYNAMIC"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_DYNAMIC",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_dynamic"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_EMBEDDED_PDV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_EMBEDDED_PDV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_EMBEDDED_PDV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_EMBEDDED_PDV"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_EMBEDDED_PDV",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_embedded_pdv"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_ENUMERATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ENUMERATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_ENUMERATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_ENUMERATED"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_ENUMERATED",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_enumerated"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_EXPLICIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_EXPLICIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_EXPLICIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_EXPLICIT"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_EXPLICIT",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_explicit"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERALIZED_TIME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GENERALIZED_TIME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERALIZED_TIME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GENERALIZED_TIME"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_GENERALIZED_TIME",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_generalized_time"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERAL_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GENERAL_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERAL_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GENERAL_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_GENERAL_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_general_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_GRAPHIC_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GRAPHIC_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_GRAPHIC_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GRAPHIC_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_GRAPHIC_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_graphic_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_GROUP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GROUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_GROUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_GROUP"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_GROUP",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_group"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_HIGH_TAG_NUMBER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_HIGH_TAG_NUMBER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_HIGH_TAG_NUMBER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_HIGH_TAG_NUMBER"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_HIGH_TAG_NUMBER",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_high_tag_number"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_IA5_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_IA5_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_IA5_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_IA5_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_IA5_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_ia5_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INLINE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_INLINE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INLINE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_INLINE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_inline"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_INNER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INNER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_INNER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INNER"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_INNER",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_inner"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_INTEGER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INTEGER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_INTEGER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_INTEGER"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_INTEGER",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_integer"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_METHOD_MASK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_METHOD_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_METHOD_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_METHOD_MASK"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_METHOD_MASK",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_method_mask"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_NULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_NULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_NULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_NULL"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_NULL",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_null"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_NUMERIC_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_NUMERIC_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_NUMERIC_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_NUMERIC_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_NUMERIC_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_numeric_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_DESCRIPTOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OBJECT_DESCRIPTOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_DESCRIPTOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OBJECT_DESCRIPTOR"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_OBJECT_DESCRIPTOR",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_object_descriptor"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OBJECT_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OBJECT_ID"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_OBJECT_ID",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_object_id"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_OCTET_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OCTET_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_OCTET_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OCTET_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_OCTET_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_octet_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_OPTIONAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OPTIONAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_OPTIONAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_OPTIONAL"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_OPTIONAL",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_optional"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_POINTER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_POINTER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_POINTER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_POINTER"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_POINTER",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_pointer"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIMITIVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRIMITIVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIMITIVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRIMITIVE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_PRIMITIVE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_primitive"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_PRINTABLE_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRINTABLE_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_PRINTABLE_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRINTABLE_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_PRINTABLE_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_printable_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIVATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRIVATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIVATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_PRIVATE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_PRIVATE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_private"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_REAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_REAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_REAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_REAL"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_REAL",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_real"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SAVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SAVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SAVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SAVE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SAVE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_save"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SEQUENCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SEQUENCE"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SEQUENCE",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_sequence"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE_OF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SEQUENCE_OF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE_OF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SEQUENCE_OF"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SEQUENCE_OF",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_sequence_of"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SET"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SET",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_set"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SET_OF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SET_OF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SET_OF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SET_OF"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SET_OF",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_set_of"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SIGNED_INT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SIGNED_INT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SIGNED_INT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SIGNED_INT"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SIGNED_INT",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_signed_int"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SKIP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SKIP"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SKIP",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_skip"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP_REST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SKIP_REST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP_REST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_SKIP_REST"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_SKIP_REST",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_skip_rest"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_T61_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_T61_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_T61_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_T61_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_T61_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_t61_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_TAGNUM_MASK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TAGNUM_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_TAGNUM_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TAGNUM_MASK"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_TAGNUM_MASK",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_tagnum_mask"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_TAG_MASK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TAG_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_TAG_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TAG_MASK"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_TAG_MASK",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_tag_mask"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_TELETEX_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TELETEX_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_TELETEX_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_TELETEX_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_TELETEX_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_teletex_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UNIVERSAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UNIVERSAL"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_UNIVERSAL",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_universal"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UNIVERSAL_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UNIVERSAL_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_UNIVERSAL_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_universal_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_UTC_TIME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UTC_TIME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_UTC_TIME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UTC_TIME"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_UTC_TIME",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_utc_time"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_UTF8_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UTF8_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_UTF8_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_UTF8_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_UTF8_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_utf8_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_VIDEOTEX_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_VIDEOTEX_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_VIDEOTEX_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_VIDEOTEX_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_VIDEOTEX_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_videotex_string"
    },
    "doc://com.apple.security/documentation/Security/SEC_ASN1_VISIBLE_STRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SEC_ASN1_VISIBLE_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SEC_ASN1_VISIBLE_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SEC_ASN1_VISIBLE_STRING"
        }
      ],
      "role": "symbol",
      "title": "SEC_ASN1_VISIBLE_STRING",
      "type": "topic",
      "url": "/documentation/security/sec_asn1_visible_string"
    },
    "doc://com.apple.security/documentation/Security/asn-1": {
      "abstract": [
        {
          "text": "Encode and decode Distinguished Encoding Rules (DER) and Basic Encoding Rules (BER) data streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/asn-1",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ASN.1",
      "type": "topic",
      "url": "/documentation/security/asn-1"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "The-Tag-Mask",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SEC_ASN1_TAG_MASK"
      ],
      "title": "The Tag Mask"
    },
    {
      "abstract": [
        {
          "text": "BER/DER universal type tag numbers.",
          "type": "text"
        }
      ],
      "anchor": "Universal-Type-Tags",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SEC_ASN1_TAGNUM_MASK",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_BOOLEAN",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_INTEGER",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_BIT_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_OCTET_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_NULL",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_ID",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_DESCRIPTOR",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_REAL",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_ENUMERATED",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_EMBEDDED_PDV",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_UTF8_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SET",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_NUMERIC_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_PRINTABLE_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_T61_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_VIDEOTEX_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_IA5_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_UTC_TIME",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERALIZED_TIME",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_GRAPHIC_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_VISIBLE_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERAL_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_BMP_STRING",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_HIGH_TAG_NUMBER",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_TELETEX_STRING"
      ],
      "title": "Universal Type Tags"
    },
    {
      "anchor": "Type-Tag-Modifiers",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SEC_ASN1_METHOD_MASK",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIMITIVE",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_CONSTRUCTED",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_CLASS_MASK",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_APPLICATION",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_CONTEXT_SPECIFIC",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIVATE"
      ],
      "title": "Type Tag Modifiers"
    },
    {
      "anchor": "Apple-Specific-Additions",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/SEC_ASN1_OPTIONAL",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_EXPLICIT",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_INLINE",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_POINTER",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_GROUP",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_DYNAMIC",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_INNER",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SAVE",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP_REST",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_CHOICE",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SIGNED_INT",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY_CONTENTS",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE_OF",
        "doc://com.apple.security/documentation/Security/SEC_ASN1_SET_OF"
      ],
      "title": "Apple Specific Additions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "The-Tag-Mask",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SEC_ASN1_TAG_MASK"
              ],
              "title": "The Tag Mask"
            },
            {
              "abstract": [
                {
                  "text": "BER/DER universal type tag numbers.",
                  "type": "text"
                }
              ],
              "anchor": "Universal-Type-Tags",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SEC_ASN1_TAGNUM_MASK",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_BOOLEAN",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_INTEGER",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_BIT_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_OCTET_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_NULL",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_ID",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_OBJECT_DESCRIPTOR",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_REAL",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_ENUMERATED",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_EMBEDDED_PDV",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_UTF8_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SET",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_NUMERIC_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_PRINTABLE_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_T61_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_VIDEOTEX_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_IA5_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_UTC_TIME",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERALIZED_TIME",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_GRAPHIC_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_VISIBLE_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_GENERAL_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_BMP_STRING",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_HIGH_TAG_NUMBER",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_TELETEX_STRING"
              ],
              "title": "Universal Type Tags"
            },
            {
              "anchor": "Type-Tag-Modifiers",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SEC_ASN1_METHOD_MASK",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIMITIVE",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_CONSTRUCTED",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_CLASS_MASK",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_UNIVERSAL",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_APPLICATION",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_CONTEXT_SPECIFIC",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_PRIVATE"
              ],
              "title": "Type Tag Modifiers"
            },
            {
              "anchor": "Apple-Specific-Additions",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/SEC_ASN1_OPTIONAL",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_EXPLICIT",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_INLINE",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_POINTER",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_GROUP",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_DYNAMIC",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_INNER",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SAVE",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SKIP_REST",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_CHOICE",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SIGNED_INT",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_ANY_CONTENTS",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SEQUENCE_OF",
                "doc://com.apple.security/documentation/Security/SEC_ASN1_SET_OF"
              ],
              "title": "Apple Specific Additions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UTC_TIME/title",
          "value": "SEC_ASN1_UTC_TIME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UTC_TIME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_UTC_TIME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BOOLEAN/title",
          "value": "SEC_ASN1_BOOLEAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BOOLEAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_BOOLEAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INTEGER/title",
          "value": "SEC_ASN1_INTEGER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INTEGER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_INTEGER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SET/title",
          "value": "SEC_ASN1_SET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UNIVERSAL_STRING/title",
          "value": "SEC_ASN1_UNIVERSAL_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UNIVERSAL_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_UNIVERSAL_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_APPLICATION/title",
          "value": "SEC_ASN1_APPLICATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_APPLICATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_APPLICATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_T61_STRING/title",
          "value": "SEC_ASN1_T61_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_T61_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_T61_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GENERAL_STRING/title",
          "value": "SEC_ASN1_GENERAL_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GENERAL_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_GENERAL_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UNIVERSAL/title",
          "value": "SEC_ASN1_UNIVERSAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UNIVERSAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_UNIVERSAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SET_OF/title",
          "value": "SEC_ASN1_SET_OF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SET_OF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SET_OF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_VIDEOTEX_STRING/title",
          "value": "SEC_ASN1_VIDEOTEX_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_VIDEOTEX_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_VIDEOTEX_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OBJECT_DESCRIPTOR/title",
          "value": "SEC_ASN1_OBJECT_DESCRIPTOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OBJECT_DESCRIPTOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_OBJECT_DESCRIPTOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OPTIONAL/title",
          "value": "SEC_ASN1_OPTIONAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OPTIONAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_OPTIONAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UTF8_STRING/title",
          "value": "SEC_ASN1_UTF8_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_UTF8_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_UTF8_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INNER/title",
          "value": "SEC_ASN1_INNER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INNER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_INNER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CLASS_MASK/title",
          "value": "SEC_ASN1_CLASS_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CLASS_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_CLASS_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TAGNUM_MASK/title",
          "value": "SEC_ASN1_TAGNUM_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TAGNUM_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_TAGNUM_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GENERALIZED_TIME/title",
          "value": "SEC_ASN1_GENERALIZED_TIME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GENERALIZED_TIME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_GENERALIZED_TIME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_DYNAMIC/title",
          "value": "SEC_ASN1_DYNAMIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_DYNAMIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_DYNAMIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_REAL/title",
          "value": "SEC_ASN1_REAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_REAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_REAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BMP_STRING/title",
          "value": "SEC_ASN1_BMP_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BMP_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_BMP_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TAG_MASK/title",
          "value": "SEC_ASN1_TAG_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TAG_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_TAG_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_NUMERIC_STRING/title",
          "value": "SEC_ASN1_NUMERIC_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_NUMERIC_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_NUMERIC_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CONSTRUCTED/title",
          "value": "SEC_ASN1_CONSTRUCTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CONSTRUCTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_CONSTRUCTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OCTET_STRING/title",
          "value": "SEC_ASN1_OCTET_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OCTET_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_OCTET_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_POINTER/title",
          "value": "SEC_ASN1_POINTER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_POINTER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_POINTER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SKIP/title",
          "value": "SEC_ASN1_SKIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SKIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SKIP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CONTEXT_SPECIFIC/title",
          "value": "SEC_ASN1_CONTEXT_SPECIFIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CONTEXT_SPECIFIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_CONTEXT_SPECIFIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SEQUENCE/title",
          "value": "SEC_ASN1_SEQUENCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SEQUENCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SEQUENCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SEQUENCE_OF/title",
          "value": "SEC_ASN1_SEQUENCE_OF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SEQUENCE_OF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SEQUENCE_OF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRIVATE/title",
          "value": "SEC_ASN1_PRIVATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRIVATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_PRIVATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ENUMERATED/title",
          "value": "SEC_ASN1_ENUMERATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ENUMERATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_ENUMERATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SIGNED_INT/title",
          "value": "SEC_ASN1_SIGNED_INT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SIGNED_INT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SIGNED_INT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BIT_STRING/title",
          "value": "SEC_ASN1_BIT_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_BIT_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_BIT_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ANY/title",
          "value": "SEC_ASN1_ANY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ANY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_ANY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_HIGH_TAG_NUMBER/title",
          "value": "SEC_ASN1_HIGH_TAG_NUMBER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_HIGH_TAG_NUMBER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_HIGH_TAG_NUMBER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_METHOD_MASK/title",
          "value": "SEC_ASN1_METHOD_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_METHOD_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_METHOD_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_IA5_STRING/title",
          "value": "SEC_ASN1_IA5_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_IA5_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_IA5_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CHOICE/title",
          "value": "SEC_ASN1_CHOICE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_CHOICE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_CHOICE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_NULL/title",
          "value": "SEC_ASN1_NULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_NULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_NULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_EXPLICIT/title",
          "value": "SEC_ASN1_EXPLICIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_EXPLICIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_EXPLICIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRIMITIVE/title",
          "value": "SEC_ASN1_PRIMITIVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRIMITIVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_PRIMITIVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_EMBEDDED_PDV/title",
          "value": "SEC_ASN1_EMBEDDED_PDV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_EMBEDDED_PDV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_EMBEDDED_PDV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GROUP/title",
          "value": "SEC_ASN1_GROUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GROUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_GROUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INLINE/title",
          "value": "SEC_ASN1_INLINE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_INLINE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_INLINE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRINTABLE_STRING/title",
          "value": "SEC_ASN1_PRINTABLE_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_PRINTABLE_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_PRINTABLE_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SKIP_REST/title",
          "value": "SEC_ASN1_SKIP_REST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SKIP_REST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SKIP_REST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GRAPHIC_STRING/title",
          "value": "SEC_ASN1_GRAPHIC_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_GRAPHIC_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_GRAPHIC_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SAVE/title",
          "value": "SEC_ASN1_SAVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_SAVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_SAVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TELETEX_STRING/title",
          "value": "SEC_ASN1_TELETEX_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_TELETEX_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_TELETEX_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ANY_CONTENTS/title",
          "value": "SEC_ASN1_ANY_CONTENTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_ANY_CONTENTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_ANY_CONTENTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OBJECT_ID/title",
          "value": "SEC_ASN1_OBJECT_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_OBJECT_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_OBJECT_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_VISIBLE_STRING/title",
          "value": "SEC_ASN1_VISIBLE_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SEC_ASN1_VISIBLE_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SEC_ASN1_VISIBLE_STRING"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/type-tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/type-tags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
