{
  "abstract": [
    {
      "text": "Use these trust settings keys in a usage constraints dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/trust"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/usage-constraints-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Usage Constraints Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsAllowedError": {
      "abstract": [
        {
          "text": "A number which, if encountered during certificate verification, is ignored for that certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsAllowedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsAllowedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsAllowedError"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsAllowedError",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingsallowederror"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsApplication": {
      "abstract": [
        {
          "text": "A trusted application reference for the application checking the certificate’s trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsApplication"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsApplication",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingsapplication"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsKeyUsage": {
      "abstract": [
        {
          "text": "A number specifying the operations for which the encryption key in this certificate can be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsKeyUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsKeyUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsKeyUsage"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsKeyUsage",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingskeyusage"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicy": {
      "abstract": [
        {
          "text": "A policy object specifying the certificate verification policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsPolicy"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsPolicy",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingspolicy"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicyString": {
      "abstract": [
        {
          "text": "A string containing policy-specific data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsPolicyString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicyString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsPolicyString"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsPolicyString",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingspolicystring"
    },
    "doc://com.apple.security/documentation/Security/kSecTrustSettingsResult": {
      "abstract": [
        {
          "text": "A number indicating the effective trust setting for this usage constraints dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecTrustSettingsResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecTrustSettingsResult"
        }
      ],
      "role": "symbol",
      "title": "kSecTrustSettingsResult",
      "type": "topic",
      "url": "/documentation/security/ksectrustsettingsresult"
    },
    "doc://com.apple.security/documentation/Security/trust": {
      "abstract": [
        {
          "text": "Evaluate trust based on a given policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/trust",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Trust",
      "type": "topic",
      "url": "/documentation/security/trust"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicy",
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsApplication",
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicyString",
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsKeyUsage",
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsAllowedError",
        "doc://com.apple.security/documentation/Security/kSecTrustSettingsResult"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicy",
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsApplication",
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsPolicyString",
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsKeyUsage",
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsAllowedError",
                "doc://com.apple.security/documentation/Security/kSecTrustSettingsResult"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsPolicy/title",
          "value": "kSecTrustSettingsPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsPolicyString/title",
          "value": "kSecTrustSettingsPolicyString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsPolicyString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsPolicyString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsKeyUsage/title",
          "value": "kSecTrustSettingsKeyUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsKeyUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsKeyUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsApplication/title",
          "value": "kSecTrustSettingsApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsAllowedError/title",
          "value": "kSecTrustSettingsAllowedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsAllowedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsAllowedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsResult/title",
          "value": "kSecTrustSettingsResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecTrustSettingsResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecTrustSettingsResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/usage-constraints-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/usage-constraints-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
