{
  "abstract": [
    {
      "text": "Perform asymmetric and symmetric encryption and decryption using cryptographic keys.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
        "doc://com.apple.security/documentation/Security/keys"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/using-keys-for-encryption"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Using Keys for Encryption"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Cryptography enables secure data exchange through an untrusted channel. One important component of this activity is encryption. A transmitter encodes data on one side of a link, rendering it gibberish to anyone without the key to decode it. The data then passes through the channel—exposed to the world, but meaningless to all but the intended receiver. That receiver, the only holder of the decryption key, reverses the encryption process to reveal the original message.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As with cryptographic keys, there are two main types of encryption:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Asymmetric.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Asymmetric encryption doesn’t require a shared secret. On the other hand, it’s computationally expensive and works only on small, discrete blocks of data. Therefore, it’s most suitable for small transfers when sender and receiver have no established relationship.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Symmetric.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Symmetric encryption is good for bulk data transfer because it’s computationally efficient and operates on streams of data. But it works only when the transmitter and the receiver share a secret key. So you typically rely on some other technique, such as asymmetric encryption or the Diffie-Hellman key exchange, to share a key and establish a session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Use-Asymmetric-Encryption",
          "level": 3,
          "text": "Use Asymmetric Encryption",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To perform asymmetric encryption, a transmitter encrypts its data with a public key. Only the holder of the matching private key can then decrypt the obscured message. You begin by obtaining a public key that corresponds to your intended recipient’s private key. Depending on the situation, you might read it from your keychain or from a certificate, or you might use one of the other methods described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/getting-an-existing-key",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". However you obtain the key, the kind of encryption you can perform depends on the key itself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, consider a 2048-bit RSA key pair, like the one generated in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/generating-new-cryptographic-keys#Creating-an-Asymmetric-Key-Pair",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Either using a signed certificate or some other trusted (but not necessarily secure) channel, the receiver transfers the public key to the transmitter. The transmitter and receiver then negotiate an appropriate encryption algorithm (or rely on a prearranged one) corresponding to the capabilities of the key pair. In this case, suppose you choose this ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " algorithm:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let publicKey: SecKey = <# a key #>",
                    "let algorithm: SecKeyAlgorithm = .rsaEncryptionOAEPSHA512"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "SecKeyRef publicKey = <# a key #>;  // E.g., from a signed cert",
                    "SecKeyAlgorithm algorithm = kSecKeyAlgorithmRSAEncryptionOAEPSHA512;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This setting specifies RSA encryption, employing the Optimal Asymmetric Encryption Padding (OAEP) scheme using SHA512 hashing. The selected algorithm must suit the key’s capabilities. But rather than trust that the key works with the algorithm, you can explicitly test for compatibility with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyOperationType/encrypt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " operation, using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyIsAlgorithmSupported(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "guard SecKeyIsAlgorithmSupported(publicKey, .encrypt, algorithm) else {",
                    "    throw <# an error #>",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "BOOL canEncrypt = SecKeyIsAlgorithmSupported(publicKey,",
                    "                                             kSecKeyOperationTypeEncrypt,",
                    "                                             algorithm);"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This call might return false if the key were not actually of type RSA or if the ",
              "type": "text"
            },
            {
              "code": "publicKey",
              "type": "codeVoice"
            },
            {
              "text": " reference actually referred to a private key (despite its name). Private keys typically have the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute set false, marking them ineligible for encryption.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As an additional check before encrypting, because asymmetric encryption restricts the length of the data that you can encrypt, verify that the data is short enough. For this particular algorithm, the plain text data must be 130 bytes smaller than the key’s block size, as reported by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyGetBlockSize(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You therefore further condition the proceedings on a length test:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "guard (plainText.count < (SecKeyGetBlockSize(publicKey)-130)) else {",
                    "    throw <# an error #>",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData* plainText = <# Data to encrypt #>;",
                    "canEncrypt &= ([plainText length] < (SecKeyGetBlockSize(publicKey)-130));"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, you conduct the encryption with a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyCreateEncryptedData(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "var error: Unmanaged<CFError>?",
                    "guard let cipherText = SecKeyCreateEncryptedData(publicKey,",
                    "                                                 algorithm,",
                    "                                                 plainText as CFData,",
                    "                                                 &error) as Data? else {",
                    "                                                    throw error!.takeRetainedValue() as Error",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData* cipherText = nil;",
                    "if (canEncrypt) {",
                    "    CFErrorRef error = NULL;",
                    "    cipherText = (NSData*)CFBridgingRelease(      // ARC takes ownership",
                    "                     SecKeyCreateEncryptedData(publicKey,",
                    "                                               algorithm,",
                    "                                               (__bridge CFDataRef)plainText,",
                    "                                               &error));",
                    "    if (!cipherText) {",
                    "        NSError *err = CFBridgingRelease(error);  // ARC takes ownership",
                    "        // Handle the error. . .",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Despite the pretests, something may still go wrong with the encryption call. When it does, the function returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " cipher text and produces an error object that indicates the cause of failure. In Objective-C, you transfer ownership of the error object to Automatic Reference Counting (ARC) with a call to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/1587932-cfbridgingrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and handle the error. In Swift, you convert the optional, unmanaged ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a managed ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Error",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and throw it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Assuming that the encryption succeeds, you send the ",
              "type": "text"
            },
            {
              "code": "cipherText",
              "type": "codeVoice"
            },
            {
              "text": " data object to the receiver through the channel. The receiver then uses its private key to decrypt the data. As described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/getting-an-existing-key",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you’ll typically get a reference to your private key from either the keychain or an identity (which might itself be stored in the keychain). You can again test the key for its suitability, using the same algorithm as before, but for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyOperationType/decrypt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " operation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "guard SecKeyIsAlgorithmSupported(privateKey, .decrypt, algorithm) else {",
                    "    throw <# an error #>",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "SecKeyRef privateKey = <# a key #>;  // From keychain or identity",
                    "BOOL canDecrypt = SecKeyIsAlgorithmSupported(privateKey,",
                    "                                             kSecKeyOperationTypeDecrypt,",
                    "                                             algorithm);"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "You can again test the length, though in this case, the cipher text should be the same length as the key’s block size, because that’s what the encryption operation should have produced:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "guard cipherText.count == SecKeyGetBlockSize(privateKey) else {",
                    "    throw <# an error #>",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "canDecrypt &= ([cipherText length] == SecKeyGetBlockSize(privateKey));"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "With the tests out of the way, the decryption proceeds much like the encryption, only now with a call to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyCreateDecryptedData(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "var error: Unmanaged<CFError>?",
                    "guard let clearText = SecKeyCreateDecryptedData(privateKey,",
                    "                                                algorithm,",
                    "                                                cipherText as CFData,",
                    "                                                &error) as Data? else {",
                    "                                                    throw error!.takeRetainedValue() as Error",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData* clearText = nil;",
                    "if (canDecrypt) {",
                    "    CFErrorRef error = NULL;",
                    "    clearText = (NSData*)CFBridgingRelease(       // ARC takes ownership",
                    "                     SecKeyCreateDecryptedData(privateKey,",
                    "                                               algorithm,",
                    "                                               (__bridge CFDataRef)cipherText,",
                    "                                               &error));",
                    "    if (!clearText) {",
                    "        NSError *err = CFBridgingRelease(error);  // ARC takes ownership",
                    "        // Handle the error. . .",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "As before, you handle a failure and the corresponding error object, if applicable. If the call succeeds, the ",
              "type": "text"
            },
            {
              "code": "clearText",
              "type": "codeVoice"
            },
            {
              "text": " object exactly matches the ",
              "type": "text"
            },
            {
              "code": "plainText",
              "type": "codeVoice"
            },
            {
              "text": " object from the transmitter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-Symmetric-Encryption",
          "level": 3,
          "text": "Use Symmetric Encryption",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the sender and receiver share a single, secret key, they can perform symmetric encryption, in which the same key both encrypts and decrypts the message. Even though the operations in this case are computationally efficient, initially sharing the key poses its own challenge. For that reason, you’ll usually want to use another method, such as asymmetric encryption, to exchange a symmetric key at the time you begin communicating.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In fact, the certificate, key, and trust services API provides a simple way to accomplish this. You follow all of the steps outlined in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/using-keys-for-encryption#Use-Asymmetric-Encryption",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", with only the following adjustments:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Change the algorithm.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " When you choose an algorithm of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512AESGCM",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or one of the other symmetric encryption algorithms, the encryption and decryption function calls change their behavior.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Omit the length checks at both the transmitter and receiver.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Because the input data is encrypted by the AES session key, that data is no longer restricted to a particular length. Similarly, the block of encrypted data is no longer expected to be the key’s block size. In fact, it’s the key’s block size plus the (variable) length of the encrypted data plus 16 bytes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "On the encryption side, instead of simply padding and encoding the given block of data with the key, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyCreateEncryptedData(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function first generates a random Advanced Encryption Standard (AES) session key. It uses this key to encrypt the input data, and then RSA encrypts the AES key using the input public key you provide. It finally assembles the RSA encrypted session key, the AES encrypted data, and a 16-byte AES-GCM tag into a block of data that it returns to you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On the decryption side, the process is reversed. The function decrypts the AES session key using the private key you provide as input and then uses that to decrypt the data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you use elliptic curve keys, then use one of the elliptic curve algorithms, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/eciesEncryptionCofactorX963SHA256AESGCM",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The precise details of this key exchange are different, compared with the RSA exchange described above. Still, the effective behavior you see as a consumer of the API is the same.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "With these small changes, you switch from asymmetric encryption to symmetric encryption supported by asymmetric encryption. You can now efficiently transmit arbitrarily large blocks of encrypted data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/Error": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Error",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cferror-ru8",
      "kind": "article",
      "role": "article",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror-ru8"
    },
    "doc://com.apple.documentation/documentation/foundation/1587932-cfbridgingrelease": {
      "abstract": [
        {
          "text": "Moves a non-Objective-C pointer to Objective-C and also transfers ownership to ARC.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1587932-cfbridgingrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBridgingRelease",
      "type": "topic",
      "url": "/documentation/foundation/1587932-cfbridgingrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/eciesEncryptionCofactorX963SHA256AESGCM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eciesEncryptionCofactorX963SHA256AESGCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/eciesEncryptionCofactorX963SHA256AESGCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyAlgorithmECIESEncryptionCofactorX963SHA256AESGCM"
        }
      ],
      "role": "symbol",
      "title": "eciesEncryptionCofactorX963SHA256AESGCM",
      "type": "topic",
      "url": "/documentation/security/seckeyalgorithm/eciesencryptioncofactorx963sha256aesgcm"
    },
    "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsaEncryptionOAEPSHA512"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512"
        }
      ],
      "role": "symbol",
      "title": "rsaEncryptionOAEPSHA512",
      "type": "topic",
      "url": "/documentation/security/seckeyalgorithm/rsaencryptionoaepsha512"
    },
    "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512AESGCM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsaEncryptionOAEPSHA512AESGCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA512AESGCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512AESGCM"
        }
      ],
      "role": "symbol",
      "title": "rsaEncryptionOAEPSHA512AESGCM",
      "type": "topic",
      "url": "/documentation/security/seckeyalgorithm/rsaencryptionoaepsha512aesgcm"
    },
    "doc://com.apple.security/documentation/Security/SecKeyCreateDecryptedData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Decrypts a block of data using a private key and specified algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyCreateDecryptedData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyCreateDecryptedData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyCreateDecryptedData"
        }
      ],
      "role": "symbol",
      "title": "SecKeyCreateDecryptedData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeycreatedecrypteddata(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyCreateEncryptedData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Encrypts a block of data using a public key and specified algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyCreateEncryptedData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyCreateEncryptedData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyCreateEncryptedData"
        }
      ],
      "role": "symbol",
      "title": "SecKeyCreateEncryptedData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeycreateencrypteddata(_:_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyGetBlockSize(_:)": {
      "abstract": [
        {
          "text": "Gets the block length associated with a cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyGetBlockSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyGetBlockSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyGetBlockSize"
        }
      ],
      "role": "symbol",
      "title": "SecKeyGetBlockSize(_:)",
      "type": "topic",
      "url": "/documentation/security/seckeygetblocksize(_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyIsAlgorithmSupported(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean indicating whether a key is suitable for an operation using a certain algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecKeyIsAlgorithmSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyRef",
          "text": "SecKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecKeyOperationType",
          "text": "SecKeyOperationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyIsAlgorithmSupported(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecKeyIsAlgorithmSupported"
        }
      ],
      "role": "symbol",
      "title": "SecKeyIsAlgorithmSupported(_:_:_:)",
      "type": "topic",
      "url": "/documentation/security/seckeyisalgorithmsupported(_:_:_:)"
    },
    "doc://com.apple.security/documentation/Security/SecKeyOperationType/decrypt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrypt"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyOperationType/decrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyOperationTypeDecrypt"
        }
      ],
      "role": "symbol",
      "title": "SecKeyOperationType.decrypt",
      "type": "topic",
      "url": "/documentation/security/seckeyoperationtype/decrypt"
    },
    "doc://com.apple.security/documentation/Security/SecKeyOperationType/encrypt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encrypt"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecKeyOperationType/encrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecKeyOperationTypeEncrypt"
        }
      ],
      "role": "symbol",
      "title": "SecKeyOperationType.encrypt",
      "type": "topic",
      "url": "/documentation/security/seckeyoperationtype/encrypt"
    },
    "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services": {
      "abstract": [
        {
          "text": "Establish trust using certificates and cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/certificate-key-and-trust-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Certificate, Key, and Trust Services",
      "type": "topic",
      "url": "/documentation/security/certificate-key-and-trust-services"
    },
    "doc://com.apple.security/documentation/Security/generating-new-cryptographic-keys#Creating-an-Asymmetric-Key-Pair": {
      "abstract": [],
      "identifier": "doc://com.apple.security/documentation/Security/generating-new-cryptographic-keys#Creating-an-Asymmetric-Key-Pair",
      "kind": "section",
      "title": "Creating an Asymmetric Key Pair",
      "type": "topic",
      "url": "/documentation/security/generating-new-cryptographic-keys#Creating-an-Asymmetric-Key-Pair"
    },
    "doc://com.apple.security/documentation/Security/getting-an-existing-key": {
      "abstract": [
        {
          "text": "Learn how to obtain an existing cryptographic key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/getting-an-existing-key",
      "kind": "article",
      "role": "article",
      "title": "Getting an Existing Key",
      "type": "topic",
      "url": "/documentation/security/getting-an-existing-key"
    },
    "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt": {
      "abstract": [
        {
          "text": "A key whose value is a Boolean that indicates whether the cryptographic key can be used for encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/kSecAttrCanEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSecAttrCanEncrypt"
        }
      ],
      "role": "symbol",
      "title": "kSecAttrCanEncrypt",
      "type": "topic",
      "url": "/documentation/security/ksecattrcanencrypt"
    },
    "doc://com.apple.security/documentation/Security/keys": {
      "abstract": [
        {
          "text": "Generate, store, and use cryptographic keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keys",
      "type": "topic",
      "url": "/documentation/security/keys"
    },
    "doc://com.apple.security/documentation/Security/using-keys-for-encryption#Use-Asymmetric-Encryption": {
      "abstract": [],
      "identifier": "doc://com.apple.security/documentation/Security/using-keys-for-encryption#Use-Asymmetric-Encryption",
      "kind": "section",
      "title": "Use Asymmetric Encryption",
      "type": "topic",
      "url": "/documentation/security/using-keys-for-encryption#Use-Asymmetric-Encryption"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/title",
          "value": "kSecAttrCanEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1kSecAttrCanEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecAttrCanEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyIsAlgorithmSupported(_:_:_:)/title",
          "value": "SecKeyIsAlgorithmSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyIsAlgorithmSupported(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyIsAlgorithmSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyOperationType~1encrypt/title",
          "value": "kSecKeyOperationTypeEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyOperationType~1encrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyOperationTypeEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1eciesEncryptionCofactorX963SHA256AESGCM/title",
          "value": "kSecKeyAlgorithmECIESEncryptionCofactorX963SHA256AESGCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1eciesEncryptionCofactorX963SHA256AESGCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmECIESEncryptionCofactorX963SHA256AESGCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA512AESGCM/title",
          "value": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512AESGCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA512AESGCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512AESGCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyOperationType~1decrypt/title",
          "value": "kSecKeyOperationTypeDecrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyOperationType~1decrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyOperationTypeDecrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCreateEncryptedData(_:_:_:_:)/title",
          "value": "SecKeyCreateEncryptedData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCreateEncryptedData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyCreateEncryptedData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCreateDecryptedData(_:_:_:_:)/title",
          "value": "SecKeyCreateDecryptedData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyCreateDecryptedData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyCreateDecryptedData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGetBlockSize(_:)/title",
          "value": "SecKeyGetBlockSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyGetBlockSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecKeyGetBlockSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA512/title",
          "value": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmRSAEncryptionOAEPSHA512"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/using-keys-for-encryption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/using-keys-for-encryption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
