{"seeAlsoSections":[{"title":"Managing the Current Context","anchor":"Managing-the-Current-Context","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/current","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext"],"generated":true}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/graphicsPort","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext","type":"reference","isActive":true},{"text":" instead.","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"graphicsPort"}],"platforms":[{"name":"macOS","introducedAt":"10.0","deprecatedAt":"10.14","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"graphicsPort","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"}],"externalID":"c:objc(cs)NSGraphicsContext(py)graphicsPort","symbolKind":"property","extendedModule":"AppKit","modules":[{"name":"AppKit"}],"role":"symbol","title":"graphicsPort","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphicsPort"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","identifier":"doc://com.externally.resolved.symbol/s:Sv","preciseIdentifier":"s:Sv"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In macOS, this is the Core Graphics context, a ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgcontext","isActive":true,"type":"reference"},{"text":" object (opaque type).","type":"text"}]}]}],"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsgraphicscontext/graphicsport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgraphicscontext/graphicsport"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The low-level, platform-specific graphics context represented by the graphic port.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/graphicsPort":{"title":"graphicsPort","type":"topic","abstract":[{"type":"text","text":"The low-level, platform-specific graphics context represented by the graphic port."}],"role":"symbol","url":"/documentation/appkit/nsgraphicscontext/graphicsport","navigatorTitle":[{"text":"graphicsPort","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"graphicsPort","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/graphicsPort","deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","role":"symbol","type":"topic","url":"/documentation/appkit/nsgraphicscontext","navigatorTitle":[{"text":"NSGraphicsContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGraphicsContext","kind":"identifier"}],"title":"NSGraphicsContext","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/current":{"title":"current","type":"topic","abstract":[{"type":"text","text":"Returns the current graphics context of the current thread."}],"role":"symbol","url":"/documentation/appkit/nsgraphicscontext/current","navigatorTitle":[{"text":"currentContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSGraphicsContext","preciseIdentifier":"c:objc(cs)NSGraphicsContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/current"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext":{"title":"cgContext","type":"topic","abstract":[{"type":"text","text":"The Core Graphics context, which is a low-level, platform-specific graphics context."}],"role":"symbol","url":"/documentation/appkit/nsgraphicscontext/cgcontext","navigatorTitle":[{"text":"CGContext","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGContext","preciseIdentifier":"c:@T@CGContextRef","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext"},"doc://com.apple.documentation/documentation/coregraphics/cgcontext":{"role":"symbol","title":"CGContext","type":"topic","fragments":[{"text":"class ","kind":"text"},{"text":"CGContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A Quartz 2D drawing environment."}],"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgcontext","kind":"symbol","url":"/documentation/coregraphics/cgcontext"},"doc://com.externally.resolved.symbol/s:Sv":{"role":"symbol","abstract":[{"type":"text","text":"A raw pointer for accessing and manipulating untyped data."}],"title":"UnsafeMutableRawPointer","kind":"symbol","url":"/documentation/Swift/UnsafeMutableRawPointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:Sv","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.0","deprecatedAt":"10.14","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"graphicsPort","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"graphicsPort"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Managing the Current Context","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/current","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext"],"anchor":"Managing-the-Current-Context"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" * "},{"kind":"identifier","text":"graphicsPort"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/cgContext","isActive":true},{"type":"text","text":" instead."}]}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1graphicsPort/title","value":"graphicsPort","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1graphicsPort/fragments","value":[{"text":"graphicsPort","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title","value":"NSGraphicsContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments","value":[{"text":"NSGraphicsContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle","value":[{"text":"NSGraphicsContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1current/title","value":"currentContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1current/fragments","value":[{"text":"currentContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1cgContext/title","value":"CGContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1cgContext/fragments","value":[{"kind":"identifier","text":"CGContext"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext/title","value":"CGContextRef","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}