{
  "abstract": [
    {
      "text": "The amount to offset the pattern color when filling the graphics context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSGraphicsContext(py)patternPhase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "patternPhase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPoint",
        "text": "NSPoint"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "patternPhase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "patternPhase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "patternPhase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property when you need to line up the pattern color with another pattern, such as the pattern in a superview. The pattern phase is a translation (width, height) applied before a pattern is drawn in the current context and is part of the saved graphics state of the context. The default pattern phase is (0,0). Setting the pattern phase has the effect of temporarily changing the pattern matrix of any pattern you decide to draw. For example, setting the pattern phase to (2,3) has the effect of moving the start of pattern cell tiling to the point (2,3) in default user space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation": {
      "abstract": [
        {
          "text": "Constants that describe compositing operators in terms of source and destination images, each having an opaque and transparent region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext": {
      "abstract": [
        {
          "text": "An object that represents a graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGraphicsContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGraphicsContext"
        }
      ],
      "role": "symbol",
      "title": "NSGraphicsContext",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation": {
      "abstract": [
        {
          "text": "The graphics context’s global compositing operation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositingOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCompositingOperation",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositingOperation"
        }
      ],
      "role": "symbol",
      "title": "compositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/compositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation": {
      "abstract": [
        {
          "text": "A constant that specifies the graphics context’s interpolation, or image smoothing, behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageInterpolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSImageInterpolation",
          "text": "NSImageInterpolation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageInterpolation"
        }
      ],
      "role": "symbol",
      "title": "imageInterpolation",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/imageinterpolation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase": {
      "abstract": [
        {
          "text": "The amount to offset the pattern color when filling the graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "patternPhase"
        }
      ],
      "role": "symbol",
      "title": "patternPhase",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/patternphase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the graphics context uses antialiasing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAntialias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAntialias"
        }
      ],
      "role": "symbol",
      "title": "shouldAntialias",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/shouldantialias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation": {
      "abstract": [
        {
          "text": "Constants that specify the interpolation, or image smoothing, behavior used by the image interpolation property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSPoint": {
      "abstract": [
        {
          "text": "A point in a Cartesian coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPoint",
      "type": "topic",
      "url": "/documentation/foundation/nspoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Rendering-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias"
      ],
      "title": "Configuring Rendering Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "patternPhase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "patternPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Rendering-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias"
              ],
              "title": "Configuring Rendering Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSPoint",
                    "text": "NSPoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "patternPhase"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1compositingOperation/title",
          "value": "compositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1compositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title",
          "value": "NSGraphicsContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGraphicsContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGraphicsContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1shouldAntialias/title",
          "value": "shouldAntialias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1shouldAntialias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldAntialias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/title",
          "value": "NSImageInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1patternPhase/title",
          "value": "patternPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1patternPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "patternPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1imageInterpolation/title",
          "value": "imageInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1imageInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/title",
          "value": "NSCompositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgraphicscontext/patternphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgraphicscontext/patternphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
