{"metadata":{"navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"title":"restoreGraphicsState()","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"externalID":"c:objc(cs)NSGraphicsContext(cm)restoreGraphicsState","modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Pops a graphics context from the per-thread stack, makes it current, and sends the context a restore graphics state message."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Managing-the-Graphics-State","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"],"title":"Managing the Graphics State"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreGraphicsState"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"paths":["/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.type.method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.type.method"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","role":"symbol","type":"topic","url":"/documentation/appkit/nsgraphicscontext","navigatorTitle":[{"text":"NSGraphicsContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGraphicsContext","kind":"identifier"}],"title":"NSGraphicsContext","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method":{"role":"symbol","abstract":[{"type":"text","text":"Saves the graphics state of the current graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.type.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method":{"role":"symbol","abstract":[{"text":"Saves the current graphics state and creates a new graphics state on the top of the stack.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)":{"role":"symbol","abstract":[{"text":"Makes the graphics context of the specified graphics state current, and resets graphics state.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGraphicsState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)","deprecated":true,"navigatorTitle":[{"text":"setGraphicsState:","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/setgraphicsstate(_:)","title":"setGraphicsState(_:)","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method":{"navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"abstract":[{"text":"Pops a graphics context from the per-thread stack, makes it current, and sends the context a restore graphics state message.","type":"text"}],"title":"restoreGraphicsState()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.type.method"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method":{"role":"symbol","abstract":[{"type":"text","text":"Removes the context’s graphics state from the top of the graphics state stack and makes the next graphics state the current graphics state."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method","title":"restoreGraphicsState()","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"restoreGraphicsState","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"restoreGraphicsState"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"],"title":"Managing the Graphics State","anchor":"Managing-the-Graphics-State","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title","op":"replace","value":"NSGraphicsContext"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments","op":"replace","value":[{"kind":"identifier","text":"NSGraphicsContext"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSGraphicsContext"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/title","op":"replace","value":"saveGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"saveGraphicsState"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/title","op":"replace","value":"saveGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/title","op":"replace","value":"setGraphicsState:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setGraphicsState:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/title","op":"replace","value":"restoreGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/title","op":"replace","value":"restoreGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}