{"variants":[{"paths":["/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This method must have been preceded with a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","type":"reference"},{"text":" message to add the graphics state to the stack. Invocations of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","type":"reference"},{"text":" methods may be nested.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Restoring the graphics state restores such attributes as the current drawing style, transformation matrix, color, and font of the original graphics state.","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"Removes the context’s graphics state from the top of the graphics state stack and makes the next graphics state the current graphics state.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"title":"restoreGraphicsState()","navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)NSGraphicsContext(im)restoreGraphicsState"},"kind":"symbol","seeAlsoSections":[{"anchor":"Managing-the-Graphics-State","generated":true,"title":"Managing the Graphics State","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)":{"role":"symbol","abstract":[{"text":"Makes the graphics context of the specified graphics state current, and resets graphics state.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGraphicsState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)","deprecated":true,"navigatorTitle":[{"text":"setGraphicsState:","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/setgraphicsstate(_:)","title":"setGraphicsState(_:)","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","role":"symbol","type":"topic","url":"/documentation/appkit/nsgraphicscontext","navigatorTitle":[{"text":"NSGraphicsContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGraphicsContext","kind":"identifier"}],"title":"NSGraphicsContext","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method":{"role":"symbol","abstract":[{"type":"text","text":"Removes the context’s graphics state from the top of the graphics state stack and makes the next graphics state the current graphics state."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method","title":"restoreGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method":{"role":"symbol","abstract":[{"type":"text","text":"Saves the graphics state of the current graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.type.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method":{"role":"symbol","abstract":[{"text":"Saves the current graphics state and creates a new graphics state on the top of the stack.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method":{"navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"abstract":[{"text":"Pops a graphics context from the per-thread stack, makes it current, and sends the context a restore graphics state message.","type":"text"}],"title":"restoreGraphicsState()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.type.method"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"restoreGraphicsState"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restoreGraphicsState"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"],"generated":true,"title":"Managing the Graphics State","anchor":"Managing-the-Graphics-State"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/title","value":"setGraphicsState:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setGraphicsState:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/fragments","op":"replace"},{"value":"NSGraphicsContext","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSGraphicsContext"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSGraphicsContext"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/title","op":"replace","value":"restoreGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/title","op":"replace","value":"saveGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/title","op":"replace","value":"saveGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"saveGraphicsState"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/title","op":"replace","value":"restoreGraphicsState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"restoreGraphicsState"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}