{"abstract":[{"text":"Saves the graphics state of the current graphics context.","type":"text"}],"variants":[{"paths":["/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.type.method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.type.method"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"seeAlsoSections":[{"title":"Managing the Graphics State","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"],"generated":true,"anchor":"Managing-the-Graphics-State"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveGraphicsState"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method sends the current graphics context a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method"},{"type":"text","text":" message and pushes the context onto the per-thread stack."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"title":"saveGraphicsState()","platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"AppKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)NSGraphicsContext(cm)saveGraphicsState"},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)":{"role":"symbol","abstract":[{"text":"Makes the graphics context of the specified graphics state current, and resets graphics state.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGraphicsState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)","deprecated":true,"navigatorTitle":[{"text":"setGraphicsState:","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/setgraphicsstate(_:)","title":"setGraphicsState(_:)","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method":{"role":"symbol","abstract":[{"text":"Saves the current graphics state and creates a new graphics state on the top of the stack.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method":{"role":"symbol","abstract":[{"type":"text","text":"Saves the graphics state of the current graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.type.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.type.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method":{"role":"symbol","abstract":[{"type":"text","text":"Removes the context’s graphics state from the top of the graphics state stack and makes the next graphics state the current graphics state."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method","title":"restoreGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method":{"navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"abstract":[{"text":"Pops a graphics context from the per-thread stack, makes it current, and sends the context a restore graphics state message.","type":"text"}],"title":"restoreGraphicsState()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.type.method"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext","role":"symbol","type":"topic","url":"/documentation/appkit/nsgraphicscontext","navigatorTitle":[{"text":"NSGraphicsContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a graphics context."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGraphicsContext","kind":"identifier"}],"title":"NSGraphicsContext","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"saveGraphicsState","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"saveGraphicsState"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Managing the Graphics State","generated":true,"anchor":"Managing-the-Graphics-State","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/setGraphicsState(_:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"saveGraphicsState"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/title","value":"setGraphicsState:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1setGraphicsState(_:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setGraphicsState:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/title","value":"saveGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveGraphicsState"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/title","value":"saveGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.type.method/fragments","value":[{"text":"+ ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/title","value":"restoreGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/fragments","value":[{"text":"- ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/title","value":"restoreGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.type.method/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"restoreGraphicsState"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title","value":"NSGraphicsContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments","value":[{"text":"NSGraphicsContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle","value":[{"kind":"identifier","text":"NSGraphicsContext"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}