{
  "abstract": [
    {
      "text": "A preset for HEVC with Alpha video at 1920 by 1080 pixels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080WithAlpha"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVOutputSettingsPresetHEVC1920x1080WithAlpha",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hevc1920x1080WithAlpha"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
        "text": "AVOutputSettingsPreset"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "hevc1920x1080WithAlpha"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hevc1920x1080WithAlpha"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
              "text": "AVOutputSettingsPreset"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset": {
      "abstract": [
        {
          "text": "A structure that defines preset configurations for an output settings assistant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "role": "symbol",
      "title": "AVOutputSettingsPreset",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080": {
      "abstract": [
        {
          "text": "A preset for HEVC video at 1920 by 1080 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc1920x1080"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetHEVC1920x1080"
        }
      ],
      "role": "symbol",
      "title": "hevc1920x1080",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/hevc1920x1080"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080WithAlpha": {
      "abstract": [
        {
          "text": "A preset for HEVC with Alpha video at 1920 by 1080 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc1920x1080WithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080WithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
        }
      ],
      "role": "symbol",
      "title": "hevc1920x1080WithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/hevc1920x1080withalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160": {
      "abstract": [
        {
          "text": "A preset for HEVC video at 3840 by 2160 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc3840x2160"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetHEVC3840x2160"
        }
      ],
      "role": "symbol",
      "title": "hevc3840x2160",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/hevc3840x2160"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160WithAlpha": {
      "abstract": [
        {
          "text": "A preset for HEVC with Alpha video at 3840 by 2160 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc3840x2160WithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160WithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetHEVC3840x2160WithAlpha"
        }
      ],
      "role": "symbol",
      "title": "hevc3840x2160WithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/hevc3840x2160withalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc7680x4320": {
      "abstract": [
        {
          "text": "A preset for HEVC video at 7680 by 4320 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc7680x4320"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc7680x4320",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetHEVC7680x4320"
        }
      ],
      "role": "symbol",
      "title": "hevc7680x4320",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/hevc7680x4320"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc1440x1440": {
      "abstract": [
        {
          "text": "A preset for MV-HEVC video at 1440 by 1440 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mvhevc1440x1440"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc1440x1440",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetMVHEVC1440x1440"
        }
      ],
      "role": "symbol",
      "title": "mvhevc1440x1440",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/mvhevc1440x1440"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc960x960": {
      "abstract": [
        {
          "text": "A preset for MV-HEVC video at 960 by 960 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mvhevc960x960"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc960x960",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPresetMVHEVC960x960"
        }
      ],
      "role": "symbol",
      "title": "mvhevc960x960",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/mvhevc960x960"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1280x720": {
      "abstract": [
        {
          "text": "A preset for H.264 video at 1280 by 720 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preset1280x720"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1280x720",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset1280x720"
        }
      ],
      "role": "symbol",
      "title": "preset1280x720",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/preset1280x720"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1920x1080": {
      "abstract": [
        {
          "text": "A preset for H.264 video at 1920 by 1080 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preset1920x1080"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1920x1080",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset1920x1080"
        }
      ],
      "role": "symbol",
      "title": "preset1920x1080",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/preset1920x1080"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset3840x2160": {
      "abstract": [
        {
          "text": "A preset for H.264 video at 3840 by 2160 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preset3840x2160"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset3840x2160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset3840x2160"
        }
      ],
      "role": "symbol",
      "title": "preset3840x2160",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/preset3840x2160"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset640x480": {
      "abstract": [
        {
          "text": "A preset for H.264 video at 640 by 480 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preset640x480"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset640x480",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset640x480"
        }
      ],
      "role": "symbol",
      "title": "preset640x480",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/preset640x480"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset960x540": {
      "abstract": [
        {
          "text": "A preset for H.264 video at 960 by 540 pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preset960x540"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
          "text": "AVOutputSettingsPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset960x540",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsPreset960x540"
        }
      ],
      "role": "symbol",
      "title": "preset960x540",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingspreset/preset960x540"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset3840x2160",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1920x1080",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1280x720",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset960x540",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset640x480",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc7680x4320",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160WithAlpha",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc1440x1440",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc960x960"
      ],
      "title": "Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset3840x2160",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1920x1080",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset1280x720",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset960x540",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/preset640x480",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc7680x4320",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc3840x2160WithAlpha",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/hevc1920x1080",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc1440x1440",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset/mvhevc960x960"
              ],
              "title": "Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsPreset",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVOutputSettingsPreset",
                    "text": "AVOutputSettingsPreset"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset640x480/title",
          "value": "AVOutputSettingsPreset640x480"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset640x480/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset640x480"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc3840x2160WithAlpha/title",
          "value": "AVOutputSettingsPresetHEVC3840x2160WithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc3840x2160WithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC3840x2160WithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc7680x4320/title",
          "value": "AVOutputSettingsPresetHEVC7680x4320"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc7680x4320/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC7680x4320"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc3840x2160/title",
          "value": "AVOutputSettingsPresetHEVC3840x2160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc3840x2160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC3840x2160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1mvhevc960x960/title",
          "value": "AVOutputSettingsPresetMVHEVC960x960"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1mvhevc960x960/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetMVHEVC960x960"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset1920x1080/title",
          "value": "AVOutputSettingsPreset1920x1080"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset1920x1080/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset1920x1080"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc1920x1080WithAlpha/title",
          "value": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc1920x1080WithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC1920x1080WithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset/title",
          "value": "AVOutputSettingsPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1mvhevc1440x1440/title",
          "value": "AVOutputSettingsPresetMVHEVC1440x1440"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1mvhevc1440x1440/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetMVHEVC1440x1440"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc1920x1080/title",
          "value": "AVOutputSettingsPresetHEVC1920x1080"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1hevc1920x1080/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPresetHEVC1920x1080"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset960x540/title",
          "value": "AVOutputSettingsPreset960x540"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset960x540/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset960x540"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset1280x720/title",
          "value": "AVOutputSettingsPreset1280x720"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset1280x720/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset1280x720"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset3840x2160/title",
          "value": "AVOutputSettingsPreset3840x2160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsPreset~1preset3840x2160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsPreset3840x2160"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avoutputsettingspreset/hevc1920x1080withalpha"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avoutputsettingspreset/hevc1920x1080withalpha"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
