{
  "abstract": [
    {
      "text": "Returns a joint name that corresponds to a key point defined in a human body pose.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@F@ARSkeletonJointNameForRecognizedPointKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNRecognizedPointKey",
        "text": "VNRecognizedPointKey"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARSkeletonJointNameForRecognizedPointKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recognizedPointKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@VNRecognizedPointKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNRecognizedPointKey",
              "text": "VNRecognizedPointKey"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The argument key point.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recognizedPointKey"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function matches human body key points defined by the Vision framework with joint names defined by ARKit. This function may return ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the key point doesn’t map to a joint name. For more information about key points, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Vision/detecting-human-body-poses-in-images",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton": {
      "abstract": [
        {
          "text": "The interface for the skeleton of a tracked body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName": {
      "abstract": [
        {
          "text": "A name identifier for a joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton.JointName",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)": {
      "abstract": [
        {
          "text": "Returns a joint name that corresponds to a key point defined in a human body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameForRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/init(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new joint name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/init(rawvalue:)"
    },
    "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/Vision/VNRecognizedPointKey"
    },
    "doc://com.apple.documentation/documentation/Vision/detecting-human-body-poses-in-images": {
      "abstract": [
        {
          "text": "Add the capability to detect human body poses to your app using the Vision framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Vision/detecting-human-body-poses-in-images",
      "kind": "article",
      "role": "article",
      "title": "Detecting Human Body Poses in Images",
      "type": "topic",
      "url": "/documentation/Vision/detecting-human-body-poses-in-images"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@VNRecognizedPointKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/Vision/VNRecognizedPointKey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Joint-Name",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)",
        "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey"
      ],
      "title": "Creating a Joint Name"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARSkeletonJointNameForRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameForRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Joint-Name",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey"
              ],
              "title": "Creating a Joint Name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ARSkeletonJointName",
                    "text": "ARSkeletonJointName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARSkeletonJointNameForRecognizedPointKey"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@VNRecognizedPointKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNRecognizedPointKey",
                    "text": "VNRecognizedPointKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "recognizedPointKey"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The argument key point.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "recognizedPointKey"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1init(_:)/title",
          "value": "ARSkeletonJointNameForRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1init(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameForRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/title",
          "value": "ARSkeletonJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/title",
          "value": "ARSkeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname/init(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname/init(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
