{
  "abstract": [
    {
      "text": "A skeletal joint that ARKit tracks representing the right foot.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@ARSkeletonJointNameRightFoot",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rightFoot"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARSkeleton",
        "text": "ARSkeleton"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ARSkeletonJointName",
        "text": "JointName"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARSkeletonJointNameRightFoot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "rightFoot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rightFoot"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARSkeleton",
              "text": "ARSkeleton"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ARSkeletonJointName",
              "text": "JointName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton": {
      "abstract": [
        {
          "text": "The interface for the skeleton of a tracked body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName": {
      "abstract": [
        {
          "text": "A name identifier for a joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton.JointName",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the head.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "head"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameHead"
        }
      ],
      "role": "symbol",
      "title": "head",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/head"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftFoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftFoot"
        }
      ],
      "role": "symbol",
      "title": "leftFoot",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/leftfoot"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftHand"
        }
      ],
      "role": "symbol",
      "title": "leftHand",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/lefthand"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left shoulder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftShoulder"
        }
      ],
      "role": "symbol",
      "title": "leftShoulder",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/leftshoulder"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightFoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightFoot"
        }
      ],
      "role": "symbol",
      "title": "rightFoot",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/rightfoot"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightHand"
        }
      ],
      "role": "symbol",
      "title": "rightHand",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/righthand"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right shoulder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightShoulder"
        }
      ],
      "role": "symbol",
      "title": "rightShoulder",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/rightshoulder"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root": {
      "abstract": [
        {
          "text": "A skeletal joint that’s the root of all other joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "root"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRoot"
        }
      ],
      "role": "symbol",
      "title": "root",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/root"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-Joints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder"
      ],
      "title": "Identifying Joints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARSkeletonJointNameRightFoot"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-Joints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder"
              ],
              "title": "Identifying Joints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ARSkeletonJointName",
                    "text": "ARSkeletonJointName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARSkeletonJointNameRightFoot"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1head/title",
          "value": "ARSkeletonJointNameHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1head/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightFoot/title",
          "value": "ARSkeletonJointNameRightFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightFoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightHand/title",
          "value": "ARSkeletonJointNameRightHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftFoot/title",
          "value": "ARSkeletonJointNameLeftFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftFoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/title",
          "value": "ARSkeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/title",
          "value": "ARSkeletonJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1root/title",
          "value": "ARSkeletonJointNameRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1root/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightShoulder/title",
          "value": "ARSkeletonJointNameRightShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftHand/title",
          "value": "ARSkeletonJointNameLeftHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftShoulder/title",
          "value": "ARSkeletonJointNameLeftShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftShoulder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname/rightfoot"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname/rightfoot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
