{
  "abstract": [
    {
      "text": "Represents a cursor pointing device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPointingDeviceType@NSPointingDeviceTypeCursor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cursor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPointingDeviceTypeCursor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSEvent.PointingDeviceType.cursor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cursor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum": {
      "abstract": [
        {
          "text": "The pointing-device types for tablet-proximity events or mouse events with a proximity event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor": {
      "abstract": [
        {
          "text": "Represents a cursor pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/cursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeCursor"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.cursor",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/cursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser": {
      "abstract": [
        {
          "text": "Represents the eraser end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eraser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeEraser"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.eraser",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/eraser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen": {
      "abstract": [
        {
          "text": "Represents the tip end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypePen"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.pen",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/pen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown": {
      "abstract": [
        {
          "text": "Represents an unknown type of pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPointingDeviceTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPointingDeviceTypeCursor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/eraser",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/pen",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSPointingDeviceTypeCursor"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/title",
          "value": "NSPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1cursor/title",
          "value": "NSPointingDeviceTypeCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1cursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1eraser/title",
          "value": "NSPointingDeviceTypeEraser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1eraser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeEraser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1pen/title",
          "value": "NSPointingDeviceTypePen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1pen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypePen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1unknown/title",
          "value": "NSPointingDeviceTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceTypeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/cursor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/pointingdevicetype-swift.enum/cursor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
