{"seeAlsoSections":[{"anchor":"Tracking-Live-Data","title":"Tracking Live Data","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didCollectDataOf:)","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilderDidCollectEvent(_:)","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didBegin:)"],"generated":true}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS","watchOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder","text":"HKLiveWorkoutBuilder","preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"workoutActivity","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity","text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"workoutBuilder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The workout builder that received the new activity."}]}]},{"name":"workoutActivity","content":[{"inlineContent":[{"text":"The workout activity that just ended.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"modules":[{"name":"HealthKit"}],"title":"workoutBuilder(_:didEnd:)","platforms":[{"deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false,"name":"macOS"},{"deprecated":false,"beta":false,"introducedAt":"9.0","unavailable":false,"name":"watchOS"}],"externalID":"c:objc(pl)HKLiveWorkoutBuilderDelegate(im)workoutBuilder:didEndActivity:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","text":"HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"workoutBuilder:didEndActivity:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didEnd:)"},"abstract":[{"type":"text","text":"Tells the delegate that the current workout activity has ended."}],"variants":[{"paths":["/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilder(_:didend:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilder(_:didend:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity":{"abstract":[{"text":"An object that describes an activity within a longer workout.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutActivity"}],"title":"HKWorkoutActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutActivity"}],"role":"symbol","url":"/documentation/healthkit/hkworkoutactivity","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didCollectDataOf:)":{"navigatorTitle":[{"text":"workoutBuilder:didCollectDataOfTypes:","kind":"identifier"}],"url":"/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilder(_:didcollectdataof:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HKLiveWorkoutBuilder","preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCollectDataOf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSampleType","text":"HKSampleType","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"title":"workoutBuilder(_:didCollectDataOf:)","abstract":[{"text":"Tells the delegate that new data has been added to the builder.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didCollectDataOf:)","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder":{"abstract":[{"text":"A builder object that constructs a workout incrementally based on live data from an active workout session.","type":"text"}],"role":"symbol","title":"HKLiveWorkoutBuilder","navigatorTitle":[{"text":"HKLiveWorkoutBuilder","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKLiveWorkoutBuilder","kind":"identifier"}],"type":"topic","url":"/documentation/healthkit/hkliveworkoutbuilder","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didEnd:)":{"abstract":[{"text":"Tells the delegate that the current workout activity has ended.","type":"text"}],"role":"symbol","title":"workoutBuilder(_:didEnd:)","navigatorTitle":[{"text":"workoutBuilder:didEndActivity:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didEnd:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","text":"HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKWorkoutActivity","text":"HKWorkoutActivity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilder(_:didend:)","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate":{"navigatorTitle":[{"text":"HKLiveWorkoutBuilderDelegate","kind":"identifier"}],"url":"/documentation/healthkit/hkliveworkoutbuilderdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKLiveWorkoutBuilderDelegate","kind":"identifier"}],"title":"HKLiveWorkoutBuilderDelegate","abstract":[{"text":"A protocol for monitoring live workout builders.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate","type":"topic","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilderDidCollectEvent(_:)":{"navigatorTitle":[{"text":"workoutBuilderDidCollectEvent:","kind":"identifier"}],"url":"/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilderdidcollectevent(_:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilderDidCollectEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HKLiveWorkoutBuilder","preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"workoutBuilderDidCollectEvent(_:)","abstract":[{"text":"Tells the delegate that a new event has been added to the builder.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilderDidCollectEvent(_:)","type":"topic","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didBegin:)":{"abstract":[{"text":"Tells the delegate that a new workout activity has started.","type":"text"}],"role":"symbol","title":"workoutBuilder(_:didBegin:)","navigatorTitle":[{"text":"workoutBuilder:didBeginActivity:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didBegin:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","text":"HKLiveWorkoutBuilder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBegin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKWorkoutActivity","text":"HKWorkoutActivity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/healthkit/hkliveworkoutbuilderdelegate/workoutbuilder(_:didbegin:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"},{"deprecated":false,"beta":false,"introducedAt":"9.0","unavailable":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"workoutBuilder:didEndActivity:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"workoutBuilder:didEndActivity:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Tracking Live Data","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didCollectDataOf:)","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilderDidCollectEvent(_:)","doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilderDelegate/workoutBuilder(_:didBegin:)"],"generated":true,"anchor":"Tracking-Live-Data"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"workoutBuilder:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder","preciseIdentifier":"c:objc(cs)HKLiveWorkoutBuilder","kind":"typeIdentifier","text":"HKLiveWorkoutBuilder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"workoutBuilder"},{"text":" ","kind":"text"},{"text":"didEndActivity:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity","text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"workoutActivity","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"workoutBuilder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The workout builder that received the new activity."}]}]},{"name":"workoutActivity","content":[{"type":"paragraph","inlineContent":[{"text":"The workout activity that just ended.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"value":"HKWorkoutActivity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title"},{"value":[{"text":"HKWorkoutActivity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments"},{"value":[{"kind":"identifier","text":"HKWorkoutActivity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle"},{"value":"workoutBuilder:didCollectDataOfTypes:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didCollectDataOf:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutBuilder:didCollectDataOfTypes:"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didCollectDataOf:)/fragments"},{"value":"HKLiveWorkoutBuilder","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/title"},{"value":[{"text":"HKLiveWorkoutBuilder","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/fragments"},{"value":[{"kind":"identifier","text":"HKLiveWorkoutBuilder"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/navigatorTitle"},{"value":"workoutBuilder:didEndActivity:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didEnd:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutBuilder:didEndActivity:"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didEnd:)/fragments"},{"value":"HKLiveWorkoutBuilderDelegate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate/title"},{"value":[{"kind":"identifier","text":"HKLiveWorkoutBuilderDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate/fragments"},{"value":[{"kind":"identifier","text":"HKLiveWorkoutBuilderDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate/navigatorTitle"},{"value":"workoutBuilderDidCollectEvent:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilderDidCollectEvent(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutBuilderDidCollectEvent:"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilderDidCollectEvent(_:)/fragments"},{"value":"workoutBuilder:didBeginActivity:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didBegin:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"workoutBuilder:didBeginActivity:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilderDelegate~1workoutBuilder(_:didBegin:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}