{
  "abstract": [
    {
      "text": "An array representing the cellular calls in progress.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "To get a list of active calls, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallObserver",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/CallKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/currentCalls"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CTCallCenter(py)currentCalls",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentCalls"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sh",
        "text": "Set"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CTCall",
        "text": "CTCall"
      },
      {
        "kind": "text",
        "text": ">?"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentCalls"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "4.0",
        "message": "Replaced by <CallKit/CXCallObserver.h>",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "4.0",
        "message": "Replaced by <CallKit/CXCallObserver.h>",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Replaced by <CallKit/CXCallObserver.h>",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentCalls"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentCalls"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sh",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sh",
              "text": "Set"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CTCall",
              "text": "CTCall"
            },
            {
              "kind": "text",
              "text": ">? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array containing a ",
              "type": "text"
            },
            {
              "code": "CTCall",
              "type": "codeVoice"
            },
            {
              "text": " object for each cellular call in progress. If no calls are in progress, the value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall": {
      "abstract": [
        {
          "text": "An object used to identify a cellular call and determine its state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "role": "symbol",
      "title": "CTCall",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcall"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter": {
      "abstract": [
        {
          "text": "An object that provides a list of current cellular calls, and provides the ability to respond to state changes for calls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallCenter"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallCenter"
        }
      ],
      "role": "symbol",
      "title": "CTCallCenter",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallcenter"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/callEventHandler": {
      "abstract": [
        {
          "text": "A closure dispatched when a call changes state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callEventHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCall",
          "text": "CTCall"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/callEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callEventHandler"
        }
      ],
      "role": "symbol",
      "title": "callEventHandler",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallcenter/calleventhandler"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/currentCalls": {
      "abstract": [
        {
          "text": "An array representing the cellular calls in progress.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentCalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCall",
          "text": "CTCall"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/currentCalls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentCalls"
        }
      ],
      "role": "symbol",
      "title": "currentCalls",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallcenter/currentcalls"
    },
    "doc://com.apple.documentation/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/CallKit"
    },
    "doc://com.apple.documentation/documentation/CallKit/CXCallObserver": {
      "abstract": [
        {
          "text": "A programmatic interface for an object that manages a list of active calls and observes call changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallObserver"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallObserver",
      "kind": "symbol",
      "role": "symbol",
      "title": "CXCallObserver",
      "type": "topic",
      "url": "/documentation/CallKit/CXCallObserver"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sh": {
      "abstract": [
        {
          "text": "An unordered collection of unique elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sh",
      "kind": "symbol",
      "role": "symbol",
      "title": "Set",
      "type": "topic",
      "url": "/documentation/Swift/Set"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Cellular-Call-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/callEventHandler"
      ],
      "title": "Responding to Cellular Call Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentCalls"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentCalls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Cellular-Call-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter/callEventHandler"
              ],
              "title": "Responding to Cellular Call Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSSet",
                    "text": "NSSet<CTCall *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentCalls"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "To get a list of active calls, use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallObserver",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CallKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter~1currentCalls/title",
          "value": "currentCalls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter~1currentCalls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentCalls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/title",
          "value": "CTCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/title",
          "value": "CTCallCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CallKit~1CXCallObserver/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXCallObserver"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter~1callEventHandler/title",
          "value": "callEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter~1callEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callEventHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctcallcenter/currentcalls"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctcallcenter/currentcalls"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
