{
  "abstract": [
    {
      "text": "Layout priority used to indicate the relative importance of constraints, allowing Auto Layout to make appropriate tradeoffs when satisfying the constraints of the system as a whole.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@T@NSLayoutPriority",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Priority"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Priority"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSLayoutConstraint.Priority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Priority"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct": {
      "abstract": [
        {
          "text": "Layout priority used to indicate the relative importance of constraints, allowing Auto Layout to make appropriate tradeoffs when satisfying the constraints of the system as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Priority"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Priority",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultHigh": {
      "abstract": [
        {
          "text": "Priority level with which a button resists compressing its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityDefaultHigh"
        }
      ],
      "role": "symbol",
      "title": "defaultHigh",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/defaulthigh"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultLow": {
      "abstract": [
        {
          "text": "Priority level at which a button hugs its contents horizontally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultLow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityDefaultLow"
        }
      ],
      "role": "symbol",
      "title": "defaultLow",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/defaultlow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCanResizeWindow": {
      "abstract": [
        {
          "text": "Appropriate priority level for a drag that may end up resizing the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragThatCanResizeWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCanResizeWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityDragThatCanResizeWindow"
        }
      ],
      "role": "symbol",
      "title": "dragThatCanResizeWindow",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/dragthatcanresizewindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCannotResizeWindow": {
      "abstract": [
        {
          "text": "Priority level at which a split view divider, say, is dragged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragThatCannotResizeWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCannotResizeWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityDragThatCannotResizeWindow"
        }
      ],
      "role": "symbol",
      "title": "dragThatCannotResizeWindow",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/dragthatcannotresizewindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/fittingSizeCompression": {
      "abstract": [
        {
          "text": "When you send a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/fittingSize",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to a view, the smallest size that is large enough for the view’s contents is computed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fittingSizeCompression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/fittingSizeCompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityFittingSizeCompression"
        }
      ],
      "role": "symbol",
      "title": "fittingSizeCompression",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/fittingsizecompression"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/init(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/required": {
      "abstract": [
        {
          "text": "A required constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "required"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/required",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityRequired"
        }
      ],
      "role": "symbol",
      "title": "required",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/required"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/windowSizeStayPut": {
      "abstract": [
        {
          "text": "Priority level for the window’s current size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowSizeStayPut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/windowSizeStayPut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutPriorityWindowSizeStayPut"
        }
      ],
      "role": "symbol",
      "title": "windowSizeStayPut",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct/windowsizestayput"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/priority-swift.property": {
      "abstract": [
        {
          "text": "The priority of the constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/priority-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "priority"
        }
      ],
      "role": "symbol",
      "title": "priority",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/fittingSize": {
      "abstract": [
        {
          "text": "The minimum size of the view that satisfies the constraints it holds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fittingSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/fittingSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fittingSize"
        }
      ],
      "role": "symbol",
      "title": "fittingSize",
      "type": "topic",
      "url": "/documentation/appkit/nsview/fittingsize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SL": {
      "abstract": [
        {
          "text": "A type that can be compared using the relational operators `<`, `<=`, `>=`, and `>`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SL",
      "kind": "symbol",
      "role": "symbol",
      "title": "Comparable",
      "type": "topic",
      "url": "/documentation/Swift/Comparable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SL",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-layout-priority",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/priority-swift.property"
      ],
      "title": "Getting the layout priority"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/required",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultHigh",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCanResizeWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/windowSizeStayPut",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCannotResizeWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultLow",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/fittingSizeCompression"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLayoutPriority"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/required",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultHigh",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCanResizeWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/windowSizeStayPut",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/dragThatCannotResizeWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/defaultLow",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct/fittingSizeCompression"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-layout-priority",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/priority-swift.property"
              ],
              "title": "Getting the layout priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSLayoutPriority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1dragThatCannotResizeWindow/title",
          "value": "NSLayoutPriorityDragThatCannotResizeWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1dragThatCannotResizeWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityDragThatCannotResizeWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1fittingSizeCompression/title",
          "value": "NSLayoutPriorityFittingSizeCompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1fittingSizeCompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityFittingSizeCompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1fittingSize/title",
          "value": "fittingSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1fittingSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fittingSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1required/title",
          "value": "NSLayoutPriorityRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1required/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1dragThatCanResizeWindow/title",
          "value": "NSLayoutPriorityDragThatCanResizeWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1dragThatCanResizeWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityDragThatCanResizeWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1defaultHigh/title",
          "value": "NSLayoutPriorityDefaultHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1defaultHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityDefaultHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/title",
          "value": "NSLayoutPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1priority-swift.property/title",
          "value": "priority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1priority-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1windowSizeStayPut/title",
          "value": "NSLayoutPriorityWindowSizeStayPut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1windowSizeStayPut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityWindowSizeStayPut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1defaultLow/title",
          "value": "NSLayoutPriorityDefaultLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct~1defaultLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriorityDefaultLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutconstraint/priority-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutconstraint/priority-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
