{
  "abstract": [
    {
      "text": "The value that indicates activities in the air.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLActivityType@CLActivityTypeAirborne",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "airborne"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLActivityTypeAirborne"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLActivityType.airborne"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "airborne"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this activity type for activities such as flying in an airplane or helicopter, paragliding, flying on a drone, skydiving, and so on. This activity also includes runway taxiing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of activity associated with location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLActivityType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityType"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne": {
      "abstract": [
        {
          "text": "The value that indicates activities in the air.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airborne"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeAirborne"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.airborne",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/airborne"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation": {
      "abstract": [
        {
          "text": "The value that indicates positioning in an automobile following a road network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automotiveNavigation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeAutomotiveNavigation"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.automotiveNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/automotivenavigation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness": {
      "abstract": [
        {
          "text": "The value that indicates positioning during dedicated fitness sessions, such as walking workouts, running workouts, cycling workouts, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fitness"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeFitness"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.fitness",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/fitness"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other": {
      "abstract": [
        {
          "text": "The value that indicates the app is using location manager for an unspecified activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeOther"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.other",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/other"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation": {
      "abstract": [
        {
          "text": "The value that indicates positioning for activities that don’t or may not adhere to roads such as cycling, scooters, trains, boats and off-road vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherNavigation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeOtherNavigation"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.otherNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/othernavigation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Activity-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation"
      ],
      "title": "Activity types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLActivityTypeAirborne"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAirborne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Activity-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation"
              ],
              "title": "Activity types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLActivityTypeAirborne"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/title",
          "value": "CLActivityTypeAutomotiveNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAutomotiveNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1other/title",
          "value": "CLActivityTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/title",
          "value": "CLActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1otherNavigation/title",
          "value": "CLActivityTypeOtherNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1otherNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeOtherNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1airborne/title",
          "value": "CLActivityTypeAirborne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1airborne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAirborne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1fitness/title",
          "value": "CLActivityTypeFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1fitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeFitness"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clactivitytype/airborne"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/clactivitytype/airborne"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
