{
  "abstract": [
    {
      "text": "Tells the system to stop observing previously registered traits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/unregisterForTraitChanges:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITraitChangeObservable(im)unregisterForTraitChanges:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "unregisterForTraitChanges:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unregisterForTraitChanges:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "unregisterForTraitChanges:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "unregisterForTraitChanges:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)UITraitChangeRegistration",
              "text": "id<UITraitChangeRegistration>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "registration"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A token that identifies the registration, obtained from one of the trait registration method calls.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "registration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method if you want the system to stop observing trait changes for a previous registration. UIKit doesn’t require you to unregister for trait changes at the end of the view lifecycle. Unregister only if you need to dynamically change which traits you observe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangehandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withAction:": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the receiving object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withAction:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withAction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withAction:"
        }
      ],
      "role": "symbol",
      "title": "registerForTraitChanges:withAction:",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet/registerfortraitchanges:withaction:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withHandler:": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe and a closure to execute when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withHandler:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "registerForTraitChanges:withHandler:",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet/registerfortraitchanges:withhandler:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withTarget:action:": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the specified target object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withTarget:action:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withTarget:action:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForTraitChanges:withTarget:action:"
        }
      ],
      "role": "symbol",
      "title": "registerForTraitChanges:withTarget:action:",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet/registerfortraitchanges:withtarget:action:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/unregisterForTraitChanges:": {
      "abstract": [
        {
          "text": "Tells the system to stop observing previously registered traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "unregisterForTraitChanges:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/unregisterForTraitChanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterForTraitChanges:"
        }
      ],
      "role": "symbol",
      "title": "unregisterForTraitChanges:",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet/unregisterfortraitchanges:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeRegistration",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeregistration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-trait-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withAction:",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withHandler:",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet/registerForTraitChanges:withTarget:action:",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeHandler",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration"
      ],
      "title": "Observing trait changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/title",
          "value": "UITraitChangeRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitraitchangeobservable-7qoet/unregisterfortraitchanges:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
