{
  "abstract": [
    {
      "text": "The requested transaction contains call actions that reference a UUID that already exists.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC34CXErrorCodeRequestTransactionErrorLeV21callUUIDAlreadyExistsSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "callUUIDAlreadyExists"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
        "text": "CXErrorCodeRequestTransactionError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "callUUIDAlreadyExists"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "callUUIDAlreadyExists"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
              "text": "CXErrorCodeRequestTransactionError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference a UUID that already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callUUIDAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "callUUIDAlreadyExists",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/calluuidalreadyexists"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction": {
      "abstract": [
        {
          "text": "The requested transaction doesn’t contain any actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emptyTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction",
      "kind": "symbol",
      "role": "symbol",
      "title": "emptyTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/emptytransaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction": {
      "abstract": [
        {
          "text": "The requested transaction contains an invalid action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/invalidaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached": {
      "abstract": [
        {
          "text": "Performing the requested transaction exceeds the maximum number of call groups for the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallGroupsReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumCallGroupsReached",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/maximumcallgroupsreached"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled": {
      "abstract": [
        {
          "text": "The app doesn’t have the entitlement to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled",
      "kind": "symbol",
      "role": "symbol",
      "title": "unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider": {
      "abstract": [
        {
          "text": "The controller can’t find a call provider to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownCallProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknowncallprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference an unknown UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownCallUUID",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknowncalluuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/title",
          "value": "CXErrorCodeRequestTransactionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/calluuidalreadyexists"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
