{
  "abstract": [
    {
      "text": "Error codes for the CallKit error domain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXErrorCodeRequestTransactionError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CXErrorCodeRequestTransactionError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callIsProtected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callIsProtected"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callIsProtected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorCallIsProtected"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.callIsProtected",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/callisprotected"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference a UUID that already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callUUIDAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.callUUIDAlreadyExists",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/calluuidalreadyexists"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction": {
      "abstract": [
        {
          "text": "The requested transaction contains no actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emptyTransaction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.emptyTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/emptytransaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction": {
      "abstract": [
        {
          "text": "The requested transaction contains an invalid action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorInvalidAction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.invalidAction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/invalidaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached": {
      "abstract": [
        {
          "text": "The requested transaction contains actions that, if performed, would exceed the maximum number of call groups for the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallGroupsReached"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.maximumCallGroupsReached",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/maximumcallgroupsreached"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled": {
      "abstract": [
        {
          "text": "The app isn’t entitled to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnentitled"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider": {
      "abstract": [
        {
          "text": "The controller couldn’t find a call provider to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknownCallProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknowncallprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference an unknown UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallUUID"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknownCallUUID",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknowncalluuid"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction": {
      "abstract": [
        {
          "text": "Domain for errors when requesting a transaction from a call controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainRequestTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainRequestTransaction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainRequestTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomainrequesttransaction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callIsProtected"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXErrorCodeRequestTransactionError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callIsProtected"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXErrorCodeRequestTransactionError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallProvider/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1emptyTransaction/title",
          "value": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1emptyTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unentitled/title",
          "value": "CXErrorCodeRequestTransactionErrorUnentitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unentitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnentitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/title",
          "value": "CXErrorCodeRequestTransactionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1maximumCallGroupsReached/title",
          "value": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1maximumCallGroupsReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callIsProtected/title",
          "value": "CXErrorCodeRequestTransactionErrorCallIsProtected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callIsProtected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorCallIsProtected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainRequestTransaction/title",
          "value": "CXErrorDomainRequestTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainRequestTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainRequestTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallUUID/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1invalidAction/title",
          "value": "CXErrorCodeRequestTransactionErrorInvalidAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1invalidAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknown/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callUUIDAlreadyExists/title",
          "value": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callUUIDAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
