{
  "abstract": [
    {
      "text": "The thumb image currently being used to render the slider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISlider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISlider/currentThumbImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISlider(py)currentThumbImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentThumbImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentThumbImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentThumbImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentThumbImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sliders can have different thumb images for different control states. The active control state determines which thumb image is stored in this property. To get the thumb image for a different control state, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbImage(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If no custom thumb images have been set using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/setThumbImage(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". In that situation, the slider uses the default thumb image for drawing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider": {
      "abstract": [
        {
          "text": "A control for selecting a single value from a continuous range of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISlider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISlider"
        }
      ],
      "role": "symbol",
      "title": "UISlider",
      "type": "topic",
      "url": "/documentation/uikit/uislider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMaximumTrackImage": {
      "abstract": [
        {
          "text": "Contains the maximum track image currently being used to render the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentMaximumTrackImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMaximumTrackImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentMaximumTrackImage"
        }
      ],
      "role": "symbol",
      "title": "currentMaximumTrackImage",
      "type": "topic",
      "url": "/documentation/uikit/uislider/currentmaximumtrackimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMinimumTrackImage": {
      "abstract": [
        {
          "text": "The minimum track image currently being used to render the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentMinimumTrackImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMinimumTrackImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentMinimumTrackImage"
        }
      ],
      "role": "symbol",
      "title": "currentMinimumTrackImage",
      "type": "topic",
      "url": "/documentation/uikit/uislider/currentminimumtrackimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/currentThumbImage": {
      "abstract": [
        {
          "text": "The thumb image currently being used to render the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentThumbImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/currentThumbImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentThumbImage"
        }
      ],
      "role": "symbol",
      "title": "currentThumbImage",
      "type": "topic",
      "url": "/documentation/uikit/uislider/currentthumbimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackImage(for:)": {
      "abstract": [
        {
          "text": "Returns the maximum track image associated with the specified control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumTrackImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumTrackImageForState:"
        }
      ],
      "role": "symbol",
      "title": "maximumTrackImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/maximumtrackimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackTintColor": {
      "abstract": [
        {
          "text": "The color used to tint the default maximum track images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumTrackTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumTrackTintColor"
        }
      ],
      "role": "symbol",
      "title": "maximumTrackTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uislider/maximumtracktintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumValueImage": {
      "abstract": [
        {
          "text": "The image representing the slider’s maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumValueImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumValueImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumValueImage"
        }
      ],
      "role": "symbol",
      "title": "maximumValueImage",
      "type": "topic",
      "url": "/documentation/uikit/uislider/maximumvalueimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackImage(for:)": {
      "abstract": [
        {
          "text": "Returns the minimum track image associated with the specified control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumTrackImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumTrackImageForState:"
        }
      ],
      "role": "symbol",
      "title": "minimumTrackImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/minimumtrackimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackTintColor": {
      "abstract": [
        {
          "text": "The color used to tint the default minimum track images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumTrackTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumTrackTintColor"
        }
      ],
      "role": "symbol",
      "title": "minimumTrackTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uislider/minimumtracktintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumValueImage": {
      "abstract": [
        {
          "text": "The image that represents the slider’s minimum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumValueImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumValueImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumValueImage"
        }
      ],
      "role": "symbol",
      "title": "minimumValueImage",
      "type": "topic",
      "url": "/documentation/uikit/uislider/minimumvalueimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/setMaximumTrackImage(_:for:)": {
      "abstract": [
        {
          "text": "Assigns a maximum track image to the specified control states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMaximumTrackImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/setMaximumTrackImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMaximumTrackImage:forState:"
        }
      ],
      "role": "symbol",
      "title": "setMaximumTrackImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/setmaximumtrackimage(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/setMinimumTrackImage(_:for:)": {
      "abstract": [
        {
          "text": "Assigns a minimum track image to the specified control states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMinimumTrackImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/setMinimumTrackImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMinimumTrackImage:forState:"
        }
      ],
      "role": "symbol",
      "title": "setMinimumTrackImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/setminimumtrackimage(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/setThumbImage(_:for:)": {
      "abstract": [
        {
          "text": "Assigns a thumb image to the specified control states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setThumbImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/setThumbImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setThumbImage:forState:"
        }
      ],
      "role": "symbol",
      "title": "setThumbImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/setthumbimage(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbImage(for:)": {
      "abstract": [
        {
          "text": "Returns the thumb image associated with the specified control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thumbImageForState:"
        }
      ],
      "role": "symbol",
      "title": "thumbImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uislider/thumbimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbTintColor": {
      "abstract": [
        {
          "text": "The color used to tint the default thumb images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thumbTintColor"
        }
      ],
      "role": "symbol",
      "title": "thumbTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uislider/thumbtintcolor"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Changing-the-sliders-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumValueImage",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumValueImage",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMinimumTrackImage",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackImage(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/setMinimumTrackImage(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMaximumTrackImage",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackImage(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/setMaximumTrackImage(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbImage(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISlider/setThumbImage(_:for:)"
      ],
      "title": "Changing the slider’s appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentThumbImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentThumbImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISlider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Changing-the-sliders-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumValueImage",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumValueImage",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMinimumTrackImage",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/minimumTrackImage(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/setMinimumTrackImage(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/currentMaximumTrackImage",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/maximumTrackImage(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/setMaximumTrackImage(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/thumbImage(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISlider/setThumbImage(_:for:)"
              ],
              "title": "Changing the slider’s appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentThumbImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumTrackTintColor/title",
          "value": "maximumTrackTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumTrackTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumTrackTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumTrackTintColor/title",
          "value": "minimumTrackTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumTrackTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumTrackTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumTrackImage(for:)/title",
          "value": "maximumTrackImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumTrackImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "maximumTrackImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentThumbImage/title",
          "value": "currentThumbImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentThumbImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentThumbImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider/title",
          "value": "UISlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentMaximumTrackImage/title",
          "value": "currentMaximumTrackImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentMaximumTrackImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentMaximumTrackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setMinimumTrackImage(_:for:)/title",
          "value": "setMinimumTrackImage:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setMinimumTrackImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMinimumTrackImage:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumValueImage/title",
          "value": "maximumValueImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1maximumValueImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumValueImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1thumbTintColor/title",
          "value": "thumbTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1thumbTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thumbTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1thumbImage(for:)/title",
          "value": "thumbImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1thumbImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "thumbImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentMinimumTrackImage/title",
          "value": "currentMinimumTrackImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1currentMinimumTrackImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentMinimumTrackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumTrackImage(for:)/title",
          "value": "minimumTrackImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumTrackImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "minimumTrackImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setThumbImage(_:for:)/title",
          "value": "setThumbImage:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setThumbImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setThumbImage:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setMaximumTrackImage(_:for:)/title",
          "value": "setMaximumTrackImage:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1setMaximumTrackImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMaximumTrackImage:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumValueImage/title",
          "value": "minimumValueImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISlider~1minimumValueImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumValueImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uislider/currentthumbimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uislider/currentthumbimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
