{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "ADClientErrorLimitAdTracking has been deprecated use ADClientErrorTrackingRestrictedOrDenied.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iad/documentation/iAd",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC13ADClientErrorLeV15limitAdTrackingSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "limitAdTracking"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC13ADClientErrorLeV",
        "text": "ADClientError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ADClientError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": true,
        "message": "ADClientErrorLimitAdTracking has been deprecated use ADClientErrorTrackingRestrictedOrDenied.",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "limitAdTracking"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "limitAdTracking"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC13ADClientErrorLeV",
              "text": "ADClientError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ADClientError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct": {
      "abstract": [
        {
          "text": "The group of error codes that pass from the attribution response to the completion handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The error codes that pass from the attribution response to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse": {
      "abstract": [
        {
          "text": "The response received from the attribution server was corrupt.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "corruptResponse",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/corruptresponse"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitAdTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "limitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/limitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData": {
      "abstract": [
        {
          "text": "The downloaded app received a payload lacking enough data to perform an attribution check.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingData",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/missingdata"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError": {
      "abstract": [
        {
          "text": "The response received from the attribution server had an HTTP 4xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestClientError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestclienterror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError": {
      "abstract": [
        {
          "text": "The communication with the attribution server had a network error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestNetworkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestNetworkError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestnetworkerror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError": {
      "abstract": [
        {
          "text": "The response received from the attribution server had an HTTP 5xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestServerError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestServerError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestservererror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied": {
      "abstract": [
        {
          "text": "The user is restricted or has denied tracking for the calling application.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingRestrictedOrDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingRestrictedOrDenied",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/trackingrestrictedordenied"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/unknown"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform": {
      "abstract": [
        {
          "text": "The attribution API was called on an unsupported platform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/unsupportedplatform"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/title",
          "value": "ADClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad/adclienterror-swift.struct/limitadtracking"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
