{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"mentions":["doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar"],"kind":"mentions"}],"metadata":{"modules":[{"name":"UIKit"}],"role":"symbol","title":"isHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"hidden"}],"symbolKind":"property","roleHeading":"Instance Property","platforms":[{"introducedAt":"18.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"18.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"18.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"2.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"externalID":"c:objc(cs)UITabBarControllerSidebar(py)hidden"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/isHidden","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"anchor":"Managing-customization","title":"Managing customization","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/preferredLayout","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Layout","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/reconfigureItem(for:)"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uitabbarcontroller/sidebar-swift.class/ishidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitabbarcontroller/sidebar-swift.class/ishidden"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Layout":{"title":"UITabBarController.Sidebar.Layout","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layout","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"Layout","kind":"identifier"}],"abstract":[],"url":"/documentation/uikit/uitabbarcontroller/sidebar-swift.class/layout","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Layout"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/preferredLayout":{"navigatorTitle":[{"text":"preferredLayout","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/preferredLayout","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITabBarController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarController"},{"text":".","kind":"text"},{"text":"Sidebar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarControllerSidebar"},{"text":".","kind":"text"},{"text":"Layout","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITabBarControllerSidebarLayout"}],"url":"/documentation/uikit/uitabbarcontroller/sidebar-swift.class/preferredlayout","abstract":[],"title":"preferredLayout","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController":{"abstract":[{"type":"text","text":"A container view controller that manages a multiselection interface, where the selection determines which child view controller to display."}],"navigatorTitle":[{"text":"UITabBarController","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController","url":"/documentation/uikit/uitabbarcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarController","kind":"identifier"}],"role":"symbol","title":"UITabBarController","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/isHidden":{"title":"isHidden","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"abstract":[],"url":"/documentation/uikit/uitabbarcontroller/sidebar-swift.class/ishidden","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/isHidden"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class":{"abstract":[{"type":"text","text":"An object for managing and configuring the sidebar."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Sidebar","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class","type":"topic","title":"UITabBarController.Sidebar","kind":"symbol","role":"symbol","url":"/documentation/uikit/uitabbarcontroller/sidebar-swift.class","navigatorTitle":[{"text":"Sidebar","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar":{"kind":"article","url":"/documentation/uikit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar","abstract":[{"type":"text","text":"Provide a compact, ergonomic tab bar for quick access to key parts of your app, and a sidebar for in-depth navigation."}],"type":"topic","title":"Elevating your iPad app with a tab bar and sidebar","identifier":"doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar","role":"article"},"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/reconfigureItem(for:)":{"role":"symbol","title":"reconfigureItem(for:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"reconfigureItemForTab:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconfigureItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITab","preciseIdentifier":"c:objc(cs)UITab"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uitabbarcontroller/sidebar-swift.class/reconfigureitem(for:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/reconfigureItem(for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"hidden","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"hidden"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"value":[{"title":"Managing customization","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/preferredLayout","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/Layout","doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class/reconfigureItem(for:)"],"anchor":"Managing-customization"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Layout/title","value":"UITabBarControllerSidebarLayout","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Layout/fragments","value":[{"kind":"identifier","text":"UITabBarControllerSidebarLayout"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1Layout/navigatorTitle","value":[{"kind":"identifier","text":"UITabBarControllerSidebarLayout"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1preferredLayout/title","value":"preferredLayout","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1preferredLayout/fragments","value":[{"text":"preferredLayout","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title","value":"UITabBarController","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments","value":[{"text":"UITabBarController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle","value":[{"text":"UITabBarController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1isHidden/title","value":"hidden","op":"replace"},{"value":[{"text":"hidden","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1isHidden/fragments","op":"replace"},{"value":"UITabBarControllerSidebar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITabBarControllerSidebar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UITabBarControllerSidebar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/navigatorTitle","op":"replace"},{"value":"reconfigureItemForTab:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1reconfigureItem(for:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reconfigureItemForTab:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class~1reconfigureItem(for:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}