{
  "abstract": [
    {
      "text": "Removes a font weight from a range of text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeightInRange:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMutableCaption(im)removeFontWeightInRange:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "removeFontWeightInRange:"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeFontWeightInRange:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeFontWeightInRange:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "removeFontWeightInRange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range from which to remove the style.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration": {
      "abstract": [
        {
          "text": "Text decorations for caption text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.Decoration",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/decoration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle": {
      "abstract": [
        {
          "text": "Font styles for caption text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontStyle"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontStyle"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.FontStyle",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/fontstyle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight": {
      "abstract": [
        {
          "text": "Font weights for a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontWeight"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontWeight"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.FontWeight",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/fontweight"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption": {
      "abstract": [
        {
          "text": "A mutable caption subclass that you use to create new captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCaption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecorationInRange:": {
      "abstract": [
        {
          "text": "Removes a decoration from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeDecorationInRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecorationInRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeDecorationInRange:"
        }
      ],
      "role": "symbol",
      "title": "removeDecorationInRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removedecorationinrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyleInRange:": {
      "abstract": [
        {
          "text": "Removes a font style from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeFontStyleInRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyleInRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFontStyleInRange:"
        }
      ],
      "role": "symbol",
      "title": "removeFontStyleInRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removefontstyleinrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeightInRange:": {
      "abstract": [
        {
          "text": "Removes a font weight from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeFontWeightInRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeightInRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFontWeightInRange:"
        }
      ],
      "role": "symbol",
      "title": "removeFontWeightInRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removefontweightinrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration:inRange:": {
      "abstract": [
        {
          "text": "Sets a decoration for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDecoration:inRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration:inRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDecoration:inRange:"
        }
      ],
      "role": "symbol",
      "title": "setDecoration:inRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setdecoration:inrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle:inRange:": {
      "abstract": [
        {
          "text": "Sets the font style for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFontStyle:inRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle:inRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFontStyle:inRange:"
        }
      ],
      "role": "symbol",
      "title": "setFontStyle:inRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setfontstyle:inrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight:inRange:": {
      "abstract": [
        {
          "text": "Sets the font weight for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFontWeight:inRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight:inRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFontWeight:inRange:"
        }
      ],
      "role": "symbol",
      "title": "setFontWeight:inRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setfontweight:inrange:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Font-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle:inRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyleInRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight:inRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration:inRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecorationInRange:"
      ],
      "title": "Configuring Font Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/title",
          "value": "AVCaptionFontStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/title",
          "value": "AVMutableCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/title",
          "value": "AVCaptionDecoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDecoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDecoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/title",
          "value": "AVCaptionFontWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontWeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmutablecaption/removefontweightinrange:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
