{
  "abstract": [
    {
      "text": "Sets a decoration for a range of text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration(_:in:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "s:So16AVMutableCaptionC12AVFoundationE13setDecoration_2inySo09AVCaptionE0V_So8_NSRangeVtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setDecoration"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaption",
        "text": "AVCaption"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVCaptionDecoration",
        "text": "Decoration"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "in"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "NSRange"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setDecoration(_:in:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setDecoration"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "decoration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaption",
              "text": "AVCaption"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCaptionDecoration",
              "text": "Decoration"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "in"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The decoration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "decoration"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range to which this decoration applies.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption": {
      "abstract": [
        {
          "text": "An object that represents text to present over a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaption"
        }
      ],
      "role": "symbol",
      "title": "AVCaption",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration": {
      "abstract": [
        {
          "text": "Text decorations for caption text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.Decoration",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/decoration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle": {
      "abstract": [
        {
          "text": "Font styles for caption text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontStyle"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontStyle"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.FontStyle",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/fontstyle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight": {
      "abstract": [
        {
          "text": "Font weights for a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontWeight"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontWeight"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.FontWeight",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/fontweight"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption": {
      "abstract": [
        {
          "text": "A mutable caption subclass that you use to create new captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCaption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecoration(in:)": {
      "abstract": [
        {
          "text": "Removes a decoration from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeDecoration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecoration(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeDecoration(in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removedecoration(in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyle(in:)": {
      "abstract": [
        {
          "text": "Removes a font style from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFontStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyle(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeFontStyle(in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removefontstyle(in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeight(in:)": {
      "abstract": [
        {
          "text": "Removes a font weight from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFontWeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeight(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeFontWeight(in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removefontweight(in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration(_:in:)": {
      "abstract": [
        {
          "text": "Sets a decoration for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDecoration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaption",
          "text": "AVCaption"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionDecoration",
          "text": "Decoration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setDecoration(_:in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDecoration(_:in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setdecoration(_:in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle(_:in:)": {
      "abstract": [
        {
          "text": "Sets the font style for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFontStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaption",
          "text": "AVCaption"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionFontStyle",
          "text": "FontStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle(_:in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFontStyle(_:in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setfontstyle(_:in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight(_:in:)": {
      "abstract": [
        {
          "text": "Sets the font weight for a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFontWeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaption",
          "text": "AVCaption"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionFontWeight",
          "text": "FontWeight"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight(_:in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFontWeight(_:in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setfontweight(_:in:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Font-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontStyle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontStyle(_:in:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontStyle(in:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/FontWeight",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setFontWeight(_:in:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeFontWeight(in:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Decoration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeDecoration(in:)"
      ],
      "title": "Configuring Font Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption/title",
          "value": "AVCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/title",
          "value": "AVCaptionFontWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontWeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/title",
          "value": "AVMutableCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/title",
          "value": "AVCaptionFontStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1FontStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/title",
          "value": "AVCaptionDecoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDecoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Decoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDecoration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmutablecaption/setdecoration(_:in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
