{
  "abstract": [
    {
      "text": "Sets text combine for a range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setTextCombine:inRange:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMutableCaption(im)setTextCombine:inRange:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setTextCombine:inRange:"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setTextCombine:inRange:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setTextCombine:inRange:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setTextCombine:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/TextCombine",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVCaptionTextCombine",
              "text": "AVCaptionTextCombine"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "textCombine"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inRange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text combine.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textCombine"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range to which the text combine applies.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Ruby": {
      "abstract": [
        {
          "text": "An object that presents ruby characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Ruby"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Ruby",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Ruby"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.Ruby",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/ruby"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/TextCombine": {
      "abstract": [
        {
          "text": "The caption’s supported rendering policy options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextCombine"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/TextCombine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextCombine"
        }
      ],
      "role": "symbol",
      "title": "AVCaption.TextCombine",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaption/textcombine"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption": {
      "abstract": [
        {
          "text": "A mutable caption subclass that you use to create new captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCaption"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCaption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeRubyInRange:": {
      "abstract": [
        {
          "text": "Removes ruby text from a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeRubyInRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeRubyInRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeRubyInRange:"
        }
      ],
      "role": "symbol",
      "title": "removeRubyInRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removerubyinrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeTextCombineInRange:": {
      "abstract": [
        {
          "text": "Removes text combine from a range of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeTextCombineInRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeTextCombineInRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTextCombineInRange:"
        }
      ],
      "role": "symbol",
      "title": "removeTextCombineInRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/removetextcombineinrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setRuby:inRange:": {
      "abstract": [
        {
          "text": "Sets ruby text for a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setRuby:inRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setRuby:inRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRuby:inRange:"
        }
      ],
      "role": "symbol",
      "title": "setRuby:inRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/setruby:inrange:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setTextCombine:inRange:": {
      "abstract": [
        {
          "text": "Sets text combine for a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTextCombine:inRange:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setTextCombine:inRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTextCombine:inRange:"
        }
      ],
      "role": "symbol",
      "title": "setTextCombine:inRange:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaption/settextcombine:inrange:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Advanced-Typography",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/Ruby",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/setRuby:inRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeRubyInRange:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaption/TextCombine",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaption/removeTextCombineInRange:"
      ],
      "title": "Configuring Advanced Typography"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Ruby/title",
          "value": "AVCaptionRuby"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Ruby/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRuby"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1Ruby/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRuby"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/title",
          "value": "AVMutableCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1TextCombine/title",
          "value": "AVCaptionTextCombine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1TextCombine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionTextCombine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaption~1TextCombine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionTextCombine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmutablecaption/settextcombine:inrange:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
