{
  "abstract": [
    {
      "text": "The system canceled tracking for the button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPress",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/cancelled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPressPhase@UIPressPhaseCancelled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cancelled"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPressPhaseCancelled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIPress.Phase.cancelled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cancelled"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress": {
      "abstract": [
        {
          "text": "An object that represents the presence or movement of a button press on the screen for a particular event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "role": "symbol",
      "title": "UIPress",
      "type": "topic",
      "url": "/documentation/uikit/uipress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represent the phases of a button press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/began": {
      "abstract": [
        {
          "text": "A physical button was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressPhaseBegan"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase.began",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum/began"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/cancelled": {
      "abstract": [
        {
          "text": "The system canceled tracking for the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressPhaseCancelled"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase.cancelled",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum/cancelled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/changed": {
      "abstract": [
        {
          "text": "A button moved, or the force property changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/changed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressPhaseChanged"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase.changed",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum/changed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/ended": {
      "abstract": [
        {
          "text": "A button was released.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressPhaseEnded"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase.ended",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum/ended"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/stationary": {
      "abstract": [
        {
          "text": "A button was pressed but hasn’t moved since the previous event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stationary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/stationary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressPhaseStationary"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase.stationary",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum/stationary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/began",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/changed",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/stationary",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/ended"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPressPhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/began",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/changed",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/stationary",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum/ended"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPressPhaseCancelled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/title",
          "value": "UIPress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1stationary/title",
          "value": "UIPressPhaseStationary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1stationary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseStationary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1began/title",
          "value": "UIPressPhaseBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1ended/title",
          "value": "UIPressPhaseEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1changed/title",
          "value": "UIPressPhaseChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1changed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/title",
          "value": "UIPressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1cancelled/title",
          "value": "UIPressPhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhaseCancelled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipress/phase-swift.enum/cancelled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipress/phase-swift.enum/cancelled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
