{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SFSafariServicesVersion@SFSafariServicesVersion10_1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "version10_1"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSafariServicesVersion10_1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SFSafariServicesVersion.version10_1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "version10_1"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion": {
      "abstract": [
        {
          "text": "The version of Safari services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version10_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion10_0"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version10_0",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version10_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version10_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion10_1"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version10_1",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version10_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version11_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version11_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion11_0"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version11_0",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version11_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version12_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion12_0"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version12_0",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version12_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version12_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion12_1"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version12_1",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version12_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version13_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version13_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version13_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion13_0"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion.version13_0",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion/version13_0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_0",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version11_0",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_0",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_1",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version13_0"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSafariServicesVersion10_1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion10_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safariservices/documentation/SafariServices",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version10_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version11_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version12_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion/version13_0"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SFSafariServicesVersion10_1"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version13_0/title",
          "value": "SFSafariServicesVersion13_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version13_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion13_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/title",
          "value": "SFSafariServicesVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version10_0/title",
          "value": "SFSafariServicesVersion10_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version10_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion10_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version10_1/title",
          "value": "SFSafariServicesVersion10_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version10_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion10_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version11_0/title",
          "value": "SFSafariServicesVersion11_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version11_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion11_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version12_0/title",
          "value": "SFSafariServicesVersion12_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version12_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion12_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version12_1/title",
          "value": "SFSafariServicesVersion12_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion~1version12_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion12_1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfsafariservicesversion/version10_1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/sfsafariservicesversion/version10_1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
