{
  "abstract": [
    {
      "text": "The Uniform Type Identifier to assign to this type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UTExportedTypeDeclarations.UTTypeIdentifier",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UTTypeIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UTTypeIdentifier"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Identifier",
        "name": "UTTypeIdentifier",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations": {
      "abstract": [
        {
          "text": "The uniform type identifiers owned and exported by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Exported Type UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
      "kind": "symbol",
      "name": "UTExportedTypeDeclarations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTExportedTypeDeclarations"
        }
      ],
      "role": "symbol",
      "title": "UTExportedTypeDeclarations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo": {
      "abstract": [
        {
          "text": "The Uniform Type Identifier types that this type conforms to.",
          "type": "text"
        }
      ],
      "ideTitle": "Conforms to UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo",
      "kind": "symbol",
      "name": "UTTypeConformsTo",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeConformsTo"
        }
      ],
      "role": "symbol",
      "title": "UTTypeConformsTo",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeconformsto"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription": {
      "abstract": [
        {
          "text": "A description for this type.",
          "type": "text"
        }
      ],
      "ideTitle": "Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription",
      "kind": "symbol",
      "name": "UTTypeDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeDescription"
        }
      ],
      "role": "symbol",
      "title": "UTTypeDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile": {
      "abstract": [
        {
          "text": "The bundle icon resource to associate with this type.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon file name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile",
      "kind": "symbol",
      "name": "UTTypeIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeIconFile"
        }
      ],
      "role": "symbol",
      "title": "UTTypeIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles": {
      "abstract": [
        {
          "text": "One or more bundle icon resources to associate with this type.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon file names",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles",
      "kind": "symbol",
      "name": "UTTypeIconFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeIconFiles"
        }
      ],
      "role": "symbol",
      "title": "UTTypeIconFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeiconfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier": {
      "abstract": [
        {
          "text": "The Uniform Type Identifier to assign to this type.",
          "type": "text"
        }
      ],
      "ideTitle": "Identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier",
      "kind": "symbol",
      "name": "UTTypeIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UTTypeIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL": {
      "abstract": [
        {
          "text": "The webpage for a reference document that describes this type.",
          "type": "text"
        }
      ],
      "ideTitle": "Reference URL",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL",
      "kind": "symbol",
      "name": "UTTypeReferenceURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeReferenceURL"
        }
      ],
      "role": "symbol",
      "title": "UTTypeReferenceURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypereferenceurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification": {
      "abstract": [
        {
          "text": "A dictionary defining one or more equivalent type identifiers.",
          "type": "text"
        }
      ],
      "ideTitle": "Equivalent Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification",
      "kind": "symbol",
      "name": "UTTypeTagSpecification",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeTagSpecification"
        }
      ],
      "role": "symbol",
      "title": "UTTypeTagSpecification",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypetagspecification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-List-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UTTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeTagSpecification/title",
          "value": "UTTypeTagSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeTagSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeTagSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeReferenceURL/title",
          "value": "UTTypeReferenceURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeReferenceURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeReferenceURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFile/title",
          "value": "UTTypeIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeDescription/title",
          "value": "UTTypeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFiles/title",
          "value": "UTTypeIconFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeIconFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/title",
          "value": "UTExportedTypeDeclarations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTExportedTypeDeclarations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIdentifier/title",
          "value": "UTTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeConformsTo/title",
          "value": "UTTypeConformsTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeConformsTo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTTypeConformsTo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
