{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo"},"abstract":[{"text":"The Uniform Type Identifier types that this type conforms to.","type":"text"}],"variants":[{"paths":["/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeconformsto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeconformsto"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"details","details":{"titleStyle":"symbol","value":[{"baseType":"string ","arrayMode":true}],"name":"UTTypeConformsTo","ideTitle":"Conforms to UTIs","platforms":[]},"title":"Details"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations"]]},"seeAlsoSections":[{"title":"Property List Keys","anchor":"Property-List-Keys","identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification"],"generated":true}],"metadata":{"symbolKind":"typealias","externalID":"plist:Information_Property_List.UTExportedTypeDeclarations.UTTypeConformsTo","roleHeading":"Property List Key","platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"5.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"5.0","name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"10.7","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"UTTypeConformsTo"}],"title":"UTTypeConformsTo","role":"symbol","modules":[{"name":"Bundle Resources"}]},"kind":"symbol","references":{"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo":{"name":"UTTypeConformsTo","abstract":[{"text":"The Uniform Type Identifier types that this type conforms to.","type":"text"}],"role":"symbol","ideTitle":"Conforms to UTIs","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeconformsto","navigatorTitle":[{"kind":"identifier","text":"UTTypeConformsTo"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo","kind":"symbol","title":"UTTypeConformsTo"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","title":"Information Property List","abstract":[{"type":"text","text":"A resource containing key-value pairs that identify and configure a bundle."}],"kind":"symbol","role":"symbol","url":"/documentation/bundleresources/information-property-list","name":"Information Property List","navigatorTitle":[{"text":"Information Property List","kind":"identifier"}],"type":"topic","titleStyle":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification":{"name":"UTTypeTagSpecification","abstract":[{"text":"A dictionary defining one or more equivalent type identifiers.","type":"text"}],"role":"symbol","ideTitle":"Equivalent Types","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypetagspecification","navigatorTitle":[{"kind":"identifier","text":"UTTypeTagSpecification"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification","kind":"symbol","title":"UTTypeTagSpecification"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","role":"overview","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles":{"name":"UTTypeIconFiles","abstract":[{"text":"One or more bundle icon resources to associate with this type.","type":"text"}],"role":"symbol","ideTitle":"Icon file names","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeiconfiles","navigatorTitle":[{"text":"UTTypeIconFiles","kind":"identifier"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles","kind":"symbol","title":"UTTypeIconFiles"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL":{"name":"UTTypeReferenceURL","abstract":[{"text":"The webpage for a reference document that describes this type.","type":"text"}],"role":"symbol","ideTitle":"Reference URL","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypereferenceurl","navigatorTitle":[{"kind":"identifier","text":"UTTypeReferenceURL"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL","kind":"symbol","title":"UTTypeReferenceURL"},"doc://com.apple.bundleresources/documentation/BundleResources":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources","title":"Bundle Resources","abstract":[{"type":"text","text":"Resources located in an app, framework, or plugin bundle."}],"kind":"symbol","role":"collection","url":"/documentation/bundleresources","type":"topic"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile":{"name":"UTTypeIconFile","abstract":[{"text":"The bundle icon resource to associate with this type.","type":"text"}],"role":"symbol","ideTitle":"Icon file name","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeiconfile","navigatorTitle":[{"kind":"identifier","text":"UTTypeIconFile"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile","kind":"symbol","title":"UTTypeIconFile"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier":{"title":"UTTypeIdentifier","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UTTypeIdentifier"}],"url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypeidentifier","name":"UTTypeIdentifier","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier","abstract":[{"type":"text","text":"The Uniform Type Identifier to assign to this type."}],"role":"symbol","titleStyle":"symbol","kind":"symbol","ideTitle":"Identifier"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription":{"kind":"symbol","role":"symbol","titleStyle":"symbol","ideTitle":"Description","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations/uttypedescription","name":"UTTypeDescription","title":"UTTypeDescription","abstract":[{"text":"A description for this type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"UTTypeDescription"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations":{"name":"UTExportedTypeDeclarations","abstract":[{"text":"The uniform type identifiers owned and exported by the app.","type":"text"}],"role":"symbol","ideTitle":"Exported Type UTIs","titleStyle":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/utexportedtypedeclarations","navigatorTitle":[{"kind":"identifier","text":"UTExportedTypeDeclarations"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations","kind":"symbol","title":"UTExportedTypeDeclarations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"introducedAt":"5.0","beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"5.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"10.7","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Property List Key","path":"/metadata/roleHeading"},{"op":"replace","value":"UTTypeConformsTo","path":"/metadata/title"},{"op":"replace","value":"typealias","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UTTypeConformsTo"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Property-List-Keys","title":"Property List Keys","identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeDescription","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFile","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIconFiles","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeIdentifier","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeReferenceURL","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeTagSpecification"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":"UTTypeConformsTo","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeConformsTo/title","op":"replace"},{"value":[{"text":"UTTypeConformsTo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeConformsTo/navigatorTitle","op":"replace"},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title","op":"replace","value":"Information Property List"},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Information Property List"}]},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeTagSpecification/title","op":"replace","value":"UTTypeTagSpecification"},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeTagSpecification/navigatorTitle","op":"replace","value":[{"text":"UTTypeTagSpecification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFiles/title","op":"replace","value":"UTTypeIconFiles"},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFiles/navigatorTitle","op":"replace","value":[{"text":"UTTypeIconFiles","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeReferenceURL/title","op":"replace","value":"UTTypeReferenceURL"},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeReferenceURL/navigatorTitle","op":"replace","value":[{"text":"UTTypeReferenceURL","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFile/title","op":"replace","value":"UTTypeIconFile"},{"op":"replace","value":[{"text":"UTTypeIconFile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIconFile/navigatorTitle"},{"op":"replace","value":"UTTypeIdentifier","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIdentifier/title"},{"op":"replace","value":[{"kind":"identifier","text":"UTTypeIdentifier"}],"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeIdentifier/navigatorTitle"},{"op":"replace","value":"UTTypeDescription","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeDescription/title"},{"op":"replace","value":[{"text":"UTTypeDescription","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations~1UTTypeDescription/navigatorTitle"},{"op":"replace","value":"UTExportedTypeDeclarations","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/title"},{"op":"replace","value":[{"kind":"identifier","text":"UTExportedTypeDeclarations"}],"path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UTExportedTypeDeclarations/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}