{
  "abstract": [
    {
      "text": "The destination file is not writable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/fileWritable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC25ICReturnDownloadErrorCodeLeV12fileWritableSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fileWritable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC25ICReturnDownloadErrorCodeLeV",
        "text": "ICReturnDownloadError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ICReturnDownloadErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "fileWritable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fileWritable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC25ICReturnDownloadErrorCodeLeV",
              "text": "ICReturnDownloadError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ICReturnDownloadErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError": {
      "abstract": [
        {
          "text": "A download error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnDownloadError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnDownloadError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/fileWritable": {
      "abstract": [
        {
          "text": "The destination file is not writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnDownloadErrorCodeLeV",
          "text": "ICReturnDownloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnDownloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/fileWritable",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileWritable",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror/filewritable"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/pathInvalid": {
      "abstract": [
        {
          "text": "The destination path is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnDownloadErrorCodeLeV",
          "text": "ICReturnDownloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnDownloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/pathInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "pathInvalid",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror/pathinvalid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/pathInvalid",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/title",
          "value": "ICReturnDownloadErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturndownloaderror/filewritable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
