{
  "abstract": [
    {
      "text": "Constants that describe the output type, which is an indication of the type of content the app is drawing or providing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIPrintInfoOutputType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OutputType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OutputType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIPrintInfo.OutputType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OutputType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use these constants when setting the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/outputType-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a ",
              "type": "text"
            },
            {
              "code": "UIPrintInfo",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo": {
      "abstract": [
        {
          "text": "Information about a print job that the system uses when it prints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Duplex-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the duplex mode of a selected printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Duplex"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Duplex-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Duplex"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.Duplex",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/duplex-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Orientation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the orientation of printing on a page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Orientation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.Orientation",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/orientation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the output type, which is an indication of the type of content the app is drawing or providing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OutputType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OutputType"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general": {
      "abstract": [
        {
          "text": "Specifies that the printed content consists of mixed text, graphics, and images. The default paper is Letter, A4, or similar locale-specific designation. Output is normal quality, duplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "general"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputGeneral"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.general",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/general"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale": {
      "abstract": [
        {
          "text": "Specifies that the printed content is grayscale. Set the output type to this value when your printable content contains no color—for example, it’s black text only. The default paper is Letter/A4. Output is grayscale quality, duplex. This content type can produce a performance improvement in some cases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grayscale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputGrayscale"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.grayscale",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/grayscale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo": {
      "abstract": [
        {
          "text": "Specifies that the printed content consists of black-and-white or color images. The default paper is 4x6, A6, or similar locale-specific designation. Output is high quality, simplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputPhoto"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.photo",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/photo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale": {
      "abstract": [
        {
          "text": "Specifies that the printed content is a grayscale image. Set the output type to this value when your printable content contains no color—for example, it’s black text only. The default paper is Letter/A4. Output is high quality grayscale, duplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoGrayscale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputPhotoGrayscale"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.photoGrayscale",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/photograyscale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/duplex-swift.property": {
      "abstract": [
        {
          "text": "The duplex mode to use for the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInfo",
          "text": "UIPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrintInfoDuplex",
          "text": "Duplex"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/duplex-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duplex"
        }
      ],
      "role": "symbol",
      "title": "duplex",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/duplex-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/jobName": {
      "abstract": [
        {
          "text": "The name of the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/jobName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jobName"
        }
      ],
      "role": "symbol",
      "title": "jobName",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/jobname"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/orientation-swift.property": {
      "abstract": [
        {
          "text": "The orientation of the printed content, portrait or landscape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInfo",
          "text": "UIPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrintInfoOrientation",
          "text": "Orientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/orientation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orientation"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/orientation-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/outputType-swift.property": {
      "abstract": [
        {
          "text": "The kind of printable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInfo",
          "text": "UIPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrintInfoOutputType",
          "text": "OutputType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/outputType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputType"
        }
      ],
      "role": "symbol",
      "title": "outputType",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/printerID": {
      "abstract": [
        {
          "text": "An identifier of the printer to use for the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/printerID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerID"
        }
      ],
      "role": "symbol",
      "title": "printerID",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/printerid"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-print-job-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/duplex-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Duplex-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/jobName",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/orientation-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Orientation-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/outputType-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/printerID"
      ],
      "title": "Managing print-job attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrintInfoOutputType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-print-job-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/duplex-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Duplex-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/jobName",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/orientation-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/Orientation-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/outputType-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/printerID"
              ],
              "title": "Managing print-job attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPrintInfoOutputType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1jobName/title",
          "value": "jobName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1jobName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jobName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photoGrayscale/title",
          "value": "UIPrintInfoOutputPhotoGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photoGrayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputPhotoGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1grayscale/title",
          "value": "UIPrintInfoOutputGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1grayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1orientation-swift.property/title",
          "value": "orientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1orientation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1duplex-swift.property/title",
          "value": "duplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1duplex-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1general/title",
          "value": "UIPrintInfoOutputGeneral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1general/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputGeneral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1printerID/title",
          "value": "printerID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1printerID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printerID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photo/title",
          "value": "UIPrintInfoOutputPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Duplex-swift.enum/title",
          "value": "UIPrintInfoDuplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Duplex-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoDuplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Duplex-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoDuplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Orientation-swift.enum/title",
          "value": "UIPrintInfoOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Orientation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1Orientation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1outputType-swift.property/title",
          "value": "outputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1outputType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/title",
          "value": "UIPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/title",
          "value": "UIPrintInfoOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprintinfo/outputtype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprintinfo/outputtype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
