{
  "abstract": [
    {
      "text": "Error codes returned by the location manager object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object delivered to the delegate use these error codes for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the error object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct": {
      "abstract": [
        {
          "text": "A Core Location error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "role": "symbol",
      "title": "CLError",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes returned by the location manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredAccuracyTooLow": {
      "abstract": [
        {
          "text": "A constant that indicates deferred mode isn’t supported for the requested accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredAccuracyTooLow"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredAccuracyTooLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDeferredAccuracyTooLow"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.deferredAccuracyTooLow",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/deferredaccuracytoolow"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredCanceled": {
      "abstract": [
        {
          "text": "A constant that indicates your app or the location manager canceled the request for deferred updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredCanceled"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDeferredCanceled"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.deferredCanceled",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/deferredcanceled"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredDistanceFiltered": {
      "abstract": [
        {
          "text": "A constant that indicates deferred mode doesn’t support distance filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredDistanceFiltered"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredDistanceFiltered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDeferredDistanceFiltered"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.deferredDistanceFiltered",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/deferreddistancefiltered"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredFailed": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager didn’t enter deferred mode for an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredFailed"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDeferredFailed"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.deferredFailed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/deferredfailed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredNotUpdatingLocation": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager didn’t enter deferred mode because location updates were already disabled or paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredNotUpdatingLocation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredNotUpdatingLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDeferredNotUpdatingLocation"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.deferredNotUpdatingLocation",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/deferrednotupdatinglocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the location service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDenied"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.denied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/denied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeCanceled": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeCanceled"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorGeocodeCanceled"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.geocodeCanceled",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/geocodecanceled"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundNoResult": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request yielded no result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeFoundNoResult"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundNoResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorGeocodeFoundNoResult"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.geocodeFoundNoResult",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/geocodefoundnoresult"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundPartialResult": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request yielded a partial result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeFoundPartialResult"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundPartialResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorGeocodeFoundPartialResult"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.geocodeFoundPartialResult",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/geocodefoundpartialresult"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager can’t determine the heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingFailure"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorHeadingFailure"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.headingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/headingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/historicalLocationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "historicalLocationError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/historicalLocationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorHistoricalLocationError"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.historicalLocationError",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/historicallocationerror"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager was unable to obtain a location value right now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationUnknown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorLocationUnknown"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.locationUnknown",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/locationunknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network": {
      "abstract": [
        {
          "text": "A constant that indicates the network was unavailable or a network error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "network"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorNetwork"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.network",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/network"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined": {
      "abstract": [
        {
          "text": "A constant that indicates the user didn’t grant the requested temporary authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptDeclined"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorPromptDeclined"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.promptDeclined",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/promptdeclined"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates a general ranging error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingFailure"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRangingFailure"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.rangingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/rangingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable": {
      "abstract": [
        {
          "text": "A constant that indicates ranging is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingUnavailable"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRangingUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.rangingUnavailable",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/rangingunavailable"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringDenied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the region monitoring service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringDenied"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRegionMonitoringDenied"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.regionMonitoringDenied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/regionmonitoringdenied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager failed to monitor a registered region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringFailure"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRegionMonitoringFailure"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.regionMonitoringFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/regionmonitoringfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringResponseDelayed": {
      "abstract": [
        {
          "text": "A constant that indicates Core Location will deliver events but they may be delayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringResponseDelayed"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringResponseDelayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRegionMonitoringResponseDelayed"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.regionMonitoringResponseDelayed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/regionmonitoringresponsedelayed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringSetupDelayed": {
      "abstract": [
        {
          "text": "A constant that indicates Core Location failed to initialize the region monitoring feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringSetupDelayed"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringSetupDelayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRegionMonitoringSetupDelayed"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.regionMonitoringSetupDelayed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/regionmonitoringsetupdelayed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the location service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied",
      "kind": "symbol",
      "role": "symbol",
      "title": "denied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/denied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager can’t determine the heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "headingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/headingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager was unable to obtain a location value right now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "locationUnknown",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/locationunknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network": {
      "abstract": [
        {
          "text": "A constant that indicates the network was unavailable or a network error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "network"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network",
      "kind": "symbol",
      "role": "symbol",
      "title": "network",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/network"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined": {
      "abstract": [
        {
          "text": "A constant that indicates the user didn’t grant the requested temporary authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptDeclined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined",
      "kind": "symbol",
      "role": "symbol",
      "title": "promptDeclined",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/promptdeclined"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates a general ranging error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "rangingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/rangingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable": {
      "abstract": [
        {
          "text": "A constant that indicates ranging is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "rangingUnavailable",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/rangingunavailable"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code": {
      "abstract": [
        {
          "text": "The error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code",
      "kind": "symbol",
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/foundation/nserror/1409165-code"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-general-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure"
      ],
      "title": "Getting general errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-general-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure"
      ],
      "title": "Getting general errors"
    },
    {
      "anchor": "Getting-region-monitoring-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringDenied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringSetupDelayed",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringResponseDelayed"
      ],
      "title": "Getting region monitoring errors"
    },
    {
      "anchor": "Getting-geocoding-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeCanceled",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundNoResult",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundPartialResult"
      ],
      "title": "Getting geocoding errors"
    },
    {
      "anchor": "Getting-deferred-location-update-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredFailed",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredCanceled",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredAccuracyTooLow",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredDistanceFiltered",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredNotUpdatingLocation"
      ],
      "title": "Getting deferred location update errors"
    },
    {
      "anchor": "Enumeration-cases",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/historicalLocationError"
      ],
      "title": "Enumeration cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-general-errors",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure"
              ],
              "title": "Getting general errors"
            },
            {
              "anchor": "Getting-region-monitoring-errors",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringDenied",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringFailure",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringSetupDelayed",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/regionMonitoringResponseDelayed"
              ],
              "title": "Getting region monitoring errors"
            },
            {
              "anchor": "Getting-geocoding-errors",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeCanceled",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundNoResult",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/geocodeFoundPartialResult"
              ],
              "title": "Getting geocoding errors"
            },
            {
              "anchor": "Getting-deferred-location-update-errors",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredFailed",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredCanceled",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredAccuracyTooLow",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredDistanceFiltered",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/deferredNotUpdatingLocation"
              ],
              "title": "Getting deferred location update errors"
            },
            {
              "anchor": "Enumeration-cases",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/historicalLocationError"
              ],
              "title": "Enumeration cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingFailure/title",
          "value": "kCLErrorRangingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRangingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredCanceled/title",
          "value": "kCLErrorDeferredCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDeferredCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingUnavailable/title",
          "value": "kCLErrorRangingUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRangingUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1network/title",
          "value": "kCLErrorNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1network/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1headingFailure/title",
          "value": "kCLErrorHeadingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1headingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorHeadingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringResponseDelayed/title",
          "value": "kCLErrorRegionMonitoringResponseDelayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringResponseDelayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRegionMonitoringResponseDelayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringFailure/title",
          "value": "kCLErrorRegionMonitoringFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRegionMonitoringFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1denied/title",
          "value": "kCLErrorDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredFailed/title",
          "value": "kCLErrorDeferredFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDeferredFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeCanceled/title",
          "value": "kCLErrorGeocodeCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorGeocodeCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringDenied/title",
          "value": "kCLErrorRegionMonitoringDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRegionMonitoringDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredAccuracyTooLow/title",
          "value": "kCLErrorDeferredAccuracyTooLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredAccuracyTooLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDeferredAccuracyTooLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringSetupDelayed/title",
          "value": "kCLErrorRegionMonitoringSetupDelayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1regionMonitoringSetupDelayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRegionMonitoringSetupDelayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/title",
          "value": "CLError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeFoundNoResult/title",
          "value": "kCLErrorGeocodeFoundNoResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeFoundNoResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorGeocodeFoundNoResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1historicalLocationError/title",
          "value": "kCLErrorHistoricalLocationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1historicalLocationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorHistoricalLocationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredDistanceFiltered/title",
          "value": "kCLErrorDeferredDistanceFiltered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredDistanceFiltered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDeferredDistanceFiltered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1locationUnknown/title",
          "value": "kCLErrorLocationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1locationUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorLocationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredNotUpdatingLocation/title",
          "value": "kCLErrorDeferredNotUpdatingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1deferredNotUpdatingLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDeferredNotUpdatingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1promptDeclined/title",
          "value": "kCLErrorPromptDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1promptDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorPromptDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeFoundPartialResult/title",
          "value": "kCLErrorGeocodeFoundPartialResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1geocodeFoundPartialResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorGeocodeFoundPartialResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/clerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
