{
  "abstract": [
    {
      "text": "Sets the detail view for the list content from view builder closures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-8ml1c"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SharedWithYou",
    "externalID": "s:So19SWCollaborationViewC13SharedWithYouE09setDetailB11ListContentyyxyXE7SwiftUI0B0RzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setDetailViewListContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "ListContent"
      },
      {
        "kind": "text",
        "text": ">(() -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "ListContent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setDetailViewListContent(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setDetailViewListContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "ListContent"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV",
              "kind": "attribute",
              "preciseIdentifier": "s:7SwiftUI11ViewBuilderV",
              "text": "ViewBuilder"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "detailViewListContent"
            },
            {
              "kind": "text",
              "text": ": () -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "ListContent"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "ListContent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI4ViewP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP",
              "text": "View"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "ListContent",
                  "type": "codeVoice"
                },
                {
                  "text": " view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "detailViewListContent"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView": {
      "abstract": [
        {
          "text": "A view that contains the collaboration content and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationView"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationView"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationView",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swcollaborationview"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setContent(_:)": {
      "abstract": [
        {
          "text": "Sets the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setContent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setContentView:"
        }
      ],
      "role": "symbol",
      "title": "setContent(_:)",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swcollaborationview/setcontent(_:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-88gy5": {
      "abstract": [
        {
          "text": "Sets the detail view for the list content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDetailViewListContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ListContent"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "ListContent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-88gy5",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDetailViewListContent(_:)",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swcollaborationview/setdetailviewlistcontent(_:)-88gy5"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-8ml1c": {
      "abstract": [
        {
          "text": "Sets the detail view for the list content from view builder closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDetailViewListContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ListContent"
        },
        {
          "kind": "text",
          "text": ">(() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "ListContent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-8ml1c",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDetailViewListContent(_:)",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swcollaborationview/setdetailviewlistcontent(_:)-8ml1c"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setShowManageButton(_:)": {
      "abstract": [
        {
          "text": "A Boolean value the system uses to show or hide the default manage-participants button in the collaboration popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setShowManageButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setShowManageButton(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShowManageButton:"
        }
      ],
      "role": "symbol",
      "title": "setShowManageButton(_:)",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swcollaborationview/setshowmanagebutton(_:)"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs views from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ViewBuilder"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ViewBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/ViewBuilder"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI4ViewP": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI4ViewP",
      "kind": "symbol",
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/SwiftUI/View"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-view-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setContent(_:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setDetailViewListContent(_:)-88gy5",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWCollaborationView/setShowManageButton(_:)"
      ],
      "title": "Setting view attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView/title",
          "value": "SWCollaborationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView~1setContent(_:)/title",
          "value": "setContentView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView~1setContent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setContentView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView~1setShowManageButton(_:)/title",
          "value": "setShowManageButton:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWCollaborationView~1setShowManageButton(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setShowManageButton:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swcollaborationview/setdetailviewlistcontent(_:)-8ml1c"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
