{"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.15"}],"symbolKind":"property","externalID":"c:objc(cs)NSCollectionLayoutEdgeSpacing(py)bottom","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"bottom","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"bottom"}]},"seeAlsoSections":[{"title":"Getting the edge spacing","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing"],"anchor":"Getting-the-edge-spacing"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscollectionlayoutedgespacing/bottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscollectionlayoutedgespacing/bottom"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom","interfaceLanguage":"swift"},"abstract":[{"text":"The bottom edge spacing value.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing":{"title":"NSCollectionLayoutEdgeSpacing","navigatorTitle":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing","role":"symbol","url":"/documentation/appkit/nscollectionlayoutedgespacing","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that defines the space around the edges of items in a collection view."}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading":{"abstract":[{"text":"The leading edge spacing value.","type":"text"}],"navigatorTitle":[{"text":"leading","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","url":"/documentation/appkit/nscollectionlayoutedgespacing/leading","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leading","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"leading"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top":{"abstract":[{"text":"The top edge spacing value.","type":"text"}],"navigatorTitle":[{"text":"top","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","url":"/documentation/appkit/nscollectionlayoutedgespacing/top","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"top"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing":{"abstract":[{"type":"text","text":"An object that defines the space between or around items in a collection view."}],"url":"/documentation/appkit/nscollectionlayoutspacing","kind":"symbol","role":"symbol","title":"NSCollectionLayoutSpacing","navigatorTitle":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSpacing","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom":{"type":"topic","role":"symbol","title":"bottom","url":"/documentation/appkit/nscollectionlayoutedgespacing/bottom","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom","kind":"symbol","abstract":[{"text":"The bottom edge spacing value.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing":{"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutedgespacing/trailing","title":"trailing","navigatorTitle":[{"text":"trailing","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"The trailing edge spacing value.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"10.15","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"bottom","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bottom"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Getting-the-edge-spacing","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing"],"title":"Getting the edge spacing","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"NSCollectionLayoutEdgeSpacing","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/title"},{"value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/fragments"},{"value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/navigatorTitle"},{"value":"leading","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1leading/title"},{"value":[{"text":"leading","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1leading/fragments"},{"value":"top","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1top/title"},{"value":[{"text":"top","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1top/fragments"},{"value":"NSCollectionLayoutSpacing","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/title"},{"value":[{"kind":"identifier","text":"NSCollectionLayoutSpacing"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/fragments"},{"value":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/navigatorTitle"},{"value":"bottom","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1bottom/title","op":"replace"},{"value":[{"kind":"identifier","text":"bottom"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1bottom/fragments","op":"replace"},{"value":"trailing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1trailing/title","op":"replace"},{"value":[{"kind":"identifier","text":"trailing"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1trailing/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}