{
  "abstract": [
    {
      "text": "Authentication could not start because there was no paired companion device nearby.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LAError@LAErrorCompanionNotAvailable",
    "fragments": [
      {
        "kind": "identifier",
        "text": "LAErrorCompanionNotAvailable"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAErrorCompanionNotAvailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "LAErrorCompanionNotAvailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "LAErrorCompanionNotAvailable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable": {
      "abstract": [
        {
          "text": "Authentication could not start because there was no paired companion device nearby.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorCompanionNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorCompanionNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorcompanionnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/title",
          "value": "LAError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laerror-c.enum/laerrorcompanionnotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
