{
  "abstract": [
    {
      "text": "Biometry is locked because there were too many failed attempts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LAError@LAErrorBiometryLockout",
    "fragments": [
      {
        "kind": "identifier",
        "text": "LAErrorBiometryLockout"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAErrorBiometryLockout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "LAErrorBiometryLockout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "LAErrorBiometryLockout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A passcode is now required to unlock biometry. Try the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " policy instead to allow use of a passcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryLockout"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotEnrolled"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but the paired accessory isn’t connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryDisconnected"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryDisconnected"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.biometryDisconnected",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrydisconnected"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but no accessory is paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotPaired"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotPaired"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.biometryNotPaired",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrynotpaired"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout": {
      "abstract": [
        {
          "text": "Touch ID is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDLockout"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDLockout"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidlockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable": {
      "abstract": [
        {
          "text": "Touch ID is not available on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled Touch ID fingers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotEnrolled"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidnotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication": {
      "abstract": [
        {
          "text": "User authentication with biometry, Apple Watch, or the device passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthentication"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthentication"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthentication",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthentication"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Biometry-failure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled"
      ],
      "title": "Biometry failure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDLockout/title",
          "value": "LAErrorTouchIDLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotAvailable/title",
          "value": "LAErrorTouchIDNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotEnrolled/title",
          "value": "LAErrorTouchIDNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthentication/title",
          "value": "LAPolicyDeviceOwnerAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryNotPaired/title",
          "value": "LAErrorBiometryNotPaired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryNotPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorBiometryNotPaired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryDisconnected/title",
          "value": "LAErrorBiometryDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorBiometryDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/title",
          "value": "LAError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laerror-c.enum/laerrorbiometrylockout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
