{
  "abstract": [
    {
      "text": "If the language of the audio track differs from the system locale, then captions matching the system locale should be displayed (if available). If the language of the audio and the language of the system locale match, no captions are shown.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/automatic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MACaptionAppearanceDisplayType@kMACaptionAppearanceDisplayTypeAutomatic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "automatic"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMACaptionAppearanceDisplayTypeAutomatic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MACaptionAppearanceDisplayType.automatic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automatic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType": {
      "abstract": [
        {
          "text": "A value that specifies the type of captions to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDisplayType"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDisplayType"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDisplayType",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedisplaytype"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/alwaysOn": {
      "abstract": [
        {
          "text": "The most robust available captioning track should always be displayed, whether subtitles, CC, or SDH. This option is selected by a switch labeled “Closed Captions + SDH” (on the Subtitles & Captioning page of iOS) and “Prefer Closed Captions and SDH” checkbox (on the Captions pane of the Accessibility options in macOS).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alwaysOn"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/alwaysOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceDisplayTypeAlwaysOn"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDisplayType.alwaysOn",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedisplaytype/alwayson"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/automatic": {
      "abstract": [
        {
          "text": "If the language of the audio track differs from the system locale, then captions matching the system locale should be displayed (if available). If the language of the audio and the language of the system locale match, no captions are shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceDisplayTypeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDisplayType.automatic",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedisplaytype/automatic"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/forcedOnly": {
      "abstract": [
        {
          "text": "Do not display captions unless they are forced for translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forcedOnly"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/forcedOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceDisplayTypeForcedOnly"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDisplayType.forcedOnly",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedisplaytype/forcedonly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/forcedOnly",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/alwaysOn"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMACaptionAppearanceDisplayTypeAutomatic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceDisplayTypeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/forcedOnly",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType/alwaysOn"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMACaptionAppearanceDisplayTypeAutomatic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1automatic/title",
          "value": "kMACaptionAppearanceDisplayTypeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceDisplayTypeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1alwaysOn/title",
          "value": "kMACaptionAppearanceDisplayTypeAlwaysOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1alwaysOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceDisplayTypeAlwaysOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/title",
          "value": "MACaptionAppearanceDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1forcedOnly/title",
          "value": "kMACaptionAppearanceDisplayTypeForcedOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType~1forcedOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceDisplayTypeForcedOnly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancedisplaytype/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancedisplaytype/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
