{
  "abstract": [
    {
      "text": "A 16-bit, little endian format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSBitmapFormat@NSBitmapFormatSixteenBitLittleEndian",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sixteenBitLittleEndian"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
        "text": "NSBitmapImageRep"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSBitmapFormat",
        "text": "Format"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBitmapFormatSixteenBitLittleEndian"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "sixteenBitLittleEndian"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sixteenBitLittleEndian"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
              "text": "NSBitmapImageRep"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSBitmapFormat",
              "text": "Format"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep": {
      "abstract": [
        {
          "text": "An object that renders an image from bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format": {
      "abstract": [
        {
          "text": "Constants that represent bitmap component formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep.Format",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst": {
      "abstract": [
        {
          "text": "A format where the alpha value comes first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatAlphaFirst"
        }
      ],
      "role": "symbol",
      "title": "alphaFirst",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/alphafirst"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied": {
      "abstract": [
        {
          "text": "A format where alpha values are not premultiplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaNonpremultiplied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatAlphaNonpremultiplied"
        }
      ],
      "role": "symbol",
      "title": "alphaNonpremultiplied",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/alphanonpremultiplied"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples": {
      "abstract": [
        {
          "text": "A format where samples are specified using floating-point numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatingPointSamples"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatFloatingPointSamples"
        }
      ],
      "role": "symbol",
      "title": "floatingPointSamples",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/floatingpointsamples"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian": {
      "abstract": [
        {
          "text": "A 16-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sixteenBitBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatSixteenBitBigEndian"
        }
      ],
      "role": "symbol",
      "title": "sixteenBitBigEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/sixteenbitbigendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian": {
      "abstract": [
        {
          "text": "A 16-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sixteenBitLittleEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatSixteenBitLittleEndian"
        }
      ],
      "role": "symbol",
      "title": "sixteenBitLittleEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/sixteenbitlittleendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian": {
      "abstract": [
        {
          "text": "A 32-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyTwoBitBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatThirtyTwoBitBigEndian"
        }
      ],
      "role": "symbol",
      "title": "thirtyTwoBitBigEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/thirtytwobitbigendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian": {
      "abstract": [
        {
          "text": "A 32-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyTwoBitLittleEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatThirtyTwoBitLittleEndian"
        }
      ],
      "role": "symbol",
      "title": "thirtyTwoBitLittleEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/thirtytwobitlittleendian"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBitmapFormatSixteenBitLittleEndian"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatSixteenBitLittleEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSBitmapFormatSixteenBitLittleEndian"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitBigEndian/title",
          "value": "NSBitmapFormatSixteenBitBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatSixteenBitBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1floatingPointSamples/title",
          "value": "NSBitmapFormatFloatingPointSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1floatingPointSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatFloatingPointSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitLittleEndian/title",
          "value": "NSBitmapFormatSixteenBitLittleEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitLittleEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatSixteenBitLittleEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaFirst/title",
          "value": "NSBitmapFormatAlphaFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatAlphaFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/title",
          "value": "NSBitmapFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitLittleEndian/title",
          "value": "NSBitmapFormatThirtyTwoBitLittleEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitLittleEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatThirtyTwoBitLittleEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/title",
          "value": "NSBitmapImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitBigEndian/title",
          "value": "NSBitmapFormatThirtyTwoBitBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatThirtyTwoBitBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaNonpremultiplied/title",
          "value": "NSBitmapFormatAlphaNonpremultiplied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaNonpremultiplied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatAlphaNonpremultiplied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/format/sixteenbitlittleendian"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/format/sixteenbitlittleendian"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
