{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAError",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/RawRepresentable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SafetyKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RawRepresentable Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit": {
      "abstract": [
        {
          "text": "Detect and respond to car crash events in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SafetyKit",
      "type": "topic",
      "url": "/documentation/safetykit"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAError": {
      "abstract": [
        {
          "text": "An error reported by SafetyKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAError"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAError"
        }
      ],
      "role": "symbol",
      "title": "SAError",
      "type": "topic",
      "url": "/documentation/safetykit/saerror"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code": {
      "abstract": [
        {
          "text": "Codes for identifying errors in SafetyKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SAError.Code",
      "type": "topic",
      "url": "/documentation/safetykit/saerror/code"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hash(into:)": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6HasherV",
          "text": "Hasher"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hash(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/safetykit/saerror/code/hash(into:)"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hashValue": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hashValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/safetykit/saerror/code/hashvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hashValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAError/Code/hash(into:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAError~1Code/title",
          "value": "SAErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safetykit/saerror/code/rawrepresentable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
