{
  "abstract": [
    {
      "text": "A type that defines a callback that receives a buffer of generated speech.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@T@AVSpeechSynthesizerBufferCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BufferCallback"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BufferCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AVSpeechSynthesizer.BufferCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BufferCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioBuffer",
              "text": "AVAudioBuffer"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer": {
      "abstract": [
        {
          "text": "An object that represents a buffer of audio data with a format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBuffer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioBuffer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioBuffer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiobuffer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer": {
      "abstract": [
        {
          "text": "An object that produces synthesized speech from text utterances and enables monitoring or controlling of ongoing speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback": {
      "abstract": [
        {
          "text": "A type that defines a callback that receives a buffer of generated speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BufferCallback"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BufferCallback"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer.BufferCallback",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/buffercallback"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback": {
      "abstract": [
        {
          "text": "A type that defines a callback that receives speech markers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MarkerCallback"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MarkerCallback"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer.MarkerCallback",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/markercallback"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to send synthesized speech to an active call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixToTelephonyUplink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mixToTelephonyUplink"
        }
      ],
      "role": "symbol",
      "title": "mixToTelephonyUplink",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/mixtotelephonyuplink"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels": {
      "abstract": [
        {
          "text": "An array of audio session channels to route generated speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputChannels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSessionChannelDescription",
          "text": "AVAudioSessionChannelDescription"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputChannels"
        }
      ],
      "role": "symbol",
      "title": "outputChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/outputchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the app manages the audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesApplicationAudioSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesApplicationAudioSession"
        }
      ],
      "role": "symbol",
      "title": "usesApplicationAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/usesapplicationaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)": {
      "abstract": [
        {
          "text": "Generates speech for the utterance and invokes the callback with the audio buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toBufferCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerBufferCallback",
          "text": "BufferCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeUtterance:toBufferCallback:"
        }
      ],
      "role": "symbol",
      "title": "write(_:toBufferCallback:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/write(_:tobuffercallback:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)": {
      "abstract": [
        {
          "text": "Generates audio buffers and associated metadata for storage or further speech synthesis processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toBufferCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerBufferCallback",
          "text": "BufferCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toMarkerCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerMarkerCallback",
          "text": "MarkerCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeUtterance:toBufferCallback:toMarkerCallback:"
        }
      ],
      "role": "symbol",
      "title": "write(_:toBufferCallback:toMarkerCallback:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/write(_:tobuffercallback:tomarkercallback:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Directing-speech-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback"
      ],
      "title": "Directing speech output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSpeechSynthesizerBufferCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Directing-speech-output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback"
              ],
              "title": "Directing speech output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*$objc(cs)AVAudioBuffer)",
                    "text": "void (^)(AVAudioBuffer *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVSpeechSynthesizerBufferCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1usesApplicationAudioSession/title",
          "value": "usesApplicationAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1usesApplicationAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesApplicationAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:toMarkerCallback:)/title",
          "value": "writeUtterance:toBufferCallback:toMarkerCallback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:toMarkerCallback:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeUtterance:toBufferCallback:toMarkerCallback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/title",
          "value": "AVAudioBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:)/title",
          "value": "writeUtterance:toBufferCallback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeUtterance:toBufferCallback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/title",
          "value": "AVSpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/title",
          "value": "AVSpeechSynthesizerMarkerCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerMarkerCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerMarkerCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/title",
          "value": "AVSpeechSynthesizerBufferCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1mixToTelephonyUplink/title",
          "value": "mixToTelephonyUplink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1mixToTelephonyUplink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mixToTelephonyUplink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1outputChannels/title",
          "value": "outputChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1outputChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputChannels"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizer/buffercallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizer/buffercallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
