{
  "abstract": [
    {
      "text": "The custom view to display for the accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/customView"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit15UICellAccessoryV23CustomViewConfigurationV06customE0So6UIViewCvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "customView"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIView",
        "text": "UIView"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "customView"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "customView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct": {
      "abstract": [
        {
          "text": "An accessory in a collection view list cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration": {
      "abstract": [
        {
          "text": "Configuration options for a custom accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CustomViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.CustomViewConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/customView": {
      "abstract": [
        {
          "text": "The custom view to display for the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/customView",
      "kind": "symbol",
      "role": "symbol",
      "title": "customView",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/customview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the cell hides the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/isHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/ishidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/maintainsFixedSize": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether to preserve the frame size of the custom view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maintainsFixedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/maintainsFixedSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "maintainsFixedSize",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/maintainsfixedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/placement": {
      "abstract": [
        {
          "text": "The placement for the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV9PlacementO",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/placement",
      "kind": "symbol",
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/reservedLayoutWidth": {
      "abstract": [
        {
          "text": "The layout width that the system reserves for the accessory, and then centers the accessory within.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reservedLayoutWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV15LayoutDimensionO",
          "text": "LayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/reservedLayoutWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "reservedLayoutWidth",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/reservedlayoutwidth"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/tintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/tintColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "tintColor",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/tintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-configuration-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/isHidden",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/placement",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/reservedLayoutWidth",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/tintColor",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration/maintainsFixedSize"
      ],
      "title": "Accessing configuration options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration/customview"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
