{
  "abstract": [
    {
      "text": "Error codes for EventKit errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "EKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError": {
      "abstract": [
        {
          "text": "An EventKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "role": "symbol",
      "title": "EKError",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code": {
      "abstract": [
        {
          "text": "Error codes for EventKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The alarm interval is greater than the recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmGreaterThanRecurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorAlarmGreaterThanRecurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.alarmGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/alarmgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmProximityNotSupported": {
      "abstract": [
        {
          "text": "The source doesn’t allow geofences on alarms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmProximityNotSupported"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmProximityNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorAlarmProximityNotSupported"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.alarmProximityNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/alarmproximitynotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowEvents": {
      "abstract": [
        {
          "text": "The calendar doesn’t allow you to add events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarDoesNotAllowEvents"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarDoesNotAllowEvents"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarDoesNotAllowEvents",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendardoesnotallowevents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowReminders": {
      "abstract": [
        {
          "text": "The calendar doesn’t allow you to add reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarDoesNotAllowReminders"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowReminders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarDoesNotAllowReminders"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarDoesNotAllowReminders",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendardoesnotallowreminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource": {
      "abstract": [
        {
          "text": "You can’t save the calendar without setting a source first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarHasNoSource"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarHasNoSource"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarHasNoSource",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarhasnosource"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarIsImmutable": {
      "abstract": [
        {
          "text": "The calendar is immutable and you can’t modify or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarIsImmutable"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarIsImmutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarIsImmutable"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarIsImmutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarisimmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly": {
      "abstract": [
        {
          "text": "The calendar is read-only and you can’t add events to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarReadOnly"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarReadOnly"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarReadOnly",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarreadonly"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarSourceCannotBeModified": {
      "abstract": [
        {
          "text": "You can’t move the calendar to another source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarSourceCannotBeModified"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarSourceCannotBeModified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarSourceCannotBeModified"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarSourceCannotBeModified",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarsourcecannotbemodified"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted": {
      "abstract": [
        {
          "text": "The event’s end date occurs before its start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datesInverted"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDatesInverted"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.datesInverted",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/datesinverted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The duration of an event is greater than its recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationGreaterThanRecurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDurationGreaterThanRecurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.durationGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/durationgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable": {
      "abstract": [
        {
          "text": "The event isn’t mutable and you can’t save or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventNotMutable"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorEventNotMutable"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.eventNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/eventnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventStoreNotAuthorized": {
      "abstract": [
        {
          "text": "The user hasn’t authorized your app to access events or reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventStoreNotAuthorized"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventStoreNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorEventStoreNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.eventStoreNotAuthorized",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/eventstorenotauthorized"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/init(rawvalue:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFailure"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInternalFailure"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.internalFailure",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/internalfailure"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidEntityType": {
      "abstract": [
        {
          "text": "The entity type is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEntityType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidEntityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvalidEntityType"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invalidEntityType",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invalidentitytype"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidInviteReplyCalendar": {
      "abstract": [
        {
          "text": "The calendar is invalid or nil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidInviteReplyCalendar"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidInviteReplyCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvalidInviteReplyCalendar"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invalidInviteReplyCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invalidinvitereplycalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan": {
      "abstract": [
        {
          "text": "The system encountered an invalid span during a save or deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSpan"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvalidSpan"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invalidSpan",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invalidspan"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved": {
      "abstract": [
        {
          "text": "You can’t move the event because it’s an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitesCannotBeMoved"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvitesCannotBeMoved"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invitesCannotBeMoved",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invitescannotbemoved"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/last": {
      "abstract": [
        {
          "text": "This error is for internal use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "last"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/last",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorLast"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.last",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/last"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar": {
      "abstract": [
        {
          "text": "The event isn’t associated with a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCalendar"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoCalendar"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/nocalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate": {
      "abstract": [
        {
          "text": "The event has no end date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noEndDate"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoEndDate"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noEndDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/noenddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate": {
      "abstract": [
        {
          "text": "The event has no start date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noStartDate"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoStartDate"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noStartDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/nostartdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationCollectionMismatch": {
      "abstract": [
        {
          "text": "The notification collection that contains this notification doesn’t match the collection the system is trying to save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCollectionMismatch"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationCollectionMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNotificationCollectionMismatch"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.notificationCollectionMismatch",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/notificationcollectionmismatch"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection": {
      "abstract": [
        {
          "text": "The notification can’t save because you haven’t added it to a notification collection and saved the collection first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationSavedWithoutCollection"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNotificationSavedWithoutCollection"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.notificationSavedWithoutCollection",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/notificationsavedwithoutcollection"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationsCollectionFlagNotSet": {
      "abstract": [
        {
          "text": "The notification collection doesn’t have the notifications collection flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationsCollectionFlagNotSet"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationsCollectionFlagNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNotificationsCollectionFlagNotSet"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.notificationsCollectionFlagNotSet",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/notificationscollectionflagnotset"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore": {
      "abstract": [
        {
          "text": "The object belongs to a different calendar store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectBelongsToDifferentStore"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorObjectBelongsToDifferentStore"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.objectBelongsToDifferentStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/objectbelongstodifferentstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/osNotSupported": {
      "abstract": [
        {
          "text": "The action isn’t supported on the current operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osNotSupported"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/osNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorOSNotSupported"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.osNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/osnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/priorityIsInvalid": {
      "abstract": [
        {
          "text": "The priority number for the reminder is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priorityIsInvalid"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/priorityIsInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorPriorityIsInvalid"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.priorityIsInvalid",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/priorityisinvalid"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/procedureAlarmsNotMutable": {
      "abstract": [
        {
          "text": "You can’t create or modify procedure alarms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "procedureAlarmsNotMutable"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/procedureAlarmsNotMutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorProcedureAlarmsNotMutable"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.procedureAlarmsNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/procedurealarmsnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/recurringReminderRequiresDueDate": {
      "abstract": [
        {
          "text": "The recurring reminder requires a due date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurringReminderRequiresDueDate"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/recurringReminderRequiresDueDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorRecurringReminderRequiresDueDate"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.recurringReminderRequiresDueDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/recurringreminderrequiresduedate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderAlarmContainsEmailOrUrl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminderAlarmContainsEmailOrUrl"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderAlarmContainsEmailOrUrl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorReminderAlarmContainsEmailOrUrl"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.reminderAlarmContainsEmailOrUrl",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/reminderalarmcontainsemailorurl"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderLocationsNotSupported": {
      "abstract": [
        {
          "text": "The source doesn’t support locations on reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminderLocationsNotSupported"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderLocationsNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorReminderLocationsNotSupported"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.reminderLocationsNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/reminderlocationsnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowCalendarAddDelete": {
      "abstract": [
        {
          "text": "The source doesn’t allow you to add or delete calendars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowCalendarAddDelete"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowCalendarAddDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorSourceDoesNotAllowCalendarAddDelete"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.sourceDoesNotAllowCalendarAddDelete",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/sourcedoesnotallowcalendaradddelete"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowEvents": {
      "abstract": [
        {
          "text": "The source doesn’t allow calendars supporting event entity types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowEvents"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorSourceDoesNotAllowEvents"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.sourceDoesNotAllowEvents",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/sourcedoesnotallowevents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowReminders": {
      "abstract": [
        {
          "text": "The source doesn’t allow calendars supporting reminder entity types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowReminders"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowReminders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorSourceDoesNotAllowReminders"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.sourceDoesNotAllowReminders",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/sourcedoesnotallowreminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceMismatch": {
      "abstract": [
        {
          "text": "The object’s source doesn’t match its container’s source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceMismatch"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorSourceMismatch"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.sourceMismatch",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/sourcemismatch"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence": {
      "abstract": [
        {
          "text": "The event’s start date collides with another occurrence of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateCollidesWithOtherOccurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorStartDateCollidesWithOtherOccurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.startDateCollidesWithOtherOccurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/startdatecollideswithotheroccurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture": {
      "abstract": [
        {
          "text": "The start date is further into the future than the calendar can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateTooFarInFuture"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorStartDateTooFarInFuture"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.startDateTooFarInFuture",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/startdatetoofarinfuture"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/structuredLocationsNotSupported": {
      "abstract": [
        {
          "text": "The source to which this calendar belongs doesn’t support structured locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "structuredLocationsNotSupported"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/structuredLocationsNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorStructuredLocationsNotSupported"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.structuredLocationsNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/structuredlocationsnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the EventKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "EKErrorDomain",
      "type": "topic",
      "url": "/documentation/eventkit/ekerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError",
        "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarSourceCannotBeModified",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarIsImmutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowCalendarAddDelete",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/recurringReminderRequiresDueDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/structuredLocationsNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderLocationsNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmProximityNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowEvents",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowReminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowReminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowEvents",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/priorityIsInvalid",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidEntityType",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/procedureAlarmsNotMutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventStoreNotAuthorized",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/osNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidInviteReplyCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationsCollectionFlagNotSet",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceMismatch",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationCollectionMismatch",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/last"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderAlarmContainsEmailOrUrl"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarSourceCannotBeModified",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarIsImmutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowCalendarAddDelete",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/recurringReminderRequiresDueDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/structuredLocationsNotSupported",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderLocationsNotSupported",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmProximityNotSupported",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowEvents",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarDoesNotAllowReminders",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowReminders",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceDoesNotAllowEvents",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/priorityIsInvalid",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidEntityType",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/procedureAlarmsNotMutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventStoreNotAuthorized",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/osNotSupported",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidInviteReplyCalendar",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationsCollectionFlagNotSet",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/sourceMismatch",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationCollectionMismatch",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/last"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/reminderAlarmContainsEmailOrUrl"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1durationGreaterThanRecurrence/title",
          "value": "EKErrorDurationGreaterThanRecurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1durationGreaterThanRecurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDurationGreaterThanRecurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1objectBelongsToDifferentStore/title",
          "value": "EKErrorObjectBelongsToDifferentStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1objectBelongsToDifferentStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorObjectBelongsToDifferentStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noStartDate/title",
          "value": "EKErrorNoStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1internalFailure/title",
          "value": "EKErrorInternalFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1internalFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInternalFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noCalendar/title",
          "value": "EKErrorNoCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidEntityType/title",
          "value": "EKErrorInvalidEntityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidEntityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvalidEntityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarSourceCannotBeModified/title",
          "value": "EKErrorCalendarSourceCannotBeModified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarSourceCannotBeModified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarSourceCannotBeModified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarDoesNotAllowReminders/title",
          "value": "EKErrorCalendarDoesNotAllowReminders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarDoesNotAllowReminders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarDoesNotAllowReminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateCollidesWithOtherOccurrence/title",
          "value": "EKErrorStartDateCollidesWithOtherOccurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateCollidesWithOtherOccurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorStartDateCollidesWithOtherOccurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationsCollectionFlagNotSet/title",
          "value": "EKErrorNotificationsCollectionFlagNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationsCollectionFlagNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNotificationsCollectionFlagNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1procedureAlarmsNotMutable/title",
          "value": "EKErrorProcedureAlarmsNotMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1procedureAlarmsNotMutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorProcedureAlarmsNotMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarReadOnly/title",
          "value": "EKErrorCalendarReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmGreaterThanRecurrence/title",
          "value": "EKErrorAlarmGreaterThanRecurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmGreaterThanRecurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorAlarmGreaterThanRecurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidSpan/title",
          "value": "EKErrorInvalidSpan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidSpan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvalidSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarDoesNotAllowEvents/title",
          "value": "EKErrorCalendarDoesNotAllowEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarDoesNotAllowEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarDoesNotAllowEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateTooFarInFuture/title",
          "value": "EKErrorStartDateTooFarInFuture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateTooFarInFuture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorStartDateTooFarInFuture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noEndDate/title",
          "value": "EKErrorNoEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/title",
          "value": "EKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventStoreNotAuthorized/title",
          "value": "EKErrorEventStoreNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventStoreNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorEventStoreNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarHasNoSource/title",
          "value": "EKErrorCalendarHasNoSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarHasNoSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarHasNoSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1last/title",
          "value": "EKErrorLast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1last/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorLast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1reminderAlarmContainsEmailOrUrl/title",
          "value": "EKErrorReminderAlarmContainsEmailOrUrl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1reminderAlarmContainsEmailOrUrl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorReminderAlarmContainsEmailOrUrl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidInviteReplyCalendar/title",
          "value": "EKErrorInvalidInviteReplyCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidInviteReplyCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvalidInviteReplyCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationSavedWithoutCollection/title",
          "value": "EKErrorNotificationSavedWithoutCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationSavedWithoutCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNotificationSavedWithoutCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invitesCannotBeMoved/title",
          "value": "EKErrorInvitesCannotBeMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invitesCannotBeMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvitesCannotBeMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarIsImmutable/title",
          "value": "EKErrorCalendarIsImmutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarIsImmutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarIsImmutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1reminderLocationsNotSupported/title",
          "value": "EKErrorReminderLocationsNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1reminderLocationsNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorReminderLocationsNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1datesInverted/title",
          "value": "EKErrorDatesInverted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1datesInverted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDatesInverted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1recurringReminderRequiresDueDate/title",
          "value": "EKErrorRecurringReminderRequiresDueDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1recurringReminderRequiresDueDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorRecurringReminderRequiresDueDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationCollectionMismatch/title",
          "value": "EKErrorNotificationCollectionMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationCollectionMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNotificationCollectionMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowEvents/title",
          "value": "EKErrorSourceDoesNotAllowEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorSourceDoesNotAllowEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowReminders/title",
          "value": "EKErrorSourceDoesNotAllowReminders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowReminders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorSourceDoesNotAllowReminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1priorityIsInvalid/title",
          "value": "EKErrorPriorityIsInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1priorityIsInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorPriorityIsInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventNotMutable/title",
          "value": "EKErrorEventNotMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventNotMutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorEventNotMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1osNotSupported/title",
          "value": "EKErrorOSNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1osNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorOSNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1structuredLocationsNotSupported/title",
          "value": "EKErrorStructuredLocationsNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1structuredLocationsNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorStructuredLocationsNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceMismatch/title",
          "value": "EKErrorSourceMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorSourceMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmProximityNotSupported/title",
          "value": "EKErrorAlarmProximityNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmProximityNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorAlarmProximityNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowCalendarAddDelete/title",
          "value": "EKErrorSourceDoesNotAllowCalendarAddDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1sourceDoesNotAllowCalendarAddDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorSourceDoesNotAllowCalendarAddDelete"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
