{
  "abstract": [
    {
      "text": "The event isn’t mutable and you can’t save or delete it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11EKErrorCodeLeV15eventNotMutableSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eventNotMutable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11EKErrorCodeLeV",
        "text": "EKError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "eventNotMutable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eventNotMutable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11EKErrorCodeLeV",
              "text": "EKError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError": {
      "abstract": [
        {
          "text": "An EventKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "role": "symbol",
      "title": "EKError",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code": {
      "abstract": [
        {
          "text": "Error codes for EventKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The alarm interval is greater than the recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmGreaterThanRecurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "alarmGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/alarmgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource": {
      "abstract": [
        {
          "text": "You can’t save the calendar without setting a source first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarHasNoSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarHasNoSource",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarhasnosource"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly": {
      "abstract": [
        {
          "text": "The calendar is read-only and you can’t add events to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarReadOnly",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarreadonly"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified": {
      "abstract": [
        {
          "text": "You can’t move the calendar to another source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarSourceCannotBeModified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarSourceCannotBeModified",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarsourcecannotbemodified"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted": {
      "abstract": [
        {
          "text": "The event’s end date occurs before its start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datesInverted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted",
      "kind": "symbol",
      "role": "symbol",
      "title": "datesInverted",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/datesinverted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The duration of an event is greater than its recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationGreaterThanRecurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "durationGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/durationgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable": {
      "abstract": [
        {
          "text": "The event isn’t mutable and you can’t save or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventNotMutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "eventNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/eventnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalFailure",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/internalfailure"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan": {
      "abstract": [
        {
          "text": "The system encountered an invalid span during a save or deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSpan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSpan",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invalidspan"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved": {
      "abstract": [
        {
          "text": "You can’t move the event because it’s an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitesCannotBeMoved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "invitesCannotBeMoved",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invitescannotbemoved"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar": {
      "abstract": [
        {
          "text": "The event isn’t associated with a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCalendar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "noCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/nocalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate": {
      "abstract": [
        {
          "text": "The event has no start date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "noEndDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/noenddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate": {
      "abstract": [
        {
          "text": "The event has no end date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "noStartDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/nostartdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore": {
      "abstract": [
        {
          "text": "The object belongs to a different calendar store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectBelongsToDifferentStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectBelongsToDifferentStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/objectbelongstodifferentstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence": {
      "abstract": [
        {
          "text": "The event’s start date collides with another occurrence of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateCollidesWithOtherOccurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "startDateCollidesWithOtherOccurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/startdatecollideswithotheroccurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture": {
      "abstract": [
        {
          "text": "The start date is further into the future than the calendar can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateTooFarInFuture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture",
      "kind": "symbol",
      "role": "symbol",
      "title": "startDateTooFarInFuture",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/startdatetoofarinfuture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekerror/eventnotmutable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
