{
  "abstract": [
    {
      "text": "The delegate for a hosted view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.extensionkit/documentation/ExtensionKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)EXHostViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EXHostViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "ExtensionKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EXHostViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "EXHostViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit": {
      "abstract": [
        {
          "text": "Create executable bundles to extend the functionality of other apps by presenting a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ExtensionKit",
      "type": "topic",
      "url": "/documentation/extensionkit"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/delegate": {
      "abstract": [
        {
          "text": "The connection delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)EXHostViewControllerDelegate",
          "text": "EXHostViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/delegate"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/makeXPCConnection()": {
      "abstract": [
        {
          "text": "Attempts to connect to the extension over XPC.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeXPCConnection"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSXPCConnection",
          "text": "NSXPCConnection"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/makeXPCConnection()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeXPCConnectionWithError:"
        }
      ],
      "role": "symbol",
      "title": "makeXPCConnection()",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller/makexpcconnection()"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate": {
      "abstract": [
        {
          "text": "The delegate for a hosted view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXHostViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXHostViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)": {
      "abstract": [
        {
          "text": "A delegate method the view controller calls when a connection succeeds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostViewControllerDidActivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EXHostViewController",
          "text": "EXHostViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostViewControllerDidActivate:"
        }
      ],
      "role": "symbol",
      "title": "hostViewControllerDidActivate(_:)",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerdidactivate(_:)"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)": {
      "abstract": [
        {
          "text": "A delegate method the host view controller calls when an extension disconnects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostViewControllerWillDeactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EXHostViewController",
          "text": "EXHostViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostViewControllerWillDeactivate:error:"
        }
      ],
      "role": "symbol",
      "title": "hostViewControllerWillDeactivate(_:error:)",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontrollerdelegate/hostviewcontrollerwilldeactivate(_:error:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Connecting-to-the-Extension",
      "generated": true,
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/makeXPCConnection()",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/delegate"
      ],
      "title": "Connecting to the Extension"
    }
  ],
  "topicSections": [
    {
      "anchor": "Delegate-Methods",
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)"
      ],
      "title": "Delegate Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EXHostViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.extensionkit/documentation/ExtensionKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Delegate-Methods",
              "identifiers": [
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerDidActivate(_:)",
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewControllerDelegate/hostViewControllerWillDeactivate(_:error:)"
              ],
              "title": "Delegate Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connecting-to-the-Extension",
              "generated": true,
              "identifiers": [
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/makeXPCConnection()",
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController/delegate"
              ],
              "title": "Connecting to the Extension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EXHostViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/title",
          "value": "EXHostViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerDidActivate(_:)/title",
          "value": "hostViewControllerDidActivate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerDidActivate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerDidActivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1makeXPCConnection()/title",
          "value": "makeXPCConnectionWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1makeXPCConnection()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeXPCConnectionWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerWillDeactivate(_:error:)/title",
          "value": "hostViewControllerWillDeactivate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewControllerDelegate~1hostViewControllerWillDeactivate(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hostViewControllerWillDeactivate:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/extensionkit/exhostviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/extensionkit/exhostviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
